### ISSUE TITLE
AssertionError in ForLoopsTransformer

### ISSUE THREAD

**Issue by tunedal** [JetBrains/kotlin-native#1012]
The code below compiles in Kotlin/JVM and Kotlin/JS:

```kotlin
  fun main(args: Array<String>) {
      val number: Int? = 14
      number?.let { n ->
          for (i in 0..n) {
              println("$i")
          }
      }
  }
```

...but in Kotlin/Native 0.4, it results in the compiler producing a [very long stack trace](https://github.com/JetBrains/kotlin-native/files/1443610/stacktrace.txt) culminating in this error:

    exception: java.lang.AssertionError: Assertion failed
            at org.jetbrains.kotlin.backend.konan.lower.ForLoopsTransformer.castIfNecessary(ForLoopsLowering.kt:132)
    ...

If the nullable Int variable is changed to non-nullable the error goes away and the program compiles.

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/1020
