### ISSUE TITLE
K/N plugin for CLion on Windows

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1015]
Not sure this is valid place to ask, but cannot find more appropriate.

$subj not working on Windows at all, even 'Hello World' example.

**Comment by zxj5470** [comment]
The `konan` is only supported on OSX or linux at present.
Maybe `konan` in Windows hasn't be finished. If you create a project in windows, CMake will show an Error liske `Unsupported host target`
In windows you could compile kotlin-native program in command line `kotlinc`(which is native)
In May,the KN(`kotlinc`) windows version was released after the  linux and osx.
So I think it should be the same.
Just wait a moment.(like a week?)

**Comment by Alefas** [comment]
We are going to support it soon. Sorry for inconveniences.

**Comment by MusaMahmood** [comment]
@Alefas Can you provide an ETA on when this will be available?

**Comment by zxj5470** [comment]
Maybe just in windows CLion can't ...
but you can write in `idea`.(it looks funny, but it just means a commandLine `konanc`can compile it in windows as well.)

My repository [ktnl-lang/ktnl](https://www.github.com/ktnl-lang/ktnl)

(I am attempting to write a simple lisp interpreter by K/N)

**Comment by benbve** [comment]
Is there an update on this. Was hoping 2017.3 would support windows?

**Comment by byersw** [comment]
Can this be a thing yet?

**Comment by ShaddamIV** [comment]
So it's mid-2018 and this thing is not yet resolved? So it is impossible to properly use Kotlin with CLion on Windows?

**Comment by byersw** [comment]
It doesn't work out of the box. At least not a few weeks ago. I tried hacking the make files using some suggestions from https://github.com/JetBrains/kotlin-native/issues/1054

I gave up after spending half a day on it
