### ISSUE TITLE
Mac binaries built with an apparent macOS 10.12 dependency

### ISSUE THREAD

**Issue by darko20** [JetBrains/kotlin-native#1025]
When I build the native compiler and the objc macOS sample from the latest sources (using gradle) the resulting binary will not run on my macOS 10.11 due to a dependency on libate.dylib which is new in 10.12. The konan.properties files stipulate `osVersionMin.osx = 10.11` but maybe that isn't definitive.

**Comment by msink** [comment]
Strange.
Here - https://github.com/msink/hello-kotlin - I tried Mac build on travis osx_image: xcode8 (OS X 10.11), and it runs.

**Comment by darko20** [comment]
That works for me too, but the sample is using the macOS API and importing a framework (it simply opens a native Window). Therein lies the problem, I think somewhere it's linking against the 10.12 macOS SDK but I don't even have that SDK on my machine, that I can tell.

**Comment by msink** [comment]
Ok, so problem is somewhere in platform libs, not in stdlib.

**Comment by darko20** [comment]
I've been trying to track down where the SDK path is set, or an SDK linker option is set, without success.

The other possibility is that the sample's imports

`import platform.AppKit.*`
`import platform.Foundation.*`
`import platform.objc.*`
`import platform.osx.*`

are including 10.12 specific libraries APIs (namely libate), but I would think they wouldn't be linked in unless used, but this could be the source of a bug perhaps.

**Comment by msink** [comment]
https://github.com/JetBrains/kotlin-native/blob/master/klib/src/platform/osx/osx.def
`-late`

**Comment by darko20** [comment]
Thanks, I didn't think to search for that. Hacking that def file will undoubtedly fix it, but the bigger issue is one of handling different SDKs, which I imagine is potentially a issue for all the platforms. Do we need to split the platform directories by SDK or is there already another (cleaner) way to handle this?

**Comment by olonho** [comment]
Yes, this need a serious design discussion. So far let's assume K/N platform libs support 10.12 and later out of the box.

**Comment by VVictorWang** [comment]
I came across this problem too. So is there any solution for this? Hacking `os.def` is not a good way. Thanks.

**Comment by SvyatoslavScherbina** [comment]
We don't have specific plans to support macOS 10.11, which is also not maintained at the moment.
