### ISSUE TITLE
package kotlin.math

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1033]
Now K/N merged 1.2, so can `package kotlin.math` be implemented in stdlib?
Then same code will be compatible with JVM/JS(1.2) and Native.
(and they should be excluded from `platform.posix` if available in stdlib)

**Comment by olonho** [comment]
Looks like a good idea in kotlin.math part, but math functions will not be removed from platform libs, ofc, as platform libs shows what particular system has.

**Comment by msink** [comment]
I'm not sure, but if for example `log(num: Double)` exists in `kotlin.math` and in `platform.posix`, after `import platform.posix.*` which will be used?
posix one can be a little slower because of additional interop layer.

**Comment by olonho** [comment]
As usual in Kotlin, if short names conflict, compiler gives an error, so use more verbose imports or FQ names.

**Comment by olonho** [comment]
v0.5 comes with kotlin.math, so closing the issue.
