### ISSUE TITLE
Performance (again) :)

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1036]
Here - https://github.com/msink/kotlin-pi - I again measure K/N performance, now in pure numberic calculations, no heap should be used.
But performance still approx 50% worse than in C or JVM. Not so drastic, but...

**Comment by pannous** [comment]
75% of C speed is something many other languages can only dream of

**Comment by msink** [comment]
Really 65% (2/3) in this test.
Not so bad, but can be imptoved, I hope.

**Comment by msink** [comment]
Fixed by #1424 - now performance is identical to C (in this test)
