### ISSUE TITLE
Accessing free'd memory should produce an access violation

### ISSUE THREAD

**Issue by MFAshby** [JetBrains/kotlin-native#1038]
When a variable is allocated then freed using the memScoped { } block or other native placement, subsequent attempts to access the value of the variable should produce an exception because the memory has been freed for use elsewhere and no longer represents your variable.

This isn't happening, see sample project https://github.com/MFAshby/memscoped_test 

Running the executable should cause an access violation, but doesn't. Instead, whatever is currently in the memory is read. This is unsafe for a variety of reasons, e.g. reading the value may succeed of fail in an apparently non-deterministic way, depending if that memory has been reused.

Is there a compiler option I am missing that would cause this code to fail as expected?
Otherwise, is there some way for the kotlin representation of the variable to know that it has been freed and is therefore invalid?

**Comment by msink** [comment]
Why it should?
If you use constructs designed for C interop - you get C level of safety - none.
Use pure Kotlin - and you get Kotlin's null safety.

**Comment by MFAshby** [comment]
I would love to use pure kotlin, unfortunately that's not a realistic situation. I don't have the time or skill to write a crypto library or graphics API in pure kotlin from scratch.

If kotlin can make interoperating with C libraries easier and less error-prone, that makes my life as a developer easier and makes it kotlin a more attractive language choice.

**Comment by olonho** [comment]
I would suggest to use memory debugging tools, like http://valgrind.org/ - it will help to find most problems like that. and it works well on binaries produced by Kotlin/Native.

**Comment by MFAshby** [comment]
I'll try valgrind for my problem, thanks.

**Comment by olonho** [comment]
We may consider using MSAN/ASAN in future releases, shall there be sufficient demand.

**Comment by MFAshby** [comment]
Using clion's 'Run with valgrind memcheck' option on my sample project produces the appropriate 'invalid read' warning messages that tell me instantly there is a problem. 
As long as I do this regularly I should avoid this type of error again.
