### ISSUE TITLE
Support gRPC

### ISSUE THREAD

**Issue by wenerme** [JetBrains/kotlin-native#1039]
I really want to use kn for my next project, but kn's interface is too narrow, even c can not call kn's lib,  without interop to other system, it's really hard to using kn for some real things. It's impossible to rewrite whole system in kn.So, I hope grpc is officially supported, some other system can smoothly transfer to kn. Here is a checklist:

* Prerequire
  * Protobuf
    * C is official support
    * Or rewrite in kn
* Runtime
  * gRPC core is write in c, used by php, node, ruby, c# ...
  * [Here](https://github.com/Juniper/grpc-c) is a c binding too.
  * Need kn binding to runtime
* Compiler
  * generate pb
  * generate grpc-server stub
  * generate grpc-client stub

If based on libgrpc, this is possible, but the binding and compiler is not trivial.

May the grpc be with kn.

**Comment by olonho** [comment]
You can provide bindings to gRPC using standard K/N interoperability tools. If what you want is exposing K/N interfaces as gRPC operations, it is also could be done in form of annotation processing compiler pass, like https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/lower/TestProcessor.kt for tests.

**Comment by wenerme** [comment]
Thanks, I will invest this when I got time

**Comment by olonho** [comment]
Closing for now.
