### ISSUE TITLE
WASM target for Linux host

### ISSUE THREAD

**Issue by zaggy** [JetBrains/kotlin-native#1046]
Hi, 

I noticed that WASM target had been added to the `konanc` compiler, but on Linux it throws an error. I would love to help on adding ability to build kotlin for WASM target on Linux but I am not very sure where to start and how do you treat third-party PRs.
 
Can anyone point me in the proper direction? I am ready to tackle Kotlin/Java or C++ code, just need to know where to start.

**Comment by olonho** [comment]
It shall be pretty straightforward, just build a WASM toolchain for Linux  (see https://github.com/JetBrains/kotlin-native/blob/master/contrib/binaryen.diff), and specify that WASM is supported near https://github.com/JetBrains/kotlin-native/blob/5d4d57949055778f3c79071d390daa7397f68cb5/shared/src/main/kotlin/org/jetbrains/kotlin/konan/target/KonanTarget.kt#L164

**Comment by sdeleuze** [comment]
:+1: For Linux WASM support!

**Comment by napperley** [comment]
The **s2wasm.h** file doesn't exist in the Kotlin Native distribution.

**Comment by napperley** [comment]
Found a pre-built Linux [WASM toolchain](http://gsdview.appspot.com/wasm-llvm/builds/linux/26845/wasm-toolchain_0.1.26845_amd64.deb). Curiously the toolchain is accompanied by **torture** [files](http://gsdview.appspot.com/wasm-llvm/builds/linux/26845/). In the toolchain file LLVM 6.0 is used, will that be an issue with Kotlin Native?

How is a pre-built toolchain (from a compressed file - eg deb) installed in the Kotlin Native distribution?

**Comment by vvlevchenko** [comment]
fixed in master, will be available for public soon
