### ISSUE TITLE
cinterop: escape invalid keyword chars in include file paths

### ISSUE THREAD

**Issue by atsushieno** [JetBrains/kotlin-native#1049]
You need some name escaping when generating C stubs. Here is what I found while trying to pass clang-c headers:

	/sources/kotlin/cinterop-playground$ cat clang-c.def 
	headers = clang-c/Index.h
	/sources/kotlin/cinterop-playground$ ~/Applications/kotlin-native-linux-0.4/bin/cinterop -def clang-c.def -copt -I/usr/lib/llvm-3.8/include/
	<snip>
	clang-3.9: warning: argument unused during compilation: '-fuse-ld=/home/atsushi/.konan/dependencies/target-gcc-toolchain-3-linux-x86-64/x86_64-unknown-linux-gnu/bin/ld'
	/sources/kotlin/cinterop-playground/nativelib-build/natives/cstubs.c:4:6: error: variable has incomplete type 'void'
	void clang-c_kniBridge1 (void* p0) {
		 ^
	/sources/kotlin/cinterop-playground/nativelib-build/natives/cstubs.c:4:11: error: expected ';' after top level declarator
	void clang-c_kniBridge1 (void* p0) {
			  ^
			  ;
	2 errors generated.

**Comment by olonho** [comment]
Please specify `package` directive either to interop tool or in .def file, to describe what package your classes shall belong to.
