### ISSUE TITLE
konan does not have an architecture that iPhone SE can execute.

### ISSUE THREAD

**Issue by Albert-Gao** [JetBrains/kotlin-native#1079]
Always get this error when I try to run the `/sample/UIKit`

I ran through the following steps:

```bash
git clone https://github.com/JetBrains/kotlin-native.git

# download dependencies:
./gradlew dependencies:update

# build the compiler and libraries:
./gradlew bundle

cd samples
cd uikit

./build.sh
```

Double click `/uikit/konan.xcodeproj`
Choose `iPhone SE` or any other emulator `iOS 11`
Press the `Play` button, `Build succeeded` but not running
Press `Play` button again, error occurs:

```bash
iPhone SE cannot run konan.

konan does not have an architecture that iPhone SE can execute.
```

> It could run on real device without problem: iPhone 6S 64GB

**Comment by olonho** [comment]
Simulator have different instruction set from the device (arm on devices, x86 on simulator), and we do not support simulator yet.

**Comment by wenerme** [comment]
So, why close this issues ?

**Comment by Albert-Gao** [comment]
@wenerme I suppose because it's not a bug...
