### ISSUE TITLE
Kotlin/native Obj-C interop problems with UITableView delegate/dataSource.

### ISSUE THREAD

**Issue by sunshinejr** [JetBrains/kotlin-native#1082]
Hi guys! We were working through kotlinconf-app and managed to open it in CLion, when we figured that the methods for table view delegate/data source are marked as not correct overridden version of a superclass method. Example screen below.
![zrzut ekranu 2017-11-28 o 15 41 20](https://user-images.githubusercontent.com/5232779/33325616-0a3fd566-d453-11e7-916c-7c13170ad23f.png)

It seems like it mismatched the method for another, different, method. Is this a known bug?

Cheers!

**Comment by SvyatoslavScherbina** [comment]
Hi. Kotlin plugin for CLion is deprecated now. Please use IntelliJ IDEA Ultimate.
See more details here:
https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-rc-released/
https://plugins.jetbrains.com/plugin/10454-kotlin-native-for-clion
