### ISSUE TITLE
Kotlin/native plugin to CLion doesn't respect suppress annotation.

### ISSUE THREAD

**Issue by sunshinejr** [JetBrains/kotlin-native#1083]
Hi guys! So on kotlinconf-app project there is a `SessionsViewController.kt`, which has an annotation `@Suppress("CONFLICTING_OVERLOADS")` before class definition (this is probably because of #1082). Xcode builds it correctly (without this annotation it fails), but CLion still prompts these conflicting overloads as an error, which is unpleasant to work with. Let me know if this is something that could be fixed or if you need more information on this problem.

Cheers!

**Comment by SvyatoslavScherbina** [comment]
Hi. Kotlin plugin for CLion is deprecated now. Please use IntelliJ IDEA Ultimate.
See more details here:
https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-rc-released/
https://plugins.jetbrains.com/plugin/10454-kotlin-native-for-clion
