### ISSUE TITLE
Gradle kotlin-dsl support

### ISSUE THREAD

**Issue by thiagogcm** [JetBrains/kotlin-native#1086]
Just started trying out kotlin-native and decided to apply the konan plugin using the gradle kotlin-dsl

```
apply {
    plugin("konan")
}
...
```
just applying the plugin does not throw any error but the konanArtifacts block does not work:
```
Unresolved reference: konanArtifacts
```

Is it a known issue?

**Comment by ilmat192** [comment]
Could you specify what version of Gradle and Kotlin/Native plugin you use?

**Comment by thiagogcm** [comment]
Sure. 
Gradle 4.3.1 
Kotlin/Native plugin 0.4

**Comment by bamboo** [comment]
Hi @thiagogcm, I'm speaking on behalf of the `kotlin-dsl` team.

For the configuration of extensions such as `konanArtifacts` to work, the `konan` plugin must be applied via the `plugins` block. Unfortunately, there's a defect preventing that to work: gradle/kotlin-dsl#611

We're going to work on a fix soon, alternatively the `konan` plugin could be enhanced to register an explicit public type for the extension as proposed in https://github.com/JetBrains/kotlin-native/pull/1088.

**Comment by thiagogcm** [comment]
thanks for reaching out @bamboo 
So this fix will probably be shipped officially on gradle 4.5+ right?

**Comment by ilmat192** [comment]
One more change to make `konanArtifacts` accessible from Kotlin DSL.

**Comment by ilmat192** [comment]
https://github.com/JetBrains/kotlin-native/pull/1090 is merged, so now the `konanArtifacts` extension is available in Kotlin DSL. Note that it may be required to define a custom plugin repository and a resolution strategy in `settings.gradle` as shown [here](https://github.com/gradle/kotlin-dsl/blob/master/doc/getting-started/Configuring-Plugins.md). It will look something like this:
```
pluginManagement {
    repositories {
        maven { url "https://dl.bintray.com/jetbrains/kotlin-native-dependencies" }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.android.application") {
                useModule("org.jetbrains.kotlin:kotlin-native-gradle-plugin:${requested.version}")
            }
        }
    }
}    
```

**Comment by bamboo** [comment]
@thiagogcm, thanks to @ilmat192 the fix in `kotlin-dsl` is no longer necessary in order to configure `konanArtifacts`. 👏

**Comment by r4zzz4k** [comment]
For me the following syntax
```
apply {
    plugin("konan")
}
```
requires configuration of `buildscript` as per [GRADLE_PLUGIN.md](https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md), and it's working with **kotlin-dsl** indeed, but
```
plugins {
    id("konan")
}
```
with `pluginManagement` block is not working as per gradle/kotlin-dsl#611 with the same error.

Am I right that to see results of #1090 I have to build plugin locally and reference local directory instead of https://dl.bintray.com/jetbrains/kotlin-native-dependencies/ before the next release?
