### ISSUE TITLE
Kotlin/native is much much slower than Kotlin/JVM for the same code

### ISSUE THREAD

**Issue by GauthierPLM** [JetBrains/kotlin-native#1087]
The attached project (Kotlin/native & kotlin/JVM, code is identical except for IO) is much slower when compiled than when running in JVM.
Here are the execution time (measured with time command) :

Kotlin/Native :
real    2m42.136s
user    2m40.610s
sys     0m0.752s

Kotlin/JVM :
real    0m0.800s
user    0m1.816s
sys     0m0.192s

[kotlin-native-tsp.zip](https://github.com/JetBrains/kotlin-native/files/1512872/kotlin-native-tsp.zip)
[kotlin-jvm-tsp.zip](https://github.com/JetBrains/kotlin-native/files/1512878/kotlin-jvm-tsp.zip)

to run the program, just run :
`<executable path> tsp_exp.txt output.txt`

Currently, the program should not output anything in output.txt.

**Comment by orangy** [comment]
+1, my experiments show that string interoplation takes unusually large amount of time. I will try to come up with an example.

**Comment by olonho** [comment]
From what we see adding  smth like `konan.internal.setThreshold(111111)` makes run time much faster. We do deeper analysis of what could be done with MM algorithms.

**Comment by olonho** [comment]
With https://github.com/JetBrains/kotlin-native/pull/1256/ on provided data test runs 10 seconds on my machine.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/1256 is merged, so closing the issue. Please reopen, if still relevant.
