### ISSUE TITLE
Bad string from fromUtf8Array with non-bmp codepoint characters

### ISSUE THREAD

**Issue by Tobi29** [JetBrains/kotlin-native#1091]
Parsing certain UTF-8 characters (I suspect ones
with non-bmp codepoints, e.g. emoticons)
causes fromUtf8Array to return a corrupt string, which
crashes when e.g. printing it:
```Kotlin
val array = byteArrayOf(0xF0.toByte(), 0x9F.toByte(), 0x98.toByte(), 0xA5.toByte())
val badStr = fromUtf8Array(array, 0, array.size)
println(badStr.length) // Kotlin/Native: 1; Kotlin/JVM: 2
println(badStr) // <- This crashes
```

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/1121
