### ISSUE TITLE
[Feature request] Add an example of code sharing between Android and iOS

### ISSUE THREAD

**Issue by Albert-Gao** [JetBrains/kotlin-native#1096]
I saw that you are already working on adding an Android example in that `calculator` project which is great. But that KN side doesn't contain any platform-specific API. I think it might be better that we have an example of how to share logic via platform-specific API.

Something like, I have a file to analysis and save. After getting the content of the file, I can do that at KN side. But in order to read and save, we need to use the platform-specific API.

```kotlin
expect class File {
     fun read()
     fun save()
}

// iOS implementation
actual class File {
    fun read()
    fun save()
}
```

I think an official approach to this kind of pattern would be more than welcome.

I current have some problems with setting up my own KN iOS project to build with platform KN API. 

I think the overall logic could be implemented in KN side, right? As the iOS ObjC API has already ported (or bridged) to kotlin.

**Comment by olonho** [comment]
Now calculator has example of such behavior. Closing, reopen if still need something else.
