### ISSUE TITLE
Reference counter SIGSEGV

### ISSUE THREAD

**Issue by rnentjes** [JetBrains/kotlin-native#1117]
Hi,

I am getting some invalid memory access error during memory allocation and free operations in generic Kotlin code (so not in specific interop code). It looks to me that there is a problem in the reference counter code. Please take a look at the screenshots for some examples. 

The code is a weberver based on the nonBlockingEchoServer example and can be found here: [https://github.com/rnentjes/konan-webserver](https://github.com/rnentjes/konan-webserver)

When I do a lot of requests simultaneously to the server it will crash after a while.

So can this be a bug in the memory management code or can it be something I did wrong? Maybe I forgot to pin something?

This is on linux 17.10 with CLION 2017.3. Kotlin plugin: 1.1.4-dev-259 and Kotlin/Native plugin 0.1-dev-67.

![screenshot at 2017-12-06 16-41-27](https://user-images.githubusercontent.com/553168/33671772-d5da561e-daa8-11e7-8182-e2e019b0e1a2.png)
![screenshot at 2017-12-06 16-49-33](https://user-images.githubusercontent.com/553168/33671794-e20f367a-daa8-11e7-9439-745ba007d06a.png)
![screenshot at 2017-12-06 17-02-48](https://user-images.githubusercontent.com/553168/33671816-f018c5ce-daa8-11e7-8a58-70ed83071b75.png)
![screenshot at 2017-12-06 17-07-53](https://user-images.githubusercontent.com/553168/33671833-fe37edb0-daa8-11e7-9e60-8ff87964a70c.png)

**Comment by olonho** [comment]
What happens if you run your code under Valgrind?

**Comment by olonho** [comment]
No response, please reopen if have more info.

**Comment by rnentjes** [comment]
I haven't gotten the time yet to dive into this issue. But during the few test I did it was running so slow under valgrind that the error never occurs. Without valgrind it still occurs every time, also with the latest version (Kotlin 1.2.30-dev-283 and Kotlin/Native 0.1-dev-86).

Is there any other thing I could test?

**Comment by olonho** [comment]
Looks like the problem is from incorrect usage of memory, more exactly writing outside of the buffer.
