### ISSUE TITLE
Execution failed for task ':calculator:compileKonanKotlinArithmeticParserIphone'

### ISSUE THREAD

**Issue by Samartan** [JetBrains/kotlin-native#1119]
Well I am try to run the Calculator sample from the kotlin-native repo. 

Followed the following steps: 

To build and run the sample do the following:

1. Open samples/calculator/calculator.xcodeproj with Xcode.

2. Open the project's target through project navigator, go to tab 'General'. In 'Identity' section change the bundle ID to the unique string in reverse-DNS format. Then select the team in 'Signing' section. See the Xcode documentation for more info.

3. Now build and run the application on a connected iPhone with Xcode.

But when I try to build the application in Xcode I get the following error and the log to it is below: 

...
...
...
The target is not enabled on the current host: linux
Target 'linux' of artifact 'libgit2' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
Target 'linux' of artifact 'libcurl' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: raspberrypi
Target 'linux' of artifact 'sdl' is not supported on the current host
Target 'raspberrypi' of artifact 'sdl' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: raspberrypi
Target 'linux' of artifact 'tetris' is not supported on the current host
Target 'raspberrypi' of artifact 'tetris' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: mingw
Target 'linux' of artifact 'ffmpeg' is not supported on the current host
Target 'mingw' of artifact 'ffmpeg' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: mingw
Target 'linux' of artifact 'sdl' is not supported on the current host
Target 'mingw' of artifact 'sdl' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: mingw
Target 'linux' of artifact 'Player' is not supported on the current host
Target 'mingw' of artifact 'Player' is not supported on the current host
The target is not enabled on the current host: mingw
:calculator:checkKonanCompiler
:calculator:compileKonanKotlinArithmeticParserIphone FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':calculator:compileKonanKotlinArithmeticParserIphone'.
> Classpath of the tool is empty: konanc
  Probably the 'konan.home' project property contains an incorrect path.
  Please change it to the compiler root directory and rerun the build.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
2 actionable tasks: 2 executed
Command /bin/sh failed with exit code 1

Thank you!

**Comment by SvyatoslavScherbina** [comment]
Have you opened the sample from the entire cloned repo, or you have moved it out?
Have you built Kotlin/Native itself with `./gradlew clean dist crossDist` before building the sample?

**Comment by olonho** [comment]
Please report if it fixes your problem or not, otherwise I have to close this issue.

**Comment by roxiemobile** [comment]
Hi, guys. I'm trying to build example in newly cloned repository and gets the same error.

Nope, it does not fixed problem. Even execution of `./gradlew clean dist crossDist` finishes with error:
```
roxiemobile@stalker: kotlin-native$ ./gradlew clean dist crossDist

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:macbookHash'.
> A problem occurred starting process 'command '/Users/stalker/.konan/dependencies/clang-llvm-5.0.0-darwin-macos/bin/clang++''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
18 actionable tasks: 16 executed, 2 up-to-date
```

**Comment by SalvatoreT** [comment]
I ran into the same issue and `./gradlew clean dist crossDist` did the trick for me.

**Comment by baruchn** [comment]
Have the same issue. Ran `./gradlew clean dist crossDist` but it ended with an error:

>* What went wrong:
Execution failed for task ':common:macbookHash'.
> A problem occurred starting process 'command '/Users/baruchnurilov/.konan/dependencies/clang-llvm-5.0.0-darwin-macos/bin/clang++''

.konen/dependencies folder is empty and unfortunately I'm not familiar with this tool.

**Comment by StefMa** [comment]
Please read the Readme carefully.
Have you run `./gradlew dependencies:update` before?

**Comment by baruchn** [comment]
My apologies. Only read the Calculator Readme and not the main one. Thanks for the quick response.

**Comment by yuriry** [comment]
When I run './gradlew dependencies:update' I get the error below.   How can I proceed from here?  Thank you in advance.

* What went wrong:
A problem occurred evaluating root project 'kotlin-native'.
> The /usr/bin/xcrun command returned non-zero exit code: 1.

**Comment by yuriry** [comment]
I had both Xcode and cmd line tools installed.  After manually deleting cmd line tools and re-starting a laptop './gradlew dependencies:update' finished without errors.

**Comment by cosminstefanxp** [comment]
I've run into the same issue. How can we run the sample completely independent of the kotlin project. I.e. how do we build our own project? How can we install the kotlin native compiler?

```
 What went wrong:
Execution failed for task ':arithmeticParser:compileKotlinIos'.
> Classpath of the tool is empty: konanc
  Probably the 'org.jetbrains.kotlin.native.home' project property contains an incorrect path.
  Please change it to the compiler root directory and rerun the build.
```
