### ISSUE TITLE
How long can  calling C++ libraries be supported ....

### ISSUE THREAD

**Issue by zxj5470** [JetBrains/kotlin-native#1120]
some libraries,like OpenCV(2/3 version)or Gdiplus ,only supply the interface for (C like)C++ but not pure C....
And I noticed that the dependencies (clang-llvm) contains clang++

I hope kotlin-native can bootstrap one day~

**Comment by olonho** [comment]
Full C++ interop is not yet a goal we aiming, however interop with some libs may be implemented.
