### ISSUE TITLE
.framework missing UIKit header

### ISSUE THREAD

**Issue by PradeepPappuAto** [JetBrains/kotlin-native#1138]
#import <UIKit/UIKit.h> is missing in the .framework binary created using kanonc

As a result "unichar" type is unresolved.

**Comment by PradeepPappuAto** [comment]
Foundation.h doesn't fix the problem. it should be UIKit.h :-(

**Comment by SvyatoslavScherbina** [comment]
As far as I see, `unichar` is declared in `Foundation/NSString.h`, which obviously gets included with `Foundation.h`. And this fix works for me.

Which version of Xcode do you use? Could you provide Kotlin source code to reproduce the issue?

**Comment by SvyatoslavScherbina** [comment]
@PradeepPappuAto Can you confirm that the issue is now fixed in master branch?

**Comment by PradeepPappuAto** [comment]
You are a champion. They are fixed.
