### ISSUE TITLE
.framework got protocol definitions wrong

### ISSUE THREAD

**Issue by PradeepPappuAto** [JetBrains/kotlin-native#1139]
Actual:
@protocol FidsOpsStdlibMutableCollection <FidsOpsStdlibCollectionFidsOpsStdlibMutableIterable>
@protocol FidsOpsStdlibMutableSet <FidsOpsStdlibSetFidsOpsStdlibMutableCollection>

Expected:
@protocol FidsOpsStdlibMutableCollection <FidsOpsStdlibMutableIterable>
@protocol FidsOpsStdlibMutableSet <FidsOpsStdlibMutableCollection>

**Comment by olonho** [comment]
What\s the difference between expected and actual? Do you have code snippets?

**Comment by PradeepPappuAto** [comment]
Sure.. here you go.
[fidsOps.h.zip](https://github.com/JetBrains/kotlin-native/files/1557149/fidsOps.h.zip)

**Comment by SvyatoslavScherbina** [comment]
Yes, I can confirm this issue. Thank you for the report.

**Comment by SvyatoslavScherbina** [comment]
@PradeepPappuAto Can you confirm that the issue is now fixed in master branch?

**Comment by PradeepPappuAto** [comment]
You are a champion. They are fixed.
