### ISSUE TITLE
Problem with cinterop and konanc commands

### ISSUE THREAD

**Issue by Samartan** [JetBrains/kotlin-native#1146]
I have been following this [blog](https://superkotlin.com/kotlin-native/) to get myself started with Kotlin/Native. 
I had no problems until the final two steps where I need to use the following two commands to build and compile :- 

```
cinterop -def src/main/c_interop/png.def -copt "$CFLAGS" -target macbook -o build/c_interop/png

```
```

konanc $COMPILER_ARGS -target macbook src/main/kotlin/logogen.kt -library build/c_interop/png -linkerOpts "-L/usr/local/lib -lpng" -o build/bin/logogen

````

Once I run the former command I get the following error: 
```

cat: /Users/manojn/IdeaProjects/kotlin-native/tools/env_blacklist: No such file or directory
Error: Could not find or load main class org.jetbrains.kotlin.cli.utilities.MainKt
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.cli.utilities.MainKt

```

How can I solve this? Happy to help with any further information. Thank You.

**Comment by alexander-gorshenev** [comment]
You seem to be working with the source tree of Kotlin/Native, and you seem to be running the `cinterop` from `/Users/manojn/IdeaProjects/kotlin-native/cmd` directory. 
You should run it from`/Users/manojn/IdeaProjects/kotlin-native/dist/bin` directory, which is the result of your `./gradlew dist` command.

**Comment by Samartan** [comment]
That is true and I did change it run it from ```/Users/manojn/IdeaProjects/kotlin-native/dist/bin```

Now I am getting File not found exception: 
```
Exception in thread "main" java.io.FileNotFoundException: /src/main/c_interop/png.def (No such file or directory)

```

![My project Structure](https://user-images.githubusercontent.com/10944487/34036734-3c7106d4-e1ac-11e7-95c4-ae72fb4eeeb3.png)

**Comment by Samartan** [comment]
That was it. Thanks!

**Comment by darkoverlordofdata** [comment]
Wow - I've been struggling with this all evening. You should fix the instructions on [https://kotlinlang.org/docs/tutorials/native/basic-kotlin-native-app.html](https://kotlinlang.org/docs/tutorials/native/basic-kotlin-native-app.html)!

Finding the correct instructions on a year old issue that you might run across by googling an error seems a bit inneficient :)
