### ISSUE TITLE
Using C library functions in kotlin

### ISSUE THREAD

**Issue by Samaritan1011001** [JetBrains/kotlin-native#1149]
I have been trying to follow this [blog](https://superkotlin.com/kotlin-native) and I have run all the steps successfully but however when I run the last command 
```
konanc $COMPILER_ARGS -target macbook src/main/kotlin/logogen.kt -library build/c_interop/png -linkerOpts "-L/usr/local/lib -lpng" -o build/bin/logogen

```

I get errors which say sqrt,pow,fopen,fclose are all *unresolved* 

```
error: unresolved reference: sqrt

``` 

This is what is in my png.def file 
```
headers = /usr/local/include/png.h stdio.h stdlib.h string.h math.h

``` 

Imported it in my logogen.kt file as 
```
import png.*

```
Happy to provide any further information. 
Thank you!

**Comment by olonho** [comment]
How does the source code looks like. Do you have github repo we can clone and try?

**Comment by Samaritan1011001** [comment]
I followed this [blog] (https://superkotlin.com/kotlin-native/) so all the code that is there in the blog is the same.

**Comment by vvlevchenko** [comment]
regarding this sample with 0.5 you need add ``import platform.posix.*`` and use different build gradle, e.g. following:
````
buildscript {
    repositories {
       mavenCentral()
       maven {
           url  "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
       }
   }

   dependencies {
       classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:0.5"
   }
}

apply plugin: 'konan'

konanArtifacts {
    interop('png') {
       defFile 'src/main/c_interop/png.def'
    }

    program('LogoGenMacbook') { 
        linkerOpts "-L/opt/local/lib -lpng" // we added this line
	libraries {
           artifact 'png' // and this one
	}
    }
}
````
