### ISSUE TITLE
Enum values are not showing up in header file

### ISSUE THREAD

**Issue by PradeepPappuAto** [JetBrains/kotlin-native#1165]
enum class Status {
    INIT,
    IN_FINISHED_VALUE,
    IN_OBJECT,
    IN_ARRAY,
    PASSED_PAIR_KEY,
    PAIR_VALUE,
    IN_ERROR,
    EOF
}

Its depicted in header file as below

__attribute__((objc_subclassing_restricted))
@interface FidsOpsStatus : FidsOpsStdlibEnum
-(instancetype)initWithName:(NSString*)name ordinal:(int32_t)ordinal NS_SWIFT_NAME(init(name:ordinal:)) NS_DESIGNATED_INITIALIZER __attribute__((unavailable));

-(int32_t)compareToOther:(FidsOpsStatus*)other NS_SWIFT_NAME(compareTo(other:));
@end;

I am unsure of how to access the enum values. I might be missing something. Could you give me through it please.

**Comment by PavelPunegov** [comment]
You can always pass and get any enum using its `ordinal` or `name`. You have to do similar Objective-C enum:
```
typedef NS_ENUM(NSInteger, SwiftStatus) {
    INIT = 0,
    IN_FINISHED_VALUE,
    IN_OBJECT,
  // etc.
}
```
Then when some Kotlin function that returns a Status enum like this example: 
`fun get(): Status` defined in KotlinFramework class, 
swift code will look like:
```
func getResultFromKotlinEnum() -> SwiftStatus {
  let result = KotlinFramework.get().ordinal
  switch result {
    case 0: return INIT
    case 1: return IN_FINISHED_VALUE,
    case 2: return IN_OBJECT
    default: return EOF
  }
```

**Comment by PradeepPappuAto** [comment]
Thanks Pavel. That makes sense. I was expecting konan to create such typedef mapping. But for now I used your solution which perfectly fits my need.

**Comment by olonho** [comment]
Yes, this will be fixed in upcoming release.
