### ISSUE TITLE
When can we expect a stable version?

### ISSUE THREAD

**Issue by PradeepPappuAto** [JetBrains/kotlin-native#1166]
My organisation is weighing out various alternatives on cross platform implementation.

We have tried
1. Kotlin/Native
2. Javascript
3. React native
4. Ionic
5. Xamarin

Off all as you must have guessed, Kotlin/Native was our favourite.

Opponents got 2 argument 
1. Is it a stable version / what is the ETA?
2. Which other companies are using it?

As the time for the actual implementation is soon approaching, I was wondering if I could get some help in supporting my decision for Kotlin/Native

**Comment by olonho** [comment]
Pradeep, great to hear you like and use Kotlin/Native. We're aiming to stable version with great tooling support soon, in the meantime, v0.5 was released, see https://blog.jetbrains.com/kotlin/2017/12/kotlinnative-v0-5-released-calling-kotlin-from-swift-and-c-llvm-5-and-more/#more-5635. 

Regarding other companies using Kotlin/Native, we cannot give such information yet, however, there are such companies, as far, as we know.

**Comment by napperley** [comment]
Does that include companies using Kotlin Native for development that isn't mobile related?

**Comment by PradeepPappuAto** [comment]
@napperley Any information on that it is being used in production environment is helpful. If it is in mobile space; the argument would be much stronger.

**Comment by mikemee** [comment]
I'm also very interested in this functionality. We have a Swift "core" library (with full tests) that we currently transliterate (by hand) to Kotlin to use for a native iOS and Android app respectively. The core lib handles business (game) logic, and also layout measurements, accessibility label text etc. Pretty much the entire logic for the app. The apps consist mostly of view controllers (storyboards/templates) & I/O to SQLite.

If we can drop the Swift code and continue on with just the Kotlin, that will be a huge win! (We were thinking we'd maintain a Swift library and call it on Android via JNI, but maybe this will be much cleaner / fully featured.)

I'm really interested to see how `structs` will be exposed to Swift. Pretty much our entire library consists of `structs` with properties and almost no methods apart from a test and production initializers. 

Kudos to the team for everything achieved so far!  🎉

**Comment by PradeepPappuAto** [comment]
@olonho for the work I am currently on; v0.5 was sufficient and is doing all the magic. However, the opponents were expecting to hear a v1.0 before any release to Prod. Do you foresee a stable version coming out soon, otherwise I will have to start building a swift version of the same code :-(

Thanks to all the contributors for all of your efforts.

**Comment by miere** [comment]
Hey guys, any feedback on this regard?
Or, maybe a better question would be, how stable is the v0.5+ right now?
