### ISSUE TITLE
Null build takes a while

### ISSUE THREAD

**Issue by russel** [JetBrains/kotlin-native#1167]
I just tried doing a null build, i.e. a build immediately after a build, and a lot of work gets done: the dependency check takes about 11s which is OK, but the build takes about 1m 55s which implies work is being redone when it should be needed.

See if some Gradle experts can do an upgrade to Gradle 4.4 and rework things to use the caching? This happened on the Groovy repo recently and the null build went from many minutes to 14s. A full build also got speeded up – 25m to about 15m.

**Comment by vvlevchenko** [comment]
grade is updated
