### ISSUE TITLE
HTTP 403 while downloading kotlin-native-linux-0.5.tar.gz

### ISSUE THREAD

**Issue by madhead** [JetBrains/kotlin-native#1171]
I have a very simple build script like this:

	import org.jetbrains.kotlin.gradle.plugin.KonanArtifactContainer

	buildscript {
		repositories {
			jcenter()
			maven("https://dl.bintray.com/jetbrains/kotlin-native-dependencies")
		}

		dependencies {
			classpath("org.jetbrains.kotlin:kotlin-native-gradle-plugin:0.5")
		}
	}

	apply {
		plugin("konan")
	}

	configure<KonanArtifactContainer> {
		...
	}

When I'm executing `./gradlew compileKonan` without having K/N 0.5 I get this error:

	:checkKonanCompiler
	Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
	:checkKonanCompiler FAILED

	FAILURE: Build failed with an exception.

	* What went wrong:
	Cannot download Kotlin/Native compiler
	> Server returned HTTP response code: 403 for URL: https://download.jetbrains.com/kotlin/native/builds/releases/0.5/linux/kotlin-native-linux-0.5.tar.gz

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 5s
	1 actionable task: 1 executed

**Comment by napperley** [comment]
Try replacing **https** with **http** and see if that resolves the issue.

**Comment by ilmat192** [comment]
Fixed

**Comment by madhead** [comment]
Thanks a lot!
