### ISSUE TITLE
IOS sysroot is not available with XCode 9.1

### ISSUE THREAD

**Issue by ilmat192** [JetBrains/kotlin-native#1175]
Copied from https://github.com/JetBrains/kotlin-native/issues/1174#issuecomment-353008906:

Here's the [build log](https://github.com/JetBrains/kotlin-native/files/1574877/buildlog.txt) I got when I tried building for device with Xcode. I slapped on an extra `--stacktrace` and `--debug` on the `gradlew` command:

<img width="179" alt="skjermbilde 2017-12-20 kl 10 18 26" src="https://user-images.githubusercontent.com/3652587/34199800-3b5b6796-e56f-11e7-8447-3e19356aa7cb.png">

<img width="151" alt="skjermbilde 2017-12-20 kl 10 18 31" src="https://user-images.githubusercontent.com/3652587/34199801-3b70f57a-e56f-11e7-8863-7a5ab28ae063.png">

Master branch pointing at commit 6ee6f5907d808f21af06436e6c44b6fe2b9bb6b5

**Comment by ilmat192** [comment]
Did the update of XCode fix the issue?
And did you run `./gradlew :dependencies:update` in the root directory before building the sample?

**Comment by olonho** [comment]
Did you read the README.md, which explicitly states that "on macOS install Xcode 9.2"?

**Comment by lempere** [comment]
You could edit backend.native/konan.properties and edit the line:

>Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
 Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk

to

> Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk
 Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.1.sdk

I tried with the xcode9 and the value 11.0 and I can get compiled, but is better if you just upgrade to xcode9.2.

**Comment by iNoles** [comment]
why not Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk is just alias to iPhoneOS11.2.sdk?

**Comment by olonho** [comment]
Closing the issue, as problems seems to be resolved.
