### ISSUE TITLE
Missing Platform Porting Documentation

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#1178]
Noticed in the Kotlin Native repository that there is no documentation covering the porting process for Kotlin Native. Are there plans to provide the missing documentation (eg **porting.md**)? Right now the porting system is a bit like a **black box** even though the Kotlin Native source code is freely available, which makes doing a port of Kotlin Native to a new platform (eg [ARM Cortex M4](https://github.com/JetBrains/kotlin-native/issues/458)) much more difficult than it needs to be.

**Comment by olonho** [comment]
Makes sense, will try to cover that.

**Comment by kylejbrock** [comment]
One of the things I'm interested in is armv7 support in iOS.  It's not really a new platform per se, but an additional architecture to an already existing platform.  So, any information around adding those sort of things would be useful, too.

**Comment by volodymyr-gz** [comment]
@olonho Are there any updates on this?

**Comment by sbogolepov** [comment]
Currently, there is no easy way to add a new target. I created [KT-43974](https://youtrack.jetbrains.com/issue/KT-43974) to track this problem. Please, describe your use-case there (e.g., what kind of applications you want to run on ARM Cortex M4). It will really help us to design a nice solution to the problem.
