### ISSUE TITLE
Package Support?

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#1179]
Does the current version of Kotlin Native (**v0.5**) have Package support?

**Comment by olonho** [comment]
What do you mean by "Package support"?

**Comment by napperley** [comment]
The ability to package source code into smaller units to easily [organise/maintain code](https://kotlinlang.org/docs/reference/packages.html#packages).

**Comment by olonho** [comment]
Kotlin/Native supports packages and they are used in samples: https://github.com/JetBrains/kotlin-native/blob/master/samples/libcurl/src/main/kotlin/org/konan/libcurl/CUrl.kt
