### ISSUE TITLE
Chrome Errors With HTML 5 Canvas Sample

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#1180]
After opening the **index.html** file from the **html5Canvas** directory in Chrome (**v62**) some errors appear in the web console:

![html 5 canvas sample errors in chrome](https://user-images.githubusercontent.com/3538279/34242414-3bcb4676-e680-11e7-9b83-56bc7d4d7abe.png)

Running the same sample in Firefox (**v57**) works just fine without any errors:

![html 5 canvas sample in firefox](https://user-images.githubusercontent.com/3538279/34242593-17f25ea0-e681-11e7-9b79-621c6625d358.png)

**Comment by olonho** [comment]
You shall serve .wasm from HTTP server, not local filesystem.

**Comment by napperley** [comment]
Ok. In that case using a web server like **Netty** will suffice (eg via Vert.x).
