### ISSUE TITLE
Issue with interop libxml library in Mac OS X

### ISSUE THREAD

**Issue by iNoles** [JetBrains/kotlin-native#1183]
Exception in thread "main" java.lang.Error: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2/libxml/tree.h:17:10: fatal error: 'libxml/xmlversion.h' file not found

```
headers = libxml2/libxml/tree.h libxml2/libxml/xpath.h libxml2/libxml/Htmlparser.h
compilerOpts.osx = -I/usr/include/libxml2
linkerOpts.osx = -L/opt/local/lib -lxml2
```

on tree.h, #include <libxml/xmlversion.h>

**Comment by vvlevchenko** [comment]
Could you please share more details what and how are you doing?

**Comment by iNoles** [comment]
I was trying to do run cinterop -def libxml.def -o libxml, then I get that fatal error message.

**Comment by vvlevchenko** [comment]
Could you please dump output of `cinterop -def libxml.def -o libxml -verbose true` here?

**Comment by iNoles** [comment]
Nothing changes.  I found a way to got it to work by using -I/<path to Xcode's MacOS SDK>/usr/include/libxml2
