### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by stangls** [JetBrains/kotlin-native#1188]
OS: Ubuntu 16.04.3 LTS
Kernel: 4.4.0
gcc version 5.4.0
openjdk version "1.8.0_151"
javac 1.8.0_151

command: `./gradlew --stacktrace bundle`

See output with stacktrace: [log.out.tar.gz](https://github.com/JetBrains/kotlin-native/files/1583557/log.out.tar.gz)

Any hints what I might be missing?
Should I run with `--scan` or `--debug`?
Any other information required to resolve this?

**Comment by vvlevchenko** [comment]
Could you please share log of `./gradlew bundle -i`?

**Comment by vvlevchenko** [comment]
I was able to reproduce the issue.  thank you for reporting.

**Comment by stangls** [comment]
here is my output of `./gradlew bundle -i` : [minus-i.out.gz](https://github.com/JetBrains/kotlin-native/files/1584483/minus-i.out.gz)

**Comment by vvlevchenko** [comment]
#1189 fixes the issue

**Comment by stangls** [comment]
yes :+1: works for me. thank you for the fast solution!
