### ISSUE TITLE
Error running worker sample on Windows 10

### ISSUE THREAD

**Issue by Kangmo** [JetBrains/kotlin-native#1195]
Kudos to the team for everything achieved so far! 
I LOVE kotlin/native. In my environment the worker sample is crashing, but not sure it is reproduced in others computers.

==

POSIX WinThreads for Windows is crashing when I run the worker sample code.

Checked out source code with tag v0.5, and ran following commands. Using Windows 10 Pro Version 1709, Build 16299.125.

Reproduction steps:
git clone https://github.com/JetBrains/kotlin-native
cd kotlin-native
git checkout v0.5
gradlew dependencies:update
gradlew bundle

Install Git for Windows, and open Git Bash terminal.
cd samples\workers
.\build.sh

open up kotlin-native\samples\workers\build\bin in file explorer and click on Workers.exe.

I see the attached error.
![2](https://user-images.githubusercontent.com/510271/34369800-621f54ee-eb02-11e7-9cdf-ca64bf3e9ebc.PNG)

C:\deep\src\kotlin-native\runtime\src\main\cpp\Memory.cpp:1003: runtime assert: Memory leaks found

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by olonho** [comment]
Likely because your app has memory leak, as assert says. Try to run your app on Linux under Valgrind.

**Comment by Kangmo** [comment]
It is not my app but samples/workers. w/ v0.4 it works well, but it crashes with the above error message w/ v0.5.

**Comment by olonho** [comment]
Right, shall be fixed with https://github.com/JetBrains/kotlin-native/pull/1196
