### ISSUE TITLE
SortedSet and SortedMap

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1208]
Kotlin/Native stdlib does not support `SortedSet`, `sortedSetOf`, `toSortedSet` and so on.
Same for `SortedMap`.
Is it JVM-only or will be implemented someday?

**Comment by olonho** [comment]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/sorted-set-of.html

Note that it's explicitly says that it is JVM-only.

**Comment by msink** [comment]
Ok, so these functions cannot be used in multiplstform code.

Rewrote my program to use `MutableList<T>` `.sortBy()` `.binarySearchBy()` - performance is even a little better... :)
