### ISSUE TITLE
Support external JAR libraries?

### ISSUE THREAD

**Issue by teras** [JetBrains/kotlin-native#1212]
Is it possible to support external JAR libraries? In the demo projects everything is written in Kotlin and no external JARs seemed to be called (or I am missing something?)

**Comment by StefMa** [comment]
Nope, jars aren't support. But you can include native libraries....

**Comment by teras** [comment]
Thank you for the response.

Are there any plans to support this in the future?
It is quite common a Kotlin project to depend on a Java JAR library - otherwise the usability of this project will be constraint by the Kotlin world only 😢

**Comment by olonho** [comment]
Kotlin/Native is not Kotlin/JVM ahead of time compiler. It is Kotlin compiler suitable for native development. As such it may not, and will not support JARs containing JVM class files as an input.
