### ISSUE TITLE
Allow Top-Level Symbol Export in Shared Library

### ISSUE THREAD

**Issue by cretz** [JetBrains/kotlin-native#1220]
Things like `@ExportForCppRuntime` don't work with Gradle `dynamic`. Some things like JNI and JVMTI need specific exported functions to invoke (e.g. `JNI_OnLoad` or `Agent_OnAttach`). I worked around this by using a cpp file and passing it to `linkerOpts` along with `-Xlinker --export-all-symbols` as seen [here](https://github.com/cretz/kotlin-native-sample-agent/tree/44c1a0b602180ccc7018a39bf2ffdb509eea63f2)

**Comment by olonho** [comment]
@ExportForCppRuntime is not intended to be used for that purpose. Probably something like @JvmName is needed.

**Comment by olonho** [comment]
See https://github.com/JetBrains/kotlin-native/pull/1237 - would it be enough for your needs?

**Comment by cretz** [comment]
I haven't tested, but it looks like it has what I need: when using "dynamic" type it will put the function in the header, and it is marked as "extern" in the LLVM bitcode which should expose it in the DLL. So, yes! Awesome.

**Comment by olonho** [comment]
PR was merged.

**Comment by cretz** [comment]
@olonho - while implementing this, I ran into two snags:

* I might have some CPP code (or other bitcode) going along with this that already defines the exported function in a header (e.g. using `jni.h` which already defines `JNI_OnLoad`), so `clang++` complains when it sees it in the generated header too. Maybe an option on `@CName` that still exposes it in the DLL but doesn't put it in the header?
* I cannot pass in or return pointers defined in a depended-upon header properly. Can you update the example to show a Kotlin function accepting a pointer to a external-header-defined struct and returning one too? Using CPointer or CValuesRef did not work for me.

**Comment by olonho** [comment]
Regarding first problem, maybe best approach would be smth like 
#define Func FuncWithSomeMangling
#include “my_api.h”

For second problem - did you try the latest master: I implemented passing CPointer as void* in https://github.com/JetBrains/kotlin-native/commit/1599eddfe108dcc27de71352805c026bb50e075c

Does it do what you need?

**Comment by cretz** [comment]
My mistake, I had the parameters switched up. All works perfectly w/ 0.6-dev-751 and I was able to remove the C++ bridge: https://github.com/cretz/javan-warty-pig/commit/d7d7722c7d7fb358d40140fb8fc7202104196a9f. Thanks!

**Comment by olonho** [comment]
Cool, closing the issue.
