### ISSUE TITLE
Cannot import third party dependencies

### ISSUE THREAD

**Issue by tonyli508** [JetBrains/kotlin-native#1223]
Tried add following line to sample Calculator build.gradle file

```groovy
dependencies {
    compile 'com.fasterxml.jackson.module:jackson-module-kotlin:2.9.0'
}
```

then import in Parser.kt, got error: 'unresolved reference: com' when building
![screen shot 2018-01-11 at 15 59 26](https://user-images.githubusercontent.com/5927738/34833905-71d0ed20-f6e8-11e7-8e13-b79c5f3c301d.png)

**Comment by olonho** [comment]
What exactly you're trying to achieve with this line? Kotlin/Native programs cannot use Java dependencies, you need to use some native JSON library, like in https://github.com/JetBrains/kotlinconf-spinner/tree/master/kotlin-native/samples/fullstack/json
or write your own implementation in pure Kotlin.
