### ISSUE TITLE
Artifact to Platform Mappings

### ISSUE THREAD

**Issue by patrickpilch** [JetBrains/kotlin-native#1233]
Hi, thanks for the awesome project!

I noticed that some target platforms were incompatible with certain output artifact types. For example, I've specified the following platforms & artifacts:
```groovy
konan.targets = ['iphone', 'iphone_sim', 'wasm32']

konanArtifacts {
    framework('KotlinArithmeticParser')
    library('ArithWasmLib')
}
```
And the **compileKonan** tasks fails due to [checking the target for macbook or iPhone (& simulator).](https://github.com/JetBrains/kotlin-native/blob/v0.5/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExport.kt#L45-L49)
```
error: compilation failed: WASM32

 * Source files: Parser.kt
 * Compiler version info: Konan: EAP 0.6.0.0 / Kotlin: 1.2.0
 * Output kind: FRAMEWORK

exception: java.lang.IllegalStateException: WASM32
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produceObjCFramework$backend_native_compiler(ObjCExport.kt:48)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:300)
...
```

I was looking through the [Gradle plugin documentation](https://github.com/JetBrains/kotlin-native/blob/v0.5/GRADLE_PLUGIN.md#building-for-different-targets) trying to find a way to restrict particular artifacts to certain platforms so I can just run the **compileKonan** task, but did not find a clear way of doing so. 

Is this possible without resorting to custom tasks like:
```groovy
task wasmTest(dependsOn: konanArtifacts.ArithWasmLib.wasm32)
```

**Comment by ilmat192** [comment]
Thanks for your report. This issue is known and the fix will be merged into the master branch soon (see this commit: https://github.com/JetBrains/kotlin-native/pull/1203/commits/fdcf7beb58e2a16ed8a2c2da0a61e6de403c61b4). As a workaround you may just disable the tasks causing errors. Add something like this after you `konanArtifacts` block:
```
compileKonanKotlinArithmeticParserWasm32.enabled = false
compileKonanArithWasmLibIphone.enabled = false
compileKonanArithWasmLibIphone_sim.enabled = false
```

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/1203.
