### ISSUE TITLE
Global var being reset in DLL when called into from separate OS thread on Windows

### ISSUE THREAD

**Issue by cretz** [JetBrains/kotlin-native#1234]
I have a JNI/JVMTI DLL in Kotlin Native. In one JNI function, I store a value (pointer) globally in a top-level var. If I call a JNI function on the same thread, I can utilize the value. If I call a JNI function on another thread (but same DLL), the value is set to its initial value (null pointer in my case). I have tested and this occurs with all top-level vars (lateinit or not, e.g. lateinit is not considered "initialized" if set on one thread and called on another).

Any idea on why this occurs? If it's absolutely necessary, I can work on creating a minimal reproducing test case. I was just hoping it'd be obvious before I have to put in that work.

**Comment by olonho** [comment]
It is intended behavior with current K/N. Kotlin top level variables are mapped to thread local variables, so each thread has its own copy of top level vars. If you need to perform actual state exchange, note that shared global mutable state is generally a bad idea. Instead you may pass a value explicitly to another thread, like in this example: https://github.com/JetBrains/kotlin-native/blob/1aa2e26344e0e79c6a8cc10ab244b7ee09b4992b/samples/videoplayer/src/main/kotlin/SDLAudio.kt#L51
or use workers object exchange mechanism, like in https://github.com/JetBrains/kotlin-native/blob/1aa2e26344e0e79c6a8cc10ab244b7ee09b4992b/samples/videoplayer/src/main/kotlin/DecoderWorker.kt#L399. 

Note, that no object could be concurrently seen by multiple threads of execution, so no deadlocks or data races could happen.

**Comment by olonho** [comment]
And of cource one could use C top level or static variable to achieve the same effect, if it is absolutely needed.

**Comment by olonho** [comment]
Take a look at https://github.com/JetBrains/kotlin-native/pull/1236 - it may be what you need.

**Comment by cretz** [comment]
I see, yeah, essentially appending it as a header piece (basically the same as custom C/C++). Yup, this should work for me, thanks. I still think there may be value for a global ref type.
