### ISSUE TITLE
Memory.cpp:718: runtime assert: unknown container type

### ISSUE THREAD

**Issue by desertjim** [JetBrains/kotlin-native#1238]
I'm trying to use reverse interop.  I have the following kotlin code:
```
import platform.CoreFoundation.CFURLRef

fun GenerateThumbnailForURLkt(url: CFURLRef): Int {
    println("received call")
    return 0
}
```

I'm calling `konanc -produce dynamic Example.kt` to generate the `dynamic_api.h` and `libdynamic.dylib`.

The following c code compiles just fine:

```
#include <CoreFoundation/CoreFoundation.h>
#include <stdio.h>
#include "dynamic_api.h"

int main(int argc, const char * argv[]) {
    // insert code here...
    printf("Hello, World!\n");
    CFStringBuiltInEncodings encoding = kCFStringEncodingUTF8;
    CFStringRef urlStr = CFStringCreateWithCString(kCFAllocatorDefault, "http://www.intel.com", encoding);
    CFURLRef url = CFURLCreateWithString(kCFAllocatorDefault, urlStr, NULL);
    
    dynamic_kref_kotlinx_cinterop_CPointer urlPtr = {0};
    urlPtr.pinned = (void*)(uintptr_t)url;
    
    dynamic_symbols()->kotlin.root.GenerateThumbnailForURLkt(urlPtr);
    return 0;
}
```
The resulting executable sometimes works as expect:
Hello, World!
received call

other times it fails:
./kotlin-native/runtime/src/main/cpp/Memory.cpp:718: runtime assert: unknown container type
Abort trap: 6

Am I doing something wrong?

**Comment by olonho** [comment]
Also you need to explicitly release an object, once it's no longer needed.

**Comment by desertjim** [comment]
I was trying to call Kotlin method `GenerateThumbnailForURLkt`, which takes a `CFURLRef` as an argument.  I'm not trying to create the `CFURLRef` in kotlin, just pass it from the C side to the Kotlin side.

What is the correct way to pass arguments from the C side?

When you say release it, do you mean like this?:
`dynamic_symbols()->DisposeStablePointer(urlPtr.pinned);`

**Comment by olonho** [comment]
Let me write a change to help you.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/1242 may be what you need.

**Comment by olonho** [comment]
This way you could pass pointers as it, without any magic.

**Comment by olonho** [comment]
PR is merged, feel free to test.

**Comment by desertjim** [comment]
just to confirm, this is what it should look like?

```
#include <CoreFoundation/CoreFoundation.h>
#include <stdio.h>
#include "dynamic_api.h"

int main(int argc, const char * argv[]) {
    // insert code here...
    printf("Hello, World!\n");
    CFStringBuiltInEncodings encoding = kCFStringEncodingUTF8;
    CFStringRef urlStr = CFStringCreateWithCString(kCFAllocatorDefault, "http://www.intel.com", encoding);
    CFURLRef url = CFURLCreateWithString(kCFAllocatorDefault, urlStr, NULL);
    
    dynamic_kref_kotlinx_cinterop_CPointer urlPtr = {url};
    
    dynamic_symbols()->kotlin.root.GenerateThumbnailForURLkt(urlPtr);
    dynamic_symbols()->DisposeStablePointer(urlPtr.pinned);
    return 0;
}
```

If so I'm still occasionally seeing: `/kotlin-native/runtime/src/main/cpp/Memory.cpp:718: runtime assert: unknown container type
Abort trap: 6`

**Comment by desertjim** [comment]
Yesterday when using 1599eddfe108dcc27de71352805c026bb50e075c.  When I tried to compile the following:
```
#include <CoreFoundation/CoreFoundation.h>
#include <stdio.h>
#include "dynamic_api.h"

int main(int argc, const char * argv[]) {
    // insert code here...
    printf("Hello, World!\n");
    CFStringBuiltInEncodings encoding = kCFStringEncodingUTF8;
    CFStringRef urlStr = CFStringCreateWithCString(kCFAllocatorDefault, "http://www.intel.com", encoding);
    CFURLRef url = CFURLCreateWithString(kCFAllocatorDefault, urlStr, NULL);
    
    //dynamic_kref_kotlinx_cinterop_CPointer urlPtr = {url};
    
    dynamic_symbols()->kotlin.root.GenerateThumbnailForURLkt(url);
    //dynamic_symbols()->DisposeStablePointer(urlPtr.pinned);
    return 0;
}
```
I saw this build error:
`./Example/Example/main.c:21:62: Passing 'CFURLRef' (aka 'const struct __CFURL *') to parameter of incompatible type 'dynamic_kref_kotlinx_cinterop_CPointer'`

I just pulled 865ae7c9d62cf3f289cff46b35dc2af2124b4cc1 and am retrying.  Will let you know how it goes.  Thanks

**Comment by desertjim** [comment]
I'm still seeing the same build error:
`Example/Example/main.c:20:62: Passing 'CFURLRef' (aka 'const struct __CFURL *') to parameter of incompatible type 'dynamic_kref_kotlinx_cinterop_CPointer'`

Here is what the generated dynamic_api.h contains:
```
#ifndef KONAN_DYNAMIC_H
#define KONAN_DYNAMIC_H
#ifdef __cplusplus
extern "C" {
#endif
typedef unsigned char   dynamic_KBoolean;
typedef char            dynamic_KByte;
typedef unsigned short  dynamic_KChar;
typedef short           dynamic_KShort;
typedef int             dynamic_KInt;
typedef long long       dynamic_KLong;
typedef float           dynamic_KFloat;
typedef double          dynamic_KDouble;
typedef void*           dynamic_KNativePtr;
struct dynamic_KType;
typedef struct dynamic_KType dynamic_KType;

typedef struct {
  dynamic_KNativePtr pinned;
} dynamic_kref_kotlinx_cinterop_CPointer;

typedef struct {
  /* Service functions. */
  void (*DisposeStablePointer)(dynamic_KNativePtr ptr);
  void (*DisposeString)(const char* string);
  dynamic_KBoolean (*IsInstance)(dynamic_KNativePtr ref, const dynamic_KType* type);

  /* User functions. */
  struct {
    struct {
      dynamic_KInt (*GenerateThumbnailForURLkt)(dynamic_kref_kotlinx_cinterop_CPointer p0 /* url */);
    } root;
  } kotlin;
} dynamic_ExportedSymbols;
extern dynamic_ExportedSymbols* dynamic_symbols(void);
#ifdef __cplusplus
}  /* extern "C" */
#endif
#endif  /* KONAN_DYNAMIC_H */
```

**Comment by olonho** [comment]
Did you rebuilt compiler? Looks like change wasn’t used.

**Comment by desertjim** [comment]
I ran the following commands to rebuild:
  514 ./gradlew clean
  515  git pull
  516  ./gradlew dependencies:update
  517  ./gradlew dist distPlatformLibs

**Comment by olonho** [comment]
For me for source code
```
import platform.CoreFoundation.CFURLRef
  
fun GenerateThumbnailForURLkt(url: CFURLRef): Int {
    println("received call")
    return 0
}
```
API file like this
```
typedef struct {
  /* Service functions. */
  void (*DisposeStablePointer)(dyn_KNativePtr ptr);
  void (*DisposeString)(const char* string);
  dyn_KBoolean (*IsInstance)(dyn_KNativePtr ref, const dyn_KType* type);

  /* User functions. */
  struct {
    struct {
      dyn_KInt (*GenerateThumbnailForURLkt)(void* url);
    } root;
  } kotlin;
} dyn_ExportedSymbols;
```
is produced with `./dist/bin/konanc dyn.kt -p dynamic -o dyn`.
Make sure, your source repo is after 1599eddfe108dcc27de71352805c026bb50e075c

**Comment by olonho** [comment]
From your output looks like 7b97916656646f5bad5dabb98f43665ef79842de is not in the tree as well.

**Comment by desertjim** [comment]
maybe gradlew clean didn't clean up everything?  I ended up just rechecking out the project and building from scratch.  It's working!  Thanks :)
