### ISSUE TITLE
Can't find dependent libraries - Windows 10

### ISSUE THREAD

**Issue by darkoverlordofdata** [JetBrains/kotlin-native#1252]
I downloaded the latest release 0.5, and I am able to build and run samples on Linux, but they fail on Windows 10:

> Downloading dependency: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-mingw-w64-x86-64.zip (0 bytes/17.8 kiBDownloading dependency: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-mingw-w64-x86-64.zip (17.8 kiB/17.8 kiB). Done.
> Extracting dependency: C:\Users\darko\.konan\cache\libffi-3.2.1-mingw-w64-x86-64.zip into C:\Users\darko\.konan\dependencies
> Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\darko\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.2.0-clang-llvm-5.0.0-windows-x86-64\bin\libclang.dll: Can't find dependent libraries
>         at java.lang.ClassLoader$NativeLibrary.load(Native Method)
>         at java.lang.ClassLoader.loadLibrary0(Unknown Source)
>         at java.lang.ClassLoader.loadLibrary(Unknown Source)
>         at java.lang.Runtime.load0(Unknown Source)
>         at java.lang.System.load(Unknown Source)
>         at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processLib(main.kt:301)
>         at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:33)
>         at org.jetbrains.kotlin.cli.utilities.MainKt.invokeCinterop(main.kt:94)
>         at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:117)

**Comment by olonho** [comment]
Could you please help us by figuring out which library is missing?

**Comment by darkoverlordofdata** [comment]
If I knew that...:)

it's failing on cinterop in the SDL example:
call cinterop -def "%DIR%\src\main\c_interop\sdl.def" -compilerOpts "%CFLAGS%" -target "%TARGET%" -o sdl || exit /b

when I rename my konanc folder to point back to release 0.3, it works again.

**Comment by darkoverlordofdata** [comment]
I skipped over release 0.4 due to the holidays. So I just tried that, and this is broken there as well, so it looks like the breakage starts in 0.4, not 0.5

**Comment by darkoverlordofdata** [comment]
The 0.4 issue was just a side effect from 0.5.
When I roll back to 0.34, compile, and them roll forward to 0.4 it works. 
But once 0.5 fails, rolling back to 0.4 also fails. I have to roll back to 0.34 to make it work again. So I'm currently working with 0.4

**Comment by vvlevchenko** [comment]
Indeed seems building with bat files is broken for some samples (for some samples build.bat present even if sample isn't enabled on platform). Thank you for reporting, as workaround you can use ``..\gradlew.bat run`` in sample you're interested.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/1262

**Comment by darkoverlordofdata** [comment]
works fine in version 0.6
