### ISSUE TITLE
error: can't produce platform.UIKit.UIView to framework API

### ISSUE THREAD

**Issue by argallo** [JetBrains/kotlin-native#1275]
My goal here is to use some platform specific libraries in kotlin and compile that into a framework for iOS.

```import kotlinx.cinterop.*
import platform.Foundation.*
import platform.UIKit.*

open class Test {

    fun uiTest(): UIView {
        return UIView()
    }

}
```

I have this kotlin file and a build file like this

```
buildscript {
ext.kotlin_native_version = '0.5'
repositories {
mavenCentral()
maven {
url "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
}
}
dependencies {
classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:$kotlin_native_version"
}
}

apply plugin: "konan"
konan.targets = ["iphone", "iphone_sim"]
konanArtifacts {
framework('nativeLibs')
}
```

If my kotlin file doesn't use any library specific calls then the Obj-c header file is generated properly and im able to use the framework in my xcode project. If I add in platform specific code like the uiTest function, then I get this error from gradle 

`error: can't produce platform.UIKit.UIView to framework API`

**Comment by SvyatoslavScherbina** [comment]
Types from platform libs (such as `UIView`) can't be produced to the framework API. Only pure-Kotlin types can be. So if a function uses platform type in its signature, please make it (or the containing class) `private` or `internal` to hide it from public API.
Is this solution applicable in your case?

**Comment by argallo** [comment]
Great this solved my issue thank you!

**Comment by gildor** [comment]
Will this be available someday?
I just have a very simple case: pass view to framework function and this function adds subviews

**Comment by SvyatoslavScherbina** [comment]
@gildor It is already supported in latest dev builds, and we are going to improve support for these cases quite soon: #1481
