### ISSUE TITLE
Compiling the hello world project with wingw (Illegal reflective access)

### ISSUE THREAD

**Issue by Frontrider** [JetBrains/kotlin-native#1281]
I tried running the hello world project, which yielded this error:

> "C:\Program Files\JetBrains\CLion 2017.3.3\bin\cmake\bin\cmake.exe" --build C:\Users\Jump\CLionProjects\untitled\cmake-build-debug-mingw --target HelloWorld.kexe -- -j 2
[ 33%] Generating CMakeFiles/HelloWorld_TEMP.kexe
KtFile: hello.kt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.text.StringFactory (file:/C:/Users/Jump/.konan/kotlin-native-windows-0.5/konan/lib/kotlin-compiler.jar) to constructor java.lang.String(char[],boolean)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.text.StringFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
CMakeFiles\HelloWorld.compile.dir\build.make:59: recipe for target 'CMakeFiles/HelloWorld_TEMP.kexe' failed
CMakeFiles\Makefile2:103: recipe for target 'CMakeFiles/HelloWorld.compile.dir/all' failed
CMakeFiles\Makefile2:78: recipe for target 'CMakeFiles/HelloWorld.kexe.dir/rule' failed
'rm' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe[3]: *** [CMakeFiles/HelloWorld_TEMP.kexe] Error 1
mingw32-make.exe[2]: *** [CMakeFiles/HelloWorld.compile.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles/HelloWorld.kexe.dir/rule] Error 2
mingw32-make.exe: *** [HelloWorld.kexe] Error 2
Makefile:117: recipe for target 'HelloWorld.kexe' failed

I would also note, that I am not good with c/c++ (one reason why I look out for kotlin), but I do have everything set up properly.

**Comment by olonho** [comment]
Thanks for the report, issue seems to come from combining CLion with MinGW, please use CLion on another platform, or use command line tools on MinGW for now. We are working on fixing it in upcoming releases.

**Comment by realtica** [comment]
I receive this error with a simple HelloWorld app:(CLion with C++ is ok)
"C:\Program Files\JetBrains\CLion 2018.1.3\bin\cmake\bin\cmake.exe" --build D:\projects\kntest1\cmake-build-debug --target HelloWorld.kexe -- -j 4
[ 33%] Generating CMakeFiles/HelloWorld_TEMP.kexe
mingw32-make.exe[3]: *** [CMakeFiles/HelloWorld_TEMP.kexe] Error -1073741515
CMakeFiles\HelloWorld.compile.dir\build.make:59: recipe for target 'CMakeFiles/HelloWorld_TEMP.kexe' failed
mingw32-make.exe[2]: *** [CMakeFiles/HelloWorld.compile.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles/HelloWorld.kexe.dir/rule] Error 2
CMakeFiles\Makefile2:103: recipe for target 'CMakeFiles/HelloWorld.compile.dir/all' failed
CMakeFiles\Makefile2:78: recipe for target 'CMakeFiles/HelloWorld.kexe.dir/rule' failed
mingw32-make.exe: *** [HelloWorld.kexe] Error 2
Makefile:117: recipe for target 'HelloWorld.kexe' failed
