### ISSUE TITLE
Inline val get with named arguments in different possitions doesn't seem to respect order

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1332]
I'm not sure if there is a problem with arithmetic in some cases. But I have run with 0.6 a common code that works on JVM and JS, and fails with Kotlin Native:

https://travis-ci.org/korlibs/klock/builds/341911113#L1191

You can check this PR to reproduce the problem: https://github.com/korlibs/klock/pull/3

**Comment by soywiz** [comment]
Now I have the exact reason for this:

```kotlin
//inline val Int.months get() = TimeDistance(months = this) // @TODO: Kotlin Native BUG: Generates TimeDistance(this), so sets years instead of months
inline val Int.months get() = TimeDistance(0, this) // Works with Kotlin Native 0.6

data class TimeDistance(val years: Int = 0, val months: Int = 0, val days: Double = 0.0, val hours: Double = 0.0, val minutes: Double = 0.0, val seconds: Double = 0.0, val milliseconds: Double = 0.0)
```

**Comment by homuroll** [comment]
Seems like bug happens during IR serialization/deserialization of the inline function.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/1367 shall fix it

**Comment by alexander-gorshenev** [comment]
#1367 has been integrated. Closing the issue.
