### ISSUE TITLE
konan -h or -help should print in stdout

### ISSUE THREAD

**Issue by kikitux** [JetBrains/kotlin-native#1334]
currently if I run konan -help or konan -h the output will be printed in stderr

some cli use stderr to print help when an incorrect input is given, but in this case -help or -h is valid

i think for cli the best user experience is use stdout for a valid command.

```
konan -help | grep targets
```

vs

```
konan -help 2>&1 | grep targets
```

Thanks
Alvaro.

**Comment by alexander-gorshenev** [comment]
This issue is now tracked at https://youtrack.jetbrains.com/issue/KT-23066 . 
One can subscribe as a watcher or vote there.
