### ISSUE TITLE
Compilation to WebAssembly is "too" optimized after switching from 0.5 to 0.6

### ISSUE THREAD

**Issue by boyanio** [JetBrains/kotlin-native#1339]
I have this very simple Kotlin file:

```
fun main(args: Array<String>) {
}

public fun feelingLucky(): Int {
  return rand(1, 101);
}

@SymbolName("Konan_js_rand")
external public fun rand(from: Int, to: Int): Int
```

When using Kotlin/Native 0.5 it produces quite a big wasm file, around 2MB. There I could inject `Konan_js_rand` from JavaScript, though, and call my function by `instance.exports["'kfun:feelingLucky$$ValueType'"]()`. However, after switching to Kotlin/Native 0.6, I cannot see these functions anymore - neither the import, nor the export. The cool thing is, the size of the wasm file is now down to ~150KB. Do I miss anything?

**Comment by aceisnotmycard** [comment]
You can mark your function with `Used` annotation to preserve it from deletion.
```Kotlin
@Used
public fun feelingLucky(): Int {
  return rand(1, 101);
}
```

**Comment by boyanio** [comment]
Fantastic, it works! :-)

**Comment by olonho** [comment]
Generally, we may want to implement mode similar to `-produce dynamic` for WASM case, along with `@JsName` annotation, specifying JavaScript name of exported symbols. But this is beyond scope of this issue,   I presume.
