### ISSUE TITLE
Using kotlin.math compiles to WebAssembly, but throws an exception on runtime

### ISSUE THREAD

**Issue by boyanio** [JetBrains/kotlin-native#1340]
I am experimenting a bit with compiling Kotlin to WebAssembly. I really like the small filesize in v0.6. Fantastic work! I am now trying to do some math in Kotlin, e.g.:

```
import kotlin.math.abs

@Used
public fun myAbs(): Double {
  return abs(PI)
}
```

This compiles fine, but throws an exception when calling the function. If I just return `PI`, it works fine.

![image](https://user-images.githubusercontent.com/980463/36354917-98a309f4-14db-11e8-8766-d1da7815bd56.png)

Do you have any idea what the problem is?

**Comment by olonho** [comment]
kotlin.math support is not present in v0.6, we're working on adding it in subsequent releases.

**Comment by boyanio** [comment]
Great, I will be following the upcoming releases (y)

**Comment by olonho** [comment]
Shall be fixed with https://github.com/JetBrains/kotlin-native/pull/1371
