### ISSUE TITLE
KN won't compile source code from another folder in a multiplatform way

### ISSUE THREAD

**Issue by Albert-Gao** [JetBrains/kotlin-native#1345]
I setup a multi platform project for sharing code between iOS and Android. 

- common: code
- android: android specific code
- ios: ios specific code

Android part works well, while the iOS part not. It seems that when it tries to compile, it won't compile the code in an MPP way. Even though I add it there.

This is the error I get:
```bash
:shared-ios:checkKonanCompiler
warning: duplicate source root: /Users/albertgao/codes/self/kotlin-native-mobile-multiplatform-example/Shared/common/main/xyz/albertgao/libs/Sample.kt
warning: duplicate source root: /Users/albertgao/codes/self/kotlin-native-mobile-multiplatform-example/Shared/common/main/xyz/albertgao/libs/Platform.kt
/Users/albertgao/codes/self/kotlin-native-mobile-multiplatform-example/Shared/common/main/xyz/albertgao/libs/Sample.kt:6:21: error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
@InlineOnly public inline operator fun <@OnlyInputTypes K, V> Map<out ???, String>.get(key: ???): String? defined in kotlin.collections
    return platform.get()
                    ^
main/xyz/albertgao/libs/Platform.kt:3:14: error: actual class 'Platform' has no corresponding members for expected class members:

    public final expect fun get(): String

actual class Platform actual constructor(
             ^
main/xyz/albertgao/libs/Platform.kt:6:14: error: actual function 'getPlatform' has no corresponding expected declaration
  actual fun getPlatform():String {
             ^
:shared-ios:compileKonanShared-iosIphone FAILED
```

This is my `ios` build.gradle:

```groovy
apply plugin: 'konan'

konanArtifacts {
    framework('shared-ios', targets: ['iphone', 'iphone_sim']) {
        srcDir '../common/main'
        srcDir 'main'


        enableDebug true
        enableMultiplatform true        
    }

    program('shared-ios-test') {
        srcDir 'test'
        commonSourceSet 'test'
        extraOpts '-tr'
    }
}

dependencies {
    expectedBy project(':shared-common')
}

task test(dependsOn: run)
```

The sample project could be found at https://github.com/Albert-Gao/kotlin-native-mobile-multiplatform-example

**Comment by ilmat192** [comment]
Looks like it's just a typo: the method returning a platform is named `get` in the `expect` class and `getPlatform` in the `actual` class for iOS. Note that you don't need to explicitly specify a path to common source as framework source directory so this line is unnecessary: `srcDir '../common/main'`.

Also here is a problem with testing. The test executable should use both common source sets: `main` and `test` but now Kotlin/Native Gradle plugin doesn't allow one to specify several common source sets for one artifact (this option will be added in the upcoming release). To work around it you may build a library using `main` common source set and then link it with the test executable:
```
    library('test-library') {
        enableMultiplatform true
        srcDir 'main'
    }

    program('shared-ios-test') {
        ...
        libraries {
            artifact 'test-library'
        }
    }
```
All the changes I suggested are in [this patch](https://gist.github.com/ilmat192/9e9dc79e291e3dbdc3897600b2dd7ebf).

**Comment by Albert-Gao** [comment]
Thanks so much ! Everything works perfectly now. Just one question, how could you know this? Where did you find the doc for the gradle plugin? I read that gradle-plugin.md, seems missing some details. I wanna know so that I could figure out in the future.

**Comment by ilmat192** [comment]
With [this](https://github.com/JetBrains/kotlin-native/pull/1348) pull request merged you will be able to set several common source sets for one artifact. In your case the 'test-library' artifact will be unnecessary and your test executable will look like this:
```
program('shared-ios-test') {
    srcDir 'test'
    srcDir 'main'
    enableMultiplatform true
    commonSourceSets 'main', 'test'
    extraOpts '-tr'
}
```
Of course such a manual creation of a test executable is pretty inconvenient so we are going to introduce a testing support similar to the Kotlin/JVM's one.

As for documentation, almost all available info about the Gradle plugin is located in the `GRADLE_PLUGIN.md` and in a tutorial [here](https://kotlinlang.org/docs/tutorials/native/gradle-for-kotlin-native.html). This documentation is more or less complete but, if you find some gap there, notify me and I'll update the doc.

**Comment by viteinfinite** [comment]
@ilmat192 Sorry for reopening this, but there is a behaviour I do not understand: why should `commonSourceSets` include `main`? Shouldn't it be already available to the program thanks to the fact that `enableMultiplatform` is activated?
Thank you in advance for your explanation 🙌
