### ISSUE TITLE
@Volatile

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/kotlin-native#1350]
`@kotlin.Volatile` is provided (but deprecated) while `@kotlin.jvm.Volatile` is not provided.

`@kotlin.jvm.Volatile` is

- Marked in the [standard library documentation](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-volatile/index.html) **not** platform-specific.
- Provided by the Javascript standard library.

**Comment by olonho** [comment]
This has to be discussed with library designers.

**Comment by ilya-g** [comment]
`kotlin.jvm.Volatile` is now declared as an "optional expectation" annotation in the common standard library, so it can be used in common code, but not in the specific platform only code where that annotation doesn't have actual part. 

At some point we'll remove `kotlin.jvm.Volatile` from JS standard library too, so it will be usable from JVM and common code only.
