### ISSUE TITLE
vararg not working inside library inline function

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/kotlin-native#1354]
This is a pernicious one as the compiler does **not** crash, but the produced executable is **incorrect**.
This is with master (e035ac1).

lib/src/main/kotlin/test/test.kt:
```kotlin
package test

fun count(vararg params: Int) = params.size

@Suppress("NOTHING_TO_INLINE")
inline fun getTwo() = count(21, 42)
```

app/src/main/kotlin/main.kt:
```kotlin
import test.getTwo

fun main(args: Array<String>) {
    println(getTwo())
}
```

Application result: `0`

Expected result: `2`

This bug **does not appear** if:
- The `getTwo` function is not inline
- The `getTwo` function is in the same module (i.e. in the app module instead of the lib module)

Note that all vararg functions are impacted, including the stdlib ones such as `arrayOf` and `listOf`, which makes me think that the problem is at the inlined call site.

**Comment by alexander-gorshenev** [comment]
Should have been be fixed by #1361
