### ISSUE TITLE
Add Support For FreeRTOS

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#1362]
Although Kotlin Native already supports an RTOS (Zephr) it would be very useful to add support for [FreeRTOS](https://www.freertos.org/) which is the most used RTOS for uCs (has very solid support for ARM), and other embedded devices. Amazon is the biggest backer of FreeRTOS and even provide their own [implementation](https://aws.amazon.com/freertos/). Licensing with FreeRTOS isn't a issue since it uses Mit (permissive license). Some of the major users of FreeRTOS include Amazon, Honeywell, and NASA. Most of the major uC manufacturers provide official support for FreeRTOS.

All of FreeRTOS (the core part) consists of just 3 C source files, which would mean that it should be reasonably straightforward for Kotlin Native to provide interop (**in theory**). Also there might be a valuable opportunity to develop support APIs to **"fill in the gaps"** as needed. How would the general Kotlin Native APIs (in development) fit into this? If FreeRTOS will be supported then a **Blinky** sample will need to be developed, followed by a **Weather Station** sample once full support and interop have been provided.

Very important to note that FreeRTOS provides concurrency out of the box (both [threads](https://www.freertos.org/Inter-Task-Communication.html) and [coroutines](https://www.freertos.org/croutine.html)). How would Kotlin's Coroutines fit in with FreeRTOS's Coroutines?

**Comment by olonho** [comment]
Nick, thanks for an interesting write up. It would be really nice to support more RTOSes in Kotlin/Native, and we welcome  contributions in that direction. Zephyr support was implemented to showcase technology and make platform support more flexible, and we believe, that adding support for additional embedded targets now could be now done by external contributors without much hassle.

**Comment by napperley** [comment]
Very little in the way of documentation to go with regarding LLVM support with FreeRTOS. Found this [article](https://polyfractal.com/post/rustl8710) which shows that LLVM does work with FreeRTOS, however it does raise some possible issues with interop. There are some rumours swirling around that the FreeRTOS API is macro heavy. If that is the case then that could throw interop into disarray.

**Comment by olonho** [comment]
Sure, cinterop extracts all macroses values automatically, see for example blinky demo in https://github.com/JetBrains/kotlin-native/pull/1349/files, i.e. in
```val port = LED0_GPIO_PORT
      val led = LED0_GPIO_PIN```
LED0_GPIO_PORT and LED0_GPIO_PIN are autoextracted from headers.

**Comment by napperley** [comment]
Unfortunately many of the defined Macros in FreeRTOS are more advanced than defining a constant, which according to the Kotlin Native [interop document](https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#macros) isn't supported (unless the documentation is out of date).

**Comment by sbogolepov** [comment]
We are migrating to YouTrack, so I'm closing this issue. Feel free to [open](https://kotl.in/issue) a new one on YouTrack or share your ideas in [KT-43974](https://youtrack.jetbrains.com/issue/KT-43974).
