### ISSUE TITLE
Symantec Reputation

### ISSUE THREAD

**Issue by dpomada** [JetBrains/kotlin-native#1372]
![symantec](https://user-images.githubusercontent.com/15732201/36799911-3f3cdd56-1c7c-11e8-899b-e25fd687f1ba.png)

I have downloaded the release and I was unable to used on windows because Symantec have detected some risk on the dll files

**Comment by olonho** [comment]
Guess this is Symantec's bug, reported them false positive.

**Comment by olonho** [comment]
In relation to submission 77257.

Upon further analysis and investigation we have verified your submission and as such this detection will be removed from our products.

The updated detection will be distributed in the next set of virus definitions, available via LiveUpdate or from our website at https://www.symantec.com/security_response/definitions.jsp

**Comment by olonho** [comment]
Above is from Symantec.
