### ISSUE TITLE
Kotlin Exception Handling in iOS Framework

### ISSUE THREAD

**Issue by jguerinet** [JetBrains/kotlin-native#1382]
Hello, 

I was wondering if/how exceptions originating from the Kotlin code should be handled within the native iOS code (Obj-C and/or Swift). Before Kotlin-Native I was using j2objc to transpile my Java code into Obj-C, and while I couldn't catch exceptions within Swift I could catch them within Obj-C using the following format: 
```
+ (JavaException *)catchException:(void(^)(void))block {
    @try {
        if (block) {
            block();
        }
    } @catch (JavaException *e) {
        return e;
    }
    return nil;
}
```
Calling this method from the Swift side and passing it a block of code that could potentially have an exception be raised allowed me to run that block, and get back the caught exception if any. 

Unfortunately it seems like exceptions originating from the Kotlin-Native produced framework are immune to my try/catch above. If an exception is raised, the app always crashes with the  `Uncaught Kotlin exception` error message, even when run through this block. 

Is there a way to catch these exceptions from within the iOS code?

Thanks!

**Comment by olonho** [comment]
Support for exception translated is planned, but not yet here.

**Comment by jguerinet** [comment]
Thanks for your response. Do you have any sense of what kind of time frame they would be planned for? I'm wondering whether to restructure my codebase to not rely as heavily on Exceptions if they won't be supported for a long period of time, or if it's better to just wait it out for now.

**Comment by olonho** [comment]
We hope to included that into upcoming release.

**Comment by SvyatoslavScherbina** [comment]
Starting from 0.7-dev-1447 version, if method is marked with `@Throws` annotation, exceptions thrown out of this method are converted to `NSError*` when calling from Objective-C and thrown as errors when calling from Swift.

**Comment by ScottPierce** [comment]
Out of curiosity, why force the method to be marked with `@Throws`? Why not have this behavior by default? It seems error prone to have such core functionality behind an annotation.

**Comment by SvyatoslavScherbina** [comment]
Because otherwise calling **any** Kotlin code from Swift would require to specify some kind of error handling at call site, e.g. `try!` or `try?` or `do ... catch`. Doesn't this seem to be much more error prone?

Also the requirement to mark method with `@Throws` annotation is quite similar to what we have in interop from Java to Kotlin/JVM: https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#checked-exceptions
