### ISSUE TITLE
[cinterop] escape invalid keyword chars in package name

### ISSUE THREAD

**Issue by youta1119** [JetBrains/kotlin-native#1383]
Hello. I fount a bug. 🐛 
if `pkgName` contains invalid identifier chars, compile fail with an error like this.

```
build/invalid-build/kotlin/example-lib/example-lib.kt:3:16: error: expecting a top level declaration
package example-lib
               ^
build/invalid-build/kotlin/example-lib/example-lib.kt:3:17: error: expecting a top level declaration
package example-lib
                ^
build/invalid-build/kotlin/example-lib/example-lib.kt:5:1: error: expecting a top level declaration
import konan.SymbolName
```

I have created example project. please see it.
https://github.com/youta1119/kotlin-native-c-interop-bug

**Comment by olonho** [comment]
Why not use another package name?

**Comment by youta1119** [comment]
@olonho 
Certainly using another package name will solve this problem.
But currently no  any document about package name constraint. (I took many time to notice that the package name caused an error.)
So I want to  that cinterop will escape the package name.

**Comment by olonho** [comment]
Not sure we shall do such a mangling. Maybe just compiler error is better.

**Comment by youta1119** [comment]
#1382 has been merged so close this issue.
