### ISSUE TITLE
Implementing callback from exported shared library

### ISSUE THREAD

**Issue by kkalisz** [JetBrains/kotlin-native#1395]
Hi I am testing different usage of kotlin native.

For now i'm trying to export shared library and use it in other project.
I have two declarations:

```
interface Callback{
    fun back(value: String)
}

class Engine(val callback: Callback)
```

after build ExportedSymbols in header file looks like this:

```
typedef struct {
  libnativetictactoe_KNativePtr pinned;
} libnativetictactoe_kref_Callback;
typedef struct {
  libnativetictactoe_KNativePtr pinned;
} libnativetictactoe_kref_Engine;


typedef struct {
  /* Service functions. */
  void (*DisposeStablePointer)(libnativetictactoe_KNativePtr ptr);
  void (*DisposeString)(const char* string);
  libnativetictactoe_KBoolean (*IsInstance)(libnativetictactoe_KNativePtr ref, const libnativetictactoe_KType* type);

  /* User functions. */
  struct {
    struct {
      struct {
        libnativetictactoe_KType* (*_type)(void);
        void (*back)(libnativetictactoe_kref_Callback thiz, const char* value);
      } Callback;
      struct {
        libnativetictactoe_KType* (*_type)(void);
        libnativetictactoe_kref_Engine (*Engine)(libnativetictactoe_kref_Callback callback);
        libnativetictactoe_kref_Callback (*get_callback)(libnativetictactoe_kref_Engine thiz);
      } Engine;
    } root;
  } kotlin;
} libnativetictactoe_ExportedSymbols;
```
To create Engine I need libnativetictactoe_kref_Callback, but i don't see any possibility to create proper 
libnativetictactoe_kref_Callback or Callback implementation. Am I missing something ?

How would be proper way to create implementation of Callback?

**Comment by olonho** [comment]
You need to have an API that creates Callback in your code, so that it is exported. Shared library is produced only from sources you pass during compile time, so export all APIs you need.

**Comment by kkalisz** [comment]
Hi Thanks for replay.
If I create API that create my Callback instance in sources everything is working fine, but my goal is provide two way communication. I Would like to create callback instance outside library and pass it as parameter for Engine.  I'm aware that this might not be as simple as it looks.

Is this scenario  even posible ?
If not what is proper way of implementing "callbacks"

**Comment by olonho** [comment]
Kotlin/Native has closed world philosophy, which means you cannot create objects outside of framework and pass it inside. What you could do, is use C structures/callbacks as an interface between multiple Kotlin/Native or Kotlin/Native and C worlds.
