### ISSUE TITLE
Cannot set iOS Framework method or class prefix

### ISSUE THREAD

**Issue by markuscraig** [JetBrains/kotlin-native#1396]
When producing an iOS 'framework', each method and class name is automatically prefixed with 3 letters derived from the framework name.  For example, a gradle 'framework("MyCustomFramework")' prefixes the public framework methods and classes with "MCF".

I need to be able to override the prefix.  Is this possible today?

**Comment by markuscraig** [comment]
In order to use Kotlin-Native at work to replace our existing iOS / Android SDK's, I need to create drop-in replacements for our existing iOS .framework and Android .aar files (to match our existing API's).  This is why I need to set a custom method / class prefix.  Our existing code does not match the KN generated class / method names.

**Comment by markuscraig** [comment]
It looks like I would need to change this function in `ObjCExportNamer.kt` to be overridden via the Kotlin-Native gradle plugin.  Is this the recommended way of doing this?  Are there any similar prior examples?  Thanks!

* https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExportNamer.kt#L427-L435

**Comment by SvyatoslavScherbina** [comment]
@markuscraig as you can see, prefix is derived from the module name, and you can set the module name explicitly with `-module_name` compiler option, e.g.:
```
framework("MyCustomFramework") {
    extraOpts '-module_name', 'TheName'
}
```

**Comment by markuscraig** [comment]
Thanks, works great!
