### ISSUE TITLE
Custom LLVM options for iOS Bitcode Framework?

### ISSUE THREAD

**Issue by markuscraig** [JetBrains/kotlin-native#1408]
For any developer that creates iOS SDK's (frameworks) for other companies, we need to support bitcode frameworks for some customers.  We also need to select a tech stack that hedges against Apple suddenly requiring bitcode for iOS.  I'm currently evaluating K/N, and this is the only limitation blocking me from selecting K/N.

The Rust team just got this working over the last 2 days...

* https://github.com/rust-lang/rust/pull/48896

Can this be achieved by setting the LLVM '-fembed-bitcode' option?  Is there any way to set custom LLVM options during K/N compilation?  Thanks!

**Comment by olonho** [comment]
@markuscraig would you be interested in developing this feature for K/N? We would love to help with reviewing and submitting the code.

**Comment by markuscraig** [comment]
@olonho I think that would be great.  I'll start diving into the code and see about adding this.  I could use any high-level pointers from you and team about how you would like to see this implemented.  Thanks!

**Comment by olonho** [comment]
Guess you could follow Rust's PR you mentioned above, and put relevant code in https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/IrToBitcode.kt

**Comment by SvyatoslavScherbina** [comment]
Bitcode in frameworks is fully supported in 1.3.50.
