### ISSUE TITLE
How to include iPhone and iPhone_sim framework in one project

### ISSUE THREAD

**Issue by StefMa** [JetBrains/kotlin-native#1410]
We have a little "shared" library for one of our projects.
These library uses Kotlin/Native to build a `jar` for the Android App and a `Framework` for the iPhone App. We generate the jar/Framework and include it manually in our projects.
That works and we are happy with the result.

But since the iOS Framework should be either a **target: iphone** or a **target: iphone_sim** it leads to some trouble with these **two** Frameworks.

Is is possible to create ONE Framework which includes both targets? So that the Framework can be used on real devices **and** on Simulators?
If not, what is a good process to "seamlessly" switch between these two while developing?!

**Comment by olonho** [comment]
Does https://medium.com/wireless-registry-engineering/create-a-universal-fat-swift-framework-b7409bbfa18f helps?

**Comment by StefMa** [comment]
Thank you @olonho! Yes that help. 
Didn't know that it is a common "issue" in the iOS world 😅

Closed since its not really related to K/N
