### ISSUE TITLE
Incremental compilation

### ISSUE THREAD

**Issue by J-Rojas** [JetBrains/kotlin-native#1437]
I've noticed that if I change one file with trivial changes and no downstream dependencies in my Kotlin project, the entire project is recompiled. 

Build times are substantially long for a medium sized project with about 30 files. 

Can Konan support incremental compilation similar to the standard Kotlin compiler?

**Comment by olonho** [comment]
I would suggest to use separation of your program to multiple .klibs, probably by dividing it into logically separated modules. Then recompilation shall speed up.

**Comment by J-Rojas** [comment]
I'm using a MPP. The slowdown derives from the use of `expectedBy project(':common')` which brings in all of the source code for that module. I'd have to break up my common module into modules that do not contain actual/expect declarations, which would be difficult to extract cleanly. I'm thinking of abandoning expect/actual for delegation to avoid this build dependency problem.

**Comment by SvyatoslavScherbina** [comment]
Closing as superseded with https://youtrack.jetbrains.com/issue/KT-42294.
