### ISSUE TITLE
data class could be translated to struct for iOS

### ISSUE THREAD

**Issue by jitinsharma** [JetBrains/kotlin-native#1441]
I compiled a kotlin code with data classes to .framework and imported to xcode. The data classes are converted to swift class with a `doCopy` method. I was wondering if it would be better to convert them to `struct` since structs are similar in concept to data classes.

**Comment by dnedrow** [comment]
So long as you don’t need to call your strict from Objective-C, you should be OK.

**Comment by StefMa** [comment]
Don't know if it worth. But what about add a compiler flag like
'objectivec' and 'swift'?

Just a dumb idea from an android developer 😂
As I said don't know if it worth it. If there are already some more things
like that...

**Comment by jitinsharma** [comment]
@olonho Understood. Makes sense since swift structs will not work with Objective-C but it would be a nice to have thing. 
@StefMa +1
Structs allow creating a copy using assignment operator which looks more idiomatic versus `doCopy` method in Swift class where all parameters of the function are necessary.

**Comment by SvyatoslavScherbina** [comment]
> structs are similar in concept to data classes.

They might serve the similar purposes, but from the language point of view structs are very different from data classes.

Data classes have identity, structs don't.
Data classes are passed by reference, structs are passed by value.

Generally data classes are just classes with specific syntactic sugar and a couple of limitations.

> The data classes are converted to swift class with a `doCopy` method. I was wondering if it would be better to convert them to `struct`

Why would this be better? What specific problem is this supposed to solve?

**Comment by SvyatoslavScherbina** [comment]
Got no response, closing.
