### ISSUE TITLE
gradle plugin crashes

### ISSUE THREAD

**Issue by liketechnik** [JetBrains/kotlin-native#1442]
When trying to follow the example for the gradle plugin for kotlin native (https://kotlinlang.org/docs/tutorials/native/gradle-for-kotlin-native.html), gradle crashes with the following error: 
```florian@florian-pc  ~/Daten/Programmieren/kotlinNativeTest  gradle 
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/florian/Daten/Programmieren/kotlinNativeTest/build.gradle' line: 13

* What went wrong:
A problem occurred evaluating root project 'kotlinNativeTest'.
> org.gradle.api.internal.GradleInternal.getExperimentalFeatures()Lorg/gradle/api/internal/ExperimentalFeatures;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

All files are equal to the ones posted in the link, except the target platform I changed to linux to match my OS.
I'm running gradle version 4.6 with Java 8 (JDK, Update 162) on Gentoo Linux and I just don't get where my mistake is or why this is not working, so I appreciate any help.
If needed, I can post any additional info or run gradle with ```--info``` and ```--debug``` option and post the output, just tell me, but I would really like to be able to use kotlin/native.

**Comment by ilmat192** [comment]
Looks like you've got a development version of the Gradle plugin. Try to explicitly specify the latest release version. Just replace in `/home/florian/Daten/Programmieren/kotlinNativeTest/build.gradle`
```
classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:+"
```
with
```
classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:0.6.2"
```

**Comment by liketechnik** [comment]
It is working now (although I had to install ncurses to get it work), thank you very much. Do you think the tutorial should somehow mention that it's problematic to use '+' for the version and one should instead specify the latest stable version? Where could I propose such a change?

**Comment by StefMa** [comment]
Using a  `+` in gradle is always not recommended and should be avoided.

You can simply click the "Edit page" on the mentioned site and create a PR:
![bildschirmfoto 2018-03-26 um 11 37 48](https://user-images.githubusercontent.com/10229883/37898867-3f7c4964-30ea-11e8-8b92-c2af5a9a6a87.png)

You can take also a look at this site https://kotlinlang.org/docs/reference/using-gradle.html which seems got automatically updates for new versions...
So maybe a automating process would be great here 👍 

Anyway. Kotlin/Native is in active development and maybe such a change would only make sense if it has reached at last it's first stable release version...

**Comment by liketechnik** [comment]
> Kotlin/Native is in active development and maybe such a change would only make sense if it has reached at last it's first stable release version...
Yes, probably right. Anyway, I think I'm going to take a look at it, because it's quite frustrating if you want to try it out and it crashes _without any reason_.

(Closing this now, because my issue is resolved and I've no further questions.)
