### ISSUE TITLE
Lower deployment target

### ISSUE THREAD

**Issue by Iliasvw** [JetBrains/kotlin-native#1460]
Hello

I am currently trying to build a project with the Kotlin Native plugin to use Kotlin for cross-platform development. It's working quite well but I do have one problem. In Xcode, the development target is 11.2. When I lower the development target too something below 11.0, all the builds will fail and running on emulator and a real device won't work.

The error I got is:
"Undefined symbols for architecture armv7:
"OBJC_CLASS$_SOSSample", referenced from:
objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

Does Kotlin Native not support the armv7? Maybe somebody that has any fix?

Thanks in advance
Ilias

**Comment by olonho** [comment]
Probably, there was a reason why deployment target was set to 11.0 then.

**Comment by Iliasvw** [comment]
The deployment target was set to 11.2 which was the most recent version available in Xcode, this is standard in Xcode.

**Comment by Iliasvw** [comment]
Thanks for the answer! Explains a lot.
