### ISSUE TITLE
"Parser" field in iOS project crashes app

### ISSUE THREAD

**Issue by sdetilly** [JetBrains/kotlin-native#1461]
I am unable to run the app in xcode. I can compile and build the project fine, but there seems to be an error with line 32 
`private let parser = KAPPartialParser(composer: KAPCalculator(), partialComposer: PartialRenderer())
`
I am not an expert in iOS development, but there doesn't seem to be any stacktraces. The only error I am getting is `Thread 1: EXC_BAD_ACCESS (code=1, address=0x1c)`

Everything runs fine on android

**Comment by olonho** [comment]
80d026afa5a5081b7a8cb2bf2561756df88a9507 shall fix it. Please try the current master.

**Comment by sdetilly** [comment]
I still have the same error after I pulled and re-run. Should I redo the gradle commands?

**Comment by olonho** [comment]
Do you run git repo or 0.6.2 release?

**Comment by olonho** [comment]
Please try with release downloaded from https://github.com/JetBrains/kotlin-native/releases/tag/v0.6.2

**Comment by sdetilly** [comment]
Somehow, it works now! Thank you very much
