### ISSUE TITLE
Hello World project cannot compile in CLion under Windows

### ISSUE THREAD

**Issue by windoze** [JetBrains/kotlin-native#1463]
My box has following software installed:
OS: Windows 10 1709 64bit
CLion 2018.1
Kotlin/Native plugin 181.4203.549

I created a simple Hello World project in K/N, but CLion cannot load the CMake project, the error message is:
```
CMake Error at KotlinCMakeModule/CMakeKotlinInformation.cmake:144 (message):
  Unsupported host target
Call Stack (most recent call first):
  KotlinCMakeModule/CMakeKotlinInformation.cmake:186 (prepare_konanc_args)
  CMakeLists.txt:7 (konanc_executable)
```

I checked CMakeKotlinInformation.cmake and found it doesn't configure target for WIN32:
```
    if (NOT KONANC_TARGET)
        if (APPLE)
            set(KONANC_TARGET macbook)
        elseif (UNIX)
            set(KONANC_TARGET linux)
        else ()
            message(FATAL_ERROR "Unsupported host target")
        endif ()
    endif ()
```

So I added `-D KONANC_TARGET=mingw` in CMake command line, and the project was successfully loaded.
But when I build the project, it shows another error message:
```
CMake Error at KotlinCMakeModule/CMakeKotlinInformation.cmake:144 (message):
  Unsupported host target
Call Stack (most recent call first):
  KotlinCMakeModule/CMakeKotlinInformation.cmake:186 (prepare_konanc_args)
  CMakeLists.txt:7 (konanc_executable)
```

Did I do anything wrong?

**Comment by olonho** [comment]
CLion on Windows is not support in combination with CMake. Gradle support in CLion will fix the problem.

**Comment by windoze** [comment]
@olonho thanks for the confirmation.
Is the gradle plugin usable now? Or any test version I can start with?

**Comment by Scellow** [comment]
@windoze check this https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md
