### ISSUE TITLE
Atomic variables on native platform

### ISSUE THREAD

**Issue by barsan-md** [JetBrains/kotlin-native#1472]
I was wondering if the Atomic variables will be available on the native platform. By looking at the [documentation](https://github.com/Kotlin/kotlinx.atomicfu/blob/master/atomicfu/src/main/kotlin/kotlinx/atomicfu/AtomicFU.kt#L79) now, it seems that the only purpose of AtomicSomething classes is to map to some equivalent in Java so the question is: is this library common among the platforms targeted by Kotlin?

Sorry for having opened an [issue](https://github.com/Kotlin/kotlinx.atomicfu/issues/2) on kotlinx.atomicfu, it passed unoticed though.

**Comment by olonho** [comment]
Interop with C functions atomically updating memory locations is available in K/N. For example on macOS functions like `OSAtomicIncrement32()` are there in platform libs already.

**Comment by barsan-ds** [comment]
Does this mean that the library linked will only target the JVM?

**Comment by olonho** [comment]
Probably yes, ask library devs.

**Comment by olonho** [comment]
More of a libraries issue, closing.
