### ISSUE TITLE
Vararg parameter with no arguments at call site produces NULL reference in K/N

### ISSUE THREAD

**Issue by J-Rojas** [JetBrains/kotlin-native#1476]
I've noticed a difference between Kotlin Native and Kotlin JVM. In JVM, `vararg` will always produce an Array regardless of the number of arguments provided. So no arguments produces an Array of 0 items. In K/N however, the `vararg` will be a NULL value when no arguments are passed, even if the vararg is a non-optional. The expected behavior would be to produce an Array of 0 items. I've had to change my common code to use optionals in the vararg parameters to account for this difference between the two compilers.

**Comment by olonho** [comment]
Could you please provide testcase and expected behavior.

**Comment by J-Rojas** [comment]
I will provide one soon, sorry for the delay.

**Comment by J-Rojas** [comment]
The specific case that fails is with variadic methods using arguments with default values.

```
fun variadicFunc(statement: String = "", vararg arguments: Any) {
    if (arguments != null) {
            print("$statement ")
            arguments.forEach {
                print("$it")
            }
            println(", Correct!")
        } else {
            println("Failed!")
        }
}

variadicFunc("Hello")
variadicFunc("Hello", "World")
variadicFunc("") //this fails in Kotlin Native, but works in Kotlin JVM
```

**Comment by olonho** [comment]
Fix is available and being tested.

**Comment by homuroll** [comment]
Fixed in master
