### ISSUE TITLE
Move documentation to... docs/ ? 

### ISSUE THREAD

**Issue by StefMa** [JetBrains/kotlin-native#1483]
The `*.MD` files get more and more. 
And half of the top-level repository contains documentation.

I don't know if it worth it or if it make sense.
But what about to moving all the files into a subdirectory called `docs/`? 🤔 
The repository will look a little bit cleaner in my opinion.

The done site?
Most of new users will maybe not see that docs directory and think that you don't provide any docs...

**Comment by olonho** [comment]
Yes, we discussed that approach and believe that current layout allows easier navigation to docs.
