### ISSUE TITLE
Is Kotlin/Native Support Classes in JDK?

### ISSUE THREAD

**Issue by yangtianlehfut** [JetBrains/kotlin-native#1485]
In Kotlin/JVM project, Kotlin can call the function in JDK, but in Kotlin/Native project, it seems can't find the classes in JDK, such as classes in java.lang. And the Kotlin/JVM seems don't support external jar libs too, according to [issues 1212](https://github.com/JetBrains/kotlin-native/issues/1212). Is Kotlin/JVM project can only use Kotlin and native language such as C/C++

**Comment by olonho** [comment]
No, Kotlin/Native is a Kotlin compiler, not JVM Ahead Of Time compiler or smth like that. So you could easily interop with C/Objective-C/Swift.

**Comment by yangtianlehfut** [comment]
Thank you for response.

Is it means that Kotlin/Native and Kotlin/JVM is just with the same Kotlin grammar， and the compiler, running environment is difference？ Similar to DSL slightly， right？

**Comment by olonho** [comment]
It is compiler to machine code, not to JVM or JS bytecode.
