### ISSUE TITLE
Some thoughts about the MPP readme

### ISSUE THREAD

**Issue by StefMa** [JetBrains/kotlin-native#1493]
Today I found the time to create a MPP project based on your MPP documentation:
https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md

As a Android Dev (and iOS nooby) I had some issues with setup the Xcode project correctly:
* I've created a new Xcode project called "multiplatform" in the created `iosApp/`. That leads to the fact that Xcode create a new dir inside this dir (`iosApp/multiplatform/*`). 

Recommendation: 
Either don't create the `iosApp/` dir from the beginning (but then I would also do not create the `androidApp/` dir). Or explitice say that you have to create the Xcode project inside the root dir and name it iosApp/ (that leads to the fact that Xcode will create the project inside the iosApp/ dir).

* Section 4 of the Xcode project settings says:
> Select the Build phases tab and remove all default phases except Target Dependencies.

If done that and it looks like that now:
![bildschirmfoto 2018-04-12 um 16 04 10](https://user-images.githubusercontent.com/10229883/38682363-2f625cf6-3e6b-11e8-81f0-4e91cca0986a.png)
But if I run the app now it crashes directly with:
> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'Main' in bundle NSBundle

**Update**
I just found out that I have to select the Greetings framework and have to remove the things there:
![bildschirmfoto 2018-04-12 um 16 24 07](https://user-images.githubusercontent.com/10229883/38683543-07115178-3e6e-11e8-95e8-24a6593b8784.png)
Everything works now. 👍 

Recommendation:
I think I've removed something which put the Main storyboard into the NSBundle (or something like that). I think the documentation is wrong here?! 🤔 

* Section 3 says that we have to use either `xxxxIos_x64`  or `xxxx Ios_arm64` based on the device (simulator or real device).
In real world I want to switch my device based without changing the `KONAN_TASK` there.

Recommendation:
In the calculator it is a little bit different. I don't know it exactly anymore. But there it will switch automatically. Based on the device. I would add this logic here too...

Other than that:
It works 🎉 
Good job 👍

**Comment by ilmat192** [comment]
@StefMa I've reworded these points in the multiplatform readme: https://github.com/JetBrains/kotlin-native/pull/1503, please take a look.

**Comment by StefMa** [comment]
Close since #1503 address everything I mentioned and will be hopefully merged soon ☺
