### ISSUE TITLE
typealias fails on resolving

### ISSUE THREAD

**Issue by skoky** [JetBrains/kotlin-native#1498]
The *cinterop* fails on typealias errors unresolved dependencies:

```
mylaps-build/kotlin/kotlin/kotlin.kt:2484:32: error: unresolved reference: _MDP_NOTIFY_TYPE
typealias MDP_NOTIFY_TYPEVar = _MDP_NOTIFY_TYPE.Var
```                               

The type `_MDP_NOTIFY_TYPE` is defined in header file like this:

```
typedef enum _MDP_NOTIFY_TYPE {
	MDP_NOTIFY_SELECT,	
	MDP_NOTIFY_INSERT,	
	MDP_NOTIFY_UPDATE,	
	MDP_NOTIFY_DELETE,	
	MDP_NOTIFY_CLEAR	
} MDP_NOTIFY_TYPE;
```

and it is not present in .kt file

**Comment by olonho** [comment]
Not sure how to reproduce that. With bug.h like that
```typedef enum _MDP_NOTIFY_TYPE {
	MDP_NOTIFY_SELECT,	
	MDP_NOTIFY_INSERT,	
	MDP_NOTIFY_UPDATE,	
	MDP_NOTIFY_DELETE,	
	MDP_NOTIFY_CLEAR	
} MDP_NOTIFY_TYPE;```
and running cinterop like that `cinterop -h bug.h -compilerOpts "-I." -o bug -pkg bug` I'm getting Kotlin bindings which look sensible:
```
@file:kotlinx.cinterop.InteropStubs
@file:Suppress("UNUSED_VARIABLE", "UNUSED_EXPRESSION")
package `bug`

import konan.SymbolName
import kotlinx.cinterop.*

// NOTE THIS FILE IS AUTO-GENERATED

enum class _MDP_NOTIFY_TYPE(override val value: Int) : CEnum {
    MDP_NOTIFY_SELECT(0),
    MDP_NOTIFY_INSERT(1),
    MDP_NOTIFY_UPDATE(2),
    MDP_NOTIFY_DELETE(3),
    MDP_NOTIFY_CLEAR(4),
    ;
    
    companion object {
        fun byValue(value: Int) = _MDP_NOTIFY_TYPE.values().find { it.value == value }!!
    }
    
    class Var(rawPtr: NativePtr) : CEnumVar(rawPtr) {
        companion object : Type(IntVar.size.toInt())
        var value: _MDP_NOTIFY_TYPE
            get() = byValue(this.reinterpret<IntVar>().value)
            set(value) { this.reinterpret<IntVar>().value = value.value }
    }
}

typealias MDP_NOTIFY_TYPEVar = _MDP_NOTIFY_TYPE.Var
typealias MDP_NOTIFY_TYPE = _MDP_NOTIFY_TYPE
```
Do you have any other context which is missed from the report?

**Comment by skoky** [comment]
Well, I can reproduce it if the file is called "kotlin.def".  If I change it to something else, it works fine. I will close the issue.
