### ISSUE TITLE
java.lang.UnsupportedOperationException on missing empty dir permanently breaks the build

### ISSUE THREAD

**Issue by thevery** [JetBrains/kotlin-native#1500]
1) Download and unpack 0.6.2
2) Go to samples dir and build calculator `./gradlew calculator:build` - build ok
3) Remove `klib/common/stdlib/targets/iphone/included` (NB: folder is actually empty!)
4) Clean build again `./gradlew calculator:build` - build failed
5) Restore removed folder, build again - still failed

OSX 10.13.4, Xcode 9.3

**Comment by olonho** [comment]
Not sure if fiddling with K/N internal dirs is supported mode of operations.

**Comment by olonho** [comment]
Shall be fixed with  688b3f26f2b529b8eb38daf1a4b888bd8f780cd1
