### ISSUE TITLE
library search path

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1534]
For include files, I can set search path from environment variable, like this:
```
konanArtifacts {
    interop('libcurl') {
        target('mingw') {
            includeDirs "${System.getenv("MSYS2_DIR")?:"c:/msys64"}/mingw64/include"
        }
    }
}
```

But cannot find similar setting for library path.

**Comment by alexander-gorshenev** [comment]
Could you elaborate a little? 
What's your scenario, and what library path are we talking about?

**Comment by msink** [comment]
Well, from beginning - on windows Kotlin/Native uses LLVM, based on trimmed version of MSYS2 package.
MSYS2 is normal distribution with package manager - pacman - ported from ArchLinux, but to use it one need full version of MSYS2, installed somewhere on local disk.
By default it installs to `c:\msys64`, but sometimes installing to `C:` is not possible, and user can select any other path. So instead of hardcoding  `c:\msys64` - better use some evvar like %MSYS2%.
Then installed packages will be accesible in `%MSYS2%/mingw64/include` and `%MSYS2%/mingw64/lib` for headers and libraries respectively.

**Comment by msink** [comment]
In `interop` artifacts `linkerOpts` from gradle DSL really does not work - not appended to `manifest.properties` line.

But really `.klib` should be self-contained and include all the `.a` and `.so/.dlib/.dll`, instead of depending on user environment.
For this use case `linkerOpts` don't work too - `libraryPaths` from `.def` don't see it.

**Comment by olonho** [comment]
Static libraries could be integrated into the .klib, but putting .so/.dll is actually harder, as they may have deps on their own, and we do not want to duplicate native deps management systems.

**Comment by msink** [comment]
OK, let's start with static libraries :)
How to set `libraryPaths` from gradle?

**Comment by olonho** [comment]
Just set it with `linkerOpts`, it shall not go to the manifest (as on user machine it could be somewhere else). And `extraOpts '-includeBinary', 'mylib'` to include a binary to the .klib.

**Comment by msink** [comment]
I still do not undestand how to handle native dependencies.
As example for libcurl:
```
>pkg-config libcurl --libs
-LF:/msys64/mingw64/lib -lcurl

>pkg-config libcurl --libs --static
-LF:/msys64/mingw64/lib -lcurl -lnghttp2 -lidn2 -lssh2 -lssl -lcrypto -lssl -lcrypto -lgdi32 -lcrypt32 -lwldap32 -lz -lws2_32
```

So dynamic linking is easy, but require 11 (одиннадцать!!!) .dll in runtime.

How to handle staic case - I have no idea.

**Comment by olonho** [comment]
Approach is same as with C or C++. You say what binary depends on in the `.def`, while use `linkerOpts` in gradle/CLI to specify where to find those in compile time. In the runtime - it is same as well, have dynamic libs in system search path, or just works if linked statically.

**Comment by msink** [comment]
In C world, typical Makefile gets that options from `pkg-config`.

In K/N for now I can do, in link time:
``` gradle
def libs = "${System.getenv("MSYS2_DIR")?:"c:/msys64/mingw64"}/bin/pkg-config libcurl --libs".execute()
libs.waitFor()
def libsFlags = libs.in.text.trim().tokenize(' ')

konanArtifacts {
    program('Curl') {
        dependsOn ':libcurl:publish'
        dependencies {
            artifactCurl 'org.jetbrains.kotlin.native:libcurl:1.0'
        }
        target('mingw') {
            linkerOpts libsFlags
        }
    }
}
```

It works as temporary workaround, but IMHO there should be direct support for this in cinterop tool and in gradle plugin.

**Comment by SvyatoslavScherbina** [comment]
This issue is mostly not actionable. `pkg-config` support is discussed in #3484.
