### ISSUE TITLE
Explicitly ignore designated super constructor check

### ISSUE THREAD

**Issue by kpgalligan** [JetBrains/kotlin-native#1539]
This change blows up Objective-C code that doesn't explicitly mark a designated constructor.

https://github.com/JetBrains/kotlin-native/commit/8371ac137fa3a3bdd0e967ecab5543844b4651bd#diff-4fbff1fd1ac95615545d03980ba283a4R521

For old code and/or generated code, trying to go back and make changes is problematic. Our code in particular is generated by J2objc. If I understand the implications correctly, changing that would be non-trivial. At best we could try to "guess". At worst it would require additional annotations defined in J2objc and applied to all classes (presumably).

It would be significantly easier to be able to disable this check in some kind of config. Thoughts? Would be up for taking a stab at it, but would need some config guidance (I just commented out for now and it works).

**Comment by olonho** [comment]
Kevin, so what would be your ideal solution from our side?
I.e. some annotation on Kotlin side, or interop stub switch, and how you'd like it to behave.

**Comment by kpgalligan** [comment]
Interop stub switch. I would imagine most interop code is going to be one of two situations. Easily changed or not easily changed. If easy to change, they should just fix it in Objc. If it's large, externally maintained, or autogen (which is our case), it's a lot easier to just disable the error check for all of it.

**Comment by r4zzz4k** [comment]
I don't see anywhere in Apple docs that designated initializers are mandatory for Objective-C classes, there's just an optional Clang's attribute `objc_designated_initializer`, which may or may not be present on initializers. I do see that designated initializers are a mandatory feature of Swift though.
So maybe this validation should work only if class has one? I don't think going for disabling of this check for the whole artifact is good if that's avoidable.

**Comment by SvyatoslavScherbina** [comment]
@r4zzz4k 
> So maybe this validation should work only if class has one?

This approach doesn't seem valid for me: Swift seems to apply other rules to imported Objective-C classes in this case: designated initializers are inherited from super class. And there are Objective-C classes in system frameworks that make use of this rule.

Actually you are right in that designated initializers aren't required in "pure" Objective-C. So we are considering replacing the compiler error by warning. However this error prevents user from writing  Kotlin class that would be initialized twice by mistake, so we are considering to forbid this by runtime check then.

**Comment by kpgalligan** [comment]
I can definitely see why default behavior is to fail, but also think a way to disable the fail is going to be pretty helpful. I think I'd vote for fail with a disable flag rather than just a warning. The user has to be aware enough of how everything works to find and add the disable flag. That won't stop people from doing bad things, but it'll at least force some awareness. That's my 2 cents.

**Comment by SvyatoslavScherbina** [comment]
@kpgalligan Using Kotlin/Native built from master branch, you can now add `disableDesignatedInitializerChecks = true` to the library `.def` file, and the compiler checks related to designated initializers for classes from this library would be suppressed.
