### ISSUE TITLE
Question: is it possible to use existing kotlin library from repositories?

### ISSUE THREAD

**Issue by roxma** [JetBrains/kotlin-native#1540]
I tried adding the following code into build.gradle to use https://github.com/fluidsonic/fluid-json

```gradle
dependencies {
    implementation("com.github.fluidsonic:fluid-json:0.9.1")
}
```

But this won't work.

```
roxma@debian hello-native $ gradle run

FAILURE: Build failed with an exception.

* Where:
Build file '/home/roxma/work/kotlin-learn/hello-native/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'hello-native'.
> Could not find method implementation() for arguments [com.github.fluidsonic:fluid-json:0.9.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

How do I add dependencies to external libraries?

**Comment by roxma** [comment]
Found related issue: https://github.com/JetBrains/kotlin-native/issues/1223

I know that Kotlin/Native cannot use jar library.

Instead I found one implemented in pure kotlin. I don't know how to import an existing pure kotlin library using `build.gradle`.

Is it possible? If not, is there any plan on this kind of feature?

**Comment by vvlevchenko** [comment]
Short answer is no and no plans to support in the nearest future. We support libraries published in K/N format. you can check our libcurl/curl sample for more details.
