### ISSUE TITLE
CInterop Can't find dependent libraries

### ISSUE THREAD

**Issue by piqllang** [JetBrains/kotlin-native#1544]
Whilst using the CInterop utility, to generate a sample klib, I am running into an error.
`interop -def zlib.def
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Anthony\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.2.0-c
lang-llvm-5.0.0-windows-x86-64\bin\libclang.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:207)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:38)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:100)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:29)
`
The contents of my zlib.def: 
`headers = zlib.h`
I am running a Windows 10 machine and have no compile errors. This has been the only issue so far.

zlib.h:
`#ifndef FOO_H_   /* Include guard */
#define FOO_H_

int foo(int x);  /* An example function declaration */

#endif // FOO_H_`

Thank you guys for your help!

**Comment by olonho** [comment]
Do you run binary distro or git? Is your Java 64-bit? Is .dll actually exists on your machine?

**Comment by piqllang** [comment]
I use the git distro, yes my Java is 64-bit, and yes the file exists.

![capture](https://user-images.githubusercontent.com/38731578/39362440-722c18ee-49f4-11e8-9588-0782d42d027d.PNG)

**Comment by olonho** [comment]
Could you please try with https://github.com/JetBrains/kotlin-native/releases/v0.7

**Comment by piqllang** [comment]
I still appear to have the same issue. I have attempted to rename the location of the libraries inside the run_konan.bat, then rename the msys2-mingw-... portion, hoping that maybe it would be an issue with the path; however, it just regenerates the path with all of the dll's. The issue appears to persist. Maybe an issue with my path? Do I need more to my path?

**Comment by SebOh** [comment]
I basically have the same issue on windows 10. I also cleaned my .konan directory and used the release version. But still the same behavior. Any ideas how to solve this issue?

**Comment by SebOh** [comment]
After some time of try and error I found a solution for this issue.

You need to update the environment variable PATH with the absolute path to the dependency bin. So for example you need to add the following:

C:\Users\[USER Name]\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.2.0-clang-llvm-5.0.0-windows-x86-64\bin

**Comment by olonho** [comment]
Usually it is not required.

**Comment by zaker139** [comment]
Yeah, I got the same question, finally I found my problem. In my case, the reason is I add a library libstdc++6.dll in my C:\Windows\System32 directory. Remove it then works well.
