### ISSUE TITLE
samples/videoplayer broken with ffmpeg4

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1548]
In FFmpeg v4 `libavresample` was removed and replaced by `libswresample`.
At least on Windows - MSYS2 distribution upgraded to ffmpeg v4.0, and build is now broken.

**Comment by olonho** [comment]
It likely means build shall be separated into separate ffmpeg klib and player itself, interacting via local maven repo (like curl example). Contributions are welcome.

**Comment by msink** [comment]
#1551

**Comment by olonho** [comment]
All pending PRы were merged.

**Comment by msink** [comment]
Fixed.
