### ISSUE TITLE
Combine classes with companion objects in Objective C frameworks?

### ISSUE THREAD

**Issue by alastaircoote** [JetBrains/kotlin-native#1549]
I'm just testing out using Kotlin Native to create a cross-platform library, and so far it looks fantastic! One wrinkle, though: when I make an Objective C framework (for use on iOS) it exports `MyClass` just fine, but also outputs `MyClassCompanionObject`, with static functions attached.

I understand why that's happening, and in many ways it's the more correct interpretation of the Kotlin code, but it doesn't match any pattern used in Objective C or Swift. Is there any way to combine these two classes to provide static functions on the original class?

**Comment by damianw** [comment]
I would suggest an opt-in mechanism, probably something like `@JvmStatic`, but for Objective-C. `object` (free or `companion`) members annotated with e.g. `@ObjCStatic` would cause the compiler to emit a static bridge on the enclosing class.

**Comment by SvyatoslavScherbina** [comment]
According [migration to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-44862. Please continue any discussions there.
