### ISSUE TITLE
Bridging with Java (The same Swift style that bridges to Objective-C)

### ISSUE THREAD

**Issue by fadi-botros** [JetBrains/kotlin-native#1550]
Now, Kotlin Native is interoperable with Objective-C. This is good.
But
One of the main domains of Kotlin is Android and the JVM, the JVM is slow and consumes a lot of memory, so what about making Kotlin Native interoperable with Java, so that the code is compiled natively, then when needed to address Java methods, it calls JNI under the hood.
And if one marks a method or class to be interoperable with Java, the compiler would generate Java code that exposes the method natively (The same Swift does with Objective-C runtime, the Objective-C runtime is somewhat like JVM but on a compiled environment, in Swift, you can mark an object as `@objc`, this makes it exposed to Objective-C runtime).

We may need something like that:

    class Something: JavaObject(@jvm var one: String, var two: String) {
        @jvm fun three(): String = one + "AA"
        fun four(): String = one + "B"
    }

This should generate Java code like that:

    public class Something {
       public native String getOne();
       public native String setOne(String value);
       public native String three();
    }

And generate the usual Kotlin Native code. And when you like to call from Native, something JVM, it will generate C instructions that use JNI.

**Comment by olonho** [comment]
Java interoperability is an explicit non-goal of Kotlin/Native, as Kotlin/JVM shall be used on Android, if interop with Java-based APIs is needed.
