### ISSUE TITLE
How to add reference from storyboard to Kotlin file

### ISSUE THREAD

**Issue by theapache64** [JetBrains/kotlin-native#1555]
I've created a sample `Kotlin/Native` iOS app using `AppCode`. It runs perfectly fine. The sample app contains one `UILabel`, one `UITextField` and a `Button`. When the user clicks the button, the textfield data will be shown in the label.

Now, I've added a new button using `XCode`'s `InterfaceBuilder`, but I don't know how to connect the button to the `ViewController.kt` file. Usually, when using `Swift`, a simple drag and drop from the `InterfaceBuilder` to the `Swift` file would automatically make the connection. But in my case it's not a `Swift` file, but `Kotlin`. 

**How do i make the connection to the `Kotlin` view controller file from the `InterfaceBuilder`** ? I tried the drag and drop, but it doesn't work.
 
I tried manually editing the storyboard file using a text editor and added the connection. It did work. but I don't feel like it as a perfect solution. **Is there any alternative?**

Below given the screenshot of the App. 

Here's the [github link][1] for the source code. 

[![Sample app][2]][2]

  [1]: https://github.com/theapache64/Konan/tree/91b6beab1a5c6692cad8509aa47b0f772caba333
  [2]: https://i.stack.imgur.com/e774c.jpg

https://stackoverflow.com/questions/50162514/how-to-add-reference-from-storyboard-to-kotlin-file

**Comment by olonho** [comment]
Current alternatives are  
 - use Swift+ XCode UI designer, and call Kotlin from Swift 
 - edit storyboard file, as you did
 - attach connections programmatically,  via API

**Comment by theapache64** [comment]
Do you have any example for alternative no 1 ?

**Comment by olonho** [comment]
Calling Kotlin from Swift? Sure: https://github.com/JetBrains/kotlin-native/blob/f5090b13172b44cf413f46ef9540f2c070aa2a0e/samples/calculator/ios/calculator/ViewController.swift#L62

**Comment by theapache64** [comment]
Cool 👍
