### ISSUE TITLE
Few doubts

### ISSUE THREAD

**Issue by theapache64** [JetBrains/kotlin-native#1559]
Let's me shoot it straight 

1. Is it possible to integrate Cocoapod libraries like 'Alamofire', 'SnapKit' etc. with a Konan project ?
2. Is it possible to run other kotlin/java libraries like 'OkHttp', 'Retrofit' in Konan project ? (I feel like it's a stupid question, but i want to confirm it 😬)

Please answer my questions and close this issue. I don't want my kotlin filled with issues. :D

**Comment by olonho** [comment]
1. Yes, it is possible, and we're working on support for CocoaPods in Gradle plugin.
2. No, Java libraries cannot be used with Kotlin/Native.

**Comment by theapache64** [comment]
Ok great. Do you have any approximate release date for the feature mentioned in answer one?

**Comment by theapache64** [comment]
I've seen many of the example apps, as well as the kotlin-conf app. It's awesome man. 

 I am planning to start one of my official projects in `konan`, It's an iOS app.  Is kotlin/native stable for an iOS project ? I am so excited to write iOS apps in Kotlin. I just can't wait for the `v1.0`. What do you say?. Should i start the project in Kotlin or wait for the stable version ? The app will be an e-commerce application, just like amazon.

**Comment by StefMa** [comment]
Why not just trying it out and share your findings/bugs/difficulties etc.
here? 🤔

**Comment by theapache64** [comment]
@StefMa 😆 That's right, but as I said, it's an official project. am taking a risk, i need to knw if it's worth choosing kotlin native at this stage `(v0.7)`. I am not saying that i don't trust kotlin/native or the am doubtful about the future of kotlin. I am damn sure that this technology will bring a revolution . i'll be answerable to my superiors. Soo..  a "Yeaah maahn, it's stable" or "Go head man", or kind of something like this would burn my confidence to another level. 😉 

I just need to know if kotlin/native ios is at the capable stage for developing an app e-commerce application.  

I know am disturbing you guys a lot asking too much things. You won't know how much  happy i am to see a technology like this. :) 

I'll be more happy if you could answer my small questions 😬

**Comment by theapache64** [comment]
@olonho Please respond 😬

**Comment by olonho** [comment]
Generally, Kotlin/Native core (i.e. compiler+runtime) is rather stable, however there may (and will) be some changes around .klib format, Gradle DSL, available API and such. However, no breaking changes planned, and we expect to provide a migration path, if something will change.

**Comment by theapache64** [comment]
Cool 👍
