### ISSUE TITLE
How to use Kotlin/Native iOS framework

### ISSUE THREAD

**Issue by ajonno** [JetBrains/kotlin-native#1560]
I wanted to test taking a framework generated from one of the sample Kotlin/Native projects - in this case it was KotlinArithmeticParser.framework from the "calculator" sample.

- I drag/dropped the *iOS_arm64* framework (```KotlinArithmeticParser.framework``` into a new Swift iOS project.
- built the Xcode project; this was ok
- tried to ```import KotlinArithmeticParser``` in ViewController.swift and then see if project built. This worked.

- tried adding this initialisation variable in ViewController.swift that uses the KotlinArithmeticParser lib: ```private let parser = KAPPartialParser(composer: KAPCalculator(), partialComposer: PartialRenderer())```

*This time the build failed and produced following error:*
![image](https://user-images.githubusercontent.com/3005269/39616142-51f08fc8-4fbd-11e8-9c27-e56598a2b9c3.png)

As you know the ```calculator``` example app produces 2 x iOS frameworks:
![image](https://user-images.githubusercontent.com/3005269/39615757-3dd36652-4fbb-11e8-86ff-3cbbde127b71.png)

Once we have created an iOS framework with Kotlin/Native - how must we go about deploying that framework to be used in any iOS (lets say iOS 10+) project ?

**Comment by SvyatoslavScherbina** [comment]
Have you added the framework to "Linked Frameworks and Libraries" list at "General" tab of project settings?

**Comment by dev-sogo** [comment]
hi, sorry for the delay on this has been busy. I came across this blog post which solved my issue re a simple 'hello world' type app with Kotlin Native. 
```http://viteinfinite.com/2018/02/creating-an-ios-framework-with-kotlin/```

**Comment by olonho** [comment]
OK, please reopen when more info is available.
