### ISSUE TITLE
Can CLion package_*.knm show source codes?

### ISSUE THREAD

**Issue by zxj5470** [JetBrains/kotlin-native#1573]
We could only see signatures in knm now.（just looks like `*.class` in IJ `out` directory  with `/* compiled code*/`）

And is there any schedules for supporting source code for stdlib otherwise I could only to clone thiw repository then open VSCode to find references for stdlib.

And C Interop with some `enum` value is also like `val a /* compiled code */`,which really makes me annoyed...

for example in OpenCV2 in CLion with my [OpenCV-KotlinNative](https://github.com/zxj5470/OpenCV-KotlinNative):
-  My `package_libopencv2_highgui.knm`
![image](https://user-images.githubusercontent.com/20026798/39796275-2e6e235c-5388-11e8-8ae1-c23e5b2a0e37.png)

- VSCode (`opencv2/core/types_c.h`)
![image](https://user-images.githubusercontent.com/20026798/39796303-5e396e7a-5388-11e8-906e-5324a119fd94.png)

**Comment by SvyatoslavScherbina** [comment]
Hi. Kotlin plugin for CLion is deprecated now. Please use IntelliJ IDEA Ultimate.
See more details here:
https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-rc-released/
https://plugins.jetbrains.com/plugin/10454-kotlin-native-for-clion
