### ISSUE TITLE
cinterop: nullability

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1580]
Nullability is major Kotlin feature, have long history, coming in the end to platform types.
In  JVM version all objects from java are `platform type` - like `Object!` (if not annotated explicitly).

But in Kotlin/Native all pointers imported by `cinterop` tool are nullable - like `COpaquePointer?`
This is unfortunate, I think they should be platform, like in JVM.

**Comment by msink** [comment]
Yes, it *should* throw NPE instead of crash.
In K/N too.

**Comment by msink** [comment]
Another question - is [Objective-C Nullability Annotations](https://developer.apple.com/swift/blog/?id=25) supported by cinterop tool?
And if yes - is it possible to use that annotation for plain C too?

**Comment by olonho** [comment]
Not sure if I got the answer. What are the benefits from using platform types? Objective-C nullability annotation is used.

**Comment by msink** [comment]
Well, I do not got the question. :)
This is Kotlin, not C and not Go - ideomatic way of handling unexpected errors is `try/catch`, not checking for error code after each API call.

**Comment by msink** [comment]
Ok, let's postpone platform types for a while.

Real question is - say I have some C library, imported by cinterop tool. Most, if not all functions take pointers as arguments, NULL is invalid.
How to force cinterop import that functions with _Nonnul paremeters?

**Comment by olonho** [comment]
At the moment, it does not work, however we would accept contributions. Tricky part would be getting https://github.com/JetBrains/kotlin-native/tree/master/libclangext to work, and after that, access to attributes shall be available in C API, and could be used properly in https://github.com/JetBrains/kotlin-native/blob/0c0446b56dbae85479231ace36f69c578fc428af/Interop/Indexer/src/main/kotlin/org/jetbrains/kotlin/native/interop/indexer/Indexer.kt#L473.

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48083 and https://youtrack.jetbrains.com/issue/KT-48084, closing.
