### ISSUE TITLE
type mismatch: inferred type is String but CValuesRef<*>? was expected

### ISSUE THREAD

**Issue by kingofoz** [JetBrains/kotlin-native#1581]
Hello,
Please see the below code, I am pretty new to kotlin:

import kotlinx.cinterop.*
import platform.posix.*

fun main(args: Array<String>) {
    val fileName = "test.txt"
    memScoped {
        val buffer = allocArray<ByteVar>(4 * 1024)
        val file = fopen(fileName, "wt")
        setvbuf(file, buffer, 0, 4096)
        if (file == null) throw Error("Cannot write file '$fileName'")
        try {
            while (true) {
                fwrite("1", 1, 1, file)
            }
        } finally {
            fclose(file)
        }
    }
}
======================================
The error comes from fwrite("1", 1, 1, file):
hello.kt:14:24: error: type mismatch: inferred type is String but CValuesRef<*>?
 was expected
                fwrite("1", 1, 1, file)

Can somebody tell me how to use fwrite()?

Thanks,
Yingjun

**Comment by olonho** [comment]
You missed `cstr`, i.e. 
```import kotlinx.cinterop.*
import platform.posix.*

fun main(args: Array<String>) {
    val fileName = "test.txt"
    memScoped {
        val buffer = allocArray<ByteVar>(4 * 1024)
        val file = fopen(fileName, "wt")
        setvbuf(file, buffer, 0, 4096)
        if (file == null) throw Error("Cannot write file '$fileName'")
        try {
            while (true) {
                fwrite("1".cstr, 1, 1, file)
            }
        } finally {
            fclose(file)
        }
    }
}``` works as expected.

**Comment by kingofoz** [comment]
Thanks, @olonho  It works now!
