### ISSUE TITLE
Xcode 9.3 is required: 9.3.1 is found

### ISSUE THREAD

**Issue by theoriginalgri** [JetBrains/kotlin-native#1582]
Three days ago, Apple released XCode 9.3.1.

The version check fails for this version since it's hardcoded to "9.3".

https://github.com/JetBrains/kotlin-native/blob/e1e4a5ce82051b642511bef7299d6297f29ca2b4/shared/src/main/kotlin/org/jetbrains/kotlin/konan/target/KonanProperties.kt#L70

**Comment by olonho** [comment]
See https://github.com/JetBrains/kotlin-native/pull/1588
