### ISSUE TITLE
How to create klib for multi-platform?

### ISSUE THREAD

**Issue by inoutch** [JetBrains/kotlin-native#1586]
Hello,

I'm trying to build to kotlin library(klib) from my codes using multi-platform of kotlin.
I suppose klib is included one or more targets(such as linux, wasm32), however the klib file I created has only one target, and distincation directory of artifacts is separated for each targets.

I use kotlin-native-gradle-plugin(konan) and I wrote as follows:
```
buildscript {
  ~ omit ~
}

apply plugin: "konan"

konanArtifacts {
    library("crosslib", targets: ['wasm32', 'linux']) {
        enableMultiplatform true

        target('linux') {
          srcFiles fileTree('src/main/kotlin/linux')
        }
        target('wasm32') {
          srcFiles fileTree('src/main/kotlin/wasm32')
        }
    }
}

dependencies {
    expectedBy project(":common")
}

```
Build results
```
build/
    konan/
        libs/                   /* I want to bundle their klib */
            linux_x64/
                crosslib.klib
            wasm32/
                crosslib.klib
```

In addion, when I install their klib using klib command, older klib removes and only the target of the new klib remains.

How can I aggregate into one kotlin library?

**Comment by olonho** [comment]
This is currently possible, but hacky. See how multiplatform stdlib is being built in https://github.com/JetBrains/kotlin-native/blob/0c0446b56dbae85479231ace36f69c578fc428af/build.gradle#L281

We are in process of reworking library format to make it more cross-platform, but this will not be there immediately.

**Comment by inoutch** [comment]
Thank you for your reply.

I hope for the more development of cross-platform library management such as klib, because rich library of java is not available in K / N.

I am looking forward to the future development.
