### ISSUE TITLE
GUI desktop applications

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1589]
Desktop GUI applications are somewhat broken, at least for Windows.
I created simple project for cross-platform GUI: https://github.com/msink/klib-ui
Nothing fancy, and it somewhat works, but looks not "themed", like in Win95.
What I did wrong?

What should be  - compiled from C example:
![image](https://user-images.githubusercontent.com/1785275/39996871-642e049c-579a-11e8-9c4c-d1cbd484fb6e.png)
How it looks actually - converted to Kotlin/Native:
![image](https://user-images.githubusercontent.com/1785275/39996829-3f9b329e-579a-11e8-936f-1a8bac479b0c.png)

Cannot test Mac version, on linux looks as expected:
![image](https://user-images.githubusercontent.com/1785275/39997408-520d2714-579c-11e8-810c-dea24ddc9480.png)

**Comment by olonho** [comment]
Seems problem is described here: https://stackoverflow.com/questions/17978546/how-to-make-window-look-more-modern. Mike, could you please try to implement suggested steps in your apps?

**Comment by msink** [comment]
Well, I just downloaded [Resource Hacker](http://www.angusj.com/resourcehacker/), opened K/N version, and imported Manifest from C version:
``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity
    version="1.0.0.0"
    processorArchitecture="*"
    name="CompanyName.ProductName.YourApplication"
    type="win32"
/>
<description>Your application description here.</description>
<!-- we DO need comctl6 in the static case -->
<dependency>
    <dependentAssembly>
        <assemblyIdentity
            type="win32"
            name="Microsoft.Windows.Common-Controls"
            version="6.0.0.0"
            processorArchitecture="*"
            publicKeyToken="6595b64144ccf1df"
            language="*"
        />
    </dependentAssembly>
</dependency>
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
        <!--The ID below indicates application support for Windows Vista -->
        <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
        <!--The ID below indicates application support for Windows 7 -->
        <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
    </application>
</compatibility>
</assembly>
```

And now both versions look identical.
But how to automate this using gradle?

**Comment by olonho** [comment]
Maybe launch windres like in https://github.com/JetBrains/kotlin-native/blob/f512b3b60af99a8cadb8278f89966eee5c6269b7/samples/tetris/build.bat#L16 from Gradle as an external task.

**Comment by msink** [comment]
Maybe, as temporary workaround.
But in long run it should have direct support in gradle plugin.

**Comment by msink** [comment]
And VTW, can someone confirm that https://github.com/msink/klib-ui/releases/download/alpha-3.5-3/libui-hello-osx actually works on OSX?

**Comment by aceisnotmycard** [comment]
<img width="321" alt="screen shot 2018-05-15 at 00 26 17" src="https://user-images.githubusercontent.com/1580082/40013032-aadd5456-57d6-11e8-9a46-9fe49d038ee6.png">

@msink, yes :)

**Comment by olonho** [comment]
Not sure if adding PE resource manipulations into generic Gradle plugin makes much sense, but adding external tools is generally easy, so shalln't be a big deal.
