### ISSUE TITLE
[Document enhancement] Improve document about multiplatform

### ISSUE THREAD

**Issue by Albert-Gao** [JetBrains/kotlin-native#1593]
Thanks for the document: @ilmat192 

https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md#4-ios-application

## 1. for adding source

Have a question to the last part

```
Add Kotlin sources into the framework: run File -> Add files to "iosApp"... 
and choose a directory with Kotlin sources (greeting/ios/src in this sample). 
Choose the framework created as a target to add these sources to. 
Do this for the common code of the library too.
```

How to do this part: `Choose the framework created as a target to add these sources to. `

## 2. for IDE
So which IDE does this document suggest to use in terms of iOS developing for the Kotlin native code? I think the current possible 2 are CLion and AppCode, is there a tutorial on how to make this setup work with AppCode? Thanks :)

**Comment by Albert-Gao** [comment]
Thanks! @StefMa I think your PR makes it easier to see what happens.

And I think I get the idea of what does `Choose the framework created as a target to add these sources to.` mean. It means when adding source file, in the popup, choose the framework as the target.

But will be better if we can have update for my second question.

**Comment by olonho** [comment]
Xcode does not know about Kotlin yet, so please use AppCode, and report us issues you have got.
