### ISSUE TITLE
[cinterop] Type is not visible from kotlin

### ISSUE THREAD

**Issue by norman784** [JetBrains/kotlin-native#1610]
Hi, I'm trying to interop between glfw and kotlin all works fine except that there are some types that cannot de accessed from kotlin.

```
fun glfwCreateWindow(width: Int, height: Int, title: String?, monitor: CValuesRef<GLFWmonitor>?, share: CValuesRef<GLFWwindow>?): CPointer<GLFWwindow>? {
    memScoped {
        return interpretCPointer<GLFWwindow>(kniBridge18(width, height, title?.cstr?.getPointer(memScope).rawValue, monitor?.getPointer(memScope).rawValue, share?.getPointer(memScope).rawValue))
    }
}
```

This is the code generated by the interop and in my code I cannot access to *GLFWwindow*

![screen shot 2018-05-18 at 5 00 18 pm](https://user-images.githubusercontent.com/204656/40242108-fc381d84-5abc-11e8-8545-d11b9b6ca1ab.png)

![screen shot 2018-05-18 at 4 58 56 pm](https://user-images.githubusercontent.com/204656/40242036-caff9e90-5abc-11e8-9fa1-2c32d14af666.png)

I want to store the reference from the window in a class property, but only seems to work if I just let the compiler set the type as a local variable.

This is my .def file

```
headers = GLFW/glfw3.h
headerFilter = GLFW/*
compilerOpts.osx = -I/usr/include -I/usr/local/include
linkerOpts.osx = -L/usr/lib -L/usr/local/lib -lglfw
linkerOpts.linux = -L/usr/lib/x86_64-linux-gnu -lglfw
```

Regards

**Comment by olonho** [comment]
Not sure if I understand your problem. `glfwCreateWindow` returns `CPointer<GLFWwindow>` which is what could be stored in your class or in local variable. I.e. `var window: CPointer<GLFWwindow>? = null` shall do

**Comment by olonho** [comment]
This is an opaque structure, defined as `typedef struct GLFWwindow GLFWwindow;` in the header, so there's no way to refer any fields in it, it could be just  passed as an opaque value.

**Comment by norman784** [comment]
So theres no way to store this result in a class property and then pass to another method the value, because those methods ask for `CPointer<GLFWwindow>?`.

In other words an opaque struct cannot be referenced in kotlin because of his nature? (my knowledge of c/c++ is limited).

**Comment by norman784** [comment]
Checking at the source of [java bindings](https://github.com/badlogic/jglfw/blob/master/jglfw/src/com/badlogic/jglfw/Glfw.java#L675) seems that they are able to access them (again my knowledge of this topic is limited, and also know that konan doesn't run over jvm :D), they convert to long to return the result and then convert back when using internally.

**Comment by olonho** [comment]
No, it is fully possible, just use CPointer type. You could typealias it to smth shorter, and also maybe report CLion issue, so that such types properly offered by completion.

**Comment by norman784** [comment]
Yes, and sorry I just entered in panic mode and didn't try to compile it.

Was a CLion issue only, is reporting as unresolved reference but the compiler is generating and running the app, where should I file a report about this?

I'll close by now. Have a great weekend.

**Comment by stigger** [comment]
@norman784 What CLion build are you using? Have you tried the 2018.2 EAP that was published yesterday with the latest Kotlin/Native plugin build?

**Comment by norman784** [comment]
hey @stigger, I was using CLion 2018.1.2, with the EAP seems that this issue disappeared, but not quite sure, because I cannot jump to the auto generated declaration of the binding, but is not a big deal for now.

Thanks
