### ISSUE TITLE
Whats the cons of using too much C interop?

### ISSUE THREAD

**Issue by norman784** [JetBrains/kotlin-native#1614]
I was wondering if theres any cons of using too much C interop, like right now I'm trying to build a game engine (for fun) and the easiest way is to use C libraries (i.e. glfw, bgfx, sdl, etc), I read somewhere that the memory sharing between Kotlin and C is somehow tricky and read somewhere else that the memory is hard (if not almost impossible) to share between threats (so my understanding is that C libs runs in another threat).

So theres really 2 questions here:

1- (read title)
2- Is recommended to write in pure Kotlin if possible instead of rely on C interop (or with any other language)

Regards

**Comment by olonho** [comment]
Kotlin/Native interoperates with C/Objective-C mostly seamlessly, and sure no threads are used to run C calls or smth like that. You could just use functions implemented in C with Kotlin, although, there's some minor performance cost associated with data conversion on the boundary. However, in many cases it is not important, and is acceptable in many others.

**Comment by norman784** [comment]
Thanks, saying that then I don’t need to worry in the short term.
