### ISSUE TITLE
Kotlin native language positioning

### ISSUE THREAD

**Issue by oahzuw** [JetBrains/kotlin-native#1615]
I've always wanted to learn C++, but I've been at the Hello World level and I have finally seen a language, Java learning, C/C++ native, Is kotlin native, I really like kotlin native,
 Kotlin native language positioning, desktop language or server language, machine learning language, or general purpose. All fields are supported. The gui in the official example is using C. /C++ library, machine learning is also using c / c + + api, server version has not yet found a usable library, I have mastered the kotlin native syntax, what can I do with it?

**Comment by olonho** [comment]
Some examples use C libraries, but written in Kotlin. Same as Kotlin/JVM uses JDK methods, or Kotlin/JS uses Javascript APIs. There's no difference which language is used to implement API, when it is being used in the program.
