### ISSUE TITLE
Native tests runner for iOS

### ISSUE THREAD

**Issue by thevery** [JetBrains/kotlin-native#1620]
Right now it is possible to write common tests and run them on JVM with `kotlin-test-junit` (I've tried `@RunWith(JUnit4::class) class SomeTestJava: SomeTestCommon()` and it works), but is there are any way to do this for iOS?

**Comment by ilmat192** [comment]
Kotlin/Native supports the `kotlin.test` package so you can run the common tests if they use this package. To do this, you need to create an executable passing `-tr` as an additional compiler option (see https://github.com/JetBrains/KotlinMultiplatformPlayground/blob/master/native/build.gradle). Currently Gradle plugin doesn't provide a testing DSL but this is in short-term plans.

If you want to runt the test executable on iOS, the UIKit sample may be useful for you: https://github.com/JetBrains/kotlin-native/tree/master/samples/uikit. It shows how to create an iOS application fully on KN and load the executable to the device.

**Comment by thevery** [comment]
iOS test executable implemented in this sample:
https://github.com/JetBrains/kotlin-mpp-example/pull/1
