### ISSUE TITLE
alloc and allocArray issues

### ISSUE THREAD

**Issue by norman784** [JetBrains/kotlin-native#1634]
This is weird, I was able to compile the project without issues, but now it throws this error:

```
src/main/kotlin/2_HelloTriangle.kt:131:18: error: unresolved reference: alloc
    val status = alloc<GLintVar>()
                 ^
src/main/kotlin/2_HelloTriangle.kt:134:19: error: unresolved reference: allocArray
        val log = allocArray<ByteVar>(512)
```

From this code:

```
import cglew.glewExperimental
import cglew.glewInit
import cglew.GLEW_OK
import cglew.glClear
import cglfw.*
import kotlinx.cinterop.*
import platform.OpenGL3.*
import platform.OpenGLCommon.GLintVar

//..... some unrelated code

fun checkProgramStatus(program: Int) {
    val status = alloc<GLintVar>() // line 131
    glGetProgramiv(program, GL_LINK_STATUS, status.ptr)
    if (status.value != GL_TRUE) {
        val log = allocArray<ByteVar>(512) // line 134
        glGetShaderInfoLog(program, 512, null, log)
        throw Error("Program linking errors: ${log.toKString()}")
    }
}
```

Also CLion complains about `Type argument resulting from type alias expansion is not within required bounds for 'T': should be subtype of 'Int', substituted type is 'GLint /* = int32_t */'`, the most annoying think is it was working just fine, the code I took from [here](https://github.com/JetBrains/kotlinconf-spinner/blob/f37a6ea758b04915d619fcf68273e4a21ae4d9fc/kotlin-native/samples/fullstack/clients/shared/src/main/kotlin/gl.kt#L97).

This was triggered after I tried to build with gradle from the cli, was testing that it works from gradle too, but I do all the work with CLion and cmake (the cmake file is generate via gradle). And it looks like

```
cmake_minimum_required(VERSION 3.8)

set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/KotlinCMakeModule)

project(gllab Kotlin)

cinterop(
    NAME cglew
    DEF_FILE src/main/c_interop/cglew.def)

cinterop(
    NAME cglfw
    DEF_FILE src/main/c_interop/cglfw.def)

konanc_executable(
    NAME 2_HelloTriangle
    SOURCES src/main/kotlin/2_HelloTriangle.kt
    LIBRARIES cglew cglfw)
```

**Comment by olonho** [comment]
alloc can only be used with placement, i.e. in memScoped {} block, or explicitly, i.e. nativeHeap.alloc. But second one will leak, unless explicitly freed.

**Comment by norman784** [comment]
Cool thanks, you are right, I might deleted that without noticing it. Could you add an enhancement flag for the Kotlin Native plugin? So we can have better error message about it.

**Comment by olonho** [comment]
Hard to tell how to implement it as a general inspection. But we'll discuss it.
