### ISSUE TITLE
Xcode 9.4 is released

### ISSUE THREAD

**Issue by StefMa** [JetBrains/kotlin-native#1636]
<img width="215" alt="bildschirmfoto 2018-05-29 um 21 19 11" src="https://user-images.githubusercontent.com/10229883/40680320-fea12ada-6385-11e8-8ae7-88db566670e4.png">
🎉 
I haven't tested it yet. But I think it is the same like #1582 , right?
So you have to update the value to 9.4

Which leads to another question.
Why is Xcode required?
Can't we get rid of it?
Or at least can't we say something like "min xcode version: X"
So not each time a new Xcode release Kotlin/native will be broken?!

**Comment by mikezriel** [comment]
Same Here:
A problem occurred evaluating root project 'kotlin-native'.
> expected Xcode version 9.3.1, got 9.4, consider updating Xcode or use "ignoreXcodeVersionCheck" variable in konan.properties

**Comment by StefMa** [comment]
They are already working on it here https://github.com/JetBrains/kotlin-native/pull/1637 ;)

**Comment by SvyatoslavScherbina** [comment]
@StefMa 

> Or at least can't we say something like "min xcode version: X"
> So not each time a new Xcode release Kotlin/native will be broken?!

Actually Kotlin/Native distribution works properly even with newer Xcode versions that weren't explicitly supported. Only building Kotlin/Native distribution itself from the source gets broken. And it is critically required to build Kotlin/Native distribution exactly with the same Xcode version as it is supposed to be built with.
