### ISSUE TITLE
Implementation of kotlin.test

### ISSUE THREAD

**Issue by MarkusAmshove** [JetBrains/kotlin-native#1639]
Hi,

I'm currently migrating a library from being JVM only to multiplatform and I'm also trying to implement a library for kotlin native.

I do have a dependency on `kotlin.test` and it is working like a charm with the `-tr` flag on compilation.

I've now stumbeld on the assertions `assertSame` and `assertNotSame` which don't seem to be implemented yet (Gradle output):

```
> Task :kluent-native:compileKonanKluent-nativeLinux FAILED
/home/markus/scm/Kluent/common/src/main/kotlin/org/amshove/kluent/Basic.kt:10:58: error: unresolved reference: assertSame
infix fun <T> T.shouldBe(expected: T?): T = this.apply { assertSame(expected, this) }
```

I'm currently using native 0.6, because of the same issue described in #1612 so I'm not sure if it would just work if I could use 0.7.
However I wasn't able to find the platform implementation for `kotlin.test` inside this native repo, could you guide me to the correct location so I can look it up in the future? :-)

**Comment by ilmat192** [comment]
Hi @MarkusAmshove!

Thank you for the report. `assertSame`/`assertNotSame` are really not implemented in KN and we will fix that. As for the second question, the user API for KN's `kotlin.test` can be found [here](https://github.com/JetBrains/kotlin-native/tree/master/runtime/src/main/kotlin/kotlin/test). If you are interested in implementation details, you may look at [this package](https://github.com/JetBrains/kotlin-native/tree/master/runtime/src/main/kotlin/konan/test).

**Comment by olonho** [comment]
I have added those on https://github.com/JetBrains/kotlin-native/pull/1637/commits/62c1a6d5b4492ec02ac8f5f68309b14e87d65128

**Comment by MarkusAmshove** [comment]
Thanks for implementing it, I'll use that implementation in the future :-)

I've also found out that `kotlin.test` has different behavior on different platforms.

If you look at [this](https://github.com/MarkusAmshove/Kluent/blob/multiplatform/common/src/test/kotlin/org/amshove/kluent/basic/ShouldEqualShould.kt#L45) test, which uses [this](https://github.com/MarkusAmshove/Kluent/blob/multiplatform/common/src/main/kotlin/org/amshove/kluent/Basic.kt#L6) assertion, defined in a common module and you can see in the comment that this test would pass on JVM but not on Native and JS.

Since multiplatform is still a preview, I haven't found a clue if this is intended or not.

The JVM implementation of `kotlin.test` (which might use the JUnit `assertEquals`) seems to test for the equality of the items within the array, while Native and JavaScript do another comparison which fails in that case.
The testcases defined below that do the same test with lists, where the behavior is the same on all platforms.

If you think this question doesn't fit into the Native repository I can build a smell repro and open an issue in YouTrack :smile:

**Comment by olonho** [comment]
Shall be fixed.
