### ISSUE TITLE
Itunesconnect reject due to Kotlin-native framework non-public API usage.

### ISSUE THREAD

**Issue by oroom** [JetBrains/kotlin-native#1642]
I uploaded iOS app with Kotlin-native framework to review and it was rejected by apple with next reason:

> We identified one or more issues with a recent delivery for your app, "AppName". Please correct the following issues, then upload again.
> 
> Non-public API usage:
> 
> The app contains or inherits from non-public classes in Frameworks/MyCore.framework/MyCore: NSBlock
> If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

I don't have `NSBlock` mentions in my framework headers and can find only one usage of NSBlock in Kotlin native in this file runtime/src/main/cpp/ObjCExport.mm
So it can be a reason. Do you have any suggestions how I can solve this issue?

**Comment by jlep** [comment]
+1 I bumped into the exact same issue. Any pointers towards a solution would be highly appreciated!

**Comment by jlep** [comment]
I was able to fix the issue in my case with the following patch: https://github.com/jlep/kotlin-native/commit/5439e99b7d11d48efb48a91d3b95306c9653cc49

After rebuilding my framework with the patched compiler/runtime I can verify with `nm -u <Framework> | grep NSBlock` that the framework doesn't import NSBlock symbol anymore.

I don't know what the full implications of this patch are. Maybe passing blocks from Objective-C to Kotlin won't work?

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/1652 shall fix that. Could you please check?

**Comment by jlep** [comment]
I was able to upload my app with #1652. Thanks!

**Comment by SvyatoslavScherbina** [comment]
Fixed in master after merging #1652.
