### ISSUE TITLE
Path variable error in script

### ISSUE THREAD

**Issue by DiaLight** [JetBrains/kotlin-native#1643]
There is error in script

https://github.com/JetBrains/kotlin-native/blob/c0f3e5f9e81f6d92852d13817da61f429dfd5867/cmd/run_konan.bat#L97

There is tests to prove error:
```bat
if ("%KONAN_DATA_DIR%"=="") (set KONAN_DATA_DIR=%USERPROFILE%\.konan)
echo %KONAN_DATA_DIR%

pause
```
Output is:
```
C:\software\dev>if ("" == "") (set KONAN_DATA_DIR=C:\Users\DiaLight\.konan )

C:\software\dev>echo
Режим вывода команд на экран (ECHO) включен.

C:\software\dev>pause
Для продолжения нажмите любую клавишу . . .
```
Quick fix of error:
```bat
if "%KONAN_DATA_DIR%"=="" (set KONAN_DATA_DIR=%USERPROFILE%\.konan)
echo %KONAN_DATA_DIR%

pause
```
Output:
```
C:\software\dev>if "" == "" (set KONAN_DATA_DIR=C:\Users\DiaLight\.konan )

C:\software\dev>echo C:\Users\DiaLight\.konan
C:\Users\DiaLight\.konan

C:\software\dev>pause
Для продолжения нажмите любую клавишу . . .
```
Because of this error, users can't compile theirs windows projects using CMake.
There past issues with same problems i had. [Can't find dependent libraries - Windows 10 #1252](https://github.com/JetBrains/kotlin-native/issues/1252) [CInterop Can't find dependent libraries #1544](https://github.com/JetBrains/kotlin-native/issues/1544)

**Comment by msink** [comment]
Also there should be spaces between parentheses and the command:
```
if "%KONAN_DATA_DIR%"=="" ( set KONAN_DATA_DIR=%USERPROFILE%\.konan )
```

**Comment by ilmat192** [comment]
Thanks for the report! The issue should be fixed by https://github.com/JetBrains/kotlin-native/pull/1649.

**Comment by ilmat192** [comment]
#1649 merged.
