### ISSUE TITLE
Missing String.toByteArray

### ISSUE THREAD

**Issue by norman784** [JetBrains/kotlin-native#1663]
As title says, [String.toByteArray](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-byte-array.html) seems to be not implemented.

Also `Charsets` seems to be not implemented either.

**Comment by olonho** [comment]
Sure, it's JVM-only method, as said in the link above. 
Please use  `String.toUtf8()` extension function from `kotlin.text` to convert to UTF-8, although.

**Comment by norman784** [comment]
Thanks, I was sure that there was one but its hard to find references to Kotlin Native currently on the net. 

So why not using the same or similar API to Kotlin JVM? Also I think that `toByteArray` follows the convention of conversion functions like `toFloat`, `toInt`, I feel `toUtf8` non descriptive.

**Comment by olonho** [comment]
Because it would require introduction of Charset into common stdlib, which is not desirable. And without `charset` argument meaning of this call become less obvious.

**Comment by norman784** [comment]
How much overhead will add Charset to the stdlib? I think is desirable to have an uniform API and also have method that self describe itself.

**Comment by olonho** [comment]
It's pretty significant, as library grows linearly with the number of convertors available (and hard to do right on JS). So this will unlikely happen, thus closing this issue.
