### ISSUE TITLE
Can I compile a source file with `import`s?

### ISSUE THREAD

**Issue by intfrog** [JetBrains/kotlin-native#1674]
Say I have a source file `strings/string.kt`, and a 'hello.kt', which depends on `strings/string.kt`, like
```kotlin
import strings.lastChar as last

fun main(args: Array<String>) {
    println("Kotlin".last())
}
```
How can I compile both these two files into one binary executable? Or is that possible?
And what if I have a 3rd party Kotlin dependency like TornadoFX? Can I still compile my program to binary?

**Comment by olonho** [comment]
Sure, just run a compiler with multiple input source files.

**Comment by olonho** [comment]
TornadoFX is wrapped around Java library (JavaFX) and as such will not work in Kotlin/Native.

**Comment by intfrog** [comment]
Thanks a lot :)
