### ISSUE TITLE
Support for Collections.shuffled?

### ISSUE THREAD

**Issue by epool** [JetBrains/kotlin-native#1675]
I'm using `implementation "org.jetbrains.kotlin:kotlin-stdlib-common:1.2.41"` in a common module of course, and there I'm able to call `.shuffled()` on a list object. This works fine in Android since it's a JVM implementation, but in iOS I'm having an `Unresolved reference: shuffled` error since this is [not implemented](https://github.com/JetBrains/kotlin-native/blob/670d05a4f35cbb3613d694406af515a13b796fb3/backend.native/tests/stdlib_external/collections/MutableCollectionsTest.kt#L108) in kotlin-native, so I'm wondering if this should be implemented in kotlin-native too or if this should be removed from `kotlin-stdlib-common` or what's the expected behavior in this scenario. The same with `.fill()` and other collection apis.

**Comment by PavelPunegov** [comment]
Both `fill()` and `shuffled()` should be implemented in Kotlin/Native with the fix for https://youtrack.jetbrains.com/issue/KT-24102
