### ISSUE TITLE
Generating a random number in Kotlin -> WebAssembly

### ISSUE THREAD

**Issue by boyanio** [JetBrains/kotlin-native#1699]
Hello,

When compiling Kotlin to WebAssembly, I can see that in the generated JavaScript file there is `knjs__Math_random`, however when trying to import `kotlin.math.random` in Kotlin, I get a compilation error. Doesn't the `random` function reside in `kotlin.math` or I am missing something? Other math functions work fine.

**Comment by PavelPunegov** [comment]
`random()` function in Kotlin doesn't reside in `kotlin.math`. On WebAsm we use only those JavaScript's Math methods which is necessary to implement `kotlin.math`.

As for random, it is going to be implemented separately from `kotlin.math`
