### ISSUE TITLE
[0.7.1] Runtime assert in Xcode 9.4.1

### ISSUE THREAD

**Issue by Marcopohlo** [JetBrains/kotlin-native#1704]
Hello I'm getting 

`ObjCExport.mm:402: runtime assert: Unable to add 'toKotlin:' method to NSBlock class` 

on Xcode 9.4.1 but it works without issue on Xcode 10 beta.. Anything I can do to fix this?

**Comment by Marcopohlo** [comment]
For anybody interested, this problem is with Kotlin/Native **0.7.1**, works okay with **0.7**.

**Comment by SvyatoslavScherbina** [comment]
This error can be caused by loading more than one framework compiled by Kotlin/Native (it is not possible currently). Can this be the case?

**Comment by Marcopohlo** [comment]
@SvyatoslavScherbina the problem is that it works in Xcode 10 with **0.7.1** quite okay but it doesn't in 9.4.1. But when I switch back to 0.7 it works just fine in both Xcode versions. Any suggestions?

**Comment by Marcopohlo** [comment]
> Do you open the same project with different Xcode versions? Is it possible that Xcode 9.4.1 has some obsolete data in derived data directory (i.e. ~/Library/Developer/Xcode/DerivedData/$project/)?

Yes I do. They both use the same DerivedData and I already tried it in Xcode 9.4.1 with `DerivedData` folder deleted and still the same. 

> Can you post the list of files and directories in YourApp.app/Frameworks and show the output of otool -L YourApp.app/YourApp?

Could you please clarify your request for iOS App? Since this will probably work only for macOS App.

**Comment by Marcopohlo** [comment]
Thank you for enlightenment. I didn't know about this.

So the result for otool is:

**Comment by SvyatoslavScherbina** [comment]
Nothing confirms loading Kotlin/Native frameworks twice.
But we can't reproduce the issue locally. Could you please try to compile and run the same project as we have used to check? It can be found at https://github.com/JetBrains/kotlin-native-calculator-sample (`ios/calculator.xcodeprj`).

**Comment by olonho** [comment]
@Marcopohlo any news on that one?

**Comment by Marcopohlo** [comment]
So sorry guys, will try it in a moment and get back to you.

**Comment by radzio** [comment]
@SvyatoslavScherbina 

> Hello. This error can be caused by loading more than one framework compiled by Kotlin/Native (it is not possible currently). Can this be the case?

Any plans to add support for loading multiple frameworks compiled by Kotlin/Native? IMHO it would be great to have that possibility.

**Comment by SvyatoslavScherbina** [comment]
@radzio could you please provide a case where loading multiple frameworks is required?

**Comment by Marcopohlo** [comment]
@SvyatoslavScherbina So the Calculator is building and running just fine.

**Comment by thevery** [comment]
We've got the same issue on our project, too.
Our workflow is building framework (actually fat one using `lipo`) with gradle and using it in project without gradle.
I'll try to push minimal sample tomorrow.

**Comment by SvyatoslavScherbina** [comment]
@Marcopohlo 
> Also I noticed you are using Kotlin 1.2.31 and I'm using 1.2.50 but I guess that won't change anything, right?

This version seems to be completely unrelated.

**Comment by kprofic** [comment]
@SvyatoslavScherbina - about the need of having more than one Kotlin/Native framework mentioned by @radzio - we have our app modularized into several components, eg. there is `Domain.framework` , `SomeBusinessLogic1.framework` and `SomeOtherBusinessLogic.framework`where the last two depend on `Domain`. We wanted to move to Kotlin/Native starting from `Domain` and reuse this on both iOS and Android. But that's just a tiny bit on the common logic we could reuse on both platforms. We would like to implement also few BusinessLogic frameworks as a common core libraries shared between platforms.

**Comment by SvyatoslavScherbina** [comment]
@kprofic So compiling multiple Kotlin modules into one iOS framework seems to be enough, doesn't it?

**Comment by SvyatoslavScherbina** [comment]
@thevery Thank you for debugging!

So the issue seems to be caused by a bug in Objective-C runtime or system frameworks which causes `load` method to be called twice.
We will make a workaround soon.

**Comment by SvyatoslavScherbina** [comment]
@Marcopohlo could you confirm that the fix works for you?
You can try it by setting Kotlin/Native version to `0.8-dev-2572` in your Gradle build (`gradle.properties` or `build.gradle`).

**Comment by kprofic** [comment]
Thanks @SvyatoslavScherbina, yes compiling into one objc framework would work but that's only when we are controlling the codebase of all modules. That wouldn't work if we want to use third-party Kotlin/Native binary while we also have our own Kotlin/Native framework.

Could you please spot some light on what are the current tech limitations that would prevent us from using multiple Kotlin/Native .frameworks ? We can take a look at the implementation and perhaps once needed contribute to make it happen.

**Comment by SvyatoslavScherbina** [comment]
@kprofic 

> yes compiling into one objc framework would work but that's only when we are controlling the codebase of all modules.

Do I understand correctly that in this case it would be enough to compile multiple klibs into one framework? Because klib is the primary Kotlin/Native redistributable library format.

> Could you please spot some light on what are the current tech limitations that would prevent us from using multiple Kotlin/Native .frameworks ?

Sure. Kotlin/Native follows closed world compilation model. This means that compiler combines all used Kotlin libraries when it creates native binary, e.g. framework. So two Kotlin frameworks in one application couldn't use same Kotlin types, because each framework needs to have its own copy of common classes.
