### ISSUE TITLE
Add Serverless Sample

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#1716]
In the Kotlin Native samples there isn't a **Serverless** sample. With Serverless there is a good case for the use of Kotlin Native. The JVM isn't optimised/designed for [Serverless applications](https://blog.travelex.io/blazing-fast-microservice-with-go-and-lambda-d30d95290f28) due to their performance characteristics/requirements:

- Quick start up time
- Low memory usage
- Small code size
- Minimal software dependencies
- Quick response time

There is a valuable opportunity for Kotlin Native to enable Kotlin to have a significant Serverless presence. One key part of taking advantage of this opportunity requires having Serverless samples available so that Kotliners can get started quickly with Serverless. Already some organisations like Pivotal (heavy adopter of Kotlin for server-side development) are [exploring](https://github.com/projectriff/riff/issues/283#issuecomment-390734154) the use of Kotlin Native over Kotlin JVM as the preferred/best way to develop Serverless applications for the **"long term"**. IBM is another organisation that is [considering](https://github.com/ibm-functions/runtime-kotlin/issues/12) providing Kotlin Native support (also likely to be **"long term"**).

One recommended way to provide a Serverless sample would be to have one based on the [OpenFaaS Weather sample](https://gitlab.com/napperley/openfaas-weather-sample) (unofficial OpenFaaS sample). [OpenFaaS](https://github.com/openfaas/faas) would be a good Serverless platform to start with for the following reasons:

- OpenFaaS is a open source project that uses a permissive license (MIT)
- Isn't tied into a proprietary FaaS (Function As A Service) provider
- Uses Docker to easily manage deployment (via Docker images)
- Automatic scaling with Docker Swarm or Kubernetes
- Uses Prometheus for performance metrics and monitoring
- Some major business's have adopted or are experimenting with OpenFaaS (Intel, VMWare, T-Mobile, HashiCorp etc)
- Has a basic Web tool to test Serverless Functions in the development phase
- Provides reasonable quality [documentation](https://docs.openfaas.com/)

**Comment by olonho** [comment]
Nick, generally it sounds like a noble goal, would you be interested in providing PR with this sample?

**Comment by napperley** [comment]
Sorry about the late response. Ended up with so many **kotlin-native** repo notifications in the Inbox that I created a filter to move them into a folder (one of the hazards of email filtering - important emails get lost in the system). Would be happy to do a PR for the sample.

**Comment by olonho** [comment]
Merged.
