### ISSUE TITLE
exception: KonanExternalToolFailure: The /.../clang-llvm-5.0.0-linux-x86-64/bin/llvm-lto exit code: 137.

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1735]
exception: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /home/travis/.konan/dependencies/clang-llvm-5.0.0-linux-x86-64/bin/llvm-lto command returned non-zero exit code: 137.

No output to guess what's going on (or can't see the reason). Maybe a LLVM bug?

You can see the error here (the end of the txt file):
https://api.travis-ci.org/v3/job/397068581/log.txt

**Comment by soywiz** [comment]
As sidenote, travis was running in docker with 4gb of RAM. I have tried to increase to instruct it to not run in docker so it has 7.5gb of memory ( https://docs.travis-ci.com/user/reference/overview/ ). And now I'm getting a segmentation fault not related to this (reported in other issue). Could it be an out of memory? But not 100% sure.

Would be nice that the exception includes the stdout/stderr from the command to provide more information. Maybe LLVM said something in addition to exiting with an error code?
Also would be nice to report total/free memory of the machine too if it fails. Or even recording memory of the machine while long processes are running and give information about peak memory usage. Since when the process starts or exits, it is not consuming memory at all.

**Comment by olonho** [comment]
Looks like OOM killer, please increase RAM in your VM.
