### ISSUE TITLE
Segmentation fault regression related to Char+null in 0.8-dev-2598

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1736]
https://github.com/korlibs/korlibs/blob/master/korma/korma/common/test/com/soywiz/korma/algo/AStarTest.kt#L107

This line fails in 0.8-dev-2598 causing a segmentation fault. https://api.travis-ci.org/v3/job/397442562/log.txt

```
/Users/soywiz/projects/korlibs/korma/korma/native/build/exe/test/debug/test.kexe
[==========] Running 59 tests from 20 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from com.soywiz.korma.algo.AStarTest
[ RUN      ] com.soywiz.korma.algo.AStarTest.testFindReachable
[1]    4376 segmentation fault
```

Works fine:
```
kotlinVersion=1.2.41
kotlinNativeVersion=0.8-dev-2494
```

Fails with segmentation fault:
```
kotlinVersion=1.2.50
kotlinNativeVersion=0.8-dev-2598
```

Changing:
`pointsMap[PointInt(x, y)]?.let { xdigits[it] } ?: (if (c) '#' else '.')`
to:
`(pointsMap[PointInt(x, y)]?.let { "" + xdigits[it] } ?: (if (c) "#" else ".")).first()`

circumvents the problem in `0.8-dev-2598` so I guess it is related to Char and null somehow

**Comment by olonho** [comment]
Shall be fixed.
