### ISSUE TITLE
Exception: EXC_BAD_ACCESS (code=1, address=0x7)

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1748]
```
kotlinVersion=1.2.51
kotlinNativeVersion=0.8-dev-2632
```

![screen shot 2018-07-02 at 01 12 26](https://user-images.githubusercontent.com/570848/42139787-338b9446-7d95-11e8-81b2-2e72b7a3166a.png)

https://github.com/korlibs/korlibs/tree/kotlin-native-gc-crash

To reproduce:

```
./gradlew :korge-native:install
cd samples
./gradlew :sample1-native:compileDebugKotlinNative
./sample1/native/build/exe/main/debug/sample1-native.kexe
```

```
./sample1/native/build/exe/main/debug/sample1-native.kexe
Korge, Korge.pre eventLoop
TRACE
null
EventLoop, EventLoop.main[0]
EventLoop, EventLoop.main[1]
EventLoop, EventLoop.main[2]
EventLoop.main[2]
BaseEventLoopNative, setImmediateInternal[0]
BaseEventLoopNative, setImmediateInternal[1]
EventLoop, EventLoop.main[3]
BaseEventLoopNative, BaseEventLoopNative.loop[0]
BaseEventLoopNative, BaseEventLoopNative.loop[1]
BaseEventLoopNative, BaseEventLoopNative.loop[2]
BaseEventLoopNative, step[0]
BaseEventLoopNative, step[1]
BaseEventLoopNative, step[2]
BaseEventLoopNative, step[3]
BaseEventLoopNative, step[5]
BaseEventLoopNative, step[6]
BaseEventLoopNative, step[6b]
BaseEventLoopNative, step[6c]
BaseEventLoopNative, step[7.1] ImmediateTask(continuation=false, continuationResult=false, continuationException=false, callback=true)
[1]    6158 segmentation fault  ./sample1/native/build/exe/main/debug/sample1-native.kexe
```

I have reached this point after a lot of builds trying different things. Just after the trace I'm forcing a GC. It seems that when accessing a lambda from task (task.callback != null), after the next GC it produces a segmentation fault inside the GC code.

In earlier tests it crashed later, because only crashes on a GC, that's why I'm forcing the GC to detect the earliest code that produces the crash.

**Comment by SvyatoslavScherbina** [comment]
After running
```
./gradlew :sample1-native:compileDebugKotlinNative
```
I get
```
> Could not find com.soywiz:korio-native:0.31.0.
  Searched in the following locations:
      file:/Users/jetbrains/.m2/repository/com/soywiz/korio-native/0.31.0/korio-native-0.31.0.module
      file:/Users/jetbrains/.m2/repository/com/soywiz/korio-native/0.31.0/korio-native-0.31.0.pom
...
```

**Comment by soywiz** [comment]
Did you checked the branch? `git checkout kotlin-native-gc-crash`, (though master should work too).

`:korge-native:install` should depend on `:korio-native:install`. And the `install` task depends on `publishToMavenLocal`.

Have you something configured (either properties, environment variables or additional flags to gradle) that could change the behaviour of the `maven-publish` plugin by changing where are the artifacts locally installed?
The first step `./gradlew :korge-native:install` produces any error or out of memory?

----

EDIT: https://travis-ci.org/korlibs/korlibs/builds/398930556#L3507
If you are using linux, maybe the first step failed, it failed on travis since `__stdoutp` is only available on mac. I have updated the branch to not `fflush` stdout it. (I tried the `fflush(stdout)` to ensure that all the output was written before the crash).

Can you try again?

**Comment by SvyatoslavScherbina** [comment]
> Did you checked the branch?

Sure.

> If you are using linux, maybe the first step failed, it failed on travis since __stdoutp is only available on mac. I have updated the branch to not fflush stdout it. (I tried the fflush(stdout) to ensure that all the output was written before the crash).

This seems to be completely irrelevant, and nothing changes after updating the branch.

Is it possible that you have an obsolete copy of `korio-native` which actually doesn't get installed by  `:korge-native:install`?

**Comment by SvyatoslavScherbina** [comment]
> obsolete copy of `korio-native` in local Maven repo which actually doesn't get installed by `:korge-native:install`

Yes, this seems to be the case: running `install` for `korio-native`, `korau-native` etc. helps to build the sample successfully.

**Comment by SvyatoslavScherbina** [comment]
We have found the root cause of the issue, fix will be available soon.
