### ISSUE TITLE
Publish the Gradle plugin to the Gradle Plugin Portal

### ISSUE THREAD

**Issue by StefMa** [JetBrains/kotlin-native#1751]
Because I saw that comment:
https://github.com/JetBrains/kotlin-native/pull/1746#issuecomment-401675945

I would recommend to publish the Gradle Plugin to the Gradle Plugin Portal so we can use the `plugins {}` block. 

Is it planned to do so? If yes, when?

**Comment by ilmat192** [comment]
Yes, it's in short-term plans. The exact ETA depends on other tasks but I think it will be done before the following release.

**Comment by StefMa** [comment]
Closed since - more or less - delivered in #1789
