### ISSUE TITLE
KProperty reflection

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1754]
This simple test works on Kotlin/JVM:
```
import kotlin.reflect.*

class Record {
    val intVal = 0
    var intVar = 0
    val intGet: Int get() = 0

    val strVal = ""
    var strVar = ""
    val strGet: String get() = ""
}

fun test(property: KProperty<*>) {
    print("${property.name}")
    if (property is KMutableProperty<*>) print(" mutable")
    when (property.returnType.classifier) {
        Int::class -> print(" Int")
        String::class -> print(" String")
    }
    println()
}

fun main(args: Array<String>) {
    test(Record::intVal)
    test(Record::intVar)
    test(Record::intGet)
    test(Record::strVal)
    test(Record::strVar)
    test(Record::strGet)
}
```
On Kotlin/Native I get:
> error: unresolved reference: returnType

But on https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-property/index.html it is not marked as jvm-only.

Will it be implemented? Or what can be used instead?

**Comment by msink** [comment]
Well, ok - I can just use two functions:
```
import kotlin.reflect.*

class Record {
    val intVal = 0
    var intVar = 0
    val intGet: Int get() = 0

    val strVal = ""
    var strVar = ""
    val strGet: String get() = ""
}

fun test(property: KProperty<String>) {
    print(property.name)
    if (property is KMutableProperty<*>) print(" mutable")
    print(" String")
    println()
}

fun test(property: KProperty<Int>) {
    print(property.name)
    if (property is KMutableProperty<*>) print(" mutable")
    print(" Int")
    println()
}

fun main(args: Array<String>) {
    test(Record::intVal)
    test(Record::intVar)
    test(Record::intGet)
    test(Record::strVal)
    test(Record::strVar)
    test(Record::strGet)
}
```
This works.

But still - should `returnType` eventually be implemented, or documented as jvm-only?

**Comment by homuroll** [comment]
Seems like there is no big problem in implementing `returnType` so my guess is that it will be done in the future.

**Comment by msink** [comment]
`returnType.classifier` is not implemented too :)

**Comment by JWThewes** [comment]
@msink Even that does not work for me. What am I doing wrong. This is my code:

   ```
fun getPropertyName(property:KProperty<*>): String {
        return property.name
    }
```

I have no idea what's going wrong here...

**Comment by lahoda** [comment]
members doesn't seem to be implemented either. Following call: 

`val memberList = myClass::class.members`

yields "Unresolved reference: members" error

**Comment by homuroll** [comment]
Looks like it works on master. Closing.

**Comment by mariarosarioidss** [comment]
Hi guys,
   any one help me  **myClass::class.members**  this property leads error in kmm project.
how resolve this error?
