### ISSUE TITLE
How to generate interop stubs for custom objc framework

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#1764]
hi,

I'm trying to add RxCocoa to sample project `kotlin-native/samples/uikit`.

RxCocoa is built with carthage and saved as `kotlin-native/samples/uikit/Carthage/Build/iOS/RxCocoa.framework`.

My RxCocoa.def contains the following:
```
depends = Foundation darwin posix
language = Objective-C
package = RxCocoa 
headers = RxCocoa/RxCocoa.h

headerFilter = RxCocoa/**

compilerOpts = -framework RxCocoa
linkerOpts = -framework RxCocoa
```

I run cinterop as follows(working dir is `kotlin-native/samples/uikit/`):
```
../../dist/bin/cinterop -def RxCocoa.def  -o RxCocoa
Exception in thread "main" java.lang.Error: /var/folders/zk/9j2yt_lj0hj4pf_qyk46j2gc0000gn/T/tmp2133410363181771511.m:1:10: fatal error: 'RxCocoa/RxCocoa.h' file not found
```

What directory does cinterop use as headers source?
Should I pass a command line param? Or is it better to move RxCocoa.framework to another location?

I checked your docs, but didn't manage to find an answer. 
Any help is appreciated.

**Comment by olonho** [comment]
Use `-compilerOpts "-Iwhere/my/headers/are"`

**Comment by ildarsharafutdinov** [comment]
Thank you.

However, I guess I need more help.

**Comment by ildarsharafutdinov** [comment]
it looks like i just need to move `interop` to be above `program`

**Comment by drofwarcs** [comment]
I believe ```includeDirs```  is looking for an absolute path. I was able to generate stubs for AFNetworking using the following:

def file
```
language = Objective-C
headers = Headers/AFURLSessionManager.h Headers/AFURLResponseSerialization.h Headers/AFHTTPSessionManager.h
compilerOpts = -framework AFNetworking
linkerOpts = -F/absolute/path/to/objcframework -framework AFNetworking
```
and in build.gradle file
```
konanArtifacts {
    interop('AFNetworking'){
        packageName 'com.afnetworking'
        includeDirs{
            allHeaders '/absolute/path/to/objcframework/AFNetworking.framework'
        }
    }

    program('MeteoriteFinder'){
        libraries {
            artifact 'AFNetworking'
        }
    }
}
   
```

Notice, that I needed to put absolute path in both files. My builds would fail if it was missing out of either. Maybe I was doing something wrong, but this is the only way I have been able to get interop to generate stubs from 3rd party objc frameworks. Hope that helps.

**Comment by ildarsharafutdinov** [comment]
@drofwarcs,

In case you decide to get rid of absolute paths, I've finally found good example https://github.com/JetBrains/kotlinconf-app/blob/master/ios/build.gradle

Here how it works for me:
```
konanArtifacts {

  def productsDir = new File("Carthage/Build/iOS").absolutePath

  interop('AFNetworking') {
    defFile 'AFNetworking.def'

    compilerOpts "-F${productsDir}"
    linkerOpts "-F${productsDir}"

    includeDirs "${productsDir}/AFNetworking.framework/Headers"
  }

  program('app') {
    libraries {
      artifact 'AFNetworking'
    }

    linkerOpts '-rpath', '@executable_path/Frameworks'
    linkerOpts "-F${productsDir}"
  }
}
```

**Comment by drofwarcs** [comment]
@ildarsharafutdinov worked like a charm. Thx 👍
