### ISSUE TITLE
Unexpected mutability issue

### ISSUE THREAD

**Issue by kpgalligan** [JetBrains/kotlin-native#1775]
I have a weird issue with mutability. I assume this is related to defaulting to freeze on objects. The code in question isn't actually doing anything out of the thread its in, so if this is expected functionality, it'll be at best confusing when it happens.

Here's a test to trigger it:

```
package co.touchlab.knarch.other
import kotlin.test.*

class BreakInit{
    @Test
    fun tryInit(){
        val inner = Inner()
    }
}

class Outer{
    var noteUpdate: String? = null
}

class Inner{
    companion object {
        val theOuter = Outer()
    }

    init {
        theOuter.noteUpdate = "asdf"
    }
}
```

Architecturally this is clumsy, but this is sort of a dumbed down example of what triggers it.

This will fail on '0.8-dev-2701' and above (also '0.8-rc1-2712'). This works on '0.8-dev-2632'.

The exception is:

```
konan.worker.InvalidMutabilityException: mutation attempt of frozen co.touchlab.knarch.other.Outer@1ad261d8 (hash is 0x1ad261d8)
        at 3   knarchtestcmd.kexe                  0x000000010658e906 kfun:kotlin.Exception.<init>(kotlin.String?)kotlin.Exception + 70
        at 4   knarchtestcmd.kexe                  0x000000010658e826 kfun:kotlin.RuntimeException.<init>(kotlin.String?)kotlin.RuntimeException + 70
        at 5   knarchtestcmd.kexe                  0x0000000106632e9d kfun:konan.worker.InvalidMutabilityException.<init>(kotlin.Any)konan.worker.InvalidMutabilityException + 285
        at 6   knarchtestcmd.kexe                  0x0000000106632f35 ThrowInvalidMutabilityException + 85
        at 7   knarchtestcmd.kexe                  0x000000010664c1d8 MutationCheck + 24
        at 8   knarchtestcmd.kexe                  0x0000000106522383 kfun:co.touchlab.knarch.other.Outer.<set-noteUpdate>(kotlin.String?) + 67
        at 9   knarchtestcmd.kexe                  0x0000000106522298 kfun:co.touchlab.knarch.other.Inner.<init>()co.touchlab.knarch.other.Inner + 136
        at 10  knarchtestcmd.kexe                  0x00000001065221be kfun:co.touchlab.knarch.other.BreakInit.tryInit() + 78
(etc)
```

If this is expected, are companion object instances frozen by default?

**Comment by olonho** [comment]
companion object is a singleton object, so it is frozen, and as it happens recursively - theOuter frozen as well. It happens on init of the companion object. As a result - when constructor of Inner is executed - it tries to modify frozen object.
To fix that - either use `@konan.worker.ThreadLocal` on the companion object, or rethink architecture somewhat, or make noteUpdate an AtomicReference<String>.

**Comment by kpgalligan** [comment]
Thanks. Missed that change in the past few commits. In case anybody stumbles on this, here's an explanation: https://github.com/JetBrains/kotlin-native/blob/master/IMMUTABILITY.md

**Comment by lehanphong** [comment]
@olonho @kpgalligan : I want use singleton for "save" session infomation of user in app (when app init), But singleton IMMUTABILITY. Do you have idea for my case. Please help me. thank U.

**Comment by kpgalligan** [comment]
@lehanphong Many ideas, but need to see some code.

**Comment by lehanphong** [comment]
```
class UserInfo {
    private val TAG = "UserInfo"

    companion object {
        val instance: UserInfo by lazy {
            LogVnd.r("Singleton UserInfo constructor run")
            UserInfo()
        }
    }

    var tokenLogin = ""
    var username = ""
    var jwtModel: JwtModel? = null
    var resAuthInfoModel: ResAuthInfoModel? = null
    var resAccountsDerModel: ResAccountsDerModel? = null
}
```
this my singleton code. When user login I cache info to "UserInfo" class.  but UserInfo is a Immutability so my app crash with line: "UserInfo.instance.username = username!!"
I no idea for same case without singleton.

**Comment by kpgalligan** [comment]
Companion objects will be frozen (immutable). UserInfo will be frozen by the time you try to write to your var's. I could explain how to fix this in particular, but you'll need to understand how Kotlin Native state and concurrency work. See [Concurrency](https://github.com/JetBrains/kotlin-native/blob/master/CONCURRENCY.md) and [Immutability](https://github.com/JetBrains/kotlin-native/blob/master/IMMUTABILITY.md). I'll also post my own [blog posts](https://medium.com/@kpgalligan/kotlin-native-stranger-threads-ep-1-1ccccdfe0c99).

I'm not sure I'd do it this way, but if really want to access the data like UserInfo.instance, try something like

```
data class UserInfo(
  val tokenLogin :String,
  val username:String,
  val jwtModel:JwtModel,
  val resAuthInfoModel: ResAuthInfoModel,
  val resAccountsDerModel: ResAccountsDerModel?) {
  private val TAG = "UserInfo"

  companion object {
    private val atom = AtomicReference<UserInfo?>(null)
    var instance: UserInfo
    get() = atom.value!!
    set(value) {
      atom.value = value.freeze()
    }
  }
}
```

I haven't run this, and again I probably wouldn't set it up that way, but it should work.

**Comment by lehanphong** [comment]
thank U @kpgalligan .
