### ISSUE TITLE
[Problem] Xcode run script to also support 32-bit target

### ISSUE THREAD

**Issue by Marcopohlo** [JetBrains/kotlin-native#1799]
Hey guys, 

since you introduced 32-bit support I'm kind of struggling with run script to support it. 

This is a script I'm using: 

```
case "$PLATFORM_NAME" in
iphoneos)
NAME=ios_arm64
;;
iphonesimulator)
NAME=ios_x64
;;
*)
echo "Unknown platform: $PLATFORN_NAME"
exit 1
;;
esac

"$SRCROOT/../core-logic/gradlew" -p "$SRCROOT/../core-logic/" ":native:build"
rm -rf "$SRCROOT/../core-logic/build/"
mkdir "$SRCROOT/../core-logic/build/"
cp -a "$SRCROOT/../core-logic/native/build/konan/bin/$NAME/" "$SRCROOT/../core-logic/build/"
```

How do I include the ios_arm32 folder that gets generated when I'm building for 32-bit device? Any ideas? I thought something with `CURRENT_ARCH` but I have no idea how to handle it properly and you haven't updated any of your samples with this.

I would be really grateful for any help.

**Comment by olonho** [comment]
Why not just compile and copy from two places instead of one, when targeting device?

**Comment by Marcopohlo** [comment]
@olonho Could you please elaborate? I would gladly do anything that simplifies this process :)

**Comment by olonho** [comment]
When you compile for the device, call the compiler twice, once for ios_arm32 and once for ios_arm64.
