### ISSUE TITLE
dokka

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1804]
To run dokka plugin in my expererimental project - https://github.com/msink/kotlin-libui:

1. I had to copy `kotlinx.cinterop` sources in staging directory, and point dokka to it.
It works as temporary workaround, but I doubt it's right way...

2. It does not find `kotlin.Pair`, dont know why. Placed it to staging too. Strange.

3. C structs with forward declaration only - like `struct uiArea` - compiled to `import cnames.structs.uiArea`.
Had to declare it as `typealias uiArea = CPointed` in staged.

So question, and why I asking here, not dokka autors:
Where `KDoc ` documentation will live in Kotlin/Native packages? In source jar's?
Not only for dokka, for IDE hints too.
As temporary workaround copying sources is ok, but what is general direction?

**Comment by msink** [comment]
So it works (well, almost works) in my project just by coincidence? :)

**Comment by olonho** [comment]
Dokka support for Native shall be reported in Dokka issue tracker, not here anyway.
