### ISSUE TITLE
Experimental Gradle Plugin: Provide type safe way to access main sourceSet

### ISSUE THREAD

**Issue by gildor** [JetBrains/kotlin-native#1807]
New Gradle Plugin for K/N provides `sourceSets` extension. 
If you want to configure `main` source set the only way is to use getter on this `NamedDomainObjectCollection`;
Dynamic groovy version:
```groovy
sourceSets.main.component {
    target("linux_x64")
}
```

Type-safe Kotlin-DSL version:
```kotlin
sourceSets["main"].component {
    target("linux_x64")
}
```

everything looks fine and type-safe (except accessing `main` by name).
But if you want to configure `outputKinds`,  you cannot do this on Kotlin, because this property is available only on `KotlinNativeMainComponent`, but `component` block receiver type is `AbstractKotlinNativeComponent`.
So current workaround:

```kotlin
sourceSets["main"].component {
    target("linux_x64")
    if (this is KotlinNativeMainComponent) {
        outputKinds.add(OutputKind.KLIBRARY)
        outputKinds.add(OutputKind.EXECUTABLE)
    }
}
```

This is not perfect solution and also error prone.

I suggest to add a type-safe accessor to sourceSet `main` (and maybe some other default source sets, maybe `test`). It will allow to have exactly the same syntax as Groovy and use proper source set component type without type check

**Comment by eskatos** [comment]
@gildor could you please clarify what plugins and versions you are using? or provide a reproducer?

**Comment by gildor** [comment]
@eskatos Sorry, forgot to log version. as I remember I had this problem with plugin 0.9.x and Gradle 4.7

Now the situation is different because  Kotlin DSL now generates `sourceSets.main` accessor. But the general situation is even worse:
*Plugin `org.jetbrains.kotlin.native` 1.3.10*
Doesn't work at all for me with Gradle 5.0, I'm getting
```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.native', version: '1.3.10']
> Failed to apply plugin [id 'org.jetbrains.kotlin.native']
   > Could not create an instance of type org.jetbrains.kotlin.gradle.plugin.experimental.internal.KotlinNativeMainComponent.
      > Could not generate a proxy class for class org.jetbrains.kotlin.gradle.plugin.experimental.internal.KotlinNativeMainComponent.
```
And it's even without configuration, just apply plugin


*Plugin 1.3.10 with Gradle 4.10.2:*
I now cannot use syntax 
```sourceSets["main"].component {
    target("linux_x64")
}```

Because K/N plugin provides not only Action<T> but also extension function, so now I have resolution ambiguity
![image](https://user-images.githubusercontent.com/186017/49487587-0b108580-f87e-11e8-97f7-19b4dfc19f27.png)

The only workaround is:
```
sourceSets["main"].component.apply {
    target("linux_x64")
}
```
And I still have to check type o fcomponent to add `outputKinds`

**Comment by gildor** [comment]
Created a separate issue about Gradle 5.0 compatibility #2440
