### ISSUE TITLE
Freeze in regex parser

### ISSUE THREAD

**Issue by e5l** [JetBrains/kotlin-native#1814]
Failed to match the following regex:
`(([a-z]|\d|[\Q+-.\E])+)\Q://\E((([a-z]|[A-Z]|\d|[\Q$-_.+\E]|[\Q!*'(),\E]|(\Q%\E(\d|[A-F]|[a-f])(\d|[A-F]|[a-f]))|[\Q;?&=\E])+)(\Q:\E(([a-z]|[A-Z]|\d|[\Q$-_.+\E]|[\Q!*'(),\E]|(\Q%\E(\d|[A-F]|[a-f])(\d|[A-F]|[a-f]))|[\Q;?&=\E])+))?\Q@\E)?(((([a-z]|[A-Z]|\d|(([a-z]|[A-Z]|\d)([a-z]|[A-Z]|\d|\Q-\E)*([a-z]|[A-Z]|\d)))\Q.\E)*([a-z]|[A-Z]|(([a-z]|[A-Z])([a-z]|[A-Z]|\d|\Q-\E)*([a-z]|[A-Z]|\d))))|(\d+\Q.\E\d+\Q.\E\d+\Q.\E\d+))(\Q:\E(\d+))?(((\Q/\E([a-z]|[A-Z]|\d|[\Q$-_.+\E]|[\Q!*'(),\E]|(\Q%\E(\d|[A-F]|[a-f])(\d|[A-F]|[a-f]))|[\Q;&=\E])*)+)(\Q?\E(([a-z]|[A-Z]|\d|[\Q$-_.+\E]|[\Q!*'(),\E]|(\Q%\E(\d|[A-F]|[a-f])(\d|[A-F]|[a-f]))|[\Q;&=\E])*))?(\Q#\E(([a-z]|[A-Z]|\d|[\Q$-_.+\E]|[\Q!*'(),\E]|(\Q%\E(\d|[A-F]|[a-f])(\d|[A-F]|[a-f]))|[\Q;&=\E])*?))?)?`
on string: `https://hacker-news.firebaseio.com/v0/topstories.json`

**Comment by qwwdfsad** [comment]
I think it may be related to https://youtrack.jetbrains.com/issue/KT-25473

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/1852 shall help.
