### ISSUE TITLE
New gradle plugin problems

### ISSUE THREAD

**Issue by e5l** [JetBrains/kotlin-native#1815]
compiler version: `0.9-dev-2831`

- [x]  Couldn't change framework prefix
- [x]  assemble fails without clean 
- [x]  framework for `ios_arm64` is missing(`./gradlew assemble`)
- [ ] The char `-` doesn't escape(targeting ios framework)

**Comment by ilmat192** [comment]
The issues 2-4 are fixed by https://github.com/JetBrains/kotlin-native/pull/1825.

**Comment by ilmat192** [comment]
As for the framework prefix, the compiler has no special flag for that. But the prefix is formed on the basis of a module name (with some additional transformations, see [here](https://github.com/JetBrains/kotlin-native/blob/8740443a4ae3ddfa2b91427f66de47d855b4e321/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExportNamer.kt#L445)) which can be specified manually via the `extraOpts` DSL method:
```
sourceSets.main.component {
    extraOpts ' -module_name' 'fooBar'
}
```
I'm not sure if we need a separate DSL for setting a custom prefix/module name, especially considering that there are some thoughts to deprecate the prefix (at least for Swift).

@e5l If you has no objections, I'll close this issue.

**Comment by e5l** [comment]
Nope, `module_name` would be enough. Thanks for the investigation.

**Comment by thevery** [comment]
Maybe add `module_name` to docs if not yet?

**Comment by ilmat192** [comment]
It is already there: https://github.com/JetBrains/kotlin-native/blob/master/FAQ.md#q-how-do-i-specify-custom-objective-c-prefixname-for-my-kotlin-framework

**Comment by napperley** [comment]
What is the Kotlin DSL version for this [snippet](https://github.com/JetBrains/kotlin-native/issues/1815#issuecomment-407667832)?

**Comment by e5l** [comment]
> The char - doesn't escape(targeting ios framework)

Fail with transitive dependency: `Kotlinx-coroutines-core-nativeCoroutineDispatcher`

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/commit/7c37f3134fc7d16e767eb012b30072f0bc8aea26.
