### ISSUE TITLE
Debug problems

### ISSUE THREAD

**Issue by e5l** [JetBrains/kotlin-native#1816]
- [ ] No line numbers in Kotlin exception stack trace(but there are kt line numbers in native backtrace)
- [ ] Debug version of the standard library is missing(sources are not available)

**Comment by abelkov** [comment]
For 1 see also https://youtrack.jetbrains.com/issue/KT-25510

**Comment by olonho** [comment]
To implement line numbers in the backtrace we need to implement DWARF parser.
Debug version of stdlib will appear once we switch to IR libs.
