### ISSUE TITLE
Laziness in frozen objects

### ISSUE THREAD

**Issue by sandwwraith** [JetBrains/kotlin-native#1817]
I think we need some sort of `by lazy {}` support even if the object is frozen. Use-case:

```kotlin
data class Data(val a: Int) {
        object serializer: KSerializer<Data> {
        override val descriptor: SerialDescriptor

        init {
            val desc = SerialClassDescImpl("Data")
            desc.addElement("name")
            descriptor = desc
        }
        }
}

class SerialClassDescImpl(val className: String) { 
// ...

private val array: MutableList<String>
fun addElement(name: String) = array.add(name)
private val inverseIndices: Map<String, Int> by lazy { buildIndices() }
fun buildIndices() = /** compute inverse index of [array] **/
}
```

This code works fine in Kotlin/JVM and Kotlin/JS, but it throws exception on Kotlin/Native, because `object serializer` got frozen after creation and `descriptor` is frozen too, while actual access to lazy indices is performed much later (in deserialization of class Data). Lazy structures in this place are important for performance of serialization framework. While this particular case can be workarounded by forcing all computations before assignment to object field, in general, absence of this feature can make impossible certain optimisations. @elizarov  supposes such lazy computation in frozen objects can be performed using atomic references.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/blob/d376d084386a94d0cfd54830f15f387865cd6313/runtime/src/main/kotlin/konan/worker/Atomics.kt#L192

**Comment by elizarov** [comment]
@olonho Thanks. Shouldn't stdlib `lazy { ... }` point to this implementation, so that we don't have to create our own expect/actual wrappers in common code?

**Comment by sandwwraith** [comment]
I think stdlib `lazy` should point to this implementation, because tread-safety is guaranteed by its contract. `lazy(LazyThreadSafetyMode.NONE)`, imo, should not and it is ok for it to throw exception from frozen object.

**Comment by olonho** [comment]
`atomicLazy` freezes producer lamdba, so it cannot be used as drop in replacement for regular `lazy`.

**Comment by sandwwraith** [comment]
I'd say it is impossible to choose whether to use `lazy` or `atomicLazy` – on the stage of class design, you can't predict if this class will be used in some object's fields or not (especially if you're writing a library). You also can't actually change anything at object's level when you're trying to use this class – if its author didn't use `atomicLazy`, you simple can't refer this class in object, there's no workarounds.

`lazy` provides thread-safety guarantees, so it should work somehow with frozen/detached object. Perhaps it worth to implement some intrinsic which will replace untriggered `lazy`s with `atomicLazy`s on freezing attempt?

**Comment by elizarov** [comment]
+1. The `lazy { ... }` in standard library should be freeze-aware. It should freeze its lambda if and only if it is frozen itself. So, basically, instead of `atomicLazy` that freezes lambda on creation, a standard `lazy { ... }` should be implemented with two fields -- one field with an `AtomicRef` and another field with a reference to lambda. The former is already "frozen" (actually, shareable), while the later would become frozen if the lazy itself is frozen.

**Comment by SvyatoslavScherbina** [comment]
@elizarov and how does this implementation handle garbage cycles?

**Comment by elizarov** [comment]
@SvyatoslavScherbina But how would garbage cycle appear in case of `lazy`? When `lazy` is frozen it also freezes lambda, so everything this lambda closes over is frozen. Now, when there is an access to lazy, the lamdba computes the value of lazy based on some set of frozen objects. It does not matter in which which Kotlin Machine instance this computation actually happens. The key trick here is that a frozen `lazy` shall also freeze the result of its computation (first), before storing it to `AtomicRef` and returning. The leftover garbage that was produced while lazy lambda was working would be ultimately collected by whatever Kotlin Machine this lambda was accessed from.  Am I missing some way in which garbage cycles can still occur? Do you have an example?

**Comment by elizarov** [comment]
@SvyatoslavScherbina You've shown an example of how an `AtomicRef` can be used to create a cycle among frozen objects. Indeed, `AtomicRef` is quite an unsafe primitive from this standpoint. I don't think its worth investing time into `AtomicRef` GC at this point (but we can do it later if we have more use-cases). Instead, we shall clearly document `AtomicRef` as an advanced API that can lead to memory leaks if not used properly. 

However, it looks like the way `AtomicRef` is going to be used _inside_ `lazy` implementation is safe. I don't see a way to create such leaks using `lazy` only.

**Comment by SvyatoslavScherbina** [comment]
`AtomicRef` is going to be used inside implementation of many different APIs, e.g. coroutines. So I find  this situation highly possible even without direct usage of `AtomicRef`. The problem is that `AtomicRef` can't be correctly used for `lazy`, because it must eventually be nullified.

**Comment by sandwwraith** [comment]
But `atomicLazy` is already built on top of `AtomicRef` and its documentation says 
> Atomic lazy initializer, could be used in frozen objects, freezes initializing lambda,
so use very carefully. Also, as with other uses of an @AtomicReference may potentially
 leak memory <...>

So this already exists and is going to be used somehow anyway, or am I missing something here?

**Comment by SvyatoslavScherbina** [comment]
You aren't missing anything, `atomicLazy` is quite unsafe.

**Comment by olonho** [comment]
As per today discussion, there was an idea that `lazy` for Native could be implemented by having traditional lazy semantics if `LazyImpl` is not frozen, or using `atomicLazy`-like semantics, if   `LazyImpl` is frozen. @elizarov @SvyatoslavScherbina could you please sketch how you believe code shall look like.

**Comment by olonho** [comment]
061ea53853fb96737bcbdf9a8e698b299c29d975 shall fix it.
