### ISSUE TITLE
binary file to konan.ImmutableBinaryBlob

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1819]
Currently if I want to embed some binary resource in executable, i need to dump it to something like
```
val `tetris_all.bmp` = immutableBinaryBlobOf(0x42, 0x4D, 0xF6, .....)
```
and add to source files.

It works, but IMHO is too complex for this simple task.
Can you please add some command-line and gradle-DSL options to do it directly, without intermediate `tetris_all.bmp.kt` file?

**Comment by joelhandwell** [comment]
Related SO question: https://stackoverflow.com/questions/51697533/how-to-include-text-blob-file-as-resource-to-be-compiled-together-as-executable

**Comment by msink** [comment]
@joelhandwell I do not know, closest is just compile it as String:

```
val `hello.txt` = """
...textfile...
"""

val text = `hello.txt`
```

Or as map:
```
val __resources = mapOf("hello.txt" to """
...textfile...
""")

val text = __resources["hello.txt"]

**Comment by olonho** [comment]
Yeah, idea is good, but we not yet sure how it better be done. I see the following options:
 - compiler switch like `-binary variable_name,file_path` which shall create an top level object 
named `variable_name` of type `BinaryBlob` with the content of the provided file
 - Gradle DSL verb, like withBinary {} which produces source code artifact, which could be then linked regularly 
 - smth else

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-39194
