### ISSUE TITLE
How to defined klib path in gradle?

### ISSUE THREAD

**Issue by mgr9525** [JetBrains/kotlin-native#1821]
I want not to use klib install!
now i can copy the klib to project's root folder,but i want to copy to klib folder.

Thanks.

**Comment by olonho** [comment]
Not sure if this report is clear enough, please provide more information.

**Comment by PramUkesh** [comment]
May be he is asking how to use klib libraries   without using default local lib repo using
klib install utils
But still want to klib using gradle but
not through -l utils while using konanc through gradle @mgr9525
