### ISSUE TITLE
Using Carthage/Cocoapods dependencies.

### ISSUE THREAD

**Issue by michalchudziak** [JetBrains/kotlin-native#1822]
Hey! 

Great job with the compiler so far!!
I wanted to integrate an external library to the project (ie. Alamofire). I've used Carthage to build the framework and add the following lines to my `build.gradle` file

```
konanArtifacts {
    def productsDir = new File("Carthage/Build/iOS").absolutePath

    interop('Alamofire') {
        defFile 'Alamofire.def'

        compilerOpts "-F${productsDir}"
        linkerOpts "-F${productsDir}"

        includeDirs "${productsDir}/Alamofire.framework/Headers"
    }
    program('Scaffolding') {
        libraries {
          artifact 'Alamofire'
        }

        linkerOpts '-rpath', '@executable_path/Frameworks'
        linkerOpts "-F${productsDir}"
    }
}
```

The `.def` file looks like this:

```
depends = Foundation UIKit darwin posix
language = Objective-C
package = framework.alamofire
headers = Alamofire.h Alamofire-Swift.h

headerFilter = **

compilerOpts = -framework Alamofire
linkerOpts = -framework Alamofire
```

While building kotlin I'm experiencing following error:
```
Error:Exception in thread "main" java.lang.Error: /blablabla/Carthage/Build/iOS/Alamofire.framework/Headers/Alamofire.h:25:1: error: use of '@import' when modules are disabled
```

These are my xCode settings for Obj-C modules:
![image](https://user-images.githubusercontent.com/7837457/42993187-051f7e54-8c0b-11e8-9e59-5fc6f4478e81.png)

Is this a problem of the library's compatibbility with K/N? Am I doing something wrong?

Also second question comes to my mind: 
https://github.com/JetBrains/kotlin-native/issues/1559 Here you claim that we can use CocoaPods (no dedicated gradle plugin yet) - do you have any guide on how to use this kind of libraries? What are the limitations?

**Comment by mike866** [comment]
@ildarsharafutdinov 
I've seen your issue. I've tried adding it like:

```
    interop('Alamofire') {
        defFile 'Alamofire.def'

        compilerOpts "-F${productsDir}", '-fmodules'
        linkerOpts "-F${productsDir}"

        includeDirs "${productsDir}/Alamofire.framework/Headers"
    }
```

The import issue seems to be gone, but kotlin is throwing `Error:(17, 5) expecting member declaration` at me when I'm trying to use `Alamofire` (`import framework.alamofire.*`) Import doesn't seem to work :(

**Comment by ildarsharafutdinov** [comment]
@mike866,

I seem to have managed to build & link Alamofire as follows(although I didn't run it). I'm not sure how it differs from your setup.

def:
```
language = Objective-C
package = framework.alamofire
headers = Alamofire.h Alamofire-Swift.h
headerFilter = **

compilerOpts = -framework Alamofire -fmodules
linkerOpts = -framework Alamofire
```

build.gradle:
```
apply plugin: 'konan'

konan.targets = [
  'iphone',
  'iphone_sim'
]

konanArtifacts {

  def productsDir = new File("Carthage/Build/iOS").absolutePath

  interop('Alamofire') {
    defFile 'Alamofire.def'

    compilerOpts "-F${productsDir}" 
    linkerOpts "-F${productsDir}"

    includeDirs "${productsDir}/Alamofire.framework/Headers"
  }

  program('app') {
    libraries {
      artifact 'Alamofire'
    }

    linkerOpts '-rpath', '@executable_path/Frameworks'
    linkerOpts "-F${productsDir}"
  }
}
```

main.kt:
```
import kotlinx.cinterop.*
import platform.Foundation.*
import platform.UIKit.*
import framework.alamofire.*
...
```

```
../gradlew compileKonanappIos_x64

BUILD SUCCESSFUL in 0s
3 actionable tasks: 1 executed, 2 up-to-date
```

My working dir is `kotlin-native/samples/uikit`.

**Comment by mike866** [comment]
I'm using basic AppCode setup, which I guess is similar. Have you tried importing the lib on kotlin side? Did it work?

**Comment by mike866** [comment]
Maybe it's a problem with Alamofire itself. I'm not sure how well it plays with Obj-C

**Comment by olonho** [comment]
Not sure what is exact problem in Kotlin/Native here. CocoaPods in general not yet supported in Gradle plugin, but we are considering implementing it.

**Comment by mike866** [comment]
@olonho Any ETA on this? I think it might make framework more usable for the larger audience.

**Comment by ildarsharafutdinov** [comment]
As far as I understand the issue is caused by the fact kotlin native doesn't support pure swift. So unless Alamofire becomes compatible with obj-c, it's impossible to use it with kotlin.

**Comment by SvyatoslavScherbina** [comment]
CocoaPods integration was implemented some time ago, and got significants improvements in 1.4.
Please refer to the documentation: https://kotlinlang.org/docs/reference/native/cocoapods.html
