### ISSUE TITLE
iOS 32/64 bit issue

### ISSUE THREAD

**Issue by thevery** [JetBrains/kotlin-native#1824]
```
> Task :unimail:ios:compileKonanNative-libIos_arm64
unimail/ios/src/main/kotlin/com/yandex/unimail/support/Async.kt:10:47: error: type mismatch: inferred type is Int but Long was expected
        val queue = dispatch_get_global_queue(QOS_CLASS_USER_INTERACTIVE, 0)
```
ok, let's use `toLong()`:

```
> Task :unimail:ios:compileKonanNative-libIos_arm32
unimail/ios/src/main/kotlin/com/yandex/unimail/support/Async.kt:10:47: error: type mismatch: inferred type is Long but Int was expected
        val queue = dispatch_get_global_queue(QOS_CLASS_USER_INTERACTIVE.toLong(), 0)
```

**Comment by msink** [comment]
> dispatch_queue_global_t dispatch_get_global_queue(long identifier, unsigned long flags);

Maybe it wants `0L` ?

**Comment by SvyatoslavScherbina** [comment]
We have special trick for such cases: https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#portability

E.g.:
```
val queue = dispatch_get_global_queue(QOS_CLASS_USER_INTERACTIVE.signExtend(), 0)
```

**Comment by thevery** [comment]
`signExtend()` works, thank you! Maybe point to it in compiler error (+`import kotlinx.cinterop.*`)?

**Comment by SvyatoslavScherbina** [comment]
Compiler is not currently aware of whether `signExtend` is applicable to fix the error. So such a message would be annoying.

**Comment by olonho** [comment]
Guess issue is resolved.

**Comment by suparngp** [comment]
I stumbled upon this today with the exact same use case. I used `QOS_CLASS_USER_INTERACTIVE.convert(), 0.convert()` to resolve the errors.
