### ISSUE TITLE
ObjC method provided by getter does not match the requirement's selector

### ISSUE THREAD

**Issue by jtouzy** [JetBrains/kotlin-native#1843]
### UPDATE with details
___
Xcode version : **9.4.1 (9F2000)**.
Kotlin version : **1.2.50**
Konan version : **0.8**

### ORIGIN
___
I'm trying to use a Kotlin/Native built framework in an iOS app.

I use this framework only for Presenters and Models classes in an MVP architecture, for having common codebase with the two platforms. These classes are full kotlin (I don't even use the multiplatform feature), and pretty basics.

I get this error after importing the framework : 
<img width="573" alt="capture d ecran 2018-08-06 a 13 55 55" src="https://user-images.githubusercontent.com/5709133/43715463-dad650fe-9980-11e8-8ee0-df9778b44989.png">

It works well with another MVP "module", with exactly the same Kotlin interfaces (except the module name). Here's my Kotlin classes :

**EventDetailsView**
```kotlin
package com.codeglacier.scorego.mobilecommon.modules.eventdetails

import com.codeglacier.scorego.mobilecommon.modules.eventdetails.viewmodel.EventVM
import com.codeglacier.scorego.mobilecommon.pattern.View

interface EventDetailsView: View {
    var presenter: EventDetailsPresenter?
    fun showDetails(viewModel: EventVM)
}
```

**EventDetailsPresenter**
```kotlin
package com.codeglacier.scorego.mobilecommon.modules.eventdetails

import com.codeglacier.scorego.mobilecommon.pattern.Presenter

interface EventDetailsPresenter: Presenter<EventDetailsView> {
    val service: EventDetailsService
    val router: EventDetailsRouter

    fun viewDidLoad()
}
```

I think objc headers can be malformed (the setPresenter function always have a different setter name), if you look at every view :

```swift
// A view
@protocol SGCAuthSignInView <SGCView>
...
@property (setter=setPresenter_:) id<SGCAuthSignInPresenter> _Nullable presenter;
@end;

// ...Another view
@protocol SGCEventDetailsView <SGCView>
...
@property (setter=setPresenter__:) id<SGCEventDetailsPresenter> _Nullable presenter;
@end;

// ...Another view
@protocol SGCWelcomeView <SGCView>
...
@property (setter=setPresenter____:) id<SGCWelcomePresenter> _Nullable presenter;
@end;
```

Welcome and AuthSignin modules works fine. But EventDetails fails.
I can give more details if anyone needs it, just ask.

Thanks.

**Comment by jtouzy** [comment]
Xcode version : **9.4.1** (9F2000).
Kotlin version : **1.2.50**
Konan version : **0.8**

Which details do you need to investigate on this ?

**Comment by jtouzy** [comment]
I just see that code compiles with a very weird implementation :

```swift
    var _pres: SGCEventDetailsPresenter?

    var presenter: SGCEventDetailsPresenter? {
        get {
            return _pres
        }
        @objc(setPresenter__:) set(presenter) {
            _pres = presenter
        }
    }
```

Because i need to set the ```@objc(setPresenter__:)``` annotation to work.
I don't really know why the compiler needs that specific selector name in this class but never had problems with other modules.

**Comment by SvyatoslavScherbina** [comment]
Now I see the problem you have encountered.

> I just see that code compiles with a very weird implementation :

It works as expected. To override a property with custom accessor selector you need to specify that selector in the implementation manually.

> I don't really know why the compiler needs that specific selector name in this class but never had problems with other modules.

The compiler currently mangles method selectors to avoid clashes between unrelated methods in different classes and interfaces.

**Comment by jtouzy** [comment]
It's not really an override, it's just a protocol implementation of a property in this case.
So, why the compiler does not need to have the selector annotation on other modules ? (like described in the header file above, the difference of the selector is just 2 underscores).

**Comment by jtouzy** [comment]
```swift
// ==> FIRST
@protocol SGCWelcomeView <SGCView>
...
@property (setter=setPresenter____:) id<SGCWelcomePresenter> _Nullable presenter;
@end;

// ==> SECOND
@protocol SGCEventDetailsView <SGCView>
...
@property (setter=setPresenter__:) id<SGCEventDetailsPresenter> _Nullable presenter;
@end;
```

Like i said before, when i'm implementing the first protocol, the compiler does not need to have a get/set on the "presenter" property, it works as expected. But it's needed when i'm implementing the second one (this current issue). I don't understand why the compiler react differently.

**Comment by jtouzy** [comment]
I can't give all the project codebase but i'll try to reproduce in a smaller project.
I'll let you know as soon as everything is ready.
