### ISSUE TITLE
constructor(pStr: String): super(pStr) {} baseclass constructor call override function error

### ISSUE THREAD

**Issue by chinacharis** [JetBrains/kotlin-native#1870]
class person {
    constructor() {}

    constructor(pStr: String) {
        fromJson(pStr)
    }
   protected fun fromJson(pStr: String) {
        val jsonObj = JsonHelper.newJson(pStr)
        ...
        load(jsonObj)
    }
   protected open fun load(pJSONObj: JSONObject) {}
}

class developer: person {
    var age: Int = 0
    var weight: Int = 0
    constructor() {}

    constructor(pStr: String): super(pStr) {}

  override fun load(pJSONObj: JSONObject) {
        age = JsonHelper.getInt(pJSONObj, "age")
        weight = JsonHelper.getInt(pJSONObj, "weight")
    }
}

var worker = developer(json)
worker.age and work.weight is 0 

modify code  as below:
class developer: person {
    var age: Int = 0
    var weight: Int = 0
    constructor() {}

    constructor(pStr: String) {
    super.fromJson(pStr)
  }

  override fun load(pJSONObj: JSONObject) {
        age = JsonHelper.getInt(pJSONObj, "age")
        weight = JsonHelper.getInt(pJSONObj, "weight")
    }
}

var worker = developer(json)
worker.age and work.weight is ok, can explain for me?

**Comment by olonho** [comment]
Not sure if we could help here. Please provide details on what is not working and how do you expect it to work.

**Comment by chinacharis** [comment]
constructor(pStr: String): super(pStr) {} seems like age and weight first assigned in load(), then assigned 0 in constructor(), always is 0
constructor(pStr: String) {super.fromJson(pStr)} work OK,  first initiablization 0, then assigned right after load()

**Comment by chinacharis** [comment]
thanks, this is specs. c++ not allow superclass constructor call pure virtual function, but java allow.
