### ISSUE TITLE
Primitive's constructor invocation

### ISSUE THREAD

**Issue by MrAkakuy** [JetBrains/kotlin-native#1881]
Look at this little code snippet:
`fun main(args: Array<String>) {
	println(Int())
}`

This simple code should not be built successfully. Kotlin JVM says:
> Cannot access '\<init\>': it is private in 'Int'

But the Kotlin/Native compiller breaks only at module verification, giving a full [dump of bitcode](https://github.com/JetBrains/kotlin-native/files/2287179/err.log).

P.S.: Konanc v0.8.1

**Comment by ilmat192** [comment]
Just checked the issue on master and it isn't reproducible. Fixed by https://github.com/JetBrains/kotlin-native/pull/1840.
