### ISSUE TITLE
Objc Interop : Interface inheritance with generic types

### ISSUE THREAD

**Issue by jtouzy** [JetBrains/kotlin-native#1884]
## Version context
Xcode version : 9.4.1 (9F2000).
Kotlin version : 1.2.50
Konan version : 0.8

## Context
I'm trying to use a Kotlin/Native built framework in an iOS app (without multiplatform feature, only pure Kotlin classes).

## Problem
For date interoperability between iOS and Android, we have made a dedicated class named DateTimeInfo. This class needs to be comparable, so, we wrote :

```kotlin
interface DateTimeInfo: Comparable<DateTimeInfo> {
    fun format(dateFormat: String): String
    // some other functions
}
```

When I try to import it in iOS, i use the generator to implements the interface :
<img width="594" alt="capture d ecran 2018-08-15 a 10 28 30" src="https://user-images.githubusercontent.com/5709133/44139033-2c7eb418-a076-11e8-918e-56031a7e7d4d.png">
And then i have this build issue :
<img width="582" alt="capture d ecran 2018-08-15 a 10 29 02" src="https://user-images.githubusercontent.com/5709133/44139060-3eb0e278-a076-11e8-899e-636c55d5e386.png">

The ```compareTo()``` method selector is implemented twice. It's because of **interface inheritance with generic types**. I already had the same problem when i was using interface inheritance (with custom interfaces with generic types) in my common project.

The conflicting generated .h file :

```objc
@protocol SGCStdlibComparable
@required
- (int32_t)compareToOther:(id _Nullable)other __attribute__((swift_name("compareTo(other:)")));
@end;
```

```objc
@protocol SGCDateTimeInfo <SGCStdlibComparable>
@required
- (NSString *)formatDateFormat:(NSString *)dateFormat __attribute__((swift_name("format(dateFormat:)")));
- (int32_t)compareToOther:(id<SGCDateTimeInfo>)other __attribute__((swift_name("compareTo(other:)")));
@end;
```

**Comment by olonho** [comment]
Closing for now.
