### ISSUE TITLE
Problem with auto-generated names of the ObjC methods

### ISSUE THREAD

**Issue by elizarov** [JetBrains/kotlin-native#1898]
See this report: https://github.com/Kotlin/kotlinx.coroutines/issues/496

**Comment by Hazer** [comment]
Any workaround to be done at least?

**Comment by RR12** [comment]
You can make every coroutines related part to be `internal` for now

**Comment by brettwillis** [comment]
As a workaround, I am currently using a custom shell script build phase in the Xcode project, to replace all `"Kotlinx-coroutines-core-native"` strings with `""` in the Kotlin framework's header file.

Order this build script after the Kotlin/Native compiler script.

In my case the Kotlin framework is `common.framework`, so the shell script looks like this:

    cd \"$CONFIGURATION_BUILD_DIR\"
    sed -i -e 's/Kotlinx-coroutines-core-native//g' common.framework/Headers/common.h

I don't understand enough about compilers and linkers to know why this doesn't cause linker or runtime errors, but it works! Perhaps because, in my case, the only way that those symbols are referenced from Swift is when they are returned out of the Kotlin framework (I'm not instantiating any of those symbols from Swift).

Hope this helps!

**Comment by mohit-gurumukhani** [comment]
Can anyone comment if the above workaround is safe or if there is some other way around?

**Comment by irgaly** [comment]
I'm working with Kotlin New Multiplatform Project : https://github.com/h0tk3y/k-new-mpp-samples

The kotlinx.serialization's jsonparser(0.7.0) classes goes invalid objC header too.
I did the same workaround, by deleting invalid objC properties in header file with gradle script.

build.gradle
```
afterEvaluate {
    [linkMainReleaseFrameworkIosArm64, linkMainDebugFrameworkIosArm64,
        linkMainReleaseFrameworkIosX64, linkMainDebugFrameworkIosX64].forEach { task ->
        task.doLast {
            kotlin.targets {
                configure([iosArm64, iosX64]) {
                    def kind = FRAMEWORK.outputDirectoryName
                    def buildType = RELEASE.name.toLowerCase()
                    def target = compilations.main.target.disambiguationClassifier
                    def header = new File(buildDir, "bin/$target/${compilations.main.name}/$buildType/$kind/${your_framework_name}.framework/Headers/${your_framework_name}.h").absolutePath
                    ant.replace(file: header, token: '@property (readonly) double double;', value: '')
                    ant.replace(file: header, token: '@property (readonly) float float;', value: '')
                    ant.replace(file: header, token: '@property (readonly) int32_t int;', value: '')
                    ant.replace(file: header, token: '@property (readonly) int64_t long;', value: '')
                }
            }
        }
    }
}
```

**Comment by lehanphong** [comment]
I have same bug
<img width="662" alt="Screen Shot 2019-03-28 at 6 01 18 PM" src="https://user-images.githubusercontent.com/11489659/55152699-82e32280-5183-11e9-9e0e-2e6fbf445b6f.png">

@irgaly Can U show full build.gradle. I don't understand [linkMainReleaseFrameworkIosArm64, linkMainDebugFrameworkIosArm64,  linkMainReleaseFrameworkIosX64, linkMainDebugFrameworkIosX64] what does this mean. And compilation.name, ios_framework_name is your config?

Help me, thank!!!

**Comment by lehanphong** [comment]
<img width="564" alt="Screen Shot 2019-03-29 at 10 37 20 AM" src="https://user-images.githubusercontent.com/11489659/55207907-b323d300-520e-11e9-81f9-328351fc51ea.png">
I fixed this by script. Thank @brettwillis

**Comment by olonho** [comment]
@elizarov @SvyatoslavScherbina anything left here?

**Comment by SvyatoslavScherbina** [comment]
All reported cases are already fixed.
