### ISSUE TITLE
CLion project examples have corrupt gradle-wrapper.jar

### ISSUE THREAD

**Issue by rnentjes** [JetBrains/kotlin-native#1935]
I updated CLion and the Kotlin native plugin and tried to create the new HelloWorld gradle based project.

Firstly the gradlew file is not made executable.
Secondly I get the following error:

```
rnentjes@rnentjes-System-Product-Name:~/CLionProjects/untitled3$ ./gradlew run
bash: ./gradlew: Permission denied
rnentjes@rnentjes-System-Product-Name:~/CLionProjects/untitled3$ chmod +x ./gradlew
rnentjes@rnentjes-System-Product-Name:~/CLionProjects/untitled3$ ./gradlew run
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
rnentjes@rnentjes-System-Product-Name:~/CLionProjects/untitled3$ 
```

This is on CLion: #CL-182.4129.51 with plugin 182.4129.59

Btw, the build.sh file in the CsvParser example works but complains about a missing konan.sh file:

```
rnentjes@rnentjes-System-Product-Name:~/CLionProjects/untitled3$ ./build.sh
bash: ./build.sh: Permission denied
rnentjes@rnentjes-System-Product-Name:~/CLionProjects/untitled3$ chmod +x ./build.sh
rnentjes@rnentjes-System-Product-Name:~/CLionProjects/untitled3$ ./build.sh
./build.sh: line 5: /home/rnentjes/CLionProjects/untitled3/../konan.sh: No such file or directory
Artifact path is /home/rnentjes/CLionProjects/untitled3/build/bin/CsvParser.kexe
rnentjes@rnentjes-System-Product-Name:~/CLionProjects/untitled3$ 
```

After some investigation it turns out that the gradle-wrapper.jar is corrupt (output from Engrampa Archive Manager):

```
Archive:  /home/rnentjes/CLionProjects/untitled4/gradle/wrapper/gradle-wrapper.jar
Zip file size: 92273 bytes, number of entries: 50
error [/home/rnentjes/CLionProjects/untitled4/gradle/wrapper/gradle-wrapper.jar]:  missing 3183384606 bytes in zipfile
  (attempting to process anyway)
error [/home/rnentjes/CLionProjects/untitled4/gradle/wrapper/gradle-wrapper.jar]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

Replacing the jar with an 4.5 gradle-wrapper.jar from another project fixed it.

**Comment by rnentjes** [comment]
That's: 641aaa40ee87b7f4ad4eb56675422cc0

**Comment by stigger** [comment]
That doesn't match the hash of the file that's being distributed in the plugin (you can check by downloading and unzipping 
https://plugins.jetbrains.com/files/10454/49188/kotlinNative-clion-182.4129.59.zip?updateId=49188&pluginId=1045)4. Please try exiting the IDE, deleting `~/.CLion2018.2/kotlin-native-templates` and starting it again.

**Comment by rnentjes** [comment]
The gradle-wrapper.jar in ~/.CLion2018.2/system/kotlin-native-templates/gradle/HelloWorld/gradle/wrapper/gradle-wrapper.jar looks correct (md5 hash 7d7d78c91ccaaa93a19578ae254bc264). 

The gradle-wrapper.jar in the generated (copied) projects contain the EF BF BD byte sequences which indicate UTF-8 unresolved characters. Maybe the file is copied character based i.o. binary?

See the attached screenshot for a comparison of the two files (original left, generated project one on the right).
![screenshot from 2018-08-27 17-12-05](https://user-images.githubusercontent.com/553168/44668055-c5415700-aa1c-11e8-86d0-52a480c4ca15.png)

**Comment by stigger** [comment]
You're right, thanks for the investigation. Will be fixed in the next update.
