### ISSUE TITLE
How to call Kotlin/Native functions in shared library from Android app?

### ISSUE THREAD

**Issue by felipecsl** [JetBrains/kotlin-native#1943]
I'm trying to create an Android application that uses a shared library (.so) file generated from a Kotlin/Native project. I'm basically manually copying the output `.so` file to the Android app `src/main/jniLibs` and manually calling `System.loadLibrary("mylib")`, which seems to work fine.
However, when I try to invoke any function from the library, it just fails with `java.lang.UnsatisfiedLinkError: No implementation found for <function_name>`. I'm clearly failing to define the native function from Android. I'm trying something like this:

```kotlin
external fun myFunction()
```

is there a way I can achieve this with the current Kotlin/Native version? if so, how can I define the `external` function so it correctly matches the shared library? I looked into using the `cinterop` but the output seems to be aimed for other Kotlin/Native projects and not Android projects. Can anyone provide any pointers please?

Thanks a lot in advance, this is super exciting!

**Comment by olonho** [comment]
You need manually bind K/N function to appropriate JNI name, using CName("Java_com_foo_Bar", "Bar") annotation on K/N side. See https://stackoverflow.com/questions/32470463/is-the-naming-convention-for-java-native-interface-method-and-module-name for matching rules.

**Comment by felipecsl** [comment]
Thanks @olonho, in which dependency can I find the `@CName` annotation?

**Comment by olonho** [comment]
See https://github.com/JetBrains/kotlin-native/blob/master/backend.native/tests/produce_dynamic/simple/hello.kt as an example of using this annotation.

**Comment by felipecsl** [comment]
Yeah I saw that, however that annotation doesn't seem to available in the compile classpath for a project that has the `konan` plugin applied. I'll see about building a jar with that and manually including it into my project.
I'm also curious if the functions will be visible for JNI (they'd need `JNIEXPORT` and `JNICALL` (see https://stackoverflow.com/questions/19422660/when-to-use-jniexport-and-jnicall-in-android-ndk)
Either way I'll try it out and report back here with my findings

**Comment by msink** [comment]
AFAIK there was global renaming `konan.*` to `kotlin.native.*` between 0.8.2 and current master.
So probably it is `konan.CName` if you use 0.8.2 or earlier.

**Comment by felipecsl** [comment]
Alright I found `CName` in `konan.internal` with K/N 0.8.2. I correctly see this in the generated C header file:
```
extern void Java_com_foo_bar_JniKt_baz();
```
However when I tried to call it still didn't work:
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.foo.bar.JniKt.baz() (tried Java_com_foo_bar_JniKt_baz and Java_com_foo_bar_JniKt_baz__)
```

**Comment by felipecsl** [comment]
ohh, never mind, I just forgot to manually copy the .so files. It actually did work 😄 
thank you!

**Comment by mananpoddar** [comment]
@felipecsl  it's not working for me. I tried calling the functions from my android app after system.loadLibrary() It says, it is not able to find the function. Could you point me to the git repo where you generated the .so file and the repo where you used the function, it would be of great help.
