### ISSUE TITLE
how to use precompiled headers in def?

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#1946]
hi,

what is the right way to specify `<my-library>.pch` file in def?

**Comment by olonho** [comment]
Have you tried `compilerOpts = -include-pch=<my-library>.pch`?

**Comment by ildarsharafutdinov** [comment]
Hi,

Yes, I tried to add this option in def file and in build.gradle(relative and absolute path).

However, it results in compilation error in all cases. The error message didn't help to figure out what goes wrong.

**Comment by olonho** [comment]
Just curious, what is the purpose of using PCH in your case? Generally, interop itself works as a form of PCH in sense that while headers are not regenerated, cached Kotlin metadata is stored in binary format and could be used without reparsing any  text representation.

**Comment by olonho** [comment]
Yes, order is preserved.
