### ISSUE TITLE
platform.Accelerate not available for Mac OS

### ISSUE THREAD

**Issue by dtornqvist** [JetBrains/kotlin-native#1953]
When building frameworks for iOS, I am able to use the platform library Accelerate by writing:
`import platform.Accelerate.*`

However, this does not seem to work for Mac OS (target `macos_x64`). Accelerate is a native platform library for both platforms since long ago. Is this expected?

**Comment by olonho** [comment]
You could create matching .def file and submit a pull request - this will speed up getting it merged.

**Comment by olonho** [comment]
You could start with https://github.com/JetBrains/kotlin-native/blob/master/platformLibs/src/platform/ios/Accelerate.def
