### ISSUE TITLE
Modern OpenGL on Windows

### ISSUE THREAD

**Issue by G0BL1N** [JetBrains/kotlin-native#1974]
Default package platform.opengl32 doesn't contain modern OpenGL functions, it is 1.1 or something like that.
I tried to use cinterop several times, with diffrent OpenGL libraries, like galogen, glad, or even MinGW header files (which should be used by platform.opengl32) and none of them seems to work. You can see an example of headers here, for example: http://galogen.gpfault.net/galogen-web.html
Can someone help me with that?

**Comment by olonho** [comment]
Self-contained error reports with actual problems you encountered are really welcome. Just statement that some library does not work are not.

**Comment by G0BL1N** [comment]
Sorry, i should have provided more information initially. I will try to explain problems i encountered.
My def file for galogen look like this:
```
headers = galogen/gl.h
compilerOpts = -DUNICODE
linkerOpts = -lopengl32
```
Function definition in the galogen header looks like this:
```c
typedef GLuint (GL_APIENTRY *PFN_glCreateShader)(GLenum type);
extern PFN_glCreateShader _glptr_glCreateShader;
#define glCreateShader _glptr_glCreateShader
```
It is pretty much the same in other OpenGL loading libraries too.
Function with _glptr_ prefix is defined in .c like this:
```c
static GLuint GL_APIENTRY _impl_glCreateShader (GLenum type) {
    _glptr_glCreateShader = (PFN_glCreateShader)GalogenGetProcAddress("glCreateShader");
    return _glptr_glCreateShader(type);
}
PFN_glCreateShader _glptr_glCreateShader = _impl_glCreateShader;
```
If that's not enough, i provided link to the online generator where you can get whole .c and .h files.
My problem is, that last macro defined for each function in .h (`#define glCreateShader _glptr_glCreateShader`) doesn't work through interop, glCreateShader function just doesn't exist in resulting library.
_glptr_glCreateShader does exist, but i can't find a way to actually call it. It looks like this in a klib-build .kt file:
```kt
var _glptr_glCreateShader: PFN_glCreateShader?
    get() = interpretCPointer<CFunction<(GLenum) -> GLuint>>(kniBridge1020())
    set(value) { kniBridge1021(value.rawValue) }
```
And this is how error looks when i'm trying to invoke it:
![image](https://user-images.githubusercontent.com/18249498/44870573-3e4ce280-ac99-11e8-8dbd-ad7aef9d0b96.png)

**Comment by msink** [comment]
You can try to ask `galogen` author - is it possible to replace in generated code `#define glCreateShader _glptr_glCreateShader` by `static inline` functions.
Or do it youself.

**Comment by G0BL1N** [comment]
It's not only galogen, it's ant OpenGL loading library I could find.
Thank you for reply, i'll see what I can do.

**Comment by olonho** [comment]
You can try to call `_glptr_glCreateShader(...)`, why it doesn't work?

**Comment by msink** [comment]
> _glptr_glCreateShader(...), why it doesn't work?

Because it is pointer to function.

typedef GLuint (GL_APIENTRY *PFN_glCreateShader)(GLenum type);
extern PFN_glCreateShader _glptr_glCreateShader;
```
#define glCreateShader _glptr_glCreateShader
```

**Comment by olonho** [comment]
Following .def
```package = funptr
---
#include <stdio.h>

typedef int (*printer)(const char*);

static int the_printer(const char* s) {
    printf("%s\n", s);
}

printer g_printer = &the_printer;
```
and following .kt
```
import funptr.*
import kotlinx.cinterop.*

fun main(args: Array<String>): Unit = memScoped {
    g_printer!!("From Kotlin".cstr.ptr)
}```
shows how to call function pointers.

**Comment by G0BL1N** [comment]
At first glance, this seems to work:
![image](https://user-images.githubusercontent.com/18249498/44919960-698e0b00-ad47-11e8-919b-5d042a452f0b.png)
I will do a little more testing and if it works, maybe i will write down some script to get rid of those `_glptr_` prefixes. Thank you very much!

**Comment by G0BL1N** [comment]
Closed too soon, i'm afraid. 
It works only in editor, but doesn't compile:
```
C:\Users\Mikhail\AppData\Local\Temp\konan_temp4901410189825519674\combined.o:(.text+0x28783): undefined reference to `_glptr_glClear'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
error: c:\Users\Mikhail\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.2.0-clang-llvm-5.0.0-windows-x86-64/bin/clang++ invocation reported errors
```
Source:
```kt
import galogen.*
import glfw.*
import kotlinx.cinterop.invoke

fun main(args: Array<String>) {
    if(glfwInit() == GLFW_FALSE)
        return
    val window = glfwCreateWindow(800,600, "Test", null, null)
    glfwMakeContextCurrent(window)

    while (glfwWindowShouldClose(window) == 0)
    {
        /* Render here */
        _glptr_glClear!!(GL_COLOR_BUFFER_BIT)

        /* Swap front and back buffers */
        glfwSwapBuffers(window)

        /* Poll for and process events */
        glfwPollEvents()
    }
    glfwTerminate()
    return
}```
Works fine if i replace ` _glptr_glClear!!(GL_COLOR_BUFFER_BIT)` with `glClear(GL_COLOR_BUFFER_BIT)` from platform.opengl32.

**Comment by G0BL1N** [comment]
I still don't know why galogen was not working, but i managed MinGW headers to work. Will post PR some time later, as it sould be working in default platfrom.opengl32.

**Comment by msink** [comment]
> I still don't know why galogen was not working

А сгенерированный им файл gl.c компилировался и линковался? Если нет, то неудивительно.

**Comment by G0BL1N** [comment]
> А сгенерированный им файл gl.c компилировался и линковался?

Глупый конечно вопрос, но как сделать чтобы компилировался и линковался?
Я смог сделать так чтобы заголовки OpenGL'а от MinGW генерировали нужные функции, оказывается в glext.h все строки вида `GLAPI GLuint APIENTRY glCreateShader (GLenum type);` обёрнуты в `#ifdef GL_GLEXT_PROTOTYPES`. Соотвественно нужно добавить `-DGL_GLEXT_PROTOTYPES` в `compilerOpts` в .def файле.
После этого нужные функции становятся видны в CLion, но опять же, не линкуются, хотя там никаких .c нет и подавно, только статическая библиотека opengl32, который линкуется и в .def файле (`linkerOpts = -lopengl32`), и, на всякий случай, задан при линковке самой программы через Gradle (`linkerOpts("-lopengl32")` в `program` в `konanArtifacts`).

**Comment by G0BL1N** [comment]
Наконец-то заработало!
Огромное спасибо!
Остаётся только привести это к нормальному виду, без префиксов в виде _glptr_ чтобы было удобнее пользоваться.
Теперь проблему можно считать закрытой.

**Comment by msink** [comment]
Ну это вообще элементарно:

`git clone https://github.com/google/galogen.git`

``` diff
diff --git a/galogen.cpp b/galogen.cpp
index f94f017..dbbc176 100644
--- a/galogen.cpp
+++ b/galogen.cpp
@@ -825,15 +825,21 @@ public:
             command.name.c_str());
 
     // Add a macro that defines the command name to call the function pointer.
-    fprintf(output_h_, "#define %s _glptr_%s\n",
+    fprintf(output_h_, "static inline %s %s(%s) {\n  _glptr_%s(%s);\n}\n",
+            command.return_ctype.c_str(),
             command.name.c_str(),
-            command.name.c_str());
+            parameter_list_sig.c_str(),
+            command.name.c_str(),
+            parameter_list_sig.c_str());
     if (!command.alias.empty()) {
-      fprintf(output_h_,
-              "#define %s %s\n",
-              command.alias.c_str(),
-              command.name.c_str());
+      fprintf(output_h_, "static inline %s %s(%s) {\n  _glptr_%s(%s);\n}\n",
+            command.return_ctype.c_str(),
+            command.alias.c_str(),
+            parameter_list_sig.c_str(),
+            command.name.c_str(),
+            parameter_list_sig.c_str());
     }
+
     // Output loader function to .c file.
     fprintf(output_c_, // Signature.
             "static %s GL_APIENTRY _impl_%s (%s) {\n",
```

``` bat
@set PATH=c:\msys64\mingw64\bin;%PATH%
g++ galogen.cpp third_party\tinyxml2.cpp -static -o galogen.exe
galogen third_party\gl.xml --api gl --ver 4.5 --profile core
```

I hope you'll publish final result somewhere on github.

**Comment by sbogolepov** [comment]
Guys, please stick to English so others could understand you as well.

**Comment by G0BL1N** [comment]
Heres the fork of the modified Galogen: https://github.com/G0BL1N/galogen
I also included scripts to generate klib or folder with all the necessary files to be used by Kotlin Native cinterop.

**Comment by Dominaezzz** [comment]
Although this solution works, would it be better to generate a completely Kotlin loader or use cinterop around a C loader?

**Comment by msink** [comment]
Of course it is not ideal, but goal was just get something working.

In long run (IMHO) galogen should be rewritten in kotlin and integrated as kotlin compiler plugin.

**Comment by elect86** [comment]
Hi @G0BL1N,

do you think is relatively easy to generate a `.def` for using opengl and glfw on Windows?

**Comment by G0BL1N** [comment]
@elect86 Didn't saw your mention for some reason, sorry it took so long to reply.
It's pretty easy to create `.def` for glfw, it should work as-is.
Tool to create working `.klib` with OpenGL  is linked above. If you only need `.def` you can get it there too.

**Comment by dickensas** [comment]
I also faced similar issue with GLEW, the cinterop generated code most of them are pointers

val glCreateShader: PFNGLCREATESHADERPROC?
    @CCall("knifunptr_glew7693_glCreateShader_getter") external get
typealias PFNGLCREATESHADERPROCVar = CPointerVarOf<PFNGLCREATESHADERPROC>
typealias PFNGLCREATESHADERPROC = CPointer<CFunction<(GLenum) -> GLuint>>

val glShaderSource: PFNGLSHADERSOURCEPROC?
    @CCall("knifunptr_glew7719_glShaderSource_getter") external get
typealias PFNGLSHADERSOURCEPROCVar = CPointerVarOf<PFNGLSHADERSOURCEPROC>
typealias PFNGLSHADERSOURCEPROC = CPointer<CFunction<(GLuint, GLsizei, CPointer<CPointerVar<GLcharVar>>?, CPointer<GLintVar>?) -> Unit>>

These **CPointer<CFunction>** with **external get** are quite difficult to invoke
But, I successfully created a GLEW,GLFW blank window
So I am stuck with a blank window now :) without any shader

**Comment by Dominaezzz** [comment]
https://github.com/Dominaezzz/kgl should make it a bit easier to use opengl.

**Comment by G0BL1N** [comment]
I have built a modified version of the galogen back in 2018 and it was usable. Now we even have proper library! Thanks, @Dominaezzz , you actually did it.

**Comment by dickensas** [comment]
Hi @Dominaezzz , @G0BL1N thanks for the help

I checked the example https://github.com/Dominaezzz/kgl-opengl-samples 

but the code glBindVertexArray() seems to be working only if I put glBindVertexArray!!() due to null safety

but the library is nice

**Comment by Dominaezzz** [comment]
Just `glBindVertexArray` in particular? (Might be worth opening an issue.)
