### ISSUE TITLE
mingw samples/videoplayer

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1981]
There are two samples using SDL2 - tetris and videoplyer, and for mingw target they demonstrate both static and dynamic linkage.
Tetris is ok - it compiles to self contained `.exe` without nonstandard dependencies.

Videoplayer is ok too - in sense that it compiles, but actually run it is not trivial.
User have options:
- run it from mingw64 shell
- have `c:\msys64\mingw64\bin` in system PATH
- copy bunch of `.dll`s to same directory where `Player.exe` is.

For last option I use hacky way - run mingw64 shell, `cd` to directory with `Player.exe`,  and run this script:
```
#!/usr/bin/bash
for f in `ntldd -R Player.exe | grep mingw64 | sed -e 's/.*=..//' | sed -e 's/ (0.*)//'`; do
    cp -v "$f" .
done
```
It assumes that `ntldd` installed in msys2: ` pacman -S mingw-w64-x86_64-ntldd`

But there should be more automated way to do so, ideally integrated to gradle script.
I'm not familiar enough in all that magic, so cannot do it myself, sorry.
Can someone do it please?

**Comment by olonho** [comment]
Not sure how to do that with Gradle, as we cannot just automagically find deps of the library. Maybe some helper program (even written in Kotlin/Native using https://github.com/LRN/ntldd/blob/master/libntldd.h) could be used in practical cases to compute actual dependencies and make appropriate static linkage.

**Comment by msink** [comment]
Static linkage is not always possible, in particular videoplayer uses ffmpeg, and ffmpeg in msys2 distribution has only dynamic variant.

But helper program to simplify copying is good idea, I'll try to make something.

**Comment by msink** [comment]
So I prototyped helper program: https://github.com/msink/win32-dlltree
Currently it just prints dependencies from msys2-mingw directory.

And how to integrate it with Gradle?

**Comment by SvyatoslavScherbina** [comment]
Created https://youtrack.jetbrains.com/issue/KT-48086, closing this.
