### ISSUE TITLE
Invalid module with 0.9-rc1-3632

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1987]
Reproduces in this branch:
https://github.com/korlibs/korlibs/tree/invalid.module.0.9-rc1-3632

Reproduced by travis here:
https://travis-ci.org/korlibs/korlibs/jobs/423346077
though since it is dumping the whole bitcode and travis is capped to 4MB, doesn't show the last part.

I'm going to try to remove files until I find the culprit, since it seems a verify error, I have no clue why is this happening.

```
error: compilation failed: Invalid module

 * Source files: Korio.kt, KorioNative.kt, KorioVersion.kt, AsyncExt.kt, AsyncPool.kt, AsyncQueue.kt, AsyncSemaphore.kt, AsyncSignal.kt, DeferredExt.kt, EmptyContinuation.kt, KorioDefaultDispatcher.kt, Signal.kt, asyncGenerate.kt, asyncProducer.kt, deprecate.kt, parallel.kt, runBlockingNoSuspensions.kt, withOptTimeout.kt, CompressionMethod.kt, Deflate.kt, FastDeflate.kt, GZIP.kt, ZLib.kt, Lzma.kt, SevenZip.kt, BitReader.kt, Huffman.kt, SlidingWindow.kt, UncompressAsyncStream.kt, AsyncHash.kt, Base64.kt, Hex.kt, SimpleChecksum.kt, SyncHash.kt, crypto.kt, NumberRawArray.kt, SubListGeneric.kt, error.kt, PathInfo.kt, Vfs.kt, VfsFile.kt, VfsUtil.kt, IsoVfs.kt, JailVfs.kt, LocalVfs.kt, LogVfs.kt, MapLikeStorageVfs.kt, MemoryVfs.kt, MergedVfs.kt, MountableVfs.kt, NodeVfs.kt, ResourcesVfs.kt, UniversalVfs.kt, UrlVfs.kt, ZipVfs.kt, Language.kt, Bytes.kt, Charset.kt, ClassExt.kt, Closeable.kt, CloseableExt.kt, Debugger.kt, Dynamic.kt, Environment.kt, ExceptionExt.kt, Semaphore.kt, StringExt.kt, String_fromIntArray.kt, ThreadLocal.kt, Undefined.kt, assert.kt, lazyVar.kt, AsyncSocketFactory.kt, HostWithPort.kt, MimeType.kt, QueryString.kt, URI.kt, URLDecoder.kt, URLEncoder.kt, Http.kt, HttpClient.kt, HttpClientEndpoint.kt, HttpDate.kt, HttpServer.kt, HttpRestClient.kt, WebSocketClient.kt, ClassReflect.kt, ObjectMapper.kt, Json.kt, Xml.kt, XmlEntities.kt, XmlStream.kt, Yaml.kt, AsyncBufferedInputStream.kt, AsyncProduceConsumerByteBuffer.kt, AsyncStream.kt, ByteArrayBuilder.kt, FastByteArrayInputStream.kt, SyncProduceConsumerByteBuffer.kt, SyncStream.kt, AsyncCache.kt, AsyncCloseable.kt, AsyncInmemoryCache.kt, BYTES_TEMP.kt, ByteArrayExt.kt, Cached.kt, CharExt.kt, CollectionExt.kt, CompareUtil.kt, DoubleExt.kt, EnumExt.kt, Indenter.kt, LangExt.kt, NumberExt.kt, OS.kt, Once.kt, RangeExt.kt, RangesExt.kt, RedirectField.kt, RegexExt.kt, StrReader.kt, UByteArraySlice.kt, UUID.kt, UntypedObject.kt, computeRle.kt, escape.kt, expectException.kt, html.kt, KorioNativeNative.kt, KorioZlib.kt, KorioDefaultDispatcher.kt, UTF8.kt, cwd.kt
 * Compiler version info: Konan: 0.9-rc1-3632 / Kotlin: 1.3.0
 * Output kind: LIBRARY

exception: java.lang.Error: Invalid module
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.verifyModule(IrToBitcode.kt:175)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.verifyModule$default(IrToBitcode.kt:166)
        at org.jetbrains.kotlin.backend.konan.Context.verifyBitCode(Context.kt:457)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:99)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
```

**Comment by olonho** [comment]
Seems this issue comes from the fact, that `synchronized` was made to throw an exception unconditionally, and codegen wasn't ready for such cases. Guess using `synchronized` function in korlibs could be rethought.

**Comment by soywiz** [comment]
Well, actually, I initially designed my libraries to be single-threaded with an event-loop, but then started to use `kotlinx.coroutines`, and some of the libraries can be used without the event loop in different threads, and since they can be executed in the JVM separate, I will probably need `synchronized` in common code.

In JS, that has different heaps per worker, and thus, no synchronization required at all, what it is done is to just execute the `block`, ignoring the `lock`, so I can use it in common code, be safe on JVM, and still work on JS:

```kotlin
@kotlin.internal.InlineOnly
public actual inline fun <R> synchronized(@Suppress("UNUSED_PARAMETER") lock: Any, block: () -> R): R =
        throw UnsupportedOperationException("synchronized() is unsupported")
```
->

```kotlin
@kotlin.internal.InlineOnly
public actual inline fun <R> synchronized(@Suppress("UNUSED_PARAMETER") lock: Any, block: () -> R): R = block()
```

I guess that the current Kotlin/Native memory model, doesn't allow shared-unfrozen instances, so I guess that should be ok to do the same, right?

Knowing that it is the `synchronized` fault, to circumvent the problem, what I'm going to do is to create a `expect/actual fun synchronizedCommon` or something like that by just executing the block in JS and Native, and using a proper synchronize in the JVM.

But would be nice to either disallow the function at compile time, and error as soon as possible, before the LLVM bitcode is generated, or just call `block` like JS? (I would prefer calling the block if possible)

**Comment by olonho** [comment]
I believe that it better be removed, but need to agree on that with the library team.
