### ISSUE TITLE
Tetris Sample lacks WebAssembly Target

### ISSUE THREAD

**Issue by Skeltpr** [JetBrains/kotlin-native#1991]
Both Kotlin/native and SDL2 is capable of compiling and using WebAssembly. As a result, there should be a sample that demonstrates game development through wasm. After all, it's of the biggest beneficiaries and users of that technology. Currently, the Tetris sample project can target all platforms except WebAssembly. In order to help facilitate complete multi-platform game development usage of Kotlin/native, the Tetris sample should be modified to include a demonstration of such.

**Comment by olonho** [comment]
SDL only works on top of Emscripten, IIRC, while K/N aims pure WASM environment, however we accept contributions in this direction, if you can make it working.
