### ISSUE TITLE
Experimental Gradle plugin: missing entryPoint

### ISSUE THREAD

**Issue by Tapchicoma** [JetBrains/kotlin-native#1997]
By using stable `konan` plugin, I can define where compiler should look for main file that contains app entry point:
```kotlin
configure<KonanArtifactContainer> {
    program("foo") {
        entryPoint("some.package.native.main")
    }
}
```

Same functionallity in new experimental `"org.jetbrains.kotlin.native"` plugin is missing (or at least it is not described in plugin section).

**Comment by Tapchicoma** [comment]
Seems PR #1996 is addressing it.

**Comment by msink** [comment]
`extraOpts '-entry', 'some.package.native.main'` does not work?

**Comment by Tapchicoma** [comment]
Yes, such approach works:
```kotlin
extraOpts(listOf("-entry", "org.test.main"))
```

@msink thank you for the help!

As there is already opened PR to add such feature to new Gradle plugin - closing this issue.
