### ISSUE TITLE
DSL konan.targets compile error

### ISSUE THREAD

**Issue by chinacharis** [JetBrains/kotlin-native#1998]
plugins {
    id("org.jetbrains.kotlin.konan").version("0.8.2")
}

konan.targets = ["macbook", "linux"]

konanArtifacts {
    program("HelloWorld")
}

Script compilation errors:

  Line 8: konan.targets = ["macbook", "linux"]
                          ^ Type inference failed. Expected type mismatch: inferred type is Array<String> but MutableList<String> was expected

  Line 8: konan.targets = ["macbook", "linux"]
                          ^ Unsupported [Collection literals outside of annotations]

2 errors

konan.targets how to configure? Thanks

**Comment by ilmat192** [comment]
Do you use Kotlin DSL?

**Comment by chinacharis** [comment]
yes, windows clion helloworld, build.gradle.kts

**Comment by chinacharis** [comment]
see 
public open class KonanExtension public constructor() {
    public final var apiVersion: kotlin.String? /* compiled code */

    public final var jvmArgs: kotlin.collections.MutableList<kotlin.String> /* compiled code */

    public final var languageVersion: kotlin.String? /* compiled code */

    public final var targets: kotlin.collections.MutableList<kotlin.String> /* compiled code */
}

targets is MutableList

**Comment by olonho** [comment]
`konan.targets = listOf("macbook", "linux")`?

**Comment by chinacharis** [comment]
NO
Script compilation error:

  Line 5: konan.targets = listOf("macbook", "linux")
                          ^ Type inference failed. Expected type mismatch: inferred type is List<String> but MutableList<String> was expected

1 error

**Comment by chinacharis** [comment]
konan.targets = listOf("macbook", "linux").toMutableList() is OK
But no run configure
konan.targets = listOf("linux", "mingw_x64").toMutableList()
only mingw_x64 output, no linux ouput

**Comment by chinacharis** [comment]
can't cross-compiled to the target platforms?
