### ISSUE TITLE
Method Resolution issue with 0.9-dev-3572?

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#2006]
Notice that it is not the latest version, since kotlinx.coroutines is not yet updated to ~rc2.

This used to work (up to 0.8.2 at least):
<img width="1464" alt="screen shot 2018-09-04 at 19 05 36" src="https://user-images.githubusercontent.com/570848/45046175-b0e10800-b075-11e8-9eb5-cba536e92536.png">

But now it produces a recursive execution. So I guess that instead of resolving the original method, it is resolving the extension method one.

**Comment by olonho** [comment]
API of `kotlin.native.concurrent.AtomicInt` no longer have get method, there's no resolve change.
