### ISSUE TITLE
Timeline for V 1.0 release

### ISSUE THREAD

**Issue by yuriry** [JetBrains/kotlin-native#2007]
What is timeline for releasing Kotlin/Native v 1.0?  We are considering using Kotlin/Native for production Android and iOS applications but management is concerned that the project is still in v 0.* stage.  Thank you in advance.

**Comment by olonho** [comment]
1.0 will appear relatively soon, we cannot give exact ETA, but you can extrapolate from the previous release schedule https://github.com/JetBrains/kotlin-native/blob/master/CHANGELOG.md.

**Comment by StefMa** [comment]
Yeah, make sense. KotlinConf is soon 😉

**Comment by msink** [comment]
So after 0.9.x there will be 1.0, not 0.10, 0.11 etc? :tada:
