### ISSUE TITLE
Strange error when compiling a large library

### ISSUE THREAD

**Issue by AregevDev** [JetBrains/kotlin-native#2025]
Hello, I am trying to make a native implementation for the popular library `Arrow`, I have included all the necessary classes, there are no syntax errors, it looks like an internal error in the LLVM generation

Crash: https://pastebin.com/2B1gp33e
Build script:
```
plugins {
    id 'kotlin-platform-common' version '1.2.61'
    id "org.jetbrains.kotlin.konan" version "0.9"
}

group 'org.aregevdev'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-common"
    testCompile "org.jetbrains.kotlin:kotlin-test-annotations-common"
    testCompile "org.jetbrains.kotlin:kotlin-test-common"
}

konan.targets = ["linux_x64"]

konanArtifacts {
    library("libarrow") {
        enableOptimizations true
    }
}```

**Comment by olonho** [comment]
This is known problem which shall be fixed once new inference algorithm will be activate in the frontend.

**Comment by AregevDev** [comment]
Is it still relevant?

**Comment by SvyatoslavScherbina** [comment]
Closing as obsolete. Feel free to reopen if you still encounter the problem.
