### ISSUE TITLE
androidNativeActivity in samples does not build

### ISSUE THREAD

**Issue by narkis** [JetBrains/kotlin-native#2027]
I have forked this repo and have an exact local copy on Linux Ubuntu 18+ 

EDIT: ./gradlew bundle execution has the following error:
`> Task :Interop:Indexer:compileClangstubsSharedLibraryClangstubsC FAILED

....kotlin/kotlin-native_fork/Interop/Indexer/prebuilt/nativeInteropStubs/c/clangstubs.c:2:10: fatal error: 
'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.
`

error :
```
> Task :compileKonanPolyhedronAndroid_arm32 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKonanPolyhedronAndroid_arm32'.
> Classpath of the tool is empty: konanc
  Probably the 'konan.home' project property contains an incorrect path.
  Please change it to the compiler root directory and rerun the build.
```
at the root on the fork I have ran the ./gradlew dependencies:update successfully 
if I remove the arm32 platform target, it then fails in the arm64 version

Thanks in advance

**Comment by olonho** [comment]
Please read the README.md - you need to have full JDK (Java 8 or Java 9) installed.

**Comment by narkis** [comment]
this is what I currently have for java -version
`$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)
`

**Comment by narkis** [comment]
this worked with the Oracle Java version installed for compiling the dependencies.
