### ISSUE TITLE
Export KN lib classes in final OBJC framework

### ISSUE THREAD

**Issue by SBNTT** [JetBrains/kotlin-native#2030]
Hi,

I've a base library (let's call it libA) that is exported as  kotlin library with:

```gradle
library('libA') {
    enableMultiplatform true
    extraOpts '-module_name', ''
}
``` 

This library (libA) is included in a multiplatform (android/ios) project. iOS module is exported as an objective C framework with:

```gradle
apply plugin: "konan"

konan.targets = ['ios_arm64', 'ios_x64']

konanArtifacts {
    framework("platforms") {
        enableMultiplatform true

        libraries {
            artifact project(':libA:ios'), 'libA'
        }
    }
}

dependencies {
    expectedBy project(':platforms:common')
}
``` 

In the iOS app, i can only access classes in platforms framework, and not libA classes.
So, I tried to export libA as framework too and include it in the iOS xcode project.
`Only one Kotlin framework can be loaded currently`
Obviously this is not possible...

Then, i'm searching a workaround in order to export libA classes in the final platforms framework.. without success. 

is this possible?

Thanks!

**Comment by DrewCarlson** [comment]
> In the iOS app, i can only access classes in platforms framework, and not libA classes.
Check the headers file of your platform framework, you should see definitions for any libA classes that are surfaced by APIs of the platform framework. This works with the experimental gradle plugin.

The problem I'm facing (and I suspect it's the same for @SBNTT) is that both my kotlin native module and my ios(xcode) project depend on the klib's APIs.

Is there a way to tell the gradle plugin to expose all classes from klib dependencies in the framework output?  Ideally `api` can be when defining klib dependencies.

**Comment by ilmat192** [comment]
Such a support is added in both `kotlin-multiplatform` and `org.jetbrains.kotlin.platform.native` plugins. See the examples [here])(https://github.com/ilmat192/kotlin-native-gradle-samples/).

There is no plans to add this feature in the `konan` plugin since it is deprecated.
