### ISSUE TITLE
How to initialize LPBOOL? Win32 Api in Kotlin Native

### ISSUE THREAD

**Issue by PramUkesh** [JetBrains/kotlin-native#2042]
How to Initialise this in Kotlin Native

```
    val result = CopyFileExA(
                          oldFile,
                          newFile,
                          null,
                          null,
                          false,
                          COPY_FILE_FAIL_IF_EXISTS
                         )
```

while false is not accepted as LPBOOL? How to initialize LPBOOL? in kotlin Native

i was getting following error :

the boolean literal does not conform to the expected type

LPBOOL? /* = CPointer */>? */ false,

**Comment by olonho** [comment]
Sure, `LPBOOL` is pointer to C `BOOL`, see  https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#passing-pointers-to-bindings for details how to create and pass pointers.

**Comment by PramUkesh** [comment]
not able to figure how to do that help me please

**Comment by PramUkesh** [comment]
@olonho
