### ISSUE TITLE
is winbase.h included in windows platfrom

### ISSUE THREAD

**Issue by PramUkesh** [JetBrains/kotlin-native#2043]
When i try to use win32 api functions from winbase.h header are not recognised showing error unresolved reference error

**Comment by PramUkesh** [comment]
FileMgmt.kt:180:17: error: unresolved reference: DeleteFile
                val result =  DeleteFile(fileName);

**Comment by PramUkesh** [comment]
@olonho can you help me

**Comment by msink** [comment]
`DeleteFile` is macro, real function is `DeleteFileW`

**Comment by PramUkesh** [comment]
thank u @msink so macros not included in api any way thank u for the answer

**Comment by PramUkesh** [comment]
am i right winbase.h not included(means not pointed to) in kotlin packages

**Comment by msink** [comment]
DeleteFileW is in `fileapi.h`, and included.
Macroses are not included, except for constants.

**Comment by olonho** [comment]
winbase.h is included, but we essentially analyze code after preprocessor run, thus DeleteFile, being a macros is not available, where real functions DeleteFileA and DeleteFileW is available.
