### ISSUE TITLE
Access to stack trace on Throwable

### ISSUE THREAD

**Issue by kpgalligan** [JetBrains/kotlin-native#2046]
Each instance of Throwable gets its current stacktrace when created, but the only way to access that is printing. The field is private

https://github.com/JetBrains/kotlin-native/blob/master/runtime/src/main/kotlin/kotlin/Throwable.kt#L25

For logging situations, it would be great to grab that. For example

https://github.com/touchlab/timber/blob/native/native/src/main/kotlin/timber/log/NativeLogTree.kt#L16

I'm grabbling the stack trace at the time of log here, and it's likely you'll be logging after catching, but you'll lose context on causes.

**Comment by sbogolepov** [comment]
Added with https://github.com/JetBrains/kotlin-native/pull/2036 :)

**Comment by kpgalligan** [comment]
Nice!
