### ISSUE TITLE
Are there any rounding functions in api for native

### ISSUE THREAD

**Issue by PramUkesh** [JetBrains/kotlin-native#2047]
Hi are there any fun to round something like double float numbers to n decimal points in Api 
if not How to Acheive that 

My fun throws error always
```
	fun Double.round(decimals : Int) : Double {
		var multiplier = 1.0
		repeat(decimals) { multiplier *= 10 }
	    return round(this * multiplier) / multiplier
	
	}
```
following result is obtained from Native is DWORD converted toLong().toDouble
calling this 
```
         var result = 2.34861
          result.round(2)

```

**Comment by PramUkesh** [comment]
error: type mismatch: inferred type is Double but Int was expected
            return round(this * multiplier) / multiplier

**Comment by olonho** [comment]
This kind of questions has nothing to do with Kotlin/Native bug tracking.

**Comment by PramUkesh** [comment]
@olonho then how to deal with rounding functions in kotlin native these most basic ones in any language

**Comment by PramUkesh** [comment]
Ok I got It I made it my self

above fun repeat() i think it is for jvms so i used extension func to create a new fun like this

source : https://git.io/fAK5w

```
	fun Double.decimals(digits : Int) : Double {
		
			var repeats = 0
			var value = 1
			do {
				value = value * 10
				repeats++
			}
			while(repeats < digits)
			
			val finalValue = (this * value).toShort()
		
		return finalValue.toDouble()/(value).toDouble()
		
	}
```

So this can round of to required digits by user on a Double

```
Eg:

val number = 1.5684568
val result = number.toDouble().decimals(2)

results in 1.56
```

But there is a problem here if decimals to be shown provided is more than number length it gives negative number may or may not be random
