### ISSUE TITLE
No samples demonstrate how to create unit tests using the gradle plugin

### ISSUE THREAD

**Issue by ChrisAJS** [JetBrains/kotlin-native#2053]
Having downloaded KN 0.8.2 via CLion, adding a `src/test/kotlin` directory does not register as a unit test root as the [Source Management](https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md#source-management) section of the docs indicates.

It would be great if one or all the samples demonstrated how to create unit tests.

**Comment by thevery** [comment]
There are some iOS/Android tests in https://github.com/JetBrains/kotlin-mpp-example

**Comment by ChrisAJS** [comment]
@thevery thanks for the link, I'll give it a look.

Ideally there should be an example for one of simpler sample projects.

Currently, the documented behaviour is not being exhibited; having a sample to demonstrate this behaviour should allow people like me to sanity test my approach, as well as identify potential regressions.

**Comment by SvyatoslavScherbina** [comment]
New project templates in IDEA are simpler.
