### ISSUE TITLE
Segmentation fault when accessing a static from a module lexicographically lower in a static variable

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/kotlin-native#2063]
Here's a demo project that shows the crash: [NATIVE-CRASH.zip](https://github.com/JetBrains/kotlin-native/files/2380002/NATIVE-CRASH.zip)

On this project, run `./gradlew :lib:test`, and see the test executable segfault (which you can run manually with `./lib/build/test-exe/test/debug/test.kexe`).

Basically, there are 2 modules.

The `test-common` common module contains the following code:
```kotlin
data class Options(val foo: Int = 42)

val baseOptions = Options()

expect val options: Options
```

The `lib` native module contains the following code:
```kotlin
import kotlin.test.*

actual val options = baseOptions.copy()

class KodeinLevelDBNativeTest {
    @Test fun emptyTest() {}
}
```

Now, here's where it gets weird... If you **invert** the lexicographic order of those two modules (for example, by renaiming the `lib` module to `zlib`), the crash disappears!

I suppose this is due to the fact that the modules and their statics are initialized in lexicographic order...?

**Comment by olonho** [comment]
Yes, please use top level object here.
