### ISSUE TITLE
IncorrectDereferenceException while accessing to const val

### ISSUE THREAD

**Issue by subprogram** [JetBrains/kotlin-native#2083]
I have a kotlin file with a set of string constants in the common module:
```
...
const val FIELD_X = "x"
... 
```

It was working fine with 0.8.2 but when I tried to migrate to 0.9, I have a runtime exception: 
```kotlin.native.IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread```
But I can't mark all constants with these annotations because it is a common module and it won't compile for JVM project.

Isn't "const val" enough to consider a field as immutable?

**Comment by olonho** [comment]
For `val` where type is  `String` we could provide the special case in the compiler. For now you could fix by adding `@SharedImmutable` to JVM code.

**Comment by olonho** [comment]
Fixed with 45032f0b88d7cb580910faebafd79a081d921dce
