### ISSUE TITLE
@Throws (for Objective-C) support in multiplatform project

### ISSUE THREAD

**Issue by standsed** [JetBrains/kotlin-native#2122]
I have setup multiplatform project where 
- common - shared module (uses plugin kotlin-platform-common)
- ios - expectedBy common and compiles to objective-c framework (uses konan plugin)
- jvm - expectedBy common uses plugin (uses plugin kotlin-platform-jvm)

Issue is that some functions in common module can throw exception and in order to handle this later in switft I must annotate these functions with `@Throws`
https://github.com/JetBrains/kotlin-native/blob/master/OBJC_INTEROP.md#errors-and-exceptions
As I understand this annotation is supported only by kotlin native compiler and after adding it I can't compile jvm module - compilation error "Unresolved reference: Throws"

Is there a way to support such setup today?
If no, any plans on adding it soon? 
I can imagine something like `@OptionalExpectation @konan.Throws` in common standard library would be perfect here.

Currently I have ugly workaround with implementing in common module my own `@Throws` annotation to satisfy jvm compiler.
When building ios framework I'm excluding custom `@Throws` implementation file and konan sees all `@Throws` as `@konan.Throws` which produces nessary result in objective-c framework

**Comment by olonho** [comment]
This is not so easy - technically your code is not common, so adding annotation for @Throws in JVM code looks like sensible workaround. Longer term - we could discuss optional expectation in stdlib.

**Comment by r4zzz4k** [comment]
> Currently I have ugly workaround with implementing in common module my own `@Throws` annotation to satisfy jvm compiler.
> When building ios framework I'm excluding custom `@Throws` implementation file and konan sees all `@Throws` as `@konan.Throws` which produces nessary result in objective-c framework

You should be able to declare your own `expect` annotation `Throws` with proper target and retention in your common module, then make `actual typealias Throws = konan.Throws` in Native and `actual annotation class Throws` with the same target and retention in JVM. This way you won't have to hide any implementation from compilers -- Native would use it's own meaningful annotation, and JVM would just see plain annotation.

**Comment by standsed** [comment]
Thanks, `typealias` solution worked out very nicely.

**Comment by alandoni** [comment]
@r4zzz4k can you give an example on how to do that? or maybe create a small repo with this approach working? I am totally lost here

**Comment by r4zzz4k** [comment]
@alandoni, please try the following:

In your `src/commonMain/kotlin/my/package/annotations.kt`:
```kotlin
package my.package

@OptionalExpectation
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CONSTRUCTOR)
@Retention(AnnotationRetention.SOURCE)
expect annotation class Throws
```

In your `src/iosMain/kotlin/my/package/annotationsIos.kt`:
```kotlin
package my.package

actual typealias Throws = kotlin.native.Throws
```

Then just annotate your methods with `@my.package.Throws` and you should be good. The fact it's `@OptionalExpectation` means JVM / Android would compile fine without `actual` variant of it, and when compiling iOS it should replace your annotation class with K/N one, thus adding proper `NSError` support.

Didn't try that myself, so let me know if it doesn't work for you.

Just as a friendly suggestion: it's probably more productive to move further discussion to **#kotlin-native** channel in Kotlin Slack, as your questions will get more visibility there. If you aren't still there, you can join via https://slack.kotl.in.

**Comment by alandoni** [comment]
@r4zzz4k I am a little bit lost here, 
1 - the framework being generated is in Objective-C, is this expected? (it would be awesome if it was in Swift), 
2 - after this change, the method has this signature:
`- (BOOL)executeParams:(MainLoginRequestEntity *)params result:(MainLoginResponseEntity ** _Nullable)result error:(NSError * _Nullable * _Nullable)error __attribute__((swift_name("execute(params:result:)")));`
is it ok? I didn't like it :(

**Comment by r4zzz4k** [comment]
On 1: yes, Kotlin/Native interops with Obj-C with some very preliminary support for Swift-specific stuff. That's covered by the documentation quite extensively, I believe.
On 2: you wanted `NSError` support, didn't you? That's exactly what's going on.

Once again, this issue tracker is for, well, issues, not questions. Please be kind to project maintainers and move to Slack if you have any questions.

**Comment by 4ntoine** [comment]
What's standard way to do it now (not workaround describe above)?

**Comment by chriswill0w** [comment]
I have the same question: What's the standard way to do it now (not workaround described above)?

**Comment by artdfel** [comment]
AFAIK, this workaround is still relevant. Also, please see this issue on the Kotlin YT:(https://youtrack.jetbrains.com/issue/KT-34848).

**Comment by artemsivcev** [comment]
@r4zzz4k this variant work with actual suspend fun? Didn't saw any differences in generated file.

**Comment by r4zzz4k** [comment]
@artemsivcev Are you asking whether `expect suspend fun` / `actual suspend fun` actually work? They should, yes.
I'm not sure if this is related to the issue though. If you have any questions, please [join Kotlin Slack](https://slack.kotl.in). There community there is friendly and passionate, and members are actively responding to questions in **[#multiplatform](https://app.slack.com/client/T09229ZC6/C3PQML5NU)** channel as well as other ones.
