### ISSUE TITLE
Windows PE binaries contain bad metadata

### ISSUE THREAD

**Issue by mikehearn** [JetBrains/kotlin-native#2123]
Right click on an EXE generated by Kotlin Native and you'll see the program declares itself to be "POSIX WinThreads for Windows" in the details tab, version 1.

I've tried using `-Wl,--major-image-version=2` but that didn't seem to have any effect. Presumably something being statically linked in is overriding it.

**Comment by msink** [comment]
#1605

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48065, closing.
