### ISSUE TITLE
Not able to link two klib files at a time

### ISSUE THREAD

**Issue by PramUkesh** [JetBrains/kotlin-native#2124]
Hey guys I was on a kotlin project where one library is produced by me and one produced by my friend so issue is when I want to use above klibs at a same time to compile a kotlin file how to achieve this via cmd line 
```
konanc test.kt -l utils(here how to link 2nd one)
```

**Comment by olonho** [comment]
`-l lib1 -l lib2`

**Comment by PramUkesh** [comment]
Can we use 
```
-l lib1,lib2

```

**Comment by PramUkesh** [comment]
And can we use klib to build another klib if yes what is syntax

**Comment by alexander-gorshenev** [comment]
> Can we use
> 
> ```
> -l lib1,lib2
> ```

yes, you can.

**Comment by alexander-gorshenev** [comment]
> And can we use klib to build another klib if yes what is syntax

yes, you can.

**Comment by PramUkesh** [comment]
see edited issue
https://github.com/JetBrains/kotlin-native/issues/2124#issuecomment-423930669

**Comment by alexander-gorshenev** [comment]
This is a nice to have mechanism.
We will hardly be able to introduce it in 1.0 release though.
