### ISSUE TITLE
Support to build targets in parallel

### ISSUE THREAD

**Issue by e5l** [JetBrains/kotlin-native#2136]
Kotlin native `0.9.2` run targets for single task sequentially.
Single target time: 3m
Total build time: 3 * 2(release, debug) * 5(ios32, ios64, macos64, linux64, mingw)  = 30m

**Comment by thevery** [comment]
iOS is actually 3: arm32+arm64+x64 (for simulator).

**Comment by olonho** [comment]
Not sure why this issue in K/N tracker. Those targets even typically compiled on different machines, and nothing prevents any level of parallelism between those.

**Comment by e5l** [comment]
So please could you provide a minimal example of how we should build the project with ios32, ios64, iosX64 in parallel with a single build?
