### ISSUE TITLE
Update calculator sample

### ISSUE THREAD

**Issue by lukaville** [JetBrains/kotlin-native#2143]
Why do we need to add common module source directory to android app module source sets here https://github.com/JetBrains/kotlin-native/blob/master/samples/calculator/android/build.gradle#L29?

I thought that adding dependency using `expectedBy` scope (`expectedBy project(':common')`) should be enough to have access to the dependency classes. I don't see such line in jvm project gradle script.

**Comment by olonho** [comment]
This sample is a bit obsolete, and to be reworked. Take a look at https://github.com/JetBrains/kotlin-mpp-example instead.
