### ISSUE TITLE
MULTIPLATFORM.md was removed?

### ISSUE THREAD

**Issue by nlhien** [JetBrains/kotlin-native#2158]
Just curious, the MULTIPLATFORM.md	was removed, so is there any official document to reference?

**Comment by olonho** [comment]
It is obsolete, please refer to https://kotlinlang.org/docs/reference/native/multiplatform.html

**Comment by olonho** [comment]
Restored with the link.

**Comment by StefMa** [comment]
Docs down @olonho ? 🤔 
![bildschirmfoto 2018-10-02 um 09 10 55](https://user-images.githubusercontent.com/10229883/46334109-1bf50e80-c623-11e8-9a30-02b880726cf0.png)
