### ISSUE TITLE
Linking failure for c library with kotlinc-native, works with konanc

### ISSUE THREAD

**Issue by PatrickDattilio** [JetBrains/kotlin-native#2169]
Sample library: https://github.com/PatrickDattilio/KotlinNativeCLibrary

Attempting to build in CLion, from CLI using `gradlew build` or with `kotlinc-native` all results in the same error.
```
>kotlinc-native src/main/kotlin/hello.kt -library build/c_interop/add
Undefined symbols for architecture x86_64:
  "_add", referenced from:
      _add_kniBridge0 in combined.o
ld: symbol(s) not found for architecture x86_64
```
Manually creating the klib, archive, and compiling with konanc successfully builds the `.kexe`
```
cinterop -def ../c_interop/add.def -compilerOpts -I. libadd.klib
clang -c -o add.o -I . add.c
llvm-ar rcs libadd.a add.o
konanc -l nativelib.klib  ../kotlin/hello.kt  -linkerOpts libadd.a -o add.kexe
```
My `build.gradle.kts` is as follows:
```
plugins {
    id("org.jetbrains.kotlin.konan").version("0.8.2")
}
konanArtifacts {
    interop("add") {
        defFile("src/main/c_interop/add.def")
        compilerOpts("-Isrc/main/c")
    }
    program("HelloWorld") {
        libraries {
            artifact("add")
        }
    }
}
```
Is something missing? The klib seems to be generated correctly into `build/konan/libs`.

**Comment by olonho** [comment]
What's missing is line like `linkerOpts = libadd.a` to the `add.def` file.

**Comment by PatrickDattilio** [comment]
@olonho That results in a missing `libadd.a` error:
```
> Task :compileKonanHelloWorldMacos_x64
ld: file not found: libadd.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
```
Is there a `compilerOpt`, or another line in `add.def` that needs to be added to generate `libadd.a`?

**Comment by olonho** [comment]
When compiling final app, you need to pass `-L/where/my/libadd.a` as `linkerOpts`.

**Comment by PatrickDattilio** [comment]
Does the gradle build handle generating the `libadd.a` for me? Do I need a `static` artifact  to force a `.a` compilation so I can then point to the archive in my `linkerOpts`?

**Comment by olonho** [comment]
Gradle/Native can do that for you, IIRC (https://guides.gradle.org/building-cpp-libraries/). But it depends on the origin of the static library, if it's compiled from C sources - that it's likely way to go.
