### ISSUE TITLE
Cannot compile project with Xcode 10

### ISSUE THREAD

**Issue by vicmns** [JetBrains/kotlin-native#2173]
I'm trying to compile my project in a machine that has Xcode 10 installed, but I'm getting the following error:
```
Task :ios:compileDebugIos_x64KotlinNative FAILED
ld: targeted OS version does not support use of thread local variables in _kfun:com.xxx.common.parser.DataJSONParsing.parseTestExample(kotlin.String?)com.xxxx.common.parser.vo.chartdata.TableData for architecture x86_64
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
```

This doesn't happen with Xcode 9 although...

Any fix or workaround for this issue? (that doesn't require downgrading Xcode versions...)

**Comment by vicmns** [comment]
On which repository can I find V0.9.3?

**Comment by StefMa** [comment]
Well, you can find it at the release side:
https://github.com/JetBrains/kotlin-native/releases/tag/v0.9.3

Beside of there the current master is also 0.9.3...more or less 😉

**Comment by vicmns** [comment]
Mmmm so 9.3 is not on Maven the only version is `0.9.3-dev-000/` and from there it jumps to `1.3.0-rc-*`. Right now I'm trying to use the 1.3 version (since I'm using Kotlin serialization also). But I'm getting a different gradle error now: `Could not resolve: org.jetbrains.kotlin:kotlin-stdlib-common:1.3.0-rc-131`.

**Comment by vicmns** [comment]
Ok now I cannot find another dependency...
```
Could not resolve all files for configuration ':ios:klibsDebugIos_arm64'.
> Could not find org.jetbrains.kotlinx:jsonparser-native:0.8.2-rc13.
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.module
      https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.pom
      https://jcenter.bintray.com/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.module
      https://jcenter.bintray.com/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.pom
      https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.module
      https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.pom
      https://dl.bintray.com/kotlin/kotlin-eap/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.module
      https://dl.bintray.com/kotlin/kotlin-eap/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.pom
      https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.module
      https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/jsonparser-native/0.8.2-rc13/jsonparser-native-0.8.2-rc13.pom
```

**Comment by vicmns** [comment]
Finally I'm able to get all dependencies correctly, [this repo](https://github.com/sandwwraith/KotlinSerializationPlayground/tree/native_preview) help me through the process.

In the end I used version `1.3.0-rc-131`

**Comment by yuriry** [comment]
@vicmns Did you use ```ext.kotlin_native_version = '1.3.0-rc-131'``` or ```ext.kotlin_version = '1.3.0-rc-146'```?  Doesn't ```ext.kotlin_native_version = '0.9.3'``` exist?  I'm having [a similar issue](https://github.com/JetBrains/kotlin-native/issues/2176) which I don't know how to resolve.  Thank you in advance!

**Comment by vicmns** [comment]
I ended using the following versions:
```
kotlin_version = 1.3.0-rc-131
konan_version = 1.3.0-rc-131
serialization_plugin_version = 1.3.0-rc-131
serialization_version = 0.8.2-rc13
```
You can find examples of the configurations in [this](https://github.com/sandwwraith/KotlinSerializationPlayground/tree/native_preview) and [this](https://github.com/vicmns/kotlin-jsonparser-multiplatform) projects.

And looking at the Maven repositories, indeed versions `0.9.3` isn't there. But from what I read versions `1.3.0-rc-131` is basically a wrapper of version `0.9.3`. You can find more of this [here](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md)

**Comment by yuriry** [comment]
@vicmns thank you for the information!  1.3.0-rc-131 also worked for me, and so 1.3.0-rc-146.  Unfortunately I'm having [a separate issue](https://github.com/Kotlin/kotlinx.serialization/issues/231) with both versions and serialization 0.8.2-rc13 on iOS

**Comment by budioktaviyan** [comment]
@vicmns thanks for addressing this issue, previously I followed [https://github.com/pink-room/kotlin-multiplatform-template](this repo). Unfortunately, when upgrading xcode and mac to newer version. It doesn't work anymore. Just asking, could we try to use the non-rc or dev library when building a multiplatform project ?
