### ISSUE TITLE
 simple installation instruction 

### ISSUE THREAD

**Issue by pannous** [JetBrains/kotlin-native#2175]
The main Readme page should include a *simple installation instruction* additionally to or instead of building from scratch instructions.

**Comment by pannous** [comment]
a link to https://github.com/JetBrains/kotlin-native/releases/latest would be a start

**Comment by olonho** [comment]
We recommend start with tutorials describing how to use Native, not from github repo. See https://kotlinlang.org/docs/reference/native-overview.html

**Comment by pannous** [comment]
well you might want to link to that *from the github repo*

**Comment by pannous** [comment]
Also the link links back *here* : https://kotlinlang.org/docs/tutorials/native/basic-kotlin-native-app.html#obtaining-the-compiler

**Comment by pannous** [comment]
why not add this to the main Readme:
`sudo snap install kotlin-native`

and or the above links
