### ISSUE TITLE
Shared library without runtime

### ISSUE THREAD

**Issue by IgorKey** [JetBrains/kotlin-native#2183]
Hi there. 
I've just tried to create 2 shared libraries and use them in one process. So I got a lot of exceptions like this: 

> objc[6317]: Class KotlinBase is implemented in both pathToLib/bin/macos_x64/libdrillagent.dylib (0x10d2df9a8) and anotherPathToLib/bin/macos_x64/libdrillagent.dylib (0x115885708). One of the two will be used. Which one is undefined.

Any change to escape this??? Can I create the second shared library **without** kotlin/n runtime?

**Comment by olonho** [comment]
So you use `-produce shared` option? Runtime must be linked into the library, and objects between two are not compatible.

**Comment by IgorKey** [comment]
Yes, I use -produce **dynamic**. So I created 2 shared libraries... Finally I got this exception

> 2018-10-09 23:12:14.977 java[10611:294564] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Only one Kotlin framework can be loaded currently'

**Comment by IgorKey** [comment]
> So you use `-produce shared` option? Runtime must be linked into the library, and objects between two are not compatible.

**Comment by olonho** [comment]
This is macOS limitation, as frameworks are dynamic libraries as well, and we can only support one framework at the moment, and check that at the runtime. For case of C interop this limitation may be lifted.

**Comment by IgorKey** [comment]
Oh... Do we have any workarounds for this? So, I found the beautiful purposes for using K/N in my tool. I produce JVMTI agent. It works perfectly without any c/c++ code... But my final goal is to create a plugin oriented arch. where each plugin consist a shared library and this library can attach to live JVM. JVM can attaches a lot of agents..
