### ISSUE TITLE
Correct project structure to get full IDE support and autocompletion?

### ISSUE THREAD

**Issue by ebraminio** [JetBrains/kotlin-native#2188]
Hey guys, I was playing with kotlin-native and [here is my highly minimal attempt](https://github.com/ebraminio/harfbuzz-kotlinnative), the project is working fine but I am not getting any IDE support. Can you have a look at the project and point to a correct and polished [not in-repo] how-to use Kotlin-Native with interop? Thank you

**Comment by thevery** [comment]
Take a look at https://github.com/h0tk3y/k-new-mpp-samples

**Comment by ebraminio** [comment]
Thanks.

I mean also something lightweight and easy to start. And that project is not using kotlin-dsl, for example "cinterop" doesn't exist on Kotlin DSL and I should use "interop" like [this](https://github.com/ebraminio/harfbuzz-kotlinnative/blob/master/build.gradle.kts#L6) but apparently that won't add IDE support. Something minimal and easy to use would be nice I believe.

**Comment by ebraminio** [comment]
Or in another way, can you clone https://github.com/ebraminio/harfbuzz-kotlinnative and see why IDE support is not smooth? The project is running fine so I think IDE should support it as is.

**Comment by olonho** [comment]
You can use new project Wizard to create correct project structure.

**Comment by ebraminio** [comment]
You are right. I wish it had more stuff in it like how to use interop and this is actually is based on it. Am closing this as I should be more specific on what I need. Feel free to have a look at that project, again the issue is not running it but IDE support which I believe is unexpected.
