### ISSUE TITLE
gradle plugins and IDE integration

### ISSUE THREAD

**Issue by IgorKey** [JetBrains/kotlin-native#2192]
So. I have a lot of questions related gradle plugins with IDE integration. 
Let's start with simple one :)
Several days before the main gradle plugin was **org.jetbrains.kotlin.konan** and descriptive on this page [GRADLE_PLUGIN](https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md). Konan works well with clion (mark sourcesets etc.) as describe in this article [IDE support](https://blog.jetbrains.com/kotlin/2018/08/kotlin-native-0-8-2/)

Nowadays, this page describes **org.jetbrains.kotlin.platform.native**. It looks brilliant and more easier to create a K/N application, but we do not have any IDE support for this... Are you going to fix this or who contribute to this plugin? Konan plugin is deprecated now?

**Comment by IgorKey** [comment]
CLion plugin is not open source... why? :( I want to contribute for it

**Comment by StefMa** [comment]
Both plugins, konan and platform.native, are available here:
https://github.com/JetBrains/kotlin-native/tree/196ca34d5b513894c2cf5ba65f0b3a3f4c009fc8/tools/kotlin-native-gradle-plugin

I don't know if the konan plugin is marked as deprecated. But in the long
run the new platform.native plugin should be used...

**Comment by IgorKey** [comment]
> CLion plugin is not open source... why? :( I want to contribute for it

Any comments about clion plugin?

**Comment by olonho** [comment]
Because it's part of commercial product.
