### ISSUE TITLE
Allow to export WASM as a library

### ISSUE THREAD

**Issue by ligi** [JetBrains/kotlin-native#2196]
When talking to you at the KotlinKonf 2018 office hours about https://github.com/walleth/KWRC20/issues/1 you suggested I open this issue. 
We need to get rid of all the JS/Trampoline for WASM stuff and your suggestion was to open an issue that there could be a way to compile to WASM as a library because this will get rid of all the JS/Trampoline overhead which we do not need.

**Comment by ligi** [comment]
cc @gballet

**Comment by SvyatoslavScherbina** [comment]
Kotlin team is working on a dedicated Kotlin to WebAssembly compiler backend.
So all works on wasm support in Kotlin/Native (through LLVM) were suspended.
More details: https://discuss.kotlinlang.org/t/state-of-webassembly-in-kotlin/18348
