### ISSUE TITLE
Make it possible to deactivate garbage collection when compiling to WASM

### ISSUE THREAD

**Issue by gballet** [JetBrains/kotlin-native#2197]
As Kotlin native targets environments where a GC is not acceptable (e.g. embedded), we would like to have the ability to disable the GC when using a WASM target. We believe there are such use cases, and we can name two:

  * Time-critical embedded applications running on the WASM VM but wanting to dispense with the impredictable aspects of GCs.
  * [Blockchain smart contracts](www.ethereum.org) using static memory and where extra cruft costs a lot of money.

CC: @ligi

**Comment by olonho** [comment]
Originally collector was designed to run without GC, see https://github.com/JetBrains/kotlin-native/blob/20d3e12e7cdc60af02d7e7c4620f4b577b1141c8/runtime/src/main/cpp/Memory.cpp#L34

**Comment by gballet** [comment]
@olonho interesting; @ligi let's try to recompile kotlin-native with

```C
#define USE_GC 0
```

and estimate the amount of work that it would be to just make it a switch.

**Comment by olonho** [comment]
With 70a019b4afc21f70e74d27a6b838323c1acb7bfc runtime shall compile without GC.

**Comment by olonho** [comment]
Please reopen, if smth else is needed.
