### ISSUE TITLE
Classes & Exceptions from klibrary missing in result Framework header

### ISSUE THREAD

**Issue by Alex009** [JetBrains/kotlin-native#2201]
on sample:
2 kotlin modules - ios framework (mpp-library) & klibrary (scl:utils). mpp-library depend to scl:utils.
in scl:utils we have method what throws CustomException.
```
fun functionWithCustomException() {
    throw CustomException()
}

class CustomException : Exception("this is custom exception")
```
in mpp-library we call this method and in catch block return any exception in lambda
```
fun testException(error: (Throwable) -> Unit) {
        try {
            functionWithCustomException()
        } catch (exc: Throwable) {
            error(exc)
        }
    }
```
then in swift we try check type of exception:
```
tester.testException() { error in
      if(error is MPUCustomException) {
        print("custom exception!")
      }
      print(error)
      return KotlinUnit()
    }
```
but MPUCustomException not generated in header file. but if we add explicit declaration in mpp-library - it generate:
```
val exc = CustomException()
```

demo project: https://github.com/Alex009/kotlin-native-missing-classes
just comment 2 lines in common code and then klibrary classes was removed from header - https://github.com/Alex009/kotlin-native-missing-classes/blob/e97f1316e4968b7988dab36c4474b6fe05130f80/mpp-library/common/src/main/kotlin/Test.kt#L20

**Comment by Alex009** [comment]
this issue https://github.com/JetBrains/kotlin-native/issues/2030 seems same case

**Comment by ilmat192** [comment]
Support for symbol exporting is added in Gradle plugins. See examples [here](https://github.com/ilmat192/kotlin-native-gradle-samples).

**Comment by jonl-percsolutions-com** [comment]
What would be the syntax for this in normal gradle DSL using presets for iOS?

**Comment by ilmat192** [comment]
It is similar to the Kotlin DSL:
```
kotlin {
    sourceSets.macosMain {
        dependencies {
            api project(":exported")
        }
    }

    targets {
        macosX64('macos') {
            binaries {
                framework('foo') {
                    export project(":exported")
                }
            }
        }
    }
}
```
Actually the `macosX64('macos')` function used in the example above is just a shortcut for this long `fromPreset(presets.macosX64, 'macos')` construction and available in the Groovy DSL too.

**Comment by jonl-percsolutions-com** [comment]
for ios there from preset looks like so:

**Comment by jonl-percsolutions-com** [comment]
from iOS the preset looks like so:

```
        final def iOSTarget = System.getenv('SDK_NAME')?.startsWith("iphoneos") \
                          ? presets.iosArm64 : presets.iosX64
        fromPreset(iOSTarget, 'iOS') {
            compilations.main.outputKinds('FRAMEWORK')
        }
```

so I can not figure out how to properly add the export to it.  I can do: 

```
        fromPreset(iOSTarget, 'iOS') {
            binaries {
                framework('main') {
                    export project(':exported')
                }
            }
        }

```

but this causes an error down the line 

> Cannot find a link task for the binary kind 'FRAMEWORK' and the build type 'DEBUG'
