### ISSUE TITLE
Build fails on Windows 10 when trying to run `dist` target

### ISSUE THREAD

**Issue by codeprogression** [JetBrains/kotlin-native#2247]
I have been unable to build the project on a windows 10 machine (builds fine on MacOS).

- Pulled down a fresh clone.
- Ensured no `~\.konan`, `.gradle` and `build` folders.
- Ran `gradlew --no-build-cache --info dependencies:update` (Completed successfully)
- Ran `gradlew --no-build-cache --info dist` (Failed while attempting to run `:runtime:mingw_x64Launcher` , expand error output below)

<details><summary>Error Output from `master`</summary><p>
<pre>
> Task :runtime:mingw_x64Launcher FAILED
Task ':runtime:mingw_x64Launcher' is not up-to-date because:
  No history is available.
Starting process 'command 'C:\Users\user\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1/bin/clang++''. Working directory: F:\github\kotlin\kotlin-native-windows\runtime\build\mingw_x64\launcher Command: C:\Users\user\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1/bin/clang++ -std=c++11 -O2 -IF:\github\kotlin\kotlin-native-windows\common\src\hash\headers -IF:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp -IF:\github\kotlin\kotlin-native-windows\runtime\src\launcher\headers -c
-emit-llvm F:\github\kotlin\kotlin-native-windows\runtime\src\launcher\cpp\androidLauncher.cpp F:\github\kotlin\kotlin-native-windows\runtime\src\launcher\cpp\launcher.cpp -BC:\Users\user\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1/bin -fno-stack-protector -target x86_64-w64-mingw32 --sysroot=C:\Users\user\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1 -Xclang -flto-visibility-public-std -DUSE_GCC_UNWIND=1 -DUSE_PE_COFF_SYMBOLS=1 -DKONAN_WINDOWS=1 -DKONAN_NO_MEMMEM=1 -DKONAN_HAS_CXX11_EXCEPTION_FUNCTIONS=1
Successfully started process 'command 'C:\Users\user\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1/bin/clang++''
In file included from F:\github\kotlin\kotlin-native-windows\runtime\src\launcher\cpp\androidLauncher.cpp:18:In file included from F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp\Natives.h:20:
In file included from F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:33:
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Alloc.h:29:10: error: use of undeclared identifier 'konan'
  return konan::calloc(1, size);
         ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Alloc.h:33:3: error: use of undeclared identifier 'konan'
  konan::free(memory);
  ^
2 errors generated.
In file included from F:\github\kotlin\kotlin-native-windows\runtime\src\launcher\cpp\launcher.cpp:18:
In file included from F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp\Natives.h:20:
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:61:27: error: use of undeclared identifier 'KonanAllocator'
                          KonanAllocator<char>> KStdString;
                          ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:61:46: error: expected '(' for function-style cast or type construction
                          KonanAllocator<char>> KStdString;
                                         ~~~~^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:63:37: error: use of undeclared identifier 'KonanAllocator'
using KStdDeque = std::deque<Value, KonanAllocator<Value>>;
                                    ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:63:52: error: 'Value' does not refer to a value
using KStdDeque = std::deque<Value, KonanAllocator<Value>>;
                                                   ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:62:16: note: declared here
template<class Value>
               ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:67:3: error: use of undeclared identifier 'KonanAllocator'
  KonanAllocator<std::pair<const Key, Value>>>;
  ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:67:45: error: expected '(' for function-style cast or type construction
  KonanAllocator<std::pair<const Key, Value>>>;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:67:47: error: expected ';' after alias declaration
  KonanAllocator<std::pair<const Key, Value>>>;
                                              ^
                                              ;
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:71:3: error: use of undeclared identifier 'KonanAllocator'
  KonanAllocator<Value>>;
  ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:71:18: error: 'Value' does not refer to a value
  KonanAllocator<Value>>;
                 ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:68:16: note: declared here
template<class Value>
               ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:73:39: error: use of undeclared identifier 'KonanAllocator'
using KStdVector = std::vector<Value, KonanAllocator<Value>>;
                                      ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:73:54: error: 'Value' does not refer to a value
using KStdVector = std::vector<Value, KonanAllocator<Value>>;
                                                     ^
F:\github\kotlin\kotlin-native-windows\runtime\src\main\cpp/Types.h:72:16: note: declared here
template<class Value>
               ^
F:\github\kotlin\kotlin-native-windows\runtime\src\launcher\cpp\launcher.cpp:53:3: error: use of undeclared identifier 'Kotlin_initRuntimeIfNeeded'
  Kotlin_initRuntimeIfNeeded();
  ^
F:\github\kotlin\kotlin-native-windows\runtime\src\launcher\cpp\launcher.cpp:57:21: error: use of undeclared
identifier 'Kotlin_deinitRuntimeIfNeeded'
  if (memoryDeInit) Kotlin_deinitRuntimeIfNeeded();
                    ^
13 errors generated.
:runtime:mingw_x64Launcher (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 2.526 secs.

> Task :llvmDebugInfoC:compileDebugInfoStaticLibraryDebugInfoCpp
Finished compileDebugInfoStaticLibraryDebugInfoCpp, see full log file:///F:/github/kotlin/kotlin-native-windows/llvmDebugInfoC/build/tmp/compileDebugInfoStaticLibraryDebugInfoCpp/output.txt.
:llvmDebugInfoC:compileDebugInfoStaticLibraryDebugInfoCpp (Thread[Task worker for ':',5,main]) completed. Took 23.916 secs.

> Task :libclangext:compileClangextStaticLibraryClangextCpp
Finished compileClangextStaticLibraryClangextCpp, see full log file:///F:/github/kotlin/kotlin-native-windows/libclangext/build/tmp/compileClangextStaticLibraryClangextCpp/output.txt.
:libclangext:compileClangextStaticLibraryClangextCpp (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 37.336 secs.

> Task :Interop:Runtime:linkCallbacksSharedLibrary
Finished linkCallbacksSharedLibrary, see full log file:///F:/github/kotlin/kotlin-native-windows/Interop/Runtime/build/tmp/linkCallbacksSharedLibrary/output.txt.
:Interop:Runtime:linkCallbacksSharedLibrary (Thread[Daemon worker Thread 3,5,main]) completed. Took 25.64 secs.

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':runtime:mingw_x64Launcher'.
> Process 'command 'C:\Users\user\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1/bin/clang++'' finished with non-zero exit value 1
</pre>
</p></details>


Tried on `master` (1e3dc5d52) and on tag `v0.9.3`. Please advise.

**Comment by olonho** [comment]
Interesting, this build is regularly happens on build bots, and we never saw anything similar. Ccould you try to build on drive C:, not F:?

**Comment by olonho** [comment]
Also is it possible that you have another file called `Porting.h` somewhere in your headers on machine, as this seems to be the file containing declarations not found by the compiler?

**Comment by codeprogression** [comment]
Building with the repo on `C:` worked. Thanks.

**Comment by olonho** [comment]
Guess we could close it for now. Reopen if more info will appear.
