### ISSUE TITLE
Resource sharing 

### ISSUE THREAD

**Issue by armcha** [JetBrains/kotlin-native#2248]
I think it will be great to add support to share resources between platforms, for example, strings, colours, images and so on․

**Comment by petrukhnov** [comment]
You could copy resources to framework by executing copy command from gradle:
cp -r "$PROJECT_DIR/src/main/resources" "$PROJECT_DIR/build/framework."

**Comment by armcha** [comment]
@olonho, For example, it can generate Static variables from string resources.
    <string name="my_string">MyString</string>
In code it will be something like this
``` Strings.my_string``` 
or
```S.my_string```

**Comment by armcha** [comment]
@petrukhnov The problem not only to copy but also an ability to use it for other platforms

**Comment by olonho** [comment]
See https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native/immutable-blob-of.html

**Comment by nadafsak** [comment]
This is what I do at the moment in my build.gradle to copy over resources for iOS:

```gradle
            exec {
                commandLine "cp"
                args = ["-r", "$projectDir/src/commonMain/resources", "$buildDir/bin/ios/debugFramework/test_shared_library.framework"]
            }
```

**Comment by Alex009** [comment]
for mobile platforms you can use https://github.com/icerockdev/moko-resources too

**Comment by nadafsak** [comment]
> for mobile platforms you can use https://github.com/icerockdev/moko-resources too

This is ok for specific assets (images, font, translation), but does not let you share generic file types.

**Comment by Alex009** [comment]
yes, for now it is, but support of generic files will be added soon

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-39194
