### ISSUE TITLE
Kotlin-native for Zephyr OS

### ISSUE THREAD

**Issue by nesteg** [JetBrains/kotlin-native#2268]
There is a desire to use the Kotlin-native  for programming the device of a managed Zephyr OS (not ARM,
port Zephyr OS exists). Could you describe the scheme or instruction how to do this using source kotlin-native.

**Comment by alexander-gorshenev** [comment]
What device are we talking about?
Kotlin/Native relies on LLVM to produce binaries for particular hardware architectures. 
So you need to make sure your 'not ARM' device is supported by LLVM.

**Comment by nesteg** [comment]
Oops!.ESP32, but as I found llvm out does not contain backend for  the Xtensa architecture used by the ESP32. It's a pity.Only С/C++.
