### ISSUE TITLE
Clarity on DetachedObjectGraph

### ISSUE THREAD

**Issue by kylejbrock** [JetBrains/kotlin-native#2272]
Hello,

My present understanding of DetachedObjectGraph is that it is capable of moving a reference to an object from one thread to another.

```
    private val elements = DetachedObjectGraph {
        val elements = mutableListOf<T>()
        elements.ensureNeverFrozen()
        elements
    }.asCPointer()
...

  val elements = DetachedObjectGraph<MutableList<T>>(elements).attach()
  elements.add(...)
```

There are at least a couple of things about this that aren't immediately clear to me.

1. What prevents multiple threads from attaching this object to their thread context.  Is it up to me to utilize some sort of locking mechanism to prevent such a thing?  I assume, yes.  Maybe some sort of locking mechanism like this (which seems, wrong):

```
internal class LockHandle {

    private val arena = Arena()
    val lock: pthread_mutex_t

    init {
        ensureNeverFrozen()
        lock = arena.alloc()
        if (pthread_mutex_init(lock.ptr, null) != 0) {
            throw RedException("Failed to initialize mutex")
        }
    }

    fun dispose() {
        pthread_mutex_destroy(lock.ptr)
        arena.clear()
    }

}

actual class Lock actual constructor() {

    private val _handle = DetachedObjectGraph { LockHandle() }.asCPointer()
    private val _disposed = AtomicReference(false)
    private val _locked = AtomicReference(false)

    init {
        freeze()
    }

    actual val disposed: Boolean
        get() = _disposed.value

    private val attachedHandle: LockHandle
        get() = DetachedObjectGraph<LockHandle>(_handle).attach()

    actual fun lock() {
        if (disposed)
            throw IllegalStateException("Already disposed")
        pthread_mutex_lock(attachedHandle.lock.ptr)
        _locked.set(true)
    }

    actual fun unlock() {
        if (disposed)
            throw IllegalStateException("Already disposed")
        _locked.set(false)
        pthread_mutex_unlock(attachedHandle.lock.ptr)
    }

    actual fun dispose() {
        val alreadyDisposed = _disposed.compareAndSet(false, true)
        if (!alreadyDisposed) {
            val handle = attachedHandle
            if (_locked.value)
                pthread_mutex_unlock(handle.lock.ptr)
            handle.dispose()
        }
    }

}

fun <T> Lock.sync(block: () -> T): T {
    if (disposed)
        throw IllegalStateException("Lock is disposed")
    return try {
        lock()
        block()
    } finally {
        unlock()
    }
}

fun <T> Lock.syncAndDispose(block: () -> T): T {
    if (disposed)
        throw IllegalStateException("Lock is disposed")
    return try {
        lock()
        block()
    } finally {
        dispose()
    }
}
```

To back protecting the shared state of something like this:

```
actual class ThreadSafeList<T> actual constructor() : Iterable<T> {

    private val elements = DetachedObjectGraph {
        val elements = mutableListOf<T>()
        elements.ensureNeverFrozen()
        elements
    }.asCPointer()
    private val mutex = Lock()

    private val attachedElements: MutableList<T>
        get() = DetachedObjectGraph<MutableList<T>>(elements).attach()

    actual fun add(element: T) = mutex.sync {
        val items = attachedElements
        items.add(element)
    }

    actual fun get(index: Int): T? = mutex.sync {
        val items = attachedElements
        items[index]
    }

    actual fun remove(element: T) = mutex.sync {
        val items = attachedElements
        items.remove(element)
    }

    actual fun removeAt(index: Int) = mutex.sync {
        val items = attachedElements
        items.removeAt(index)
    }

    actual fun indexOf(element: T): Int = mutex.sync {
        val items = attachedElements
        items.indexOf(element)
    }

    actual fun dispose() = mutex.syncAndDispose {
        attachedElements.clear()
    }

    override fun iterator(): Iterator<T> = mutex.sync {
        attachedElements.map { it }.iterator()
    }

}
```

2.  If I have an object that I want to create in one thread, and then move to another.  How do I detach it once it's attached?

```
fun someMethod(): ... {
  val obj = SomeObject()
  val detached = DetachedObjectGraph { obj }.asCPointer()
  return detached
}

```

This throws an exception.  And, if this really is an illegal thing to do.  Is there a legal way to detach something without knowing up front that you're going to need it detached?

The same sort of confusion exists with Workers and executing a set of work with data based on information from another thread.

I should note, I realize I can always freeze an object and transfer it safely.  But, I don't always want the object frozen.

Any clarity you could provide would be helpful.  Thanks.

**Comment by kylejbrock** [comment]
@olonho Thanks, but there's still some blanks for me on what the best way to do things is.

Here is a more in-depth example:

https://github.com/kylejbrock/kotlin-mpp-example

Some issues I face are noted in this file:

https://github.com/kylejbrock/kotlin-mpp-example/blob/master/src/linuxMain/kotlin/example/platform/threads/TaskPool.kt

I can generate a core dump.  Or I can generate a kotlin.IllegalStateException: Illegal transfer state.

But, I don't know how I would accomplish what I want to accomplish in Kotlin/Native.

I recognize that DetachedObjectGraph can only be used once in either direction.  However, I thought the CPointer was usable multiple times.  Is this not the case?

Thanks!!

I should note, I'm not attesting to the correctness of the LRU Cache.  It's really only there to help explain what I want to do.  There are a few other concepts in this example, but I haven't gotten around to expanding on those yet.  Once I understand this hurdle, I'll move on to the rest.

**Comment by olonho** [comment]
Yes, `CPointer` being an unsafe mechanism intended for C interop can be used to crash an application. If what you're trying to achieve is executing some operation on worker pool you unlikely need `CPointer`. Following sample may give you some insight on how it could be implemented

``
import kotlin.native.concurrent.Future
import kotlin.native.concurrent.TransferMode
import kotlin.native.concurrent.Worker

class TaskPool constructor(workerCount: Int) {
    var index = 0u
    val workers = Array(workerCount) { Worker.start() }

    inline fun <reified T, R> execute(crossinline producerConsumer: () -> Pair<T, (T) -> R>): Future<R> {
        return workers[(index++ % 4u).toInt()].execute(TransferMode.SAFE, {
            val pair = producerConsumer()
            Pair(pair.first, pair.second)
        }) { it ->
            it.second(it.first)
        }
    }
    
    fun shutdownAndWait() {
        workers.forEach {
            it.requestTermination(true).result
        }
    }
}


data class Data(var x: Int, var s: String)

fun usePool() {
    val pool = TaskPool(4)
    val f1 = pool.execute {
        Data(42, "hello") to { it: Data ->
            it.x++
            it
        }
    }
    val f2 = pool.execute {
        Data(99, "bye") to {
                it: Data ->
            it.s += " bye"
            it
        }
    }

    println("f1=${f1.result} f2=${f2.result}")
    
    pool.shutdownAndWait()
}

fun main() {
    usePool()
}``
Note, that in this model data produced by producer for `execute` must be shareable (i.e. either frozen or privately owned). One viable approach to achieve that is either add a boxing class, whicha guarantee single owner, or use producer lambda as in sample above.

**Comment by kylejbrock** [comment]
Ok, thanks for the information.  I think I finally understand the scope of DetachedObjectGraph.

I've updated my example to make it "work".  There's some things about it that are "dangerous".  But, I'm not aware of a better way to accomplish what I want.

The piece that was hanging me up was that the pointer itself is a single use pointer.  It seemed to me that DetachedObjectGraph itself was the only part that was single use.
