### ISSUE TITLE
C-Interop

### ISSUE THREAD

**Issue by kylejbrock** [JetBrains/kotlin-native#2273]
Hello,

I'm trying to create some integration between Kotlin & Python.  However, it's not immediately clear how I would interact with a Kotlin List in C.

```
lib..._kref_kotlin_collections_List (*...)(lib..._kref_... thiz);
```
The above example returns a List, but there's no header definition associated with the List operations (including allocating one).  Is it not possible to interact with generic based data structures?

Also, if one has multiple kotlin dynamic modules that they are trying to integrate into a single Python module.  Is it safe to pass a pointer allocated from one module to the other module?

Thanks

**Comment by olonho** [comment]
Have you seen https://github.com/JetBrains/kotlin-native/tree/master/samples/python_extension?
Currently, you need explicitly write in Kotlin all operations you want to see exported, i.e. add 
`fun List.getElement(index: Int): ElementType`, for example.

**Comment by kylejbrock** [comment]
Yea, I've looked at that sample.  It was helpful.

I'll try and add the extension methods.

Thanks!
