### ISSUE TITLE
Generate documentation for ObjC interfaces

### ISSUE THREAD

**Issue by DevTchernov** [JetBrains/kotlin-native#2281]
Is there way to put some helpful comments above generated interfaces, like in J2Objc? (https://github.com/google/j2objc/blob/master/translator/src/main/resources/com/google/devtools/j2objc/J2ObjC.properties)
For example, the following sample must be enough to navigate from iOS project to Kotlin classes:
```
/*!
 @brief Class header generated by the Kotlin/Native. Project - $(kotlin_project_name), task - $(gradle_task_name)
 @see $(full_path_to_kotlin_file)
 */
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("SettingsRepository")))
@interface MPLSettingsRepository : KotlinBase
...
@end;
```

**Comment by SvyatoslavScherbina** [comment]
> must be enough to navigate from iOS project to Kotlin classes

Could you clarify?
Do you suppose opening `$(full_path_to_kotlin_file)` file manually? Or do you mean that Xcode supports such a snippet and shows a clickable link to user?

**Comment by SvyatoslavScherbina** [comment]
Got no response, closing.
