### ISSUE TITLE
runtime assert: Recursive GC is disallowed

### ISSUE THREAD

**Issue by brettwillis** [JetBrains/kotlin-native#2291]
Running Kotlin 1.3.0 on iOS, I sometimes get this error at this line of Kotlin code:

    actual fun logDebug(tag: String, message: String) {
        NSLog("DEBUG: $tag: $message") // <-- SIGABRT here
    }

Error message:

    /opt/teamcity-agent/work/4d622a065c544371/runtime/src/main/cpp/Memory.cpp:1372: runtime assert: Recursive GC is disallowed

Stacktrace:

<img width="274" alt="screen shot 2018-11-01 at 8 41 34 pm" src="https://user-images.githubusercontent.com/6925974/47839145-94afdc00-de16-11e8-91d7-f3dc647b12af.png">

The error is very intermittent, I'd say it happens about 1 time out of 1000.

**Comment by olonho** [comment]
Could you please help us get the self-contained reproducer?

**Comment by brettwillis** [comment]
Ok, so I've learnt some more. Previously, around Kotlin/Native 0.8\~0.9 and Coroutines 0.26\~0.27, this happened very occasionally and I only remember it in `NSLog(...)` as described above. 

Now as I am experimenting more with Kotlin 1.3.0 and Coroutines 1.0.0, I've realised it's happening much more often, almost like it happens after a certain period of time. And the `SIGABRT` actually happens anywhere and everywhere, with no relation. Currently I don't know what part is causing the error so I can give you a reproducer. Here are some more stack traces:

<img width="505" alt="screen shot 2018-11-01 at 8 53 41 pm" src="https://user-images.githubusercontent.com/6925974/47875029-40d6de80-de7a-11e8-9828-896d33ea2106.png">

<img width="505" alt="screen shot 2018-11-01 at 8 50 01 pm" src="https://user-images.githubusercontent.com/6925974/47875033-43393880-de7a-11e8-8309-85c55c55fc9f.png">

I'm not explicitly using any `dealloc` hooks, but I don't know what's happening in the third party libraries I'm using. However I'm not seeing and obvious dealloc frames in the stack traces.

This may or may not be related, but I'm using Coroutines with my own Dispatcher wrapper for the main thread. The dispatcher looks like below. I've noticed that the errors often happen when there are a few levels of recursion in the Dispatcher (i.e. it dispatches a block, which dispatches a block, which dispatches a block, etc... around 5 levels).

	@UseExperimental(InternalCoroutinesApi::class)
	private object MainLoopDispatcher: CoroutineDispatcher(), Delay {

		override fun dispatch(context: CoroutineContext, block: Runnable) {
			dispatch_async(dispatch_get_main_queue()) {
				try {
					block.run()
				} catch (err: Throwable) {
					logError("UNCAUGHT", err.message ?: "", err)
					throw err
				}
			}
		}



		@InternalCoroutinesApi
		override fun scheduleResumeAfterDelay(timeMillis: Long, continuation: CancellableContinuation<Unit>) {
			dispatch_after(dispatch_time(DISPATCH_TIME_NOW, timeMillis * 1_000_000), dispatch_get_main_queue()) {
				try {
					with(continuation) {
						resumeUndispatched(Unit)
					}
				} catch (err: Throwable) {
					logError("UNCAUGHT", err.message ?: "", err)
					throw err
				}
			}
		}

		@InternalCoroutinesApi
		override fun invokeOnTimeout(timeMillis: Long, block: Runnable): DisposableHandle {
			val handle = object : DisposableHandle {
				var disposed = false
					private set

				override fun dispose() {
					disposed = true
				}
			}
			dispatch_after(dispatch_time(DISPATCH_TIME_NOW, timeMillis * 1_000_000), dispatch_get_main_queue()) {
				try {
					if (!handle.disposed) {
						block.run()
					}
				} catch (err: Throwable) {
					logError("UNCAUGHT", err.message ?: "", err)
					throw err
				}
			}

			return handle
		}

	}

Sorry about the vagueness, I'll keep trying to see a pattern to reproduce it, but any leads would be helpful.

**Comment by SvyatoslavScherbina** [comment]
Could you please share full stacktrace?
First of all, some top elements in your stacktrace seem to be hidden by Xcode. Could you please try to uncheck "Show only stack frames with debug symbols and between libraries" switch (leftmost button on the bottom of the stacktrace tab at the left pane, see https://help.apple.com/xcode/mac/10.0/#/devea99126aa for more details)?

Also I'd like to see the bottom elements of your stacktrace.

**Comment by brettwillis** [comment]
Here's another:

    #0	0x00000001af3a9104 in __pthread_kill ()
    #1	0x00000001af4240e0 in pthread_kill$VARIANT$mp ()
    #2	0x00000001af300d78 in abort ()
    #3	0x0000000102808eb0 in konan::abort() ()
    #4	0x0000000102808e38 in RuntimeAssertFailed(char const*, char const*) ()
    #5	0x0000000102809f90 in GarbageCollect ()
    #6	0x000000010280aa0c in ReleaseRef(ObjHeader const*) ()
    #7	0x0000000100c53d6c in outlined destroy of ThegateLibCommonChurch? ()
    #8	0x0000000100c53d04 in @objc MessageViewController.__ivar_destroyer ()
    #9	0x00000001ae9e0468 in object_cxxDestructFromClass(objc_object*, objc_class*) ()
    #10	0x00000001ae9f070c in objc_destructInstance ()
    #11	0x00000001ae9f0774 in object_dispose ()
    #12	0x00000001dc448bc8 in -[UIResponder dealloc] ()
    #13	0x00000001dc7568c0 in -[UIViewController dealloc] ()
    #14	0x0000000100c52ca8 in ___lldb_unnamed_symbol30$$thegate ()
    #15	0x00000001030bb584 in _swift_release_dealloc ()
    #16	0x0000000100c52de0 in block_destroy_helper ()
    #17	0x00000001af2a8a44 in _Block_release ()
    #18	0x000000010280abd4 in runDeallocationHooks(ContainerHeader*) ()
    #19	0x00000001028098ac in GarbageCollect ()
    #20	0x000000010280aa0c in ReleaseRef(ObjHeader const*) ()
    #21	0x000000010281966c in LeaveFrame ()
    #22	0x000000010281e318 in kfun:kotlinx.atomicfu.atomic(#GENERIC)Generic at /opt/teamcity-agent/work/88b0986a7186d029/atomicfu-native/src/main/kotlin/kotlinx/atomicfu/AtomicFU.kt:21
    #23	0x000000010282d6f0 in kfun:kotlinx.coroutines.AbstractContinuation.<init>(kotlin.coroutines.Continuation<#GENERIC>;kotlin.Int)kotlinx.coroutines.AbstractContinuation<#GENERIC> at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:61
    #24	0x000000010282c870 in kfun:kotlinx.coroutines.CancellableContinuationImpl.<init>(kotlin.coroutines.Continuation<#GENERIC>;kotlin.Int)kotlinx.coroutines.CancellableContinuationImpl<#GENERIC> at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/CancellableContinuation.kt:219
    #25	0x000000010284b3e8 in kfun:kotlinx.coroutines.channels.AbstractChannel.Itr.$hasNextSuspend$COROUTINE$13.invokeSuspend#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/CancellableContinuation.kt:181
    #26	0x000000010284b0ac in kfun:kotlinx.coroutines.channels.AbstractChannel.Itr.hasNextSuspend#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/AbstractChannel.kt:866
    #27	0x000000010284ad3c in kfun:kotlinx.coroutines.channels.AbstractChannel.Itr.hasNext#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/AbstractChannel.kt:855
    #28	0x000000010285d240 in kfun:kotlinx.coroutines.channels.$map$lambda-11$COROUTINE$71.invokeSuspend(kotlin.Result<kotlin.Any?>)kotlin.Any? at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/Channels.common.kt:145
    #29	0x0000000102797c78 in kfun:kotlin.coroutines.native.internal.BaseContinuationImpl.resumeWith(kotlin.Result<kotlin.Any?>) at /opt/teamcity-agent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:32
    #30	0x00000001028301a0 in kfun:kotlinx.coroutines.resumeMode$kotlinx-coroutines-core-native@kotlin.coroutines.Continuation<#GENERIC>.(#GENERIC;kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0:1
    #31	0x000000010282fbf4 in kfun:kotlinx.coroutines.resume$kotlinx-coroutines-core-native@kotlinx.coroutines.DispatchedTask<#GENERIC>.(kotlin.coroutines.Continuation<#GENERIC>;kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Dispatched.kt:272
    #32	0x000000010282f95c in kfun:kotlinx.coroutines.UndispatchedEventLoop.resumeUndispatched(kotlinx.coroutines.DispatchedTask<#STAR>)ValueType at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Dispatched.kt:58
    #33	0x000000010282f7cc in kfun:kotlinx.coroutines.dispatch$kotlinx-coroutines-core-native@kotlinx.coroutines.DispatchedTask<#GENERIC>.(kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Dispatched.kt:258
    #34	0x000000010282f41c in kfun:kotlinx.coroutines.AbstractContinuation.dispatchResume#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:182
    #35	0x000000010282f2ac in kfun:kotlinx.coroutines.AbstractContinuation.completeStateUpdate(kotlinx.coroutines.NotCompleted;kotlin.Any?;kotlin.Int) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:250
    #36	0x000000010282df18 in kfun:kotlinx.coroutines.CancellableContinuationImpl.completeResume(kotlin.Any) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/CancellableContinuation.kt:258
    #37	0x000000010284bc8c in kfun:kotlinx.coroutines.channels.AbstractChannel.ReceiveHasNext.completeResumeReceive#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/AbstractChannel.kt:942
    #38	0x0000000102841328 in kfun:kotlinx.coroutines.channels.AbstractSendChannel.offerInternal(#GENERIC)kotlin.Any at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/AbstractChannel.kt:52
    #39	0x00000001028574c0 in kfun:kotlinx.coroutines.channels.ConflatedChannel.offerInternal(#GENERIC)kotlin.Any at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/ConflatedChannel.kt:38
    #40	0x000000010285739c in kfun:kotlinx.coroutines.channels.ConflatedBroadcastChannel.Subscriber.offerInternal#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/ConflatedBroadcastChannel.kt:278
    #41	0x0000000102858490 in kfun:kotlinx.coroutines.channels.ConflatedBroadcastChannel.offerInternal#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/ConflatedBroadcastChannel.kt:250
    #42	0x000000010285684c in kfun:kotlinx.coroutines.channels.ConflatedBroadcastChannel.offer(#GENERIC)ValueType at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/ConflatedBroadcastChannel.kt:222
    #43	0x00000001028556bc in kfun:kotlinx.coroutines.channels.BroadcastCoroutine.offer#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/Broadcast.kt:86
    #44	0x000000010288d8f4 in kfun:nz.arrowheadapps.church.$ticker$lambda-8$lambda-7$COROUTINE$13.invokeSuspend(kotlin.Result<kotlin.Any?>)kotlin.Any? at /path/to/myproject/thegate/no source file:1
    #45	0x0000000102797c78 in kfun:kotlin.coroutines.native.internal.BaseContinuationImpl.resumeWith(kotlin.Result<kotlin.Any?>) at /opt/teamcity-agent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:32
    #46	0x00000001028301a0 in kfun:kotlinx.coroutines.resumeMode$kotlinx-coroutines-core-native@kotlin.coroutines.Continuation<#GENERIC>.(#GENERIC;kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0:1
    #47	0x000000010282fbf4 in kfun:kotlinx.coroutines.resume$kotlinx-coroutines-core-native@kotlinx.coroutines.DispatchedTask<#GENERIC>.(kotlin.coroutines.Continuation<#GENERIC>;kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Dispatched.kt:272
    #48	0x000000010282f760 in kfun:kotlinx.coroutines.dispatch$kotlinx-coroutines-core-native@kotlinx.coroutines.DispatchedTask<#GENERIC>.(kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Dispatched.kt:261
    #49	0x000000010282f41c in kfun:kotlinx.coroutines.AbstractContinuation.dispatchResume#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:182
    #50	0x000000010282f2ac in kfun:kotlinx.coroutines.AbstractContinuation.completeStateUpdate(kotlinx.coroutines.NotCompleted;kotlin.Any?;kotlin.Int) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:250
    #51	0x000000010282e8fc in kfun:kotlinx.coroutines.AbstractContinuation.updateStateToFinal#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:222
    #52	0x000000010282e6e8 in kfun:kotlinx.coroutines.AbstractContinuation.resumeImpl(kotlin.Any?;kotlin.Int) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:200
    #53	0x000000010282e050 in kfun:kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched@kotlinx.coroutines.CoroutineDispatcher.(#GENERIC) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/CancellableContinuation.kt:262
    #54	0x0000000102877cfc in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.scheduleResumeAfterDelay$lambda-1#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:47
    #55	0x0000000102877bcc in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.$<anonymous>$FUNCTION_REFERENCE$36.invoke#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:41
    #56	0x000000010286dcd0 in platform_darwin_kniBridge227 ()
    #57	0x000000010286e620 in __platform_darwin_kniBridge226_block_invoke ()
    #58	0x0000000103950de4 in _dispatch_client_callout ()
    #59	0x00000001039541e0 in _dispatch_continuation_pop ()
    #60	0x0000000103966cac in _dispatch_source_invoke ()
    #61	0x000000010395e914 in _dispatch_main_queue_callback_4CF ()
    #62	0x00000001af7a21bc in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
    #63	0x00000001af79d084 in __CFRunLoopRun ()
    #64	0x00000001af79c5b8 in CFRunLoopRunSpecific ()
    #65	0x00000001b1a10584 in GSEventRunModal ()
    #66	0x00000001dc097558 in UIApplicationMain ()
    #67	0x0000000100c6fc90 in main at /path/to/myproject/thegate/thegate/AppDelegate.swift:19
    #68	0x00000001af25cb94 in start ()
    Enqueued from com.apple.main-thread (Thread 1) Queue : com.apple.main-thread (serial)
    #0	0x0000000103967bdc in dispatch_after ()
    #1	0x000000010286e5d0 in platform_darwin_kniBridge226 ()
    #2	0x000000010286d89c in kfun:platform.darwin.dispatch_after(kotlin.ULong;platform.darwin.NSObject?;kotlin.Function0<kotlin.Unit>?) ()
    #3	0x00000001028773e4 in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.scheduleResumeAfterDelay#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:41
    #4	0x000000010283fd8c in kfun:kotlinx.coroutines.$delay$COROUTINE$6.invokeSuspend(kotlin.Result<kotlin.Any?>)kotlin.Any? at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Delay.kt:79
    #5	0x0000000102840040 in kfun:kotlinx.coroutines.delay(kotlin.Long) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Delay.kt:60
    #6	0x000000010288d91c in kfun:nz.arrowheadapps.church.$ticker$lambda-8$lambda-7$COROUTINE$13.invokeSuspend(kotlin.Result<kotlin.Any?>)kotlin.Any? at /path/to/myproject/thegate/no source file:1
    #7	0x0000000102797c78 in kfun:kotlin.coroutines.native.internal.BaseContinuationImpl.resumeWith(kotlin.Result<kotlin.Any?>) at /opt/teamcity-agent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:32
    #8	0x00000001028301a0 in kfun:kotlinx.coroutines.resumeMode$kotlinx-coroutines-core-native@kotlin.coroutines.Continuation<#GENERIC>.(#GENERIC;kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0:1
    #9	0x000000010282fbf4 in kfun:kotlinx.coroutines.resume$kotlinx-coroutines-core-native@kotlinx.coroutines.DispatchedTask<#GENERIC>.(kotlin.coroutines.Continuation<#GENERIC>;kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Dispatched.kt:272
    #10	0x000000010282f760 in kfun:kotlinx.coroutines.dispatch$kotlinx-coroutines-core-native@kotlinx.coroutines.DispatchedTask<#GENERIC>.(kotlin.Int)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Dispatched.kt:261
    #11	0x000000010282f41c in kfun:kotlinx.coroutines.AbstractContinuation.dispatchResume#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:182
    #12	0x000000010282f2ac in kfun:kotlinx.coroutines.AbstractContinuation.completeStateUpdate(kotlinx.coroutines.NotCompleted;kotlin.Any?;kotlin.Int) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:250
    #13	0x000000010282e8fc in kfun:kotlinx.coroutines.AbstractContinuation.updateStateToFinal#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:222
    #14	0x000000010282e6e8 in kfun:kotlinx.coroutines.AbstractContinuation.resumeImpl(kotlin.Any?;kotlin.Int) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt:200
    #15	0x000000010282e050 in kfun:kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched@kotlinx.coroutines.CoroutineDispatcher.(#GENERIC) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/CancellableContinuation.kt:262
    #16	0x0000000102877cfc in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.scheduleResumeAfterDelay$lambda-1#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:47
    #17	0x0000000102877bcc in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.$<anonymous>$FUNCTION_REFERENCE$36.invoke#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:41
    #18	0x000000010286dcd0 in platform_darwin_kniBridge227 ()
    #19	0x000000010286e620 in __platform_darwin_kniBridge226_block_invoke ()
    #20	0x0000000103950de4 in _dispatch_client_callout ()
    #21	0x00000001039541e0 in _dispatch_continuation_pop ()
    #22	0x0000000103966cac in _dispatch_source_invoke ()
    #23	0x000000010395e914 in _dispatch_main_queue_callback_4CF ()
    #24	0x00000001af7a21bc in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
    #25	0x00000001af79d084 in __CFRunLoopRun ()
    #26	0x00000001af79c5b8 in CFRunLoopRunSpecific ()
    #27	0x00000001b1a10584 in GSEventRunModal ()
    #28	0x00000001dc097558 in UIApplicationMain ()
    #29	0x0000000100c6fc90 in main at /path/to/myproject/thegate/thegate/AppDelegate.swift:19
    #30	0x00000001af25cb94 in start ()
    Enqueued from com.apple.main-thread (Thread 1) Queue : com.apple.main-thread (serial)
    #0	0x0000000103967bdc in dispatch_after ()
    #1	0x000000010286e5d0 in platform_darwin_kniBridge226 ()
    #2	0x000000010286d89c in kfun:platform.darwin.dispatch_after(kotlin.ULong;platform.darwin.NSObject?;kotlin.Function0<kotlin.Unit>?) ()
    #3	0x00000001028773e4 in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.scheduleResumeAfterDelay#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:41
    #4	0x000000010283fd8c in kfun:kotlinx.coroutines.$delay$COROUTINE$6.invokeSuspend(kotlin.Result<kotlin.Any?>)kotlin.Any? at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Delay.kt:79
    #5	0x0000000102840040 in kfun:kotlinx.coroutines.delay(kotlin.Long) at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Delay.kt:60
    #6	0x000000010288d91c in kfun:nz.arrowheadapps.church.$ticker$lambda-8$lambda-7$COROUTINE$13.invokeSuspend(kotlin.Result<kotlin.Any?>)kotlin.Any? at /path/to/myproject/thegate/no source file:1
    #7	0x0000000102797c78 in kfun:kotlin.coroutines.native.internal.BaseContinuationImpl.resumeWith(kotlin.Result<kotlin.Any?>) at /opt/teamcity-agent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:32
    #8	0x000000010282ba90 in kfun:kotlinx.coroutines.DispatchedTask.run() at /opt/teamcity-agent/work/44ec6e850d5c63f0:1
    #9	0x0000000102877144 in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.dispatch$lambda-0#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:29
    #10	0x0000000102877074 in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.$<anonymous>$FUNCTION_REFERENCE$35.invoke#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:27
    #11	0x000000010286dbe8 in platform_darwin_kniBridge206 ()
    #12	0x000000010286e41c in __platform_darwin_kniBridge205_block_invoke ()
    #13	0x000000010394f840 in _dispatch_call_block_and_release ()
    #14	0x0000000103950de4 in _dispatch_client_callout ()
    #15	0x000000010395ea94 in _dispatch_main_queue_callback_4CF ()
    #16	0x00000001af7a21bc in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
    #17	0x00000001af79d084 in __CFRunLoopRun ()
    #18	0x00000001af79c5b8 in CFRunLoopRunSpecific ()
    #19	0x00000001b1a10584 in GSEventRunModal ()
    #20	0x00000001dc097558 in UIApplicationMain ()
    #21	0x0000000100c6fc90 in main at /path/to/myproject/thegate/thegate/AppDelegate.swift:19
    #22	0x00000001af25cb94 in start ()
    Enqueued from com.apple.main-thread (Thread 1) Queue : com.apple.main-thread (serial)
    #0	0x0000000103955c24 in dispatch_async ()
    #1	0x000000010286e3cc in platform_darwin_kniBridge205 ()
    #2	0x000000010286d774 in kfun:platform.darwin.dispatch_async(platform.darwin.NSObject?;kotlin.Function0<kotlin.Unit>?) ()
    #3	0x0000000102876ed8 in kfun:nz.arrowheadapps.church.platform.MainLoopDispatcher.dispatch#internal at /path/to/myproject/common/src/iosMain/kotlin/platform/Coroutines.kt:27
    #4	0x0000000102829134 in kfun:kotlinx.coroutines.resumeCancellable$kotlinx-coroutines-core-native@kotlin.coroutines.Continuation<#GENERIC>.(#GENERIC)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/Dispatched.kt:127
    #5	0x000000010283494c in kfun:kotlinx.coroutines.intrinsics.startCoroutineCancellable$kotlinx-coroutines-core-native@kotlin.coroutines.SuspendFunction1<#GENERIC,#GENERIC>.(#GENERIC;kotlin.coroutines.Continuation<#GENERIC>)Generic at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/intrinsics/Cancellable.kt:23
    #6	0x00000001028559b4 in kfun:kotlinx.coroutines.channels.LazyBroadcastCoroutine.onStart#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/Broadcast.kt:120
    #7	0x0000000102833c94 in kfun:kotlinx.coroutines.AbstractCoroutine.onStartInternal$kotlinx-coroutines-core-native() at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/AbstractCoroutine.kt:77
    #8	0x0000000102828614 in kfun:kotlinx.coroutines.JobSupport.startInternal#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/JobSupport.kt:345
    #9	0x00000001028271bc in kfun:kotlinx.coroutines.JobSupport.start()ValueType at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/JobSupport.kt:343
    #10	0x0000000102855a8c in kfun:kotlinx.coroutines.channels.LazyBroadcastCoroutine.openSubscription#internal at /opt/teamcity-agent/work/44ec6e850d5c63f0/common/kotlinx-coroutines-core-common/src/channels/Broadcast.kt:115
    #11	0x0000000102879714 in kfun:nz.arrowheadapps.church.RefCountChannel.openSubscription()kotlinx.coroutines.channels.ReceiveChannel<#GENERIC> at /path/to/myproject/common/src/commonMain/kotlin/Utils.common.kt:235
    #12	0x000000010288e72c in kfun:nz.arrowheadapps.church.TimeAgoImpl.string(platform.Foundation.NSDate)kotlinx.coroutines.channels.ReceiveChannel<kotlin.String> at /path/to/myproject/common/src/commonMain/kotlin/TimeAgo.kt:18
    #13	0x00000001028a1d28 in kfun:nz.arrowheadapps.church.ui.FeedItemViewController.<set-item>(nz.arrowheadapps.church.feeds.FeedItem?) at /path/to/myproject/common/src/commonMain/kotlin/ui/FeedItemViewController.kt:59
    #14	0x0000000102750b50 in ___lldb_unnamed_symbol306$$thegateLib ()
    #15	0x0000000100c596b0 in FeedItemCell.item.setter ()
    #16	0x0000000100c62c58 in FeedViewController.tableView(_:cellForRowAt:) at /path/to/myproject/thegate/thegate/FeedViewController.swift:78
    #17	0x0000000100c62d28 in @objc FeedViewController.tableView(_:cellForRowAt:) ()
    #18	0x00000001dc5baf74 in -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] ()
    #19	0x00000001dc5bb4bc in -[UITableView _createPreparedCellForGlobalRow:willDisplay:] ()
    #20	0x00000001dc586c40 in -[UITableView _updateVisibleCellsNow:isRecursive:] ()
    #21	0x00000001dc5a4b2c in -[UITableView layoutSubviews] ()
    #22	0x00000001dc745998 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
    #23	0x00000001b3df5a34 in -[CALayer layoutSublayers] ()
    #24	0x00000001b3dfa9c4 in CA::Layer::layout_if_needed(CA::Transaction*) ()
    #25	0x00000001b3d599d4 in CA::Context::commit_transaction(CA::Transaction*) ()
    #26	0x00000001b3d882f4 in CA::Transaction::commit() ()
    #27	0x00000001b3d8915c in CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) ()
    #28	0x00000001af7a1b94 in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
    #29	0x00000001af79c828 in __CFRunLoopDoObservers ()
    #30	0x00000001af79cdc8 in __CFRunLoopRun ()
    #31	0x00000001af79c5b8 in CFRunLoopRunSpecific ()
    #32	0x00000001b1a10584 in GSEventRunModal ()
    #33	0x00000001dc097558 in UIApplicationMain ()
    #34	0x0000000100c6fc90 in main at /path/to/myproject/thegate/thegate/AppDelegate.swift:19
    #35	0x00000001af25cb94 in start ()

**Comment by brettwillis** [comment]
After inspecting the stack traces and experimenting more, I think I can confirm the behaviour of this crash:
1. There is a view controller called `MessageViewController`
2. `MessageViewController` has `var church: CommonChurch? /*ThegateLibCommonChurch*/` which has an instance assigned to it on initialisation
3. `TheGateChurch` is a **singleton** object from the Kotlin framework which inherits from the abstract base class `ThegateLibCommonChurch` (in Kotlin: `object TheGateChurch: Church() { ... }`). In the framework: `TheGateChurch` is `ThegateLibTheGateChurch` (Swift name: `TheGateChurch`), and `Church` is `ThegateLibComonChurch` (Swift name: `CommonChurch`).
4. The singleton instance of `TheGateChurch` is retrieved in the root view controller using the factory function `TheGateChurch()` and is retained by the root view controller. When `MessageViewController` is initialised it is the instance of `TheGateChurch` is passed to `MessageViewController`. As I mentioned the instance is retained by the root view controller, so I don't know why it is being destroyed when `MessageViewController` is released ???
5. This crash always happens only after `MessageViewController` has been presented and then dismissed. I suspect the crash just happens at the first GC cycle after it has been dismissed, normally with 10 seconds or so.

**Comment by brettwillis** [comment]
Thank you for your work on this. Is there a release available with this fix that I can verify?

**Comment by olonho** [comment]
Yes, in upcoming 1.3.10 Kotlin release Native part will have this issue fixed.

**Comment by brettwillis** [comment]
I've tested with 1.3.10, and the error looks to have been fixed. Thank you!
