### ISSUE TITLE
unable to add .jar dependencies from mavenLocal for ios targets

### ISSUE THREAD

**Issue by mitdre** [JetBrains/kotlin-native#2293]
I'm writing a multiplatform presenter library. 

The code below exists in my root project's gradle file.

```
subprojects{
    apply plugin: 'java'

    dependencies{
        compile "com.xxx:yyy:zzz"
    }

    repositories{
        mavenLocal()
    }
}
```

this is sufficient to satisfy dependencies in the jvm artifact. However, kotlin/native declares references to classes in `com.xxx.yyy` to be unresolved when building ios frameworks.

**Comment by olonho** [comment]
Correct, Kotlin/Native doesn't use JVM jars, and cannot depend on them.

**Comment by mitdre** [comment]
not the answer i wanted to hear. Sad!
