### ISSUE TITLE
Objective C Framework

### ISSUE THREAD

**Issue by JackED42** [JetBrains/kotlin-native#2294]
Looking at the framework that is produced, it is a dynamic framework, and I was wondering if it would be possible to make it static. I am not sure if this is a limitation of kotlin native, but i would think it should be possible.

I am going to attempt to build a custom version that changes LinkStage.kt to make framework build statically rather than dynamic, but just wanted to check if there was another way using konan.properties or something.

Thanks

**Comment by olonho** [comment]
Why do you want static framework? Generally, even dynamic frameworks are included into the application bundle and static linkage of things like Foundation is unlikely what you really need.

**Comment by JackED42** [comment]
For the project I am using, I would need to use it statically. This is due to slow start up times with the many dynamic libraries already within the app.

I have tried to build kotlin native myself to test. But when I run konanc I get an error that it can't find stdlib

**Comment by olonho** [comment]
Likely statically linked library will start slower, as system libraries are preloaded in memory, while static library shall be read from the storage.

**Comment by mikeger** [comment]
@olonho if you are using the dynamic framework, then it's packaged together with the main application binary in the `Frameworks` folder. When the app is starting, the iOS has to link the calls from the app to the framework.
If you are using the static framework, then it's linked statically to the application binary and the code is linked on the compilation stage. In this case the framework is integrated in the app and it must not be loaded separately.

**Comment by kylejbrock** [comment]
@olonho Being able to generate a static framework would be quite helpful.

There is the scenario of needing to link against a static framework (for instance, Firebase).  And also linking against the same frameworks in the actual iOS app.

However, linking against a static framework with a dynamic framework ... and then including both libraries (static & dynamic) in the app causes some very bad behavior.  

This situation seems to be alleviated by using a static framework.

There may be a better way to accomplish this, I'm just not sure what it is.

**Comment by olonho** [comment]
Yes, static frameworks can be produced with `-Xstatic-framework`
