### ISSUE TITLE
RegEx fails which works on JVM and JS

### ISSUE THREAD

**Issue by jurmous** [JetBrains/kotlin-native#2297]
The following test succeeds on JS and JVM but fails in Native (only tested MacOS). It succeeds with value `:20` so something goes wrong with the `+` operator.

```kotlin
import kotlin.test.Test
import kotlin.test.assertTrue

class RegexTest {
    private val regEx = Regex("^(:[0-5]?[0-9])+$")

    @Test
    fun regexTest() {
        assertTrue {
            regEx.containsMatchIn(":20:30")
        }
    }
}
```

**Comment by olonho** [comment]
Curiously with regexp `"^(:[0-5]?[0-9])+"` test passes as well.

**Comment by olonho** [comment]
Also note potential problems listed in https://youtrack.jetbrains.com/issue/KT-25473

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/2361/commits/7adc11f35f30c2bd07cfc4c65778745967b741ad.

**Comment by jurmous** [comment]
Thanks for the fix! ❤️
