### ISSUE TITLE
Emoji corrupts later string operations

### ISSUE THREAD

**Issue by jurmous** [JetBrains/kotlin-native#2298]
When using certain emojis in code it corrupts later String operations. (Only tested on MacOS)

Below a test:

Main module
```kotlin
object TestObject {
    fun test(): String {
        val test = "test"
        return "?$test"
    }
}
```

Test module
```kotlin
import kotlin.test.Test
import kotlin.test.assertEquals

open class StringTest {
    @Test
    fun stringTest() {
        println("\uD83E\uDD17")
        assertEquals("?test", TestObject.test())
    }
}
```

Result:
```
🤗
kotlin.AssertionError: Expected <?test>, actual <�test>.
```

(No problems in JVM and JS)

**Comment by olonho** [comment]
Very interesting. Unfortunately, I cannot reproduce it with the following snippet
```import kotlin.test.Test
import kotlin.test.assertEquals

open class StringTest {
    @Test
    fun stringTest() {
        println("\uD83E\uDD17")
        assertEquals("?test", TestObject.test())
    }
}

object TestObject {
    fun test(): String {
        val test = "test"
        return "?$test"
    }
}
```
compiled like `./dist/bin/konanc emo.kt -tr -o emo` on macOS. Could you please give us more information (like small GitHub repo and OS) so that we could reproduce such behavior.

**Comment by jurmous** [comment]
It only goes wrong if TestObject is in a different Module. If it is in the same module the test succeeds.

**Comment by olonho** [comment]
Indeed, with emo1.kt
```object TestObject {
    fun test(): String {
        val test = "test"
        return "?$test"
    }
}``` and 
emo2.kt
```import kotlin.test.*

open class StringTest {
    @Test
    fun stringTest() {
        println("\uD83E\uDD17")
        assertEquals("?test", TestObject.test())
    }
}
```
compiled as `./dist/bin/konanc emo1.kt -p library -o emo1` and `./dist/bin/konanc emo2.kt -l emo1 -tr -o emo` I can see the behavior you described.

**Comment by olonho** [comment]
See https://youtrack.jetbrains.com/issue/KT-28006 for analysis. Generally, to workaround such a problem, you can do smth like 
``val smile = byteArrayOf(-16, -97, -92, -105).stringFromUtf8()
    println(smile)``
and we will fix it in further versions.

**Comment by jurmous** [comment]
Thanks for looking into it so quickly! 😄
