### ISSUE TITLE
udev and usb for platform.linux

### ISSUE THREAD

**Issue by thawkins** [JetBrains/kotlin-native#2299]
Would it be possible to add the libudev and libusb imports for the linux platform.

**Comment by olonho** [comment]
Not sure if we plan to extend platform libs on Linux too far from libc, interop with other libs can be easily achieved with cinterop tool.

**Comment by thawkins** [comment]
What about supporting a contrib process, like  platform.linux.contrib.xxx so that folks can contribute library mappings?

**Comment by olonho** [comment]
Makes sense, maybe even ship those in .def file form in distribution, not building bindings explicitly. Please send PR with .def to platformLibs/src/contrib/<os>.

**Comment by thawkins** [comment]
i will try and get a pair of defs for libusb and libudev done and submitted
as a pr to that folder

it may take me at least a week as im still learning all ty3 interop stuff,
im building a libary to talk to arduinos, 3d printers, cncs via the usb
serial devices, it works but i need these to to pull connection metadata
back.

**Comment by olonho** [comment]
No progress here, closing.
