### ISSUE TITLE
`Disambiguating Targets` help needed

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#2306]
https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#disambiguating-targets

I'm playing with https://github.com/JetBrains/kotlin-mpp-example and would like to have 2 android(or 2 ios) apps that use the same common module. However, I need the common module to be built with different configs. 

`buildTypes` + `flavors` would do the trick for android. As far as I understand `configurations` + `sourceSets` is the way to go with kotlin native.

So, in order to do that, I added a configuration with a source set and specified it in the dependencies as follows.

> greeting/build.gradle:
```
...
configurations {
    xyz
}

kotlin {

    targets {
        fromPreset(presets.android, 'androidLib')
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
            }
        }

        commonTest {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-test-common'
                implementation 'org.jetbrains.kotlin:kotlin-test-annotations-common'
            }
        }

        androidLibMain {
            dependsOn commonMain
        }

        xyz {
            dependsOn androidLibMain
        }
    }
}
...
```

> androidApp/build.gradle
```
implementation project(path: ':greeting', configuration: 'androidLibXyz')
```

This results in gradle error `Unable to resolve dependency for ':androidApp@debug/compileClasspath': Could not resolve project :greeting.`

Although this seems to be exactly what the doc says: 
> Use the appropriate target's runtime elements configuration, such as jvm6RuntimeElements.

Any hint on how to do this right is highly appreciated.

**Comment by ildarsharafutdinov** [comment]
Let's say I want to specify configuration explicitly something like:

`implementation project(path: ':greeting', configuration: 'androidLibMainImplementation')`

This one passes gradle project structure checks, but the compilation fails.

What configuration is used by default?

**Comment by ildarsharafutdinov** [comment]
@h0tk3y ,

Thank you for the clarification and samples on how to use attributes, I'll definitely try them.

However, `<targetName>RuntimeElements` part is still unclear. 

Having that there is the `androidLib` target in the sample [project](https://github.com/JetBrains/kotlin-mpp-example)  I expect the following statements to be absolutely the same:
1. `implementation project(':greeting')` 
2. `implementation project(path: ':greeting', configuration: 'androidLibRuntimeElements')`

Nevertheless, only the first one works while the second results in `unable to resolve dependency` errors.

So when you refer to `<targetName>`, is it the second param in `fromPreset(presets.android, 'androidLib')` call?

**Comment by ildarsharafutdinov** [comment]
btw, 

It doesn't look as if I can define 2 android targets, since it results in `Cannot add extension with name 'kotlinOptions', as there is an extension already registered with that name.`.

Having 2 jvm targets is ok ...

**Comment by SvyatoslavScherbina** [comment]
Please open a new issue in YouTrack if you still experience the problem: https://kotl.in/issue
