### ISSUE TITLE
Emit LLVM Bitcode from Gradle Plugin?

### ISSUE THREAD

**Issue by kunalsheth** [JetBrains/kotlin-native#2308]
I remember this was possible on previous versions.
Has it been discontinued?
Is there a new way of handling custom targets?

**Comment by olonho** [comment]
What exactly are you trying to do? For iOS case see https://github.com/JetBrains/kotlin-native/blob/master/FAQ.md#q-how-do-i-enable-bitcode-for-my-kotlin-framework.

**Comment by kunalsheth** [comment]
I am trying to use kotlin-native for a robotics competition (for a target not already supported).
I'd prefer to use the official kotlin-native plugin instead of distributing my own fork.  (#1827)

Right now, my plan is to compile Kotlin into LLVM ".bc" files and then have the [robotics competition's official Gradle plugin](https://github.com/wpilibsuite/GradleRIO) compile for the platform. Is this possible? Or would you recommend a different approach?

Thanks!

**Comment by olonho** [comment]
It will unlikely work out of the box, as K/N has libffi static library linked into generated code, so you'll need to provide one for your platform. Other than that, it may work, and in this case `-p bitcode` CLI compiler option may help. However, you also need standard library's and runtime's bitcode as well, use `--verbose object_files,linker` to find out needed files.

**Comment by olonho** [comment]
OK, now we got rid of libffi, so it could be possible. @ilmat192 can Gradle DSL produce that?

**Comment by ilmat192** [comment]
No, currently the `kotlin-multiplatform` plugin cannot produce separate bitcode files.

> I remember this was possible on previous versions.

Yes, we did have such a functionality in our first `konan` plugin. It's deprecated and not supported now but it's still available at the [Plugin portal](https://plugins.gradle.org/plugin/org.jetbrains.kotlin.konan). So probably you could use it.

Adding bitcode producing to the `kotlin-multiplatform` plugin doesn't look very complex. So I think we can do this.

**Comment by SvyatoslavScherbina** [comment]
Regarding custom targets: emitting LLVM bitcode can probably help only for small number of cases, because bitcode is in fact platform-dependent.

For handling custom targets, please see https://youtrack.jetbrains.com/issue/KT-43974
If you have other use cases for emitting bitcode, please create new issue in YouTrack using https://kotl.in/issue
