### ISSUE TITLE
@CName annotation should work for multiplatform commonMain

### ISSUE THREAD

**Issue by Syrou** [JetBrains/kotlin-native#2309]
In order to export a top level function from kotlin to a c library we can use the @CName annotation to lift the function out from the normal struct setup. While trying to develop a multiplatform project and use commonMain as the "truth" there is no way to tell that a specific function should be top level.

This is currently only possible in the native modules, but this creates a problem because even with the -Xmulti-platform because the annotation wont work in commonMain with an expect/actual setup

This is highly needed in order to easily create C# libraries without any weird mangling or instance setups

**Comment by SvyatoslavScherbina** [comment]
Fixed in 1.5.20.
