### ISSUE TITLE
cinterop -linkerOpts does not honor "linker options"

### ISSUE THREAD

**Issue by jwerle** [JetBrains/kotlin-native#2312]
but if `linkerOpts` is found in a `.def` file, it works..

**Comment by olonho** [comment]
Could you please provide an example of what doesn't work and how you expect it to work?

**Comment by jwerle** [comment]
@olonho The `cinterop` command is not honoring the `-linkerOpts` command line argument, or I am using it incorrectly.

I need to define `linkerOpts` [here](https://github.com/datkt/uv/blob/master/uv.def#L8), which are the results of running `pkg-config --libs libuv/libuv.pc`. Ideally, this can be done programmatically in a [Makefile](https://github.com/datkt/uv/blob/master/Makefile#L31) instead and I can omit it from the `.def` file all together.

konanc information:

```
$ konanc -version
info: kotlinc-native 1.3.20-dev-689 (JRE 1.8.0_192-b26)
Kotlin/Native: 1.1-dev
```

**Comment by ulex** [comment]
I have a strong feeling, that cinterop does not honor any argument except `-def`.
It seems very weird that invoking `cinterop -def libcurl.def dsafdsafdsa` does not produce any error.

**Comment by olonho** [comment]
`linkerOpts` to cinterop only makes sense for JVM interop at the moment, as we build dynamic library here. Improved error reporting here.
