### ISSUE TITLE
cinterop and relative paths

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#2314]
Partially was discussed in #1032, but still require ugly workarounds.

Situation: I want to interop with C library, available in precompiled release tarball, and link it statically.
So I downloaded and unpacked it to "build" directory, and add to .def file relative paths:

```
...

headers = ui.h
noStringConversion = uiFreeInitError
compilerOpts = -I./build

staticLibraries = libui.a
libraryPaths = build

...
```

But this path is  relative to current OS directory, not to `.def` or `.gradle` file!

So it works if I compile it as `cd libui && ../gradlew build`,
but if called as `./gradlew :libui:build` - it falis.

OK, I can add support for this case:
```
...

headers = ui.h
noStringConversion = uiFreeInitError
compilerOpts = -I./build -I./libui/build

staticLibraries = libui.a
libraryPaths = build libui/build

...
```
and i works in both cases.

But I still can call it from something else, and it fail: `cd samples && ../gradlew :libui:build`.

As workaroind I can add to .gradle
```
...
            compilations.main {
                cinterops {
                    libui {
                        includeDirs "${project.rootDir}/libui/build"
                    }
                }
            }
...
```
but not for `libraryPaths` - there are no such option in DSL.

And in general I think this workaround is ugly - relative paths in `.def` should work in a predictable way.

**Comment by Dominaezzz** [comment]
Is this going to be fixed anytime soon. My build is rather fragile because I've hard-coded the path.

**Comment by olonho** [comment]
We believe that proper approach is to compute appropriate full paths in build scripts.

**Comment by msink** [comment]
Maybe, but then `libraryPaths` or something similar should be added to cinterop tool and dradle plugin.
Or cinerop should handle `linkerOpts=-L...` for static libs.

**Comment by msink** [comment]
Well, looks like `cinterop` supports it, but how to call it from `build.gradle.kts` ?
```patch
         }
         compilations["main"].cinterops.create("libui") {
             includeDirs(buildDir)
+            freeCompilerArgs = mutableListOf("-staticLibrary=$buildDir/libui.a")
         }
     }
```
```
Script compilation error:
  Line 54:             freeCompilerArgs = mutableListOf("-staticLibrary=$buildDir/libui.a")
                       ^ Unresolved reference: freeCompilerArgs
1 error
```

**Comment by msink** [comment]
Ok,
```patch
         compilations["main"].cinterops.create("libui") {
             includeDirs(buildDir)
         }
+        compilations["main"].kotlinOptions.freeCompilerArgs = mutableListOf(
+            "-include-binary", "$buildDir/libui.a"
+        )
     }
 
     if (os.isLinux || publishModeEnabled) linuxX64("linux") {
```
Compiles, but in this case `libui.a` is included in `libui.klib`.
Before it was included in `libui-cinterop-libui.klib`.
Does it matter?

**Comment by jeancharles-roger** [comment]
I have the problem when using [Gradle composite builds](https://docs.gradle.org/current/userguide/composite_builds.html). When I build from the project everything is fine with a relative `libraryPath`but it fails when the project is composed by another.

```
staticLibraries = libiup.a
libraryPaths.linux = iup/lib/iup-3.28/linux64
libraryPaths.mingw = iup/lib/iup-3.28/windows64
libraryPaths.osx = iup/lib/iup-3.28/darwin64
```

Having a reliable reference path for relative one would be nice.

**Comment by SalomonBrys** [comment]
Another solution:

```diff
 mainCompilation.cinterops.create("libcrypto") {
+    extraOpts("-libraryPath", "$projectDir/nativeLib/build/$targetName/lib")
 }
```

This has the advantage of having the static library be included in the `cinterop` klib.

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48082, closing.
