### ISSUE TITLE
K/N debugger is very slow with LLDB bindings

### ISSUE THREAD

**Issue by ddolovov** [JetBrains/kotlin-native#2315]
**STR:**
* Import a sample project (https://drive.google.com/open?id=1AFMmhxyleQYqVFHkabO24bhTpUjpuY3O) to CLion 183+.
* Setup a breakpoint at `Sample.kt` line 12 and run in debug mode.

**Expected Result:**
* Debugger is fast/responsive.
* Fields (even inner fields) are displayed fast.

**Actual Result:**
* There are performance issues with displaying fields.
   * Here is the video that shows the speed of displaying fields with LLDB bindings (`konan_lldb.py`) enabled: https://drive.google.com/open?id=1PH-chFwIFiVPcGp6Nj2PjDTZYJ5DwlvM
   * Here is the video that shows speed of debugger with disabled LLDB bindings: https://drive.google.com/file/d/1-XNKH5Q_gVFQUWeCTB32vIPsx4ezVGh_/view?usp=sharing
* Also, CLion console has a lot of repetitive error messages like this: `Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in  ignored`

**Comment by vvlevchenko** [comment]
It isn't very honest comparison, in K/N we have python interpretation and zillion calls to runtime, while C need once parse dwarf layout. Closer comparison could be debugging of objC code, it's of course has also native support but lldb still has to ask runtime (not so actively) to accompaniment. It's possible that adding native formatters in Clion's lldb significantly reduce python overhead, but not sure about cost of runtime support.

**Comment by vvlevchenko** [comment]
bindings since 1.4.20 has significantly improved performance of synthetic object creation. If it's still the issue please open new ticket in https://youtrack.jetbrains.com/search/Native%2520issues-27280
