### ISSUE TITLE
K/N debugger: no way to access `this` in debugger

### ISSUE THREAD

**Issue by ddolovov** [JetBrains/kotlin-native#2316]
**Problem:** This is no way to access `this` in Kotlin/Native debugger would it be LLDB console or CLion expression evaluator window.
<img src="http://drive.google.com/uc?export=view&id=1DCsXKyC1SkDPC72m2UO0c_YJat3zSFu_">
<img src="https://drive.google.com/uc?export=view&id=1F0gwpHjCKBRpsrqAjx-nJagL1nkntImv">

**Expected:** It should be possible to use `this` (or close analogue) in LLDB console and in CLion expression evaluator.

**Comment by vvlevchenko** [comment]
please take a look at #2323, it's workaround over limitation of c-expression evaluator. Perhaps it could be used in CLion, for a period of lack of kotlin expression evaluator.

**Comment by ddolovov** [comment]
I would like to reopen this issue because I believe we do need possibility to evaluate expressions with `this` keyword in K/N debugger. As for K/N support in IDE this even becomes critical (other flavors of Kotlin allow using `this` in "Expression Evaluator" window).

**Comment by SvyatoslavScherbina** [comment]
@vvlevchenko @ddolovov is this still the case?

**Comment by ddolovov** [comment]
Yes, it is. There is still no way to access `this` in IDE, e.g. in "Evaluate Expression"

**Comment by vvlevchenko** [comment]
```

**Comment by SvyatoslavScherbina** [comment]
I see.
> as a workaround it's possible to rename: <this> -> _this

Let's use this approach.

**Comment by vvlevchenko** [comment]
the issue's been fixed in agreed way.
