### ISSUE TITLE
K/N debugger points to the wrong line number on entering fun with params

### ISSUE THREAD

**Issue by ddolovov** [JetBrains/kotlin-native#2319]
**STR:**
* Write and compile a simple program. Like this:
```kotlin
/* top-level comment */

fun greet0() {
    println("Hello, anonymous!")
}

@Suppress("UNUSED_VARIABLE")
fun greet1(name: String) {
    println("Hello, $name!")
}

/**
 * block comment
 */
fun greet2(givenName: String, secondName: String) {
    println("Hello, $givenName $secondName!")
}

fun main() {
    greet0()
    greet1("John")
    greet2("John", "Smith")
}
```
* Set breakpoints at lines 20 (where `greet0()` call is made), 21 (`greet1()`) and 22 (`greet2()`).
* Run in debugger and wait until the first breakpoint is hit.
* Do step in (`step` command).
* You will move inside of `greet0()` function call to the line 4. That's OK.
* Continue (`continue` command). Wait until the second breakpoint is hit.
* Do step in.
* You will move to the line 7 (this is the line with `@Suppress` annotation). **This is wrong!** Backtrace:
```
(lldb) thread backtrace
* thread #1, queue = 'com.apple.main-thread', stop reason = step in
  * frame #0: 0x000000010680ea94 lldb-debugging2.kexe`kfun:greet1(kotlin.String) at Sample.kt:7
    frame #1: 0x000000010680ea5a lldb-debugging2.kexe`kfun:main() at Sample.kt:21
    frame #2: 0x000000010680ea36 lldb-debugging2.kexe`EntryPointSelector + 6
    frame #3: 0x000000010680e9a7 lldb-debugging2.kexe`Konan_start at start.kt:17
    frame #4: 0x000000010680e921 lldb-debugging2.kexe`Konan_run_start + 113
    frame #5: 0x000000010680e89b lldb-debugging2.kexe`main + 27
    frame #6: 0x00007fff7df39015 libdyld.dylib`start + 1
```
* Continue (`continue` command). Wait until the third breakpoint is hit.
* Do step in.
* You will move to the line 12 (this is the line where block comment starts). **This is wrong!** Backtrace: 
```
(lldb) thread backtrace
* thread #1, queue = 'com.apple.main-thread', stop reason = step in
  * frame #0: 0x000000010680eb84 lldb-debugging2.kexe`kfun:greet2(secondName=0x00007ffee93f96f0) at Sample.kt:12
    frame #1: 0x000000010680ea69 lldb-debugging2.kexe`kfun:main() at Sample.kt:22
    frame #2: 0x000000010680ea36 lldb-debugging2.kexe`EntryPointSelector + 6
    frame #3: 0x000000010680e9a7 lldb-debugging2.kexe`Konan_start at start.kt:17
    frame #4: 0x000000010680e921 lldb-debugging2.kexe`Konan_run_start + 113
    frame #5: 0x000000010680e89b lldb-debugging2.kexe`main + 27
    frame #6: 0x00007fff7df39015 libdyld.dylib`start + 1
```

**Expected Result:**
* Debugger should move to the line which contains `fun` keyword.

**Comment by vvlevchenko** [comment]
It's frontend's decision what to assume start of the function and we just translate this decision to debug info. So it's definitely request to frontend.

**Comment by vvlevchenko** [comment]
for record: https://youtrack.jetbrains.com/issue/KT-28324

**Comment by ddolovov** [comment]
Not reproduced in Kotlin/Native 1.2-eap-8089.
