### ISSUE TITLE
K/N debugger on Windows

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#2326]
Now Kotlin/Natve works in CLion EAP on Windows, so - what should be used as debugger?
- gdb from msys2-mingw works only for breakpoints and primitive types inspections,
- llvm from msys2-mingw does not work:
```
C:\msys64\mingw64\bin\lldb.exe: unknown option -- interpreter=mi2
error: unknown or ambiguous option

Process finished with exit code 0
```
and anyway it is useless:
```
(lldb) script
error: your copy of LLDB does not support scripting.
```

**Comment by msink** [comment]
Well, now `lldb-1-windows` is available on current master, so I can try debugging.
Lets try as steps from DEBUGGING.md:

```
msink@Sinkovsky MINGW64 /f/src/kotlin-native
$ /f/work/.konan/dependencies/lldb-1-windows/bin/lldb main.exe
(lldb) target create "main.exe"
Current executable set to 'main.exe' (x86_64).
b main.kt:5
(lldb) b main.kt:5
Breakpoint 1: where = main.exe`kfun:main() + 269 at main.kt:5:13, address = 0x000000000042be8d
r
(lldb) r
Process 10928 launched: 'F:\src\kotlin-native\main.exe' (x86_64)
Process 10928 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x000000000042be8d main.exe`kfun:main() at main.kt:5:13
   2        var x = 1
   3        var y = 2
   4        var p = Point(x, y)
-> 5        println("p = $p")
                    ^
   6    }
   7    data class Point(val x: Int, val y: Int)
(lldb) fr var
(lldb) fr var
(int) x = 1
(int) y = 2
(ObjHeader *) p = 0x0000000000395978
command script import dist/tools/konan_lldb.py
(lldb) command script import dist/tools/konan_lldb.py
fr var
(lldb) fr var
(int) x = 1
(int) y = 2
(ObjHeader *) p = {}
p p
(lldb) p p
(ObjHeader *) $4 = {}
```

Something wrong here, should be:
```
(ObjHeader *) p = Point(x=1, y=2)
```

**Comment by msink** [comment]
"Native Debugging Support" does not work for me, on Windows10 / IDEA2020.1 / 1.3.70EAP2

<img width="391" alt="proba" src="https://user-images.githubusercontent.com/1785275/74631403-b6091880-517e-11ea-8993-7486aa3febef.png">

**Comment by vvlevchenko** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-45987 basic lldb scenario doesn't work on Windows](https://youtrack.jetbrains.com/issue/KT-45987)
