### ISSUE TITLE
classes do not inherit superclass tests

### ISSUE THREAD

**Issue by AlecStrong** [JetBrains/kotlin-native#2328]
If I have a class `Foo` with a `kotlin.test.Test` annotated method, that method does not get executed with a subclass `Bar` that extends `Foo`

**Comment by AlecStrong** [comment]
also true for `@AfterTest` and `@BeforeTest`

**Comment by ilmat192** [comment]
Does the subclass override the test method? If yes, is this method annotated with `@Test` in the subclass too?

**Comment by AlecStrong** [comment]
the subclass does not override the test method. I can force it to run by overriding it, but thats not the behavior I was expecting (junit will run any superclass methods annotated with `@Test`)

**Comment by ilmat192** [comment]
Hm.. In the latest K/N release (which is included in Kotlin 1.3.10) such test methods are executed. E.g. for the following code both `A.foo` and `B.foo` are executed:
```
import kotlin.test.*

open class A {
    @Test
    fun foo() {
        println("Foo")
    }
}

class B : A()
```

But we don't execute `B.foo` if it is overridden without the `@Test` annotation. That's why I asked about overriding.

What version of Kotlin do you use? Could you provide a link to your project where this issue is observed?

**Comment by AlecStrong** [comment]
I'm using kotlin 1.3.10. I imagine the problem is likely because of the location of the superclass. The structure is like this:

```
project
--moduleA
----src
------nativeTest
--------kotlin
----------com.sample.package
------------TestA.kt
----build.gradle
--moduleB
----src
------commonMain
--------kotlin
----------com.sample.package
------------TestB.kt
----build.gradle
```

`TestB` contains the `@Test` annotated methods, `TestA` inherits from it. The dependency is set up like this (`project/moduleA/build.gradle`):

```
kotlin {
  sourceSets {
    commonMain {
      dependencies {
        implementation deps.kotlin.stdlib.common
      }
    }
    nativeTest {
      dependencies {
        implementation project(':moduleB')
      }
    }
  }
}
```

The error is observed in SqlDelight.
`moduleB` is [driver-test](https://github.com/square/sqldelight/tree/master/drivers/driver-test) with its [TestB](https://github.com/square/sqldelight/blob/master/drivers/driver-test/src/commonMain/kotlin/com/squareup/sqldelight/driver/test/TransacterTest.kt)
`moduleA` is [ios-driver](https://github.com/square/sqldelight/tree/master/drivers/ios-driver) with its [TestA](https://github.com/square/sqldelight/blob/master/drivers/ios-driver/src/nativeTest/kotlin/com/squareup/sqldelight/drivers/ios/IosTransacterTest.kt) that inherits from TestB

**Comment by ilmat192** [comment]
Thank you for the links and the description! I'll take a closer look at the problem.

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/2453.

**Comment by AlecStrong** [comment]
thank you!
