### ISSUE TITLE
framework with K/N class which inherits from NSObject

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#2330]
E.g.  this is K/N part.

```
class MyObject: NSObject {
    @OverrideInit constructor() : super()
}
```

Objc/swift app should be able to use `MyObject`. However, it's not visible since the class is not listed in framework headers. 

Is there a way to achieve something like that?

**Comment by SvyatoslavScherbina** [comment]
Such classes aren't exposed through framework APIs currently.
What are you trying to achieve?

**Comment by ildarsharafutdinov** [comment]
I want to reduce the volume of swift/objc code to bare minimum. However, I want to keep Xcode project(and the function `main`) in order to avoid complexity with app signing/extensions/other apple specific stuff.

So the idea was to move `UIApplicationDelegate` implementation to the framework and use it in `main` function. Since `NSObject` successors are not exported from the framework I ended up with 2 AppDelegates:
- objc implementation inherits `UIApplicationDelegate` and forwards calls to K/N
- K/N implementation receives calls and does actual work

If K/N successors of `NSObject` were exported from the framework, it would be possible to get rid of the extra wrapper.

**Comment by ildarsharafutdinov** [comment]
@SvyatoslavScherbina ,

Thank you.

However, I didn't manage to make it work.

```
@ExportObjCClass("MyUIApplicationDelegate")
actual class AppDelegate: UIApplicationDelegateProtocol, UIResponder() {

    override fun application(application: UIApplication, didFinishLaunchingWithOptions: Map<Any?, *>?): Boolean {
        window = UIWindow(frame = UIScreen.mainScreen.bounds)
        window?.rootViewController = ViewController(R.strings.message)

        window?.makeKeyAndVisible()

        return true
    }
}
```


```
#import <UIKit/UIKit.h>

int main(int argc, char * argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, @"MyUIApplicationDelegate");
    }
}
```

Above code results in `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to instantiate the UIApplication delegate instance. No class named MyUIApplicationDelegate is loaded.'`

I also tried to add the module/framework name prefix `AllMyUIApplicationDelegate` in main, but the error is the same.

**Comment by SvyatoslavScherbina** [comment]
No prefix is required.
The issue is likely to be caused by that the framework is not initialized yet properly by this moment.
You can call any function from it to force the initialization.

**Comment by SvyatoslavScherbina** [comment]
> However, I was forced to use mainWindow instead of window.

> With window I get unrecognized selector setWindow.

This can be caused by the clash with `AppDelegate.window`.

**Comment by ildarsharafutdinov** [comment]
The error occurs when I use `UIApplicationDelegateProtocol`'s `window`:

```
const val APPLICATION_DELEGATE_CLASSNAME = "ApplicationDelegate"

@Suppress("unused")
@ExportObjCClass(APPLICATION_DELEGATE_CLASSNAME)
actual class AppDelegate : UIApplicationDelegateProtocol, UIResponder {

    @OverrideInit
    constructor() : super()

    override fun application(
            application: UIApplication,
            didFinishLaunchingWithOptions: Map<Any?, *>?
    ): Boolean {

        window = UIWindow(frame = UIScreen.mainScreen.bounds)
        window?.rootViewController = ViewController(R.strings.message)

        window?.makeKeyAndVisible()

        return true
    }
}
```

And this seems to be the only way to use `window`, since its `final`.

The error: 
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ApplicationDelegate setWindow:]: unrecognized selector sent to instance 0x600001094160'
```

**Comment by SvyatoslavScherbina** [comment]
This error means that you have not implemented `window` setter, i.e. `setWindow` method of `UIApplicationDelegateProtocol`.
See [uikit sample](https://github.com/JetBrains/kotlin-native/blob/91463efac8fbe36461b8f0b8400d8ff3d91ccf4b/samples/uikit/src/iosMain/kotlin/main.kt#L23) for proper `UIApplicationDelegateProtocol` implementation.

**Comment by ildarsharafutdinov** [comment]
Ahhh, I need to implement getter and setter for objc property, instead of "implementing" the property.

Thanks.

**Comment by SvyatoslavScherbina** [comment]
You are welcome!
