### ISSUE TITLE
Go back to main thread from a worker [concurrency]

### ISSUE THREAD

**Issue by acecilia** [JetBrains/kotlin-native#2333]
I am trying to perform some asynchronous work in the background and then use the result from main thread. The way I am trying to do it is with workers, as follows:
```
fun backgroundThread(callback: (String) -> Unit) {
    val worker = Worker.start()

    val future = worker.execute(TransferMode.SAFE, { }) {
        // We are in background thread
        NSThread.isMainThread
    }

    future.consume { // <<<<< THIS IS BLOCKING!
        // We are in main thread
        callback("Is main thread: ${it}")
    }

    worker.requestTermination()
}
```

The problem I am having is that I can not find a way to go back to main thread asynchronously: as I marked in the above code, the consume function is blocking the main thread until the worker finishes (see documentation: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native.concurrent/-future/consume.html).

How can I go back to main thread asynchronously, as soon as the worker finishes, without blocking?
Thanks!

**Comment by olonho** [comment]
Which OS is that? For most of them sending OS-specific event to the main thread when task is done shall do.

**Comment by acecilia** [comment]
@olonho I would like to do it with Kotlin, for any OS. Can it be done with the Workers?

**Comment by olonho** [comment]
Solution shall be platform-dependent, Kotlin/Native is not Java-style WORA solution, but aims to tight platform integration.

**Comment by ildarsharafutdinov** [comment]
@olonho,

 > sending OS-specific event to the main thread when task is done shall do

 Could you explain what you mean a bit more?

As far as I understand `event to the main thread` is not supposed to be sent from the `job` lambda. Also `consume` blocks the main thread(the calling side), thus an "async event" makes no sense.

Its probably possible to check future state periodically or call `waitForMultipleFutures` from time to time.

But is there a better solution?

**Comment by SvyatoslavScherbina** [comment]
Generally native-mt branch of kotlinx.coroutines covers this case, and it is the recommended solution at the moment.
See https://github.com/Kotlin/kotlinx.coroutines/issues/462 for more details ([tl;dr](https://github.com/Kotlin/kotlinx.coroutines/issues/462#issuecomment-698077907))
