### ISSUE TITLE
Multiplatform K/N compiler crashes with an IllegalStateException

### ISSUE THREAD

**Issue by serebit** [JetBrains/kotlin-native#2343]
Kotlin: `1.3.0` (also fails with `1.3.10`)
Gradle: `5.0-rc-3` (also fails with `4.10.2`)
Konan: `1.0.1` (also fails with `1.0.2`)

In [this project](https://gitlab.com/serebit/logkat/tree/0.4.3), when attempting to build all modules, the Konan compiler crashes during the `compileKotlinLinux` stage. The basic message given is `error: compilation failed: org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl@4be7acd9`, along with a full (and lengthy) stack trace. The JVM module compilation succeeds, and IntelliJ's linter shows no problems with the code.

I attempted to minimize the issue, but even after changing all the functions and values in the linuxMain module to stubs, the build continued to fail. The build also fails on GitLab CI, which means it can't be a local issue with my installation. You can see the full result of a clean build at https://gitlab.com/serebit/logkat/-/jobs/122080780.

**Comment by homuroll** [comment]
Will be fixed with https://github.com/JetBrains/kotlin-native/pull/2357.

**Comment by homuroll** [comment]
Fixed in master.
