### ISSUE TITLE
Seperate Samples from main project

### ISSUE THREAD

**Issue by Tadaboody** [JetBrains/kotlin-native#2346]
I'd like the option to clone and work on individual samples, without having to clone the whole repository and vise-versa: Work on the repository without having to clone and update all of the samples. I think [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) will be a great fit for this

**Comment by SvyatoslavScherbina** [comment]
Thank you for the suggestion. We have plans to reorganize our samples, including moving them to other repositories.
