### ISSUE TITLE
[ POSIX ] struct sigaction : member sa_handler is immutable. Why? 

### ISSUE THREAD

**Issue by harlem88** [JetBrains/kotlin-native#2365]
val sa: sigaction = nativeHeap.alloc() 
 **sa.__sigaction_handler = staticCFunction(::handler)** //val member
 sigaction(SIGALRM, sa.ptr , null)

**Comment by olonho** [comment]
Which platform and Kotlin version is that?

**Comment by olonho** [comment]
Full Kotlin translation in current master is as following:
``
class sigaction(rawPtr: NativePtr) : CStructVar(rawPtr) {
    
    companion object : Type(152, 8)
    
    val __sigaction_handler: anonymousStruct15
        get() = memberAt(0)
    
    val sa_mask: __sigset_t
        get() = memberAt(8)
    
    var sa_flags: Int
        get() = memberAt<IntVar>(136).value
        set(value) { memberAt<IntVar>(136).value = value }
    
    var sa_restorer: CPointer<CFunction<() -> Unit>>?
        get() = memberAt<CPointerVar<CFunction<() -> Unit>>>(144).value
        set(value) { memberAt<CPointerVar<CFunction<() -> Unit>>>(144).value = value }
    
}

class anonymousStruct15(rawPtr: NativePtr) : CStructVar(rawPtr) {
    
    companion object : Type(8, 8)
    
    var sa_handler: __sighandler_t?
        get() = memberAt<__sighandler_tVar>(0).value
        set(value) { memberAt<__sighandler_tVar>(0).value = value }
    
    var sa_sigaction: CPointer<CFunction<(Int, CPointer<siginfo_t>?, COpaquePointer?) -> Unit>>?
        get() = memberAt<CPointerVar<CFunction<(Int, CPointer<siginfo_t>?, COpaquePointer?) -> Unit>>>(0).value
        set(value) { memberAt<CPointerVar<CFunction<(Int, CPointer<siginfo_t>?, COpaquePointer?) -> Unit>>>(0).value = value }
    
}
``
and it is correct. One cannot set `sa_handler` directly, what shall be done is to use either
`sigaction.__sigaction_handler. sa_sigaction` or `sigaction.__sigaction_handler. sa_handler` depending on desired signature.

**Comment by harlem88** [comment]
Ahhh, Ok! Great!

Thanks.
