### ISSUE TITLE
Variables named double or long cannot compile

### ISSUE THREAD

**Issue by AlecStrong** [JetBrains/kotlin-native#2371]
I have a method `bindDouble(index: Int, double: Double)` and am compiling for a ios framework file

the generated `.h` file has
`- (void)bindDoubleIndex:(int32_t)index double:(MPPDouble * _Nullable)double __attribute__((swift_name("bindDouble(index:double:)")));
`

it errors on the second double here: `double:(MPPDouble * _Nullable)double` saying `Expected identifier`

**Comment by SvyatoslavScherbina** [comment]
@sandwwraith current issue is different from that one: it doesn't require mangling any parts of user-visible API, only parameter names are incorrect in this case.
