### ISSUE TITLE
IOS tests and info.plist

### ISSUE THREAD

**Issue by Dkhusainov** [JetBrains/kotlin-native#2426]
Currently when running ios test with command `xcrun simctl spawn iPhone 8 text.kexe` generated `test.kexe.DYSM/Contents/info.plist` desn't affect the test environment in any way. Is it supposed to work or do we have to find some other way to run tests with modified `info.plist`?

**Comment by SvyatoslavScherbina** [comment]
Could you provide an example of `test.kexe.DYSM/Contents/Info.plist` property that should affect the test environment? This is `.plist` file for debug symbols bundle, not for the binary itself.

**Comment by Dkhusainov** [comment]
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

I'm trying to do a test with netowrk, and it fails because by default IOS doesn't allow unsecure(or old ssl vertions, or not trusted cert) connnections. I'm not expert at IOS, maybe there is some other way to bypass it

**Comment by SvyatoslavScherbina** [comment]
`NSAppTransportSecurity` looks like a key that should be included into `Info.plist` of the binary itself. What happens if you create a bundle with `text.kexe` and proper `Info.plist`, and then run the binary from this bundle with `xcrun simctl spawn`?

**Comment by Dkhusainov** [comment]
Okay. I'll try this some time later when I have the time. Don't close the issue for now

**Comment by SvyatoslavScherbina** [comment]
You can try this Gradle task proposed by Aleks Nestserau:

```gradle
task iosTest {
    def device = project.findProperty("iosDevice")?.toString() ?: "iPhone 8"
    dependsOn 'linkTestDebugExecutableIos'
    group = JavaBasePlugin.VERIFICATION_GROUP
    description = "Runs tests for target 'ios' on an iOS simulator"

    doLast {
        def binary = kotlin.targets.ios.compilations.test.getBinary('EXECUTABLE', 'DEBUG')
        def infoPlistSrc = file("$rootProject.projectDir/src/iosTest/resources/Info.plist")
        def infoPlistDest = file("$binary.parentFile/Info.plist")

        Files.copy(infoPlistSrc.toPath(), infoPlistDest.toPath(), StandardCopyOption.REPLACE_EXISTING)

        exec {
            commandLine 'export', 'SIMCTL_CHILD_CFNETWORK_DIAGNOSTICS=3'
            commandLine 'xcrun', 'simctl', 'spawn', device, binary.absolutePath
        }
    }
}
```

**Comment by ilmat192** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-37818](https://youtrack.jetbrains.com/issue/KT-37818) which describes test resources as a more general feature.
