### ISSUE TITLE
how `[NSObject class]` is mapped to kotlin?

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#2427]
hi,

how `[NSObject class]` is mapped to kotlin?

there used to be `*.klib` in `~/.konan`, but not any more.
where can I find platform libs sources?

**Comment by SvyatoslavScherbina** [comment]
You can examine platform libraries (located in `$KONAN_HOME/klib`) with `klib contents` command.
`[NSObject class]` is mapped to `NSObject` companion object.

**Comment by SvyatoslavScherbina** [comment]
`NSObject` can be found in `darwin` platform library which is located e.g. at
`~/.konan/kotlin-native-macos-1.0.2/klib/platform/ios_arm64/darwin`.
