### ISSUE TITLE
run kotlin-native Binary on android but got "Segmentation fault"

### ISSUE THREAD

**Issue by xuanjiazhen** [JetBrains/kotlin-native#2428]
I use kotlinc-native on Linux(ubuntu x86-64) to compile android(arn64 os:android P) targets binary.
Then I push the binary onto android and execute them in the shell by adb.
I only got "Segmentation fault" without any more details.
```
$ kotlinc-native -version
info: kotlinc-native 1.3.0-rc-190 (JRE 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
Kotlin/Native: 1.0.2
```

**Comment by olonho** [comment]
K/N produces native activity, unlikely it could be run directly from adb, please check https://github.com/JetBrains/kotlin-native/tree/master/samples/androidNativeActivity

**Comment by olonho** [comment]
No feedback, closing, please reopen if more info available.
