### ISSUE TITLE
Kotlin iOS compile fails when expect/actual fun fails with a suspend function as a parameter

### ISSUE THREAD

**Issue by HaukeRa** [JetBrains/kotlin-native#2431]
Demo project:
https://github.com/HaukeRa/KotlinMultiplatformTest

A method with this signature: `
expect fun expectFunctionWithSuspendFunctionParameter(cb: (suspend (Any) -> Unit)): SendChannel<Any>`
Fails to compile for iOS in a multiplatform project. On the JVM target it works fine.

Compilation fails with

> shared/src/commonMain/kotlin/com/example/kotlindemo/Demo.kt:6:80: error: type mismatch: inferred type is KSuspendFunction1<@ParameterName Any, Unit> but suspend (Any) -> Unit was expected
private val act: SendChannel<Any> = expectFunctionWithSuspendFunctionParameter(::receiveEvent)

**Comment by SvyatoslavScherbina** [comment]
Thank you for the detailed report.
Please replace `::receiveEvent` by `{ receiveEvent(it) }` to workaround the issue.
https://github.com/HaukeRa/KotlinMultiplatformTest/blob/master/shared/src/commonMain/kotlin/com/example/kotlindemo/Demo.kt#L8

Kotlin/Native doesn't support references to suspend functions yet.

**Comment by HaukeRa** [comment]
Thanks for the quick response. 

That did it (almost). For others coming here:
Applying your workaround gives
> MultiplatformTest\shared\src\commonMain\kotlin\com\example\kotlindemo\Demo.kt: (6, 95): This syntax is reserved for future use; to call a reference, enclose it in parentheses: (foo::bar)(args)

When applying the compiler's suggestion, it gives me:
> shared/src/commonMain/kotlin/com/example/kotlindemo/Demo.kt:6:81: error: expression '(::receiveEvent)' of type 'KSuspendFunction1<@ParameterName Any, Unit>' cannot be invoked as a function. The function 'invoke()' is not found
private val act: SendChannel<Any> = expectFunctionWithSuspendFunctionParameter({(::receiveEvent)(it)})

What you probably ment (and what works) is invoking the function directly within the lambda, and omitting the function reference completely like this: 

`expectFunctionWithSuspendFunctionParameter({receiveEvent(it)})`
