### ISSUE TITLE
IncorrectDereferenceException without using top level variables

### ISSUE THREAD

**Issue by Coneys** [JetBrains/kotlin-native#2443]
I was trying to use Kotlin/Native to share data models between iOS and Android app, but when I use my models from Swift, accesing it throws IncorrectDereferenceException:
`DispatchQueue.global(qos: .background).async {
            let mem = Mem(id: 0, sequence: 0, text: "test", text_x: 0.5, text_y: 0.5)
            DispatchQueue.main.async {
                print("Text: \(mem.text)")
            }
        }`

I know that I can freeze my variable, but I have to change it sometime later. How can I pass thread ownership of this object? I know this is possible by Kotlin/Native Workers, but can I do it with iOS Queue?

**Comment by olonho** [comment]
There's not much difference here. See https://github.com/JetBrains/kotlin-native/blob/328413337b9dcab1dba6dd4d3cf5975d617e60d1/samples/objc/src/objcMain/kotlin/Window.kt#L20 - in this example we pass an object created with producer, and as result it's guaranteed to not have other references. Other approach is to use smth like

```data class Input(var int: Int)

class Box<T>(boxed: T) {
    private var value_: T? = boxed
    val value: T get() {
        val result = value_!!
        value_ = null
        return result
    }
}

inline fun <reified T, reified R> Worker.executeAsync(data: Box<T>, crossinline consumerMaker: () -> ((T) -> R)): Future<R> =
        execute(TransferMode.SAFE, {
        Pair(data.value, consumerMaker())
    }) { it -> it.second(it.first) }

fun main() {
    val worker = Worker.start()
    val boxedInput = { Box(Input(42)) } ()
    val future = worker.executeAsync(boxedInput) { { input: Input ->
        input.int++
        input
    } }
    println(future.result)
}```

**Comment by Coneys** [comment]
Thanks for your response. I tried example with Boxing, but the case is, I need to use concurrency in Swift (DispatchQueue) and I have no idea how to connect it with passing ownership. You did this using Worker api inside of Kotlin, which does it for you, right? With TransferMode. 

I've read that I can do it manually using DetachedObjectGraph, is this right? Swift cannot see this class, so I did implement it with using expected and actual keywords. Then I created DetachedObjectGraph on background thread, but when I tried to receive value from it on main thread with attach() method, code threw IncorrectDereferenceException

**Comment by olonho** [comment]
Not with the current concurrency model, however we are evaluating possibilities of adding more options here.

**Comment by rawadhilal88** [comment]
Adding more concurrency model options would be great. This is currently blocking us from using Kotlin for iOS. Our use cases work for Kotlin JVM/Android and Kotlin JS. Until there's an easy way of sharing mutable objects between threads 
on iOS we cannot support Kotlin native. Our customers heavily use the iOS dispatch queue and we can't limit them because we simply decided to use Kotlin to build our SDKs.

**Comment by Reedyuk** [comment]
Is there any update on when this might be changed? It's an absolute blocker for me.

**Comment by Coneys** [comment]
Same here, we would love to share code between iOS and Android, but for now it is too expensive (in time measure). It is faster to write code twice ;(

**Comment by nbransby** [comment]
August now and still no word on "evaluating possibilities of adding more options here"?

**Comment by soundbites** [comment]
We are having the same issue, but all our state is immutable. So a read only object accessible in Swift background threads would work as well.

**Comment by kar** [comment]
Any updates on this? Is there no way to use freeze() in Kotlin MPP?

**Comment by kar** [comment]
What I'm trying to do is to execute a function on another (non main) thread in iOS. No mutable state. Could someone give a basic example on how to do so?

**Comment by SvyatoslavScherbina** [comment]
About our plans: https://blog.jetbrains.com/kotlin/2020/07/kotlin-native-memory-management-roadmap/
YouTrack issue: https://youtrack.jetbrains.com/issue/KT-42296

There are a lot of articles and discussions in the internet. For example, see the topic in KMM documentation: https://kotlinlang.org/docs/mobile/concurrency-overview.html.
Also there is public Kotlin Slack (visit http://slack.kotlinlang.org/ if you don't have access yet), channels `#kotlin-native` and `#multiplatform` are relevant. 

Asking for help here, in this issue, is generally inefficient.
