### ISSUE TITLE
TargetSupportException zephyr_stm32f4_disco

### ISSUE THREAD

**Issue by jwoolston** [JetBrains/kotlin-native#2447]
Trying to setup a project with the gradle plugin, I am receiving a TargetSupportException for `zephyr_stm32f4_disco`. 

Plugin version is `1.3.11`
I will spare you the rather verbose stack trace, but the reported error is: 

>What went wrong:
A problem occurred evaluating root project 'kotlin-native-gradle'.
Unknown target name: zephyr_stm32f4_disco

The gradle script I am trying to use is basically just trying to build the zephyr blinky example. I have failed at numerous attempts to build using the shell scripts due to a variety of failures. 

```gradle
plugins {
    id "org.jetbrains.kotlin.platform.native" version "1.3.11"
}

ext.ZEPHYR_BASE = '/home/jared/Zephyr-Development/zephyr'
ext.BOARD = 'stm32f4_disco'

sourceSets.main {
    // Platform independent sources
    kotlin.srcDirs += 'src/main/kotlin'
}

components.main {


    // Set up targets
    targets = ["zephyr_$BOARD".toString()]

    // Set up output kinds
    outputKinds = [EXECUTABLE]

    // Specify custom entry point for executables
    entryPoint = "sample.Main"

    allTargets {

    }

    dependencies {

        // cinterop dependency
        cinterop("$BOARD") {
            // Def-file describing the native API
            // The default path is src/main/c_interop/<interop-name>.def
            defFile project.file("src/main/c_interop/${BOARD}.def")

            // Package to place the Kotlin API generated
            packageName "platform.zephyr.$BOARD"

            // Options to be passed to the compiler and linker by the cinterop tool
            compilerOpts '-Xclang -DSTM32F407xx'
            includeDirs "$ZEPHYR_BASE/kernel/include", "$ZEPHYR_BASE/arch/arm/include",
                    "$ZEPHYR_BASE/soc/arm/st_stm32/stm32f4", "$ZEPHYR_BASE/soc/arm/st_stm32/common",
                    "$ZEPHYR_BASE/boards/arm/$BOARD", "$ZEPHYR_BASE/include",
                    "$ZEPHYR_BASE/include/drivers", "$ZEPHYR_BASE/ext/hal/cmsis/Include",
                    "$ZEPHYR_BASE/ext/hal/st/stm32cube/stm32f4xx/soc",
                    "$ZEPHYR_BASE/ext/hal/st/stm32cube/stm32f4xx/drivers/include",
                    "$ZEPHYR_BASE/ext/hal/st/stm32cube/stm32f4xx/drivers/include/Legacy",
                    "$ZEPHYR_BASE/drivers", "$projectDir/build/zephyr/include/generated",
                    "$projectDir/build/zephyr/include/generated/syscalls"
        }
    }
}

task ninjaBuild(type: Exec) {
    errorOutput = System.out
    ignoreExitValue = false
    workingDir projectDir
    commandLine("./ninjaBuild.sh", "$ZEPHYR_BASE", "$BOARD")
}
```

I've taken a look at #1379 but there has been a large version difference since then. This seems to happen if I don't specify `konan.home` in the project's `gradle.properties`, as well as if I set it to a downloaded version or a built from source version.

The output of `konanc -list-targets` is as follows:

>jared@jared-laptop-ubuntu:~/GIT/kotlin-native/dist/bin$ ./konanc -list-targets
linux_x64:                    (default) linux
linux_arm32_hfp:                        raspberrypi
linux_mips32:                           
linux_mipsel32:                         
android_arm32:                          
android_arm64:                          
wasm32:                                 
zephyr_stm32f4_disco:          

At this point I am wondering if I am missing something in my host machine that is making the `zephyr_stm32f4_disco` target not be supported dynamically? I have a large "for fun" project I was hoping to use this for and expand support in both zephyr and kotlin native for more of the STM32F4 features as needed if I can get this to work.

**Comment by msink** [comment]
It's not supported in gradle plugin, only in `konanc`.

**Comment by jwoolston** [comment]
@msink Thankyou for the clarification there. Since that is the case, can you perhaps enlighten me on why I can't get the samples to build on the command line? I have done my best to update the scripts for each failure and ultimately come up with this:

>[39/39] Linking C static library zephyr/libzephyr.a
logging: using Kotlin home directory /home/jared/kotlin-native/konan
/home/jared/Zephyr-Development/kotlin-zephyr/src/main.kt:11:16: error: unresolved reference: LED0_GPIO_PORT
    val port = LED0_GPIO_PORT
               ^
/home/jared/Zephyr-Development/kotlin-zephyr/src/main.kt:16:29: error: type mismatch: inferred type is Int but u32_t /* = UInt */ was expected
    gpio_pin_configure(dev, led, GPIO_DIR_OUT)
                            ^
/home/jared/Zephyr-Development/kotlin-zephyr/src/main.kt:20:30: error: type mismatch: inferred type is Int but u32_t /* = UInt */ was expected
         gpio_pin_write(dev, led, if (toggler) 1 else 0);
                             ^
/home/jared/Zephyr-Development/kotlin-zephyr/src/main.kt:20:48: error: the integer literal does not conform to the expected type u32_t /* = UInt */
         gpio_pin_write(dev, led, if (toggler) 1 else 0);
                                               ^
/home/jared/Zephyr-Development/kotlin-zephyr/src/main.kt:20:55: error: the integer literal does not conform to the expected type u32_t /* = UInt */
         gpio_pin_write(dev, led, if (toggler) 1 else 0);
                                                      ^
When I look at the generated `stm32f4_disco.kt` file, I see that it does not contain `LED0_GPIO_PORT` but does contain `LED0_GPIO_CONTROLLER`. I have made some modifications (using the `LED0_GPIO_CONTROLLER` and casting values to `UInt`) and gotten past these errors but I'm starting to run into issues between me using the zephyr sdk vs the GNU ARM. 

I am interested in getting all this updated so it can be working again if it would be welcomed, but I will almost certainly need some guidance. Is this mostly a matter of things moved on and this wasn't kept up to date or is there some reason why the zephyr sdk cant be used? Does the plugin not support this target due to being un-implemented or is there some larger reason?

**Comment by msink** [comment]
I too had almost same result when tried to compile zephyr sample a month ago. It took almost five minutes to compile!

Guess just no one interested in this - too slow and too bad result. Untill there will be significant result in optimizations area - it's almost unusable anyway.

**Comment by jwoolston** [comment]
Yes this is unfortunate. I can live with the execution time for now if it worked. Via a combination of ninja and referencing the libsupc++.a lib in the GNU ARM libraries, I was able to get to the point of being able to flash a board. When I did the Zephyr console spams this: 

> ***** Booting Zephyr OS zephyr-v1.13.0-2451-g691e1170c1 *****
***** USAGE FAULT *****
  No coprocessor instructions
***** Hardware exception *****
Current thread ID = 0x200008c0
Faulting instruction address = 0x801d2e2
Fatal fault in thread 0x200008c0! Aborting.
***** USAGE FAULT *****
  Illegal load of EXC_RETURN into PC

Progress I suppose, but not what I was hoping for.

**Comment by jwoolston** [comment]
@msink I know you have put some work into this yourself, are you in any of the more general communications channels and interested in bouncing some ideas back and forth as I chip away at this?

**Comment by msink** [comment]
On my side it was just experiment - and for me result was that it's possible in theory, but almost unusable in practice, as I said above - ultil/if there will be significant improvements in the compiler.

So for now I'm not interested in this, sorry.

**Comment by jwoolston** [comment]
No problem, thanks for confirming the state of things.

**Comment by jwoolston** [comment]
I am closing this issue since it the plugin is known to not support the STM32 target.
