### ISSUE TITLE
I want to help with STM32 Zephyr support

### ISSUE THREAD

**Issue by jwoolston** [JetBrains/kotlin-native#2449]
I know that the STM32 zephyr support is limited at present and it is likely largely due to lack of demand. I have a substantial interest in using kotlin on STM32 and similar targets and would be more than happy to help develop/test related to this target. I took a look at https://youtrack.jetbrains.com/issues/KT?p=100&q=%23Unresolved%20tag:%20%7BUp%20For%20Grabs%7D&f=false and did not see anything outstanding. Is there interest in this and if so, where do I start?

**Comment by olonho** [comment]
Probably the simples approach would be to develop an nontrivial sample functional on STM32 and prepare sysroot with Zephyr suitable for usage with such a demo.

**Comment by msink** [comment]
Then maybe first fix current trivial sample, and make pull request.

**Comment by jwoolston** [comment]
@msink I was able to get them running on my machine after some updates. I don't think it was strictly necessary but I converted them to use ninja since that is what zephyr is recommending in their getting started. I will submit a PR shortly. I also built your changes (just the Porting.cpp) for hello world to get the `println()` functionality locally against `master`

**Comment by jwoolston** [comment]
Closing this issue since there is some traction on other more specific conversations.
