### ISSUE TITLE
Memory leak when reading files while a regex variable is defined

### ISSUE THREAD

**Issue by jush** [JetBrains/kotlin-native#2465]
Please find a repository with code to reproduce the issue at [https://github.com/jush/regex_memory_leak](https://github.com/jush/regex_memory_leak).

The issue is that the Kotlin native program exits with error message:

`/opt/teamcity-agent/work/4d622a065c544371/runtime/src/main/cpp/Memory.cpp:1150: runtime assert: Memory leaks found`

The conditions for that to happen are the following:

* Declare a top level variable that uses `toRegex()` (see [Application.kt#L12](https://github.com/jush/regex_memory_leak/blob/master/src/nativeMain/kotlin/Application.kt#L12))
* Read a file with more than 4000 lines using posix functions (see [Application.kt#L27](https://github.com/jush/regex_memory_leak/blob/master/src/nativeMain/kotlin/Application.kt#L27))

If one of the two above conditions are removed the program exits properly.

The machine where I'm seeing this behaviour is a `MacBook Pro (15-inch, 2018), 2,6 GHz Intel Core i7 and 32 GB 2400 MHz DDR4` although in another project we see the exact same behaviour also in Windows.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/2469 shall fix it

**Comment by kavanmevada** [comment]
"Reg Exr "was created by gskinner.com, and is proudly" hosted by Media Temple.".replace("\\s(?=(\"[^\"]*\"|[^\"])*\$)".toRegex(), "")

Memory leak :
/opt/teamcity-agent/work/4d622a065c544371/runtime/src/main/cpp/Memory.cpp:1150: runtime assert: Memory leaks found
