### ISSUE TITLE
Are there hash functions

### ISSUE THREAD

**Issue by SBNTT** [JetBrains/kotlin-native#2466]
Hi,

I've a simple question.
I need to use some hashing methods in my project (such as SHA256).

Are there some of them implemented ?
If no, can i have some advices on how to achieve that ?

Thaanks

**Comment by olonho** [comment]
It's not part of the standard library, however on Apple platforms you can use CommonCrypto, i.e.

```import kotlinx.cinterop.*
import platform.CoreCrypto.CC_SHA256
import platform.CoreCrypto.CC_SHA256_DIGEST_LENGTH

fun main() {
    val input = "Hi Kotlin".toUtf8()
    val digest = UByteArray(CC_SHA256_DIGEST_LENGTH)
    input.usePinned { inputPinned ->
        digest.usePinned { digestPinned ->
            CC_SHA256(inputPinned.addressOf(0), input.size.convert(), digestPinned.addressOf(0))
        }
    }
    val digestString = digest.joinToString(separator = "") { it -> it.toString(16) }
    println(digestString)
}```

**Comment by SBNTT** [comment]
Hi,

Thanks for this snippet !

What about if i want to made it usable for others platforms ?
Do i need to cinterop something like openssl ?

**Comment by SBNTT** [comment]
by saying 

> add self-containing hashing code to the .def file

Did you mean adding directly an implementation in C to into the .def file ? Like in [INTEROP.md](https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#adding-custom-declarations)

**Comment by SBNTT** [comment]
I've done it by compiling c code to a static .a library, then linking it statically in the .def file using staticLibraries and libraryPaths params.

**Comment by davidbarkhuizen** [comment]
Guys, we need proper hash functions in the standard library for Android, compiling in external includes is not a reasonable solution.

**Comment by r4zzz4k** [comment]
I suggest you to visit https://kotl.in/slack, specifically **#stdlib**, as that should be a better place to discuss additions to standard library than repository for specific Kotlin backend.

**Comment by Rjmaurya13** [comment]
HI @olonho , Can you please help me to convert this function to use in Kotlin Multiplatform.

var rsa2048Asn1Header:[UInt8] = [
        0x30, 0x82, 0x01, 0x22, 0x30, 0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86,
        0xf7, 0x0d, 0x01, 0x01, 0x01, 0x05, 0x00, 0x03, 0x82, 0x01, 0x0f, 0x00
    ]
   
    func sha256(_ data : Data) -> String {
        var keyWithHeader = Data(bytes: rsa2048Asn1Header)
        keyWithHeader.append(data)
        var hash = [UInt8](repeating: 0,  count: Int(CC_SHA256_DIGEST_LENGTH))
        keyWithHeader.withUnsafeBytes {
            _ = CC_SHA256($0, CC_LONG(data.count), &hash)
        }
        return Data(bytes: hash).base64EncodedString();
    }
    
I will really appreciate your help. #

**Comment by artdfel** [comment]
Hello @Rjmaurya13! There are two different approaches that one can apply here. First, if you want to make this function available as a part of the Multiplatform library, you can write your implementation in pure Kotlin.  Or, maybe already existing library can make sense here - have a look at [krypto](https://github.com/korlibs/krypto) for example. 
In the second option, I will assume that, as we are in the Kotlin/Native GH issue tracker, you want to write something in K/N. If so, one got to use platform-specific libraries - this approach was illustrated above. Also, on this option, I know an interesting [thread](https://kotlinlang.slack.com/archives/C3SGXARS6/p1541771174265700) in the Kotlin Slack. 
And I strongly recommend asking such questions in the Slack.

**Comment by Rjmaurya13** [comment]
I found a way to do this. It's working in Kotlin Multiplatform.
```
private fun sha256(data : NSData) : String {
                var rsa2048Asn1Header = byteArrayOf(0x30.toByte(), 0x82.toByte(), 0x01.toByte(),
0x22.toByte(), 0x30.toByte(), 0x0d.toByte(), 0x06.toByte(), 0x09.toByte(), 0x2a.toByte(),
0x86.toByte(), 0x48.toByte(), 0x86.toByte(), 0xf7.toByte(), 0x0d.toByte(), 0x01.toByte(),
0x01.toByte(), 0x01.toByte(), 0x05.toByte(), 0x00.toByte(), 0x03.toByte(), 0x82.toByte(),
0x01.toByte(), 0x0f.toByte(), 0x00.toByte())

                rsa2048Asn1Header += data.toByteArray()
                val input = rsa2048Asn1Header

                val digest = UByteArray(CC_SHA256_DIGEST_LENGTH)
                input.usePinned { inputPinned ->
                    digest.usePinned { digestPinned ->
                        CC_SHA256(inputPinned.addressOf(0), input.size.convert(), digestPinned.addressOf(0))
                    }
                }
                val digestString = digest.joinToString(separator = "") { it -> it.toString(16) }
                return digestString
 }
```
