### ISSUE TITLE
ObjC - Naming conflicts when classes have the same name 

### ISSUE THREAD

**Issue by platoblm** [JetBrains/kotlin-native#2467]
Classes in kotlin common, that have the same name but are in different packages, are compiled to ObjC with their simple names and the addition of underscores.
```
For example:
com.example.first.View
com.example.second.View
com.example.third.View

will be compiled in ObjC to:
View
View_
View__
```
We are seeing this in a project that uses the mutliplatform gradle plugin, similar to [this repo](https://github.com/platoblm/kn-objc-name-conflicts). Is there maybe a compiler-option to include the package in the names of the generated ObjC classes and avoid the underscores?  

At the moment we're trying to keep all names unique with the help of typealiases, but even a temporary workaround would be really helpful. Thanks!

**Comment by StefMa** [comment]
ObjC doesn't have the feature of "packages" or something.
At the end of the day all classes needs unique names. Otherwise there would be a compiler error.

Having the package name in the class names are very ... strange, no? 
I mean, do you want to call (from ObjC site) the class `com.example.first.View` (when its possible with dots as classnames.. otherwise it would be `comexamplefirstView` 😅 ).

Why are you against the underscores? 🤔

**Comment by SvyatoslavScherbina** [comment]
Btw, we consider underscores temporary solution.

@StefMa I agree that class names with package prefixes are quite clumsy.

@platoblm how do you use these `View` classes from Kotlin?

**Comment by platoblm** [comment]
Indeed ObjC doesn't help much with that! :) The main issue with the trailing underscores is that the ObjC names are not very predictable, which makes things tricky when we try to auto generate source that will work with those ObjC classes.

Apple's [swift-protobuf](https://github.com/apple/swift-protobuf) and [grpc-swift](https://github.com/grpc/grpc-swift) are addressing that by adding the whole proto package to the name by default (so the above would be ``Com_Example_First_View``). See [here](https://github.com/grpc/grpc-swift/blob/master/Sources/Examples/Echo/Generated/echo.grpc.swift) for an example. Not ideal, but at the end of the day it might be a decision between having unique and so longer names and reduced readability in kotlin, or having longer names in ObjC/Swift. It's probably difficult to find a  perfect solution given the lack of packages in ObjC.

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-42249
