### ISSUE TITLE
Default linker options

### ISSUE THREAD

**Issue by cy6erGn0m** [JetBrains/kotlin-native#2472]
Currently a library developer that need cinterop should provide a list of compiler/linker lookup paths for `-I`, `-L` and so on. Unfortunately different Linux distributions use different paths conventions. For example, depending on a distro `/usr/lib` could contain 32bit or 64bit binaries. Debian-based distributions (like Ubuntu) typically contains 64bit binaries at `/usr/lib`. On the contrary in most RPM-based distributions 64bit binaries are placed at `/lib64` and `/usr/lib64`.

In our examples we suggest users to provide the following options: [samples/libcurl/src/nativeInterop/cinterop/libcurl.def:4](https://github.com/JetBrains/kotlin-native/blob/master/samples/libcurl/src/nativeInterop/cinterop/libcurl.def#L4) that seems to cover this problem but it is for sure unreliable. The worse is that all library developers need to copy-paste this string and not all developers understand what it actually does and there are still questions. For example, it `/usr/lib64` is specified so is `/usr/lib` included (by default?) or not? If yes then what are paths priorities? It is not exactly clear, is this string simply added to the list of linked options or replaces the default? 

I believe that this is serious enough k/n libraries portability issue. Reasons are the following:
- library developers need to know everything about all potential user's platforms and copy-paste the same solutions for other libraries (solutions that are probably wrong too in some cases)
- library users need to override linked options manually if they are not provided properly by the developer otherwise it could lead to errors that look unlcear to unexperienced users (for example `error: /usr/lib/libcurl.so is incompatible with /home/cy/.konan/dependencies/target-gcc-toolchain-3-linux-x86-64/x86_64-unknown-linux-gnu/sysroot/usr/lib64/crt1.o`)

Questions are:
- if there is a reasonable default, why don't we use it out of the box for particular platforms? 
- shouldn't we replicate (entirely or partially) libtool/confiugre/autoconf functionality in our plugin?

**Comment by msink** [comment]
I think it should use `pkg-config` info somehow.

**Comment by olonho** [comment]
Nobody prevents passing output of `pkg-config` via Gradle as compiler/linker options.

**Comment by cy6erGn0m** [comment]
The problem is that it is required to do at library use side and nobody knows about pkg-config/libtool and so on

**Comment by cy6erGn0m** [comment]
@msink well, on my machine

```bash
$ pkg-config libcurl --libs
-lcurl
$ pkg-config sdl --libs
-lSDL -lpthread
```

**Comment by msink** [comment]
Hm, yes - on Linux in native compilation mode `pkg-config` skips the -I/-L options that refer to system directories - listed in `libtool --config | grep sys_lib_search_path_spec`

MSYS2 always runs in cross-compiling mode, so doesn't skip anything.

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48087, closing.
