### ISSUE TITLE
JetBrains' Goals for Zephyr

### ISSUE THREAD

**Issue by jwoolston** [JetBrains/kotlin-native#2483]
As I continue trying to get more of Kotlin native working for zephyr/STM32, I was curious if there is an intended long term goal from JetBrains/Kotlin-Native of broadly supporting Zephyr or if there is a particular subset of devices that are being targeted? Obviously for non ARM devices different sysroots would need to exist (and bare metal ARM doesn't have a proper one yet anyway).

**Comment by msink** [comment]
I'm not JetBrains, but it's was me that proposed Zephyr/STM32 as first experimental target of embedded devices. JetBrains had general intention to try embedded/IoT market.
Almost random select, but Zephyr simplified first attempt as it have sane API modelled from Linux Kernel, and wide range of supported platforms.
STM32 was selected as it have good support in LLVM.

**Comment by jwoolston** [comment]
I am certainly no expert with LLVM but it is my understanding that the support for ARM in general is pretty good, so would it be reasonable then to assume that at a minimum ARM targets in Zephyr would be not much of a stretch (dealing with board configuration management aside)? I agree that Zephyr is a great target for the same reason.

**Comment by olonho** [comment]
Kotlin/Native for embedded targets is generally an area where we expect community will provide us with feedback and contributions for targets relevant for the people.

**Comment by jwoolston** [comment]
@olonho I ask because I was hoping to come up with a more generic way of using it with zephyr, especially as I look to fill in some of the porting holes like timing, math, etc. Many of these require certain parts of zephyr to be enabled but may not always be available or desired. To this end, I would envision perhaps a generic `Zephyr ARM` target and from there many of the Clang args it uses would be inferred from the config file for the project (as one option) - perhaps a different way of handling the args would be better this was what seemed most viable to me. Does this seem reasonable? In theory I would this this would provide a good solution as it would work from command line or gradle plugin once that is supported.

**Comment by jkbbwr** [comment]
I would really strongly like to see kotlin/native go the way of bare metal compilation without zephyr. Let people bridge the environment and bring their own functions (`malloc` and `free` and etc)

**Comment by sbogolepov** [comment]
Hi. Current approach to Zephyr target requires to recompile the distribution, is not supported in other parts of Kotlin (e.g. Gradle plugin) and is not really flexible. So this is not what we are working on right now. Before making things the right way, we are trying to understand what people want to do with Kotlin on different platform, including embedded targets. Please, share your use-cases [here](https://youtrack.jetbrains.com/issue/KT-43974).
