### ISSUE TITLE
Can cinterop be smarter

### ISSUE THREAD

**Issue by Wooyme** [JetBrains/kotlin-native#2486]
In most C libraries, they always use the naming conventions like LibName_Method to name the function,for example, cJSON_AddStringToObject,EVP_EncryptUpdate and at the same time,the first argument of those functions is always a CPointer which has the same effect as `this` in Kotlin.
So I'm thinking that can you add some tools like `Codegen` in java so that we can use these c libraries easier.

**Comment by olonho** [comment]
Interop is not intended to perform smart conversion, but more or less literally translate the C API. But as an additional non-default behavior controlled by .def file option it could be considered.
