### ISSUE TITLE
Gradle plugin producing multiple binaries

### ISSUE THREAD

**Issue by lathspell** [JetBrains/kotlin-native#2505]
I've only played around with Kotlin Native a bit to produce a Linux binary but I noticed that the current Gradle Plugin seems incapable of producing more than one binary. Configuration examples like components.main with entryPoint in GRADLE_PLUGIN.md suggests that. Wouldn't it be better if it just scans for every global `fun main(Array<String>)` signature and makes them a binary of the same name?

**Comment by ilmat192** [comment]
Yes, it will be supported in `kotlin-multiplatform` in 1.3.20 (see https://github.com/JetBrains/kotlin/commit/ea21662bed03abe97da244ee8541eef352d4f7b6).
