### ISSUE TITLE
Possible to use `includeBuild` to include native lib in multiplatform project?

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2508]
Hi! I'm trying to setup an environment where I use `includeBuild` (and in the future swap that out for a `gitRespository`-type source dependency) to include a kotlin native library into a multiplatform project. I feel like I'm almost there, but I've hit a wall with this error trying to build the multiplatform project:

```
> Configure project :
Kotlin Multiplatform Projects are an experimental feature.
This build is set up to publish Kotlin multiplatform libraries with experimental Gradle metadata. Future Gradle versions may fail to resolve dependencies on these publications. You can disable Gradle metadata usage during publishing and dependencies resolution by removing `enableFeaturePreview('GRADLE_METADATA')` from the settings.gradle file.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':linkDebugFrameworkIos'.
> Could not resolve all task dependencies for configuration ':iosCompileKlibraries'.
   > Could not resolve com.dominaezzz:kotlin-sqlite.
     Required by:
         project :
      > Unexpected type for attribute 'org.jetbrains.kotlin.platform.type' provided. Expected a value of type org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType but found a value of type shadow.org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType.
```

Here are my gradle files:

### Multiplatform
build.gradle
```
plugins {
    id 'kotlin-multiplatform' version '1.3.11'
}
repositories {
    mavenCentral()
}
group 'com.plangrid'
version '0.0.1'

apply plugin: 'maven-publish'

kotlin {
    targets {
        fromPreset(presets.jvm, 'jvm')
        fromPreset(presets.iosX64, 'ios') {
            compilations.main.outputKinds('FRAMEWORK')
        }
    }
    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
                implementation 'com.dominaezzz:kotlin-sqlite'
            }
        }
        commonTest {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-test-common'
                implementation 'org.jetbrains.kotlin:kotlin-test-annotations-common'
            }
        }
        jvmMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib'
            }
        }
        jvmTest {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-test'
                implementation 'org.jetbrains.kotlin:kotlin-test-junit'
            }
        }
        iosMain {
        }
        iosTest {
        }
    }
}

configurations {
    compileClasspath
}
```

settings.gradle
```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "kotlin-multiplatform") {
                useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")
            }
        }
    }
}

enableFeaturePreview('GRADLE_METADATA')

rootProject.name = 'PGFoundation'

includeBuild('../kotlin-sqlite')
```

### Kotlin Native Library (trying to make https://github.com/Dominaezzz/kotlin-sqlite usable locally):
build.gradle
```
plugins {
	id 'org.jetbrains.kotlin.platform.native' version '1.3.11'
}

group 'com.dominaezzz'
version '0.0.1'

apply plugin: 'maven-publish'

sourceSets {
	main.kotlin.srcDirs += 'src/main/kotlin/ksqlite'
	test.kotlin.srcDirs += 'src/test/kotlin'
}

components.main {
	targets = ['ios_x64']
	outputKinds = [KLIBRARY]
	dependencies {
		cinterop('sqlite3') {
			target('linux') {
				compilerOpts('-I/usr/include -I/usr/include/x86_64-linux-gnu')
			}
			target('macos') {
				compilerOpts('-I/usr/local/include -I/opt/local/include')
			}
			target('mingw') {
				compilerOpts('-IC:/msys64/mingw64/include')
			}
		}
	}
}

components.test {
	target('linux') {
		linkerOpts('-L/usr/lib -L/usr/lib/x86_64-linux-gnu')
	}
	target('macos') {
		linkerOpts('-L$/usr/local/lib')
	}
	target('mingw') {
		linkerOpts('-LC:/msys64/mingw64/lib -Wl,-Bstatic -lstdc++ -static')
	}
	extraOpts('-tr')
}
```

settings.gradle
```
rootProject.name = 'kotlin-sqlite'

enableFeaturePreview('GRADLE_METADATA')
```

I'm now worried that I've hit whatever issue is behind this snippet from GRADLE_PLUGIN.md (specifically the multiplatform bit):
> This document describes Kotlin/Native experimental Gradle plugin, which is not the plugin yet supported by IDE or in multiplatform projects. See MPP Gradle plugin documentation for more information.

Any help would be appreciated, as well as opinions about gradle-related cleanup here (new to gradle). Thanks!

**Comment by r4zzz4k** [comment]
From what I see in the error message, native plugin has common dependency with multiplatform one, which is repackaged under `shadow.` package to avoid clash. I believe this is the same reason why there are two Gradle plugins for kotlinx.serialization -- one for multiplatform, one for native.
Your best bet is probably to ask if @Dominaezzz is going to switch to multiplatform plugin. That should be logical move since his profile mentions Android and I'm sure he has this planned :)
Another thing to check is whether library published by native plugin can be consumed using multiplatform one. If that's the case than you should be able to publish sqlite library to local maven repo and consume it from your multiplatform project, thus avoiding dependency substitution which is causing mentioned problem.

**Comment by benasher44** [comment]
Gotcha! I should just switch to the multiplatform plugin then. Will play around with that and report back (and close).

**Comment by Dominaezzz** [comment]
I am indeed planning to switch to the multiplatform plugin but have been working on something else.
If it does help, I can do the switch now but I haven't figured out publishing yet.

**Comment by benasher44** [comment]
I'm doing it now locally, so that I can test things. I'll open a PR once it's done, or I'll update with yours if you get to it sooner. Up to you!

**Comment by benasher44** [comment]
Was able to get passed this issue with the update to switch to multiplatform. thanks!
