### ISSUE TITLE
cinterop: staticCFunction and StableRef

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#2510]
Here proven to work coroutine UI dispatcher for iOS:
``` kotlin
object MainLoopDispatcher: CoroutineDispatcher(), Delay {

    override fun dispatch(context: CoroutineContext, block: Runnable) {
        dispatch_async(dispatch_get_main_queue()) {
            try {
                block.run()
            } catch (err: Throwable) {
                logError("UNCAUGHT", err.message ?: "", err)
                throw err
            }
        }
    }

    override fun scheduleResumeAfterDelay(timeMillis: Long, continuation: CancellableContinuation<Unit>) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, timeMillis * 1_000_000), dispatch_get_main_queue()) {
            try {
                with(continuation) {
                    resumeUndispatched(Unit)
                }
            } catch (err: Throwable) {
                logError("UNCAUGHT", err.message ?: "", err)
                throw err
            }
        }
    }

    override fun invokeOnTimeout(timeMillis: Long, block: Runnable): DisposableHandle {
        val handle = object : DisposableHandle {
            var disposed = false
                private set
            override fun dispose() {
                disposed = true
            }
        }
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, timeMillis * 1_000_000), dispatch_get_main_queue()) {
            try {
                if (!handle.disposed) {
                    block.run()
                }
            } catch (err: Throwable) {
                logError("UNCAUGHT", err.message ?: "", err)
                throw err
            }
        }
        return handle
    }
}
```

Well, now I want to do the same for my guinea pig, desktop `libui` library.
It have direct analogs for `dispatch_async` and `dispatch_after` functions - `uiQueueMain` and `uiTimer`.
For now I have this:
``` kotlin
object uiDispatcher : CoroutineDispatcher(), Delay {

    override fun dispatch(context: CoroutineContext, block: Runnable) {
        val ref: StableRef<Runnable> = StableRef.create(block).also { actions.add(it) }
        uiQueueMain(data = ref.asCPointer(), f = staticCFunction { data: COpaquePointer? ->
            val ref: StableRef<Runnable> = data!!.asStableRef()
            val block: Runnable = ref.get()
            block.run()
        })
    }

    override fun scheduleResumeAfterDelay(timeMillis: Long, continuation: CancellableContinuation<Unit>) {
        val ref: StableRef<CancellableContinuation<Unit>> = StableRef.create(continuation).also { actions.add(it) }
        uiTimer(timeMillis.toInt(), data = ref.asCPointer(), f = staticCFunction { data: COpaquePointer? ->
            val ref: StableRef<CancellableContinuation<Unit>> = data!!.asStableRef()
            val continuation: CancellableContinuation<Unit> = ref.get()
            with(continuation) {
                resumeUndispatched(Unit)
            }
            0 // do not autorepeat
        })
    }

    override fun invokeOnTimeout(timeMillis: Long, block: Runnable): DisposableHandle {
        val handle = DisposableRunnable(block)
        val ref: StableRef<DisposableRunnable> = StableRef.create(handle).also { actions.add(it) }
        uiTimer(timeMillis.toInt(), data = ref.asCPointer(), f = staticCFunction { data: COpaquePointer? ->
            val ref: StableRef<DisposableRunnable> = data!!.asStableRef()
            val handle: DisposableRunnable = ref.get()
            handle.block?.run();
            0 // do not autorepeat
        })
        return handle
    }

    class DisposableRunnable(
        var block: Runnable?
    ) : DisposableHandle {
        override fun dispose() {
            block = null
        }
    }

    private val actions = mutableListOf<StableRef<Any>>()

    fun onExit() {
        actions.forEach { it.dispose() }
    }
}
```

So questions:

- Why Kotlin lambda can be passed directly to ObjectiveC, but for C it must be wrapped to `staticCFunction` and params must be pinned by `StableRef.create` ?
 Where is ObjectiveC "black magic" that makes it possible ?

- StableRef "should eventually be manually disposed" - but in this usecase I cannot imagine how to do it, other then just add it to list, and clean it at the program end.
 But for long running program with intensive coroutines usage - list will be very long - so this is not appropriate.

- "lambda must not capture any values" - ok, but why then it warns about name shadowing:
```
libui\src\nativeMain\kotlin\coroutines\dispatcher.kt:14:17: warning: name shadowed: ref
            val ref: StableRef<Runnable> = data!!.asStableRef()
                ^
libui\src\nativeMain\kotlin\coroutines\dispatcher.kt:15:17: warning: name shadowed: block
            val block: Runnable = ref.get()
                ^
libui\src\nativeMain\kotlin\coroutines\dispatcher.kt:23:17: warning: name shadowed: ref
            val ref: StableRef<CancellableContinuation<Unit>> = data!!.asStableRef()
                ^
libui\src\nativeMain\kotlin\coroutines\dispatcher.kt:24:17: warning: name shadowed: continuation
            val continuation: CancellableContinuation<Unit> = ref.get()
                ^
libui\src\nativeMain\kotlin\coroutines\dispatcher.kt:36:17: warning: name shadowed: ref
            val ref: StableRef<DisposableRunnable> = data!!.asStableRef()
                ^
libui\src\nativeMain\kotlin\coroutines\dispatcher.kt:37:17: warning: name shadowed: handle
            val handle: DisposableRunnable = ref.get()
                ^
```

**Comment by msink** [comment]
Callbacks can be either called once (in most cases), or can be not called at all before program ends.

**Comment by Dominaezzz** [comment]
Is there a way to know if the callbacks are not called? or why they would not be called?
Seems like a bit of a lifetime issue from libui in the api design.

**Comment by msink** [comment]
It will not be called for example if long `delay` in coroutine will not expire before program end. Then `libui` will terminate not finished callback on OS level, but not notify Kotlin code.

Well, maybe I can somehow patch `libui` - it is relatively small and self contained, but same problem can be in GTK, OpenGL or some other big libraries...

**Comment by Dominaezzz** [comment]
In that case, I think rolling your own version of `StableRef`, which doesn't declare non-disposed references at the end of the program as "leaked". Or maybe the actual `StableRef` should just do this. It is just reference counting.

**Comment by SvyatoslavScherbina** [comment]
> Why Kotlin lambda can be passed directly to ObjectiveC, but for C it must be wrapped to staticCFunction and params must be pinned by StableRef.create ?
Where is ObjectiveC "black magic" that makes it possible ?

Because Objective-C has blocks which encapsulate function pointer with associated data (so blocks can capture values), and functions like `dispatch_async` have block-typed parameters. Blocks are objects thus removed automatically by reference counting.

> StableRef "should eventually be manually disposed" - but in this usecase I cannot imagine how to do it, other then just add it to list, and clean it at the program end.
But for long running program with intensive coroutines usage - list will be very long - so this is not appropriate.

> Callbacks can be either called once (in most cases), or can be not called at all before program ends.

> Maybe, and it's why I'm asking here, not disposed StableRef currently called "runtime error".

As for now you can try one of the following approaches:

1. Have a registry for stable refs that are not disposed yet, and dispose them on exit

or

2. Suppress memory leak check by terminating process with [exitProcess](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.system/exit-process.html)

> "lambda must not capture any values" - ok, but why then it warns about name shadowing:

For the same reason it warns about it in any other case.

**Comment by msink** [comment]
>> "lambda must not capture any values" - ok, but why then it warns about name shadowing:

> For the same reason it warns about it in any other case.

If they cannot be captured - they are not accessible from inside `staticCFunction` - so are not shadowed.
Am I wrong?

**Comment by msink** [comment]
> Because Objective-C has blocks which encapsulate function pointer with associated data (so blocks can capture values), and functions like dispatch_async have block-typed parameters. Blocks are objects thus removed automatically by reference counting.

Can it be simulated for C, if callback have transparent `void *data` parameter?

**Comment by SvyatoslavScherbina** [comment]
> > > "lambda must not capture any values" - ok, but why then it warns about name shadowing:
> 
> > For the same reason it warns about it in any other case.
> 
> If they cannot be captured - they are not accessible from inside `staticCFunction` - so are not shadowed.
> Am I wrong?

It is true, but one can still refer wrong variable by mistake.

**Comment by SvyatoslavScherbina** [comment]
> > Because Objective-C has blocks which encapsulate function pointer with associated data (so blocks can capture values), and functions like dispatch_async have block-typed parameters. Blocks are objects thus removed automatically by reference counting.
> 
> Can it be simulated for C, if callback have transparent `void *data` parameter?

Using `StableRef` seems to be somewhat like such a simulation.
