### ISSUE TITLE
iOS Subclassing "can't be implemented" 'NSGenericException' Better error message

### ISSUE THREAD

**Issue by Reedyuk** [JetBrains/kotlin-native#2512]
I have a kotlin native project, where I have defined a class called:
```
actual open class BluetoothCommonService {
    actual fun scan() {}
    actual fun connect(bluetoothPeripheral: BluetoothPeripheral) {}
    actual fun didConnect() {}
    actual fun discoveredServices() {}
    actual fun discoveredDevices() {}
    actual fun characteristcValueChanged() {}
}
```

At the moment I intend to bring this class into my iOS project and subclass it:
```
class BluetoothService: BluetoothCommonService {

    var centralManager: CBCentralManager!
    var delegates = [BluetoothServiceDelegate]()

    override init() {
        super.init()
        centralManager = CBCentralManager(delegate: self, queue: nil)
    }

    override func scan() {
        centralManager.scanForPeripherals(withServices: nil, options: nil)
    }

    override func connect(bluetoothPeripheral: BluetoothPeripheral) {
        
    }
}
```
It compiles fine, but when I run the application, i get this error upon instantiation of BluetoothService:

> *** Terminating app due to uncaught exception 'NSGenericException', reason: '[AppName.BluetoothService scan] can't be implemented'

* As a note, i'm doing all of the bluetooth handling within the actual native layer, but i wanted to build a nice interface/subclass for now and then gradually bring more into the multiplatform project. BluetoothPeripherial object is a Kotin Native object I created and works fine before i implemented the bluetooth service class so i know its not that.

**Comment by SvyatoslavScherbina** [comment]
`scan` can't be overridden because it is final.
Please try to add `open` keyword to method declarations in `BluetoothCommonService`.

**Comment by Reedyuk** [comment]
I will check later today, thanks and good spot. Could probably do with a better error message

**Comment by Reedyuk** [comment]
Confirmed as working.
Is it possible to request a better error message when this happens? 

Thanks

**Comment by SvyatoslavScherbina** [comment]
>Is it possible to request a better error message when this happens?

Done with https://github.com/JetBrains/kotlin-native/commit/757449ba9c2bf798578e7fa84f686ad1b4b4e8e7
