### ISSUE TITLE
Inconsistency with size_t type wasm32

### ISSUE THREAD

**Issue by SBNTT** [JetBrains/kotlin-native#2515]
I call a C function from Kotlin native which has a size_t parameter. 
Passing parameter as ULong, it compile for macos64 target

When compiling the same code for wasm32 target, i got this error:
`error: type mismatch: inferred type is ULong but size_t /* = UInt */ was expected`

If I pass parameter as UInt, it compile for wasm32 but got this error when compiling for macos64
`error: type mismatch: inferred type is UInt but size_t /* = ULong */ was expected`

**Comment by msink** [comment]
Use `.convert()` instead of `.toUInt()`/`.toULong()`.

**Comment by SBNTT** [comment]
Wow Thanks !
