### ISSUE TITLE
Web assembly explanations

### ISSUE THREAD

**Issue by SBNTT** [JetBrains/kotlin-native#2517]
Hi

I have a native module, whose `build.gradle` looks like this:

```gradle
apply plugin: "org.jetbrains.kotlin.platform.native"

sourceSets {
    main.kotlin.srcDirs += "src/main"
}

components.main {
    targets = ['macos_x64', 'linux_x64', 'mingw_x64']
    entryPoint = "sbntt.test.main"
    outputKinds = [EXECUTABLE]

    dependencies {
        implementation project(":core")
        implementation project(":services:service_a")
        implementation project(":services:service_b")
        implementation project(":services:service_c")
    }
}
``` 

This works well for compiling native executables.

I would like to be able to export this as web assembly binary, then I add wasm32 to targets array.
It compiles without any errors, but when I run it into a browser, this error appears:
`Uncaught (in promise) CompileError: AsyncCompile: Compiling wasm function "Kotlin_io_Console_print" failed: call found empty stack @+159234`

I saw in canvas sample that dom library is included. Is it the reason why this does not work ?
I tried to add the dom library in a test project, and there is my `build.gradle`:

```gradle
buildscript {
    allprojects {
        repositories {
            jcenter()
        }
    }
}

plugins {
    id "org.jetbrains.kotlin.multiplatform" version "1.3.11"
}

import org.jetbrains.kotlin.gradle.tasks.KotlinNativeCompile
import java.nio.file.Paths

String packageName = 'kotlinx.interop.wasm.dom'
String jsinteropKlibFileName = Paths.get(buildDir.toString(), 'klib', "$packageName-jsinterop.klib").toString()

kotlin {
    targets {
        fromPreset(presets.wasm32, 'wasmapi') {
            compilations.main.outputKinds 'EXECUTABLE'
            compilations.main.entryPoint 'sbntt.wasmapi.main'
        }
    }

    sourceSets {
        wasmapi {
            dependencies {
                implementation files(jsinteropKlibFileName)
            }
        }
    }
}

task jsinterop(type: Exec) {
    workingDir projectDir
    def ext = MPPTools.isWindows() ? '.bat' : ''
    def distributionPath = project.properties['org.jetbrains.kotlin.native.home'] as String
    if (distributionPath != null) {
        commandLine Paths.get(file(distributionPath).path, 'bin', "jsinterop$ext").toString(),
                '-pkg', packageName,
                '-o', jsinteropKlibFileName,
                '-target', 'wasm32'
    } else {
        doFirst {
            // Abort build execution if the distribution path isn't specified.
            throw new GradleException("""\
                |Kotlin/Native distribution path must be specified to build the JavaScript interop.
                |Use 'org.jetbrains.kotlin.native.home' project property to specify it.
            """.stripMargin())
        }
    }
}

tasks.withType(KotlinNativeCompile).all {
    dependsOn jsinterop
}
``` 

unfortunatly, I got this error:
`Could not get unknown property 'MPPTools' for task ':jsinterop' of type org.gradle.api.tasks.Exec.` and do not managed to fix it.

Another question:
Are service_a, service_b etc... dependencies bundled into the wasm build output or do I need to link them in any way ?

Moreover, is it possible to compile this module without entry point, load it in a web page and call wasm function from javascript ? if yes, can I have an example ?

Thanks !

**Comment by neismit** [comment]
1) Replace "MPPTools.isWindows()" on "OperatingSystem.current().isWindows()".
2) in gradle.properties set variable: org.jetbrains.kotlin.native.home=[path to kotlin-native git repo]/dist
2) Assemble from source code html5Canva (https://github.com/JetBrains/kotlin-native/tree/master/samples/html5Canvas)
3) Find: kotlin-native-master/samples/html5Canvas/build/klib/kotlinx.interop.wasm.dom-jsinterop.klib
4) copy it in your project and correct "jsinteropKlibFileName" in gralde file.
5) run ./gradlew YourProject:wasm32MainKlibrary

I'm not sure about (2), if you copy klib in your project, but I do it.

**Comment by SvyatoslavScherbina** [comment]
Closing as obsolete.
