### ISSUE TITLE
[Feature Request] Bridge ByteArray as Swift.Data/NSData in Swift/Obj-C

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2518]
Right now, `ByteArray` is bridged as a `PGFKotlinByteArray`. It doesn't take much effort to add a `toData()` extension in the ios platform code in Kotlin, but it would be nice if this were bridged automatically.

**Comment by benasher44** [comment]
That's a good point about mutation. How about bridging to `NSMutableData`  then?

>  is not absolutely correct, because ByteArray and NSData are different types with different operations and semantics.

Am I wrong in assuming that `ByteArray` is most often used to represent a data blob? I'm new to this ecosystem and am looking for a cross-platform type to use pass raw data back between a native/jvm client and a K/N lib. `ByteArray` seemed like the closest type.

**Comment by SvyatoslavScherbina** [comment]
> That's a good point about mutation. How about bridging to NSMutableData then?

Still different type: `NSMutableData` is resizable (and abstract), while `ByteArray` is not.

> ByteArray seemed like the closest type. Is there another you all recommend?

No, I don't think so.

**Comment by benasher44** [comment]
Hm okay. I suppose extensions are the best option then. Closing
