### ISSUE TITLE
Enable Gradle Caching for compilation tasks

### ISSUE THREAD

**Issue by Dkhusainov** [JetBrains/kotlin-native#2520]
Currently tasks `compileKotlin$Preset` are only checked for UP-TO-DATE and not cached to gradle build cache. Running a build scan on my native build showed that "Not cacheable | Caching has not been enabled for the task."

**Comment by fab1an** [comment]
Please prioritize this, it's an easy win.

**Comment by Dkhusainov** [comment]
@ilmat192 Is this implemented yet? If it is I'm gonna close it.
#https://github.com/JetBrains/kotlin-native/issues/2758

**Comment by ilmat192** [comment]
No, it isn't implemented yet.

**Comment by gimlids** [comment]
Compilation of my small multiplatform lib (including iOS target) takes forever (4m 53s) even locally. Is my build misconfigured or is it expected to be very slow until this issue is closed?

**Comment by gimlids** [comment]
Specifically, `linkMyLibReleaseFrameworkIos` seems to take the majority of that time.

**Comment by artdfel** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), I'm closing this issue in favor of https://youtrack.jetbrains.com/issue/KT-39564. I also posted the link onto this issue there, just to save the context.
