### ISSUE TITLE
Improve bridging for Swift.Data/NSData

### ISSUE THREAD

**Issue by SvyatoslavScherbina** [JetBrains/kotlin-native#2529]
See also #2518.

**Comment by DTHeaven** [comment]
How's going about this feature?

**Comment by SvyatoslavScherbina** [comment]
The discussion from #2518 is still relevant.

**Comment by SvyatoslavScherbina** [comment]
We are [migrating issues to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), so moving this one to https://youtrack.jetbrains.com/issue/KT-46185
