### ISSUE TITLE
Kotlin/Native MPP: Extending a native class causes type to be erased

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [JetBrains/kotlin-native#2545]
Android Studio 3.3
Kotlin Version 1.3.11
gradleVersion 4.7
android gradle version 3.2.1

I have created a Multi Platform Android/IOS project.  I was attempting to create a custom extension of UIViewController that will delegate to another class that is a custom interface.  When Kotlin Native compiles the framework library, however, the type for the class that extends UIViewController is not included in the header file and there is no warning that something is incorrect.  It just appears that the compiler is ignoring the class.   If the class is referenced from another class, UIViewController is used instead of the extended class.

example classes, in iOSMain directory:

```
class TestControllerDelegate {

}

class TestViewController(val controllerDelegate: TestControllerDelegate): UIViewController(null,null) {
}

class TestControllerManager(val controller: TestViewController)
```

generated header file output:

```
@class TestMPP_commonTestControllerDelegate, TestMPP_commonTestControllerManager, UIViewController
//.... 
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("TestControllerDelegate")))
@interface Srts_commonTestControllerDelegate : KotlinBase
- (instancetype)init __attribute__((swift_name("init()"))) __attribute__((objc_designated_initializer));
+ (instancetype)new __attribute__((availability(swift, unavailable, message="use object initializers instead")));
@end;

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("TestControllerManager")))
@interface Srts_commonTestControllerManager : KotlinBase
- (instancetype)initWithController:(UIViewController *)controller __attribute__((swift_name("init(controller:)"))) __attribute__((objc_designated_initializer));
@property (readonly) UIViewController *controller;
@end;
//.... 
```

So, due to the generation here, a TestViewController with a TestControllerDelegate can never be created in Swift   If there is something incompatible about this code, then I would expect the compiler to issue a warning or an error.  

Removing the UIViewController extension allows the TestViewController class to be included appropriately in the header file.

**Comment by SvyatoslavScherbina** [comment]
This behaviour is expected. See #2491.

If you want to create instance of this class from Swift, does anything prevent you from declaring a factory function in Kotlin and calling it from Swift?

**Comment by jonl-percsolutions-com** [comment]
Nothing prevents me from doing so, but the following comment from the documentation lead me to believe that the class would simply be made final and unable to be extended.

> Non-final Kotlin classes inheriting Swift/Objective-C types aren't supported yet, so it is not possible to declare a complex class hierarchy inheriting Swift/Objective-C types

I was not attempting to create a "complex hierarchy" but just a simple one and it took me about 4 hours to figure out why the type was not appearing at all.  So the bug report is less about the intended behavior and the lack of feedback from the compiler and the unclear nature of what will occur in the current documentation.  I think the solution in #2491 will work in the long run if the generated interface is at least visible, I wouldn't care about extending the class. Is this now the behavior in 1.3.20-EAP?  I am working on testing that because I need the export framework functionality.

**Comment by SvyatoslavScherbina** [comment]
> I think the solution in #2491 will work in the long run if the generated interface is at least visible, I wouldn't care about extending the class.

It is visible but unavailable, so you can't instantiate it.

> Is this now the behavior in 1.3.20-EAP

Yes.

**Comment by SvyatoslavScherbina** [comment]
Ok, thank you for the feedback.

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48069, closing.
