### ISSUE TITLE
No document for kotlin-native for WebAssembly

### ISSUE THREAD

**Issue by futurechallenger** [JetBrains/kotlin-native#2546]
Can you guys please add document for kotlin-native WebAssembly. It better include:
1. In time samples
2. Doc for how things work
3. How to get a smaller size of compiled WASM file
4. Multi-thread, maybe coroutine support in WASM (as in Chrome 70, `pthread` can be used to do muti-thread thing)

**Comment by salvador-barboza** [comment]
Are there any plans on commiting to improving this documentation? If you can provide some guidence, I would be glad to help.

**Comment by SvyatoslavScherbina** [comment]
Kotlin/Native WASM target is not actively developed and maintained now.
Instead there is development of new separate WASM backend.
