### ISSUE TITLE
How to debug iosTest in multiple-platform(Android/iOS) project 

### ISSUE THREAD

**Issue by wuseal** [JetBrains/kotlin-native#2550]
As title, How could we debug the ios tests write with Kotlin/native on MBP?
I have tried `AppCode` and `CLion`, But All can't find any way to debug the ios test write with K/N.
It's very important for me that an exception without a crash has happened, and I need to locate the problem. Thanks.
As this simple test code in Created Default multiple-platform project for iOS And Android at `~/IdeaProjects/MultipleTest/app/src/iosTest/kotlin/sample/SampleTestsIOS.kt`
```kotlin
package sample

import kotlin.test.Test
import kotlin.test.assertTrue

class SampleTestsIOS {
    @Test
    fun testHello() {
        assertTrue("iOS" in hello())
    }
}
```

**Comment by SvyatoslavScherbina** [comment]
Adding an exception breakpoint may help.
See
https://www.jetbrains.com/help/clion/using-breakpoints.html#exception-breakpoints (C/C++ Exception Breakpoint)
https://www.jetbrains.com/help/objc/creating-exception-breakpoints.html
