### ISSUE TITLE
Could not find method kapt() multiplatform project

### ISSUE THREAD

**Issue by SBNTT** [JetBrains/kotlin-native#2551]
Start a new project in intellij IDEA and choose `kotlin (Mobile ANdroid/iOS)`template.
in app/build.gradle

add `apply plugin: 'kotlin-kapt'` after `apply plugin: 'kotlin-android-extensions'`

add
```
implementation 'com.github.bumptech.glide:glide:4.8.0'
kapt 'com.github.bumptech.glide:compiler:4.8.0'
``` 

in the main dependencies.

error:
`Could not find method kapt() for arguments [com.github.bumptech.glide:compiler:4.8.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

**Comment by h0tk3y** [comment]
@SBNTT Please make sure you specify the `kapt` dependency within a top-level `dependencies { ... }` block, not inside a dependencies block for some of the source sets.

**Comment by SBNTT** [comment]
Ho thanks ! maybe this should be moved in the project template also

**Comment by KursX** [comment]
What is the solution for this problem? I also can not figure it out

`
plugins {
    id 'kotlin-multiplatform'
}
repositories {
    google()
    jcenter()
    mavenCentral()
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "a.b.c"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1"
    }
}


kotlin {
    targets {
        fromPreset(presets.android, 'android')
        fromPreset(presets.iosX64, 'ios') {
            compilations.main.outputKinds('FRAMEWORK')
        }
        final def iOSTarget = System.getenv('SDK_NAME')?.startsWith("iphoneos") \
                              ? presets.iosArm64 : presets.iosX64
        fromPreset(iOSTarget, 'iOS') {
            compilations.main.outputKinds('FRAMEWORK')
        }
        fromPreset(presets.android, 'android')
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
            }
        }
        androidMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib'
            }
        }
        iosMain {
            dependencies {
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    
    implementation 'androidx.room:room-runtime:2.2.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.1'
    
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    kapt 'androidx.room:room-compiler:2.2.3'

}`

**Comment by artem-mi** [comment]
@KursX Try the following order of directives:
```
...
kotlin {
    ...
}
apply plugin: 'kotlin-kapt'
dependencies {
    ...
}
```
