### ISSUE TITLE
no access to native platform opengl or glut

### ISSUE THREAD

**Issue by tempest766** [JetBrains/kotlin-native#2553]
I thought the glut and opengl functions were suppose to be natively accessible in the linux_x64 target if the native dev packages were also installed?  I've got a well stocked f27 workstation that I frequently do c++ opengl/glut programming on, but the konanc compiler cannot resolve any of the glut or opengl imports.

**konanc OpenGlTeapot.kt -o OpenGlTeapot**

According to the docs, minimalist as they are, that should be enough.

Waht gives?

**Comment by msink** [comment]
#2511

**Comment by olonho** [comment]
For Linux OpenGL and GLUT not shipped as the platform library, so interop shall be used to bridge with those libs. See https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#simple-example

**Comment by tempest766** [comment]
> For Linux OpenGL and GLUT not shipped as the platform library, so interop shall be used to bridge with those libs. See https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#simple-example

OK.  not the solution I wanted to read but it is what it is.  

Suppose I want to build targetted platform libraries for lets say, rapsberrypi, want to build them on the x64 using the target option.  I'm guessing that won't work and that the compilation of the library link modules would need to be done ON THE TARGET PLATFORM.  Unfortunately that's what I'm trying to avoid; doing any compilation on the target.

**Comment by msink** [comment]
You anyway have to install opengl on the target device - and mount that device as network drive to your host.
Now, if you have access to that target `.h` files, and cross-compiling pair host-target supported - cinterop should work.
If it does not - it's a bug.
