### ISSUE TITLE
Embed native framework in iOS output

### ISSUE THREAD

**Issue by Endanke** [JetBrains/kotlin-native#2555]
Hey there!

I'm building a standalone iOS Framework for distribution with Kotlin-Multiplatform (let's call it **Main**).
I had a bunch of platform specific code, written in Swift, which I've bundled in a dynamic framework (let's call it **PlatformSpecific**) and it's included in the project with the cinterop tool.

**PlatformSpecific** includes a couple internal tools that's only used by us and I'd like to hide it from the end-users, who will only use **Main**.
Currently, if I'd like to include **Main** in a host application, I need to include **PlatformSpecific** too, which means that the end-users have to install two frameworks and they can see some internal headers from **PlatformSpecific**.

My question is: Is it possible to somehow embed **PlatformSpecific** in **Main** for distribution? I'm thinking either to copy the framework inside the **Main** framework or include it as a static library. So far I had no success with the first approach and I don't know how to do the second properly.

_Update:_ I was trying to convert **PlatformSpecific** to a static library, but it breaks the build at the linking phase, probably because I have Swift sources and I'm not sure if I can add the required libraries in the Kotlin project. Probably the other approach would be more universal for similar use-cases.

(Sidenote: I know that Apple discourages the usage of umbrella frameworks, but in this case all the code in **PlatformSpecific** is supplied by us, so it won't cause any conflicts with other libraries)

**Comment by SvyatoslavScherbina** [comment]
Hello,
> they can see some internal headers from PlatformSpecific.

You can distribute `PlatformSpecific.framework` without `Headers` directory.

> copy the framework inside the Main framework

This is likely to be possible. Have you tried placing `PlatformSpecific.framework` under `Main.framework/Frameworks/`?

**Comment by Endanke** [comment]
@SvyatoslavScherbina 
Thanks, removing the headers directory technically solves my problem!

I've tried placing it inside the Main framework, but then I'll get a runtime error in the host application, which indicates that PlatformSpecific is not loaded.
```
dyld: Library not loaded: @rpath/PlatformSpecific.framework/PlatformSpecific
Referenced from: /private/var/containers/Bundle/Application/2DB23DA5-9F0C-4790-9654-0020199CD44B/Sample.app/Frameworks/Main.framework/Main
```
I guess it's because **PlatformSpecific** is not included in the embedded binaries list. Or maybe the search paths inside **Main** should me modified?

**Comment by SvyatoslavScherbina** [comment]
What does the following command show?
```
$ otool -l .../Main.framework/Main  | grep -A2 LC_RPATH
```

**Comment by Endanke** [comment]
The following output:
```
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
```

**Comment by SvyatoslavScherbina** [comment]
So rpath appears to be incomplete for this kind of embedding.
Please open Xcode project for `PlatformSpecific`, select the project itself in the navigator pane, then select framework target in "Targets" section to the right, switch to "Build Settings" tab on the top and locate "Runtime Search Paths" key.
The value is likely to contain `@executable_path/Frameworks`. Adding `@loader_path/Frameworks` should help with `Library not loaded` issue.

**Comment by Endanke** [comment]
The **PlatformSpecific** target already contains the `@loader_path/Frameworks` value. Since I'd like to include it in **Main** I should modify that target. The problem is, that the Main.framework is generated with Kotlin, so I guess I should add this value in the gradle configuration somehow?

**Comment by Endanke** [comment]
Yes `install_name_tool` did the job, it works now!
Thank you very much for the help! 👍 
I'll read more about these commands, they are extremely useful.

**Comment by SvyatoslavScherbina** [comment]
Btw, it actually seems to be possible to achieve the same with Gradle configuration.
Please try to add `compilations.main.linkerOpts '-rpath @loader_path/Frameworks'` next to `compilations.main.outputKinds('FRAMEWORK')` in your `build.gradle`.
