### ISSUE TITLE
How to determine build type in kotlin-multiplatform project

### ISSUE THREAD

**Issue by dfpalomar** [JetBrains/kotlin-native#2562]
Hello. I'm struggling to find a solution for a problem that seems simple.

I’m working on a multiplaform project, iOS and JVM (I’m not targeting Android directly) and depending on the build type (debug or release) I want to configure the logging level (i.e. to print only errors in release). Since there is no a _BuildConfig_ class available (like the one generated by the Android gradle plugin), how can I know from `commonMain` the build type?

**Comment by msink** [comment]
#952

**Comment by SvyatoslavScherbina** [comment]
Hello.
You can configure debug and release binaries to include alternative source sets.
See the example here: https://github.com/ilmat192/kotlin-native-gradle-samples/tree/master/debug-logger
Debug builds include [commonDebug](https://github.com/ilmat192/kotlin-native-gradle-samples/tree/master/debug-logger/src/commonDebug/kotlin) source set, release builds include [commonRelease](https://github.com/ilmat192/kotlin-native-gradle-samples/tree/master/debug-logger/src/commonRelease/kotlin) instead.

**Comment by steve-the-edwards** [comment]
Seems like a lot of gradle work to just carry separate source sets.  Can we define a constant similar (a la BuildConfig.DEBUG) that is derived from the project build property in the build?

**Comment by SvyatoslavScherbina** [comment]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native/-platform/is-debug-binary.html

**Comment by SvyatoslavScherbina** [comment]
It should. Please report an issue if you discover that it doesn't.
