### ISSUE TITLE
Reflection in Kotlin Multiplatform

### ISSUE THREAD

**Issue by ImanX** [JetBrains/kotlin-native#2564]
How to use Reflection in Kotlin Multiplatform ?
is there any documents about it?

**Comment by olonho** [comment]
Basic reflection is available, full one is not available.

**Comment by ImanX** [comment]
@olonho Where I can access to documents it?

**Comment by olonho** [comment]
Usual place: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/index.html
