### ISSUE TITLE
Q: Static linking opportunity?

### ISSUE THREAD

**Issue by 4ntoine** [JetBrains/kotlin-native#2565]
Is there any opportunity to build static library to be linked later to use in native apps?

The build logics is pretty complicated, in brief - we wan't to build `.a` and then to link it with native C++ code compiled into single executable. Is it possible? So far i've found lot's of posts on how to build shared library with Kotlin/Native.

### Long story
We want to start using Kotlin with Kotlin/Native in complicated project with 85% of C++ code and 15% android code (UI mostly). It has project-specific build configuration (with `GN`) that depends on build variant - in Debug build it builds lot's of shared libraries (.so), in Release mode it builds lot's of archives (.a) and links into single huge executable. We want to avoid breaking building logics and just provide either static library or dynamic library when needed. The only difference is language + compiler used.

**Comment by olonho** [comment]
Yes, it is possible, use `-produce static` build flag or matching Gradle DSL, see https://github.com/JetBrains/kotlin-native/blob/master/FAQ.md#q-how-do-i-create-a-static-library-or-an-object-file

**Comment by 4ntoine** [comment]
@olonho Thanks a lot! Closing it
