### ISSUE TITLE
How about supporting set framework's version in building?

### ISSUE THREAD

**Issue by horita-yuya** [JetBrains/kotlin-native#2569]
## Problem
Currently, version of a framework is hard-coded [here](https://github.com/JetBrains/kotlin-native/blob/d02a51ba98a2f68080a0a77cbcd3c7592ad31ae3/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExport.kt#L146), 1.0 .

## Suggestion
How about supporting set the version in building (I mean, in build.gradle)?

## Purpose:
- Grasping that the version of local .framework used for development and the one of remote .framework cached in like CircleCI Artifacts are same.
- Separating main app's building and common framework's building can make building time shorter.

Or, any other solutions can achieve my purpose? 🙏

**Comment by olonho** [comment]
Makes sense, we just need to decide how to control the version from Gradle, and what format expectations are there.

**Comment by ilmat192** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-33117](https://youtrack.jetbrains.com/issue/KT-33117).
