### ISSUE TITLE
new native project

### ISSUE THREAD

**Issue by whaqzhzd** [JetBrains/kotlin-native#2573]
How to create a new OpenGL project
I created a kotlin/native project using idea.
Imitated the official sample and wrote gradle

```js
def hostPreset = MPPTools.defaultHostPreset(project, [kotlin.presets.mingWX64])

kotlin {
    targets {
        fromPreset(hostPreset, 'opengl') {
            compilations.main.outputKinds 'EXECUTABLE'
            compilations.main.entryPoint 'test.opengl.main'
        }
    }
}
```
But I received an error, I don't know how to proceed to the next step
Could not get unknown property 'MPPTools' for root project 'iceclam_kotlin' of type org.gradle.api.Project.

**Comment by olonho** [comment]
To create new project please use IDEA new project wizard.
 ![Image](https://i.imgur.com/JKQ2wgU.png)
