### ISSUE TITLE
new export option for framework doesn't export everything

### ISSUE THREAD

**Issue by Dkhusainov** [JetBrains/kotlin-native#2576]
`
framework {
  export project(":other-project")
}
`

global functions and companion objects from `other-project` are not exported. 

Also, is there any way to change prefix of the classes exported? 
Right they are prefixed with project name, aka 'Other_project*'

**Comment by SvyatoslavScherbina** [comment]
Have you seen this sample? https://github.com/ilmat192/kotlin-native-gradle-samples/tree/master/export-kotlin-multiplatform
Companion objects and global functions from `:exported` project are successfully included to the framework built from `:framework` project.

> Also, is there any way to change prefix of the classes exported?

Please try to apply this trick to your `other-project`: https://kotlinlang.org/docs/reference/native/faq.html#q-how-do-i-specify-a-custom-objective-c-prefixname-for-my-kotlin-framework
