### ISSUE TITLE
No task generated for running tests on iOS simulator

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2578]
I've been trying to figure out how to run tests in the iOS simulator, and I stumbled upon [this line](https://github.com/JetBrains/kotlin-native/blob/master/buildSrc/plugins/src/main/kotlin/org/jetbrains/kotlin/ExecutorService.kt#L162). I'm going to make my own gradle task for running iOS tests, but it'd be great if the kotlin-multiplatform plugin generated this for you. Thank you!

**Comment by benasher44** [comment]
Adding something to your project like this seems to work:
```
afterEvaluate {

    def simulatorName = 'iPad Air 2'
    def testExeTask = linkTestDebugExecutableIosSim

    task("runIosSimTests", type: Exec, dependsOn: [testExeTask], group: "iOS") {
        doFirst {
            println(testExeTask.outputFile.get())
        }
        executable 'xcrun'
        args = [
                'simctl',
                'spawn',
                simulatorName,
                testExeTask.outputFile.get()
        ]
        ignoreExitValue = true
    }
}
```

**Comment by benasher44** [comment]
this is assuming you have a call like `fromPreset(presets.iosX64, 'iosSim')` in your build.gradle, which would generate the `linkTestDebugExecutableIosSim` task

**Comment by benasher44** [comment]
With something like this, it'd be nice to be able to configure what simulator you want the tests to run on (with some default in place, maybe derived from the result of `xcrun simct list`).

**Comment by 9468305** [comment]
I create an injection action like this, now the workflow of `gradle check` is: run `test` -> run `iosTest` -> `check` finished.
```
tasks.register("iosTest") {
    mustRunAfter("test")
    doLast {
        exec {
            commandLine("xcrun", "simctl", "spawn", "iPhone 8", iosTestBinary.absolutePath)
        }
    }
}

tasks.named("check") {
    dependsOn("iosTest")
}
```

Formerly I try this way, but failed as `Task with name 'test' not found in root project `.
```
tasks.register("iosTest") {
...
}

tasks.named("test") {
    finalizedBy("iosTest")
}
```

**Comment by 9468305** [comment]
I've found that `okio` is using default kotlin gradle plugin to implement iOS/Native tests, without additional configuration.

https://github.com/square/okio/blob/master/okio/build.gradle
https://github.com/square/okio/issues/615

**Comment by benasher44** [comment]
Where do you see that? All native test targets are created, and many include runners. There isn’t one for iOS though

**Comment by 9468305** [comment]
I download it, import to IntelliJ, build and run, then gradle tasks show native unit test case results, which as same as `xcrun simctl ...`.  Maybe not include tests for iOS SDK API ?
I haven't figure out source code, but it seems can replace `call xcrun simctl ...`

**Comment by benasher44** [comment]
If there's an iOS test runner, then they're creating the test task themselves. Searching JetBrains/Kotlin, this is the only current reference to `xcrun`: https://github.com/JetBrains/kotlin/blob/f32d48c66d3f17e8e6483e1fd0e776d75037ffb0/idea/idea-gradle/src/org/jetbrains/kotlin/idea/configuration/KotlinGradleMobileSharedMultiplatformModuleBuilder.kt#L186. There, they generate the task boilerplate, which I believe you can see if you use one of their wizards to create a new project.

**Comment by 9468305** [comment]
Yeah, you are right. So I guess https://github.com/square/okio/blob/master/okio/build.gradle#L78 just match and trigger native target tests. 
I'll go deeper later. Thank you.

**Comment by benasher44** [comment]
One is now provided as part of the mpp library target. This also isn't a K/N issue but one for the mpp plugin. Closing
