### ISSUE TITLE
kotlin.native.concurrent in module-java.info

### ISSUE THREAD

**Issue by Burtan** [JetBrains/kotlin-native#2579]
Currently kotlin.native.concurrent cannot be used in a modular application:

`Error: java.lang.IllegalArgumentException: kotlin.native.concurrent: Invalid package name: 'native' is not a Java identifier`

**Comment by Burtan** [comment]
This is not 100% right, there are two classes which are available for java. 

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native.concurrent/index.html

**Comment by jreznot** [comment]
Since Kotlin 1.3 we cannot modularize kotlin-stdlib anymore due to this `native` name of the package.

JLink cannot process such a package:
```
Error: java.lang.IllegalArgumentException: kotlin.native.concurrent: Invalid package name: 'native' is not a Java identifier
```
