### ISSUE TITLE
getTimeMillis() for posix platforms gives some strange output

### ISSUE THREAD

**Issue by TheIndifferent** [JetBrains/kotlin-native#2583]
When using `getTimeMillis()` from `kotlin.system` on Posix platform, it returns only about 30 hours instead of 60+ years.

The code to reproduce the issue:
```
package sample.dateformat

import kotlinx.cinterop.*
import platform.posix.*
import kotlin.system.getTimeMillis

fun main(args: Array<String>) {
    val timeSeconds: Long = getTimeMillis() / 1000
    println(timeSeconds)
    memScoped {
        val timeRef: CPointer<tm>? = localtime(cValuesOf(timeSeconds))
        val buffer: CArrayPointer<ByteVar> = allocArray<ByteVar>(20)
        if (strftime(buffer, 20, "%Y-%m-%dT%H-%M-%S", timeRef) == 0UL) {
            throw Exception("Failed to format date")
        }
        println(buffer.toKString())
    }
}
```

Full working reproducer project:
https://github.com/TheIndifferent/kotlin-gettimemillis

At the same time, replacing `getTimeMillis()` with `time(null)` (the one from stdlib) returns the correct time and is formatted correctly:
https://github.com/TheIndifferent/kotlin-native/commit/518d3f9cb0894b7c595f5ac246fe41db82d5506c

**Comment by SvyatoslavScherbina** [comment]
`getTimeMillis()` is not supposed to return Unix time (i.e. time since 1 January 1970).
The documentation is not clear enough on that though.

**Comment by olonho** [comment]
To obtain time since epoch use `platform.posix.gettimeofday`.

**Comment by TheIndifferent** [comment]
I see... So what is the `epoch` for Kotlin then? Could this issue be marked as issue with documentation so it will be more clear on how to use `getTimeMillis()` exactly and why we might need it?

**Comment by SvyatoslavScherbina** [comment]
Yes, we consider this issue as issue with documentation and going to make it more clear.
`getTimeMillis` is supposed to be used to compute time deltas, e.g. to measure a duration.

**Comment by olonho** [comment]
Fixed the docs, closing.
