### ISSUE TITLE
Static analysis for unsupported host targets in IntelliJ

### ISSUE THREAD

**Issue by serebit** [JetBrains/kotlin-native#2585]
This would greatly benefit those who develop for kotlin/native on a single platform, but use remote CI/CD to build, test, and deploy artifacts.

**Comment by sbogolepov** [comment]
Hi. What specific use-cases do you mean?

**Comment by serebit** [comment]
Say someone wants to build their mostly-common multiplatform application for MacOS, but they don't have a Mac to develop on locally. They could add a MacOS target and use IntelliJ static analysis to make sure their code at least doesn't have any syntax errors or statically resolveable problems, then test it with something like CircleCI.

**Comment by sbogolepov** [comment]
The case with Apple platforms is a tricky one from license side of view. To make static analysis usable, we need to provide declarations for `platform.*` libraries (Apple frameworks in this case). AFAIK, Apple might not like it.
Another example is MinGW, but it can be solved differently (see https://youtrack.jetbrains.com/issue/KT-43024).

**Comment by serebit** [comment]
I didn't realize Apple was stringent enough to not only prevent cross-compilation, but also prevent the mere exposure of platform APIs without implementations. Seems a bit over-protective and not legally enforceable, really.

That said, given that I have no interest in developing for Apple platforms while they continue to intentionally hamper efforts to do so from non-Apple hardware, I'd settle for stable MinGW cross-compilation.

**Comment by sbogolepov** [comment]
I'll close the issue then. Feel free to open a new one at http://kotl.in/issue if you come up with a new case :)
