### ISSUE TITLE
Kotlin native gradle plugin generates iOS framework with invalid naming ("-" converted to "_")

### ISSUE THREAD

**Issue by mikezliu** [JetBrains/kotlin-native#2588]
My kotlin native project has hyphens in it (i.e. my-shared-project). When the kotlin native gradle plugin generates an iOS frameowork, it renames it into my_shared_project.framework, which is invalid naming and can't be submitted to the app store.  The app store only allows hyphens in embedded frameworks (my-shared-project is valid, my_shared_project is not valid).  I couldn't find an easy way to change the name in the generated framework, so in the end I ended up renaming my kotlin native project to mySharedProject, which doesn't follow the naming convention used in my other projects.

**Comment by ilmat192** [comment]
Thank you for the report. Looks like it can be fixed easily.

As a workaround you can specify a name for a framework using the `baseName` property introduced in 1.3.20:
```
kotlin {
    iosArm64 {
        binaries {
            framework {
                // Base name for the output file. foo.framework will be produced.
                baseName = "foo"
            }
        }
    }
}
```

See also: https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries

**Comment by mikezliu** [comment]
Thanks, will take a look
