### ISSUE TITLE
Ios framework module name changed after update from gradle 4.7 to gradle 4.10

### ISSUE THREAD

**Issue by pauliusrum** [JetBrains/kotlin-native#2590]
Hello,

after update from gradle 4.7 to gradle 4.10 the ios framework module name changes

With gradle 4.7:
```
framework module common {
    umbrella header "common.h"

    export *
    module * { export * }
}
```

With gradle 4.10
```
framework module main {
    umbrella header "main.h"

    export *
    module * { export * }
}
```

Can I specify an argument that would generate the previous module that was `common` instead of `main`?

**Comment by pauliusrum** [comment]
Adding this code snippet fixed the issue:
```
 compilations.main.extraOpts '-output', "$buildDir/bin/eld_common.framework"
```

**Comment by ilmat192** [comment]
Could you provide a gradle buildscript you use? 

In 1.3.20 the default name for frameworks declared using the `compilation.outputKinds` was really changed. But also a [DSL](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries) allowing one to declare and customize final binaries independently (including the output name) was introduced. You can use it instead of `compilation.outputKinds` as it done in the MPP example: https://github.com/JetBrains/kotlin-mpp-example/compare/1f8d3a535291c4618fed2da62b8736688e1ae846...44034c1179e6890d3e2de85c4d1828196069850a.

**Comment by pauliusrum** [comment]
I was using this configuration in  4.7:

```
kotlin {
    targets {
        fromPreset(project.hasProperty('iosDevice') ? presets.iosArm64 : presets.iosX64, 'ios') {
            compilations.main.outputKinds 'framework'
        }
    }
}

task iosFramework {
    def buildType = project.findProperty('kotlin.build.type') ?: 'debug'

    group = JavaBasePlugin.BUILD_TASK_NAME
    description = 'Compiles and packages Objective-C framework'

    dependsOn "link${buildType.toLowerCase().capitalize()}FrameworkIos"
    doLast {
        def binary = kotlin.targets.ios.compilations.main.getBinary('framework', buildType)

        copy {
            from binary
            into "$buildDir/bin/common.framework/"
            include '**/*'
        }
    }
}
```

It would generate ios framework that i could import in swift as `import common`. To achieve the same result after 4.10 i changed the build script since it did not continue to generate the same outputs as before:

```
kotlin {
    targets {
        fromPreset(project.hasProperty('iosDevice') ? presets.iosArm64 : presets.iosX64, 'ios') {
            compilations.main.outputKinds 'framework'
        }
    }
}

task iosFramework {
    def buildType = project.findProperty('kotlin.build.type') ?: 'debug'

    group = JavaBasePlugin.BUILD_TASK_NAME
    description = 'Compiles and packages Objective-C framework'

    kotlin.targets.ios.compilations.main.extraOpts '-output', "$buildDir/bin/common.framework"

    dependsOn "linkMain${buildType.toLowerCase().capitalize()}FrameworkIos"
}
```

I did this because i could not find any other way how one could change the framework name.
https://github.com/JetBrains/kotlin-native/blob/d02a51ba98a2f68080a0a77cbcd3c7592ad31ae3/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExport.kt#L70
