### ISSUE TITLE
`String.wcstr` not usable with `wcsftime` on Linux

### ISSUE THREAD

**Issue by nlbuescher** [JetBrains/kotlin-native#2609]
Arch Linux
IntelliJ IDEA CE
Gradle 4.10
Kotlin MPP 1.3.20

Given:
```kotlin
val String.wcstr: CValues<UShortVar>
```

I am unable to pass a string literal to the wcsftime function like so:
```kotlin
memScoped {
    val t = alloc<time_tVar>()
    time(t.ptr)
    val str = allocArray<wchar_tVar>(8)
    wcsftime(str, 8u, "%T".wcstr, localtime(t.ptr))
    val timeString = str.toKString()
}
```

The error:
```
Type mismatch.
Required: CValuesRef<wchar_tVar /* = IntVarOf<wchar_t /* = Int */> */>?
Found: CValues<UShortVar /* = UShortVarOf<UShort> */>
```

The problem seems to be that `wchar_t` is defined as `int` in GCC and Clang on Linux, but Kotlin/Native defines it as `ushort` instead.

This similarly seems to break the `toKString()` functionality:
```
None of the following functions can be called with the arguments supplied.
CPointer<ByteVar /* = ByteVarOf<Byte> */>.toKString() defined in kotlinx.cinterop
CPointer<ShortVar /* = ShortVarOf<Short> */>.toKString() defined in kotlinx.cinterop
CPointer<UShortVar /* = UShortVarOf<UShort> */>.toKString() defined in kotlinx.cinterop
```

**Comment by olonho** [comment]
One could write custom conversion extension values to arbitrary type, for example 4 byte wchar, for example using iconv platform library. Kotlin/Native doesn’t support this type out if the box.

**Comment by nlbuescher** [comment]
What I'm saying isn't that `String.wcstr` should be defined as `String.wcstr: CValues<wchar_tVar>`. That won't work. I get that. But since the `platform.posix` package is already platform dependent, is it possibly to make `String.wcstr` also platform dependent, and define it as `Cvalues<IntVar>` for linux, or is there some reason this is not possible?

**Comment by olonho** [comment]
Currently string accessors are part of interop runtime, not of platform libs.

**Comment by olonho** [comment]
Take a look on https://github.com/JetBrains/kotlin-native/pull/2689

**Comment by olonho** [comment]
Fixed, added `String.utf32` property getter, and `toKStringFromUtf32` for opposite translation.
