### ISSUE TITLE
Support iOS i386 (32bit simulator) KonanTarget

### ISSUE THREAD

**Issue by AlecStrong** [JetBrains/kotlin-native#2615]
Our CI build runs unit tests against every supported simulator, right now it's failing attempting to link the generated kotlin framework for the i386 architecture (x32). Would it be possible to add an `iosX32` target to support old simulators?

Thanks in advance!

**Comment by olonho** [comment]
Not sure what's the practical sense of doing that.

**Comment by AlecStrong** [comment]
our continuous integration enumerates all the supported iOS builds and runs unit tests in a simulator on them. We support iOS 10 which has arm32 devices supported still, and the simulators that run those images need i386.

**Comment by olonho** [comment]
Considering Apple is phasing out 32-but phones/tablets, and iOS 11 doesn't support 32-bit devices, not sure is 32-bit simulator is critical for most users. Is it indeed absolutely critical in your case?

**Comment by thevery** [comment]
AFAIK Apple Watch (except latest Series 4) is still 32-bit. But watch also requires mandatory bitcode.

**Comment by olonho** [comment]
watchOS is different story, and we may eventually support it.

**Comment by AlecStrong** [comment]
got it - thanks for clarification

**Comment by tylerwilson** [comment]
+1 for x32 support, if it is not too onerous. I am running into an issue with arm32 and it might be useful to be able to debug in the iPhone 5/4S simulator.

**Comment by SvyatoslavScherbina** [comment]
We have no plans to support 32-bit iOS simulator.
32-bit iOS is obsolete, and also it is unclear what prevents one from testing and debugging on a 64-bit emulator:
so far we haven't seen an example of an issue reproducible on both 32-bit device and 32-bit simulator but not on 64-bit device or simulator
