### ISSUE TITLE
Cross-compile mingw target from linux and mac hosts

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#2621]
AFAIK simplest possible way to do so is running native windows msys2-mingw toolchain under wine64 wrapper.
I tried under latest full wine 4.0 - at least this works, with two warnings:
```
$ wine64 ~/.konan/dependencies/msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1/bin/clang.exe hello.c -o hello.exe
0009:fixme:file:FindFirstFileExW flags not implemented 0x00000002
002a:fixme:file:SetFileInformationByHandle 0x60, 3, 0x27d120, 90
```
But generated `hello.exe` is valid runnable windows file:
```
$ wine64 hello.exe 
Hello World!
```

So we can ask user who want to cross-compile  to install 64-bit wine, and then adding support for mingw64 target should be relatively easy.

**Comment by olonho** [comment]
Could you try to implement such approach and see how it works?

**Comment by msink** [comment]
Will try, but first wanted to discuss - if we go this way - should we depend on user-installed wine, or build our own and download as regular dependency?

I tried to build trimmed to bare minimum version:
```
#! /bin/sh

./configure \
  --prefix=/home/msink/.konan/dependencies/wine64-4.0-1-linux-x86-64 \
  --enable-win64          \
  --disable-win16         \
  --disable-tests         \
  --without-alsa          \
  --without-capi          \
  --without-cms           \
  --without-coreaudio     \
  --without-cups          \
  --with-curses           \
  --without-dbus          \
  --without-fontconfig    \
  --without-freetype      \
  --with-gettext          \
  --without-gphoto        \
  --without-glu           \
  --without-gnutls        \
  --without-gsm           \
  --without-gssapi        \
  --without-gstreamer     \
  --without-hal           \
  --without-jpeg          \
  --without-krb5          \
  --without-ldap          \
  --without-mpg123        \
  --without-netapi        \
  --without-openal        \
  --without-opencl        \
  --without-opengl        \
  --without-osmesa        \
  --without-oss           \
  --without-pcap          \
  --with-png              \
  --with-pthread          \
  --without-pulse         \
  --without-sane          \
  --without-sdl           \
  --without-tiff          \
  --without-udev          \
  --without-v4l           \
  --without-vkd3d         \
  --without-vulkan        \
  --without-xcomposite    \
  --without-xcursor       \
  --without-xfixes        \
  --without-xinerama      \
  --without-xinput        \
  --without-xinput2       \
  --without-xml           \
  --without-xrandr        \
  --without-xrender       \
  --without-xshape        \
  --without-xshm          \
  --without-xslt          \
  --without-xxf86vm       \
  --without-x             \
  || exit 1

make || exit 1

make install-lib || exit 1
```

It builds and works, but contains harcoded paths to my home dir, what is wrong.
How to make it portable - I do not know, not an expert in this area.

**Comment by olonho** [comment]
Guess it's better to use user's Wine.

**Comment by msink** [comment]
Well, tried in #2629 : it fails with message
```
> Task :runtime:mingw_x64Runtime FAILED
clang-6.0: error: unsupported option '-fPIC' for target 'x86_64-w64-windows-gnu'
```
Again, how to debug that kind of errors - I do not know, sorry.

**Comment by olonho** [comment]
This indeed looks like a bug. Created WIP PR which includes code from this one at. https://github.com/JetBrains/kotlin-native/pull/2635

**Comment by olonho** [comment]
Merged experimental mingw support on Linux and macOS as part of bf7040a119c77b7a5128e5ed40d0b749eb098e77.

**Comment by AlecStrong** [comment]
is it possible to target mingW from Mac is you're using the kotlin multiplatform gradle plugin? or is this feature only available if you compile kotlin native yourself with the property set?

**Comment by msink** [comment]
There was old PR: https://github.com/JetBrains/kotlin/pull/2639
But still not merged, don't know why.

**Comment by AlecStrong** [comment]
Any chance it could get revisited/merged? It would make setting up CI for libraries dead simple if I could deploy all artifacts from one machine
