### ISSUE TITLE
Error when set Callback for Singleton

### ISSUE THREAD

**Issue by lehanphong** [JetBrains/kotlin-native#2625]
I want show Log for my app from kotlin-native, but have error runtime. please help me!!! thank U

> Singleton LogShareCode constructor runInstances of kotlin.Error, kotlin.RuntimeException and subclasses aren't propagated from Kotlin to Objective-C/Swift.
Other exceptions can be propagated as NSError if method has or inherits @Throws annotation.
Uncaught Kotlin exception: kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen vn.com.vndirect.sharecode.utils.LogShareCode@25b4388
        at 0   main                                0x0000000105f5a2d6 kfun:kotlin.Exception.<init>(kotlin.String?)kotlin.Exception + 70
        at 1   main                                0x0000000105f5a1f6 kfun:kotlin.RuntimeException.<init>(kotlin.String?)kotlin.RuntimeException + 70
        at 2   main                                0x0000000105f5bb26 kfun:kotlin.native.concurrent.InvalidMutabilityException.<init>(kotlin.String)kotlin.native.concurrent.InvalidMutabilityException + 70
        at 3   main                                0x0000000105ff6d63 ThrowInvalidMutabilityException + 275
        at 4   main                                0x0000000106019732 MutationCheck + 50
        at 5   main                                0x0000000105f33823 kfun:vn.com.vndirect.sharecode.utils.LogShareCode.<set-listener>(vn.com.vndirect.sharecode.utils.LogShareCodeListener?) + 67
        at 6   main                                0x0000000105f33775 kfun:vn.com.vndirect.sharecode.utils.LogShareCode.<init>()vn.com.vndirect.sharecode.utils.LogShareCode + 1413
        at 7   DPro                                0x0000000105c2b654 $S4DPro14ViewControllerC11viewDidLoadyyFTo + 36
        at 8   UIKitCore                           0x00000001106c74e1 -[UIViewController loadViewIfRequired] + 1186
        at 9   UIKitCore                           0x00000001106c7940 -[UIViewController view] + 27
        at 10  UIKitCore                           0x0000000110d1ec53 -[UIWindow addRootViewControllerViewIfPossible] + 122
        at 11  UIKitCore                           0x0000000110d1f36e -[UIWindow _setHidden:forced:] + 294
        at 12  UIKitCore                           0x0000000110d325c0 -[UIWindow makeKeyAndVisible] + 42
        at 13  UIKitCore                           0x0000000110cdf833 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4595
        at 14  UIKitCore                           0x0000000110ce4c2f -[UIApplication _runWithMainScene:transitionContext:completion:] + 1623
        at 15  UIKitCore                           0x00000001105034e9 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
        at 16  UIKitCore                           0x000000011050c29c +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
        at 17  UIKitCore                           0x0000000110503126 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 233
        at 18  UIKitCore                           0x0000000110503ae0 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1085
        at 19  UIKitCore                           0x0000000110501cb5 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 795
        at 20  UIKitCore                           0x000000011050195f -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 435
        at 21  UIKitCore                           0x0000000110506a90 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 584
        at 22  UIKitCore                           0x000000011050780e _performActionsWithDelayForTransitionContext + 100
        at 23  UIKitCore                           0x00000001105067ef -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 221
        at 24  UIKitCore                           0x000000011050b93a -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
        at 25  UIKitCore                           0x0000000110ce344e -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
        at 26  UIKitCore                           0x0000000110887d09 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 357
        at 27  FrontBoardServices                  0x0000000113a632da -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
        at 28  FrontBoardServices                  0x0000000113a6e443 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 271

Kotlin
```
class Log private constructor() {
    var listenner: LogShareCodeListener? = null
    companion object {
        val instance: Log by lazy {
            Log()
        }
    }
    fun d(tag : String, mess: String?) {
        listenner?.onDebug(tag, mess)
    }
    fun e(e: String?) {
        listenner?.onError(e)
    }
    fun r(runTo : String?) {
        listenner?.onRunTo(runTo)
    }
}
```

Swift:
`LogShareCode.Companion.init().instance.listener = self`

**Comment by olonho** [comment]
Yes, singletons are immutable after creation. See https://github.com/JetBrains/kotlin-native/issues/2619. Also we'd recommend search for similar issue before reporting new one.

**Comment by lehanphong** [comment]
thank @olonho  and sorry because similar issue.
