### ISSUE TITLE
Build ios framework error when using "import platform.Foundation.NSLog"

### ISSUE THREAD

**Issue by lehanphong** [JetBrains/kotlin-native#2637]
I have error when build IOS framework, this is my code
```
actual fun platformName1(): String {
    NSLog("DEBUG %@ ", "Duc")
    return UIDevice.currentDevice.systemName() +
            " " +
            UIDevice.currentDevice.systemVersion
}
```
if I remove NSLog("DEBUG %@ ", "Duc") -> build success
<img width="803" alt="screen shot 2019-02-07 at 5 15 31 pm" src="https://user-images.githubusercontent.com/11489659/52404622-07a6ae00-2afc-11e9-9fd5-3159f0daf480.png">

**Comment by olonho** [comment]
Yes, this is known issue fixed in 1.3.21.

**Comment by ilmat192** [comment]
As a workaround you can manually disable bitcode-embedding as shown [here](https://github.com/JetBrains/kotlin-mpp-example/blob/master/greeting/build.gradle#L46).

Note that in this example usage of `compilation.outputKinds` is replaced with usage of the binaries DSL introduced in 1.3.20 (see the [diff](https://github.com/JetBrains/kotlin-mpp-example/compare/1f8d3a535291c4618fed2da62b8736688e1ae846...44034c1179e6890d3e2de85c4d1828196069850a)).

**Comment by lehanphong** [comment]
@olonho  thank you
