### ISSUE TITLE
 `ld: framework not found` after update to kotlin 1.3.21

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#2639]
After update from kotlin 1.3.11 & gradle 4.7 to kotlin 1.3.21 & gradle 4.10(along with serialization to 0.10.0 & coroutines to 1.1.1) weird things started to happen.

Particularly, the linker can't find 3rd party frameworks and fails with messages like:
```
ld: framework not found Crashlytics
error: /Applications/Xcode10.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
```

Here is iOS part of my `build.gradle`(which has the only change related to `binaries` block):
```
kotlin {
    targets {
        def buildForDevice = project.findProperty("device")?.toBoolean() ?: false
        def iosPreset = (buildForDevice) ? presets.iosArm64 : presets.iosX64
        fromPreset(iosPreset, 'ios') {
            binaries { framework {} }

//         here is what used to be instead of 'binaries' line:
//         compilations.main.outputKinds('FRAMEWORK')
        }

        configure([ios]) {
            compilations.main {
                linkerOpts "-F../ios-app/frameworks"

                cinterops {
                    crashlytics {
                        defFile '../ios-app/cinterop/Crashlytics.def'
                        includeDirs '../ios-app/cinterop'
                    }
                    ...
                }
            }
        }
    }
    ...
}
```

`Crashlytics.def`:
```
language = Objective-C
package = frameworks.Crashlytics
headers = Crashlytics/Crashlytics.h
headerFilter = Crashlytics/**

compilerOpts = -framework Crashlytics
linkerOpts = -framework Crashlytics
```

I assume paths are ok, since the project builds with kotlin 1.3.11. Moreover headers seem to be found with kotlin 1.3.21 since compilation step is passed.

So the question is what is wrong with frameworks paths.
Is it a known issue? #2312 sounds somewhat similar.
Is there a way to dump `ld` invocation to check paths?

**Comment by olonho** [comment]
Seems relative paths is somewhat incorrect.  Could you try to compute absolute path on Gradle side?
`-Xverbose-phases=linker` shall help you.

**Comment by ildarsharafutdinov** [comment]
I hardcoded absolute path to the framework `linkerOpts "-F/my/absoulte/path"`.
I made sure the framework is there: 
```
> ls /my/absoulte/path
> Crashlytics.framework
```

This didn't fix the error.

I also didn't figure out how/where to pass `-Xverbose-phases=linker`.

**Comment by ildarsharafutdinov** [comment]
Also, having that paths are the same, why the issue arises in kotlin 1.3.21 and not 1.3.11?

**Comment by ilmat192** [comment]
`linkerOpts` property of a compilation affects only binaries created using the `compilations.outputKinds` call. If a binary is created using the binaries DSL, you need to configure its linker options in a corresponding code block:

```
binaries {
    framework {
        linkerOpts = [...]
    }
}
```

**Comment by olonho** [comment]
`compilations["main"].kotlinOptions.freeCompilerArgs = ["-Xverbose-phases=linker"]`

**Comment by ildarsharafutdinov** [comment]
@ilmat192 , @olonho ,

Thanks.

I moved `linkerOpts` up to `binaries.framework` and it solved the issue.

Is there more info on what else is affected by switch from `compilations.main.outputKinds('FRAMEWORK')` to  `binaries { framework {} }`?

**Comment by ilmat192** [comment]
Accessing binaries using API's provided by compilations (like `compilation.getBinary`) is affected. These API can return only binaries created with the `compilations.outputKinds` approach.

See how the MPP example is ported to the new DSL: [diff](https://github.com/JetBrains/kotlin-mpp-example/compare/1f8d3a535291c4618fed2da62b8736688e1ae846...44034c1179e6890d3e2de85c4d1828196069850a).

**Comment by sellmair** [comment]
I followed the diff given by @ilmat192  and still get this error 😢 
Here is my common codes build.gradle.kts

```

@file:Suppress("UNUSED_VARIABLE")

plugins {
    kotlin("multiplatform")
}

kotlin {
    val jvm = jvm()
    macosX64()

    //val ios = if (System.getenv("SDK_NAME")?.toLowerCase()?.startsWith("iphoneos") == true) iosArm64("ios") else iosX64("ios")
    val ios = iosX64("ios")
    ios.binaries {
        framework {
            embedBitcode("disable")
        }
    }


    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(Deps.Kotlin.StdLib.common)
                implementation(Deps.quantum)
                implementation(Deps.Kotlin.Coroutines.common)
                implementation(Deps.kodein)
            }
        }

        jvm.compilations["main"].defaultSourceSet {
            dependencies {
                implementation(Deps.Kotlin.Coroutines.jvm)
            }
        }

        val native by creating {
            dependsOn(getByName("commonMain"))
        }

        val nativeTest by creating {
            dependsOn(getByName("commonTest"))
        }

        macosX64().compilations["main"].defaultSourceSet {
            dependsOn(native)
        }

        macosX64().compilations["test"].defaultSourceSet {
            dependsOn(nativeTest)
        }
    }
}

apply {
    from("copyFramework.gradle")
}

```


And here is the copyFramework.gradle

```


task copyFramework {
    def buildType = project.findProperty("kotlin.build.type") ?: "DEBUG"
    dependsOn "link${buildType.toLowerCase().capitalize()}FrameworkIos"

    doLast {
        def srcFile = kotlin.targets.ios.binaries.getFramework(buildType).outputFile
        def targetDir = new File(buildDir, "framework")
        copy {
            from srcFile.parent
            into targetDir
        }
    }
}

```

**Comment by saket** [comment]
Looks like `linker` is no longer a valid argument for `Xverbose-phases`. What are the current options?

**Comment by sbogolepov** [comment]
`-Xverbose-phases=Linker` should work.
