### ISSUE TITLE
Compiling macOS Target on Linux and Windows hosts

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#2641]
This should be technically possible using https://github.com/tpoechtrager/osxcross , but I'm not sure in legal status of that approach.
So does it worth investigating?

**Comment by olonho** [comment]
Not sure if this is worth investigating, as https://www.apple.com/legal/sla/docs/xcode.pdf clearly states
"Install a reasonable number of copies of the Apple Software on Apple-branded computers that
are owned or controlled by You to be used internally by You or Your Authorized Developers only as
follows:"
