### ISSUE TITLE
 mach-o, but wrong architecture

### ISSUE THREAD

**Issue by Tripwire999** [JetBrains/kotlin-native#2643]
Hi,

I've followed the guid on the Kotlin native website to setup an multiplatform project in Android Studio. Everything works fine on Android and on the iOS Simulator. But somehow I can't get my iOS app to run on my iPhone 8 plus. Even when I force the iOSTarget to presets.iosArm64 it compiles but crashes immediately with the error:
**mach-o, but wrong architecture**

My SharedCode gradle:
`apply plugin: 'kotlin-multiplatform'

kotlin {
    targets {
        final def iOSTarget = System.getenv('SDK_NAME')?.startsWith("iphoneos") ? presets.iosArm64 : presets.iosX64

        fromPreset(iOSTarget, 'iOS') {
            compilations.main.outputKinds('FRAMEWORK')
        }

        fromPreset(presets.jvm, 'android')
    }

    sourceSets {
        commonMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib-common'
        }

        androidMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib'
        }

        iosMain.dependencies {
        }
    }
}

task packForXCode(type: Sync) {
    final File frameworkDir = new File(buildDir, "xcode-frameworks")
    final String mode = project.findProperty("XCODE_CONFIGURATION")?.toUpperCase() ?: 'DEBUG'

    inputs.property "mode", mode
    dependsOn kotlin.targets.iOS.compilations.main.linkTaskName("FRAMEWORK", mode)

    from { kotlin.targets.iOS.compilations.main.getBinary("FRAMEWORK", mode).parentFile }
    into frameworkDir

    doLast {
        new File(frameworkDir, 'gradlew').with {
            text = "#!/bin/bash\nexport 'JAVA_HOME=${System.getProperty("java.home")}'\ncd '${rootProject.rootDir}'\n./gradlew \$@\n"
            setExecutable(true)
        }
    }
}

tasks.build.dependsOn packForXCode

// workaround for https://youtrack.jetbrains.com/issue/KT-27170
configurations {
    compileClasspath
}`

**Comment by SvyatoslavScherbina** [comment]
Could you please post the complete error message?

**Comment by olonho** [comment]
If there will be no additional info we had to close the report. Generally it seems produced binary is for the wrong arch.

**Comment by SaifurRahmanMohsin** [comment]
Same bug. [Link to full report](https://scans.gradle.com/s/yoestj7ssiqye/console-log?task=:shared:linkDebugFrameworkIos)
