### ISSUE TITLE
How use KClass<*> in Java classes

### ISSUE THREAD

**Issue by ImanX** [JetBrains/kotlin-native#2652]
I declared a function with generic types, I will use it in java classes but that isn't valid in java.
can I use it generic type reflect in kotlin native ?

in kotlin class:
```kotlin
 fun <T : Type> buildMethod(clazz: KClass<T>): T {
        return Type() as T;
    }
```

in java class when use it:
```java
 Request request = new Request(MethodType.Query);
        a.buildMethod(CellNumber.class); //
```

```exception
error: method buildMethod in class Request cannot be applied to given types;
required: KClass<T>
found: Class<CellNumber>
reason: cannot infer type-variable(s) T
(argument mismatch; Class<CellNumber> cannot be converted to KClass<T>)
where T is a type-variable:
T extends Type declared in method <T>buildMethod(KClass<T>)
```

**Comment by SvyatoslavScherbina** [comment]
`java.lang.Class` and `KClass` are different types.
You can convert former to latter by using [`.kotlin` extension property](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/java.lang.-class/kotlin.html).
To use `buildMethod` from Java you can define a wrapper in Android- or JVM-specific source set of your Kotlin multiplatform project.

**Comment by olonho** [comment]
No more feedback, closing.
