### ISSUE TITLE
Segfault when calling _instance on a singleton object before anything else

### ISSUE THREAD

**Issue by medlefsen** [JetBrains/kotlin-native#2657]
Using the example library at https://kotlinlang.org/docs/tutorials/native/dynamic-libraries.html and compiling to either a static or dynamic library, when I call _instance on the Object singleton *before* I call any other functions, it immediately segfaults (gdb tells me in FreezeSubgraph).

Here is small example zip: 
[bug.zip](https://github.com/JetBrains/kotlin-native/files/2860483/bug.zip)

If I call a different function first, everything works fine.

I'm on Arch Linux, but have also reproduced on Ubuntu 18.04. Tested with Kotlin/Native versions 1.0.3 and 1.1.2

Thanks

**Comment by olonho** [comment]
Shall be fixed with https://github.com/JetBrains/kotlin-native/pull/2658
