### ISSUE TITLE
Deeply nested types not visible from Swift

### ISSUE THREAD

**Issue by Zanfa** [JetBrains/kotlin-native#2667]
Any type that is nested more than once isn't accessible by it's `swift_name`. Consider the following Kotlin type definition:
```
data class A(val b: B) {
    data class B(val c: C) {
        object C
    }
}
```

Which generates the following header:

```
...

__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("A.B.C")))
@interface SharedCodeABC : KotlinBase
- (instancetype)initWithName:(NSString *)name __attribute__((swift_name("init(name:)"))) __attribute__((objc_designated_initializer));
- (NSString *)component1 __attribute__((swift_name("component1()")));
- (SharedCodeABC *)doCopyName:(NSString *)name __attribute__((swift_name("doCopy(name:)")));
@property (readonly) NSString *name;
@end;

...
```

However, when trying to initialize it in Swift by calling `A.B.C()`, you get `Type 'A.B' has no member 'C'`. Using `SharedCodeABC()` still works fine though, it's just the type as shortened by `swift_name` that Swift doesn't recognize.

**Comment by SvyatoslavScherbina** [comment]
Confirmed. Thank you for the report!
