### ISSUE TITLE
What's the difference between konan and multiplatform plugin?

### ISSUE THREAD

**Issue by 9468305** [JetBrains/kotlin-native#2669]
There are two plugins, "org.jetbrains.kotlin.konan" and "org.jetbrains.kotlin.multiplatform".
What's the difference between them?

From here: https://kotlinlang.org/docs/tutorials/native/gradle-for-kotlin-native.html, it use "konan".
But when I use IDEA 2018.3.4 to create a new Kotlin/Native project, it use "kotlin-multiplatform".

BTW:
kotlin-multiplatform 1.3.21 auto download kotlin-native-macos-1.1.2.(I expect the latest 1.3.11!)

**Comment by olonho** [comment]
Please use org.jetbrains.kotlin.multiplatform - it is the the plugin which is being developed and is supported in tooling.

**Comment by 9468305** [comment]
Thanks.

**Comment by eino-makitalo** [comment]
Is this multiplatform also planned to some how install cinterop. It's now only in windows ~/.konan/kotlin/kotlin-native-windows-1.1.2/bin
