### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ImanX** [JetBrains/kotlin-native#2673]
I developed a lib by Kotlin native, all of things are ok in ios and android emulators
Today, I deployed project in Xcode on physically device but it didn't run. 
and get exception: 
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ZPAPIAPI", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_ZPAPIKotlinUnit", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_ZPAPIMe", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_ZPAPIMethodType", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_ZPAPIRequest", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I think my lib isn't arm64 for compile on iOS devices.

**Comment by nlhien** [comment]
@ImanX Did you resolve the issue? I am facing the same problem.

**Comment by vikihleblya** [comment]
@ImanX Did you fix this problem?

**Comment by ImanX** [comment]
@nlhien @vikihleblya Yes, That has solved.

**Comment by sigurdurrafn** [comment]
@ImanX How did you solve this issue? Was there something wrong with the gradle setup?

**Comment by zsperske** [comment]
Sooooo sad to come across this with no solution posted :(

**Comment by sigurdurrafn** [comment]
I was making separate binaries for iPhone(arm) and the xcode simulator(x86) and I would sometimes bump into this, like the wrong architecture had been compiled or linked incorrectly somehow.

In the end, I started building a cocoapod that includes both binaries and haven't run into it since.
