### ISSUE TITLE
Kotlin version mapping to Kotlin Native version?

### ISSUE THREAD

**Issue by 9468305** [JetBrains/kotlin-native#2678]
I'm confused with Kotlin version and Kotlin Native version which in [release page](https://github.com/JetBrains/kotlin/releases).

Kotlin 1.3.11 mapping to Kotlin Native 1.3.11, https://github.com/JetBrains/kotlin/releases/tag/v1.3.11
But Kotlin 1.3.21 mapping to Kotlin Native 1.1.2, https://github.com/JetBrains/kotlin/releases/tag/v1.3.21, which is degrade?

**Comment by olonho** [comment]
There's single Kotlin versioning, current version of Kotlin is 1.3.20.

**Comment by 9468305** [comment]
@olonho My confusion is Kotlin Native 1.3.11 vs Kotlin Native 1.1.2, is this degrade version number or something else?

**Comment by Guang1234567** [comment]
@9468305 

`v1.1.2` is a `git tag`,   and  `Kotlin 1.3.20` is a `branch`

**Comment by msink** [comment]
Just reverse - `kotlin-1.3.20` is git tag, and `v1.1.0-fixes` is branch. :grin:

**Comment by olonho** [comment]
There's no such public version as Kotlin/Native 1.1.2, Kotlin/Native is now versioned same way as Kotlin. Internal branch names doesn't affect the fact that K/N is released on same schedule as rest of Kotlin, and have same versioning.

**Comment by Guang1234567** [comment]
@msink  

hahaha,   the comment above was fixed.
