### ISSUE TITLE
k/n sync failed on windows OS

### ISSUE THREAD

**Issue by hzqd** [JetBrains/kotlin-native#2687]
Hello！ I use idea and openjdk-11.0.2 to create a kotlin-native program on windows, but there are some issue about it.
Idea told me :`sync failed`
> Unable to find method 'sun.misc.Unsafe.defineClass(Ljava/lang/String;[BIILjava/lang/ClassLoader;Ljava/security/ProtectionDomain;)Ljava/lang/Class;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

How can I solve this problem ?

**Comment by SvyatoslavScherbina** [comment]
Please try to use older Java version.

**Comment by olonho** [comment]
JDK11 is not supported at the moment.

**Comment by hzqd** [comment]
thank you !
