### ISSUE TITLE
BSDs as target platform

### ISSUE THREAD

**Issue by ovalseven8** [JetBrains/kotlin-native#2690]
At your website you list the following target platforms right now:

- iOS (arm32, arm64, emulator x86_64)
- MacOS (x86_64)
- Android (arm32, arm64)
- Windows (mingw x86_64)
- Linux (x86_64, arm32, MIPS, MIPS little endian)
- WebAssembly (wasm32)

https://kotlinlang.org/docs/reference/native-overview.html#target-platforms

---

Are there any plans to support FreeBSD/OpenBSD? If no, what's the reason?

Sorry for the issue here.

**Comment by olonho** [comment]
The reasons behind adding new platforms is mostly demand, as it's not too difficult. We would consider adding FreeBSD x86_64 target support (on Linux host) as an experimental target, if someone would contribute it.

**Comment by sbogolepov** [comment]
> Are there any plans to support FreeBSD/OpenBSD? If no, what's the reason?

While adding a new target to Kotlin/Native is not too difficult, the following things are hard:
1. Support in other parts of Kotlin (e.g. kotlinx libraries)
2. Maintain it (test on CI, fix target-specific bug, update toolchains, etc.)

OTOH, it is clear that there is a demand for Kotlin/Native compilation for new environments and we are gathering information about them. So please share you use-cases [on YouTrack](https://youtrack.jetbrains.com/issue/KT-43974).
