### ISSUE TITLE
[Feature Request] Support for junit xml test logger

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2707]
Currently, the supported test loggers are [`GTEST|TEAMCITY|SIMPLE|SILENT`](https://github.com/JetBrains/kotlin-native/blob/9cd5e86dd95c0f6690f9325097731ff352d91fc5/runtime/src/main/kotlin/konan/test/TestRunner.kt#L143). It would be great to add support for junit XML output. Adding junit XML output would mean that we could get proper test reporting setup in a Jenkins CI environment.

Thanks for your consideration!

**Comment by ilmat192** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-43364](https://youtrack.jetbrains.com/issue/KT-43364).
