### ISSUE TITLE
Will encryption and decryption (like java.security) port to Kotlin/Native ?

### ISSUE THREAD

**Issue by kavanmevada** [JetBrains/kotlin-native#2716]

**Comment by olonho** [comment]
It is available on Apple platforms in `platform.CoreCrypto` package and partially on other platforms via POSIX APIs. Interop with OpenSSL or other crypto libraries is possible as well.

**Comment by kavanmevada** [comment]
I was looking for Java like library. Interop with OpenSSL is possible but if would prefer kotlin-native version of it. Thanks for help.

If Kotlin/Native team implement BigInteger and BigDecimal I would love to Implement RSA in kotlin-native.

**Comment by olonho** [comment]
Not sure if it's a good idea. Most cryptolibraries are implemented in very special way, both in terms of security and performance, and for any professional use it makes sense to interop with the existing code. Which platform do you want to run your code on?

**Comment by kavanmevada** [comment]
macOS, Linux and Windows.

**Comment by olonho** [comment]
If you need such a wide variety of platforms - interop with smth like openssl or  boringssl looks like the best option.
