### ISSUE TITLE
mixing Kotlin and Objective-C supertypes is not supported

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#2725]
hi guys,

is there a way to achieve something like this?
```
interface Disposable {
    fun dispose()
}

class X: NSObject(), Disposable { // <<< mixing Kotlin and Objective-C supertypes is not supported
    override fun dispose() {}
}
```

**Comment by ildarsharafutdinov** [comment]
> Swift/Objective-C classes and protocols can be subclassed with a Kotlin final class. Non-final Kotlin classes

I guess this is it the reason of the compiler error.
Is that right?

**Comment by SvyatoslavScherbina** [comment]
Hi. These two errors are different.

> is there a way to achieve something like this?

Please consider replacing inheritance with composition.

**Comment by francismariano** [comment]
Hello

I need implements a view interface to attach that view into my CustomPresenter. But when my class implements the View the following error is displayed: "mixing Kotlin and Objective-C supertypes is not supported". I thing the problem described is not solved with composition replacement, because with composition I am not able to attach my custom class into presenter (Please, if my supposition is wrong, let me know.).

is there a way to achieve something like this?

```
class CustomController : UIViewController, MyCustomView {

    private lateinit var presenter: CustomPresenter
    
    @OverrideInit
    constructor(coder: NSCoder) : super (coder)

    override fun viewDidLoad() {
        super.viewDidLoad()
        presenter = CustomPresenter()
    }

    override fun viewDidAppear(animated: Boolean) {
        super.viewDidAppear(animated)
        presenter.attach(view: this)
    }

    override fun viewDidDisappear(animated: Boolean) {
        presenter.detach()
        super.viewDidDisappear(animated)
}
```
Thank you in advanced.

**Comment by SvyatoslavScherbina** [comment]
Using composition:

```kotlin
class CustomController : UIViewController {

    private val myCustomView = object : MyCustomView {
        // ...
    }

    private lateinit var presenter: CustomPresenter
    
    @OverrideInit
    constructor(coder: NSCoder) : super (coder)

    override fun viewDidLoad() {
        super.viewDidLoad()
        presenter = CustomPresenter()
    }

    override fun viewDidAppear(animated: Boolean) {
        super.viewDidAppear(animated)
        presenter.attach(myCustomView)
    }

    override fun viewDidDisappear(animated: Boolean) {
        presenter.detach()
        super.viewDidDisappear(animated)
}
```

Alternatively consider writing `CustomController` in Swift.

**Comment by francismariano** [comment]
Ok, thank you.
I have written the CustomController in Swift, but I have some problems with coroutine implementation. Otherwise, I am not getting to link the CustomController.kt with my Storyboard. =(
