### ISSUE TITLE
[Feature Request] Code coverage for native

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2733]
As a next step toward improving the test runner, it’d be great to be able to build and run in a mode generates code coverage data.

Thanks!

**Comment by olonho** [comment]
First step of coverage is implemented in https://github.com/JetBrains/kotlin-native/commit/b22404c947c6f728cf7406d6725b475e77b2c84c, please take a look and report your experience.

**Comment by benasher44** [comment]
Great thanks! I'll give it a try and report back in the next week or so

**Comment by olonho** [comment]
Basic coverage support is implemented, more fine-grained issues shall be separately reported.
