### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Guang1234567** [JetBrains/kotlin-native#2738]
Hello dev:

I write a demo that calling **kotlin-native function** in C++.

Then i add **android ndk build feature**  in `build.gradle` like below code (my demo) :

https://github.com/Guang1234567/demo-android-jni-impl-by-kotlin-native/blob/da81c3763619d503e63fe092da7a62cdd2acd042/kt_mpp/build.gradle#L23-L36

Everything is ok that launched by `./gradlew :app:installDebug`,  but open in android studio 3.3 and after `gradle sync` i met a problem:

```ruby

WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: kt_mpp

```

I think there is sth wrong between  `kotlin-multiplatform gradle plugin` and [android ndk build system](https://developer.android.com/ndk/guides/cmake).

**Comment by olonho** [comment]
Not sure if there's any problem, you just got a warning.

**Comment by Guang1234567** [comment]
Yes, just got a warning, so close this issue.
