### ISSUE TITLE
Dependency on platform specific actual implementation

### ISSUE THREAD

**Issue by jcraane** [JetBrains/kotlin-native#2748]
Perhaps it is a misunderstanding from my part but what I want to do is the following:

Implementing an except declaration in commonMain with an actual implementatio in androidMain.

I have the following kotlin native module:

```
common
  commonMain
    Log.kt
  androidMain
    Log.kt
  iosMain
    Log.kt
```

commonMain/Log.kt defines for example the following method: 

`expect fun debug(message: String, vararg args: String = emptyArray())`

in androidMain/Log.kt I want to delegate the d method to Timber, like in the following example:

```
actual fun debug(message: String, vararg args: String) {
    Timber.d(message, args)
}
```

The problem is that Timber cannot be resolved. I added the following dependencies to the androidMain sourceSet:

```
androidMain.dependencies {
    implementation "com.jakewharton.timber:timber:4.7.1"
    // Other dependencies are omitted
}

```
I can see that the dependency is mentioned in the androidMain Dependencies in the Gradle tool window.

Is this the correct way of doing this? If you need any more information let me know.

Thanks in advance.

**Comment by SBNTT** [comment]
Hello,

I think you should put Timber implementation line into the root `dependencies` block, not into `androidMain.dependencies`

**Comment by jcraane** [comment]
I tried your suggestion but that does not seem to work (syntax error). The only place where dependencies are allowed in a kotlin-multiplatform module seems the dependencies of the specific source sets.

**Comment by SBNTT** [comment]
Oh, okay, I use the Mobile Android/iOS template from intellij IDEA to try. Project structure is not exactly the same as your

**Comment by jcraane** [comment]
I checked the project structure of the template and the structure is indeed a little bit different than my project. I am going to change my project so it reflects the structure of the template. That way I should be able to use the actual keyword in the source code of my Android project (including the correct dependencies, like Timber).

**Comment by artdfel** [comment]
Close as outdated. Please reopen if the problem is still here.
