### ISSUE TITLE
Non-public API usage when uploading to Appstore

### ISSUE THREAD

**Issue by NilsLattek** [JetBrains/kotlin-native#2751]
When uploading our app to the iOS appstore it gets rejected with the following error:
```
Non-public API usage:

The app references non-public selectors in Frameworks/main.framework/main: clearCache, decodeByte, decodeShort, decodeString, hasNext, isNullable, next, updateMode
```
The path states that this is happening in main.framework which is our compiled Kotlin native framework.
The method `clearCache` is one which we created ourselfs and is only called from within the common layer, implementation is like:
```kotlin
interface ScannedParcelsCache {
    // ...
    fun clearCache()
}

class ScannedParcelsCacheImpl : ScannedParcelsCache {
    // ...

    override fun clearCache() {
        scannedItemsList.clear()
    }
}
```

Looking through the main.h file I can see that the methods `decodeByte`, `decodeShort`, `isNullable`, `updateMode`and `decodeString` are from Kotlinx.serialization so also not private APIs.

`hasNext` and `next` are from:
```objc
__attribute__((swift_name("KotlinIterator")))
@protocol MainKotlinIterator
@required
- (BOOL)hasNext __attribute__((swift_name("hasNext()")));
- (id _Nullable)next __attribute__((swift_name("next()")));
@end;
```

So we are not calling any private Apple APIs and I am wondering why Apple thinks that we are. Any ideas?

gradle config:
```groovy
task packForXCode(type: Sync) {
    final File frameworkDir = new File(buildDir, "xcode-frameworks")
    final String mode = project.findProperty("XCODE_CONFIGURATION")?.toUpperCase() ?: 'DEBUG'

    inputs.property "mode", mode
    dependsOn kotlin.targets.iOS.compilations.main.linkTaskName("FRAMEWORK", mode)

    from { kotlin.targets.iOS.compilations.main.getBinary("FRAMEWORK", mode).parentFile }
    into frameworkDir

    doLast {
        new File(frameworkDir, 'gradlew').with {
            text = "#!/bin/bash\nexport 'JAVA_HOME=${System.getProperty("java.home")}'\ncd '${rootProject.rootDir}'\n./gradlew \$@\n"
            setExecutable(true)
        }
    }
}
```

and Xcode runscript phase:
```bash
cd "$SRCROOT/../../SharedCode/build/xcode-frameworks"
./gradlew :SharedCode:packForXCode -PXCODE_CONFIGURATION=${CONFIGURATION}
```

**Comment by olonho** [comment]
Does it block upload?

**Comment by NilsLattek** [comment]
Upload from Xcode to Apple servers is fine. After upload Apple is doing checks on the binary file and sends an email with that error message and invalidates the binary. So you cannot publish it.
I have now renamed my method from `clearCache` to `clear` after some findings on Stackoverflow and for now the error is gone. Also for the other methods which is strange.
It seems that objc selectors with specific names can cause problems. Somehow Apple then thinks that we are calling these selectors on there objects.

**Comment by ildarsharafutdinov** [comment]
@NilsLattek ,

did you manage to pass review? or did you fix `non-public clearCache` error?

**Comment by SvyatoslavScherbina** [comment]
Thank you for the report, we have reproduced the issue.

**Comment by SvyatoslavScherbina** [comment]
The problem is caused by false positive error in non-public API usage checker during AppStore validation.
To workaround the issue, please try to rename `clearCache` function.

**Comment by NilsLattek** [comment]
yes renaming `clearCache` solves the issue. We have only made the app available through testflight so it passes Apples automatic checks now. That means it should also be no problem publishing to AppStore.
I was just a bit worried why it was enough to just change our `clearCache` method when Apple was first complaining about more methods (from Frameworks).

**Comment by SvyatoslavScherbina** [comment]
We can't know the details of Apple validation rules for sure.
This behaviour was discovered accidentally.

**Comment by NilsLattek** [comment]
Okay, I think we can close this ticket since it works for now.
