### ISSUE TITLE
Test fails when enough empty test are added to the test class

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/kotlin-native#2762]
Here is a stripped down version of Kodein-DB, *a work in progress*, that demonstrates a bug in Kotlin Native: https://github.com/SalomonBrys/Kotlin-Native-Test-Bug-Demo

**This is for linux only!**

The bug is this:
- When I run the `test` test that is alone in its class, the test succeeds.
- When I add 30 more empty tests that do absolutely nothing, the previous test suddently fails with a `NullPointerException`.

Using Kotlin Gradle Multiplatform 1.3.21

Here's how to reproduce:

1. Clone the repo https://github.com/SalomonBrys/Kotlin-Native-Test-Bug-Demo.
2. Run `./gradlew clean linuxX64Test`.
3. Note that `test` fails with a `kotlin.NullPointerException`.
4. Edit the file `kodein-leveldb/src/linuxX64Test/kotlin/org/kodein/db/leveldb/test/LevelDBTests.kt` and comment out the 30 `empty_*` test functions.
5. Run `./gradlew clean linuxX64Test`.
6. Note that `test` succeeds.

The exact number of empty test needed for the bug to show is variable, but 30 seems to always make it appear. 10, for example, is not enough.
Also, splitting the tests in multiple test classes does not seem to help.

**Comment by SvyatoslavScherbina** [comment]
Sorry, I can't reproduce the issue: Gradle build configuration keeps failing with
```
FAILURE: Build failed with an exception.

* Where:
Build file '.../kodein-leveldb/build.gradle.kts' line: 9

* What went wrong:
A problem occurred configuring project ':ldb-lib:leveldb'.
> Could not open cache directory euvqycbagqmqkymysfmzey1cv (.../.gradle/caches/4.10.2/gradle-kotlin-dsl/euvqycbagqmqkymysfmzey1cv).
   > org.gradle.api.internal.initialization.DefaultClassLoaderScope@7df0859c must be locked before it can be used to compute a classpath!

```

**Comment by SalomonBrys** [comment]
@SvyatoslavScherbina This is a known Gradle issue.
Please comment the `evaluationDependsOn` line in the indicated `build.gradle.kts` file.

**Comment by SvyatoslavScherbina** [comment]
Then Gradle can't find `createDebug` task on line 14 due to wrong configuration order, as expected.

**Comment by SvyatoslavScherbina** [comment]
Ok, I've hard-coded linker option path instead and reproduced the issue.

**Comment by SvyatoslavScherbina** [comment]
Your code has incorrect native memory accesses.
For example, [this memory](https://github.com/SalomonBrys/Kotlin-Native-Test-Bug-Demo/blob/87e2d808756f1b53a7d1c1cf63954f406b4c00dc/kodein-leveldb/src/linuxX64Main/kotlin/org/kodein/db/leveldb/native/LevelDBNative.kt#L177) is used after deallocation.

**Comment by SalomonBrys** [comment]
Wooooooow...
I am really sorry about that!
I guess this is a perfect example of "unknown behaviour" when incorrectly accessing non-managed memory.
I really apologize for making you debug my own mistake. Thanks a lot for the help.

**Comment by SvyatoslavScherbina** [comment]
That’s all right 👌
