### ISSUE TITLE
How to log stack trace for RuntimeException on iOS?

### ISSUE THREAD

**Issue by mikezliu** [JetBrains/kotlin-native#2763]
What's the recommended way to log the stack trace of RuntimeException thrown by Kotlin on iOS?  It's not feasible to wrap every call to the framework with a try catch (I also store common helper functions in the shared framework), and the exception thrown is too vague to be able to track down the cause of the crash.

```
Instances of kotlin.Error, kotlin.RuntimeException and subclasses aren't propagated from Kotlin to Objective-C/Swift.
Other exceptions can be propagated as NSError if method has or inherits @Throws annotation.
```

**Comment by cesdperez** [comment]
Hey @mikezliu , I'm having the same issue. Could you share with me your findings? thanks
