### ISSUE TITLE
curl :: kotlinc-native main.kt

### ISSUE THREAD

**Issue by karippery** [JetBrains/kotlin-native#2764]
Now i am working in sample/curl.
everything was work fine on this site [click](https://github.com/JetBrains/kotlin-native/tree/master/samples/curl)
but when i want to do Compiling `kotlin-native\samples\curl\src\curlMain\kotlin>kotlinc-native main.kt` to get program.kexe file
**i got some starnge errors**
![kotlinc](https://user-images.githubusercontent.com/33422429/54359644-631c0c80-4663-11e9-9470-d21645cca832.PNG)

why i got this?
how can i see output ?

**Comment by olonho** [comment]
Samples are compiled with Gradle, i.e.
```
# cd samples/
# ./gradlew assemble
```

**Comment by karippery** [comment]
thank you for your reply 
i question was how i should see the output as a file `program.kexe` in the sample curl?

and in samples\libcurl  gradlew is working 
```
samples\libcurl>gradlew assemble
'gradlew' is not recognized as an internal or external command,
operable program or batch file.
```
so that i use `gradle assemble`
libcurl and curl are BUILD SUCCESSFUL
and in curl i  cmd `gradle runProgram`
i got output "curl_easy_perform() failed Couldn't connect to server"

everything  work fine i only need how can i produce program.exe file or main.exe?

**Comment by olonho** [comment]
Binaries are in 
samples/curl//build/bin/curl/mainReleaseExecutable/main.exe or .kexe
depending on architecture.

**Comment by msink** [comment]
Curl sample is bad starting point for experiments with Kotlin'/Native on Windows - resulting .exe file heavily depends on many (dozens!) of .dll from MSYS2 distribution.

You must either have them in system PATH, or copy alongside with .exe
Here is utility to list that .dll's - https://github.com/msink/win32-dlltree
