### ISSUE TITLE
Worker missing pthread_exit or pthread_join

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2777]
It looks like when you start a `Worker` using `Worker.start()` it creates a pthread, but then there's no subsequent `pthread_exit` or `pthread_join` call to shutodwn the thread anywhere. Is it intentionally not possible to shutdown a `Worker`'s thread, or is this a bug? This was pointed out in the  `#kotlin-native` channel, so I thought I'd file an issue. Thanks!

**Comment by olonho** [comment]
Thread routine returns when worker is requested to be terminated, and according to `pthread_create` manual

```
The thread is created executing start_routine with arg as its sole argument.  If the start_routine returns, the effect is as if
     there was an implicit call to pthread_exit() using the return value of start_routine as the exit status. 
```

**Comment by benasher44** [comment]
Ah that explains it then. Thanks for that clarification!
