### ISSUE TITLE
Share Code between iOS and OSX

### ISSUE THREAD

**Issue by fab1an** [JetBrains/kotlin-native#2778]
How would one go about in sharing code between `macosX64` and `iosArm64` targets?
I created a source-set, but I couldn't figure out how to:
* Make both targets depend on the new source-set
* Enable common cinterops (like the metal framework) for the new source-set

**Comment by ilmat192** [comment]
1. As for any other targets you can configure dependency between source sets. In your case it will look like this:

```
kotlin {
    macosX64("mac")
    iosArm64("ios")

    sourceSets {
        // A common source set for mac and ios.
        commonAppleMain { ... }

        // Configure platform source sets to depend on the common one.
        iosMain.dependsOn commonAppleMain
        macMain.dependsOn commonAppleMain
    }
}
```

But note that currently there are no "common" platform libraries thus an IDE will not be able to resolve platform calls in `commonAppleMain`. It means that for example `fopen` call made in `commonAppleMain` will be red in the IDE but the compiler will still be able to produce artifacts for both platforms. 

2. Currently there is no way to create a common cinterop library for several platforms so you have to declare separate cinterops in corresponding compilations.

It's better to ask such questions in our Slack at https://kotlinlang.slack.com (channel `#kotlin-native` or `#multiplatform`).

**Comment by LouisCAD** [comment]
This module shares code between iOS and macOS using a mix of symbolic links and custom logic in buildSrc used by `build.gradle.kts`: https://github.com/LouisCAD/Splitties/tree/41a84abe3b098d47490908dc23bfd810526fa0ea/modules/preferences
