### ISSUE TITLE
Inconsistent xcode version usage

### ISSUE THREAD

**Issue by Streppel** [JetBrains/kotlin-native#2779]
**OS**: Darwin Kernel Version 18.2.0
**GRADLE**: v5.2.1
**KOTLIN/NATIVE**: v1.0.3
**XCODE**: v10.1 (10B61)

`README.md` file says that

> on macOS install Xcode 10.1

however, when running `./gradlew update:dependencies` we get (with `ignoreXcodeVersionCheck` set to `false` of course)

```
FAILURE: Build failed with an exception.

* Where:
Build file 'home/kotlin/native/kotlin-native-1.0.3/build.gradle' line: 44

* What went wrong:
A problem occurred evaluating root project 'kotlin-native-1.0.3'.
> expected Xcode version 10.0, got 10.1, consider updating Xcode or use "ignoreXcodeVersionCheck" variable in konan.properties
```

Can we use 10.1 indeed or should we update the docs?

**Comment by SvyatoslavScherbina** [comment]
Why are you referring to `README.md` from master branch while trying to build Kotlin/Native v1.0.3?

**Comment by Streppel** [comment]
@SvyatoslavScherbina indeed I guess I messed up there... will be closing this since using 10.1 worked fine for me. Thanks!
