### ISSUE TITLE
KN wasm magic?

### ISSUE THREAD

**Issue by WhiteHexagon** [JetBrains/kotlin-native#2786]
Can someone please direct me for documentation on how the following code works please? 

Specifically where does 'document' and 'asCanvas' come from?

I'm trying to make a call from KN/WASM to change a html label but I'm really finding it hard to locate information.  So I'm looking for package documentation for the 2 imports please.  Or is the asCanvas done by some other magic?

```
import kotlinx.interop.wasm.dom.*
import kotlinx.wasm.jsinterop.*

fun main() {

    val canvas = document.getElementById("myCanvas").asCanvas
```

**Comment by alexander-gorshenev** [comment]
See `Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/wasm/idl/dom.kt`. 
The web idl binding generator for kotlin/native wasm has not been productized yet.
