### ISSUE TITLE
How can Int be converted to NSUInteger?

### ISSUE THREAD

**Issue by mikezliu** [JetBrains/kotlin-native#2790]
I am trying to convert an Integer to a NSUInteger.  I have tried:

1. Using the suggested toNSUInteger(), but it compiles with an unresolved error message

2. Using toUInt() and toULong(), but it says type mismatch error. Editor does not give an error when using toULong, but gradle compile does give an error.

**Comment by mikezliu** [comment]
This was what I ended up with. Is there a better way?

`
        var precision = 5
        var nativePrecision: NSUInteger? =
                precision.toULong() as? NSUInteger // 64 bit
                ?: precision.toUInt() as? NSUInteger // 32 bit
        if (nativePrecision == null) {
            nativePrecision = 2u // Fallback to a default value
        }
`

**Comment by SvyatoslavScherbina** [comment]
Use [`nativePrecision.convert<NSUInteger>()`](http://kotlinlang.org/docs/reference/native/c_interop.html#portability).
