### ISSUE TITLE
Execution failed for task "linkDebugFrameworkIos"

### ISSUE THREAD

**Issue by francismariano** [JetBrains/kotlin-native#2793]
Hi all,
I am trying to execute the task "copyFramework" from inside XCode but it fails.
Follow some errors from copyFramework run with --debug.

`[LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :app:linkDebugFrameworkIos FAILED`

`ERROR] [system.err] warning: skipping /Users/asdf/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-native_debug_ios_x64/1.1.1/64446fd4d75249e6617076c8f4d3b0ca8ff09a2f/kotlinx-coroutines-core-native.klib. The abi versions don't match. Expected '[2]', found '5'`

`ERROR] [system.err] warning: the compiler versions don't match either. Expected '[1.0.3]', found '1.1.1-release-6082'`

`[ERROR] [system.err] error: compilation failed: Could not find "/Users/asdf/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-native_debug_ios_x64/1.1.1/64446fd4d75249e6617076c8f4d3b0ca8ff09a2f/kotlinx-coroutines-core-native.klib" in [/Users/asdf/Documents/Projects/Android/myProject/iosApp, /Users/asdf/.konan/klib, /Users/asdf/.konan/kotlin-native-macos-1.0.3/klib/common, /Users/asdf/.konan/kotlin-native-macos-1.0.3/klib/platform/ios_x64].`

`[ERROR] [system.err]  * Compiler version info: Konan: 1.0.3 / Kotlin: 1.3.11
[ERROR] [system.err]  * Output kind: FRAMEWORK`

`[ERROR] [system.err] exception: java.lang.IllegalStateException: Could not find "/Users/asdf/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-native_debug_ios_x64/1.1.1/64446fd4d75249e6617076c8f4d3b0ca8ff09a2f/kotlinx-coroutines-core-native.klib" in [/Users/asdf/Documents/Projects/Android/myProject/iosApp, /Users/asdf/.konan/klib, /Users/asdf/.konan/kotlin-native-macos-1.0.3/klib/common, /Users/asdf/.konan/kotlin-native-macos-1.0.3/klib/platform/ios_x64].`

-----------------------------------------------
More informations

**Gradle version : 4.10.1**
**kotlin-multiplatform version: '1.3.11'**

```
task copyFramework {
    def buildType = project.findProperty("kotlin.build.type") ?: "DEBUG"
    def target = project.findProperty("kotlin.target") ?: "ios"
    dependsOn "link${buildType.toLowerCase().capitalize()}Framework${target.capitalize()}"
    doLast {
        def srcFile = kotlin.targets."$target".compilations.main.getBinary("FRAMEWORK", buildType)
        def targetDir = getProperty("configuration.build.dir")
        copy {
            from srcFile.parent
            into targetDir
            include 'app.framework/**'
            include 'app.framework.dSYM'
        }
    }
}
```
Can anyone help me?

**Comment by olonho** [comment]
You have incorrect ABI version in your library, and compiler says so:

```The abi versions don't match. Expected '[2]', found '5'```

You need to use matching compiler and library versions.

**Comment by francismariano** [comment]
Ok. I understood.

How could I fix the ABI version in my library? Have you a guide for that?

**Comment by francismariano** [comment]
Sorry, I update the kotlin-multiplatform plugin version from 1.3.11 to 1.3.20.

**Comment by francismariano** [comment]
Hello,

I created a new project (File -> New -> New Project -> Kotlin (Mobile Android/iOS) with IDEA version: 

```
IntelliJ IDEA 2018.3.5 (Community Edition)
Build #IC-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

In the default project generated I update the kotlin-multiplatform plugin version from 1.3.11 to 1.3.20. When I try to build the project with Xcode I get the following error

```
> Configure project :app
Kotlin Multiplatform Projects are an experimental feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:copyFramework'.
> Task with path 'linkDebugFrameworkIos' not found in project ':app'.
```

**Comment by ilmat192** [comment]
Yes, the task naming was changed in 1.3.20. Try to update the IDEA plugin to latest EAP and create the example project again. 

To update the plugin, run `Tools -> Kotlin -> Configure Kotlin Plugin Update`, choose the EAP 1.3.x channel and install the updated plugin. 
![image](https://user-images.githubusercontent.com/7298542/54802736-28d3f000-4c9f-11e9-8664-3b9bed47db55.png)

**Comment by francismariano** [comment]
Thank you. Your suggestion works for me.
But now the first problem come back.

```
> Task :app:linkDebugFrameworkIos FAILED
w: skipping /Users/asdf/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-native_debug_ios_arm32/1.1.1/1bf3b91ac874e5b5c34493a187556458134d6aa6/kotlinx-coroutines-core-native.klib. The abi versions don't match. Expected '[8]', found '5'
w: The compiler versions don't match either. Expected '[1.2]', found '1.1.1-release-6082'
```
The new version of the kotlin (1.3.30-eap-45) expect by 1.2 version kotlinx-coroutines-core-native, but the last release of it it 1.1.1. Maybe, I have to wait for releasing of the 1.2 version.

Best regards.

**Comment by ilmat192** [comment]
Yes, but now have a correct project structure and can manually switch to Kotlin `1.2.21` in the build script.

**Comment by abelkov** [comment]
Related: https://youtrack.jetbrains.com/issue/KT-30885
