### ISSUE TITLE
[Improvement] Freezing a class hierarchy

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2795]
If I have a base class A, for which I want to add N number of subclasses, and I want all instances of A to be frozen after initialization, I have to remember to add freeze() at the end of all `init` methods for all subclasses of A becuase adding it to A's init will not allow its subclasses to set properties during initialization (causes mutability exception). If your class hierarchy gets deeper than that, then this becomes even more difficult to manage, as you might be forced to move your freeze calls to the call sites where you create your frozen objects (cannot freeze a class in the middle of a class hierarchy in its init method without running into the same issue in its subclass's initialization).

It would be great if there could exist (for example) something like `@Frozen` to annotate a class that should be frozen after initialization, but would allow the entire hierarchy to initialize, when initializing subclasses. This could always apply to that class and its children (allow flexibility in having some sub-trees be frozen and not others).

The implementation suggestion is only meant to be an idea / jumping off point, and I'm open to any way that this situation could be improved :)

**Comment by kpgalligan** [comment]
Without getting into how I'd like to see it implemented, the init/freeze order issue has bitten more than once. As an alternative, having the actual freeze happen at the end of initialization would also help. I have not thought that through much, so there may be very good reasons why that wouldn't work.

**Comment by SvyatoslavScherbina** [comment]
We don't have plans for this, considering [Kotlin/Native Memory Management Roadmap](https://blog.jetbrains.com/kotlin/2020/07/kotlin-native-memory-management-roadmap/).
