### ISSUE TITLE
ObjC interop: Map CharSequence to NSString?

### ISSUE THREAD

**Issue by maksim-m** [JetBrains/kotlin-native#2796]
According to the [documentation](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-char-sequence/index.html) `CharSequence` interface is present in Kotlin Native.
When I compile the following code:
```kotlin
fun method1(string: String) = string.length
fun method2(charSequence: CharSequence) = charSequence.length
```
with `org.jetbrains.kotlin.multiplatform` version 1.3.21 this generates the header:
```
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("SampleKt")))
@interface MMLSampleKt : KotlinBase
+ (int32_t)method1String:(NSString *)string __attribute__((swift_name("method1(string:)")));
+ (int32_t)method2CharSequence:(id)charSequence __attribute__((swift_name("method2(charSequence:)")));
@end;
```

Swift compiler successfully validates the parameter type of the method1, but expects a parameter of type `Any` for the second method, which may cause an runtime error: 
![image](https://user-images.githubusercontent.com/1863269/54706796-0d060800-4b40-11e9-9b75-22833a598a0a.png)

Since `CharSequence` is not present on Swift/Objectivtiv-C, does it make sense to map it to `NSString` at the compile time?

**Comment by SvyatoslavScherbina** [comment]
> Since CharSequence is not present on Swift/Objectivtiv-C, does it make sense to map it to NSString at the compile time?

I don't think so.

Image that `CharSequence` was represented as `NSString`, and you had `method3(): CharSequence`.
Then `method1(string: method3())` would be valid code. But what should happen if `method3()` returns a `StringBuilder` instance? Isn't it the equivalent problem?

**Comment by SvyatoslavScherbina** [comment]
Got no response, closing.
