### ISSUE TITLE
[Improvement] Better test integration with IntelliJ

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2801]
It's not too difficult to get test runners setup for native targets, but it's very difficult to debug them. With the iOS test runner for example, it's easy enough to write a gradle task that runs the tests and does some reporting, but debugging tests and interacting with them in IntelliJ is difficult. Two things would improve this:

1. While you can have them wait for a debugger to attach, and then manually attach lldb, it'd be much better if you could run the tests in the debug configuration in IntellIj and hit breakpoints that were set in the GUI.
1. It would also be nice if tests that passed/failed showed up in the IntellIj test window, similar to how they do when running common tests using Android's test runner (e.g. the `testDebugUnitTest` gradle task)

Solving 1. might mean also solving #2578, but if that's too difficult in the near term, solving it for the macos test runner (generated by the mpp plugin) might provide the template that those of us who are using a custom iOS test gradle task could use to adjust our custom ios test runner tasks.

**Comment by olonho** [comment]
Yes, this is planned for upcoming IDE work.

**Comment by benasher44** [comment]
@olonho following up on this, I can do `xcrun simctl spawn --wait-for-debugger -s 'iPad Air 2' build/bin/iosSim/debugTest/test.kexe`, but then there's no K/N debugger in IntelliJ I can tell to attach to this. Do you have any advice here?

**Comment by benasher44** [comment]
I downloaded IntelliJ Ultimate + K/N Debugging plugin. It looks like it only supports specific targets.

**Comment by benasher44** [comment]
This is really an mpp + IDEA problem. Filed here: https://youtrack.jetbrains.com/issue/IDEA-228681
