### ISSUE TITLE
How to use BigDecimal datatype in Kotlin Multiplatform?

### ISSUE THREAD

**Issue by Adriannatsu** [JetBrains/kotlin-native#2804]
I followed the tutorial https://kotlinlang.org/docs/tutorials/native/mpp-ios-android.html, then I successfully create the folders of androidmain, iosmain and commonmain. 
However when I want to implement the datatype BigDecimal in the commonmain. It won't work. I need the decimal dataype for the currency.

**Comment by SvyatoslavScherbina** [comment]
`BigDecimal` is Java class, so it is not available on iOS.
Please refer to the documentation:
https://kotlinlang.org/docs/reference/multiplatform.html
https://kotlinlang.org/docs/reference/platform-specific-declarations.html

**Comment by olonho** [comment]
Note that for most practical cases `ULong` shall be enough.

**Comment by kendy** [comment]
I've ported BigDecimal to Kotlin/Native here: https://github.com/kendy/Kotlin-Native-BigDecimal if you are interested :-)
