### ISSUE TITLE
When will this project release? 

### ISSUE THREAD

**Issue by DTHeaven** [JetBrains/kotlin-native#2816]
Hi,
Is there a plan to release this project? 
Would it has break changes between current version and release?
How do you think if I use current version to our official product? Is there any severe problems?

Thanks!

**Comment by olonho** [comment]
Kotlin/Native already release along with general Kotlin release, including upcoming 1.3.30 release. To use it just create new project or open existing one with IntelliJ IDEA or Android Studio with recent Kotlin plugin.

**Comment by DTHeaven** [comment]
> Kotlin/Native already released along with general Kotlin releases, including upcoming 1.3.30 release. To use it just create new project or open existing one with IntelliJ IDEA or Android Studio with recent Kotlin plugin.

"Multiplatform projects are an experimental feature in Kotlin 1.2 and 1.3. All of the language and tooling features described in this document are subject to change in future Kotlin versions."

Here it says "Multiplatform projects are an experimental feature in Kotlin 1.2 and 1.3", which actually  I want to ask.
Is it stable enough to use in official project?

**Comment by olonho** [comment]
Yes, we consider it usable for practical purposes, including official projects, clause you refer mostly means that there are changes that could happen in language, tooling and platform implementation during further platform evolution, not that it is unstable or unusable for production environments.

**Comment by DTHeaven** [comment]
> Yes, we consider it usable for practical purposes, including official projects, clause you refer mostly means that there are changes that could happen in language, tooling and platform implementation during further platform evolution, not that it is unstable or unusable for production environments.

I got it.
Thank you very much.
