### ISSUE TITLE
Cast internal class object to public interface fails in Swift

### ISSUE THREAD

**Issue by laviallb** [JetBrains/kotlin-native#2830]
When  I declare in Kotlin :
```
public interface InterA {}
internal class ClassA: InterA {}
```
And expose in Swift an `InterA` backed by a `ClassA` instance,
Some cast operations fail: 
```
    private func getObject<T>(_ value: InterA) -> T? {
        let castedValue = value as? T // nil
        let test1 = value is T // false
        let test2 = value is InterA // true
        let test3 = T.self == InterA.self // true
        return castedValue
    }

    let inter: InterA? = getObject(commonManager.api.a) // commonManager.api.a is a ClassA
```
It is not possible to cast `value` in `T`, even if `T` is `InterA`. If I change getObject to take `value` as `Any`, even `test2` fails.

Everything works well if ClassA is public.

The use case behind that issue is to be able tu use a DI framework such as Swinject.

**Comment by SvyatoslavScherbina** [comment]
Confirmed, thank you for the report.
