### ISSUE TITLE
Support mingwX86 in kotlin-multiplatform

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#2837]
Is mingw-x86 supported in gradle `kotlin-multiplatform` platform plugin?

Tried in current master branch:
``` diff
--- a/samples/tetris/build.gradle
+++ b/samples/tetris/build.gradle
@@ -104,7 +104,7 @@ afterEvaluate {
 }
 
 private def determinePreset() {
-    def preset = isRaspberryPiBuild() ? kotlin.presets.linuxArm32Hfp /* aka RaspberryPi */ : MPPTools.defaultHostPreset(project)
+    def preset = isRaspberryPiBuild() ? kotlin.presets.linuxArm32Hfp /* aka RaspberryPi */ : MPPTools.isWindows() ? kotlin.presets.mingwX86 : MPPTools.defaultHostPreset(project)
     println("$project has been configured for ${preset.name} platform.")
     preset
 }
```
Result:
```
A problem occurred evaluating project ':tetris'.
> Could not get unknown property 'mingwX86' for KotlinTargetPreset container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.
```

Well, after this:
``` diff
--- a/samples/gradle.properties
+++ b/samples/gradle.properties
@@ -2,7 +2,7 @@
 org.gradle.parallel=true
 
 # Pin Kotlin version:
-kotlin_version=1.3.21
+kotlin_version=1.3.30-eap-125
 
 # Use custom Kotlin/Native home:
 org.jetbrains.kotlin.native.home=../../dist
```
Error is a little different:
```
> Configure project :tetris
project ':tetris' has been configured for mingwX86 platform.
Target 'tetris' for platform mingw_x86 is ignored during build on this mingw_x64 machine. You can build it with one of the host platforms: .
```

**Comment by olonho** [comment]
Indeed, https://upsource.jetbrains.com/kotlin/review/KOTLIN-CR-2878 shall fix it.

**Comment by msink** [comment]
So will it be in next `1.3.30-eap-*`?

**Comment by ilmat192** [comment]
Yes, the fix is merged in both `master` and `1.3.30` (https://github.com/JetBrains/kotlin/commit/54d75fb73bc626312aebe867e8c80aa5af42d5d4).

**Comment by msink** [comment]
Thanks, it works in eap-150.

Here my quick and dirty hach: https://github.com/msink/kotlin-native/commit/519808a0078d49ea9ed794355230f7f2dcd1ba52
Now it compiles, `mainDebugExecutable` works as expected, but `mainReleaseExecutable` shows empty window.
So something is broken in mingw-x86 target if optimization is enabled...

**Comment by ilmat192** [comment]
Could you please open a separate ticket here on at the [YouTrack](https://youtrack.jetbrains.com/issues/KT) to track this problem?

**Comment by msink** [comment]
Opened #2848
