### ISSUE TITLE
32-bit windows target (mingw_x86) broken in RELEASE builds

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#2848]
`mingw_x86` target in `1.3.30-eap-150` works just fine in DEBUG build, but is somewhat broken in RELEASE - it compiles, but some operations silently not called in runtime.
Both `master` and `1.2.0-fixes` branches are broken in same way.

My (quick and dirty) hacked version of samples/tetris - https://github.com/msink/kotlin-native/commit/9e955ff9c7091c2c764fa2f6d2ae0d86c3213aed , I do not have smaller reproducer, sorry.

mainDebugExecutable:
![image](https://user-images.githubusercontent.com/1785275/55538339-a48a5f80-56d7-11e9-9c22-bed448a4b084.png)

mainReleaseExecutable: 
![image](https://user-images.githubusercontent.com/1785275/55538374-bec43d80-56d7-11e9-9271-529f05badd55.png)

**Comment by olonho** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/2870

**Comment by msink** [comment]
Will it be in `1.3.31`?
