### ISSUE TITLE
Linker error using FOLDERID_Documents

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#2853]
In a mingw target, we want to use `FOLDERID_Documents` from `platform.windows.*`, but doing so causes a linker error: `undefined reference to 'FOLDERID_Documents'`. I've attached a minimal sample project that reproduces the error. It would be great to either resolve this in Kotlin-Native or learn what linker flag we should be using.

[winTest.zip](https://github.com/JetBrains/kotlin-native/files/3055260/winTest.zip)

**Comment by benasher44** [comment]
We tried `-lshell32`, which didn't work (suggestion from slack).

**Comment by msink** [comment]
``` diff
--- a/build.gradle
+++ b/build.gradle
@@ -15,6 +15,7 @@ kotlin {
             outputKinds("executable")
             // Change to specify fully qualified name of your application's entry point:
             entryPoint 'sample.main'
+            linkerOpts '-luuid'
         }
     }
     sourceSets {
```

**Comment by benasher44** [comment]
@msink that did it thanks!. @olonho is this something that can be fixed in K/N?

**Comment by olonho** [comment]
In theory, we could have that in default DLLs to link, but in fact I think it's better to somewhat split Windows platform libs somehow, instead of always linking everything. Do you have an idea how it better be done?

**Comment by msink** [comment]
AFAIK, `libuuid.a` does not link any dll.

**Comment by benasher44** [comment]
That makes sense. I think splitting up platform.windows.* into sub-packages based on the libraries the symbols come from would help. Initially, we could use that as a hint to know which linker flags we need. In the future, maybe a plugin could lean on that to know which linker flags to add?

**Comment by olonho** [comment]
OK, as quick workaround let's do d5096cbb1e14ed4f015cd63533f1b05a80fc03d4, but generally effort on splitting Windows platform lib from people more familiar with Win32 API would be awesome.
