### ISSUE TITLE
cocopods plugin pod generate source

### ISSUE THREAD

**Issue by kodal** [JetBrains/kotlin-native#2863]
> Task :KotlinAppIos:cinteropAFNetworkingKotlinAppIos FAILED
Exception in thread "main" java.lang.Error: /var/folders/wc/rmc_x9cn51583gnndfx5twyc0000gn/T/tmp1458922366242336349.m:1:9: fatal error: module 'AFNetworking' not found
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:133)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:43)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:16)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:349)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:214)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:38)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:67)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)

**Comment by ilmat192** [comment]
Do you build the application from Xcode?

**Comment by Syrou** [comment]
Having the same issue, I believe you should be able to build your project from IntelliJ without this being a problem

**Comment by Syrou** [comment]
@ilmat192 Was this the error you referenced before you pushed to master? Or is this something else?

**Comment by ilmat192** [comment]
> I believe you should be able to build your project from IntelliJ without this being a problem

No, if we want to interop with a CocoaPods library, we need to download it and obtain paths to its headers and module files somehow. Currently we rely on a user's Xcode project. This project is correctly configured by CocoaPods, so when the Gradle build is started from such a project, we can obtain all necessary parameters from Xcode settings (see [the doc](https://kotlinlang.org/docs/reference/native/cocoapods.html#interoperability). Thus currently a K/N module interoping with some CocoaPods library can be built only from Xcode. But I guess we will be able to lift this limitation in future releases.

> Was this the error you referenced before you pushed to master?
Sorry, what is the error and the push you mentioned?

**Comment by Syrou** [comment]
So basicly this is gonna stop the entire :build task then? Or will it get resolved once the xcode project has managed to build?

**Comment by Syrou** [comment]
Such a quickfix could look like this, added to the build.gradle.kts:
```
gradle.taskGraph.beforeTask {
    val isRanFromXcode = if (project.properties["kotlin.native.cocoapods.target"] != null) false else true
    if (isRanFromXcode) {
        val numberOfPods = kotlin.cocoapods.pods.size
        if (numberOfPods > 0) {
            if (this.name.contains("generateDef") || this.name.contains("IOS")) {
                this.setActions(listOf())
                logger.info("While using pods we can not build iOS from intellij, iOS needs to be build from xcode in these cases")
            }
        }
    }
}
```

**Comment by Syrou** [comment]
Can also confirm that I'm getting this error while building from xcode out of no where after updating to Version 10.1 (10B61) was able to build with previous verison that I had

**Comment by kodal** [comment]
Build on xcode fixes that

**Comment by ilmat192** [comment]
> My suggestion would be, don't attempt to build for iOS if pods is used instead of blocking while using :build/:assemble and instead show a information message telling the iOS target will not get built from IntelliJ.

It sounds reasonable but I think that such a conditional disabling building certain targets should be generalized. We already have at least one use case when it may be useful: disabling cross compilation for some platforms (e.g. a Linux target can be build on any host but we may want to build it only on Linux hosts, see https://youtrack.jetbrains.com/issue/KT-30498). So I think it worth focusing on such a generalized disabling targets and getting rid of using Xcode.
