### ISSUE TITLE
Provide simple libcurl project template for CLion

### ISSUE THREAD

**Issue by ChrisAJS** [JetBrains/kotlin-native#2869]
With Kotlin/Native being iterated on quickly- often coming back to the project after sometime means learning all the different Gradle incantations to be able to get a functional project.

One of the pain points is the C interop, which is one of the most useful parts of K/N.

Can the curl example (that I believe used to ship with K/N) be re-added?

**Comment by SvyatoslavScherbina** [comment]
Hi. Kotlin plugin for CLion is deprecated now. Please use IntelliJ IDEA Ultimate.
See more details here:
https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-rc-released/
https://plugins.jetbrains.com/plugin/10454-kotlin-native-for-clion
