### ISSUE TITLE
Including libraries exported with GRADLE_METADATA in a project not using GRADLE_METADATA doesn't work anymore after K/N 1.2.0

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#2883]
See https://github.com/Kotlin/kotlinx.coroutines/issues/1105

This prevents me from updating most of my libraries (the ones depending on kotlinx.coroutines) to Kotlin 1.3.30 and people using them have to stick to 1.3.21.

**Comment by msink** [comment]
I think it's same bug as in https://github.com/JetBrains/kotlin-native/issues/2372#issuecomment-483195978

**Comment by ilmat192** [comment]
Since Gradle 6.0 the Gradle metadata is enabled by default so closing this issue as obsolete.
