### ISSUE TITLE
Cocoapods build for ios 8

### ISSUE THREAD

**Issue by NiKlimenko** [JetBrains/kotlin-native#2885]
Currently it's not possible to build ios project via cocoapods in xcode 10.
There are few errors:

**ld: targeted OS version does not support use of thread local variables in _kfun:kotlin.text.checkRadix$stdlib(kotlin.Int)ValueType for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

**ld: targeted OS version does not support use of thread local variables in _kshadowobjref:kotlinx.wasm.jsinterop.ArenaManager for architecture armv7**

How to reproduce: try to build the cocoapods sample placed in this repository. Change the deployment target to 8 in the xcode project settings.

**Comment by olonho** [comment]
iOS starting with 9.0 is supported.

**Comment by NiKlimenko** [comment]
> iOS starting with 9.0 is supported.

Please include this information in the documentation.
