### ISSUE TITLE
Cannot successfully sync with plugin version 1.3.30

### ISSUE THREAD

**Issue by spencerelliott** [JetBrains/kotlin-native#2892]
When attempting to sync a gradle project using these settings:

```
buildscript {
    repositories {
        google()
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://kotlin.bintray.com/ktor" }
        maven { url "https://kotlin.bintray.com/kotlinx" }
        maven { url "https://dl.bintray.com/kotlin/kotlin-dev/" }
        maven { url "https://dl.bintray.com/jetbrains/kotlin-native-dependencies" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:1.3.30"
        classpath "com.alecstrong:cocoapods-gradle-plugin:0.3.0"
    }
}
```

I receive the error:

```
Failed to resolve: org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.30-eap-164
```

I also receive an error when trying to request `1.3.30-eap-164` for `kotlin-serialization-unshaded` but I placed the `.pom` and `.jar` files in my local `m2` directory to solve the issue. 

I expect the libraries associated with the `1.3.30` build should not have the `eap-164` tag added to them as they are not available in any of the repositories I am able to find.

**Comment by olonho** [comment]
Why do you believe that this report is related to Kotlin/Native?

**Comment by spencerelliott** [comment]
Did I post this in the wrong repository? I believe this is an issue with the Kotlin Native gradle plugin which I thought was also part of this repo. Apologies if I placed this on the wrong tracker.

**Comment by spencerelliott** [comment]
This issue does not appear when I downgrade to version `1.3.21` of `org.jetbrains.kotlin:kotlin-native-gradle-plugin` which makes me believe that this has to do with upgrading to `1.3.30`

**Comment by spencerelliott** [comment]
Sorry, I was missing the `kotlin-dev` repository in my main `repositories` block in my gradle. This seems to have fixed the issue. Sorry for the distrubance.

**Comment by ilmat192** [comment]
> classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:1.3.30"
    classpath "com.alecstrong:cocoapods-gradle-plugin:0.3.0"

You're using the `kotlin-native-gradle-plugin` which is implemented for the old multiplatform paradigm, has no support in IDE and doesn't work with the CocoaPods plugin. So it's recommended to use the `kotlin-multiplatform` plugin instead: https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html.

**Comment by spencerelliott** [comment]
Thanks @ilmat192. I've been updating this project as new releases of Kotlin/Native have been coming out. It looks like the use of `kotlin-native-gradle-plugin` was left over from before so I was able to remove it without any ill effects. I had the definition for the `kotlin-multiplatform` plugin later in my gradle file. Thanks for the help!
