### ISSUE TITLE
Functions with generics missing from dynamic library headers

### ISSUE THREAD

**Issue by mjbryant** [JetBrains/kotlin-native#2893]
It looks like functions with generic types just get left out of generated dynamic libraries with no warnings or anything. Using [`1.3.30`](https://github.com/JetBrains/kotlin/releases/tag/v1.3.30) on Linux, with the simple kotlin file

```kotlin
fun <T> getItemFromList(index: Int, list: List<T>): T {
    return list[index]
}
```
running `kotlinc-native src/kotlin/main.kt -o build/a -p dynamic` produces an `a_api.h` file with no exported symbols.

If this isn't implemented, it should at least warn you that functions with generic types won't be included in the dynamic library.

**Comment by Pomis** [comment]
I think I have seen the implementation of this in some experimental branch. Really hope to see it in next releases.

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-39212
