### ISSUE TITLE
ZLib Linux Arm 32

### ISSUE THREAD

**Issue by caffeine-mgn** [JetBrains/kotlin-native#2901]
Hello. I try to build kotlin-native to two targets: linuxArm32 and linux64.

I have the source:
```
import platform.zlib.*
.....
internal val native = malloc(sizeOf<z_stream_s>().convert())!!.reinterpret<z_stream_s>()
.....
```

When I build it to linux64 target it build normally. But when build to linuxArm32 I have errors:
```
Unresolved reference: zlib
Unresolved reference: z_stream_s
```

I use multiplatform kotlin 1.3.30. Host: Windows 10

**Comment by olonho** [comment]
Fixed in master.
