### ISSUE TITLE
How can I choose the export function declaration? like stdcall or fastcall?

### ISSUE THREAD

**Issue by JuerGenie** [JetBrains/kotlin-native#2902]
Because some terrible things, I must be develop some plug-ins on an old-old-old system, and it working on old version win server.
I find some way to export top-level function like c (use "CName"), but how can I export thies like `extern "C"__declspec(dllexport) int __stdcall ...`?
Just give me a tip plzz and thx :)

**Comment by olonho** [comment]
At the moment it is not possible directly, but you can write your own stubs with any calling convention and call K/N library from there.

**Comment by JuerGenie** [comment]
Got it, \*pack\* the library again. This is my first idea and I dont like this... :X
but it look like the only one choose, okay.
By that way...I just want some api like this:

```kotlin
@Export(name = "some_api", convention = CallingConvention.Stdcall)
fun someApi (args: Any) { /* do something... */ }
```

Anyway, thank you.

**Comment by henjue** [comment]
@JuerGenie hi，how did you solve this problem!

**Comment by JuerGenie** [comment]
> @JuerGenie hi，how did you solve this problem!

ahh, Just like previous comment said, if you programming by c/cpp or other language and you want to export function like stdcall, you can write a library use your program language and ref the K/N library in there and export functions what you want, like this:
```cpp
// export a top-level function:  test(name: String): String
#include `mykotlinlibrary.h`

extern "C" __declspec(dllexport) const char* __stdcall hello(const char* name);

const char* hello(const char* name) {
  // do something...
  // and call K/N library's function
  return test(name);
}
```
hope it could help you.

**Comment by henjue** [comment]
@JuerGenie I want to use only K / N, it seems that there is no way!

**Comment by JuerGenie** [comment]
> @JuerGenie I want to use only K / N, it seems that there is no way!

yep, so sad. :X
so, at last, I rewrite the system's module-loader, let it can load K/N library (what I do: load .ktmod (it is .dll) file and read hard-code entry address to call), wanna try it?
