### ISSUE TITLE
iOS NSAttributedString , How can it be converted into kotlin code?

### ISSUE THREAD

**Issue by ljyao** [JetBrains/kotlin-native#2909]
NSDictionary *attributesDict = @{ (id) kCTFontAttributeName : (__bridge id) font,
                                      (id) kCTForegroundColorAttributeName : (__bridge id) color };
    
NSAttributedString *stringToDraw = [[NSAttributedString alloc] initWithString:string
                                                                       attributes:attributesDict];

**Comment by ljyao** [comment]
__bridge id ???

**Comment by SvyatoslavScherbina** [comment]
Please share more detailed snippet. What are `font` and `color`?

**Comment by ljyao** [comment]
> Please share more detailed snippet. What are `font` and `color`?

How to replace  (id)  and (__bridge id)？

**Comment by SvyatoslavScherbina** [comment]
Please share more detailed snippet. What are `font` and `color`?

**Comment by ljyao** [comment]
> Please share more detailed snippet. What are `font` and `color`?

 CTFontRef font = [_font font];
    CGColorRef color = [_color color];

**Comment by SvyatoslavScherbina** [comment]
Please share more detailed snippet. What are `_font` and `_color`?

**Comment by ljyao** [comment]
> Please share more detailed snippet. What are `_font` and `_color`?

Don't care  `_font` and `_color`，How to replace (id) and (__bridge id)？
`CFBridgingRetain(font)!!.reinterpret()` not working!

**Comment by olonho** [comment]
Please consult docs in https://github.com/JetBrains/kotlin-native/blob/master/OBJC_INTEROP.md

**Comment by ljyao** [comment]
> consult

The document has no cast to (id)
