### ISSUE TITLE
-Xprint-ir argument of compiler CLI is ignored

### ISSUE THREAD

**Issue by sandwwraith** [JetBrains/kotlin-native#2910]
IDEA suggests that function https://github.com/JetBrains/kotlin-native/blob/8272ca7442cc205a7e4ca5060865d4497c1b0aca/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/Context.kt#L435 is not used anywhere

It should be fixed or removed completely (in favor of `-Xdump-phases-after-???`?)

**Comment by artdfel** [comment]
Closing as obsolete, see #3127.
