### ISSUE TITLE
How to convert 'kotlin.targets.ios.binaries.getExecutable('test', 'DEBUG').outputFile' to kts?

### ISSUE THREAD

**Issue by 9468305** [JetBrains/kotlin-native#2918]
Dear guys:

Would you please tell me how to convert this code to kotlin DSL style?
```
kotlin.targets.ios.binaries.getExecutable('test', 'DEBUG').outputFile
```

I have tried `kotlin.targets["ios"].compilations["test"]...`, and search int these files, but didn't find out any properties related to that `binaries` or `executable`.

Thank you~

**Comment by ilmat192** [comment]
`binaries` is not a property of a compilation, it's a property of a target. So the Kotlin snippet is the following:
```
kotlin.targets["ios"].binaries.getExecutable("test", "DEBUG").outputFile
```
