### ISSUE TITLE
Plugin [id: 'org.jetbrains.kotlin.multiplatform', version: '1.3.30'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by BreimerR** [JetBrains/kotlin-native#2924]
plugins {
        kotlin("multiplatform") version "1.3.30"
    }

    repositories {
        mavenCentral()

    }

    kotlin {
        // For ARM, preset function should be changed to iosArm32() or iosArm64()
        // For Linux, preset function should be changed to e.g. linuxX64()
    // For MacOS, preset function should be changed to e.g. macosX64()
    linuxX64("Unify") {
        binaries {
            // Comment the next section to generate Kotlin/Native library (KLIB) instead of executable file:
            executable("unify") {
                // Change to specify fully qualified name of your application's entry point:
                entryPoint = "unify.main"
            }
        }
    }
}

// Use the following Gradle tasks to run your application:
// :runHelloWorldAppReleaseExecutableHelloWorld - without debug symbols
// :runHelloWorldAppDebugExecutableHelloWorld - with debug symbols

**Comment by BreimerR** [comment]
I have tried adding other repo's with no success i.e

       plugins {
            kotlin("multiplatform") version "1.3.30"
       }

       repositories {
           mavenCentral()
           maven("https://dl.bintray.com/kotlin/kotlin-eap")
           maven("https://dl.bintray.com/kotlin/kotlin-dev")
       }

       kotlin {
              // For ARM, preset function should be changed to iosArm32() or iosArm64()
              // For Linux, preset function should be changed to e.g. linuxX64()
              // For MacOS, preset function should be changed to e.g. macosX64()
              linuxX64("Unify") {
                    binaries {
                        // Comment the next section to generate Kotlin/Native library (KLIB) instead of executable 
                    file:
                       executable("unify") {
                            // Change to specify fully qualified name of your application's entry point:
                            entryPoint = "unify.main"
                       }
                    }
                 }
           }

           // Use the following Gradle tasks to run your application:
           // :runHelloWorldAppReleaseExecutableHelloWorld - without debug symbols
           // :runHelloWorldAppDebugExecutableHelloWorld - with debug symbols

**Comment by olonho** [comment]
Use smth like 
```plugins {
    id 'kotlin-multiplatform' version '1.3.31'
}```

**Comment by 9468305** [comment]
@BreimerR Did you setup `settings.gradle.kts` like this? 
```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "kotlin-multiplatform") {
                useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")
            }
        }
    }
    /*enable here when you need other plugins.
    repositories {
        google()
        jcenter()
        mavenCentral()
        gradlePluginPortal()
    }*/
}
```

**Comment by ilmat192** [comment]
@BreimerR Is this issue still actual? If yes, what version of Gradle do you use?

**Comment by artdfel** [comment]
Closed as obsolete.

**Comment by javadba** [comment]
Everything I have are brand new versions as of yesterday 3/5/20.  I am seeing this error message: uncertain if it were for the same or a different issue.  Here is the critical portion of `build.gradle`

```
buildscript {
    ext.kotlin_version = '1.3.71'

    repositories {
        mavenCentral()
        google()
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    }
}

plugins {
    id 'java'
    id 'application'
    id 'org.jetbrains.kotlin.multiplatform'
    id 'kotlinx-serialization'
}

group 'com.pointr'
version '0.1-SNAPSHOT'

apply plugin: 'kotlin'
apply plugin: 'maven-publish'
apply plugin: 'application'
apply plugin: 'kotlinx-serialization'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$kotlin_version"
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.0'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.11.0'
    implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.6'
    implementation("com.charleskorn.kaml:kaml:0.17.0")
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.10.0'
}

wrapper {
   gradleVersion = '6.3' //version required
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

application {
    mainClassName = 'pointr.bluej.WebHandler'
}

```

**Comment by artdfel** [comment]
Hi, @javadba! Please share the complete error message.

**Comment by ImanX** [comment]
> Everything I have are brand new versions as of yesterday 4/5/20. I am seeing this error message: uncertain if it were for the same or a different issue. Here is the critical portion of `build.gradle`
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.3.71'
> 
>     repositories {
>         mavenCentral()
>         google()
>         jcenter()
>     }
>     dependencies {
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
>     }
> }
> 
> plugins {
>     id 'java'
>     id 'application'
>     id 'org.jetbrains.kotlin.multiplatform'
>     id 'kotlinx-serialization'
> }
> 
> group 'com.pointr'
> version '0.1-SNAPSHOT'
> 
> apply plugin: 'kotlin'
> apply plugin: 'maven-publish'
> apply plugin: 'application'
> apply plugin: 'kotlinx-serialization'
> 
> sourceCompatibility = 1.8
> 
> repositories {
>     mavenCentral()
> }
> 
> dependencies {
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
>     implementation "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
>     implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$kotlin_version"
> }
> 
> wrapper {
>    gradleVersion = '6.3' //version required
> }
> 
> compileKotlin {
>     kotlinOptions.jvmTarget = "1.8"
> }
> compileTestKotlin {
>     kotlinOptions.jvmTarget = "1.8"
> }
> 
> application {
>     mainClassName = 'pointr.bluej.WebHandler'
> }
> ```

I faced out same error !
