### ISSUE TITLE
Enum references from swift crash

### ISSUE THREAD

**Issue by kpgalligan** [JetBrains/kotlin-native#2926]
I'm still digging into this, but ran into a very strange issue and wanted some other eyes on it. Referencing enums directly in swift crashes. To repro, add the following test to [values.swift](https://github.com/JetBrains/kotlin-native/blob/7b2bc6d935dde87202a74a371bff9b770a35aa70/backend.native/tests/framework/values/values.swift#L385):

```
try assertEquals(actual: ValuesKt.passEnum(), expected: Enumeration.answer)
```

`Enumeration.answer` simply crashes saying `unrecognized selector sent to class`.

I've done a clean build of kotlin native master and it crashes. Prod 1.3.30 (native 1.2.0) seems to work OK. I've tried to build 1.2.0 locally but it complains about Xcode 10.1, then when that check is disabled the build eventually fails (not sure if they're related). I have an old 1.2.0 local build from several days ago that seems to work.

So, this is either a very obscure local build issue, or something introduced post 1.2.0. If someone can run that test line on master successfully, then it's a local problem. However, I found this trying to sort out a very weird crash we're seeing in prod builds from 1.3.30 on devices when init is called on enums, so if this is actually a problem, it would be good to know the root cause.

**Comment by SvyatoslavScherbina** [comment]
Thank you, confirmed.
