### ISSUE TITLE
objc_release crash on enums

### ISSUE THREAD

**Issue by kpgalligan** [JetBrains/kotlin-native#2931]
I'm not 100% sure this is just for enums, but it looks like a memory management race condition in objc interop.

Create an enum class

```kotlin
enum class Direction {
    NORTH, SOUTH, WEST, EAST, NORTHWEST, NORTHEAST
}
```

From Swift, loop through that a lot from more than one thread.

```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        for i in 0..<2 {
            AppDelegate.loadInBackground()
        }
        usleep(10000000)
        
        return true
    }
    
    static func loadInBackground()  {
        DispatchQueue.global(qos: .background).async {
            for i in 0..<100 {
                let et : Direction?
                switch i % 7 {
                case 0:
                    et = Direction.east
                case 1:
                    et = Direction.north
                case 2:
                    et = Direction.northeast
                case 3:
                    et = Direction.northwest
                case 4:
                    et = Direction.south
                case 5:
                    et = Direction.west
                default:
                    et = nil
                }
                if i % 1000 == 0 {
                    print("entity: \(et)")
                }
            }
            print("This is run on the background queue")
        }
    }
//AppDelegate etc
}
```

On multiple threads that will trigger a crash in objc_release.

[Xcode screenshot](https://drive.google.com/file/d/1ndWDOegGracAdUiYVVLZfMBwauB31Q2R/view?usp=sharing) for more context

I've tried this on 1.3.31. The version above has 2 threads and 100 loops, which should in theory make it unlikely to happen, but it's been happening every time. If repro isn't working, try higher loop count (assuming the problem is a memory/arc race).

[Slightly different form](https://drive.google.com/file/d/1Y3CoTQCO7RuSXuh4VfIcNptCPeRIe9Gy/view?usp=sharing). Happens occasionally.

## Update with some additional info

This is very easy to trigger and doesn't really need a loop.

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        for i in 0..<2 {
            AppDelegate.loadInBackground(tcount: i)
        }
        usleep(2000000)
        
        return true
    }
    
    static func loadInBackground(tcount: Int)  {
        DispatchQueue.global(qos: .background).async {
            let et = Direction.east
        }
    }
```

Adding a delay in the top loop prevents the issue, which suggests a race condition, but it seems unlikely that DispatchQueue would be so precise in the example above as to cause the crash every time.

Anyway, this avoids crashing. Smaller usleep delay values eventually start crashing again.

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        for i in 0..<2 {
            AppDelegate.loadInBackground(tcount: i)
            usleep(20000)
        }
        usleep(2000000)
        
        return true
    }
```

Some other things I've tried.

```kotlin
fun makeDir():Direction{
    initRuntimeIfNeeded()
    return Direction.EAST
}
```

Also crashes.

Putting the call in [an autoreleasepool](https://drive.google.com/file/d/1ODsAx-qhUUNAKhKNphQ10ID9Z1KX6S3_/view?usp=sharing) moves the place where it crashes, but still does.

Finally, just as a test I did the following which was no help.

```kotlin
enum class Direction {
    @SharedImmutable
    NORTH,
    @SharedImmutable
    SOUTH,
    @SharedImmutable
    WEST,
    @SharedImmutable
    EAST,
    @SharedImmutable
    NORTHWEST,
    @SharedImmutable
    NORTHEAST
}
```

I've also tried this on 1.3.21 and it seems to be the same.

**Comment by olonho** [comment]
Reproducer info.

main.swift:
```
import UIKit
import dirs

UIApplicationMain(0, nil, nil, nil)

class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        for i in 0..<2 {
            AppDelegate.loadInBackground(tcount: i)
        }
        usleep(2000000)
        
        return true
    }
    
    static func loadInBackground(tcount: Int)  {
        DispatchQueue.global(qos: .background).async {
            let et = Direction.east
        }
    }
}
```
dirs.kt:
```
enum class Direction {
    NORTH, SOUTH, WEST, EAST, NORTHWEST, NORTHEAST
}
```

 ./dist/bin/konanc -p framework dirs.kt -o dirs -target ios_x64

swiftc main.swift  -o d -target x86_64-apple-ios12.0-simulator -sdk `xcrun --show-sdk-path --sdk iphonesimulator` -emit-executable -F . 

install_name_tool -change @rpath/dirs.framework/dirs $HOME/kotlin-native/dirs.framework/dirs ./d

`xcrun --find simctl` spawn "iPhone 6" `pwd`/d

**Comment by benasher44** [comment]
You might be able to force the over release sooner if you wrap the background block in autoreleasepool

**Comment by SvyatoslavScherbina** [comment]
Fixed with #2936.

**Comment by benasher44** [comment]
Will there be an EAP or other dev release we can use if we're running into this?

**Comment by SvyatoslavScherbina** [comment]
Yes, I believe so.
