### ISSUE TITLE
Not finding runtime dll's in win10

### ISSUE THREAD

**Issue by darkoverlordofdata** [JetBrains/kotlin-native#2940]
I have a SDL2 demo for Windows 10.  We ran into some issues with it before (#1252) but I don't believe that is actually related to this issue.

After downloading the latest version of kotlin native, it builds ok, but now when I run it, it is unable to find SDL2_image.dll, which is at C:\msys64\mingw64\bin\SDL2_image.dll:

> C:/Users/darko/Documents/GitHub/kotlin-native-sdl2/build/konan/bin/mingw_x64/shmupwarz.exe: error while loading shared libraries: SDL2_image.dll: cannot open shared object file: No such file or directory

So I tried copying the SDL2 dll's to the same folder as my exe, but instead of fixing it, the error has changed

> C:/Users/darko/Documents/GitHub/kotlin-native-sdl2/build/konan/bin/mingw_x64/shmupwarz.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

That usually means there are dependant runtime references that are not found - in this case stuff like libpng16-16.dll. So I copied that dll, and the others into the local exe folder, and of course, now it works.

But that is not a fix, that is just verifying that it has trouble finding dll's - so how do I make it look in the system bin folders to find dll's?

**Comment by darkoverlordofdata** [comment]
It looks like you've made a lot of progress since the last time I was playing with k/n - the last time my code worked was on version 0.6, so I regression tested, and found that this breakage starts with version 0.8 - So I am stuck on version 0.7.1 until we can figure out what causes this - but it was something introduced at version 0.8. I don't see anything in the release change description that sounds like it would do it.

**Comment by msink** [comment]
It is Windows limitation, not related to Kotlin/Native.
Windows always looks for dll's first in current dir, second in dirs listed in system PATH envvar.

**Comment by olonho** [comment]
Indeed it's generic Windows behavior, which has nothing to do with Kotlin/Native.

**Comment by darkoverlordofdata** [comment]
I understand that. I guess I wasn't clear on that point. The Sdl dll's are
on my path. That is why 7.1 can find them. What I don't understand is why
starting with 0.8 it doesn't find dll's that are on my path.

**Comment by msink** [comment]
Sorry, but I do not believe. Are you sure it is in PATH?
Can you share your project sources?
For me everything works just fine.
