### ISSUE TITLE
Requires CLion to work in Windows10?

### ISSUE THREAD

**Issue by darkoverlordofdata** [JetBrains/kotlin-native#2942]
This is weird. I have no problems getting k/n 0.7.1 and prior working on windows. Starting with 0.8, I started getting dll not found exceptions unless I put the dll's in the same folder as the exe. I was told by k/n support that this is normal windows behaviour (#2940), however I did have the dll path in my path environment variable, so I'm not so sure I buy that explanation.

So I tried installing CLion+Kotlin Plugin (just the evaluation copy) to help me troubleshoot this. But CLion fails when creating the k/n Hello World template. Yarg! So I went back and tried again from the command line.

The thing is, after installing CLion, k/n now works as expected, I don't have to copy the dll's locally. I checked and made sure that CLion made no changes to environment variables. So I have no idea what it could have changed, but whatever, it works, right?

So, what happens when my CLion evaluation expires? Will kotlin/native start failing again? I thought this was an open source language. It should not require proprietary hooks to run, right? I guess I'll find out in 30 days?

**Comment by olonho** [comment]
There's no relation between CLion and CLI Kotlin/Native tools or behavior of produced programs. Likely your PATH was somehow changed and it led to behavior you describe.
