### ISSUE TITLE
iOS SDK `errno` macro clashes with `errno` name of PosixException.TryAgainException parameter

### ISSUE THREAD

**Issue by xsveda** [JetBrains/kotlin-native#2945]
When building an iOS Framework out of Kotlin Multiplatform build the framework's header file includes `PosixException.TryAgainException` definition with `initWithErrno` method that accepts `errno` parameter:

```
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("PosixException.TryAgainException")))
@interface Ios_integrationPosixExceptionTryAgainException : Ios_integrationPosixException
- (instancetype)initWithErrno:(int32_t)errno message:(NSString *)message __attribute__((swift_name("init(errno:message:)"))) __attribute__((objc_designated_initializer));
@end;
```

The XCode build of projects that includes this framework fails as this `errno` parameter  somehow clashes with `errno` macro from iOS SDK `usr/include/sys/errno.h` file:

```
__BEGIN_DECLS
extern int * __error(void);
#define errno (*__error())
__END_DECLS
```

**Comment by SvyatoslavScherbina** [comment]
Thanks, fixed in master by #2951
