### ISSUE TITLE
LLVM intrinsics for bit operations

### ISSUE THREAD

**Issue by ilya-g** [JetBrains/kotlin-native#2949]
The following bit operations are going to be introduced into the standard library ([KT-12749](https://youtrack.jetbrains.com/issue/KT-12749)):
- `countOneBits`
- `countLeadingZeroBits`, `countTrailingZeroBits`
- `takeHighestOneBit`, `takeLowestOneBit`

It seems to be possible to implement these operations with LLVM instructions as following:
- `countOneBits`: [`llvm.ctpop`](https://llvm.org/docs/LangRef.html#llvm-ctpop-intrinsic)
- `countLeadingZeroBits`: [`llvm.ctlz`](https://llvm.org/docs/LangRef.html#llvm-ctlz-intrinsic) with `is_zero_undef` parameter equal to 0.
- `countTrailingZeroBits`: [`llvm.cttz`](https://llvm.org/docs/LangRef.html#llvm-cttz-intrinsic) with `is_zero_undef` parameter equal to 0.
- `takeHighestOneBit`, `takeLowestOneBit` can be implemented with `ctlz` and `cttz`, though since they require special handling of zero input, they can call these instructions with `is_zero_undef != 0`, e.g.

    ```
    fun Int.takeHighestOneBit(): Int = 
        if (this == 0) 0 else 1.shl(Int.SIZE_BITS - 1 - llvm.ctlz(this, 1))
    ```

**Comment by olonho** [comment]
It's not required to use intrinsics here- just builtin_ctzl(),builtin_popcount() in C part of stdlib shall work as efficiently.

**Comment by ilya-g** [comment]
ok, good to know.

**Comment by ilya-g** [comment]
`builtin_ctz()` is undefined for zero input, unlike `llvm.ctlz(..., is_zero_undef = 0)`

**Comment by ilya-g** [comment]
Also I'm not sure which version of `ctz` to use for `kotlin.Int` and `kotlin.Long`
