### ISSUE TITLE
Long building for target release linux arm x32

### ISSUE THREAD

**Issue by caffeine-mgn** [JetBrains/kotlin-native#2953]
Host: Windows 10
Kotlin: 1.3.31

Build for target Linux arm x32 debug build take 10-15 sec. But when I try to build for target Linux arm x32 release it works infinity. I wait 20 min and build not done.

Log:
```
>..\gradlew linkMainReleaseExecutableLinuxArm32

............

> Task :repo:linkMainReleaseExecutableLinuxArm32
C:\Users\User\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1\bin\ld.lld: warning: lld uses extended branch encoding, no object with architecture supporting feature detected.
C:\Users\User\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1\bin\ld.lld: warning: lld may use movt/movw, no object with architecture supporting feature detected.
<-------------> 0% EXECUTING [3m 45s]
> :repo:linkMainReleaseExecutableLinuxArm32
```

**Comment by olonho** [comment]
Could you please provide an example project.

**Comment by olonho** [comment]
Also may make sense to try `--no-threads` linker switch around https://github.com/JetBrains/kotlin-native/blob/dcd773ece565c64884c1b251ad64b3899d3f56b6/konan/konan.properties#L212
