### ISSUE TITLE
32-bit windows target (mingw_x86) broken in Windows 7

### ISSUE THREAD

**Issue by anatoly62** [JetBrains/kotlin-native#2958]
mingw_x86 target in 1.3.31 just fine in Windows 10 pro, but is do not work in Windows 7 pro. 
It compiles, but do not execute.

**Comment by anatoly62** [comment]
kotlin-native v.1.21 Binary distribution from https://github.com/JetBrains/kotlin/releases/tag/v1.3.31

**Comment by msink** [comment]
Works for me.
What CPU is on your Win7 computer?
x86 terget is compiled for "sandybridge".

**Comment by anatoly62** [comment]
I`m tested four computers
1. Intel Core i-5 4200U 2.3 Ghz. Windows 10. 64-bit. 32 and 64 bit real prоgrams work fine
2. Intel Core i-3 540 3.1 Ghz.  Windows 7 pro 64-bit. 64 bit real prоgrams work fine. 32 bit helloWold can`t execute with message from Windows "Program is terminated".
3. AMD E-250 1.66 Ghz.  Windows 7 pro 64-bit. 64 bit real prоgrams work fine. 32 bit helloWold can`t execute with message from Windows "Program is terminated".
4. Intel Pentium G3450 3.4 Ghz Windows 7 pro 32-bit. 32 bit helloWolds can`t execute with message from Windows "Program is terminated"

**Comment by olonho** [comment]
Could you please clarify what is the application you're testing? Works for machine we tested for.

**Comment by anatoly62** [comment]
fun main(args: Array<String>) {
	println("Hello World")
}
konanc.bat test32.kt -target mingw_x86 -o test32 

Прекращена работа программы "POSIX WinThreads for Windows"
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	test32.exe
  Версия приложения:	1.0.0.0
  Отметка времени приложения:	5cd5338e
  Имя модуля с ошибкой:	test32.exe
  Версия модуля с ошибкой:	1.0.0.0
  Отметка времени модуля с ошибкой:	5cd5338e
  Код исключения:	c000001d
  Смещение исключения:	0000b44c
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1058
  Дополнительные сведения 1:	0a9e
  Дополнительные сведения 2:	0a9e372d3b4ad19135b953a78882e789
  Дополнительные сведения 3:	0a9e
  Дополнительные сведения 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by anatoly62** [comment]
> Could you please clarify what is the application you're testing? Works for machine we tested for.

**Comment by anatoly62** [comment]
closed by mistake

**Comment by olonho** [comment]
Try changing `-mcpu` to smth like pentium4 at https://github.com/JetBrains/kotlin-native/blob/bcd411837152f3546047b8703dbb493dabf0d545/konan/konan.properties#L442.

**Comment by anatoly62** [comment]
yes it works

**Comment by olonho** [comment]
OK, then we'll fix the definition in the master to `pentium4`
