### ISSUE TITLE
kotlin native gradle plugin arm

### ISSUE THREAD

**Issue by pawelbialek** [JetBrains/kotlin-native#2960]
Hi!

Does kotline native gradle plugin support build target for shared arm (32/64) ?

**Comment by olonho** [comment]
Not sure what do you mean.

**Comment by pawelbialek** [comment]
Hmm.. means I haven't elaborated well enough.
I mean the gradle 'multiplatform plugin - does it support the arm 64 build target with shared library variant ('dynamic') ?

**Comment by olonho** [comment]
arm64 is the CPU, when talking target is makes sense to mention OS to refer particular target.
