### ISSUE TITLE
No embedded bitcode for android native binaries

### ISSUE THREAD

**Issue by pgarba** [JetBrains/kotlin-native#2963]
Hi,

I played with kotlin native and discovered that its not possible to embed the llvm bitcode into the output binary for Android. The reason is that the kotlin native toolchain is using llvm-lto to link the bitcode objects and apply LTO. Is there a reason why you use llvm-lto instead of clang with the -flto option ?! 

The problem is that the "-fembed-bitcode" option is implemented in clang itself instead of llvm so choosing llvm-lto to to apply lto on the binaries will never be able to embed the bitcode into the objects.

Here in Thales we develop some tools that make use of the embedded bitcode. Thats why it would be great to find a solution for this.

Thanks,
Peter

**Comment by sbogolepov** [comment]
Hello. 
We are going to switch from `llvm-lto` to `clang` quite soon, stay tuned :)

**Comment by pgarba** [comment]
That’s great news. Would it be possible to also have a setting to enable the embedded bitcode like we have for iOS?!

embedBitcode "bitcode" // for release binaries.

**Comment by olonho** [comment]
What exactly are your scenarious of bytecode usage?

**Comment by pgarba** [comment]
Can I contact you by mail to discuss this further ?

**Comment by olonho** [comment]
Sure, or use PM in public Slack (@olonho).

**Comment by sbogolepov** [comment]
Replacing this issue with [KT-42700](https://youtrack.jetbrains.com/issue/KT-42700) because we are [migrating](https://github.com/JetBrains/kotlin-native/issues/4079) to YouTrack.
