### ISSUE TITLE
Codable support

### ISSUE THREAD

**Issue by Pomis** [JetBrains/kotlin-native#2978]
Is there any hope that Kotlin/Native will support Codable protocol? 
In order to support Swift serialization, classes should implement Codable protocol, but it is not possible to do now. Can't even import in Kotlin code it to create typealiasing.

**Comment by olonho** [comment]
Probably you could achieve same results serializing to JSON from Kotlin.

**Comment by Pomis** [comment]
Yes, that was the only suitable solution, now implementing it using Kotlinx Serialization library

**Comment by alexeisele** [comment]
@Pomis - once you had a class serialized to JSON via Kotlinx Serialization, did you try and use it in swift?
Any example of that if so?

**Comment by RomeuG** [comment]
Anybody know the status of `Codable` support ?

I am in a situation where it would spare a lot of work if I could expose `Codable` objects to Swift from Kotlin Multiplatform.

**Comment by SvyatoslavScherbina** [comment]
Nothing is changed so far.

**Comment by JavierSegoviaCordoba** [comment]
@olonho Kotlin Serialization could work with Swift clients (supposing we cannot use Ktor clients and so)

**Comment by prof18** [comment]
I've managed to use Kotlin Serialization with Swift and Alamofire. Give a look to this issue: https://github.com/Kotlin/kotlinx.serialization/issues/1210#issuecomment-735382571N

**Comment by Baileypollard** [comment]
Could really use this as well

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48081, closing.
