### ISSUE TITLE
Get a KClass instance from Obj-C/Swift

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/kotlin-native#2988]
Right now, there is no way to get a `KClass` instance from Swift / ObjC.

Let's say a Kotlin function is declared as such:

```kotlin
fun <T : Any> getInstance(type: KClass<T>)
```

The function `getInstance` is accessible but not callable from Swift.
This is because there is no way in ObjC / Swift to access a KClass instance.
Kotlin/Native should provide a way to access `KClass` instances directly from Swift / ObjC:

```swift
let manager = SampleKt.getInstance(type: Manager.kotlinClass) as! Manager
```

The current workaround is to explicitly make the `KClass` object accessible, such as:

```kotlin
object KotlinClasses {
    fun manager() = Manager::KClass
}
```

So we can use it in Swift:

```Swift
let manager = SampleKt.getInstance(type: KotlinClasses().manager()) as! Manager
```

This is not a scalable solution since the framework developper has to anticipate every classes the app developper will need.

**Comment by SvyatoslavScherbina** [comment]
> `let manager = SampleKt.getInstance(type: Manager.kotlinClass) as! Manager`

Not sure if this is implementable for protocols.
Do I understand correctly that `getInstance` can be used for protocols too?

**Comment by SalomonBrys** [comment]
Yes, it must exist for Kotlin interfaces, which are translated to protocols.

I understand that `Manager.kotlinClass` is not possible as-is if `Manager` is a Kotlin interface (translated to protocol).
I think there are many ways to circumvent this:

- K/N could automatically create an object containing methods to get classes for each exposed type. (Basically automate the `KotlinClasses` of my example workaround) => `SampleKt.getInstance(type: KotlinClasses.Manager())`.
- K/N could create, for each type, a `Meta` object that would allow to acces the KClass => `SampleKt.getInstance(type: Manager.Meta.kotlinClass())`.
- K/N could expose a function `func kotlinClass(meta: Any.Type) -> KotlinKClass` that would of course only work for Kotlin-translated classes => `SampleKt.getInstance(type: kotlinClass(Manager.self))`.

**Comment by Hazer** [comment]
@SalomonBrys the first one, in my opinion, scales poorly, names clashing may be a thing, but the other 2 options looks like nice additions to me, the 2nd is nice because is extensible, any extra metadata can be appended there, maybe some more "reflection"-kind of methods also can be included later, the last one looks clean and easier to implement to me, but it's not as extensible.

I have mixed feelings about solutions to this issue, giving limitations and such, but I truly think this issue is relevant.

**Comment by SvyatoslavScherbina** [comment]
I consider a bit different approach currently:
to provide `getKClass(ObjCClass): KClass<*>?` and `getKClass(ObjCProtocol): KClass<*>?` within Kotlin/Native standard libraries.

This would enable 
* making your library API accept classes and protocols directly
* adding  `kotlinClass`-like function to your framework explicitly if required.

**Comment by SvyatoslavScherbina** [comment]
I mean something like this: https://github.com/JetBrains/kotlin-native/pull/3036/files#diff-c138c1120f091ad4bbf41fc9adb26ab5R11

(See this [Kotlin](https://github.com/JetBrains/kotlin-native/pull/3036/files#diff-4c8ae35e49bcc0d3acee5359e3ece7ebR432) and [Swift](https://github.com/JetBrains/kotlin-native/pull/3036/files#diff-70d67fdf4f0ce9743b3fe83058f59ad1R586) code as an example).

@SalomonBrys what do you think?

**Comment by SalomonBrys** [comment]
That looks perfect.

Some questions:
- Your test do not show if `getKClass` is working for standard types, such as `String` or `Int`.
- Your test do not show if `qualifiedName` is supported. Not very important but useful (and supported by "native" Kotlin KClass).

Other than that, this fits my needs perfectly :)

**Comment by SvyatoslavScherbina** [comment]
> Your test do not show if getKClass is working for standard types, such as String or Int.

This is not supported by the API. What do you need this for?

> Your test do not show if qualifiedName is supported. Not very important but useful (and supported by "native" Kotlin KClass).

The resulting `KClass` is equivalent to what `::class` produces, so `.qualifiedName` is supported.

**Comment by SalomonBrys** [comment]
In the Kodein-DI container, it is possible to bind constants:

```kotlin
val kodein = Kodein {
    constant("name") with "Salomon"
    constant("answer") with 42
}
```

Such constants are then retrievable like this:

```kotlin
val name: String by kodein.instance("name")
val answer: Int by kodein.instance("answer")
```

In Swift, they would be retrieved like this:

```swift
let name: String = kodein.Instance(getKClass(String.self), "name") as! String
let answer: Int = kodein.Instance(getKClass(Int.self), "answer") as! Int
```

However, I can think of many ways to circumvent the absence of primitive KClass in the API, so this is definitely not blocking ;)

**Comment by SvyatoslavScherbina** [comment]
Thank you for the explanation.

Providing support for classes like `String` and primitive types here is somewhat complicated, especially considering Objective-C involved between Kotlin and Swift.
For example, `String.self` or `Int.self` aren't instances of `AnyClass` corresponding to Objective-C `Class` and Kotlin `ObjCClass` types.

**Comment by SalomonBrys** [comment]
No problems: this can be easily provided at the library level :)

**Comment by SvyatoslavScherbina** [comment]
Fixed with #3036 then.

**Comment by kar** [comment]
Could someone provide an example on how can I use this in Swift in MPP? I can't resolve the getOriginalKotlinClass call

**Comment by SvyatoslavScherbina** [comment]
@kar could you provide more details?
Are you trying to call `getOriginalKotlinClass` from Kotlin or Swift code? If it is Kotlin, please make sure that you have `import kotlinx.cinterop.getOriginalKotlinClass` and that this file belongs to target-specific source set, not common one.

**Comment by kar** [comment]
@SvyatoslavScherbina from Swift. Basically my question is what should we expect when it comes to Kotlin classes in Swift, how should (and shouldnt) we use them. I couldn't find any details in the docs.

**Comment by SvyatoslavScherbina** [comment]
> from Swift.

Then please add the method calling `getOriginalKotlinClass` to your Kotlin code, and then call this method from Swift, see e.g. https://github.com/JetBrains/kotlin-native/issues/2988#issuecomment-497268161.

> Basically my question is what should we expect when it comes to Kotlin classes in Swift, how should (and shouldnt) we use them.

Your question is not clear to me.

> I couldn't find any details in the docs.

Do you mean these docs?
https://kotlinlang.org/api/latest/jvm/stdlib/kotlinx.cinterop/get-original-kotlin-class.html

**Comment by kar** [comment]
Yeah. It wasn't clear to me on how to use it, but I'm a K/N beginner. Your explanation, works, thanks a ton!
