### ISSUE TITLE
How to call iOS10 os_log functions from kotlin

### ISSUE THREAD

**Issue by 9468305** [JetBrains/kotlin-native#2989]
Hi guys:

According to https://developer.apple.com/documentation/os/logging , I write some simple kotlin functions to print log on iOS.  
But all results is wrong:
1. `os_log_type_enabled()` always return false.  
```
os_log_type_enabled(OS_LOG_DEFAULT, OS_LOG_TYPE_DEFAULT)
os_log_type_enabled(OS_LOG_DEFAULT, OS_LOG_TYPE_INFO)
os_log_type_enabled(OS_LOG_DEFAULT, OS_LOG_TYPE_DEBUG)
os_log_type_enabled(OS_LOG_DEFAULT, OS_LOG_TYPE_ERROR)
os_log_type_enabled(OS_LOG_DEFAULT, OS_LOG_TYPE_FAULT)
```

2. `_os_log_create()` and `_os_log_internal()` 's first parameter declared as `dso: kotlinx.cinterop.CValuesRef<*>?`, which I don't know how to use.

```
public fun _os_log_create(dso: kotlinx.cinterop.CValuesRef<*>?, @kotlinx.cinterop.internal.CCall.CString subsystem: kotlin.String?, @kotlinx.cinterop.internal.CCall.CString category: kotlin.String?): platform.darwin.os_log_t? /* = platform.darwin.NSObject? */ { /* compiled code */ }

@kotlinx.cinterop.internal.CCall public external fun _os_log_internal(dso: kotlinx.cinterop.CValuesRef<*>?, log: platform.darwin.os_log_t? /* = platform.darwin.NSObject? */, type: platform.darwin.os_log_type_t /* = kotlin.UByte */, @kotlinx.cinterop.internal.CCall.CString message: kotlin.String?, vararg variadicArguments: kotlin.Any?): kotlin.Unit { /* compiled code */ }
```

I didn't found out the mapping functions of os_log, only `_os_log......` at package `platform.darwin.*` . Did I miss something?

Thank you!

**Comment by SvyatoslavScherbina** [comment]
`os_log` is not a function, it is function-like macro: https://developer.apple.com/documentation/os/os_log
Such macros aren't supported by Kotlin/Native.

**Comment by SvyatoslavScherbina** [comment]
> `os_log_type_enabled()` always return false.

Can't reproduce.

**Comment by olonho** [comment]
You could use your own logging facility using `os_log` in Objective-C or .def file and interop with them.

**Comment by 9468305** [comment]
@SvyatoslavScherbina @olonho 
Thank you!

I checked `os_log` header file. All `os_log` macros use `os_log_internal()` finally.  
```
_os_log_internal(&__dso_handle, log, type, format, ##__VA_ARGS__);

extern struct mach_header __dso_handle;
```

So I fixed my kotlin functions as below, which is work now.  
```
_os_log_internal(__dso_handle.ptr, OS_LOG_DEFAULT, OS_LOG_TYPE_DEFAULT, "$msg")
```
