### ISSUE TITLE
Can not found 1.3.40-compatible coroutines versions.

### ISSUE THREAD

**Issue by DTHeaven** [JetBrains/kotlin-native#3006]
Task :cross_utils:compileKotlinIos
w: skipping /Users/apple/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-iosx64/1.2.1/93d54c8602dda3c95095e46506a49e006aebe33a/kotlinx-coroutines-core.klib. The abi versions don't match. Expected '[9]', found '8'
w: The compiler versions don't match either. Expected '[1.3]', found '1.2-release-9411'
e: Could not find "/Users/apple/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-iosx64/1.2.1/93d54c8602dda3c95095e46506a49e006aebe33a/kotlinx-coroutines-core.klib" in [/Users/apple/Coder/Bytedance/SharedCode/demo/rocket_multi_platform, /Users/apple/.konan/klib, /Users/apple/.konan/kotlin-native-macos-1.3-eap-10240/klib/common, /Users/apple/.konan/kotlin-native-macos-1.3-eap-10240/klib/platform/ios_x64].

**Comment by olonho** [comment]
It is not yet published.

**Comment by DTHeaven** [comment]
> It is not yet published.

Is there a plan?

**Comment by olonho** [comment]
1.3.40 is not yet released, closer to release - yes.

**Comment by rharter** [comment]
Kotlin 1.3.40 is release now, and this same issue comes up. Any release plan?

**Comment by kpgalligan** [comment]
For kotlinx.coroutines? Should probably post in https://github.com/Kotlin/kotlinx.coroutines

I believe 1.2.2 is compatible but there's no 1.3.x for kotlin 1.3.40 yet

**Comment by artdfel** [comment]
Closed as obsolete
