### ISSUE TITLE
esp32/xtensa support

### ISSUE THREAD

**Issue by xian** [JetBrains/kotlin-native#3014]
Since #2268, Espressif has made a bunch of progress [adding support for llvm](http://lists.llvm.org/pipermail/llvm-dev/2019-March/130796.html) for its very popular esp32 microcontroller. Would be awesome if kotlin-native had integrated support.

**Comment by olonho** [comment]
Shalln't be too hard to implement now, as K/N is purely bitcode at the moment. Tricky part could be fitting into size requirements, but DCE effort may help here as well.

**Comment by aran-arunakiri** [comment]
yes please

**Comment by JcMinarro** [comment]
Any news about it?

**Comment by Ic-ks** [comment]
@xian is there any documentation how to add a new platform target to kotlin-native? BTW espressifs llvm project was moved:  https://github.com/espressif/llvm-project 
I can't wait to see kotlin running on affordable embedded devices :)

**Comment by michaelbrylevskii** [comment]
Any news about it?

**Comment by SvyatoslavScherbina** [comment]
No news about it, at least from Kotlin team.

**Comment by napperley** [comment]
Stand a much higher chance of getting the [Rasbperry Pi Pico](https://youtu.be/o-tRJPCv0GA) supported by Kotlin Native as a target (eg **rpiPico**), which should be made a **high priority**. Already LLVM supports the **ARM Cortex M0+** CPU.

**Comment by chris-hatton** [comment]
@napperley on point as usual 👌 good call on Pico as the KIoT outlet

**Comment by sbogolepov** [comment]
According to #4079, I'm closing this issue in favor of:
* [KT-43974](https://youtrack.jetbrains.com/issue/KT-43974). There you can share your use-cases of a possible esp32/xtensa target. 
* [KT-44498](https://youtrack.jetbrains.com/issue/KT-44498). Raspberry Pi Pico-specific ticket.
