### ISSUE TITLE
MSVC support on Windows

### ISSUE THREAD

**Issue by HydrogenC** [JetBrains/kotlin-native#3015]
Are you planning to add MSVC support or will always use MinGW on Windows?

**Comment by HydrogenC** [comment]
Other LLVM based compilers all offer support for MSVC on windows (eg. LDC, Rust), I hope Kotlin/Native to provide support for MSVC.

**Comment by HydrogenC** [comment]
It’s quite weird for a LLVM based compiler to be bundled with a full MinGW distribution.

**Comment by olonho** [comment]
Why do you believe MSVC support is critical?

**Comment by msink** [comment]
> weird for a LLVM based compiler to be depended on a full MinGW distribution
`msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1-2` is 2.6 GiB, where almost 2/3 (1.6 GiB) is clang+LLVM.
