### ISSUE TITLE
Can official share K/N development environment?

### ISSUE THREAD

**Issue by qhhonx** [JetBrains/kotlin-native#3025]
We knew that opening K/N project by IntelliJ with gradle plugin is preferable choice. But in those development environment We have missed C/C++ files intelligence because of using gradle building settings not CMake. So are there best tooling stacks used by official for convenient and fluent development progress? BTW, I am newbie to Kotlin from iOS without IntelliJ IDEA experience.

**Comment by olonho** [comment]
You can use CLion and AppCode with Kotlin/Native plugin, it supports Gradle projects.
