### ISSUE TITLE
GC of kotlin/native can not handle cycle reference?

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3026]

**Comment by acc110789** [comment]
![GC](https://user-images.githubusercontent.com/11617214/58476285-eb9a4b80-8182-11e9-84e4-5c294f77754b.png)

**Comment by acc110789** [comment]
the document of object GC suggest that after perform periodic garbage collection , it could handle cycle reference. how ever,  i found that is not the truth. below is my test code.

**Comment by acc110789** [comment]
~~~
import platform.darwin.NSObject
import kotlin.native.internal.GC

class KotlinObjectOne {
    var two: KotlinObjectTwo? = null
    var nsObject: NSObject? = null
}

class KotlinObjectTwo {
    var one: KotlinObjectOne? = null
}

@Suppress("CAST_NEVER_SUCCEEDS")
class KotlinNativeFramework {
    fun testString(obj: NSObject) {

        GC.start()
        GC.resume()

        val one = KotlinObjectOne()
        val two = KotlinObjectTwo()

        one.two = two
        two.one = one

        one.nsObject = obj

        println("begin gc")
        GC.collect()
        GC.collect()
        println("end gc")
    }
}
~~~

**Comment by acc110789** [comment]
instance 'one' reference to instance 'two' , and instance 'two' reference to instance 'one' , so ,  they have the relationship of 'cycle reference'。and instance 'one' also keep reference to 'nsObject' which is   create in object-c。if both instance 'two' and instance 'one' are recycled, then the method dealloc of 'nsObject' will be invoked.

**Comment by acc110789** [comment]
~~~
@interface AppDelegate ()

@end

@implementation AppDelegate



- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // KNFKotlinNativeFramework class is located in the framework that is generated during build.
    // If it is not resolved, try building for the device (not simulator) and reopening the project
    MyTestObject* obj = [MyTestObject  new];
    [[[KNFKotlinNativeFramework alloc] init] testStringObj:obj];
    return YES;
}

~~~

**Comment by acc110789** [comment]
![output](https://user-images.githubusercontent.com/11617214/58477096-4fbe0f00-8185-11e9-9064-5f3770cc073d.png)

console log:
there is no 'i am recycled' found after 'end gc'

**Comment by artdfel** [comment]
Hello! Thanks for your report, it was detailed enough. We inspected it and now can definitely tell, what is wrong here.
The garbage collector is not suitable for work like some ultimate dealloc methods. They manage only the memory, that came out of use. It means, that there should be no references to the memory from the current scope. In your example, both variables(`one` and `two`) are still in the scope of `thisString` function. So, they will not be collected by GC that you called from the same function. If you really want to start GC by yourself, just call it from the outside, just after the function.
Please note that in most situations you can let GC bear your variables by his own, with no explicit call.

**Comment by acc110789** [comment]
> It means, that there should be no references to the memory from the current scope.

thx, my stupid!!!
