### ISSUE TITLE
Lexical or Preprocessor Issue - compilation error in shared code header only when adding into iOS framework

### ISSUE THREAD

**Issue by karthikprabhuA** [JetBrains/kotlin-native#3031]
I am getting a compilation error "Lexical or Preprocessor Issue"**_"'$' in identifier"_** and **_"Extra ';' outside of a function"_** in the native shared code header file when adding into iOS framework. But its working when adding into iOS project.

**Comment by artdfel** [comment]
Hello! Can you please provide some kind of details or even the actual code you compile? For me, it looks like the name of your file can be broken, but it can be literally everything

**Comment by karthikprabhuA** [comment]
Actually its working when I create and add it into new framework. Its probably some settings on my old existing framework. I will check on my side. Thank you for your quick response
