### ISSUE TITLE
Run-time binary error on the latest Fedora 30

### ISSUE THREAD

**Issue by nikanorov** [JetBrains/kotlin-native#3037]
Can;t run produced binary executables on the latest Fedora release 30. Don't matter are they build on the same Fedora machine or other Linux. 

Error message:
error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

kotlin-multiplatform version 1.3.21

**Comment by olonho** [comment]
Please refer to https://fedoraproject.org/wiki/Changes/FullyRemoveDeprecatedAndUnsafeFunctionsFromLibcrypt

**Comment by artdfel** [comment]
For now, we recommend using the workaround described in official Fedora documentation from the previous comment. It says, that Fedora 30 users got to install additional package, `libxcrypt-compat`, manually. One can do it easily with a built-in package manager.
