### ISSUE TITLE
Support Dynamic Linking (WASM)

### ISSUE THREAD

**Issue by cromwellian** [JetBrains/kotlin-native#3039]
Kotlin-Native produces a lot of bloat from dependencies (a simple 20 line Kotlin class using kotlinx.coroutines and kotlinx.serialization compiles mainReleaseExecutable to a 1.6 megabyte WASM file)

It would be nice to support compiling in a mode where kotlinx.coroutines, kolinx.serialization, the kotlin runtime, etc would be separate WASM files. These can be cached separately for faster loading and less memory use. 

(In my use case, I have a lot of small Kotlin-Native 'plugins' separately compiled and late-loaded to WASM that run within the same Web Worker, or later, multiple workers sharing a heap when Web Assembly threads are separately implemented). 

Refs: https://github.com/emscripten-core/emscripten/wiki/Linking
https://webassembly.org/docs/dynamic-linking/

**Comment by olonho** [comment]
Sounds interesting, we generally accept patches in this directions, but not yet plan to implement it ourselves at the moment.

**Comment by SvyatoslavScherbina** [comment]
Kotlin team is working on a dedicated Kotlin to WebAssembly compiler backend.
So all works on wasm support in Kotlin/Native (through LLVM) were suspended.
More details: https://discuss.kotlinlang.org/t/state-of-webassembly-in-kotlin/18348
