### ISSUE TITLE
compile object c header files to klib fail. 

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3046]

**Comment by acc110789** [comment]
There are many object c classes which are generated by third part proto buffer utils.
We want to import these generated object c classes into 'iosMain'  of multiplatform kotlin module.
We use interop to compile the object c header files.
However, it fails.

**Comment by acc110789** [comment]
![fail](https://user-images.githubusercontent.com/11617214/58811669-d45fd000-8652-11e9-8275-c651caf953bf.png)

**Comment by acc110789** [comment]
Is there any suggestion or any workaround?

**Comment by artdfel** [comment]
Hello! It looks like some specific case, so it would be helpful if you can tell more details. 
What third-party utils did you use? It might be so, the instruments you chose to generate ObjC code had an influence on this result.

**Comment by acc110789** [comment]
hello, we use obejct-c code generator provided by https://github.com/protocolbuffers/protobuf

**Comment by acc110789** [comment]
I will provider you a demo later

**Comment by acc110789** [comment]
our problem is solved ,thx
