### ISSUE TITLE
./gradlew dependencies:update returns HTTP 404 when downloading mingw_x64Dependencies

### ISSUE THREAD

**Issue by grantas33** [JetBrains/kotlin-native#3057]
> Task :dependencies:mingw_x64Dependencies FAILED
Task ':dependencies:mingw_x64Dependencies' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:dependencies:mingw_x64Dependencies (Thread[Execution worker for ':',5,main]) completed. Took 0.72 secs.

FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/f/kotlin-native/dependencies/build.gradle' line: 48

* What went wrong:
Execution failed for task ':dependencies:mingw_x64Dependencies'.
> org.jetbrains.kotlin.konan.util.DependencyDownloader$HTTPResponseException: Server returned HTTP response code: 404 for URL: https://cache-redirector.jetbrains.com/download.jetbrains.com/kotlin/native/msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1-2.tar.gz

**Comment by msink** [comment]
Did you run it from WSL, CYGWIN or MSYS2 terminal?

**Comment by grantas33** [comment]
> Did you run it from WSL, CYGWIN or MSYS2 terminal?

Yes, I ran it on WSL (Ubuntu)

**Comment by msink** [comment]
So `System.getProperty("os.name")` returns something unexpected:

https://github.com/JetBrains/kotlin-native/blob/e7396682f5f98659cb66618b7cb56ce0ac2ed79a/shared/src/main/kotlin/org/jetbrains/kotlin/konan/util/DependencyExtractor.kt#L25

```kotlin
    internal val useZip = System.getProperty("os.name").startsWith("Windows")

    internal val archiveExtension = if (useZip) {
        "zip"
    } else {
        "tar.gz"
    }
```

**Comment by grantas33** [comment]
As I run the command from Ubuntu (Windows Subsystem for Linux), `System.getProperty("os.name")` returns `Linux` (as it probably should). Maybe the link of the `.tar.gz` file is down?

**Comment by msink** [comment]
There isn't `.tar.gz` for Windows, only `.zip`

**Comment by grantas33** [comment]
I expect `.tar.gz` since I'm on Linux (I need the `.tar.gz` version for Linux)

**Comment by msink** [comment]
Cross-compilation on Linux for Windows target is experimental and not included in published distribution.

**Comment by sbogolepov** [comment]
Indeed, current cross-compilation on Linux for Windows target is broken and should be reworked from the ground up. 
I created https://youtrack.jetbrains.com/issue/KT-43024 to track this problem.
