### ISSUE TITLE
iOS: binaries are not generated if there are no source files

### ISSUE THREAD

**Issue by fluidsonic** [JetBrains/kotlin-native#3062]
I have a multiplatform iOS submodule which does nothing but aggregating other iOS Gradle dependencies and exporting them (using `export(…)` in Gradle) into the final `.framework` which is then used by Xcode. That means the aggregation module has no sources on its own.

#### Actual
No binaries are generated when building the module. I have to add an empty Kotlin source file as a workaround.

#### Expected
As there are exports from other dependencies I expect binaries to be created independent of the existence of any source files.

Kotlin 1.3.31

**Comment by kerry** [comment]
hey @fluidsonic . I am trying the same thing. But in my case, if any class is not being used, that is not exported in the final framework. Can you share your project structure if possible?

**Comment by fluidsonic** [comment]
Do you use the `export()` functions in Gradle to re-export your aggregation library's dependencies?

That's roughly what I do:

```Kotlin
kotlin {
   iosArm64()
   iosX64()

   targets
      .filterIsInstance<KotlinNativeTarget>()
      .filter { it.targetName.startsWith("ios") }
      .forEach { target ->
         val dependencySuffix = target.targetName.toLowerCase()

         target.binaries {
            listOf(DEBUG, RELEASE).forEach { buildType ->
               getFramework(buildType).apply {
                  baseName = "XKotlin"
                  isStatic = false

                  freeCompilerArgs.add("-Xobjc-generics")
                  freeCompilerArgs.add("-Xdisable-phases=Devirtualization")

                  export(project(":genki-client-model"))
                  export(project(":genki-client-ui-model"))
                  export("team.genki:chotto-core-$dependencySuffix:0.9.41")
                  export("team.genki:chotto-client-$dependencySuffix:0.9.41")
                  export("com.github.fluidsonic:fluid-stdlib-$dependencySuffix:0.9.24")
                  export("com.github.fluidsonic:fluid-time-$dependencySuffix:0.9.12")
                  export("io.ktor:ktor-http-$dependencySuffix:1.2.2")
               }
            }
         }
      }

   // …
}
```

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-42246
