### ISSUE TITLE
Same labels are mutated with underscores

### ISSUE THREAD

**Issue by Pomis** [JetBrains/kotlin-native#3064]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/7953442/59412133-730fcd80-8dc5-11e9-9e83-a0507412a52e.png">
In some cases the compiled headers have argument labels with a lot of underscores. It make code look ugly, and also, when you add a new method with the same argument label in Kotlin code, you have to update all the other occurrences of this label with different number of underscores. 
Example:

```
interface Feature1Contract {
    ...
    interface View {
         fun init(presenter: Presenter)
    }
}

interface Feature2Contract {
    ...
    interface View {
         fun init(presenter: Presenter)
    }
}
```
will produce this:
```
class Feature1View : Feature1ContractView {
    func doInit(presenter presenter: Feature1ContractPresenter) {
    }
}

class Feature2View : Feature2ContractView {
    func doInit(presenter_ presenter: Feature2ContractPresenter) {
    }
}
```

**Comment by SvyatoslavScherbina** [comment]
This behaviour is intended to prevent clashes.
To avoid it you can rename `presenter` parameter in Kotlin to something more unique, e.g. `feature1Presenter`.

**Comment by Pomis** [comment]
> This behaviour is intended to prevent clashes.
> To avoid it you can rename `presenter` parameter in Kotlin to something more unique, e.g. `feature1Presenter`.

thank you for response. Do we really need labels there? Maybe it is possible to generate without labels, having only argument name?

**Comment by SvyatoslavScherbina** [comment]
This is not supported.
