### ISSUE TITLE
Document correct way to bundle dynamic libraries with binaries with Gradle plugin

### ISSUE THREAD

**Issue by sgarfinkel** [JetBrains/kotlin-native#3086]
I'm absolutely no expert to any of this, but as far as I can tell there's no obvious way to do this.

On Windows (not sure if this is the same on Linux) the OS searches for dynamic libraries in both the PATH _and_ the folder of the binary. I'm trying to build an application that uses cinterop. It works fine, however the library was not built statically, and due to some constraints I can't recompile it either.

Currently the run tasks simply fail because the dependent DLL is never installed next to the generated executable. I'd like to make this build self-contained without having to install these DLLs in my path. I'd also like to be able to ensure that whatever resultant bundle (zip/tar) includes this supporting binary.

Any help or suggested approaches are greatly appreciated. I'm not sure if there's an idiomatic way to do this.

**Comment by artdfel** [comment]
Hello! If I correctly understood your needs, you want to deal with the library without touching anything but build process. To do something like that, I can recommend trying two slightly different approaches, both use Gradle:

1. You can define, where your `run` task should try to find the library. This means that the path to the .dll  got to be resolved by Gradle, and then added to the PATH variable during the task execution.
2. To be more general, you can even write the addition for your `bundle` task, that will copy an instance of the .dll next to your executable.

If there will come more questions, feel free to ask here, or you can try [public slack](https://kotlinlang.slack.com), it is the main community hub for now.

**Comment by sgarfinkel** [comment]
@artdfel Yeah, I ended up just placing the DLL in a common location and updating the runTasks that use it. It'd be awesome though if the DLLs could be bundled into the klib artifacts somehow so that project dependencies would work correctly. I think Gradle Native does this correctly.
