### ISSUE TITLE
Warning - 'swift_name' attribute has invalid identifier for base name

### ISSUE THREAD

**Issue by tshort15-ford** [JetBrains/kotlin-native#3094]
When linking to a framework, in the client app I'm seeing the above warning due to serializer, e.g. 

'swift_name' attribute has invalid identifier for base name __attribute__((swift_name("<class name>.$serializer")))

I'd guess it's due to the .$ in the name.  Is there any way to fix this warning?

**Comment by SvyatoslavScherbina** [comment]
Known issue.
To workaround it add `-Xcc -Wswift-name-attribute` to "Other Swift Flags" in "Build Settings" of your client app.

(If you import Kotlin framework to Objective-C code, then adding `-Wswift-name-attribute` to "Other C Flags" may also be required).

**Comment by SvyatoslavScherbina** [comment]
(updated the comment above)

**Comment by tshort15-ford** [comment]
Thanks - it'd be ideal not to require a settings change to ignore the warning, but at least there's a way.

**Comment by SvyatoslavScherbina** [comment]
Warning will be ignored by default in 1.3.41, proper fix will be included to 1.3.50.
