### ISSUE TITLE
platform.CoreBluetooth should be available on macOS

### ISSUE THREAD

**Issue by LouisCAD** [JetBrains/kotlin-native#3099]
If you take [symbols from CoreBluetooth](https://developer.apple.com/documentation/corebluetooth/cbcentralmanager?language=objc), you can see they are available in macOS (starting version 10.17), but when I copy paste this code in a macosx64 source set:
```kotlin
private suspend fun letsTryBluetooth() {
    platform.CoreBluetooth.CBCentralManager(delegate = null, queue = null)
}
```
it's marked red by the IDE, which is not the case when pasted in an `iosArmXX` source set.

Could you make this framework available to use on macOS from Kotlin/Native?

If other frameworks are in this case, it'd be really great to have them too.

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/3141.
