### ISSUE TITLE
Copying Data Classes with NSCopying in Objc/Swift

### ISSUE THREAD

**Issue by tedlefter** [JetBrains/kotlin-native#3108]
Hi!
When having a data class in Kotlin, the class generated in Objc/Swift does not implement `copy()` as a deep copy, It will return the same instance of the object being copied.
The compiler will generate the `doCopy()` method that does the deep copy, but I was wondering what was the reason behind this?
Also, the `doCopy()` requires passing in all values for each class attribute, making it less useful in my opinion.

**Comment by SvyatoslavScherbina** [comment]
Hi.

> It will return the same instance of the object being copied.

To support using Kotlin objects as `NSDictionary` keys.

> The compiler will generate the doCopy() method that does the deep copy,

AFAIK it does shallow copy as it just provides access to Kotlin data class `copy` method.

**Comment by tedlefter** [comment]
Maybe I am misunderstanding something.
AFAIK, `NSDictionaries` use the hash value of the object used as the key. A data class with the same contents should and will generate the same hash. Not sure what role 'copy()' has to play here.

Because this is a `Data Class`, I would expect the `NSCopying` method `copy()` to be implemented as doing a deep copy. In the same way that the `copy()` is implemented for JVM by returning a new instance with the same data.
In my opinion, providing the `doCopy()` here and forcing to specify all the parameters doesn't bring any value. With the same effort, one could just create a new instance of the data class and specify all the values.

Hope this clarifies it a bit.

**Comment by SvyatoslavScherbina** [comment]
> A data class with the same contents should and will generate the same hash.

Unless data class overrides `hashCode`.

> Not sure what role 'copy()' has to play here.

`NSDictionary` copies the keys, see e.g. https://developer.apple.com/documentation/foundation/nsdictionary/1410010-initwithobjects?language=objc

> doing a deep copy. In the same way that the copy() is implemented for JVM

It is not a deep copy, it is shallow copy.

> I would expect the NSCopying method copy() to be implemented as doing a deep copy.

`NSCopying` is not specified good enough to expect any particular copying policy here.

> In my opinion, providing the doCopy() here and forcing to specify all the parameters doesn't bring any value. With the same effort, one could just create a new instance of the data class and specify all the values.

`doCopy` is provided automatically since a `data class` has `copy` method. Currently default arguments is not supported when importing Kotlin to Objective-C/Swift.

**Comment by tedlefter** [comment]
> It is not a deep copy, it is shallow copy.
Yep, you are right, it is a shallow copy. That was my mistake 🤦‍♂ I'm sorry about this.

Thank you very much for the explanation and your time.
