### ISSUE TITLE
Compilation failed: null with Kotlin 1.3.40

### ISSUE THREAD

**Issue by jcraane** [JetBrains/kotlin-native#3109]
We migrated our Kotlin multiplatform project from 1.3.21 to 1.3.40 (and updated all dependencies accordingly) and now we get the following error when compiling the common Kotlin code to IOS native:

```
> Task :common:linkDebugFrameworkIos
e: Compilation failed: null

e: kotlin.KotlinNullPointerException
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.getNode(DFGBuilder.kt:516)
```

There are lots of classes in our common code so it is not easy to determine what causes the error. Adding --info or --debug does not provide much more info.

Is there a preferred way of debugging these kind of issues? I can copy the code to a minimal project and then manually removing classes to see when it will work but this is quite tedious.

Thanks!

**Comment by homuroll** [comment]
Please try compile with option `-Xdisable-phases=Devirtualization,BuildDFG` or with gradle:
```
compilations.all {
    kotlinOptions {
        freeCompilerArgs += "-Xdisable-phases=Devirtualization,BuildDFG"
    }
}
```
and tell us if it helps or not.

**Comment by jcraane** [comment]
I am not sure where to put that configuration. I get a message compilations is an unknown property (in gradle). Apart from this I was able to localize this issue: The following construction does compile/run on the JVM but gives a NullPointerException when compiling to native:

```
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient

@Serializable
data class CachedItem(var data: String) {
    @Transient
    var timeProvider = RealtimeProvider()
    var creationTime = timeProvider.getNow()
}

class RealtimeProvider {
    fun getNow() = 100L
}
```

If I remove the dependency on the timeProvider in the initialization of the creationTime property, the code does compile.

I can workaround this issue but should this scenario be supported (it was working in 1.3.21)?

**Comment by homuroll** [comment]
Looks like a bug in the serialization plugin. @sandwwraith will look at it.

**Comment by NiKlimenko** [comment]
@jcraane seems you are trying to serialize the `creationTime` property which depends on `timeProvider` that you skipped for serialization.

**Comment by jcraane** [comment]
That is correct indeed. But serializing/deserializing works on the JVM in this case but the compilation phase to IOS/native code fails. This was working with kotlin 1.3.21. If I remove the @Serializable, compilation to native code works (but than I cannot deserialize/serialize it from/to JSON of course).

**Comment by olonho** [comment]
This is an issue of https://github.com/Kotlin/kotlinx.serialization compiler plugin, so would be better to move discussing the problem there.

**Comment by webfrea-k** [comment]
@homuroll I've tried to add `"-Xdisable-phases=Devirtualization,BuildDFG"` as you suggested. The command leads to another error:
``` 
* Compiler version info: Konan: 1.3 / Kotlin: 1.3.40
 * Output kind: FRAMEWORK

e: java.lang.UnsupportedOperationException: org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl@4ab32a94
```
Hope this helps, otherwise I'll wait for the kotlinx.serialization fix.

**Comment by sandwwraith** [comment]
I can confirm that the problem is caused by `creationTime` dependent on `timeProvider` variable. Such code causes problems in the serialization plugin now.

**Comment by webfrea-k** [comment]
@sandwwraith can anything else cause this? We have a lot of classes too, but I don't think there is a single case where child class would not be marked as @Serializable (all the classes top-down are serializable in our case).

**Comment by edenman** [comment]
I know it's been a couple years, but I'm seeing the same issue https://youtrack.jetbrains.com/issue/KTOR-2174

**Comment by SvyatoslavScherbina** [comment]
We are [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), so I'm closing this issue in favour of [KT-45044](https://youtrack.jetbrains.com/issue/KT-45044).
