### ISSUE TITLE
collection class supplement

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3125]
We need queue、PriorityQueue、LinkedList，thx。
Is there any plan to add there API in stdlib_common?

**Comment by olonho** [comment]
Not sure if this issue is relevant for Kotlin/Native, as common stdlib is tracked in https://youtrack.jetbrains.com/issues/KT. Practically speaking, you may take a look at https://github.com/bmaslakov/kotlin-algorithm-club.

**Comment by acc110789** [comment]
thx
