### ISSUE TITLE
Memory leaks using Worker

### ISSUE THREAD

**Issue by SBNTT** [JetBrains/kotlin-native#3133]
I'm coding a simple socket server
Main thread run an infinite loop, and dispatch jobs to a worker pool

The main loop looks like something like that:
```kotlin
var socket: Int
while (running) {
    updateWorkersState()
    socket = accept(serverSocket, null, null)

    if (socket > 0) {
        enqueueJob(socket)
    }

    if (jobsQueue.isNotEmpty()) {
        dequeueJob()
    }
}
```

When i launch some benchmarks, memory used by the program grows up...

**Comment by artdfel** [comment]
Hello! It would be nice to have an example with step-by-step instructions. How did you make the benchmarks? 
Have you managed this problem for now, or what is the reason to close it?

**Comment by SBNTT** [comment]
Hi

I've made an example as simple as i can:
https://gist.github.com/SBNTT/1a5074de3bfe392f333bdad053e5efe6

There no worker pool management here as the problem stay the same with and without

I used a http benchmark tool like Siege 
run the server
run a benchmark and observe memory used by the server
memory grows up and is never freed after the benchmark is done

Got no solution for now.
i'll implement connection handling and threads management in C

**Comment by olonho** [comment]
You start worker on every connection, and never terminate it. It is incorrect.

**Comment by SBNTT** [comment]
I terminate them in updateWorkersState() function.

as i said before, this example start a worker for every connection just for simplicity.
i got a version with a fixed size worker pool and this does not change anything

**Comment by SvyatoslavScherbina** [comment]
https://gist.github.com/SBNTT/1a5074de3bfe392f333bdad053e5efe6#file-kn-3133_1-kt-L139

How do you stop this event loop? Have you checked that termination request actually gets processed?

https://gist.github.com/SBNTT/1a5074de3bfe392f333bdad053e5efe6#file-kn-3133_1-kt-L77

How do you release this future? Every future result should be consumed (e.g. with `.result`) to avoid memory leak.

**Comment by SBNTT** [comment]
Thanks

I though it stop itself when it finishes its execution, but actually wrapping worker execution in `runBLocking` isn't needed so..

I use the macos activity monitor, and yes, termination request gets processed because threads amount decreases.

The result of this future is Unit, so it looks strange to consume it no ?
Event if I make a call to the `.result` field, it does not change anything

i've done a revision of the gist with that

**Comment by SvyatoslavScherbina** [comment]
`requestTermination()` returns a future too, and that requires explicit consumption as well.

**Comment by SBNTT** [comment]
So I move to my real version where I do not start a new worker for each connection. Then, with a worker pool, i do not request termination during runtime os no need to manage the `Future` returned by `requestTermination` 

Removing the useless `runBLocking` and make a call to `Future.result` to consume it solves the problem

Thannnnks
