### ISSUE TITLE
Compiling SwiftUi for desktop when using cocoaPods fails

### ISSUE THREAD

**Issue by luca992** [JetBrains/kotlin-native#3134]
The following error is thrown:
```
ld: in /<path>/app/build/cocoapods/framework/app.framework/app(combined.o), 
building for UIKitForMac, but linking in object file built for macOS, file 
'//<path>/app/build/cocoapods/framework/app.framework/app' for architecture x86_64
```

Looks related to [this](https://forums.developer.apple.com/thread/117229)
`Libraries coming into the UIKit for Mac environment need to be compiled for the iOS platform, not the macOS platform. `

**Comment by artdfel** [comment]
Hello! Thank you for the report.
Can you please provide an additional information on the project?
 What was the target you were building for? Is this issue reproducible for some simple project, or you cannot get it outside of the current one?

**Comment by luca992** [comment]
In the kotlin project I am targeting macosX64, iosX64, iosArm64. I think it should be reproducible with any simple project. I can make one if you would like.

**Comment by artdfel** [comment]
Okay, I see. If it is possible to have an accurate way to reproduce this, it would be very helpful.

**Comment by luca992** [comment]
https://github.com/luca992/SwiftUi-Destop-Test-Project

Just open `SwiftUi Kotlin Native Test/SwiftUi Kotlin Native Test.xcworkspace`

Running on iphone simulator works.
Running on desktop fails with the error I reported

**Comment by michallaskowski** [comment]
FYI: https://github.com/CocoaPods/CocoaPods/issues/8877#issuecomment-499752865

So the code needs to be compiled with extra CFLAGS and LDFLAGS. I am yet unsure if this can be done easily in build.gradle for Kotlin Native or Multiplatform, or a bigger change is needed.

**Comment by luca992** [comment]
Is there anyway to workaround this? 
I tried replacing `$OTHER_CFLAGS` with `-target x86_64-apple-ios-macabi -miphoneos-version-min=13.0` in the generated podspec file, and running pod install again. That did not help

**Comment by SvyatoslavScherbina** [comment]
> I tried replacing $OTHER_CFLAGS with -target x86_64-apple-ios-macabi -miphoneos-version-min=13.0 in the generated podspec file

This is not supposed to work.

> Is there anyway to workaround this?

I'm not aware of any.

**Comment by luca992** [comment]
So does a new target for swiftui desktop need to be created?
similar to this commit adding linux/arm64 support?
https://github.com/JetBrains/kotlin-native/commit/c3638e48dc78ae9fdd087f45e866c63ddbb4c874

**Comment by SvyatoslavScherbina** [comment]
This should help, but I'm not sure that this is the only option.

**Comment by luca992** [comment]
related:
https://github.com/JetBrains/kotlin-native/pull/3383

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-40442
