### ISSUE TITLE
Dwmapi.dll is not linked

### ISSUE THREAD

**Issue by Trumeet** [JetBrains/kotlin-native#3135]
While I was trying to use the Dwm APIs in the platform library for Windows, I discovered that the required DLL `dwmapi.dll` is not seemed to be linked in the `def` file.

Unfortunately, I do not understand any C/C++ stuff so I'm afraid I cannot give the further information if any.

See: 
[https://github.com/JetBrains/kotlin-native/blob/d5096cbb1e14ed4f015cd63533f1b05a80fc03d4/platformLibs/src/platform/mingw/windows.def#L2](https://github.com/JetBrains/kotlin-native/blob/d5096cbb1e14ed4f015cd63533f1b05a80fc03d4/platformLibs/src/platform/mingw/windows.def#L2)

[https://docs.microsoft.com/en-ca/windows/desktop/api/dwmapi/nf-dwmapi-dwmextendframeintoclientarea#requirements](https://docs.microsoft.com/en-ca/windows/desktop/api/dwmapi/nf-dwmapi-dwmextendframeintoclientarea#requirements)

The compile error: 
```
C:\Users\yuutaw\AppData\Local\Temp\konan_temp8122729484653105859\combined.o:(.text+0x29159): undefined reference to `DwmExtendFrameIntoClientArea'
```

**Comment by msink** [comment]
for kotlinc-native:
`-linker-option -ldwmapi` 

Or for build.gradle.kts:
```
kotlin {
    mingwX86().binaries.executable {
        linkerOpts("-ldwmapi")
    }
}
```

**Comment by Trumeet** [comment]
> for kotlinc-native:
> `-linker-option -ldwmapi`
> 
> Or for build.gradle.kts:
> 
> ```
> kotlin {
>     mingwX86().binaries.executable {
>         linkerOpts("-ldwmapi")
>     }
> }
> ```

Thanks and it works!

Are there any plans to link this library in the platform library def file?

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/4511.
