### ISSUE TITLE
Objects aren't deleted when they go out of scope

### ISSUE THREAD

**Issue by mr0xf00** [JetBrains/kotlin-native#3155]
Hi there. I'm giving KN a try to see if it's the right pick for a use case I have : using it for the business logic in a c++ application. However I'm noticing something weird.

Consider the following code : 
```kotlin
fun alloc(){
    val c = IntArray(100000000)
    c.forEachIndexed{i,_ -> c[i] = if(i %2 == 0)  255 else 0}
    println("average : ${c.average()}")
}
fun main() {
    alloc()
    while (true){
        println("done")
        sleep(1)
    }
}
```
What I expected would happen here is that it would allocate the size of Int times 100000000 (381MB as expected) while in `alloc()` and by the time it reaches the while loop, that IntArray would have been freed since there is nothing referencing it. But this not the case since even while "done" is being printed, the memory usage is still 381MB. I initially assumed that since KN uses reference counting, this would behave like it would with `shared_ptr` in c++, but it seems no to do so in this case. So could it perhaps be using a GC which didn't get triggered before the while loop ? 
To test that I added this :
```kotlin
    repeat(20){
        alloc()
    }
```
What happens here is that it keeps allocating memory until there is none left, and then throws an error about not being able to allocate.
But if I were to change it to the following : 
```kotlin
    repeat(20){
        alloc()
        GC.collect()
    }
    while (true){
        println("done")
        sleep(1)
    }
```
Then it works exactly as I expected the previous one to do : Never goes above 381MB of memory usage, and by the time it's printing those dones, the memory usage is something like 300KB. 
However by changin the array to a list : 
```kotlin
fun alloc(){
    val c = List(100000000) {if(it %2 == 0)  255 else 0}
    println("average : ${c.average()}")
}
```
The 20 iterations do finish, but the memory usage remains above 2GB after. Removing the `GC.collect()` line leads to it stopping early.

I was able to replicate this behavior in both debug and release mode, using the -opt option, using 1.3.41 and 1.3.0, on Linux and Windows. Which leads me to believe that I might be missing something fundamental about how KN works.

**Comment by msink** [comment]
So objects really are deleted, but memory not returned to system.
Not surprising - it's how C heap works, memory used by allocated and freed objects not returns to system, but is available for allocating next objects.

**Comment by mr0xf00** [comment]
Thanks for the reply. But I don't seem to follow.
In a language with manual memory management such as C, as long as I'm allocating something that doesn't exceed what the OS would give me, for as much as I want, the following would work, since I'm taking care of the deallocations myself :
```c
for(i = 0; i < 1000; i++){
     uint8_t *p = malloc(sizeof(uint8_t)*100000000);
     //some operation
     free(p);
}
```
Same thing on the JVM. I can run a similar loop as much as I want, and the GC always kicks in at the right time to collect the unreferenced objects.
But in KN, I simply can't get it to do that. It just keeps allocating memory each time, until there is none left and exits before finishing all iterations. As is the case with this code :
```kotlin
fun main() {
    repeat(1000){
        val c = IntArray(100000000)
        c.forEachIndexed{i,_ -> c[i] = if(i %2 == 0)  255 else 0}
        println("average $it : ${c.average()}")
    }
}
```
Here is a video of what happens when I run it : https://i.imgur.com/JGsqMLb.mp4

A real life use case for this would be a batch image processing utility : The user has an X amount of memory available, and wants to for example crop 100 images in a directory. If the images take up 0.9*X memory each when loaded, then it should be completely possible to process them all, as long as each image is handled separately and then saved and discarded (i.e : the array containing the pixel values is dereferenced). 
Would this be feasible in KN right now ?

**Comment by olonho** [comment]
If you use arena-based allocations with `memScoped` you can exactly control lifetime. Probably we could fine-tune GC heuristics to trigger GC not only on RC thresholds, but also on memory allocated. I'll try to sketch something around it, but generally expecting that memory will be freed at some moment is usually not very good idea in systems with automated memory management.

**Comment by mr0xf00** [comment]
I'm assuming that you're talking about `memScoped` + using the `nativeHeap.allocArray` stuff with the `free` to match since just wrapping what's inside the loop with `memScoped` didn't have any effect. But I'd really like to avoid all forms of manual memory management for what I need to use KN for.

As for the GC using RC thresholds, I did the test again with a big amount of small arrays totalling around 100GB and it stayed under a reasonable amount of memory usage. So apparently the problem here is that I was allocating a small number of huge objects. But that's really unavoidable when dealing with stuff like images. 

So is there any possibility of adding something that would allow us to set a memory threshold, above which the GC kicks in (and if possible have it pick a value based on the total memory). Or even allow a `shared_ptr` like behavior (which what I was expecting at first) where objects get deleted _immediately_ whenever their reference count drops to 0 ?

**Comment by olonho** [comment]
If you'll put `memScoped` inside loop it will automatically free immediately. Or Arena could be used for explicit release control, if needed.

I will try to prototype a solution which takes into account the total allocation size, not only release set size.

**Comment by mr0xf00** [comment]
Ok thanks ! Looking forward to that.
Although your suggestion of wrapping the code in `memScoped` didn't seem to have any effect : https://i.imgur.com/hDHqYDe.mp4

**Comment by olonho** [comment]
I suggest to combine native allocations with `alloc` and `memScoped`.

**Comment by olonho** [comment]
In https://github.com/JetBrains/kotlin-native/pull/3162 implemented allocation-size aware thresholds.
