### ISSUE TITLE
Strange behavior with class named Type

### ISSUE THREAD

**Issue by Pomis** [JetBrains/kotlin-native#3167]
Existing Koltin class:
```
class MapboxModel(
...
) {
    enum class Type { NONE, TASK, SEARCH }
}
```
Using it in Swift:
```
extension MapViewController : MapContractView {
    
    func setCompassButton(mapType: MapboxModel.Type) {
        
    }
```
Causes following behavior: swift compiler detects as if needed method is not implemented and suggests adding protocol stubs. After doing this, it fails on invalid redeclaration. 
Works perfect if rename Type to any other name.
It would be better to rename class at compile time, as if it is done with fun init() -> func doInit()

**Comment by SvyatoslavScherbina** [comment]
Thanks, confirmed.
