### ISSUE TITLE
When Worker's executeAfter method will be available on a release version

### ISSUE THREAD

**Issue by romanandreyvich** [JetBrains/kotlin-native#3171]
Question is how fast pull requests are going to be available in a release version? In our case, we want to use Worker.executeAfter method that have been implemented on may 14, here:
https://github.com/JetBrains/kotlin-native/pull/2971 but it's still not available (in Kotlin 1.3.40).

How soon this pull request will be included to a release version?

**Comment by olonho** [comment]
According to normal Kotlin release schedule it will be available in 1.3.50.
