### ISSUE TITLE
Unable to update to kotlin native 1.3.41

### ISSUE THREAD

**Issue by mikezliu** [JetBrains/kotlin-native#3182]
I've been stuck on Kotlin 1.3.21 for a while and want to update to the latest version of Kotlin (1.3.41)!

After incrementing Kotlin to 1.3.41, I get the following error:

Unable to find method 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeCompilation.getLinkTask(Lorg/jetbrains/kotlin/gradle/plugin/mpp/NativeOutputKind;Lorg/jetbrains/kotlin/gradle/plugin/mpp/NativeBuildType;)Lorg/jetbrains/kotlin/gradle/tasks/KotlinNativeLink;'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

How can I debug this? I have tried re-downloading dependencies but no luck

**Comment by olonho** [comment]
Which version of Gradle are you using?

**Comment by mikezliu** [comment]
5.4.1

**Comment by michalharakal** [comment]
Deleting of all cache folders helped in my case with similar issues. 

- ~/.gradle/caches
- ~/.konan
- .gradle folder in your project's folder

**Comment by ilmat192** [comment]
The `getLinkTask` method was deprecated in 1.3.30 and removed in 1.3.40. Use the [binaries DSL](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries) instead.

**Comment by mikezliu** [comment]
I'm not using getLinkTask myself - I'm guessing one of my libraries (ktor, serialization, etc.) is using it

**Comment by ilmat192** [comment]
> I'm guessing one of my libraries (ktor, serialization, etc.) is using it

As far as I know they don't. May be some plugin? Could you share a link to your project or at least provide your build script?
