### ISSUE TITLE
Build error when path to a project contains spaces

### ISSUE THREAD

**Issue by artem-mi** [JetBrains/kotlin-native#3183]
I use kotlin multiplatform to build a set of common modules for Android and iOS app in my project. During the build process I got a lot of _“Source file or directory not found: ”_ errors. If I move my project to a directory without spaces in the path, everything builds fine.
You can find full build log here: https://justpaste.it/2aocl.

I have also tried to build separate kotlin source file (using _konanc @\<argfile\>_ option) which path contains spaces and the problem has taken place too.

kotlin gradle plugin version used is **1.3.41**

**Comment by ilmat192** [comment]
Opened a YT track mirror: https://youtrack.jetbrains.com/issue/KT-35934

**Comment by ilmat192** [comment]
Fixed by https://github.com/jetbrains/kotlin/commit/8158d34bdac8d4299677a8bd83623f19b1faf989
