### ISSUE TITLE
class generated by cinterop clash with already existed class。

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3185]
We have two object-c classes，one class name is "IMRPost" , another class name is "IMRPostMeta"。
When we use cinterop importing these two classes, we found cinterop generate a companion object who's name is "IMRPostMeta" for "IMRPost" . The new generated class "IMRPostMeta" clash with our already existed object-c class "IMRPostMeta"。

We think the postfix "meta" is very common, can you choose another postfix for your newly generated classes or interface?

**Comment by olonho** [comment]
This is an Objective-C convention we cannot change.
