### ISSUE TITLE
Wasm doesn't support exceptions

### ISSUE THREAD

**Issue by sandwwraith** [JetBrains/kotlin-native#3194]
On attempt to throw/catch any exception (such as in `assertFailsWith` test function), wasm runtime crashes and reports 

```
runtime assert: Exceptions unsupported
Exception executing entry point: Error: abort()
Error: abort()
    at abort (build/bin/wasm32/debugTest/test.wasm.js:379:19)
    at _ZN5konan5abortEv (wasm-function[8637]:1)
    at _Z19RuntimeAssertFailedPKcS0_ (wasm-function[8622]:196)
    at ThrowException (wasm-function[37]:149)
```

This makes almost every Kotlin library (e.g. stdlib, kotlinx.serialization, coroutines, ktor) **unusable (or very dangerous to use)** on wasm target. 

Some resources (https://reviews.llvm.org/D43746, https://v8.dev/blog/emscripten-llvm-wasm) claims that LLVM - WASM translator supports them, so that should be possible technically (although I'm not a LLVM expert to be 100% sure). There's also an exception handling [proposal](https://github.com/WebAssembly/exception-handling/blob/master/proposals/Exceptions.md) for WebASM, so I think exceptions are on their roadmap. 
Anyway, Kotlin as a language has exceptions, so it would be not fair to support them only on particular platforms.

**Comment by SvyatoslavScherbina** [comment]
Kotlin team is working on a dedicated Kotlin to WebAssembly compiler backend.
So all works on wasm support in Kotlin/Native (through LLVM) were suspended.
More details: https://discuss.kotlinlang.org/t/state-of-webassembly-in-kotlin/18348
