### ISSUE TITLE
Q: how to adjust naming?

### ISSUE THREAD

**Issue by 4ntoine** [JetBrains/kotlin-native#3199]
Since swift does not have namespaces and i have same classnames i'm getting ugly names in obj-c wrapper. Any opportunity to adjust it? Please read my full question at SO: https://stackoverflow.com/questions/57101327/how-to-adjust-swift-classnames-for-kotlin-multiplatform-project-with-cocoapods

**Comment by SvyatoslavScherbina** [comment]
The answer to your question at SO is correct.
