### ISSUE TITLE
Performance hit when function uses `CharSequence` instead of `String`

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/kotlin-native#3200]
I made a library for high-performance streaming of HTML content in Kotlin called [kotlin-html](https://github.com/ScottPierce/kotlin-html). For fun I benchmarked it on Kotlin/native to get an idea of how it performs vs JVM. Kotlin/native performed much worse than JVM. Here were the results:

### JVM
```
Benchmark Completed. Benchmark Total Millis: 17980, Average iteration was 359.52 millis
```

### Native w/ Writer using `CharSequence`
`./gradlew :benchmark:runReleaseExecutableMacosX64`
```
Benchmark Completed. Benchmark Total Millis: 192694, Average iteration was 3853.88 millis
```

Something that @jnorthrup noticed in https://github.com/ScottPierce/kotlin-html/pull/13 was that by swapping the [HtmlWriter](https://github.com/ScottPierce/kotlin-html/blob/master/kotlin-html/src/commonMain/kotlin/dev/scottpierce/html/write/HtmlWriter.kt#L6-L15) to use `String` instead of `CharSequence`, the performance is improved by ~65%. the `kotlin-html` library is basically just one giant `StringBuilder` under the hood in these tests - so for some reason Kotlin/native imposes a performance penalty when using `String` as a `CharSequence`.

### Native w/ Writer using `String`
```
Benchmark Completed. Benchmark Total Millis: 125298, Average iteration was 2505.96 millis
```

This ticket is specifically for the usage of `CharSequence` performing so much worse than `String` - even though at runtime it's still String's being used here. These should perform exactly the same - shouldn't they? Or is this something that only a JIT compiler can optimize?

**Comment by jnorthrup** [comment]
I'll pragmatically suggest that I noticed the problem domain of this benchmark is the classic domain of what javolution set out to make perofrmant, and since there is a c++ javolution library and kotlin emulates java without apparently an optimal baseline, javolution c++ might as well be nominated as the surrogate java string library in kotlinc https://github.com/javolution/javolution-cpp

**Comment by olonho** [comment]
Fixed with 824d8ae55e772c8e7370cadb6737dee4a87a3df8

**Comment by ScottPierce** [comment]
Just pulled and built master to try this.

### String:
```
Benchmark Completed. Benchmark Total Millis: 118087, Average iteration was 2361.74 millis
```

### CharSequence:
```
Benchmark Completed. Benchmark Total Millis: 142180, Average iteration was 2843.58 millis
```

The difference is much less drastic, but there is still a difference. Is it even reasonable in a AOT language like this that they be the same?

**Comment by jnorthrup** [comment]
it would would really help to know what cheap and expensive optimizations
are being chosen at compile time, this certainly should be nearly identical
with the type-check in place, and even the gross CharSequence interator
should approximate memcpy in a true closed-loop lto situation without the
type-check.
