### ISSUE TITLE
No Obj-c class generated for Kotlin class

### ISSUE THREAD

**Issue by 4ntoine** [JetBrains/kotlin-native#3208]
There is no Objective-C class generated for Kotlin class (using Cocoapods).
As a result i've used another class (with similar name) which results in **very** weird behaviour: class fields are mapped wrong.

I've prepared the screenshots, example project, detailed explanation on how to reproduce and the rootcause of the issue. Also it includes ios test to see what's wrong. Read README file in the archive. 

https://github.com/4ntoine/NotesClientApp/issues/4

PS. It can be related that multiplatform modules are distributed via Maven repo (not just `api project(:someProject)`)

**Comment by 4ntoine** [comment]
https://youtrack.jetbrains.com/issue/KT-32883

**Comment by SvyatoslavScherbina** [comment]
Your Swift code is wrong.

In `ListNotesImpl.swift`:

```swift
import Foundation
import app_mvp

class ListNotesImpl : App_apiListNotes {

    let notes = [ DomainNote(id: "id1", title: "title1", body: "body1") ]

    func execute() throws -> App_apiListNotesResponse {
        // I guess my bug is actually here: passing a list of [DomainNote] instead of [ListNotesResponse.Note]
        // but the latter is just not generated in Obj-C! (K/N bug)

        // The weird thing is that it does not crash (though it's wrong class), but results in weird fields mapping.
        return App_apiListNotesResponse.init(notes: notes)
    }

}
```

`ListNotes.Response` constructor expects collection of `ListNotes.Note`, while you pass list of `name.antonsmirnov.notes.domain.Note`.
The compiler doesn't help here because `Collection<*>` type is mapped to Swift `AnyObject` (due to lack of more suitable type), so type mismatch affects the runtime behaviour instead.

**Comment by 4ntoine** [comment]
Hi, Svyatoslav.

This is exactly what is written in my comment. My point is that there is no `ListNotes.Note` obj-c class generated to be used. I've realized only when i got wrong mapping.

So the rootcause is (my understanding and please correct me), that according obj-c class is not generated in header.

PS. You were really fast to find the reason, kudos.

**Comment by 4ntoine** [comment]
Do you want me to attach generated `*.h` file or you can do it (relatively fast)?

**Comment by 4ntoine** [comment]
And yes, i did realized that i was just lucky to make it running as it was another class that was used in runtime by fact.

**Comment by 4ntoine** [comment]
BTW. it would be good to be able to configure Kotlin package.classname to Obj-c classnames as it seems there is no such possibility:
https://stackoverflow.com/questions/57101327/how-to-adjust-swift-classnames-for-kotlin-multiplatform-project-with-cocoapods

**Comment by SvyatoslavScherbina** [comment]
> according obj-c class is not generated in header

This is not a bug. Unless you export the dependency explicitly, classes from it that aren't referenced from the header don't get included into the framework.

So to make this class appear you can either reference it from other API of the module or export the entire dependency (see "Exporting dependencies in frameworks" [here](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries)).

> (and wrong mapping is just consequence that occasionally worked somehow).

There is no wrong mapping.

**Comment by 4ntoine** [comment]
Thanks for the explanation!

This is very strange and misleading default behaviour IMO.
If i have a class in `jar` i expect it to be available in according native code.

> So to make this class appear you can either reference it from other API
What is another API? It's referenced from the same `app-mvp` project. Why can't it be detected that it's actually used?

> see "Exporting dependencies in frameworks" here).
I've followed the link and did not get how to make it exposed explicitely. Can you explain?

**Comment by 4ntoine** [comment]
```
plugins {
    id 'idea'
    id 'kotlin-multiplatform'
    id('org.jetbrains.kotlin.native.cocoapods')
}

kotlin {
    targets {
        jvm()
        iosX64().binaries { // iOS simulator
            framework {
                export "name.antonsmirnov.notes:app-api:$rootProject.server_module_version"
            }
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib'
                api "name.antonsmirnov.notes:app-api-metadata:$rootProject.server_module_version"
            }
        }
        jvmMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
                api "name.antonsmirnov.notes:app-api-jvm:$rootProject.server_module_version"
            }
        }
        jvmTest {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-test'
                implementation 'org.jetbrains.kotlin:kotlin-test-junit'
                implementation "com.nhaarman.mockitokotlin2:mockito-kotlin:$mockito_kotlin_version"
            }
        }
        iosX64Main {
            dependencies {
                api "name.antonsmirnov.notes:app-api-iosx64:$rootProject.server_module_version"
            }
        }
    }

    // All exceptions in Kotlin are not checked, but in Swift they are checked.
    // So we need @Throws annotation for iOS compatibility to generate swift signatures with `.. throws -> ..`
    // This requires @ExperimentalMultiplatform annotation in all methods with @Throws.
    // In order to prevent adding @ExperimentalMultiplatform every here and there we can use compiler option:
    targets.all {
        compilations.all {
            kotlinOptions {
                freeCompilerArgs += '-Xuse-experimental=kotlin.ExperimentalMultiplatform'
            }
        }
    }
}

version = "$rootProject.module_version"

kotlin {
    cocoapods {
        summary = "App MVP of NotesClientApp"
        homepage = "https://github.com/4ntoine/NotesClientApp"
    }
}
```

getting:
```
$./gradlew clean assemble podspec

> Configure project :NotesServerApp:app-api
Kotlin Multiplatform Projects are an experimental feature.
This build consumes Gradle module metadata but does not produce it when publishing Kotlin multiplatform libraries. 
To enable Gradle module metadata in publications, add 'enableFeaturePreview("GRADLE_METADATA")' to the settings.gradle file. 
See: https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#experimental-metadata-publishing-mode

> Configure project :app-mvp
Kotlin Multiplatform Projects are an experimental feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/asmirnov/Documents/dev/src/Notes/NotesClientApp/app-mvp/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':app-mvp'.
> Cannot create binary debugFramework: binary with such a name already exists
```

It seems it does not work with Cocoapods plugin

**Comment by 4ntoine** [comment]
Yup, it works with 2 changes:
1) remove cocoapods plugin
2) use module artifact name with platform suffix (exactly as in sourcesets) : `..-iosx64`

Any workaround for cocoapods?

**Comment by SvyatoslavScherbina** [comment]
> What is another API? It's referenced from the same app-mvp project. Why can't it be detected that it's actually used?

`Collection<ListNotes.Note>` type is [mapped](https://github.com/JetBrains/kotlin-native/issues/3208#issuecomment-514556652) to Swift `AnyObject`, so `ListNotes.Note` is not [referenced](https://github.com/JetBrains/kotlin-native/issues/3208#issuecomment-514574706) from the header.

> It seems it does not work with Cocoapods plugin

Because this part
```groovy
framework {
    export "name.antonsmirnov.notes:app-api:$rootProject.server_module_version"
}
```
defines a new framework instead of configuring existing (that is created by cocoapods plugin).

**Comment by 4ntoine** [comment]
> defines a new framework instead of configuring existing (that is created by cocoapods plugin).

How should it be written properly?

**Comment by 4ntoine** [comment]
Solved with the following:
```
...
kotlin {
    cocoapods {
        summary = "App MVP of NotesClientApp"
        homepage = "https://github.com/4ntoine/NotesClientApp"
    }

    targets.iosX64.binaries
        .findAll { it instanceof org.jetbrains.kotlin.gradle.plugin.mpp.Framework }
        .every {
            it.export "name.antonsmirnov.notes:app-api-iosx64:$rootProject.server_module_version"
            it.transitiveExport = true
        }
}
```

Improvements (for idiomatic groovy) appreciated.
