### ISSUE TITLE
Porting Kotlin Native to Haiku OS

### ISSUE THREAD

**Issue by volodymyr-gz** [JetBrains/kotlin-native#3214]
I would like to port Kotlin Native to [Haiku OS](https://www.haiku-os.org). There's an LLVM support (and Swift has been successfully [ported](https://www.haiku-os.org/tags/swift/)). But it's unclear where I should start from, and how does the process of introducing a new Kotlin Native target should look like. Some porting documentation (#1178) or hints would be helpful there.

**Comment by olonho** [comment]
Why not consult existing PRs adding new platforms, such as c3638e48dc78ae9fdd087f45e866c63ddbb4c874?

**Comment by SvyatoslavScherbina** [comment]
Got no response, closing.
Feel free to reopen if necessary.
