### ISSUE TITLE
Performance Test Framework

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3216]
What for is `performance` directory in source tree?

1) Is it usable for any user or for K/N team only?
`gradlew :performance:konanRun` just hangs on Windows.

2) I think it should contain test where LLVM optimizer can do it best, for example
https://github.com/msink/kotlin-pi (converted from http://bellard.org/pi/pi.c)
Here perfopmance should be equal in C, JVM and Native.

**Comment by LepilkinaElena** [comment]
`performance` is directory with our benchmarks and runner for them.

> Is it usable for any user or for K/N team only?

Benchmarks can be used by anyone, but of course they are mostly are needed by K/N compiler developers to check impact of their changes on performance.

> gradlew :performance:konanRun just hangs on Windows.
Are you sure that it hangs? All benchmarks run for several hours. You can run only one benchmark to check. We run them on CI system on Windows and they are working. If you really have problems6 please, provide your detailed system information.

>  think it should contain test where LLVM optimizer can do it best, for example
https://github.com/msink/kotlin-pi (converted from http://bellard.org/pi/pi.c)
Here perfopmance should be equal in C, JVM and Native.

Thank you. We are open for new benchmarks. If you are ready to share your benchmark you can add it by yourself or if you don't want to spend your time on integration it to our system, please, let us know, and we'll add it.

**Comment by msink** [comment]
How long should run `:performance:cinterop:konanRun` ?
I waited half-hour before terminate it.
Well, can wait more, but doubt it will ever complete.

**Comment by LepilkinaElena** [comment]
Yes, it's strange6 on our Windows machine it works faster.

Please, use option `-filter`, to run only one benchmark, but not subset https://github.com/JetBrains/kotlin-native/blob/master/HACKING.md#performance-measurement

**Comment by msink** [comment]
Weird, but yes:
- `gradlew :performance:cinterop:konanRun` - hangs
- `gradlew :performance:cinterop:konanRun --filter=struct,macros,types` - terminates in 40 seconds.

**Comment by LepilkinaElena** [comment]
I think that your machine just works slower.
There are gradle properties 
`nativeWarmup = 20
attempts = 60`

You can set them manually to small value to check.
Also I'll add verbose mode for benchmarks. I'll publish here PR.

**Comment by msink** [comment]
Well, set both to 1 - now `gradlew :performance:cinterop:konanRun` completes in 3m 28s.

**Comment by msink** [comment]
About adding new test - I can try do it myself, but main point is to compare C/JVM/Native, and as I can see - `jvmRun` is unsupported for now?

**Comment by LepilkinaElena** [comment]
Ok, I had a look on your benchmark. As I understood right in native for package `pi` you use generated by cinterop, in jvm - just code from `pi.kt`.

`jvmRun` is supported in benchmarks subset `ring`, in `cinterop` subset we have code with a lot of extensions for K/N and have no similar implementation for JVM.

**Comment by msink** [comment]
Yes, here C source code compiled to `.so`, and used twice - in C test directly, and in K/N test - impoted by `cinterop` tool.

Also here was proposed somehow add Swift comparison: https://github.com/msink/kotlin-pi/issues/4

**Comment by LepilkinaElena** [comment]
We plan adding benchmarks to compare Kotlin and Swift. But now we don't have such benchmarks.
I think that your benchmark can be a start of new subset or now it can be in `ring` and later we can replace it if it's needed.

**Comment by LepilkinaElena** [comment]
Added flag `--verbose` to show in log what benchmark is running now https://github.com/JetBrains/kotlin-native/pull/3218

**Comment by msink** [comment]
Well, my first attempt ta add new test: #3225 

For now it compiles for Native, but fails on `runNative`.
`runJvm` fails too.

What is wrong here?

**Comment by LepilkinaElena** [comment]
All discussion about new benchmark in review.
