### ISSUE TITLE
can not set module name to empty String

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3228]
kotlin 1.3.40 , when we specify module name to empty String:
extraOpts '-module-name' , ""
compiler error shows.

However , kotlin 1.3.31 permit empty module name.

We want empty module name permited , thx.

**Comment by artdfel** [comment]
This way to produce frameworks without prefixes in class names was not supposed to use. So, I would say that, if you rely on this type of naming, you got to leave this practice. Maybe this feature must be discussed, but as far as it was not among our goals, it won't be available in the nearest future.
