### ISSUE TITLE
cinterop with xctest.framework for iOS link error

### ISSUE THREAD

**Issue by levicc** [JetBrains/kotlin-native#3232]
```  

.def  
language=Objective-C  
package = platform.XCTest  
headers = XCTest/XCTest.h  
linkerOpts=-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework  
compilerOpts=-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/  
headerFilter = XCTest/**  

```

```  

iosX64("ios") {
        binaries {
            framework("XXX")
        }
        compilations.main {
            outputKinds("framework")
            cinterops {
                xctest {
                    defFile project.file("src/iosMain/xctest.def")
                    packageName 'com.cinterop.xctest'
                }
            }
        }
    }

```

```  

package sample

import com.cinterop.xctest.*

fun elementWithTestId(testId: String, sElement: XCUIElement):XCUIElement {
    val query = sElement.descendantsMatchingType(XCUIElementTypeAny)
    return query.elementMatchingType(XCUIElementTypeAny, testId)
}  

```

I want to generate a framework to provide a function
app-cinterop-xctest.klib generate successful，But link error:  

```  

app:linkXCTestDebugFrameworkIos
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIDevice", referenced from:
      objc-class-ref in combined.o
ld: symbol(s) not found for architecture x86_64
e  

```  
  
So I add `linkerOpts=-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework` in .def，but no use.  

How can it work?

**Comment by idstein** [comment]
We've experienced the same issue. Add the following to add the dependency to your produced framework.
```
binaries {
            framework("XXX") {
                    linkerOpts += ['-framework', 'UIKit']
                }
        } 
```

Or modify your interop def file and add a dependsOn relation for UIKit

```
language=Objective-C  
package = platform.XCTest
depends =UIKit
modules = XCTest
compilerOpts = -framework XCTest
linkerOpts = -framework XCTest
```

**Comment by levicc** [comment]
> We've experienced the same issue. Add the following to add the dependency to your produced framework.
> 
> ```
> binaries {
>             framework("XXX") {
>                     linkerOpts += ['-framework', 'UIKit']
>                 }
>         } 
> ```
> 
> Or modify your interop def file and add a dependsOn relation for UIKit
> 
> ```
> language=Objective-C  
> package = platform.XCTest
> depends =UIKit
> modules = XCTest
> compilerOpts = -framework XCTest
> linkerOpts = -framework XCTest
> ```

thanks, it work
