### ISSUE TITLE
Generic extension functions do not use class's type parameter with -Xobjc-generics

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#3240]
If I have the following:

```kotlin
class Test<T> {
}
fun <T> Test<T>.foo(arg: T) {…}
```
The argument to foo shows up as `id`/`Any` in Obj-C/Swift. The workaround is to do:
```kotlin
class Test<T> {
    fun foo(arg: T) {…}
}
```

This isn't ideal because it means you cannot add platform-specific generic extension functions.

**Comment by SvyatoslavScherbina** [comment]
See more details here: https://github.com/JetBrains/kotlin-native/pull/2850#issuecomment-486511913

**Comment by benasher44** [comment]
Makes sense. Had a brief chat with @kpgalligan. Seems like this could be possible when the extension type-signature exactly matches. We could warn when the type-signature does not match to help.

**Comment by idstein** [comment]
We could really use those generics extension functions.

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48071, closing.
