### ISSUE TITLE
How can I generate an Instance by class name in iosMain?

### ISSUE THREAD

**Issue by kry4ever** [JetBrains/kotlin-native#3247]
in the commonMain
`expect fun createInstance(className: String): Any?`

in the androidMain
`actual fun createInstance(className: String): Any? {
    return Class.forName(className).newInstance()
}`

in the iosMain
`actual fun createInstance(className: String): Any? {
    val ins = NSClassFromString(className)
    // then, what should I do?
}`

**Comment by SvyatoslavScherbina** [comment]
> `actual fun createInstance(className: String): Any? { val ins = NSClassFromString(className) // then, what should I do? }`

You can't do this in Kotlin currently. What's your case, could you provide more details?

**Comment by kry4ever** [comment]
> > `actual fun createInstance(className: String): Any? { val ins = NSClassFromString(className) // then, what should I do? }`
> 
> You can't do this in Kotlin currently. What's your case, could you provide more details?

Actually, I want to use flutter and kotlin-native together, I use flutter to show UI, and kotlin-native to do the logic(use command pattern).  So I have a lot of action objects in kotlin-native,  then I send some action(the full package and class name) from Flutter,  the kotlin-native side receive it and generate the instance of action. I can use reflect in android side,  how about ios?

**Comment by SvyatoslavScherbina** [comment]
There is no `Class.forName` in Kotlin on iOS. Consider maintaining a mapping from class to factory instead.
