### ISSUE TITLE
How to get a double pointer with a pointer?

### ISSUE THREAD

**Issue by ZhouGongZaiShi** [JetBrains/kotlin-native#3249]
```
Kotlin native:
val `in`: CPointer<uint8_tVar> = (pointedHandle.input_start.toLong() + pointedHandle.input_offset.convert<Long>()).toCPointer<uint8_tVar>()!!

C:
BrotliDecoderResult BrotliDecoderDecompressStream(
  BrotliDecoderState* state, size_t* available_in, const uint8_t** next_in,
  size_t* available_out, uint8_t** next_out, size_t* total_out);
```
I have a `CPointer<uint8_tVar>` (corresponding to `uint8_t *` in C) that I need to call the `BrotliDecoderDecompressStream()`, but one of its argument types is `uint_8**`.   
How do I get `CPointer<CPointerVar<uint8_tVar>>` via `CPointer<uint8_tVar>`?

**Comment by artdfel** [comment]
Hello! Try something like this:
```
memScoped {
        val nextIn = allocPointerTo<uint8_tVar>()
        nextIn.value = (pointedHandle.input_start.toLong() + pointedHandle.input_offset.convert<Long>()).toCPointer<uint8_tVar>()!!
        val pointerNextIn = nextIn.ptr // has type Cpointer<CPointerVar<uint8_tVar>>
    }
```

**Comment by ZhouGongZaiShi** [comment]
> Hello! Try something like this:
> 
> ```
> memScoped {
>         val nextIn = allocPointerTo<uint8_tVar>()
>         nextIn.value = (pointedHandle.input_start.toLong() + pointedHandle.input_offset.convert<Long>()).toCPointer<uint8_tVar>()!!
>         val pointerNextIn = nextIn.ptr // has type Cpointer<CPointerVar<uint8_tVar>>
>     }
> ```

Thanks! It works very well.
