### ISSUE TITLE
Speedup usage of printf function family

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#3256]
Hello! When using the `printf` family of C functions, the `format` argument takes a Kotlin `String`, which then has to be encoded into UTF-8 bytes for each call. I have a place where I want to call `snprintf` in a tight loop. To speed things up (due to slowdown from repeated UTF-8 encoding of the static format string), ideally (one of the following):

1. I'd be able to store the format as a constant `ByteArray` myself, so that the decode only happens once.
2. The compiler would optimize this for me (nice-to-have, but unclear if this use case is common).

Right now, I'm getting around all of this with a cinterop (just a C function that itself calls `snprintf`) where the format string is defined in C. I've been using this cinterop for awhile because the `snprintf` calls used to be slow to a varargs-related performance issue. It's now much better as of a recent Kotlin/Native release (pretty sure the one where the libffi dep was dropped), so now I'd like to work toward removing this cinterop. Is there some other optimization/workaround I could try for this case? This encode issue adds about a 20% performance penalty, which is why I'm going to stick with the cinterop until we can figure something out.

Another thought: maybe K/N could generate versions of these functions that take a `ByteArray` instead of a `String`?

Thanks!

**Comment by SvyatoslavScherbina** [comment]
Hello!

> This encode issue adds about a 20% performance penalty

What makes you think so?

> Is there some other optimization/workaround I could try for this case?

I'm not sure there is any optimization possible currently not involving custom `cinterop` configuration. So:

> stick with the cinterop

Is there a particular reason to avoid this?

**Comment by benasher44** [comment]
> What makes you think so?

I profiled it using Xcode's Instruments app over 100k runs.

> Is there a particular reason to avoid this?

I only want to avoid it to improve compile time. cinterop adds ~15s to build time for only these few functions.

**Comment by SvyatoslavScherbina** [comment]
> cinterop adds ~15s to build time for only these few functions.

This should happen only with clean build. Is it so?

**Comment by benasher44** [comment]
Ah yes it looks like it's only for clean builds. Thanks for calling that out! Closing.
