### ISSUE TITLE
Uber sharedLib for linux

### ISSUE THREAD

**Issue by IgorKey** [JetBrains/kotlin-native#3257]
For now, as I know, the KN executable depends on libc (glibc) library. And it dynamically linked.
So, these things in my case bring a problem. I created a Shared lib which attach to some process (java process) at runtime. It works good in some fresh ubuntu-based OS. But yesterday I tried to load this one on the env with CentOs 6 and got a strange issue.

> Could not find a library. Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by blabla_path)

So, as I understand, this env has lessversion of  GLIBC(e.g. GLIBC_2.12) or doesn't have GLIBC at all.

**Problem**: my lib distributes as "plugin" for some process, so I can't modify or install  GLIBC on the host machine where my plugin will be used.

@olonho, Are there any ways to solve these issues? e.g. statically linked GLIBC to my .so file?
I tried it
![image](https://user-images.githubusercontent.com/32630789/63092542-c1c71880-bf6a-11e9-85a1-3ce14a8d7996.png)
but got the error **bin/ld.lld: error: unable to find library -libgcc**

**Comment by SvyatoslavScherbina** [comment]
Consider producing static library from Kotlin/Native and then making a dynamic library from it manually with custom linkage rules, using either system or Kotlin/Native-provided toolchain.

**Comment by IgorKey** [comment]
Thanks!

**Comment by zaxebo1** [comment]
@SvyatoslaScherbina : can you kindly elaborate with sample exact commands?

> Consider producing static library from Kotlin/Native and then making a dynamic library from it manually with custom linkage rules, using either system or Kotlin/Native-provided toolchain.

**Comment by SvyatoslavScherbina** [comment]
Something like this may help:
```
gcc -Wl,--whole-archive libstatic.a -Wl,--no-whole-archive -shared -o libdynamic.so
```
