### ISSUE TITLE
compile failed when producing .kexe from windows

### ISSUE THREAD

**Issue by IgorKey** [JetBrains/kotlin-native#3260]
I tried to run linuxTest tasks from windows.
the task produces the below error:
```
> Task :linkDebugTestLinux
C:\Users\Igor_Kuzminykh\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1\bin\ld.lld: error: deflate.o: invalid data encoding
e: C:\Users\Igor_Kuzminykh\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1/bin/ld.lld invocation reported errors

> Task :linkDebugTestLinux FAILED
```
What does it mean? How I can get more details about this error?

P.S. windowsTest works well

**Comment by artdfel** [comment]
Can you provide additional info on your case? Are you getting the same result with linuxExecutable task? Also, you can try to run Gradle with `--info` and `--stacktrace` arguments to produce more detailed output.

**Comment by IgorKey** [comment]
yes, all executable tasks(linuxExecutable) produce the same error.
No, there aren't any useful info with --info or --stacktrace
![image](https://user-images.githubusercontent.com/32630789/63272238-61a2e000-c2a4-11e9-8427-d7b256282b8d.png)
I thinking about llvm logs or else..

**Comment by artdfel** [comment]
Can you try to run `konanc` manually, with arguments listed it this report? It will let you use additional arguments like `-verbose`.

**Comment by IgorKey** [comment]
Oh, sorry, for this poor details.
Yeah. I tried use cli for this. but problem and info the same..
![image](https://user-images.githubusercontent.com/32630789/63279229-51ddc880-c2b1-11e9-8b58-625b3c483ce4.png)
-verbose didn't get any useful info...

**Comment by IgorKey** [comment]
UPD:
This reproduce only using klib, which was produced by me.
It's build from korio project. and store in mymavenrepo - https://mymavenrepo.com/repo/OgSYgOfB6MOBdJw3tWuX/com/soywiz/korio-native/

only this dependency throw this error. But in linux target it works...
I created the [test project](https://github.com/IgorKey/kn-gist-deflate-error.git) for reproducing...
gradle linkLinux     on windows Host

**Comment by artdfel** [comment]
So, it looks like you produced the library the wrong way - somehow you have statically linked the wrong version of `deflate.o`, just as the error tells. I recommend you to contact @soywiz directly as far as this problem has no cause in Kotlin/Native. Also, please share the steps you performed to build the library, it might help as far as the problem lies in it.

**Comment by IgorKey** [comment]
Thanks for help!
