### ISSUE TITLE
AES / SHA / HMACSHA ... Crypto Method in commonMain not find

### ISSUE THREAD

**Issue by VincentChen1212** [JetBrains/kotlin-native#3261]
I need use k/m project to build a library for android/ios/java server, I want to write AES256 / SHA512 / HMACSHA256 in commonMain, but I can't find suitable method.

Like can't use cipher in commonMain, no sample for ios to write cccrypt.AES...etc.

 thanks

**Comment by artdfel** [comment]
If I understood you correctly, I'd recommend to search for already existing libraries. For example, you can have a look at [this one](https://korlibs.soywiz.com/krypto/).
