### ISSUE TITLE
link Release Framework Fail

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3268]
<img width="931" alt="Lark20190821-122107" src="https://user-images.githubusercontent.com/11617214/63402514-49e76b00-c40e-11e9-898a-29f9c1324fd4.png">
this is error info.

**Comment by acc110789** [comment]
How can we quick fix this?

**Comment by artdfel** [comment]
Please check your Java heap size, just as the error reports. Try to extend it manually. If the problem remains, please provide additional info on your case.

**Comment by acc110789** [comment]
> Please check your Java heap size, just as the error reports. Try to extend it manually. If the problem remains, please provide additional info on your case.

![Lark20190821-223242](https://user-images.githubusercontent.com/11617214/63441275-b80a4d00-c463-11e9-9116-446f49361bbd.png)

I found that the jvmargs for  konanc is always "-Xmx3G" .
I do not know how to change to like "-Xmx10G".
How can i configure this in my  mpp project.

**Comment by acc110789** [comment]
i get it.
write this in gradle.properties
org.jetbrains.kotlin.native.jvmArgs=-Xmx10G
