### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed

### ISSUE THREAD

**Issue by VincentChen1212** [JetBrains/kotlin-native#3269]
My K/N Project Like:

```
src
----androidNativeMain
----c_interop
--------ctypto
------------sha
----------------sha512.c
----------------sha512.h
----commonMain
----iOSMain
----nativeInterop
--------cinterop
------------interop.def
```

interop.def
```
headers = ....sha512.h (Use Absolute Path)
package = XX.XX.XX
compilerOpts = -Isrc/c
```

build.gradle
```
plugins {
    id 'org.jetbrains.kotlin.multiplatform' version '1.3.41'
}

repositories {
    mavenCentral()
}
group 'com.example'
version '0.0.1'

apply plugin: 'maven-publish'

kotlin {
    androidNativeArm64("androidNative") {
        compilations.main.cinterops {
            interop
        }

        binaries {
            sharedLib {
                baseName = "AndroidNative"
            }
        }
    }

    iosArm64("iOS") {
        binaries {
            framework {
                baseName = "iOS"
            }
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation kotlin('stdlib-common')
            }
        }

        androidNativeMain {
        }

        iOSMain {
        }
    }
}
```

In My Android Main
I Create a Method
```
fun DoSHA512(){
//Call SHA512_Simple which is from "sha512.c"
}
```

Build OK and Gen a libAndroidNative.so

But When My Android Call "DoSHA512()"
Exception
"java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "SHA512_Simple" referenced by "/data/app/...../libAndroidNative.so"..."
(Other Method is OK if it doesn't call c method)

How to fix it????

And
in ".def"
How to write Relatively Path for "headers"

Thanks

**Comment by artdfel** [comment]
The problem is that the `.klib` file you got by the `cinterop` tool is just a set of bindings to the original C file. In your case, the final binary is trying to find sha512.c file, as the interop'ted header points there. To make everything work, you got to distribute it with your lib somehow, which looks like not so good idea. What's the reason behind using a separate .c file instead of implementing its content by Kotlin/Native itself?

**Comment by cydhhp** [comment]
@artdfel Thanks your answer.
I actually use "PURE Kotlin" to coding AES256/SHA512/HMACSHA256 in commonMain, but commonMain can't use java/javax package, so I can't coding them (I don't understand about generating algorithm) , and find no sample.
Another reason, for android, it needs .so library , and androidNativeArm64Main also can't use java/javax package, so to use .c file

I Need your suggestion, Thanks very much.

**Comment by artdfel** [comment]
You can try to put the content of your `sha512.c` file to the `.def` custom declarations section, as described [here](https://kotlinlang.org/docs/reference/native/c_interop.html#adding-custom-declarations).

**Comment by VincentChen1212** [comment]
@artdfel Thanks your answer.
It sloves my questions, You are my Hero.
Thanks very very very much
