### ISSUE TITLE
Stored value type does not match pointer operand type!

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#3271]
Kotlin 1.3.41
Full log: https://travis-ci.org/korlibs/korim/jobs/575036180#L855
Reproduced in this branch: https://github.com/korlibs/korim/tree/bitcode.dump.bug.kotlin.1.3.41

**Comment by artdfel** [comment]
Thank you for the report! We successfully reproduced this issue and now started an investigation for its causes.

**Comment by SvyatoslavScherbina** [comment]
Likely fixed in Kotlin 1.3.50 with https://github.com/JetBrains/kotlin/commit/ceaa64dfb18f754dd634ff59729540ba198a75f2

@soywiz could you please check building your code with 1.3.50?

**Comment by soywiz** [comment]
I'm going to try to compile all my libraries against `1.3.50-release-112` from https://dl.bintray.com/kotlin/kotlin-dev
Is there a version of kotlinx.coroutines uploaded somewhere pre-compiled against 1.3.50?

**Comment by SvyatoslavScherbina** [comment]
Try kotlinx.coroutines version `1.3.0-RC-1.3.50-eap-5` with atomicfu `0.12.9-1.3.50-eap-5`.

**Comment by soywiz** [comment]
Doesn't seems to reproduce in Korim using `1.3.50-release-112`.
I'm going to compile the rest of the libraries against this to see if I can find additional problems.

**Comment by soywiz** [comment]
FYI, I was able to compile all my libraries without issues.

Though I'm getting a segmentation fault at runtime when processing events on macOS. I have not changed anything on the code, so it is a bit strange, but I will investigate a bit more.

**Comment by SvyatoslavScherbina** [comment]
> I was able to compile all my libraries without issues.

That's great, thanks for checking!

> Though I'm getting a segmentation fault at runtime when processing events on macOS. I have not changed anything on the code, so it is a bit strange, but I will investigate a bit more.

This may be caused by supporting variadic Objective-C methods in 1.3.40 (e.g. if you get other method called with the same code).
