### ISSUE TITLE
Support Android x86 target

### ISSUE THREAD

**Issue by HarukaMa** [JetBrains/kotlin-native#3272]
This was mentioned in #939 but unfortunately did not get enough attraction.

Quoting @atsushieno: 

> Well, Android x86 target is real on emulators especially with HAXM enabled. It is something significant.

Without this target, we are forced to use real devices or emulators based on arm (not being updated anymore: latest one was still Android 7) which is 10x slower than x86-based emulators according to Google. That could be inconvenient during development.

Also, iOS targets do have `ios_x64` which is specifically for emulators (I think), so I really couldn't understand why proper Android emulators are not supported.

**Comment by Bluexin** [comment]
x86 specifically or x86_64 ? In which case, see https://github.com/JetBrains/kotlin/pull/2538

**Comment by HarukaMa** [comment]
Maybe `android_x86` is also needed, since only x86 is in the "recommended" system images:

![image](https://user-images.githubusercontent.com/861659/63588663-07768780-c5e2-11e9-9ede-df795b44138f.png)

But there are x86_64 images too, so there could be some people using them.

**Comment by gildor** [comment]
x86 is very important for emulator, and especially for cases when you use it on CI

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/3306

**Comment by gildor** [comment]
@olonho This PR covers only Android x86_64, are there any plans to support Android x86?

**Comment by olonho** [comment]
It's not hard to do, with toolchain architecture changed in this PR, but someone got to convince me that it is indeed needed.

**Comment by gildor** [comment]
@olonho 
1. The main reason for me is x86 emulator, which is the main target ABI for Android emulators. It uses less memory than x86_64 emulator and recommended to use by Google.
Also, some CIs are x86 OS, so you just cannot run x86_64 emulator using native architecture on them.
2. Some devices (smartwatches) based on Intel Z3520 chipset supports only x86 architecture even ARM emulation is not supported 
3. Many other devices (mostly based on Intel C3230, Intel Z3735, Intel Z8500) are x86 only.  They support armeabi-v7a emulation mode, but it's significantly slower than native x86. Google Play device catalog contains 217 certificated models of devices that are x86 with armeabi-v7a emulation support

**Comment by HarukaMa** [comment]
For image references please see the above reply (11 days ago). That's from AVD manager.

**Comment by olonho** [comment]
OK, see https://github.com/JetBrains/kotlin-native/pull/3314
