### ISSUE TITLE
Minimal Xcode version

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3273]
K/N 1.3.41 worked in `xcode8` image on Travis CI, but 1.3.50 fails with message
```
error: unknown argument: '-fembed-bitcode=off'
e: Compilation failed: The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ command returned non-zero exit code: 1.
```
So what Xcode version should be used now for library publishing?

**Comment by artdfel** [comment]
It was not an intentional move to step away from Xcode 8. Please try Travis CI's default one(9.4.1 as I found in the [documentation](https://docs.travis-ci.com/user/reference/osx/#macos-version)), or the most recent stable release(10.3), if it is available.

**Comment by msink** [comment]
So I moved to `xcode9.2` mentioned as prerequisite in README.md, it works.
