### ISSUE TITLE
About CValuesRef / CValues ... 

### ISSUE THREAD

**Issue by VincentChen1212** [JetBrains/kotlin-native#3276]
Hi All

I am a freashman for K/N, and many things are not understand!
Now I use Cinterop to gen a Method
Like below：
```
public fun AES_CBC_encrypt_buffer(
    output: kotlinx.cinterop.CValuesRef<platform.posix.uint8_tVar /* = kotlinx.cinterop.UByteVarOf<platform.posix.uint8_t /* = kotlin.UByte */> */>?, 
    input: kotlinx.cinterop.CValuesRef<platform.posix.uint8_tVar /* = kotlinx.cinterop.UByteVarOf<platform.posix.uint8_t /* = kotlin.UByte */> */>?, 
    length: platform.posix.uint32_t /* = kotlin.UInt */, 
    key: kotlinx.cinterop.CValuesRef<platform.posix.uint8_tVar /* = kotlinx.cinterop.UByteVarOf<platform.posix.uint8_t /* = kotlin.UByte */> */>?, 
    iv: kotlinx.cinterop.CValuesRef<platform.posix.uint8_tVar /* = kotlinx.cinterop.UByteVarOf<platform.posix.uint8_t /* = kotlin.UByte */> */>?
    ): kotlin.Unit { /* compiled code */ }
```

Then I Call it,
BUT
I don't Know how to use
The five Pararms：
```
val output = allocArray<uint8_tVar>(1024)
val input = "MyInputString".encodeToByteArray()
val length= "MyInputString".size
val key= "MyKey"
val iv= "MyIV"
```

Can anyone Help me.
or good resource to ref.
Thanks a lot

**Comment by artdfel** [comment]
Hello! Maybe you can use something like this
```
memScoped {
        val output = allocArray<uint8_tVar>(1024)
        val string = "MyInputString"
        val input = string.encodeToByteArray().asUByteArray().toCValues()
        val length= string.length.toUInt()
        val key= "MyKey".encodeToByteArray().asUByteArray().toCValues()
        val iv= "MyIV".encodeToByteArray().asUByteArray().toCValues()
        AES_CBC_encrypt_buffer(output, input, length, key, iv)
}
```
And I strongly recommend using Kotlin Slack channel for such questions. Also, you can read our C interoperability explanation [here](https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md).

**Comment by cydhhp** [comment]
@artdfel , Thanks for your answer, it is very useful for me!

Now, how do i let my output answer CArrayPointer<uint8_tVar> to String, I cant't use pure kotlin to convert

Thanks a lot

**Comment by artdfel** [comment]
The cause of this is the fact that your `outputData` can contain `'\0'` symbols, as the algorithm doesn't care about correctness of the result as a string. So, when you try to convert it to the string, it takes only bytes that lie before the first `'\0'` entry. Please avoid using any string types, Java nor Kotlin ones, to store the ciphers.
