### ISSUE TITLE
rethrow exception recursion

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3282]
![Lark20190826-175725](https://user-images.githubusercontent.com/11617214/63682946-ad690280-c82b-11e9-80c7-3a333f7a6c72.png)

when there is a crash in object-c world, this happen.

**Comment by acc110789** [comment]
kotlin 1.3.41

**Comment by artdfel** [comment]
Hello! Thank you for the report, please provide an example project with steps to reproduce this behavior.

**Comment by acc110789** [comment]
our mistake! , thx
