### ISSUE TITLE
[MPP, iOS, 1.3.50] EXC_BAD_ACCESS occurs when printing a negative Byte

### ISSUE THREAD

**Issue by k-yamada** [JetBrains/kotlin-native#3290]
Kotlin version: 1.3.50
Device: iPhone 12.3.1 (Real device)

```
// Reproduce.kt:

class Reproduce {
    fun test() {
        val plusByte = 1.toByte()
        val zeroByte = 0.toByte()
        val minusByte = (-1).toByte()
        println(plusByte) // OK
        println(zeroByte) // OK
        println(minusByte) // ERROR: EXC_BAD_ACCESS
    }
}
```

```
// ViewController.swift:

import UIKit
import SharedCode

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        let reproduce = Reproduce()
        reproduce.test()
    }
}
```

<img width="851" alt="EXC_BAD_ACCESS" src="https://user-images.githubusercontent.com/192619/63878056-c2988980-ca03-11e9-94f4-84183b050294.png">

Runnable example: https://github.com/k-yamada/mpp-ios-android/pull/1

**Comment by SvyatoslavScherbina** [comment]
Thanks, confirmed.

**Comment by SvyatoslavScherbina** [comment]
The crash is caused by LLVM bug. It is fixed in LLVM 8, but unfortunately latest Xcode version doesn't seem to ship the fix.

To workaround the issue, please locate `~/.konan/kotlin-native-macos-1.3.50/konan/konan.properties` file and replace the line
```properties
clangDebugFlags.ios_arm64 = -O0
```

with

```properties
clangDebugFlags.ios_arm64 = -O0 -mllvm -fast-isel=false
```

**Comment by k-yamada** [comment]
Thank you for telling me how to avoid this issue.
