### ISSUE TITLE
wasm32 build fails after upgrade to 1.3.50

### ISSUE THREAD

**Issue by molikuner** [JetBrains/kotlin-native#3298]
**Description**
I'm currently trying to setup a wasm project. I get a JVM crash at `linkDebugExecutableWasm32`. After trying the same code with Kotlin `1.3.41` instead of the newest version `1.3.50` the build succeeds.

**Setup:**
build.gradle.kts:
```Kotlin
plugins {
    kotlin("multiplatform") version "1.3.50"
}

repositories {
    mavenCentral()
}

kotlin {
    wasm32 {
        binaries {
            executable {
                entryPoint = "main"
            }
        }
    }
}
```
src/wasm32Main/kotlin/Hello.kt:
```Kotlin
fun hello(): String = "Hello, Kotlin/Native!"

fun main() {
    println(hello())
}
```
**Logs:**
gradle:
```
> Task :linkDebugExecutableWasm32
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007fed39323c0f, pid=9944, tid=0x00007fed39505700
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-8u222-b10-1~deb9u1-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x1bc0f]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/molikuner/CLionProjects/wasmTest/hs_err_pid9944.log
#
# If you would like to submit a bug report, please visit:
#   https://youtrack.jetbrains.com
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

> Task :linkDebugExecutableWasm32 FAILED
```
`hs_err_pid9944.log`:
https://kotlinlang.slack.com/files/ULYEHAJLC/FMWTNLR3J/hs_err_pid9944.log

**Environment**
Linux (debian stretch x64)

**Comment by artdfel** [comment]
Thank you for the report!
Please provide additional information about your `libc6` package version

**Comment by molikuner** [comment]
```
$ sudo apt policy libc6    
libc6:
  Installed: 2.24-11+deb9u4
  Candidate: 2.24-11+deb9u4
```

**Comment by artdfel** [comment]
Well, the same as mine. Maybe you can share the `ld-linux-x86-64 .so.2` file itself?

**Comment by molikuner** [comment]
I uploaded a ZIP, because the original file in `/lib/x86_64-linux-gnu` is a link to an other file in that directory. Also, if needed, I can upload to an other service, but I don't know any other :wink:.
It contains the link and the file where it's linked to.

[onetime link to zip](https://send.firefox.com/download/822a75b369b34810/#OVRbLfIc-Mkm1Zmh9rPFyQ)

**Comment by artdfel** [comment]
What CPU do you have on your workstation?

**Comment by molikuner** [comment]
Well, I wouldn't call it 'workstation' but anyways:
```
$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 15
Model name:            Intel(R) Core(TM)2 CPU         T7400  @ 2.16GHz
Stepping:              6
CPU MHz:               2167.000
CPU max MHz:           2167.0000
CPU min MHz:           1000.0000
BogoMIPS:              4322.82
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm kaiser tpr_shadow dtherm
```

**Comment by olonho** [comment]
Does it only happen for WASM targets, or other targets (such as Linux_ affected as well?

**Comment by molikuner** [comment]
Actually I needed to test that, as I didn't build any of my other projects recently. I tried `linuxX64` which also crashes. Seems as this problem isn't limited to WASM.

**Comment by olonho** [comment]
Intersting, can you boot some other distro on the same machine?

**Comment by molikuner** [comment]
That would take some time, as I would need to setup those, but that's time I'm willing to invest in the problem. Any suggestions on which distros?

**Comment by olonho** [comment]
Something like Ubuntu 18.04 is fine.

**Comment by olonho** [comment]
Also you could try Docker on same machine and run compiler there (my current idea is that you have something special around dynamic library loading).

**Comment by molikuner** [comment]
I tested the build in following docker containers: `Ubuntu (18.04)` and `Debian (Stretch)`
Both were working, which means, that my host system has a strange/broken environment. For now I'll build my stuff in a docker container and wait until this is "magically" fixed by an update or by me installing the newest `debian` after a complete wipe.
But anyways, if you'd like to investigate the problem further, I'll be happy to help.
