### ISSUE TITLE
linkTestDebugExecutableIos FAILED : Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by jittya** [JetBrains/kotlin-native#3299]
> Task :app:iosMainKlibrary
> Task :app:linkTestDebugExecutableIos
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIDevice", referenced from:
      objc-class-ref in combined.o
ld: symbol(s) not found for architecture x86_64
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors

> Task :app:linkTestDebugExecutableIos FAILED

**Comment by SvyatoslavScherbina** [comment]
Known issue.
Add this to your `ios` target configuration in Gradle build script:
```
binaries.getByName("testDebugExecutable").linkerOpts("-framework UIKit")
```

**Comment by jittya** [comment]
@SvyatoslavScherbina Worked!!!

**Comment by ArthurBrum** [comment]
What if I need to link more than one framework like this?
UIKit, Foundation, AVFoundation... etc

**Comment by SvyatoslavScherbina** [comment]
> What if I need to link more than one framework like this?

Why do you ask? Have you encountered a similar problem with other framework?

This particular issue can happen only with system frameworks, and `UIKit` is the only known example.

**Comment by ArthurBrum** [comment]
Well, I just had to link things correctly, you already helped me here:
https://github.com/JetBrains/kotlin-native/issues/3096#issuecomment-584028554
