### ISSUE TITLE
Regression in test.kexe: pointer being freed was not allocated

### ISSUE THREAD

**Issue by jurmous** [JetBrains/kotlin-native#3311]
After updating to 1.3.50/1.3.40 I have an issue with a malloc error while running the tests. I have no clue on how to debug the error.

```
test.kexe(3828,0x1179fc5c0) malloc: *** error for object 0x7fa7a619fa68: pointer being freed was not allocated
test.kexe(3828,0x1179fc5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

The project itself is almost all common code and standard library. There is only a base64 native "actual" handling with pointers I am aware of but it is handled with memScoped {} block.

I have uploaded the test.kexe build with 1.3.50 and included DWARF. 
[test.kexe.zip](https://github.com/JetBrains/kotlin-native/files/3573576/test.kexe.zip)

If I begin to comment out tests others pop up so it seems something fundamental.

Is the issue known? And how can I debug this myself if needed?

**Comment by artdfel** [comment]
Hello!
It looks like you are using `memScoped` incorrectly. In your case, a pointer was allocated in the block and then given to the Objective-C side. Then, it was free by the garbage collector, but after the end of the `memScoped`. It should go away if you use `nativeHeap` to allocate what you want.

**Comment by jurmous** [comment]
Ah that did the trick. I now moved a base64 encode method from memScope to get the pointer from native heap.  Am I doing it correctly? Because the result seems to be verbose. I am still searching for the right paths.

```
/** Encode [bytes] array into a base64 String */
    actual fun encode(bytes: ByteArray): String {
        return NSData.create(
            bytesNoCopy = bytes.toCValues().let {
                it.place(interpretCPointer(nativeHeap.alloc(it.size, it.align).rawPtr)!!)
            },
            length = bytes.size.toULong()
        ).base64EncodedStringWithOptions(0)
    }
```

**Comment by olonho** [comment]
Likely it was just a bug which kept unnoticed due to lack of delayed reference counter updates.
