### ISSUE TITLE
How to get objc class from kclass.

### ISSUE THREAD

**Issue by DTHeaven** [JetBrains/kotlin-native#3330]
Sometime we need use objc class as param, but we can only get kclass from common code.

**Comment by olonho** [comment]
Whu not use
```
    val p = NSObject()
    println(p.`class`)
```?

**Comment by artdfel** [comment]
This option is unavailable, please provide some additional details on your needs. What exactly you're trying to do?

**Comment by DTHeaven** [comment]
```
expect class HttpClient(url: String) {

    fun <Response : Any> get(
        path: String,
        queryMap: Map<String,String> = mutableMapOf(),
        responseClass: KClass<Response>,
        onSuccess: (Response?) -> Unit,
        onError: (Throwable?) -> Unit
    )

    fun <Response : Any> post(
        path: String,
        request: Any?,
        responseClass: KClass<Response>,
        onSuccess: (Response?) -> Unit,
        onError: (Throwable?) -> Unit
    )

}
```

In iosMain, we need use responseClass as objc class to interact with iOS lib.

**Comment by olonho** [comment]
How exactly do you want to use it in iOS library? Why do you believe such class makes sense for Objective-C?

**Comment by DTHeaven** [comment]
> How exactly do you want to use it in iOS library? Why do you believe such class makes sense for Objective-C?

In our case, 'Response' is subclass of GPBMessage in iosMain, we use [XXResponse parseFromData] to obtain instance from OC.

**Comment by SvyatoslavScherbina** [comment]
For Kotlin subclasses of Objective-C classes this should help:
```kotlin
class MyResponse : GPBMessage() {
    companion object : GPBMessageMeta()
}
```
Then `MyResponse` can be used as Objective-C class.

**Comment by DTHeaven** [comment]
> For Kotlin subclasses of Objective-C classes this should help:
> 
> ```kotlin
> class MyResponse : GPBMessage() {
>     companion object : GPBMessageMeta()
> }
> ```
> 
> Then `MyResponse` can be used as Objective-C class.

That's great, I will have a try.
Thanks!
