### ISSUE TITLE
KClassUnsupportedImpl 

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3332]
There is a kotlin class which is subclass of a object-c class.
When we try to get its KClass , we get KClassUnsupportedImpl. And when we invoke KClassUnsupportedImpl.simpleName, crash happen.

**Comment by acc110789** [comment]
we want to get a correct KClass which we can get  the simpleName property

**Comment by olonho** [comment]
Better report issues with a reproducer, so that we could understand your usecase better.
