### ISSUE TITLE
EXC_BAD_ACCESS occurs when I'm trying to call toMutableList on a ByteArray with at least one negative byte

### ISSUE THREAD

**Issue by romanandreyvich** [JetBrains/kotlin-native#3355]
When I'm trying to call toMutableList() method on a ByteArray (with at least one negative byte) I got a crash. 

On new Kotlin 1.3.50 when i do (in Common):

```
val bytes = byteArrayOf(1)
val mutableBytes = bytes.toMutableList()
```

It works fine, but if a byteArray contains a negative value i got a crash on iOS (on Android works fine). It's easy to reproduce, example:

```
val bytes = byteArrayOf(-1)
val mutableBytes = bytes.toMutableList() /* got a crash here on iOS */
```

The issue looks similar with https://github.com/JetBrains/kotlin-native/issues/3290 but the workaround described in the discussion didn't help.

Kotlin: 1.3.50
Device: iPhone 7 (Real device), iOS: 12.0

**Comment by artdfel** [comment]
Reproduced successfully, but the workaround helped as expected(Kotlin 1.3.50, iOS 12.4.1). Can you please provide additional information on the crash?

**Comment by olonho** [comment]
@romanandreyvich please provide us more info, otherwise we cannot help you here.

**Comment by romanandreyvich** [comment]
Tried the workaround again and it helped. Thank you
