### ISSUE TITLE
Re-generate platform libs adhoc - iOS 13 support

### ISSUE THREAD

**Issue by idstein** [JetBrains/kotlin-native#3362]
We use custom cinterops to work around missing vector types in K/N. However, our custom interops are not working anymore, as they refer to XCode 11 GM headers that transitively include new iOS 13 types e.g. MTLCoordinate2D.

```
Showing Recent Messages
> Task :extensions:ar:cinteropArkithelpersIos

e: ...ar-cinterop-arkithelpers.klib-build/kotlin/platform/ARKit/helpers/helpers.kt: (29, 30): Unresolved reference: AVAudio3DMixingPointSourceInHeadMode

e: ...ar-cinterop-arkithelpers.klib-build/kotlin/platform/ARKit/helpers/helpers.kt: (31, 30): Unresolved reference: AVAudio3DMixingSourceMode

e: ...ar-cinterop-arkithelpers.klib-build/kotlin/platform/ARKit/helpers/helpers.kt: (100, 23): Unresolved reference: MTLCoordinate2D
...
```

Example Kotlin interop file
```
package=platform.ARKit.helpers
language=Objective-C
depends=ARKit
---
#import <ARKit/ARKit.h>

// float3 and float3x3
static inline void simd_float3x3ToFloatArray(simd_float3x3 matrix, float* copyTarget)
...
```

Can we somehow re-generate platform libs adhoc?
When do you plan to support Xcode 11; respectively iOS 13?

**Comment by olonho** [comment]
First, there are plans to support SIMD types. 

Second, XCode 11 is still beta, we usually support XCode release in K/N release following the release, unless there are special reasons not to do so.

**Comment by olonho** [comment]
And surely you can generate interop bindings against any library, but better do that in different namespace, as it's unlikely it will properly work with standard platform libraries.

**Comment by idstein** [comment]
We reaolved this by adding a headerFilter to only include out import statement to avoid tranisitive importa.

**Comment by olonho** [comment]
Master now shall have support for XCode 11.
