### ISSUE TITLE
No run task when using mingwX86

### ISSUE THREAD

**Issue by Ricky12Awesome** [JetBrains/kotlin-native#3369]
A `runTask` is not being generated when using `mingwX86` but is being generated for `mingwX64`

I've discovered this when trying to use https://github.com/msink/kotlin-libui

I Can create the executable and run it just fine though, just no `runTask`

**Comment by ilmat192** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-42669](https://youtrack.jetbrains.com/issue/KT-42669)
