### ISSUE TITLE
FatFrameworkTask not found.

### ISSUE THREAD

**Issue by VincentChen1212** [JetBrains/kotlin-native#3370]
Hi,
I Try to use FatFrameworkTask 
(My IDE is IntelliJ)
But I got Error
![2019-09-23-09 09 18](https://user-images.githubusercontent.com/51907583/65397411-7a8e3c00-dde2-11e9-86eb-350bd29ac64d.png)
How to fix it ?
Thanks

**Comment by ilmat192** [comment]
It may relate to Groovy DSL support in IntelliJ. Try to use the Kotlin DSL instead.

**Comment by cydhhp** [comment]
wow, Kotlin DSL is ok, what is different from this two? why the offical sample use  Groovy and Kotlin DSL?

**Comment by VincentChen1212** [comment]
WOW, Kotlin DSL is ok, what is different from this two? why the offical sample use Groovy and Kotlin DSL?

**Comment by ilmat192** [comment]
The Kotlin DSL is statically typed and provides a better IDE support comparing to the Groovy DSL. See more here: https://docs.gradle.org/current/userguide/kotlin_dsl.html.

> why the offical sample use Groovy and Kotlin DSL?

Sorry, I didn't get your question :) What sample do you mean?

**Comment by webfrea-k** [comment]
It's colored red for me too, but it actually works.
Just specify it somewhere below:

```
    task generateIosFrameworkDebug(type: FatFrameworkTask) {
        //task
    }
```
