### ISSUE TITLE
Extend "Kotlin/Native as a Dynamic Library" tutorial by python wrappers

### ISSUE THREAD

**Issue by MarAlder** [JetBrains/kotlin-native#3378]
Is it possible to include the [python-extension](https://github.com/JetBrains/kotlin-native/tree/master/samples/python_extension) approach into the [Kotlin/Native as a Dynamic Library](https://kotlinlang.org/docs/tutorials/native/dynamic-libraries.html) tutorial in order to have a consistent example for beginners?

I managed to set up IntelliJ/Gradle etc. with respect to the [tutorial](https://kotlinlang.org/docs/tutorials/native/dynamic-libraries.html) an I get the dll and header file, but I find it hard to combine the kotlin-bridge with this example.

**Comment by artdfel** [comment]
Hello! What kind of issues are you experiencing?

**Comment by SvyatoslavScherbina** [comment]
Got no response, closing.
