### ISSUE TITLE
iOS app crash on initRuntime()

### ISSUE THREAD

**Issue by FrancoSabadini** [JetBrains/kotlin-native#3422]
**Kotlin version:** 1.3.41

**iOS version:** 12.4.1
**Device:** iPhone 7 Plus

I got the crash info from Crashlytics so not sure how to reproduce it.

Stacktrace:

```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x20a15b0dc __pthread_kill + 8
1  libsystem_pthread.dylib        0x20a1d4094 pthread_kill$VARIANT$mp + 380
2  libsystem_c.dylib              0x20a0b3ea8 abort + 140
3  App                            0x100a87dbc (anonymous namespace)::initRuntime() + 4381359548
4  App                            0x100a87d6c konan::snprintf(char*, unsigned long, char const*, ...) + 4381359468
5  App                            0x100a89d20 garbageCollect(MemoryState*, bool) + 4381367584
6  App                            0x100a8c1b4 AllocInstance + 4381376948
7  App                            0x100745f00 kfun:kotlin.collections.HashMap.entriesIterator$stdlib()kotlin.collections.HashMap.EntriesItr<#GENERIC,#GENERIC> + 4377943808
8  CoreFoundation                 0x20a550578 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
9  CoreFoundation                 0x20a54fe7c __CFRunLoopDoBlocks + 272
10 CoreFoundation                 0x20a54b3e8 __CFRunLoopRun + 2312
11 CoreFoundation                 0x20a54a7c0 CFRunLoopRunSpecific + 436
12 GraphicsServices               0x20c74b79c GSEventRunModal + 104
13 UIKitCore                      0x23704fc38 UIApplicationMain + 212
14 App                            0x1004d0b4c main + 14 (AppDelegate.swift:14)
15 libdyld.dylib                  0x20a00e8e0 start + 4
```

**Comment by artdfel** [comment]
Hello! Please try to update the compiler version. There is the latest stable release 1.3.50, available [here](https://github.com/JetBrains/kotlin-native/releases/tag/v1.3.50).

**Comment by FrancoSabadini** [comment]
Hi @artdfel, I have already updated to Kotlin 1.3.50 and released a new version of the app around a week ago. 

So far I haven't seen this crash again in Crashlytics, but then again it only happened once with the previous version of the app so not sure how often it'd appear.

I'll keep an eye on it for the next few weeks and if I don't see it again I'll let you know and you can probably close this.

**Comment by FrancoSabadini** [comment]
Hi again @artdfel, I still haven't seen new instances of this issue after updating to 1.3.50 so I'll close it. If it appears again I'll re-open it. Thanks for the help! :)
