### ISSUE TITLE
Support XCFramework

### ISSUE THREAD

**Issue by horita-yuya** [JetBrains/kotlin-native#3423]
Currently, FatFramewokTask has been supported. Also, supporting XCFramework would be more helpful.

https://developer.apple.com/videos/play/wwdc2019/416/

**Comment by MrAsterisco** [comment]
It would be awesome to have integrated support, but this can be achieved easily with the following configuration.

In your `build.gradle`:

```groovy
targets {
        ios()
        configure([iosX64, iosArm64]) {
                binaries.framework {
                    baseName = "YourFramework"
                }
        }
}
```

This produces two frameworks in your build directory, one in `iosArm64` and the other in `iosX64`. Just run the following script when you want to build the XCFramework:

```shell
xcodebuild -create-xcframework -framework iosArm64/debugFramework/YourFramework.framework -framework iosX64/debugFramework/YourFramework.framework -output YourFramework.xcframework
```

This can also be automated using a custom Gradle task or by adding a Run Script phase in your Xcode project.

**Comment by horita-yuya** [comment]
Yes, I have been using such a script. But I thought default support might be useful.

**Comment by ilmat192** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-42667](https://youtrack.jetbrains.com/issue/KT-42667)

**Comment by epool** [comment]
I created this little [gradle task](https://gist.github.com/epool/b55f9b8f64427efc5717510e0246c278) for building a release .xcframework from a shared module.
