### ISSUE TITLE
Different readLine() behavior on JVM and Native

### ISSUE THREAD

**Issue by esgwpl** [JetBrains/kotlin-native#3430]
```
info: kotlinc-native 1.3.50 (JRE 12.0.2+10)
Kotlin/Native: 1.3.50
```

```
fun main() {
    var numberList = (1..9).shuffled()
    val sortedNumberList = (1..9).toList()
    var steps = 0
    var input: Int

    while (numberList != sortedNumberList) {
        print("$numberList\nFlip how many? ")
        input = readLine()?.toIntOrNull() ?: 0
        if (input < 2 || input > 9) {
            println("Invalid input.")
            continue
        }
        numberList = numberList.take(input).reversed() + numberList.takeLast(9 - input)
        steps++
    }
    println("$numberList\nDone in $steps steps!")
}
```

On the JVM, putting EOF as an input (Ctrl + D on Linux) will cause the program to print "Invalid input." once and skips over to the next iteration of the while loop and ask for another input. When compiled with konanc on the other hand, hitting Ctrl + D will cause the program to be stuck printing "Invalid input." over and over again.

**Comment by artdfel** [comment]
Hello! 
Thank you for the report! We managed to reproduce the issue, please wait for updates.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/3435 fixes it

**Comment by olonho** [comment]
Fix merged.
