### ISSUE TITLE
Memory keeps increasing when using Worker to execute lots of jobs

### ISSUE THREAD

**Issue by Piasy** [JetBrains/kotlin-native#3438]
I create a simple project to evaluate Kotlin/Native for multiplatform development, in which I want to use Worker to offload jobs from main thread. But I find out that when I execute 1000 empty jobs, the memory will increase about 1KB~3KB, and it never drops back.

Below is the screenshot of it:

![WX20191008-134620](https://user-images.githubusercontent.com/3098704/66370435-de178c80-e9d2-11e9-8271-d7ef8e648e18.png)

I also verify that the same problem exists on Windows.

As for Android, Worker is not available, so I use ExecutorService, in which the problem doesn't exist. Actually the memory will increase after every 1K jobs' execution, but it will drop back when GC happens.

Here is the source code of my project: https://github.com/Piasy/KmppBootstrap/tree/task_queue

**Comment by Piasy** [comment]
I've confirmed that when using GCD instead of Worker on iOS, the issue didn't exist, although the memory would increase, it would drop back sometime later.

**Comment by olonho** [comment]
Does it grows linearly if you execute 10000 or 1000000 jobs? Native memory in many cases is just not released back by the system allocator, and it's not a problem by itself, as actual memory is controlled by OS VMM.

**Comment by Piasy** [comment]
@olonho Thanks for your response, when using Worker, it grows linearly, when I execute 1000 jobs, it grows 1KB~3KB, when I repeat executing 1000 jobs 10 times, it grows 1MB~3MB.

I verified that the memory usage would increase to hundreds of MB and never drops back, and it would be killed by OS after it reached the memory limit.

That's definitely a problem, and when using GCD the memory stays low. I think it may have memory leaks when using Worker.

**Comment by olonho** [comment]
Please provide reproducer.

**Comment by Piasy** [comment]
@olonho The GitHub link is a minimal project that could reproduce this issue.

**Comment by olonho** [comment]
It doesn't have a single mention of Worker in the source code, and is not minimal. Please provide minimal reproducer with the source code.
```kotlin/bugs/KmppBootstrap> find . -name \*.kt| xargs grep Worker|wc -l
       0
```

**Comment by Piasy** [comment]
@olonho  It's in the `task_queue` branch. Sorry for the confusion.

**Comment by olonho** [comment]
You never do anything with the `Future` object returned by `execute`. It must be consumed to avoid leaks. In your case `executeAfter(0)` could be a better choice.

**Comment by Piasy** [comment]
Oh thanks! I'll try it now.

**Comment by Piasy** [comment]
It works like a charm! Thank you so much for saving my day!

**Comment by kerry** [comment]
@Piasy I am also currently researching on KN for common library in android and iOS. Are dispatch_queues and workers interchangeable in Kotlin/Native? Is there any advantage of one over the other?

**Comment by Piasy** [comment]
Hi @kerry , sorry that I get no idea about that, maybe you should ask it in the forum or somewhere else.
