### ISSUE TITLE
static library has no debug info？

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3446]
I have a demo mpp project, its ios target produce a framework.
My ios project use this framework.
I found that when the framework is static library ,  i can not set kotlin breakpoint.

when the framework is not static as follows: 

![dynamic_configure](https://user-images.githubusercontent.com/11617214/66537717-10042c80-eb54-11e9-8d8b-a37273f68250.png)

I can set kotlin breakpoints with lldb as follows:
![dynamic_lib_result](https://user-images.githubusercontent.com/11617214/66537930-e3044980-eb54-11e9-8473-bf1cb49b87fe.png)

But , when the framework is static as follows:
![static_configure](https://user-images.githubusercontent.com/11617214/66537959-0202db80-eb55-11e9-8b10-5879e770b752.png)

I can not set kotlin breakpoints with lldb as follows:
![static_lib_result](https://user-images.githubusercontent.com/11617214/66537979-1515ab80-eb55-11e9-8f3f-62ea4c1da53c.png)
 as you can see, it says: Unable to resolve breakpoint to any actual locations.

**Comment by acc110789** [comment]
Out mpp project want to produce static library framework , but this will diable kotlin debugging. Is there something wrong? Do you have any suggestion?

**Comment by ilmat192** [comment]
Hello! A static framework does contain a debug information so probably it was stripped by some other tool. Could you please share your project?

**Comment by acc110789** [comment]
Actually , I just want the produced static library framewok debuggable.

**Comment by acc110789** [comment]
> Hello! A static framework does contain a debug information so probably it was stripped by some other tool. Could you please share your project?

hello，Is there any problem？

**Comment by vvlevchenko** [comment]
Hello, thank you for provided project. We're able to reproduce the issue. What we see that both binaries static framework and result application have debug information. We're investigating at the moment why lldb can't resolve breakpoint.

**Comment by vvlevchenko** [comment]
Hello,
 you can do following:
   1. go to the folder where your application is built
   2. run dsymutil on binary, e.g. `dsymutil StatBr.app/StatBr`
   3. now AppCode or Xcode can set breakpoints in static framework for you.

**Comment by acc110789** [comment]
thx

**Comment by vvlevchenko** [comment]
the workoaround isn't required anymore after 1.4-rc. for more details please take a look at https://youtrack.jetbrains.com/issue/KT-40566
