### ISSUE TITLE
App crash in CharArray (iOS)

### ISSUE THREAD

**Issue by FrancoSabadini** [JetBrains/kotlin-native#3469]
I got the crash info from Crashlytics and I haven't been able to reproduce it locally.

**Kotlin version:** 1.3.50

**iOS version:** 13.1.2 (17A860)
**Device:** iPad Air 2

**Error:** EXC_BAD_ACCESS KERN_INVALID_ADDRESS

**Stack trace:**

```
Crashed: com.apple.main-thread
0  App                           0x105103e30 (anonymous namespace)::garbageCollect(MemoryState*, bool) + 4369841712
1  App                           0x105111e64 ObjHeader* (anonymous namespace)::allocInstance<true>(TypeInfo const*, ObjHeader**) + 4369899108
2  App                           0x104efe9ec kfun:io.ktor.util.CaseInsensitiveMap.$<get-entries>$lambda-2$FUNCTION_REFERENCE$87.invoke#internal + 4367722988
3  CoreFoundation                 0x1b49f107c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
4  CoreFoundation                 0x1b49f0800 __CFRunLoopDoBlocks + 268
5  CoreFoundation                 0x1b49ebcb0 __CFRunLoopRun + 2288
6  CoreFoundation                 0x1b49eb098 CFRunLoopRunSpecific + 480
7  GraphicsServices               0x1beb55534 GSEventRunModal + 108
8  UIKitCore                      0x1b8b0b7ac UIApplicationMain + 1940
9  App                           0x104b8e6a4 main + 14 (AppDelegate.swift:14)
10 libdyld.dylib                  0x1b486af30 <redacted> + 4
```

**Comment by SvyatoslavScherbina** [comment]
Have you tried applying the workaround from https://github.com/JetBrains/kotlin-native/issues/3259#issuecomment-526503356?

**Comment by FrancoSabadini** [comment]
@SvyatoslavScherbina yes I have tried that workaround and I still got this error.

**Comment by FrancoSabadini** [comment]
After updating to Kotlin 1.3.61 I have not seen this anymore, I'll close this for now and if I see it again I'll re-open it.

**Comment by vikihleblya** [comment]
@francos, hi, have you got this issues again?

**Comment by francos** [comment]
Hi @vikihleblya, I am no longer working on the project where I saw this issue, but it didn't appear anymore while I was at the company.

**Comment by vikihleblya** [comment]
Okay, thank you @francos for answering!
