### ISSUE TITLE
Split up and add headerFilters to windows.def

### ISSUE THREAD

**Issue by micolous** [JetBrains/kotlin-native#3483]
I'm [building Kotlin bindings for the PC/SC API](https://github.com/micolous/kotlin-pcsc) (aka `winscard`) that are multiplatform (~I plan to release this library as open source~ **edit:** [this is now released](https://github.com/micolous/kotlin-pcsc)).  I've got this working for JNA (on JVM), Linux and macOS; but have many difficulties trying to get this working right on Windows Native, and the reason is [windows.def][].

At present, [windows.def][] includes `windows.h`, and tries to link against a basket of different libraries:

https://github.com/JetBrains/kotlin-native/blob/e21ab4f1e728e3fe875343d83c98ede9fb3d6bd9/platformLibs/src/platform/mingw/windows.def#L6

_Unfortunately,_ `windows.h` includes pretty much every Windows platform API header, and there have been no `headerFilters` set for `windows.def`.

As a result:

* Any Windows library needs to be added to this file to be usable ([example patch](https://github.com/JetBrains/kotlin-native/commit/d5096cbb1e14ed4f015cd63533f1b05a80fc03d4)), even when transitively included in `windows.h`, or hacks like #3135 need to be added.

* The generated bindings don't have complete coverage on `noStringConversion` -- any function call which passes a multistring won't work properly (eg: `SCardListReaders`).

* Anyone who tries to add their _own_ platform definition that includes something from `windows.h` will have Kotlin Multiplatform tools **silently drop those declarations**.  This is incredibly frustrating to debug.

* This links to platform libraries that are not needed by all users, adding unnecessary bloat to their Windows binaries.

What I think is needed to solve this:

* **Short-term**: Add explicit `headerFilters` to exclude everything that gets transitively included from `windows.h`.  That way, at least developers can provide their own bindings to Windows APIs.

* **Long-term**: Split up Windows platform libraries, much like the [macOS platform bindings already do](https://github.com/JetBrains/kotlin-native/tree/master/platformLibs/src/platform/osx); so you'd have `dwmapi.def`, `comctl32.def`, `winscard.def`, etc. which map into `platform.windows.dwmapi.*`, `platform.windows.comctl32.*` and `platform.windows.winscard.*` respectively.

[windows.def]: https://github.com/JetBrains/kotlin-native/blob/master/platformLibs/src/platform/mingw/windows.def

**Comment by msink** [comment]
Well, sure win32 API is a mess.
`windows.h` directly or indirectly includes:
```
apiset.h
apisetcconv.h
basetsd.h
bcrypt.h
bemapiset.h
cderr.h
cguid.h
combaseapi.h
comcat.h
commctrl.h
commdlg.h
corecrt.h
corecrt_wstdlib.h
crtdefs.h
ctype.h
datetimeapi.h
dde.h
ddeml.h
debugapi.h
dlgs.h
docobj.h
dpapi.h
driverspecs.h
dwmapi.h
errhandlingapi.h
excpt.h
exdisp.h
fibersapi.h
fileapi.h
fltwinerror.h
guiddef.h
handleapi.h
heapapi.h
imm.h
in6addr.h
inaddr.h
interlockedapi.h
ioapiset.h
isguids.h
jobapi.h
knownfolders.h
ktmtypes.h
libloaderapi.h
limits.h
lzexpand.h
malloc.h
mcx.h
memoryapi.h
minwinbase.h
minwindef.h
mmreg.h
mmsystem.h
msacm.h
mstcpip.h
msxml.h
namedpipeapi.h
namespaceapi.h
nb30.h
ncrypt.h
oaidl.h
objbase.h
objectarray.h
objidl.h
objidlbase.h
ocidl.h
ole2.h
oleauto.h
oleidl.h
poppack.h
processenv.h
processthreadsapi.h
processtopologyapi.h
profileapi.h
propidl.h
propkeydef.h
propsys.h
prsht.h
psdk_inc/_fd_types.h
psdk_inc/_ip_mreq1.h
psdk_inc/_ip_types.h
psdk_inc/_socket_types.h
psdk_inc/_ws1_undef.h
psdk_inc/_wsa_errnos.h
psdk_inc/_wsadata.h
psdk_inc/_xmitfile.h
psdk_inc/intrin-impl.h
pshpack1.h
pshpack2.h
pshpack4.h
pshpack8.h
qos.h
realtimeapiset.h
reason.h
rpc.h
rpcasync.h
rpcdce.h
rpcdcep.h
rpcndr.h
rpcnsi.h
rpcnsip.h
rpcnterr.h
rpcsal.h
sal.h
sdkddkver.h
sdks/_mingw_ddk.h
sdks/_mingw_directx.h
sec_api/stdlib_s.h
sec_api/stralign_s.h
sec_api/string_s.h
securityappcontainer.h
securitybaseapi.h
servprov.h
shellapi.h
sherrors.h
shldisp.h
shlguid.h
shlobj.h
shlwapi.h
shobjidl.h
shtypes.h
specstrings.h
stdarg.h
stdlib.h
stralign.h
string.h
stringapiset.h
structuredquerycondition.h
synchapi.h
sysinfoapi.h
systemtopologyapi.h
threadpoolapiset.h
threadpoollegacyapiset.h
timezoneapi.h
tvout.h
unknwn.h
unknwnbase.h
urlmon.h
usp10.h
utilapiset.h
uxtheme.h
vadefs.h
vfw.h
virtdisk.h
winapifamily.h
winbase.h
wincon.h
wincrypt.h
windef.h
windows.h
winefs.h
winerror.h
wingdi.h
wininet.h
winioctl.h
winnetwk.h
winnls.h
winnt.h
winperf.h
winreg.h
winscard.h
winsmcrd.h
winsock.h
winsock2.h
winspool.h
winsvc.h
winuser.h
winver.h
wnnc.h
wow64apiset.h
ws2def.h
ws2ipdef.h
ws2tcpip.h
wtypes.h
wtypesbase.h
```

What shoud be included in `headerFilters` ?

**Comment by micolous** [comment]
For the short-term solution, include anything that is needed for the existing linker flags:

```
-lcomctl32 -lcrypt32 -lshlwapi -lshell32 -limm32 -lusp10 -lwininet -lgdi32 -luser32 -lkernel32 -lbcrypt -luuid
```

That way we _shouldn't_ break anyone who is using this.

I'm not familiar enough with Windows native stuff to figure out a programatic way to calculate this.  I've worked out a few libraries by hand:

library | header(s)
------ | ------------
bcrypt | bcrypt.h
comctl32 | commctrl.h
crypt32 | wincrypt.h
gdi32 | TODO
imm32 | TODO
kernel32 | TODO
shlwapi | shlwapi.h
shell32 | TODO
uuid | TODO
user32 | winuser.h windowsx.h
usp10 | TODO
wininet | wininet.h

**Comment by msink** [comment]
Did PR: #3496

**Comment by micolous** [comment]
Thanks.  I've since managed to try working around this for `winscard`, it required [significant](https://github.com/micolous/kotlin-pcsc/blob/3d5013f67c296a83fe740897c7640a3a587c6b4b/src/nativeInterop/cinterop/winscard.def#L35-L67) [surgery](https://github.com/micolous/kotlin-pcsc/blob/master/src/nativeWindowsMain/kotlin/PlatformTypes.kt) to get it even _building_ on Windows -- but this still crashes.

**Comment by msink** [comment]
And **who** will test if it works? It should, if not, and someone finds a bug - this issue tracker is exactly for that.

**Comment by sbogolepov** [comment]
We are transferring issues to YouTrack (#4079), so I created [KT-45071](https://youtrack.jetbrains.com/issue/KT-45071) to track this problem there.
