### ISSUE TITLE
Support pkg-config in Native build plugin

### ISSUE THREAD

**Issue by micolous** [JetBrains/kotlin-native#3484]
Lots of build scripts have hard coded paths for Linux and macOS.  Some mingw scripts in this repository have hard coded paths as well.

This was previously raised a couple of years in the context of gtk3 in #699, but it's not clear what the next actions are / were (and GTK isn't the only thing that uses pkg-config).  It looks like [the GTK3 sample still hard codes paths](https://github.com/JetBrains/kotlin-native/blob/e21ab4f1e728e3fe875343d83c98ede9fb3d6bd9/samples/gtk/build.gradle.kts#L33-L63) to deal with differences between Debian, Fedora and macOS.

This would also make the build system work better for [Linux distributions that don't use the traditional `/usr` path structure](https://gobolinux.org/at_a_glance.html).

**Comment by msink** [comment]
On Linux `pkg-config` does not print `libdir`: "This is because it treats the -L flag specially and knows that the ${libdir} directory /usr/lib is part of the system linker search path. This keeps pkg-config from interfering with the linker operation."
But `cinterop` does not use system linker search path, and `-L${libdir}` have to be in `linkerOpts`

```
$ pkg-config --libs gtk+-3.0
-lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
```

```
$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/gtk+-3.0.pc
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib/x86_64-linux-gnu
includedir=${prefix}/include
targets=x11 broadway wayland mir

gtk_binary_version=3.0.0
gtk_host=x86_64-pc-linux-gnu

Name: GTK+
Description: GTK+ Graphical UI Library
Version: 3.18.9
Requires: gdk-3.0 atk >= 2.15.1 cairo >= 1.14.0 cairo-gobject >= 1.14.0 gdk-pixbuf-2.0 >= 2.30.0 gio-2.0 >= 2.45.8
Requires.private: atk atk-bridge-2.0 wayland-client >= 1.5.91 xkbcommon >= 0.2.0 wayland-cursor >= 1.5.91 wayland-egl mirclient >= 0.11.0 mircookie >= 0.17.0 epoxy >= 1.0 pangoft2 gio-unix-2.0 >= 2.45.8
Libs: -L${libdir} -lgtk-3 
Cflags: -I${includedir}/gtk-3.0 
```

**Comment by micolous** [comment]
Yup, `-L{libdir}` is not shown on macOS either by default.  It looks like this can be fixed with the environment variable `PKG_CONFIG_ALLOW_SYSTEM_LIBS=1`:

```
$ pkg-config --libs libcurl
-lcurl
$ PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 pkg-config --libs libcurl
-L/usr/lib -lcurl
```

**Comment by msink** [comment]
Great, it works on Linux and MinGW:
```
$ PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 pkg-config --libs gtk+-3.0
-L/usr/lib/x86_64-linux-gnu -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
```
```
$ PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 pkg-config --libs gtk+-3.0
-LF:/msys64/mingw64/lib -lgtk-3 -lgdk-3 -lz -lgdi32 -limm32 -lshell32 -lole32 -Wl,-luuid -lwinmm -ldwmapi -lsetupapi -lcfgmgr32 -lpangowin32-1.0 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lintl -lglib-2.0
```

**Comment by micolous** [comment]
This is what I ended up trying, but it needs some fixing to work:

https://gist.github.com/micolous/c00b14b2dc321fdb0eab8ad796d71b80

* When trying to use this on a macOS host, I get back pkg-config errors, because the library I was trying to use on Linux wasn't in my macOS host environment.

* When trying to use this on a Linux host to compile stuff for Linux, I get back:

```
> Task :cinterop...LinuxX64
warning: -linker-option(s)/-linkerOpts/-lopt option is not supported by cinterop. Please add linker options to .def file or binary compilation instead.
```

This is a pretty ugly hack, so I'd rather this functionality be properly past of the Native build plugin.
