### ISSUE TITLE
UITabBarController crash in iOS related to Objective-C subclass properties

### ISSUE THREAD

**Issue by Ti-m** [JetBrains/kotlin-native#3488]
Hey, when I run the following code I get a crash:

```
import platform.UIKit.*

class TabBarBug : UITabBarController(nibName = null, bundle = null) {
    val innerNavDashboard = UINavigationController(rootViewController = UIViewController())

    override fun viewDidLoad() {
        super.viewDidLoad()

        val tabDashboard = UITabBarItem(title = "tabbaritem-dashboard", image= null, selectedImage = null)

        this.innerNavDashboard.tabBarItem = tabDashboard

        this.viewControllers = listOf(this.innerNavDashboard) //This line crashes with -[NSNull _setViewHostsLayoutEngine:]: unrecognized selector sent to instance 0x7fff805f0330

    }
}
```
I think this is a bug because:
* If I convert the code to swift and run it directly in Xcode it works.
* If I convert innerNavDashboard to a local variable of viewDidLoad it works in Kotlin too.

So the issue seems related to properties.

```
2019-10-23 14:39:33.667636+0200 MyProject[37446:1296203] -[NSNull _setViewHostsLayoutEngine:]: unrecognized selector sent to instance 0x7fff805f0330
2019-10-23 14:39:33.702761+0200 MyProject[37446:1296203] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull _setViewHostsLayoutEngine:]: unrecognized selector sent to instance 0x7fff805f0330'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23bcb154 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23baef6c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23bb10f8 _CF_forwarding_prep_0 + 120
	5   UIKitCore                           0x00007fff46e3aa34 -[UITabBarController _setViewControllers:animated:] + 242
	6   UIKitCore                           0x00007fff46e3b76b -[UITabBarController setViewControllers:animated:] + 119
	7   my_project                      0x000000010f1db57f kfun:my.bundle.TabBarBug.objc:viewDidLoad + 1471
	8   my_project                      0x000000010f1db9de _knbridge353 + 142
	9   UIKitCore                           0x00007fff46e356cc -[UITabBarController initWithNibName:bundle:] + 237

**Comment by olonho** [comment]
See https://github.com/JetBrains/kotlin-native/blob/838cccf275b121878003d9c8c2f7600d78b10989/samples/uikit/src/iosMain/kotlin/ViewController.kt#L16, note @ExportObjCClass annotation.

**Comment by SvyatoslavScherbina** [comment]
> I am not sure how to do this. Should this annotation appear in my Framework header if I add @ExportObjCClass to my class? Or do I have to add it by hand in my code?

`@ExportObjCClass` is likely not related to your issue and thus not actually required here.

> The line with the crash in my first post is not even reached. So you mean my crash is caused by an uninitialized value?

Yes.

> innerNavDashboard Is declared as an non-nullable reference. So this shouldn’t be possible?

In fact it is possible. Uninitialized values usually cause such problems.

> In this code the crash is happening too.

Exactly, because `val navDashboard: UINavigationController` is initialized after super initializer too.

For example, see the snippet in pure Kotlin showing this behaviour:
```kotlin
open class Base {
    open fun foo() {}

    init {
        foo()
    }
}

class Derived(val x: Any) : Base() {
    override fun foo() {
        println(x)
    }
}

fun main() {
    Derived(Any())
}
```
It prints `null` on JVM too.

**Comment by Ti-m** [comment]
Ah you're right.
The compiler even generates a warning in the base class. Of course I don't have the base class in this case. ;-)
I replaced viewDidLoad with viewWillAppear and it works.
Thank you very much.
