### ISSUE TITLE
A module whos module name contain "@" char lead to link fail

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3494]
clone this repo:
https://github.com/acc110789/Test_KN_AT

there are there module: "kn_rocket" , "kn_bussiness" and "kn_bussiness@1"。

The only difference between "kn_bussiness" module and "kn_bussiness@1" module is their module name.

when "kn_rocket" depend on "kn_bussiness" , "./gradlew :kn_rocket:linkDebugFrameworkIos"  succeed.

but when "kn_rocket" depend on "kn_bussiness@1" , "./gradlew :kn_rocket:linkDebugFrameworkIos"  fails.

I submit a same issue before,
https://github.com/JetBrains/kotlin-native/issues/3242

please support "@" character.

we use jenkins to auto packaging ， and jenkins will generate path which contain the character '@'。

**Comment by artdfel** [comment]
I answered in the previous one, so there is no need to open new issues. Closing this one as a duplicate.
