### ISSUE TITLE
Warnings in samples/tetris

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3497]
On current master compiling samples/tetris passed, but with bunch of warnings:
```
> Configure project :tetris
project ':tetris' has been configured for mingwX64 platform.

> Task :tetris:cinteropSdlTetris

> Task :tetris:compileKotlinTetris
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/SDL_Visualizer.kt: (43, 21): [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/Tetris.kt: (22, 5): [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/Tetris.kt: (21, 5): [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/main.kt: (11, 21): [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null

> Task :tetris:copyCinteropSdlTetris
> Task :tetris:compileWindowsResources

> Task :tetris:linkDebugExecutableTetris
F:\Work\.konan\dependencies\msys2-mingw-w64-x86_64-clang-llvm-lld-compiler_rt-8.0.1\bin\ld: .rsrc merge failure: duplicate leaf: type: 10 (VERSION) name: 1 lang: 409
w: F:/src/kotlin-native/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/endorsedLibraries/kotlinx.cli/src/main/kotlin/kotlinx/cli/ArgParser.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/Regex.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/AbstractCharClass.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/CharClass.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/Pattern.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/AbstractSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/JointSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/SurrogateCharSets.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/SurrogateRangeSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/SDL_Visualizer.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/Tetris.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/main.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null

> Task :tetris:linkReleaseExecutableTetris
F:\Work\.konan\dependencies\msys2-mingw-w64-x86_64-clang-llvm-lld-compiler_rt-8.0.1\bin\ld: .rsrc merge failure: duplicate leaf: type: 10 (VERSION) name: 1 lang: 409
w: F:/src/kotlin-native/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/endorsedLibraries/kotlinx.cli/src/main/kotlin/kotlinx/cli/ArgParser.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/Regex.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/AbstractCharClass.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/CharClass.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/Pattern.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/AbstractSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/JointSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/SurrogateCharSets.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/SurrogateRangeSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/SDL_Visualizer.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/Tetris.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/main.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null

> Task :tetris:compileKotlinMetadata NO-SOURCE
> Task :tetris:metadataMainClasses UP-TO-DATE
> Task :tetris:metadataJar
> Task :tetris:assemble
> Task :tetris:tetrisProcessResources
> Task :tetris:tetrisMainKlibrary
> Task :tetris:compileTestKotlinTetris NO-SOURCE
> Task :tetris:linkDebugTestTetris NO-SOURCE
> Task :tetris:tetrisTest SKIPPED
> Task :tetris:allTests
> Task :tetris:check
> Task :tetris:build

BUILD SUCCESSFUL in 1m 20s
9 actionable tasks: 9 executed
```

**Comment by olonho** [comment]
This warning will be fixed soon.

**Comment by GypsyTheDj** [comment]
> On current master compiling samples/tetris passed, but with bunch of warnings:
> 
> ```
> > Configure project :tetris
> project ':tetris' has been configured for mingwX64 platform.
> 
> > Task :tetris:cinteropSdlTetris
> 
> > Task :tetris:compileKotlinTetris
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/SDL_Visualizer.kt: (43, 21): [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/Tetris.kt: (22, 5): [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/Tetris.kt: (21, 5): [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/main.kt: (11, 21): [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> 
> > Task :tetris:copyCinteropSdlTetris
> > Task :tetris:compileWindowsResources
> 
> > Task :tetris:linkDebugExecutableTetris
> F:\Work\.konan\dependencies\msys2-mingw-w64-x86_64-clang-llvm-lld-compiler_rt-8.0.1\bin\ld: .rsrc merge failure: duplicate leaf: type: 10 (VERSION) name: 1 lang: 409
> w: F:/src/kotlin-native/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/endorsedLibraries/kotlinx.cli/src/main/kotlin/kotlinx/cli/ArgParser.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/Regex.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/AbstractCharClass.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/CharClass.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/Pattern.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/AbstractSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/JointSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/SurrogateCharSets.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/SurrogateRangeSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/SDL_Visualizer.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/Tetris.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/main.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> 
> > Task :tetris:linkReleaseExecutableTetris
> F:\Work\.konan\dependencies\msys2-mingw-w64-x86_64-clang-llvm-lld-compiler_rt-8.0.1\bin\ld: .rsrc merge failure: duplicate leaf: type: 10 (VERSION) name: 1 lang: 409
> w: F:/src/kotlin-native/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/endorsedLibraries/kotlinx.cli/src/main/kotlin/kotlinx/cli/ArgParser.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/Regex.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/AbstractCharClass.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/CharClass.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/Pattern.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/AbstractSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/JointSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/SurrogateCharSets.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/runtime/src/main/kotlin/kotlin/text/regex/sets/SurrogateRangeSet.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/SDL_Visualizer.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/Tetris.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> w: F:/src/kotlin-native/samples/tetris/src/tetrisMain/kotlin/main.kt: [IR VALIDATION] unexpected type: expected kotlin.Nothing?, got kotlin.native.internal.DefaultConstructorMarker?
> CONST Null type=kotlin.native.internal.DefaultConstructorMarker? value=null
> 
> > Task :tetris:compileKotlinMetadata NO-SOURCE
> > Task :tetris:metadataMainClasses UP-TO-DATE
> > Task :tetris:metadataJar
> > Task :tetris:assemble
> > Task :tetris:tetrisProcessResources
> > Task :tetris:tetrisMainKlibrary
> > Task :tetris:compileTestKotlinTetris NO-SOURCE
> > Task :tetris:linkDebugTestTetris NO-SOURCE
> > Task :tetris:tetrisTest SKIPPED
> > Task :tetris:allTests
> > Task :tetris:check
> > Task :tetris:build
> 
> BUILD SUCCESSFUL in 1m 20s
> 9 actionable tasks: 9 executed
> ```

Waiting for A Fix of the warning

**Comment by homuroll** [comment]
I see no such warnings on master. Closing.
