### ISSUE TITLE
ios memory cost overhead

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3504]
repo: https://github.com/acc110789/Test_Mem/tree/master/src/iosMain/kotlin/sample

clone this repo and build a ios Framework

invoke `SampleMacosKt.main()` ios proejct(swift).

In this method , We create some memory-cost objects which increate ios memory to 3.14GB. 

However , after we release these memory-cost objects and wait a long time , ios memory is still 3.14GB

We found ios memory did not decrease except that we invoke `GC.collect` explicitly.

However , the document suggest we do not invoke `GC.collect` explicitly.

**Comment by artdfel** [comment]
Hello! 
As far as I can see, explicitly invoke of `GC.collect()` is the best of currently available options. Please keep on using this approach until things change.

**Comment by idstein** [comment]
Memory is not immediately released as in ARC model. A garbage collection cycle is required to release unreferenced Kotlin objects.
The automatic GC cycle are invoked whenever new Kotlin objects are allocated or objects run out of scope, yet GC will only kick if there has been a reasonable amount of objects collect that can be freed.

**Comment by acc110789** [comment]
> Hello!
> As far as I can see, explicitly invoke of `GC.collect()` is the best of currently available options. Please keep on using this approach until things change.

hello,  Is there a plan to improve it?
