### ISSUE TITLE
Support for including arbitrary file in bundle for Kotlin Native library project?

### ISSUE THREAD

**Issue by cody1024d** [JetBrains/kotlin-native#3511]
Hello,

I was wondering if there was an accepted method to include an arbitrary file (for example a json file) within a Kotlin Native (in the context of multiplatform) project such that it is included within the static framework that I am generating?

A use case that I am trying to accomplish:

I am writing a library that handles authenticating against a server.  This particular server needs a self-signed certificate.  I want to include this certificate within the library, so each client (of this library) does not have to include the certificate themselves.

On the Android side I accomplish this by putting it inside the res/raw folder (and thus it gets bundled up correctly), but am unfamiliar with how this would work given the Kotlin Native gradle plugin.

Thanks!

**Comment by artdfel** [comment]
Hello!
 Currently, there is no such option in the plugin. But, one can extend the Gradle script with some manual copying important files into the framework. There is a conversation [here](https://github.com/JetBrains/kotlin-native/issues/2248), with some recommendations on it. Also, one can take a look at the library [moko-resources](https://github.com/icerockdev/moko-resources/tree/327eef878d929ec78cc38eb7202b99404a400874), dealing with this problem.

**Comment by cody1024d** [comment]
Thank you @artdfel for the quick and thurough response.  Closing this issue.
