### ISSUE TITLE
Issue with dependency resolution when creating universal framework

### ISSUE THREAD

**Issue by jcraane** [JetBrains/kotlin-native#3514]
I don't know if this is the correct place for this.

We have a Kotlin native Android/iOS app and want to use the universal frameworks feature (as
described in https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries). The basic setup works fine but when we add dependencies (for example ktor) we get the following error:

> Task :linkDebugFrameworkIos32
e: /Users/jamiecraane/develop/AndroidStudio/kotlin-native-gradle-samples/fat-framework/src/commonMain/kotlin/Api.kt: (3, 8): Unresolved reference: io
e: /Users/jamiecraane/develop/AndroidStudio/kotlin-native-gradle-samples/fat-framework/src/commonMain/kotlin/Api.kt: (6, 22): Unresolved reference: HttpClient

The dependencies of the ios32 variant could not be resolved. If we remove the ktor dependency the fat framework can be build. This minimal test project can be found here: https://github.com/jcraane/kotlin-native-gradle-samples/tree/master/fat-framework

Is this the correct way of configuring this or am I missing something?

Thanks!

**Comment by artdfel** [comment]
I managed to build successfully after adding 
```
configure(sourceSets.filter { it.name.startsWith("ios") }) {
        //dependsOn(sourceSets["commonMain"])
        dependencies {
            implementation("io.ktor:ktor-client-ios:1.2.4")
        }
    }
```
to the `build.gradle.kts`, just after the framework configuration. Please give it a try and tell if it won't help.

**Comment by jcraane** [comment]
Ik applied the changes you suggested but still getting the same error (executing "gradle clean build"). I have signed up to the Slack channel so I will post this question there.

**Comment by artdfel** [comment]
Oh, it looks like I was unclear in some aspect. This configure block got to be written after the 
```
    val ios32 = iosArm32("ios32")
    val ios64 = iosArm64("ios64")
    val iosSim = iosX64("iosSim")
```
section, not before. Source sets cannot be configured in your current script, as they do not exist yet.

**Comment by jcraane** [comment]
Yes, this seems to work, I can build the framework now!
