### ISSUE TITLE
How to do Multi-threaded task with GTK

### ISSUE THREAD

**Issue by kavanmevada** [JetBrains/kotlin-native#3519]
Almost every app require background processing without freezing main UI. I tried coroutine and gdk_thread_new, Nothing work for background processing in app.

- with coroutine it run task parallel if nothing c related inside it. So i can't integrate between c and kotlin code.

- with gdk_thread_new task execute in background but when i try to receive variable value i  crashes

Please provide more guidance about multi-threading.

**Comment by artdfel** [comment]
Hello!
 There is a [document](https://github.com/JetBrains/kotlin-native/blob/master/CONCURRENCY.md) on concurrent programming in the project. If I understand correctly, workers are the thing you're trying to find. Please give this approach a try, and feel free to ask for any help.
Also, when you are facing crashes, it's always good to share the details.

**Comment by kavanmevada** [comment]
`package sample

import kotlinx.cinterop.*
import libgtk3.*
import kotlin.native.concurrent.*


fun main(args: Array<String>) {

    val futures = arrayListOf<Future<Any>>()

    memScoped {
        val argc = alloc<IntVar>()
        argc.value = args.size
        val argv = alloc<CPointerVar<CPointerVar<ByteVar>>>()
        argv.value = args.map { it.cstr.ptr }.toCValues().ptr
        gtk_init(argc.ptr, argv.ptr)
    }

    val fraction = 0.0

    /* create a new window, set values */
    val window = gtk_window_new (GtkWindowType.GTK_WINDOW_TOPLEVEL)
    gtk_window_set_title (window?.reinterpret(), "Hello GTK+ World")
    /* set the size of the window */
    gtk_widget_set_size_request(window?.reinterpret(), 200, 200);
    /* connect the windows "destroy" event */
    g_signal_connect_object(window?.reinterpret(), "destroy",
        staticCFunction(::destroy_app).reinterpret(), null, 0u)

    val progress_bar = gtk_progress_bar_new()
    gtk_container_add(window?.reinterpret(), progress_bar)
    gtk_widget_show(progress_bar)

    gtk_progress_bar_set_fraction (progress_bar?.reinterpret(), fraction)

    /* set the window as visible */
    gtk_widget_show (window);


    futures.add(Worker.start().execute(TransferMode.SAFE, { "workers[0]" }) { input ->
        /* run the GTK+ main loop */
        gtk_main()
    })

    futures.add(Worker.start().execute(TransferMode.SAFE, { progress_bar }) { input ->
        (0 .. 10).forEach {
            g_usleep(1000000)
            val progress = it/10.toFloat()
            gtk_progress_bar_set_fraction(input?.reinterpret(), progress.toDouble())
        }

        Worker.start().execute(TransferMode.SAFE, { input }) { input ->
            (10 downTo 0).forEach {
                g_usleep(1000000)
                val progress = it/10.toFloat()
                gtk_progress_bar_set_fraction(input?.reinterpret(), progress.toDouble())
            }
            println("future2 ended !")
        }.consume { println(it) }

    })


    futures.forEach {
        it.consume { println(it) }
    }

}


fun destroy_app() {
    gtk_main_quit()
}
`

Workers works well in background and also update progress bar
Is this right way ?

**Comment by artdfel** [comment]
It seems fine to me.
I think we can close the issue if you managed to resolve your problem. For the future, I recommend you to join our official [Slack](http://slack.kotlinlang.org/?_ga=2.156041915.1066077704.1572246741-1089074657.1560174812), there is a lot of interesting discussions.

**Comment by kavanmevada** [comment]
When I try to call worker with g_signal_object worker implementation become complex. Any way of using coroutione launch or async ?

fun main(args: Array<String>) {
    
        runBlocking {
            launch {
                test1WithCoroutines()
            }
    
            launch {
                test2WithCoroutines()
            }
        }
    
    }
    
    suspend fun test1WithCoroutines() {
        println("Start Coroutines 1")
        delay(500)
        println("End Coroutines 1")
    }
    
    suspend fun test2WithCoroutines() {
        println("Start Coroutines 2")
        g_usleep(3000000)
        println("End Coroutines 2")
    }


Result :
Start Coroutines 1
Start Coroutines 2
End Coroutines 2
End Coroutines 1

when i pass any gtk blocking function it's not work. function execute in sequence instead of parallel

**Comment by artdfel** [comment]
I am not sure, that I understand you correctly. What kind of crash do you experience? Please report it with more details. 
Also, it's a lot easier to deal with a project, not a piece of code. If you want a help with Worker usage, you can look through the `workers` sample. Also, there were some articles by Kevin Galligan, [this one](https://touchlab.co/kotlin-native-stranger-threads-ep-1/) for example.

**Comment by kavanmevada** [comment]
@artdfel Worker work correctly but I wasn't able to get stable reference while in separate thread. looked lot about it finnally solved by `initRuntimeIfNeeded()`

Anyways I implemented own AsyncTask function for GTK


```
class AsyncTask<T, K>(input: T?, function: (T) -> K, function2: (T, K) -> Unit) {

    val functionAsInput = StableRef.create((input to function) to function2).asCPointer()

    val memoryAlloc = memScoped {
        alloc<pthread_tVar>() to alloc<COpaquePointerVar>()
    }

    val result get() = memoryAlloc.second

    init {
        pthread_create(memoryAlloc.first.ptr, null, staticCFunction { pointer: COpaquePointer ->
            initRuntimeIfNeeded()

            val inputPair
                    = pointer.asStableRef<Pair<Pair<T, (T) -> K>, (Pair<T, K>) -> Unit>>().get()

            val result = inputPair.first.second(inputPair.first.first)

            val passDataToUi = StableRef.create((inputPair.first.first to result) to inputPair.second).asCPointer()

            gdk_threads_add_idle(staticCFunction { pointer: COpaquePointer ->

                val inputPair2
                        = pointer.asStableRef<Pair<Pair<T, K>, (T, K) -> Unit>>().get()


                inputPair2.second(inputPair2.first.first, inputPair2.first.second)

                null as COpaquePointer?
            }.reinterpret(), passDataToUi)

            return@staticCFunction StableRef.create(result as Any).asCPointer()

        }.reinterpret(), functionAsInput)
    }
}

```
