### ISSUE TITLE
Bridging between NSData and CFDataRef

### ISSUE THREAD

**Issue by cody1024d** [JetBrains/kotlin-native#3524]
Hello,

Another quick question as I dive deeper into my usecase.

I am currently trying to accept a self-signed cert for a server, and thus have overwritten the method

```
fun URLSession(
        session: NSURLSession, didReceiveChallenge: NSURLAuthenticationChallenge,
        completionHandler: (NSURLSessionAuthChallengeDisposition, NSURLCredential?) -> Unit
    )
```

Eventually, I end up trying to parse the remote certificate, and end up with a pointer to some CFData (CFDataRef is it's type alias).  Now that I have CFData, in the Swift world, I could cast this to NSData, and go on my way.  However, Kotlin does not like this cast, and ends up throwing an exception.  Is there any bridging available between NSData and CFDataRef?

I'd even be ok with going from NSData to CFData, and comparing it to the CFData from the CFDataRef.

Fore more concrete information, specifically, I'm calling to SecTrustGetCertificateAtIndex, and comparing it to NSData of a self-signed cert held locally.

**Comment by artdfel** [comment]
Hello! I suppose you're trying to find something like in this Slack [discussion](https://kotlinlang.slack.com/archives/C3SGXARS6/p1571947160170500) (I recommend to join the Slack if you already didn't :-) ). In two words, you should use [CFBridgingRelease](https://developer.apple.com/documentation/foundation/1587932-cfbridgingrelease) for casts like that.

**Comment by cody1024d** [comment]
Hello again @artdfel! :)

Thank you for the solution!

I will join the slack now.  It is much better ace for quick questions like this.  Sorry for spamming the issues.
