### ISSUE TITLE
Object classes with inheritance (instantiated multiple times)

### ISSUE THREAD

**Issue by AndreasMattsson** [JetBrains/kotlin-native#3525]
Steps to reproduce:
1. Check out this single-commit fork of master, modifying the Cocoapods sample:
https://github.com/AndreasMattsson/kotlin-native/commit/dc70a8cade78e6c8194ee9eb9cd294bc9f8dcf55
2. Run the ios app and observe the printed output.

e.g.

> State Test
StateTest init
State Random inherited instance val 1: 486183893
StateTest init
State Random inherited instance val 2: -229446675
StateTest init
State Random inherited instance lazy 1: -1434534466
StateTest init
State Random inherited instance lazy 2: 1847758197
StateTest init
State Random file val 1: -1751854446
StateTest init
State Random file val 2: -1751854446
StateTest init
State Random file lazy 1: 1950481871
StateTest init
State Random file lazy 2: 1950481871
StateTest.IndependentSingleton init
State Random independent val 1: -1186721552
State Random independent val 2: -1186721552
State Random independent lazy 1: -1858185365
State Random independent lazy 2: -1858185365

The differs from the expected behavior in that StateTest init is apparently run once for each access of `InheritingSingleton` rather than providing singleton-like access. It also appears that the init block of `InheritingSingleton` itself is never called. I would expect all pairwise ("1: " / "2:" ) logs here to print the same value, but this breaks down for the case of the object that inherits from StateTest.

For comparison, these are log outputs from doing equivalent calls on JVM:
> State Test
StateTest init
StateTest.InheritingSingleton init
State Random inherited instance val 1: -14155247
State Random inherited instance val 2: -14155247
State Random inherited instance lazy 1: -1793673803
State Random inherited instance lazy 2: -1793673803
State Random file val 1: -483920171
State Random file val 2: -483920171
State Random file lazy 1: -1570839155
State Random file lazy 2: -1570839155
StateTest.IndependentSingleton init
State Random independent val 1: -883005959
State Random independent val 2: -883005959
State Random independent lazy 1: -1287948357
State Random independent lazy 2: -1287948357

Here the StateTest init block is only called once (multiple times on iOS). InheritingSingleton init is also called once (never on iOS). And the pairwise logs all show the same numbers (showing that the random number is only generated once for each val).

**Comment by AndreasMattsson** [comment]
For reference, when running/testing this I commented out `org.jetbrains.kotlin.native.home=../../../dist
` in `gradle.properties`, and as such was running with the default 1.3.50 version, rather than a locally built master.

**Comment by SvyatoslavScherbina** [comment]
Thanks, confirmed.
This behaviour looks much like Swift bug, I've reported it here: https://bugs.swift.org/browse/SR-11686

**Comment by AndreasMattsson** [comment]
@SvyatoslavScherbina Interesting, thank you for looking into it.

Are you aware of any workaround I can do on the Swift/iOS side in order to access "StateTest.InheritingSingleton" (or other objects declared similarly) with expected Singleton semantics? Or would I have to initialize through other means on the KN/multiplatform side and pass an explicit reference through other means? (it feels more icky to have to pollute my cross-platform kotlin code to work around a swift bug than it would be to introduce a temporary hack on the swift/ios side)

**Comment by SvyatoslavScherbina** [comment]
#3528 generally workarounds Swift compiler bug and thus fixes this issue. We plan to include it into 1.3.60.

> Are you aware of any workaround I can do on the Swift/iOS side in order to access "StateTest.InheritingSingleton" (or other objects declared similarly) with expected Singleton semantics?

You can add any parameter to `StateTest` constructor to workaround the issue, e.g.
```kotlin
open class StateTest(ignore: Int) {
    // ...
    object InheritingSingleton : StateTest(0) {
    // ...
}
```

**Comment by AndreasMattsson** [comment]
@SvyatoslavScherbina Thank you! Good to know!
