### ISSUE TITLE
iOS: debug and release builds mismatching

### ISSUE THREAD

**Issue by franmowinckel** [JetBrains/kotlin-native#3531]
I'm using the multiplatform plugin `1.3.50` with a setting (mainly the build gradle file) like the one described here: https://play.kotlinlang.org/hands-on/Targeting%20iOS%20and%20Android%20with%20Kotlin%20Multiplatform/03_CreatingSharedCode

That produces 2 frameworks:
- build/bin/ios
  -debugFramework
    MyFramework.framework
    MyFramework.framework.dSYM
  -releaseFramework
    MyFramework.framework

And the framework contains the binary (in this case it would be `MyFramework.framework/MyFramework`)

The thing is that I was wondering why the release one didn't contain the dSYM (see: https://github.com/JetBrains/kotlin-native/issues/2422). But then I also noticed that the binary in the debug one was smaller than the one in the release one... ??

am I missing something or are the frameworks swapped?

**Comment by olonho** [comment]
Release build contains full bitcode for AppStore upload, debug doesn't.

**Comment by franmowinckel** [comment]
Thanks! Yep, that makes total sense! so I guess that the related issue can also be closed, since you can get the dSYMs from Apple Store right?
