### ISSUE TITLE
Add support for resources for Frameworks

### ISSUE THREAD

**Issue by idstein** [JetBrains/kotlin-native#3539]
We have a large multi-module Kotlin Native project running for Android, iOS and JVM. However, we struggle to get a convenient way to copy resources to created test executables or frameworks. 

For Android AAR and JVM JARs there exists defined ways how to ship resources in Gradle, but for iOS we have to declare complex copy tasks that involve resolving transitive dependencies.

Can you add support to ship resources via KLIb and ultimately build frameworks with bundled resources?

**Comment by olonho** [comment]
Practically speaking nothing prevents putting anything in klib (it's just a zip archive) and using it in other parts of the build. But it probably better be designed in combination with Gradle DSL support.

**Comment by ilmat192** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-39194.

**Comment by ilmat192** [comment]
UPD: Moved use cases described here into separate tickets from [KT-39194](https://youtrack.jetbrains.com/issue/KT-39194):
[KT-42418](https://youtrack.jetbrains.com/issue/KT-42418) - Embedding resources to frameworks
[KT-37818](https://youtrack.jetbrains.com/issue/KT-37818) - Support for resources in test runs.
