### ISSUE TITLE
cinerop:platform: non-transitive variant of excludedFunctions

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3540]
I tried to exclude from `platform.posix` all functions not listed in POSIX-2004 document.
Big list, but doable.

But then - I asume if include same headers in `platform.linux` (or `darwin`) , that depends on posix - it should not include functions from `posix`, but include everything excluded from `posix`.

Really - it does not contain both, seems that `excludedFunctions` is transitive.

PS And maybe in this usecase even better would be non-transitive white-list.

PPS Well, white-list is already there :)
Just set `headerFilter` to empty and copy-paste function definitions after `---`

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48077, closing.
