### ISSUE TITLE
compile opengl from scratch using msys64 getting error

### ISSUE THREAD

**Issue by dickensas** [JetBrains/kotlin-native#3564]
Unresolved reference: __builtin_va_list

opengl32.klib-build\kotlin\opengl32\opengl32.kt: (33, 25): Unresolved reference: __builtin_va_list

The opengl headers are inter oped to kotlin file

in the top I see

import platform.builtin.__builtin_va_list

this fails in windows 10 msys64

**Comment by artdfel** [comment]
Please reveal more details on your use-case - what you are trying to do, what `kotlin-native` version is being used, etc. Also, it would be nice to have an example project, that helps to reproduce this behavior.

**Comment by dickensas** [comment]
@artdfel sure I will create an app for this issue
please find the DEF file below

headers = GL/gl.h GL/glext.h
staticLibraries = libopengl32.a
package = opengl32
libraryPaths = c:/msys64/mingw64/x86_64-w64-mingw32/lib c:/msys64/mingw64/lib
compilerOpts = -DUNICODE
linkerOpts = -lopengl32

nothing else I do, I simply compile the gradle project 
with kotlin multiplatform version 1.3.70-dev-1436

the generated opengl32.kt itself has this line at line number 30
import platform.builtin.__builtin_va_list

**Comment by olonho** [comment]
Why cannot you use opengl Kotlin platform libraries.

**Comment by dickensas** [comment]
Hi @olonho 

if I put in my code

import platform.opengl32.*

it does not have methods related to opengl shader and many methods are missing
most of the methods in glext.h is missing

that is why I wanted to cinterop it from scratch, so that I can use all those missing methods

**Comment by olonho** [comment]
Why do you believe that reimport will add missing methods?

**Comment by dickensas** [comment]
I switched to GLEW and GLFW as a workaround

**Comment by dickensas** [comment]
closing the issue, the headerFilter removes the error and missing methods can be solved using macro or switching the GLEW or GLAD
