### ISSUE TITLE
cinterop makes all function nullable - leads to ugly code

### ISSUE THREAD

**Issue by dickensas** [JetBrains/kotlin-native#3567]
I used cinterop on GLEW and GLFW
I successfully completed the code, and it works perfectly, but
all the methods throws null safe call error while compiling, 
which leads slightly ugly code

C Code
--------
unsigned int pId;
pId = glCreateProgram();
glAttachShader(pId, vsId);
glAttachShader(pId, fsId);
glLinkProgram(pId);

glDeleteShader(vsId);
glDeleteShader(fsId);

Kotlin Code
-------------
val pId = glCreateProgram!!()
        
glAttachShader!!(pId.toUInt(), vsId.toUInt())
glAttachShader!!(pId.toUInt(), fsId.toUInt())
glLinkProgram!!(pId)

glDeleteShader!!(vsId.toUInt())
glDeleteShader!!(fsId.toUInt())

if I am going to put "!!" for all method calls, then the code will look ugly
also the type infer looks ugly

but the code perfectly works

Kotlin version: 1.3.70-dev-1231-17

**Comment by olonho** [comment]
Those are not functions, but global variables which can potentially store null value, thus nullability check is required.

**Comment by msink** [comment]
AFAIK global variables are frozen, so how they can change?
