### ISSUE TITLE
Could not find klib when depending on empty module

### ISSUE THREAD

**Issue by sellmair** [JetBrains/kotlin-native#3572]
Compiling in a multi-module Gradle project will fail with something like

```
> Task :synthetic:compileKotlinIos FAILED
e: Could not find "/Users/sellmair/Sources/qbs/engine-android/image_processing/build/classes/kotlin/ios/main/image_processing.klib" in [/Users/sellmair/Sources/qbs/engine-android, /Users/sellmair/.konan/klib, /Users/sellmair/.konan/kotlin-native-macos-1.3.60/klib/common, /Users/sellmair/.konan/kotlin-native-macos-1.3.60/klib/platform/ios_x64].
```

If the module dependency does not contain any sources for iOS (empty iosMain, empty commonMain). Such modules can still be used to proxy a set of other dependencies, OR when converting existing projects from JVN/Android only to multiplatform. 

This probably happens, because of the multiplatform plugin seeing no sources for the iOS module and therefore skipping the creation of the klib file. The depending module will then complain about this missing file.

**Comment by sellmair** [comment]
Current workaround: Put at least one dummy Kotlin class into commonMain or your corresponding nativeMain

**Comment by ilmat192** [comment]
Duplicated by https://github.com/JetBrains/kotlin-native/issues/2617. Fixed by https://github.com/JetBrains/kotlin/commit/df46dfc63de6d3192d4514015ad3d960de4b2469.
