### ISSUE TITLE
The target 'android' already exists

### ISSUE THREAD

**Issue by River418** [JetBrains/kotlin-native#3573]
kotlin_version:1.3.50 for `org.jetbrains.kotlin:kotlin-gradle-plugin`
I want to import Android API in the multiplatform library, so i edit the library build.gradle.kts like this:

      import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

      plugins {
        kotlin("multiplatform")
        id("com.android.library")
        id("kotlin-android-extensions")
     }

     android {
       compileSdkVersion(29)
       buildToolsVersion("29.0.2")
       defaultConfig {
          minSdkVersion(19)
          targetSdkVersion(29)
          versionCode = 1
          versionName = "1.0"
          testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
     }
     sourceSets {
        getByName("main").manifest.srcFile(project.projectDir.path + "/src/androidMain/AndroidManifest.xml")
        getByName("main").res.srcDirs(project.projectDir.path + "/src/androidMain/res/")
     }
     buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            }
        }
     }

    kotlin {
       val iOSTarget: (String, KotlinNativeTarget.() -> Unit) -> KotlinNativeTarget =
        if (System.getenv("SDK_NAME")?.startsWith("iphoneos") == true)
            ::iosArm64
        else
            ::iosX64

    iOSTarget("ios") {
        binaries {
            framework {
                baseName = "SharedCode"
            }
        }
    }

    android()
    //jvm("android")

    sourceSets["commonMain"].dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-common")
    }

    sourceSets["androidMain"].dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib")
     }
    }

    val packForXcode by tasks.creating(Sync::class) {
    val targetDir = File(buildDir, "xcode-frameworks")

    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val framework = kotlin.targets
        .getByName<KotlinNativeTarget>("ios")
        .binaries.getFramework(mode)
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)

    from({ framework.outputDirectory })
    into(targetDir)

    doLast {
        val gradlew = File(targetDir, "gradlew")
        gradlew.writeText("#!/bin/bash\n"
                + "export 'JAVA_HOME=${System.getProperty("java.home")}'\n"
                + "cd '${rootProject.rootDir}'\n"
                + "./gradlew \$@\n")
        gradlew.setExecutable(true)
       }
    }
    tasks.getByName("build").dependsOn(packForXcode)

sync gradle with this error:
`The target 'android' already exists, but it was not created with the 'jvm' preset. To configure it, access it by name in `kotlin.targets` or use the preset function 'android'. `

**Comment by h0tk3y** [comment]
This is the expected behavior when you create a target as `android()` and access it as `jvm("android")`, but I can only see on commented occurrence of the latter. Are you accessing the target as `jvm("android")` from some other script? You can try to run the build with `--stacktrace` and see which of your build scripts causes that.

**Comment by River418** [comment]
> This is the expected behavior when you create a target as `android()` and access it as `jvm("android")`, but I can only see one commented occurrence of the latter. Are you accessing the target as `jvm("android")` from some other script? You can try to run the build with `--stacktrace` and see which of your build scripts causes that.

I think this  error is a cache bug of Android Studio~because I opened this project in IntelliJ, everything goes fine~thansk for the reply

**Comment by Takhion** [comment]
ah @River418 also keep in mind that sometimes the order of the plugins matters, and generally the Android one likes to be applied before the Kotlin one:
```kotlin
id("com.android.library")
kotlin("multiplatform")
```

**Comment by River418** [comment]
> ah @River418 also keep in mind that sometimes the order of the plugins matters, and generally the Android one likes to be applied before the Kotlin one:
> 
> ```kotlin
> id("com.android.library")
> kotlin("multiplatform")
> ```

yeah，I tried edit the plugin order like what u suggested~it seems work in Android Studio now~Thanks a lot
