### ISSUE TITLE
apply plugin for konan plugin

### ISSUE THREAD

**Issue by dickensas** [JetBrains/kotlin-native#3580]
what is the KTS syntax for below gradle plugin

apply plugin: 'konan'

I tried

plugins {
     id("org.jetbrains.kotlin.konan")
}

no luck

**Comment by artdfel** [comment]
I'm almost sure that this plugin is not available for users, currently, the `kotlin-multiplatform` [should](https://github.com/JetBrains/kotlin-native/issues/2669) be used.  It is not being published starting from [this commit](https://github.com/JetBrains/kotlin-native/commit/08074ad9369257abfe4f8cb9f6a0570ba50331e1#diff-5176ebdf1fae3e45d74ca41e3135198d), and only used as an internal tool. Why do you prefer to apply it?

**Comment by dickensas** [comment]
I was not sure, I simply want to know the DSL version
