### ISSUE TITLE
Can we disable mutability checks?

### ISSUE THREAD

**Issue by DTHeaven** [JetBrains/kotlin-native#3582]
It's very inconvenient use current thread model with old projects.
Is it possible fallback to classical thread-oriented concurrency model?

**Comment by artdfel** [comment]
Please clarify, what kind of problems do you have?

**Comment by petrukhnov** [comment]
In old projects (probably pre kn 0.8 if i recall correctly) it was possible create Kotlin object in Swift, pass it to Kotlin function, and then get it back with some of its fields updated, and then pass to other threads in Swift side. 
It was up to the developer to ensure that 2 threads don't try to modify objects at the same time (or there was a crash).

Now it is not possible to create Kotlin object and pass it to some other thread in Swift. There is no guides how to achieve similar flexibility with latest Kotlin versions. Developers have to try different workarounds like:
- wrap all Kotlin calls (including instantination of every Kotlin object) inside some dedicated thread in iOS
- use ObjectiveC classes to communicate between Swift and Kotlin
- use some cpointers (there is no examples what does it mean, besides few lines in api)


What people are looking for is to be able to use Kotlin in Swift code, same way as they use other libraries:
```
myNiceSwiftFunction() {
  let someData = MyKotlinClass()
  DispatchQueue.global(qos: .background).async {
    MyCalculatorKotlinClass.calculate(someData) // which will update some fields in someData
    DispatchQueue.main.async {
      someData.setFieldX(5)
      UiView.updateButton(someData)
    }
  }
}
```

**Comment by olonho** [comment]
No, it was never possible to do that correctly, it was just a missing check. What prevents you from sharing Swift object this way?

**Comment by petrukhnov** [comment]
> What prevents you from sharing Swift object this way?
The fact, that it will not be part of the Kotlin library, and that object can't be used in library internal code (business logic).

My intent was not to discuss how kotlin handle mutability, but it was attempt to explain what @DTHeaven probably means. I saw many of such complaints during this year.

**Comment by SvyatoslavScherbina** [comment]
Closing as answered.
See also: https://blog.jetbrains.com/kotlin/2020/07/kotlin-native-memory-management-roadmap/
