### ISSUE TITLE
Question: When is kotlin native going out of alpha?

### ISSUE THREAD

**Issue by mikezliu** [JetBrains/kotlin-native#3583]
2 years? 5 years? Never? Thanks

P.S. it's a question from my manager

**Comment by olonho** [comment]
It's definitely not in alpha at the moment, so you'd better clarify exact scope of the question. What kind of feature/behavior/guarantees which you're asking about?

**Comment by mikezliu** [comment]
I'm wondering approximately when we should be able to use kotlin native in a production app. I've been using it for a side project so far but hesitant about using it for new projects at work.

One of the issue I'm waiting to be addressed is better multi-threading support. In particular, using KN objects / view models across different threads from swift/objc code.

**Comment by olonho** [comment]
Many people already use it in production, and nothing prevents you from doing that as well. One could use K/N objects from multiple threads, including Swift/Objective-C as long as there's single owner or when object is frozen. Generally, please do not mix lack of API artifact format stability (what makes K/N formally "Moving Fast" per https://kotlinlang.org/docs/reference/evolution/components-stability.html) and production readiness of the compiler and the runtime. And even more stable APIs may have not exactly JVM concurrency model, but it makes runtime *more* production ready, not less, as concurrency-related bugs are harder to make and easier to track.
