### ISSUE TITLE
Fresh MacOS kotlin native project build fails without XCode installed

### ISSUE THREAD

**Issue by PatrickLemke** [JetBrains/kotlin-native#3587]
MacOS Version: 10.15.1
Kotlin Multiplatform Gradle Plugin Version: 1.3.60

When creating a fresh Kotlin native multiplatform project on MacOS I get this error when trying to build it for the frist time for the MacOS target: 
```
e: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /usr/bin/xcrun command returned non-zero exit code: 72.
```

When installing XCode, the error went away. Maybe there is a more intuitive way to display this error message.

**Comment by artdfel** [comment]
Closing, the fix should be available with `1.3.70` release.
