### ISSUE TITLE
Unresolved references on imported packages in iosMain after upgrade to Kotlin 1.3.60

### ISSUE THREAD

**Issue by ojaynico** [JetBrains/kotlin-native#3589]
![Screen Shot 2019-11-19 at 2 11 53 AM](https://user-images.githubusercontent.com/10561216/69101915-f965c500-0a71-11ea-877e-baa080bee4e0.png)

**Comment by artdfel** [comment]
Check if there is a Ktor release compatible with Kotlin 1.3.60. Usually, libraries and frameworks release in a couple of days after the language release - they got to be built and published, etc. Please wait for a while, and ping here if it won't change.

**Comment by ojaynico** [comment]
@artdfel , the errors have been resolved after upgrading my ktor version (for all clients) from 1.2.5 to 1.2.6.
Thanks.
