### ISSUE TITLE
[Multiplatform] K/N 1.3.31 vs 1.3.41+ iOS Memory Leaks? 

### ISSUE THREAD

**Issue by nuno-vieira** [JetBrains/kotlin-native#3595]
Hi, I've been using Multiplatform in a project and noticed something that is worrying me. After analysing the Memory Graph in Xcode, I found that in Kotlin Native 1.3.41 version, all the objects created in the iOS Project seem to not be released. I've tested this in the [Multiplatform Sample App](https://github.com/Kotlin/mpp-example), and compared creating multiple objects using the sample app with 1.3.31 vs 1.3.41.

### MPP Sample app with 1.3.31
Added this code in `viewDidLoad()` of `ViewController`: 
```Swift
(0...2000).forEach { _ in
     _ = Calculator()
 }
```
The memory graph shows, no `Calculator` instance:
![image](https://user-images.githubusercontent.com/12814114/69290702-a4a08680-0bf8-11ea-9d4a-9719f5f8a831.png)

### MPP Sample app with 1.3.41
Added this code in `viewDidLoad()` of `ViewController`: 
```Swift
(0...2000).forEach { _ in
     _ = Calculator()
 }
```
The memory graph shows, 2001 `Calculator` instances:
![image](https://user-images.githubusercontent.com/12814114/69290894-4627d800-0bf9-11ea-8d11-854b9a16e7e6.png)

Is this related to the new Memory Model changes? Is this expected? The `Calculator` is not even referenced anywhere, the `ViewController` doesn't hold it. 

I've tried also with 10k instances, and it looks some are cleaned. But is this desirable? And efficient? 

Test with 10k:
```Swift
(0...10_000).forEach { _ in
     _ = Calculator()
 }
```
Result: 
![image](https://user-images.githubusercontent.com/12814114/69290982-a0c13400-0bf9-11ea-9402-09476fbfe0c1.png)

So it looks that in this case, GC has done some work.

**Comment by olonho** [comment]
Yes, reference processing is delayed, if you need to force reference collection - run GC.collect.

**Comment by nuno-vieira** [comment]
@olonho Hi! Thank you for the quick response. How do I use that? Some special import is needed?

**Comment by nuno-vieira** [comment]
Thank you for the quick response @olonho. Will do that 👍

After taking a look at the GC, I have some questions, just for curiosity:
```Kotlin
    /**
     * GC threshold, controlling how frequenly GC is activated, and how much time GC
     * takes. Bigger values lead to longer GC pauses, but less GCs.
     */
    var threshold: Int
        get() = getThreshold()
        set(value) = setThreshold(value)
    @SymbolName("Kotlin_native_internal_GC_getThreshold")
    private external fun getThreshold(): Int
    @SymbolName("Kotlin_native_internal_GC_setThreshold")
    private external fun setThreshold(value: Int)
```

The Threshold is time based, so don't understand why then the GC did collect instances for the 10k's case. Something that I'm missing? Or is any other reason GC can collect? 

Also is this `value: Int` what unit of time?

**Comment by mikezliu** [comment]
I'm hitting a similar issue on Kotlin native 1.3.50. However I'm having trouble using the GC object in my native kotlin native code - seems like it fails to resolve.

I tried:
```
import kotlin.native.internal
import kotlin.native.*
```

But GC.collect says that GC is an unresolved reference

**Comment by artdfel** [comment]
Hello @mikezliu! Please try to call it like it's done [here](https://github.com/JetBrains/kotlin-native/blob/master/backend.native/tests/runtime/memory/only_gc.kt).

**Comment by mikezliu** [comment]
Thanks! I’ll give it a try

**Comment by sky-filipeuva** [comment]
I just want to inquire on why reference collection is delayed from versions superior to 1.3.31. Is this in some way connected to the upcoming update on KN multithreading model ?

**Comment by olonho** [comment]
This is performance optimization to avoid refcounting associated with stack slots updates.

**Comment by dhoskins** [comment]
> Yes, reference processing is delayed, if you need to force reference collection - run GC.collect.

I tried this and ran into `runtime assert: Recursive GC is disallowed` error, this happened when it was done from a `deinit` that happened as a result of a scheduled GC. Any way to ensure GC.collect is done safely?

**Comment by nikolaykasyanov** [comment]
@olonho I wonder if GC will be triggered upon getting an iOS memory warning notification?

**Comment by olonho** [comment]
There's no correlation, but nothing prevents you from doing that at the suitable moment.

**Comment by nikolaykasyanov** [comment]
@olonho thanks for answering. I'd argue that there actually is correlation as one would want to clean up as much memory as possible if such a notification comes. I realize though that doing this by default is probably not the best idea.
