### ISSUE TITLE
Can't add submodule cinterops

### ISSUE THREAD

**Issue by artemsivcev** [JetBrains/kotlin-native#3600]
I'm successfully added FirebaseMLVision, but this still need common lib.

Build.gradle:
```
        configure([targets.iosX64,
                   targets.iosArm64
        ]) {
            compilations.main.source(sourceSets.iosMain)
            compilations.test.source(sourceSets.iosTest)
            compilations["main"].cinterops {
...
                FirebaseMLVision {
                    packageName 'cocoapods.FirebaseMLVision'
                    defFile = file("$projectDir/src/iosMain/c_interop/FirebaseMLVision.def")
                    includeDirs("$projectDir/../ios_test/Pods/FirebaseMLVision", "$projectDir/../ios_test/Pods/FirebaseMLCommon")
                    compilerOpts("-F$projectDir/src/iosMain/c_interop/modules/FirebaseMLVision-${versions.firebaseMLVisionIos}")
                }
                FirebaseMLVisionTextModel {
                    packageName 'cocoapods.FirebaseMLVisionTextModel'
                    defFile = file("$projectDir/src/iosMain/c_interop/FirebaseMLVisionTextModel.def")
                    includeDirs("$projectDir/../ios_test/Pods/FirebaseMLVision")
                    compilerOpts("-F$projectDir/src/iosMain/c_interop/modules/FirebaseMLVisionTextModel-${versions.firebaseMLVisionTextModelIos}")
                }
...
```

And an error:
```
Exception in thread "main" java.lang.Error: /Users/User/Documents/multiplatform/lib/src/iosMain/c_interop/modules/FirebaseMLVisionTextModel-0.19.0/FirebaseMLVisionTextModel.framework/Modules/module.modulemap:3:10: error: inferred submodules require a module with an umbrella
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:146)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:67)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:13)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:359)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:220)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:38)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:69)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dx-ocr-lib:cinteropFirebaseMLVisionTextModelIosArm64'.
> Process 'command '/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home/bin/java'' finished with non-zero exit value 1

```

Some one see this before? I think it's because FirebaseMLVisionTextModel didn't have any headers. How can I compile this framework then?

**Comment by artemsivcev** [comment]
I see this error because FirebaseMLVisionTextModel didnt have "umbrella header" in module.modulemap. How can I resolve it in Kotlin?

**Comment by artemsivcev** [comment]
I added empty headers to framework and it's successfully compile. But I think thats no gona work

**Comment by artdfel** [comment]
Please extend the report with `.def` files contents.

**Comment by artemsivcev** [comment]
> Please extend the report with `.def` files contents.

FirebaseMLVision.def
```
language = Objective-C
modules = FirebaseMLVision
compilerOpts = -framework FirebaseMLVision
linkerOpts = -framework FirebaseMLVision
```

FirebaseMLVisionTextModel.def
```
language = Objective-C
modules = FirebaseMLVisionTextModel
compilerOpts = -framework FirebaseMLVisionTextModel
linkerOpts = -framework FirebaseMLVisionTextModel
```

**Comment by SvyatoslavScherbina** [comment]
Actually `FirebaseMLVisionTextModel.framework` is not importable neither to Swift nor to Objective-C (with `@import`). For example,
```swift
import FirebaseMLVisionTextModel
```
can't be compiled with Swift compiler, which would report the same "inferred submodules require a module with an umbrella" error.

In other word, it doesn't provide a correct module. That's why it can't be handled by `cinterop` with `modules =` in `.def` file.

**Comment by artemsivcev** [comment]
Ok, but how can I compile it in my multiplatform lib anyway?

**Comment by artemsivcev** [comment]
Just del language and module sections? Thats it? Not be so ez...

**Comment by SvyatoslavScherbina** [comment]
You don't need processing `FirebaseMLVisionTextModel` with `cinterop` because it doesn't contain any public API. You can discover this fact by looking inside `FirebaseMLVisionTextModel.framework`: it lacks both `Headers` directory and Swift modules.

**Comment by artemsivcev** [comment]
Then I don't understand how to add this framework to my project. Without it FirebaseMLVision didn't recognise anything. Any ideas?

**Comment by SvyatoslavScherbina** [comment]
It should be enough to make your binary link with this framework. This can be achieved in different ways. The simplest one is probably to add `-framework FirebaseMLVisionTextModel` to `linkerOpts` in `FirebaseMLVision.def`.

**Comment by artemsivcev** [comment]
Hmmm... It's not so clear, but I try it out. Thx!

**Comment by ilmat192** [comment]
@artemsivcev, did the approach with `-framework FirebaseMLVisionTextModel` in `linkerOpts` help you? Could we close the issue?

**Comment by ilmat192** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue  as answered. If you still have some reports/questions, feel free to [open an issue in YoutTrack](https://kotl.in/issue) or ask us in [Slack](https://kotlinlang.slack.com/channels/kotlin-native).
