### ISSUE TITLE
Memory leak when using kotlin native in iOS extension

### ISSUE THREAD

**Issue by mikezliu** [JetBrains/kotlin-native#3601]
Hi,

I seem to be running into a memory leak when using kotlin native in an iOS today notification center widget. I narrowed down the issue to as follows:

In Kotlin Native, I defined a class and an interface:
```
class ApiManager(val dataManager: SharedDataManager) { }
```
```
interface SharedDataManager { }
```

On iOS, I implemented the data manager and pass it through to the ApiManager:

```
class AppDataManager: NSObject, SharedDataManager {
    deinit {
        print("deinit AppDataManager")
    }
}
```
```
class AppComponent {
  let dataManager: AppDataManager
  let apiManager: ApiManager

  override init() {
    self.dataManager = AppDataManager()
    self.apiManager = ApiManager(dataManager: self.dataManager)
  }

   deinit {
        print("deinit AppComponent")
   }
}
```

AppComponent is initialized in the extension view controller, like this:
```
class WidgetViewController: UIViewController, NCWidgetProviding {
  let appComponent: WidgetAppComponent
  init() {
    self.appComponent = AppComponent()
  }
}
```

Now when I run this code and close the extension (swipe away from the today notification center), I see on console output:
```
deinit AppComponent
```

But not 'deinit AppDataManager'.  Seems ApiManager (kotlin native world) has a reference on AppDataManager.

When I comment out this line above:
```
self.apiManager = ApiManager(dataManager: self.dataManager)
```
And then run the app, I see on console output:
```
deinit AppComponent
deinit AppDataManager
```

When looking at iOS debugger, memory for the extension keeps increasing until it crashes. Sometimes deinit AppDataManager happens after I re-open the extension 5-6 times, sometimes the extension just runs out of memory first and crashes.

I'm running Kotlin Native 1.3.50. Not sure if I saw this issue on 1.3.21 (I didn't get reports of this issue until the last month when I updated to 1.3.50)

**Comment by nuno-vieira** [comment]
This seems to be related with: https://github.com/JetBrains/kotlin-native/issues/3595, and it looks this is expected, because of the Memory Management changes introduced in 1.3.40+ versions.

**Comment by mikezliu** [comment]
Is there any way to manually GC?  It seems that class is internal. For widget this is a pretty big issue because the OS kills it after 10-20MB

**Comment by mikezliu** [comment]
Per other thread, I ended up using kotlin.native.internal.GC.collect()

**Comment by mikezliu** [comment]
Does GC.collect run asynchronously? I noticed that even when I call this from iOS extensions, it doesn't always run (perhaps it doesn't have enough time before the extension is frozen? I need to find out more about how extensions work)

**Comment by olonho** [comment]
GC.collect run synchronously on current thread/worker only.

**Comment by mikezliu** [comment]
It would be good if there’s some way to set an upper memory limit to trigger GC. iOS extensions typically have around 10-30MB mem limit before being silently killed by OS. So my current workaround looks pretty bad in code (lots of manual GC collect at different checkpoints).

**Comment by olonho** [comment]
You can fine tune GC thresholds, see https://github.com/JetBrains/kotlin-native/blob/be6722d44ad801fcfb9bd8929ebcafe568c6fcc6/runtime/src/main/kotlin/kotlin/native/internal/GC.kt#L62

**Comment by mikezliu** [comment]
I looked at the doc in GC.kt but I'm not sure what threshold means. Is it seconds, milliseconds, kb, MB, or something else?

**Comment by artdfel** [comment]
Hey @mikezliu! I'd recommend you to have a look at some parts of the `Memory.cpp`, links below. According to [this](https://github.com/JetBrains/kotlin-native/blob/bcfd837363626f37cb906f5c77122019b00325bb/runtime/src/main/cpp/Memory.cpp#L423) code, the threshold here is the number of cycle candidates on what GC got started. By default, it is set to [8*1024](https://github.com/JetBrains/kotlin-native/blob/bcfd837363626f37cb906f5c77122019b00325bb/runtime/src/main/cpp/Memory.cpp#L75).The structure is thread-local, so it [seems](https://github.com/JetBrains/kotlin-native/blob/bcfd837363626f37cb906f5c77122019b00325bb/runtime/src/main/cpp/Memory.cpp#L2867) applying `setThreshold(...)` only to the current thread.
Also, I got to mention that those details are rapidly changing, so one shouldn't rely on my explanation too heavily😅.

**Comment by SvyatoslavScherbina** [comment]
Closing as answered.
