### ISSUE TITLE
type CValue<NVGcolor> of return value is not supported here: not a structure or too complex

### ISSUE THREAD

**Issue by se1by** [JetBrains/kotlin-native#3609]
I tried to use [nanovg](https://github.com/memononen/nanovg) and get the error above with the following line of code: 
```kotlin
val color = nvgRGBA(255, 192, 0, 255)
``` 

The [NVGColor struct](https://github.com/memononen/nanovg/blob/master/src/nanovg.h#L35) is defined as followed:
```C
struct NVGcolor {
    union {
        float rgba[4];
        struct {
            float r,g,b,a;
        };
    };
};
```

The [nvgRGBA function](https://github.com/memononen/nanovg/blob/master/src/nanovg.c#L431) looks like this:
```C
NVGcolor nvgRGBA(unsigned char r, unsigned char g, unsigned char b, unsigned char a)
{
	NVGcolor color;
	// Use longer initialization to suppress warning.
	color.r = r / 255.0f;
	color.g = g / 255.0f;
	color.b = b / 255.0f;
	color.a = a / 255.0f;
	return color;
}
```

Could you shed some light on what is going wrong and how I could circumvent it?

//Edit:
I was able to circumvent this by creating an intermediate function in the def file that takes an NVGcolor pointer and calls the real function with the derefenced color:

```C
static void nvgFillColorPtr(NVGcontext* context, NVGcolor* nvgColor) {
    nvgFillColor(context, *nvgColor);
}
```

```kotlin
val color = alloc<NVGcolor>()
color.r = 255 / 255f
color.g = 192 / 255f
color.b = 0 / 255f
color.a = 255 / 255f
nvgFillColorPtr(ctx, color.ptr)
```

While this works, it's a kinda annoying workaround as I have to create intermediate functions for every function I want to call with a NVGcolor parameter, so I'd be glad if there is a better way.

**Comment by artdfel** [comment]
Thank you for the report, @se1by! It seems like there is a bug here, so it's awesome that you found a workaround solution. There will be an update here when the fix will become available.

**Comment by SvyatoslavScherbina** [comment]
Should work in the upcoming 1.5.30 release (starting from M1).
