### ISSUE TITLE
Configure download URL

### ISSUE THREAD

**Issue by greenarr0w** [JetBrains/kotlin-native#3613]
Hello everybody

I wanted to ask if it is possible to configure the download URL of the kotlin-native compiler when using the`[id org.jetbrains.kotlin.multiplatform']` plugin?

The reason I want to do that is because I can't download dependencies from the internet in my company. For that we are using the Sonatype Nexus Repository Manager where I have the possibility to upload thirdparty dependencies. 

At the moment I have to download the kotlin native compiler manually and then define it with the kotlin.native.home property in my project.

My expectation is that there would be something similar like the distributionUrl property of the gradle wrapper.

Thanks in advance.

**Comment by artdfel** [comment]
Hello, @greenarr0w! There is no such option, but we figured out some recommendations that might help you. Currently, the plugin is looking for an exact ivy repository for an exactly named artifact. One can have a look at the details by this [link](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/NativeCompilerDownloader.kt). But, one can circumvent this fact by creating own repository, and specifying the build script to work with it. This should be done somehow like
```
repositories {
    ivy {
        setUrl(file("local-kn-repo/dev/1.3.60-dev-0/macos"))
        patternLayout {
            artifact("[artifact]-[revision].[ext]")
        }
        metadataSources {
            artifact()
        }    }
}
```
, where path to the repository should consist of  `*<dev|release>/<version>/<macos|linux|windows>`. Please also note, that dev version structure differs from the release one - the dev extends version number with `-dev-...` suffix. 
So, you got to do two main things - put the compiler to the correct path in the Repository Manager, and extend all of your scripts with the property above. To control the version of Native compiler, you got to sync path and the `kotlin.native.version` property in the project's gradle.properties file. For the example above, it would be `kotlin.native.version=1.3.60-dev-0`.

**Comment by greenarr0w** [comment]
Hello @artdfel thank you very much for the answer. I would like to try that out. Is there a place where I can find all the releases from download.jetbrains.com including also the dependencies (for example llvm & libffi) of the kotlin native compiler. Because the compiler wants to download them in the first run.

**Comment by artdfel** [comment]
All those dependencies are listed in [this](https://github.com/JetBrains/kotlin-native/blob/master/konan/konan.properties) file in this repository. The compiler uses it as described [here](https://github.com/JetBrains/kotlin-native/blob/master/shared/src/main/kotlin/org/jetbrains/kotlin/konan/util/DependencyProcessor.kt). It may be useful to have a look through this code, to make yourself more familiar with this machinery.
If you want to do download things manually, just use `download.jetbrains.com` with this URL structure: `$dependenciesUrl/$dependency.<tar.gz|zip>`. According to the current state of the compiler, it would be, for example [MacOS llvm](https://download.jetbrains.com/kotlin/native/clang-llvm-apple-8.0.0-darwin-macos.tar.gz). Compiler wants dependencies to be presented in the `~/.konan/dependencies/` directory. 
Also, you can try to host all those files in your Repository Manager, and then override the `konan.properties` contents of the local compiler(it can be found in the `~/.konan/kotlin-native-$hostName-$version/konan/konan.properties`).

**Comment by greenarr0w** [comment]
@artdfel Thanks for the detailed answer. I will see what we can do.

**Comment by alexeisele** [comment]
I'm running into this same issue when trying to build the master branch of https://github.com/kotlin-hands-on/mpp-ios-android/tree/master

Should I be putting that custom repository configuration inside of the root level `build.gradle` under `buildscript` `repositories` or `allprojects` `repositories` section?

In addition, I can see a `TODO` to source this base url from a variable here: https://github.com/JetBrains/kotlin-native/blob/dde5eced877bc5c1c317850a2f9f64737d750bd3/konan/konan.properties#L17

Is this something that can be easily achieved in the next release?

**Comment by artdfel** [comment]
Hi @alexeisele! Root `build.gradle`'s `allprojects` section seems to be the most correct place. The TODO you found, its an obsolete thing that should not be taken into the account in this case.

**Comment by alexeisele** [comment]
Thanks @artdfel!
That got me past the download url issue. Unfortunately it looks like when the compiler tries to run the `clang` executable that was downloaded, I get permission denied issues as downloaded executables are only allowed to run from specific controlled directories at my company. 

Do you know if it's possible to configure kotlin-native to use the default clang compiler already installed instead of having to go download one?

It looks like someone already tried to pursue this: https://discuss.kotlinlang.org/t/how-to-use-default-system-clang-llvm-for-kotlin-native/8481
