### ISSUE TITLE
IntelliJIDEA stop showing POSIX and cintrop suggestions

### ISSUE THREAD

**Issue by kavanmevada** [JetBrains/kotlin-native#3629]
After updating to build 193.5233.102 and kotlin native 1.3.61 code suggestions and code complition broke.

It stoped my work since 2 days no solutions. Really frustrated by relying on this only IDE.

**Comment by Thomas-Vos** [comment]
Did you find a solution? I downgraded the Kotlin Plugin to 1.3.50 for now but really want to update it.

**Comment by kavanmevada** [comment]
From menu code completion , turn switch to basic suggestions then switch back to smart suggestions

**Comment by julKali** [comment]
I can't find this menu ... can you please specify it a bit further? Do you mean settings?
I could only find this in settings:
![image](https://user-images.githubusercontent.com/17690423/77102340-f4f9ea80-6a18-11ea-8b15-5f0965bb791e.png)
