### ISSUE TITLE
identityHashCode

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3640]
Is there Kotlin/Native equivalent of JVM `System.identityHashCode()` method?

commonMain
```kotlin
expect fun identityHashCode(instance: Any?): Int
```

jvmMain - works:
```kotlin
actual fun identityHashCode(instance: Any?): Int = System.identityHashCode(instance)
```

nativeMain - complains that `Any.identityHashCode()` is internal:
```kotlin
actual fun identityHashCode(instance: Any?): Int = instance?.identityHashCode() ?: 0
```
As workaround - this compiles (but is ugly hack):
```kotlin
@SymbolName("Kotlin_Any_hashCode")
external fun Any.__identityHashCode(): Int
actual fun identityHashCode(instance: Any?): Int = instance?.__identityHashCode() ?: 0
```

Usecase: https://android.googlesource.com/platform/frameworks/support/+/a2ed24eb4f7a1e38c87ea6ff473ad6e60d9bf223/compose/compose-runtime/src/commonMain/kotlin/androidx/compose/ObserverMap.kt#105

**Comment by olonho** [comment]
OK, I'll try to provide smth here.

**Comment by msink** [comment]
Well, it's going even worse - now it uses not only `identityHashCode`, but also `Reference<T>` and `ReferenceQueue<T>`, that too do not have K/N eqivalents.

So now I do not know how to port this file, and is it possible at all: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/compose/compose-runtime/src/commonMain/kotlin/androidx/compose/ObserverMap.kt

**Comment by olonho** [comment]
Why not discuss it with Compose devs on `#compose` channel. Original issues is fixed and `kotlin.native.identityHashCode` will be available in 1.3.70.

**Comment by msink** [comment]
They said that entire class should be `expected`, with different K/N implementation.
But without `ReferenceQueue` implementation will be very slow, and this function is in hot path.
Anyway seems that K/N implementation of Compose will be orders of magnitude slower than Android's.

**Comment by olonho** [comment]
Not sure why it shall be so slow, we would expect similar performance characteristics.
