### ISSUE TITLE
Support adding a prefix to swift_name for Classes and Protocols

### ISSUE THREAD

**Issue by nuno-vieira** [JetBrains/kotlin-native#3644]
Would be nice to have a way to add a prefix to the `swift_name` of the generated Objc Framework Headers. So in Swift, we could call the protocols and classes with a custom prefix. 

This useful if there are classes and protocols with the same name in Kotlin Multiplatform and on the iOS Project. For my case, this is really important, since we are using Kotlin Multiplatform for a component in an SDK, and we don't want to expose MPP Models to the clients ( at least yet, because of how some stuff is converted to Swift, like enums, mutable arrays, etc...). So in the iOS Project, we map these MPP models to Swift Models, and we don't want to rename the Swift Models because of Multiplatform, and since Android doesn't need this, it wouldn't also make sense to change the name in the Multiplatform side.

What do you guys think about this?

Currently, in other to work around this, we can create a post-build script in Gradle that renames the swift_names of the classes and interfaces. But would be nice that Kotlin/Native would support this.

**Comment by artdfel** [comment]
Hello, @nuno-vieira! Thanks for your feedback. 
IIRC, prefixing `swift_name`s was set aside because of namespace existence in the Swift world.

**Comment by nuno-vieira** [comment]
@artdfel But since the generated framework is not a swift framework, we can't really call the classes with the Framework's Name as the namespace. 

So if we `import TheBestSDK` we can't resolve conflicts by calling `TheBestSDK.SomeObject`.

**Comment by nuno-vieira** [comment]
@artdfel I will close this issue 🤦‍♂You are totally right. The reason why we could not use the Module name to prefix it is because the Module name has the same name as an Object 🤦‍♂So the compiler can't know what you are trying to refer, to the module or the object.
