### ISSUE TITLE
Add Text Editor Sample

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#3651]
In the Kotlin Native samples there isn't a text editor sample. There is a [Gtk](https://github.com/JetBrains/kotlin-native/tree/master/samples/gtk) sample in the Kotlin Native repository however it is too basic. Would be good to have a more advanced/realistic sample that uses the Gtk toolkit, which would show the following:

- How to use callbacks
- Structuring a desktop GUI
- Handling the Gtk life cycle
- Using managed layouts
- Dealing with stable references/callback data
- Window management
- Managing C pointers
- Handling file IO
- Using dialogs

**Comment by olonho** [comment]
Please use https://github.com/msink/kotlin-libui.

**Comment by artdfel** [comment]
Also, I've seen [these](https://github.com/dickensas/kotlin-gradle-templates) [two](https://github.com/kavanmevada/kotlin-native-gtk-linux) projects, that can be interesting.

**Comment by napperley** [comment]
Looks as though I am being misunderstood. Libui (cross platform GUI library) isn't the same as Gtk (a GUI toolkit that is native to the top three Linux desktop distributions - Ubuntu, Linux Mint, and Fedora); it is like comparing apples and oranges. This [project](https://github.com/napperley/kotlin-native/tree/kpad-sample/samples/kpad) will show what I mean by what has been mentioned in the first comment.
