### ISSUE TITLE
addressOf bounds

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#3655]
Thi is not a "bug" but a behaviour I think you should consider:

This gives an `ArrayIndexOutOfBoundsException`:

```
package sample

import kotlinx.cinterop.*

fun main() {
    val ba = byteArrayOf()
    ba.usePinned { pin ->
        println(pin.addressOf(0))
    }
}
```

Even if the array is empty it has an allocated address, it is not a null pointer so has an address. And I believe you should be able to get the address of the end of the array to be consistent even if that address is not writable still is an address.

This should be valid too: `pin.addressOf(array.size) - pin.addressOf(0)`

This behaviour made caused me lot of trouble in several cases like here:
https://github.com/korlibs/korge/issues/25

Or when using `fwrite`, `fread` with empty arrays. You are using pointers manually, so you are at risk anyway. 

You normally use empty arrays with 0 length, so nobody will either read/write to that pointer anyway, but you are not expecting to have an exception there.

**Comment by artdfel** [comment]
Hello @soywiz! I think that throwing an exception here should be considered as expected behavior. Basically, you get IOOBE because the index is bigger than the array size. Are you proposing to cut the exception out of here? I'm afraid that would be incorrect, sorry.

**Comment by soywiz** [comment]
I'm proposing to support the last index of the array too even if you can't write to it. Or at least a way to get the pointer to the array even if it has length 0. You can still get the pointer of an array of one element add 3 positions to the pointer and write to the memory (and that's bad too).

https://linux.die.net/man/3/calloc

> If size is 0, then malloc() returns either NULL, or a unique pointer value that can later be successfully passed to free().

In any case in C you can get the pointer to something you allocated as 0.

In Java when using JNA for example, you can pass a Buffer that is empty 0 and it internally resolves to the Pointer.

The problem is that like this you cannot get the pointer or null to an empty array, that causes unexpected problems in edge cases, so you have to place ifs everywhere to support empty arrays.

If you do not like supporting the addressOf of the end of the array, maybe they could provide an extension function or property to get access to the beginning of the array or null, but some APIs might require non-null pointers even if later you pass a 0 to the length of the buffer.

**Comment by olonho** [comment]
Not sure if making error-prone APIs in in our plans. This is an edge case, and practically speaking you can have smth like
`fun Pinned<ByteArray>.addressOfOrNull(index: Int): CPointer<ByteVar>? = if (this.size == 0) null else this.get().addressOfElement(index)` but I wouldn't call this API pretty.

**Comment by soywiz** [comment]
in the case it helps someone having the same converns, I have solved it in my own stack like this:

```kotlin
private val emptyPinnedByte = ByteArray(1).pin()

// @TODO: Performance penalty due to requiring calling `this.get()` to get the size of the array. Optimal solution should be provided my Kotlin/Native.

/** Returns a valid not-null address, either from the beginning of this array or from another address if the array is empty */
val Pinned<ByteArray>.startAddressOf: CPointer<ByteVar> get() = if (this.get().isNotEmpty()) this.addressOf(0) else emptyPinnedByte.addressOf(0)
```

Since I needed a non-null address to not propagate nullability on places that required a not-null pointer. Sadly this is suboptimal since I have the penalty of having to get the array to check the size, but still better than having ifs elses or problems like the ones I have been having over these years and discovered later when the inputs were empty arrays.
