### ISSUE TITLE
Cygwin .dll and .a files linking using cinterop

### ISSUE THREAD

**Issue by dickensas** [JetBrains/kotlin-native#3664]
I tried to cinterop libraries inside cygwin C:\cygwin64\lib C:\cygwin64\usr\include

interop is working, binary exe linking and execution seems to be not happening 

any experience or demo or help will be good

**Comment by artdfel** [comment]
Hello! What do you mean by "not happening" here? If you use Gradle, there should probably be some kind of output. Also, can you please add the `.def` file to this report?

**Comment by msink** [comment]
I doubt that this is possible - K/N compiles to MinGW ABI, and cygwin ABI is very different.
