### ISSUE TITLE
[Reverse C Interop] No methods for kotlin package types

### ISSUE THREAD

**Issue by alusch** [JetBrains/kotlin-native#3666]
If your public API returns something from the `kotlin` package like `Error`, you'll get an opaque type in the generated header (`YourProject_kref_kotlin_Error`), but no vtables, so you can't directly interact with them from C.

We have an API that returns an `Error` to report status, and currently need a helper function in Kotlin to extract the message and cause in order to understand what went wrong.

`List` is a big one too, though that has additional complexities due to the generic parameter.

**Comment by olonho** [comment]
Yes, this is by design. You can extract useful helpers into a klib and put it into all interop modules as described in comments to https://github.com/JetBrains/kotlin-native/issues/3571.

**Comment by alusch** [comment]
Thanks, @olonho. Could you please elaborate on the design a bit, or link to some documentation if it exists? It's not a big deal to set up helpers like you describe (though dealing with generics is a bit painful), but it does seem a bit unfortunate that each project needs to reinvent similar utility functions.

**Comment by olonho** [comment]
You can build such library once and reuse it by including as described in https://github.com/JetBrains/kotlin-native/issues/3571#issuecomment-562538118
