### ISSUE TITLE
[Cocoapods Plugin] automatically include sqlite library if it was linked 

### ISSUE THREAD

**Issue by AlecStrong** [JetBrains/kotlin-native#3672]
assuming an ios target configured as such:

```groovy
extraOpts("-linker-options", "-lsqlite3")
```

the generated `.podspec` should have this block

```
spec.libraries = 'c++', 'sqlite3'
```

happy to look into contributing this, if it seems reasonable.

**Comment by olonho** [comment]
Yeah, idea looks great. +1.

**Comment by wellingtoncosta** [comment]
@AlecStrong how can I set this `extraOpts` using Kotlin Dsl?

**Comment by wellingtoncosta** [comment]
I found the solution:

```kotlin
targets.getByName<KotlinNativeTarget>("ios").compilations.forEach {
  it.kotlinOptions.freeCompilerArgs += arrayOf("-linker-options", "-lsqlite3")
}
```

**Comment by ilmat192** [comment]
@AlecStrong, should this feature really rely on `-linker-options` passed to the compiler? Shouldn't we provide a separate DSL to configure podspec content instead?

Please correct me if I wrong, but `spec.libraries` in Kotlin podspecs makes sense only if the Kotlin module produces a _static_ framework. But `-linker-options` doesn't make sense for static frameworks because we don't run linker for them. And vice-versa: we can link a _dynamic_ framework against some libraries but there is no need to list them in `spec.libraries`  in this case.

**Comment by AlecStrong** [comment]
I'm not sure, it's been a while since I played with dynamic/static frameworks, everything you're saying makes sense though. I thought you still needed to have `-linker-options` specified even for static frameworks in order to have sqlite bundled in in some way (like if you're running unit tests)

**Comment by ilmat192** [comment]
@AlecStrong I've found out that the Kotlin/Native compiler can [store](https://github.com/JetBrains/kotlin-native/blob/9e6031e66a9d54a1950a0026259b890f47cea48c/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/CompilerOutput.kt#L185) some linker options declared in cinterop libraries to the produced bitcode/object files. Then a system linker will pick these options when building a final application. In this case, there is no need to specify a library in `spec.libraries` if the `linkerOpts` field in the def-file already references it via `-l`.

We still need to specify `-L<path>` for unit tests and dynamic frameworks though. But it doesn't relate to the CocoaPods integration.

Could you please tell more about your use case? Probably the approach with `linkerOpts` can help you without editing the podspec.

P.S. We are [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079) now, so I've created YT-issue to track the general problem: configuring content of the generated podspec. Feel free to comment there as well.

**Comment by ilmat192** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-42630](https://youtrack.jetbrains.com/issue/KT-42630).
