### ISSUE TITLE
How to change .rdata linking paths for ARM binaries?

### ISSUE THREAD

**Issue by fjanicki** [JetBrains/kotlin-native#3677]
I am trying to use Kotlin for an embedded linux target. My target has an OS built around a Yocto distribution. I tried to make an hello world sample app to see if Kotlin would work on it and I get an error:

```
root@0F0DC359377060757787:~# ./appli
-sh: ./appli: not found
```

I then inspect the .rdata

```
Dynamic section at offset 0x2bce8 contains 29 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libdl.so.2]
 0x00000001 (NEEDED)                     Shared library: [libm.so.6]
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]
```

All those shared libraries .rdata seem to be present on my target system, except for the last one, it's there but it dosen't have the same name. I suspect this is the issue.

This is what is present on my target
```
root@0F0DC359377060757787:~# ls /lib | grep ld
ld-2.20.so
ld-linux.so.3
```

vs  `ld-linux-armhf.so.3` in the .rdata

I am looking for a way to either patch the binary after compilation or a gradle configuration that I could change to change the name of the shared object it links to, at compilation time like I would do in C++. Any idea on how to do this?

Note that I cannot just symlink `ld-linux-armhf.so.3` to `ld-linux.so.3` since my /lib/ is a read-only file system on my target.

This is my current gradle file:

```
plugins {
    kotlin("multiplatform") version "1.3.61"
}

group = "com.noden.embedded"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

kotlin {
    /* Targets configuration omitted.
    *  To find out how to configure the targets, please follow the link:
    *  https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#setting-up-targets */
    macosX64("native") {
        binaries {
            executable()
        }
    }

    linuxArm32Hfp() {
        binaries {
            executable()
        }
    }
        sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(kotlin("stdlib-common"))
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
    }
}
```

**Comment by artdfel** [comment]
Hello! I think that the best idea here would be to use some third-party util, [patchelf](https://nixos.org/patchelf.html), for example.

**Comment by fjanicki** [comment]
Hi, Yeah this is what I initially though, but was wondering if it was possible to do it at compilation time instead.

What if I have a custom generated sysroots, would it be possible to use this instead of the one provided by the `linuxArm32Hfp() {}` target?

**Comment by fjanicki** [comment]
I tried with `patchelf`and indeed it is working with the following command:

`patchelf --set-interpreter /lib/ld-linux.so.3 untitled1.kexe`

**Comment by olonho** [comment]
See https://github.com/JetBrains/kotlin-native/blob/e1bb426e55c5c3b02210b1c24bb1a4ac2c3f7834/konan/konan.properties#L371, but we'll unlikely support such a solution.

**Comment by fjanicki** [comment]
Yeah this is what I ended up doing, I changed this file and recompiled the compiler. Do you know how I could add a new target alongside the Raspberry Pi target? I see that it downloads the sysroots from somewhere but I can't really find how to implement my own build target / sysroots.

**Comment by olonho** [comment]
You don't need to recompile anything, it's enough to fix property file in the place used by IDEA. New targets are not so easy to add, but you could replace existing toolchain and modify compiler flags in konan.properties.

**Comment by artdfel** [comment]
Closing as answered, please feel free to reopen if there are further questions.
