### ISSUE TITLE
Could not find or load main class org.jetbrains.kotlin.cli.utilities.MainKt

### ISSUE THREAD

**Issue by ghost** [JetBrains/kotlin-native#3687]
Using Kotlin from here:

https://github.com/JetBrains/kotlin/releases/latest

I get this:

~~~
$ PATH=jdk-13.0.1/bin:"$PATH" \
> kotlin-native-windows-1.3.61/bin/kotlinc
Error: Could not find or load main class
   org.jetbrains.kotlin.cli.utilities.MainKt
Caused by: java.lang.ClassNotFoundException:
   org.jetbrains.kotlin.cli.utilities.MainKt
~~~

**Comment by olonho** [comment]
Can you try with JDK8 or 11?

**Comment by cup** [comment]
@olonho

~~~
$ PATH=../jdk-11/bin:"$PATH" bin/kotlinc
Error: Could not find or load main class
   org.jetbrains.kotlin.cli.utilities.MainKt
Caused by: java.lang.ClassNotFoundException:
   org.jetbrains.kotlin.cli.utilities.MainKt
~~~

**Comment by artdfel** [comment]
Closing as obsolete, please reopen if the problem is still here.

**Comment by cup** [comment]
https://github.com/JetBrains/kotlin-native/issues/3838

**Comment by rafihadi04** [comment]
i have same problem in windows. but i think its because the directory of kotlin_home using space in my case its "D:\Rafi Punya\kotlinc" but when i change to "D:\Rafi\kotlinc" its working very well
