### ISSUE TITLE
Undefined symbols for architecture x86_64 on Library from cocoapods

### ISSUE THREAD

**Issue by kuuuurt** [JetBrains/kotlin-native#3702]
I'm trying to use `AWSS3` on K/N and whenever I try to build it, I get this error: 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AWSS3TransferUtilityMultiPartUploadExpression", referenced from:
      objc-class-ref in result.o
ld: symbol(s) not found for architecture x86_64
```

Do I have to setup cinterop manually even when using cocoapods?

My configuration is just this
```kotlin
kotlin {
    cocoapods {
        summary = "My Shared Module"
        homepage = "Link to a Kotlin/Native module homepage"
        pod("AWSS3")
    }
    ...
}
```

And I'm using it in a class
```kotlin
actual class TransferUtility {
    lateinit var awsS3TransferUtility: AWSS3TransferUtility
    actual suspend fun uploadPhoto(
        objectKey: String,
        imagePath: String
    ): String = suspendCoroutine {
        val expression = AWSS3TransferUtilityMultiPartUploadExpression()

        val completionHandler: AWSS3TransferUtilityMultiPartUploadCompletionHandlerBlock
        completionHandler = { _, error ->
            if (error != null) {
                it.resumeWithException(Throwable(error.localizedDescription))
            }
            it.resume()
        }

        awsS3TransferUtility.uploadFileUsingMultiPart(
            NSURL.fileURLWithPath(imagePath),
            objectKey,
            "image/jpeg",
            expression,
            completionHandler
        )
    }
}
```

**Comment by ilmat192** [comment]
Thank you for the report! I'll take a look. What Kotlin version do you use?

> Do I have to setup cinterop manually even when using cocoapods?

No, the interop is created and configured automatically. You still may access it and change the configuration though.

**Comment by kuuuurt** [comment]
I'm using 1.3.61

**Comment by kuuuurt** [comment]
Here's some more info.

I'm using it in a modular setup so I have my `shared-ios` module which gets all other modules (while we still can't import multiple K/N module):

```kotlin
kotlin {
    cocoapods {
        summary = "Shared iOS module for Android and iOS"
        homepage = "Link to a Kotlin/Native module homepage"
        pod("AWSS3")
    }

    val iOSTarget: (String, KotlinNativeTarget.() -> Unit) -> KotlinNativeTarget =
        if (System.getenv("SDK_NAME")?.startsWith("iphoneos") == true)
            ::iosArm64
        else
            ::iosX64

    iOSTarget("ios") {
        compilations {
            val main by getting {
                kotlinOptions.freeCompilerArgs = listOf("-Xobjc-generics")
            }
        }

        binaries.framework(frameworkName) {
            baseName = frameworkName
            export(project(":shared:shared-common"))
            export(project(":shared:shared-upload"))
        }
    }
}
```

And `shared-upload` is this

```
kotlin {
    cocoapods {
        summary = "Shared Upload module for Android and iOS"
        homepage = "Link to a Kotlin/Native module homepage"
        pod("AWSS3")
    }
}
```

This is the error I'm receiving on Xcode with a warning

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AWSS3TransferUtilityMultiPartUploadExpression", referenced from:
      objc-class-ref in result.o
ld: symbol(s) not found for architecture x86_64
w: Following libraries are specified to be exported with -Xexport-library, but not included to the build:
/path-to-project/shared-upload/build/libs/ios/main/shared-upload-cinterop-AWSS3.klib
```

I thought that it's with the library so I tried `AFNetworking` and it's also happening.

**Comment by kuuuurt** [comment]
Hello @ilmat192! I've found the issue. I've been using the `packForXcode` task like in the (docs)[https://play.kotlinlang.org/hands-on/Targeting%20iOS%20and%20Android%20with%20Kotlin%20Multiplatform/03_CreatingSharedCode]

I tried out the unchanged file from`podspec` using `syncFramework` and it works now.

**Comment by kuuuurt** [comment]
Okay, did some more digging and found [this](https://discuss.kotlinlang.org/t/kotlin-multiplatform-binaries-name-for-native-targets/14364) and [this](https://discuss.kotlinlang.org/t/kotlin-multiplatform-binaries-name-for-native-targets/14364)

So I can't rename my frameworks and I have to use the default. Now, my problem is that I have a modular structure and I just export the libraries in a `shared-ios` module

shared-ios
- shared-module-1
- shared-module-2

And I do such configuration by using 

```
kotlin {
    iosX64("ios") { // iosArm64("ios")
        binaries {
            framework {
                export(project(":shared:shared-common"))
                export(project(":shared:shared-medications"))
                export(project(":shared:shared-orders"))
                export(project(":shared:shared-user"))
                export(project(":shared:shared-states"))
                export(project(":shared:shared-splash"))
                export(project(":shared:shared-otp"))
                export(project(":shared:shared-auth"))
                export(project(":shared:shared-dashboard"))
                export(project(":shared:shared-patient-auth"))
                export(project(":shared:shared-patient-payments"))
                export(project(":shared:shared-patient-onboarding"))
                export(project(":shared:shared-patient-dashboard"))
                export(project(":shared:shared-patient-profile"))
                export(project(":shared:shared-provider-dashboard"))
            }
        }
    }
}
```

But this results to `Cannot create binary debugFramework: binary with such a name already exists`

Is this something we can't do as well? Or is there a workaround so we can still configure the existing binary?

**Comment by ilmat192** [comment]
Hi! Sorry for the late answer.

> But this results to Cannot create binary debugFramework: binary with such a name already exists

This construction
```kotlin
framework {
    export(project(":shared:shared-module-1"))
    export(project(":shared:shared-module-2"))
}
```
creates a new framework so you got this error. You need to edit settings for a framework created by the CocoaPods plugin by default instead. Since there are two frameworks (debug and release), the easiest way to do this is to configure all frameworks in the `binaries` container using the `withType` method:
```kotlin
import org.jetbrains.kotlin.gradle.plugin.mpp.Framework
...
binaries.withType(Framework::class.java) {
    export(project(":shared:shared-module-1"))
    export(project(":shared:shared-module-2"))
}
```

As for renaming a resulting framework, there is a workaround. The CocoaPods plugin always uses the Gradle module name as a name of the framework. So, you cannot rename the framework itself but you can rename the module without renaming a module directory. To do this, rename the module in your `settings.gradle` and then specify the old directory for this module:

```kotlin
include(":Foo")
project(":Foo").projectDir = file("bar")
```

**Comment by kuuuurt** [comment]
Thanks @ilmat192!

I forgot to comment that I got this resolved using `withType` but thanks for pointing that out for everyone to see. 

Right now, I just renamed the Gradle module as a whole along with the directory. I'll try the configuration on `settings.gradle` and hopefully it works!

**Comment by kuuuurt** [comment]
Yup it works. Thanks again @ilmat192!

**Comment by kharchenkovitaliypt** [comment]
Link CocoaPods frameworks with iosTest binary
https://youtrack.jetbrains.com/issue/KT-44857
