### ISSUE TITLE
Add support for Mac Catalyst

### ISSUE THREAD

**Issue by Thomas-Vos** [JetBrains/kotlin-native#3713]
Please add support for Mac Catalyst. With the new Mac Catalyst you can create a native Mac OS app from an iPad app. Mac Catalyst has support for iOS UIKit APIs. For more information see: https://developer.apple.com/mac-catalyst/

If I try to build my Kotlin framework for iosX64 I get an error in Xcode that it was built for iOS Simulator. If I try to use macosX64 I get an error that it was built for macOS.
So it looks like the framework needs to be specifically built for Mac Catalyst.

Related:
- https://kotlinlang.slack.com/archives/C3SGXARS6/p1576425974024100
- https://github.com/JetBrains/kotlin-native/pull/3383
- https://github.com/JetBrains/kotlin/pull/2626

**Comment by joshuamking-driveclutch** [comment]
Any updates on this?

**Comment by JUSTINMKAUFMAN** [comment]
Also could use a fix on this!

**Comment by jasperblues** [comment]
It sounds as though all that would be required is a tweak to the compiler settings.

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-40442
