### ISSUE TITLE
runtime assert: Object must not be tagged

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3723]
Trying to port `ObserverMap` from Android Jetpack Compose to K/N - get weird error:
`runtime assert: Object must not be tagged`
and process with unit-tests terminated abnormally.

implementation: https://github.com/msink/kotlin-libui/blob/ObserverMap/compose-runtime/src/nativeMain/kotlin/ObserverMap.kt
unit-test: https://github.com/msink/kotlin-libui/blob/ObserverMap/compose-runtime/src/commonTest/kotlin/ObserverMapTests.kt

What is wrong here?

**Comment by msink** [comment]
Fixed by #3781

**Comment by msink** [comment]
@olonho Will #3781 be in 1.3.70?

**Comment by kylejbrock** [comment]
This seems to still be a problem in 1.3.71.  Just migrated from 1.3.61 and now my app is crashing with this error.
