### ISSUE TITLE
Improve Concurrency Documentation

### ISSUE THREAD

**Issue by brendanw** [JetBrains/kotlin-native#3740]
It would be great if it were clarified in https://github.com/JetBrains/kotlin-native/blob/master/CONCURRENCY.md that any time an object is referenced by two functions that can change the coroutine context (eg async, launch, withContext, suspending function) that the object will be frozen. It'd be helpful to drive home the point by showing an example where the coroutine is executed on a single thread but objects are still frozen.

This came up as a problem here https://github.com/ktorio/ktor/issues/1537

**Comment by benasher44** [comment]
This probably belongs as documentation in the coroutines library for native mt coroutines when it's released, since this is behavior controlled by that library
