### ISSUE TITLE
[Feature request] WASI support

### ISSUE THREAD

**Issue by gengjiawen** [JetBrains/kotlin-native#3744]
See https://wasi.dev/.

Ref: 
* https://github.com/bytecodealliance/wasmtime
* https://github.com/golang/go/issues/31105

**Comment by syrusakbary** [comment]
Would be great to have a WASI target for Kotlin.

I work at [Wasmer](https://wasmer.io) (a fast, standalone WebAssembly runtime) and we are super excited to see more languages targeting WebAssembly & WASI.

Let me know if we can help in any way to get Kotlin targeting WASI :)

**Comment by bashor** [comment]
@gengjiawen thank you for your request! 
From my point of view, WASI support doesn't require special support from the compiler side but likely should be supported as a library and maybe in tooling.

@syrusakbary thank you for the offer!
Right now we are working on a dedicated compiler backend for WebAssambly and a key requirement for us now is "we don't want to bring own memory manager", so we depend on GC-proposal.
So, we are really missing any implementation of it. 
What do you think about the proposal?
Do you have any plan about supporting this proposal in Wasmer?

BTW, are you going to be at WebAssembly Summit?

**Comment by bashor** [comment]
I've created [the issue to track](https://youtrack.jetbrains.com/issue/KT-36172), feel free to vote or star it to get updates.
