### ISSUE TITLE
kotlin and webassembly

### ISSUE THREAD

**Issue by j209** [JetBrains/kotlin-native#3747]
I think working on WebAssembly support in Kotlin/Native is so poor.
Webassembly will be the first class technology for web developement in the feature and Kotlin despite of is the perfect language for the WebAssembly,it seems it drop behind c# [blazor](https://github.com/dotnet/blazor) or even python [pyodide](https://github.com/iodide-project/pyodide).
[My call for Kotlin as a major frontend language](https://gist.github.com/sdeleuze/0da8c3d6a43c659977a16e017020503b)

**Comment by bashor** [comment]
Hi, thank you for asking!

We've started a dedicated compiler backend for WebAssambly, we'll announce details as soon as it will be ready to try. To be informed about the news I'd recommend you to join #webassembly channel in our Slack, can get an invitation [here](https://kotl.in/slack).

Stay tuned!

**Comment by ethanfrey** [comment]
> We've started a dedicated compiler backend for WebAssambly

Any updates here @bashor ?

**Comment by bashor** [comment]
@ethanfrey we are working on the new backend, it already passes about 60% of compiler tests. You can track the progress here https://youtrack.jetbrains.com/issue/KT-42292
