### ISSUE TITLE
iOS app crashes when using static value inside static function before the value is defined

### ISSUE THREAD

**Issue by francos** [JetBrains/kotlin-native#3750]
The crash appears when you define a constant after a static method and use that constant inside the method.

This should be either caught by the compiler or just work as is, right now it crashes at runtime and the error doesn't explain exactly what is going on so it's hard to figure it out. 

This is the reproducer:

```kotlin
class SomeClass {

    fun authenticate() {
        val url = AUTHENTICATE_URL
    }


    companion object {

        private val AUTHENTICATE_URL = "https://whatever?goto=${getAuthorizeUrl()}"


        private fun getAuthorizeUrl(): String {
            return "https://whatever?param1=$PARAM"
        }

        private const val PARAM = "paramvalue"

    }

}
```

**Comment by olonho** [comment]
This behavior is kind of expected, and I'd recommend to set `PARAM` before `AUTHENTICATE_URL`.

**Comment by FrancoSabadini** [comment]
Hi @olonho, 

Thanks for the response. I know that switching the order of the constants avoids this issue, but there are a few reasons why I think it's important to fix it: 

1. Neither the Kotlin Compiler nor the Kotlin Intellij Plugin shows an error or warning for this, which means that the app crashes at runtime. This is not ideal and seems like it could be avoided (although I don't know the specifics of the compiler or plugin code so I'm not sure how hard it'd be).

2. The error shown by the crash doesn't offer much help on why it crashes, which makes this situation very hard and time-consuming to track. 

3. This same code works on the JVM, so when working on Kotlin Multiplatform, it is an inconsistency between platforms that might confuse developers and breaks the "build once run anywhere" principle. 

If this can't be easily fixed, I think intermediate solutions to help developers could be:

1. Show an error at compile-time. 

2. Show a proper error when the app crashes at runtime to explain what the issue actually is so it's easier and quicker to fix.

**Comment by Tvede-dk** [comment]
Hi @FrancoSabadini 
Although I cannot explain why it works on the JVM (since kotlin does not change the rules for initialization (I cannot find the Youtrack ticket that stated Kotlin would not change this behavior) which if you go into  the JVM specification does not guarantee intialization order with regards to function calls, see https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.3.2.3 ) 

But i can advocate for https://plugins.jetbrains.com/plugin/12853-csense--kotlin-assistance/ which is an IDEA plugin that tries to detect this case (along some other inconveniences), which I'm the creator of.

**Comment by FrancoSabadini** [comment]
Hi @Tvede-dk, thanks for the info!

I was not aware of that JVM specification, even weirder that it still worked on the JVM 🤔. Not only did this compile for Android, it also run without any runtime crashes.

**Comment by homuroll** [comment]
Created an issue on YT: https://youtrack.jetbrains.com/issue/KT-43210. Closing here.
