### ISSUE TITLE
[Reverse C Interop] Surprising multithreaded crashes

### ISSUE THREAD

**Issue by alusch** [JetBrains/kotlin-native#3754]
This may just be an incomplete understand on my part, so I'd appreciate any clarification you can offer. I'm returning pinned objects from Kotlin to C, so had assumed that read-only multi-threaded access was allowed. However, I noticed some crashes when attempting to dispose pointers on different threads than they were created on.

knlibrary.kt:
```
package knlibrary

import kotlin.native.concurrent.freeze

data class Foo (val thing: String)

fun getFoo(thing: String): Foo {
    return Foo(thing).freeze();
}
```

test.cpp:
```
#include <thread>
#include "knlibrary_api.h"

int main()
{
    knlibrary_ExportedSymbols* lib = knlibrary_symbols();
    auto knlibrary = lib->kotlin.root.knlibrary;
    auto foo = knlibrary.getFoo("Test");
    auto t = std::thread([&]
    {
        // Uncomment to prevent crash
        //printf("Thing: %s\n", knlibrary.Foo.get_thing(foo));
        lib->DisposeStablePointer(foo.pinned);
    });
    t.join();

    return 0;
}
```

run.cmd:
```
@echo off

call kotlinc-native -g knlibrary.kt -produce dynamic -o knlibrary.dll

lib.exe /def:knlibrary.def /out:knlibrary.lib /machine:x64
cl.exe test.cpp knlibrary.lib
test.exe
```

This assumes you have the 64-bit cl.exe on your path (e.g. using the VS x64 Native Tools Command Prompt), as well as the Kotlin and Java bin directories.

If you run as is, it crashes inside `DisposeStablePointer`, evidently because an address looked up from TLS was null. Surprisingly, uncommenting the `printf` line both successfully prints the value and also prevents the crash from occurring.

After observing this behavior I noticed this line from https://kotlinlang.org/docs/tutorials/native/dynamic-libraries.html:
> Note, Kotlin/Native object references do not support multi-threaded access. Hosting the returned `libnative_ExportedSymbols*` pointer per thread might be necessary.

Does this mean that no access to a Kotlin reference from different threads in C is allowed whatsoever, and that the above example is invalid? Or is the limitation more narrow? I did also try calling `knlibrary_symbols()` on the background thread to get a new pointer in case it had to initialize some thread-local state, but it had the same effect. I'd appreciate your help in better understanding this case. Thanks!

**Comment by artdfel** [comment]
Hello @alusch! The only thing your example missing is probably a 'kotlin.native.initRuntimeIfNeeded()' call in the new thread. It can be done automatically sometimes, but it is better to do it at the beginning of a new thread(see [here](https://github.com/JetBrains/kotlin-native/issues/1448) and [here](https://github.com/JetBrains/kotlin-native/blob/dbc10781af2896d159879188dbc9832e865074f0/INTEROP.md#callbacks)). The quote about multi-threading should not be an issue, as far as you froze everything in the very beginning. 
To make the answer a little bit more formal, that's how this example can be extended:
knlibrary.kt
```
package knlibrary

import kotlin.native.initRuntimeIfNeeded
import kotlin.native.concurrent.freeze


data class Foo (val thing: String = "testOne")

fun getFoo(thing: String): Foo {
    return Foo(thing).freeze()
}

fun initThings(){
    initRuntimeIfNeeded()
}

```

test.c
```
#include <thread>
#include "knlibrary_api.h"

int main()
{
    knlibrary_ExportedSymbols* lib = knlibrary_symbols();
    auto knlibrary = lib->kotlin.root.knlibrary;
    auto foo = knlibrary.getFoo("Test");

    auto t = std::thread([&]
    {
        knlibrary.initThings();
        lib->DisposeStablePointer(foo.pinned);
    });
    t.join();

    return 0;
}
```

**Comment by alusch** [comment]
Ah, thank you, @artdfel! I must have missed that since I was focusing on the other direction of interop.
