### ISSUE TITLE
Allow export of kotlin stdlib headers

### ISSUE THREAD

**Issue by PatrickLemke** [JetBrains/kotlin-native#3766]
I have a Kotlin Multiplatform library that should be callable from other languages like C, C++, C#, Python, etc. 

If I export the project as a sharedLib however, the Kotlin stdlib headers are not exported. That means that If there's a function that has as a return type an object from the stdlib like HashMap, I can't call any functions on it. 

Is there a way to export the headers for the stdlib as well or is there only the workaround of not using those return types / creating the functions we need manually?

**Comment by vvlevchenko** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-45961 Users want to interact with objects of libraries (e.g. stdlib) types used in C/C++ exported kotlin code](https://youtrack.jetbrains.com/issue/KT-45961)
