### ISSUE TITLE
Linux distributions that use musl cannot compile any kotlin/native program

### ISSUE THREAD

**Issue by serebit** [JetBrains/kotlin-native#3771]
# The Error
As of now, when attempting to compile a Kotlin/Native program on Alpine Linux, the compilation will fail with the following message: 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /root/.konan/dependencies/clang-llvm-8.0.0-linux-x86-64/lib/libclang.so.8: libtinfo.so.5: cannot open shared object file: No such file or directory
```
Despite what the error message says, this is not due to a missing `libtinfo.so.5`, at least not initially. This error message occurs when `libtinfo.so.5` is missing, sure, but it occurs even when it is present on the system via a symbolic link to `ncurses.so.5` (which is the strategy that Solus uses for packages that still link to `libtinfo.so.5`).

# The Reproduction
On a Linux machine with Docker installed and the Docker daemon running:
```
sudo docker run -it adoptopenjdk/openjdk8:alpine-slim
```
This will open up a Bash shell within an Alpine docker container with a JDK preinstalled. Run the following from within that container:
```
apk add ncurses5-libs libstdc++ git
ln -sv /usr/lib/libncurses.so.5 /usr/lib/libtinfo.so.5
git clone https://gitlab.com/serebit/wraith-master root/wraith-master
cd root/wraith-master
./gradlew --refresh-dependencies
./gradlew build
ldd /root/.konan/dependencies/clang-llvm-8.0.0-linux-x86-64/lib/libclang.so.8
```
This will both show the build failure, and the results of checking the symbol resolution of `libclang.so.8`.

# The Explanation

Where this error message persists seems to be on Linux distributions that use `musl` instead of `glibc`. Running `ldd` on the `libclang.so.8` file gives several shared library errors, most of which can be resolved by installing `libstdc++` and `ncurses5-libs`, and adding the above symlink from `/usr/lib/ncurses.so.5` to `/usr/lib/libtinfo.so.5`. 

After doing this, the majority of errors are gone, and `ldd` outputs the following for `libclang.so.8`:
```
	/lib/ld-musl-x86_64.so.1 (0x7f8f9d0d7000)
	libdl.so.2 => /lib/ld-musl-x86_64.so.1 (0x7f8f9d0d7000)
	libz.so.1 => /lib/libz.so.1 (0x7f8f98b43000)
	librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f8f9d0d7000)
	libtinfo.so.5 => /usr/lib/libtinfo.so.5 (0x7f8f98b00000)
	libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7f8f9d0d7000)
	libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f8f9d0d7000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f8f98967000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f8f98953000)
	libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f8f9d0d7000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f8f9872a000)
Error relocating /root/.konan/dependencies/clang-llvm-8.0.0-linux-x86-64/lib/libclang.so.8: mallinfo: symbol not found
Error relocating /root/.konan/dependencies/clang-llvm-8.0.0-linux-x86-64/lib/libclang.so.8: backtrace: symbol not found
Error relocating /root/.konan/dependencies/clang-llvm-8.0.0-linux-x86-64/lib/libclang.so.8: backtrace_symbols_fd: symbol not found
```
All the links are correctly resolved, and yet three symbols are missing: `mallinfo`, `backtrace`, and `backtrace_symbols_fd`. According to my research, these symbols can be resolved on distributions that use `glibc`, but *not* on distributions that use `musl`, and this is validated by running the `ldd` command on a distribution that uses `glibc`:
```
	linux-vdso.so.1 (0x00007ffc3a930000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f9a96ecb000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f9a96eb2000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f9a96ea7000)
	libtinfo.so.5 => /usr/lib64/libtinfo.so.5 (0x00007f9a96e43000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f9a96e22000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f9a96cd4000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f9a96ae3000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f9a96ac8000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f9a968df000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f9a9b47a000)
```
Note that the former uses `/lib/ld-musl-x86_64.so.1`, and the latter does not.

# The Solution
Some investigation reveals recommendations for similar problems, which include installing `libexecinfo-dev` and `libexecinfo` (which doesn't fix the problem). As I see it, there are two options for fixing this problem.
### Option A
Allow using the system's distribution of clang instead of the packaged version, via a gradle property or flag. This would allow Linux distributions that package a musl-compatible Clang to compile programs correctly.
### Option B
Patch out the uses of those symbols in your distribution of Clang.

**Comment by SvyatoslavScherbina** [comment]
See also: https://youtrack.jetbrains.com/issue/KT-38876

**Comment by serebit** [comment]
Migrated this to https://youtrack.jetbrains.com/issue/KT-38891

**Comment by SvyatoslavScherbina** [comment]
Thanks!
