### ISSUE TITLE
Useless instructions

### ISSUE THREAD

**Issue by j-android** [JetBrains/kotlin-native#3785]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend.native:compileCompilerKotlin'.
> Compilation error. See log for more details

If you want this to be popular, then there should be a seamless process for building WITH NO ERRORS!!!

Why are binaries for macos, win and linux not available for downloads of konan?
You are making this very frustrating!

**Comment by remyers** [comment]
FWIW, I got the same error and my colleague recommended these steps:
