### ISSUE TITLE
Where is AtomicReference?

### ISSUE THREAD

**Issue by kar** [JetBrains/kotlin-native#3795]
I'm trying to use AtomicReference in my MPP project, and I can't seem to be able to make intellij see it. Which dependency is supposed to provide it? My gradle looks like this:

    sourceSets["commonMain"].dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-common")
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.3.3")
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-native:1.3.3")
        implementation("io.ktor:ktor-client-core:1.3.0")
        implementation("io.ktor:ktor-client-json:1.3.0")
        implementation("io.ktor:ktor-client-serialization:1.3.0")
    }

    sourceSets["androidMain"].dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib")
        implementation("io.ktor:ktor-client-android:1.3.0")
        implementation("io.ktor:ktor-client-json:1.3.0")
        implementation("io.ktor:ktor-client-serialization-jvm:1.3.0")
    }

    sourceSets["iosMain"].dependencies {
        implementation("io.ktor:ktor-client-ios:1.3.0")
        implementation("io.ktor:ktor-client-ios-iosx64:1.3.0")
        implementation("io.ktor:ktor-client-json-native:1.3.0")
        implementation("io.ktor:ktor-client-serialization-native:1.3.0")
    }

**Comment by r4zzz4k** [comment]
There is no common `AtomicReference` for all platforms in standard library. `java.util.concurrent.atomic.AtomicReference` should be available for JVM and Android with no dependencies, `kotlin.native.concurrent.AtomicReference` comes from bundled stdlib in Native. You can check out https://github.com/Kotlin/kotlinx.atomicfu if it fits your needs, but don't forget to carefully read README.

**Comment by rocketraman** [comment]
According to the docs, it *should* be available in common and JVM -- are the docs just wrong or am I misunderstanding something?

![image](https://user-images.githubusercontent.com/53049/96625880-bf81ec00-12dc-11eb-8936-c0686858df5b.png)

(https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native.concurrent/-atomic-reference/)

**Comment by JakeWharton** [comment]
Those the filters. Not the availability.

**Comment by rocketraman** [comment]
Ah! Just noticed the little dots on the right showing only native. Thanks.

**Comment by shoanchikato** [comment]
Maybe this will help someone one day: https://github.com/touchlab/Stately
