### ISSUE TITLE
Can't build some K/N release tags locally due to HTTP errors

### ISSUE THREAD

**Issue by serebit** [JetBrains/kotlin-native#3798]
When attempting to build some Kotlin/Native release tags, namely the `1.3.60` release and the EAP tag `v1.3.70-eap1`, the Gradle project `:shared:buildSrc` fails with the following error:
```
A problem occurred configuring project ':shared:buildSrc'.
> Could not resolve all artifacts for configuration ':shared:buildSrc:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.70-eap-38.
     Required by:
         project :shared:buildSrc
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.70-eap-38.
         > Could not get resource 'https://buildserver.labs.intellij.net/guestAuth/app/rest/builds/buildType:(id:Kotlin_KotlinRelease_1370_Compiler),number:1.3.70-eap-38,branch:default:any,pinned:true/artifacts/content/maven/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.70-eap-38/kotlin-gradle-plugin-1.3.70-eap-38.pom'.
            > Could not GET 'https://buildserver.labs.intellij.net/guestAuth/app/rest/builds/buildType:(id:Kotlin_KotlinRelease_1370_Compiler),number:1.3.70-eap-38,branch:default:any,pinned:true/artifacts/content/maven/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.70-eap-38/kotlin-gradle-plugin-1.3.70-eap-38.pom'. Received status code 400 from server: Bad Request
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.70-eap-38.
         > Could not get resource 'https://buildserver.labs.intellij.net/guestAuth/app/rest/builds/buildType:(id:Kotlin_KotlinRelease_1370_Compiler),number:1.3.70-eap-38,branch:default:any,pinned:true/artifacts/content/maven/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.70-eap-38/kotlin-gradle-plugin-1.3.70-eap-38.pom'.
            > Could not GET 'https://buildserver.labs.intellij.net/guestAuth/app/rest/builds/buildType:(id:Kotlin_KotlinRelease_1370_Compiler),number:1.3.70-eap-38,branch:default:any,pinned:true/artifacts/content/maven/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.70-eap-38/kotlin-gradle-plugin-1.3.70-eap-38.pom'. Received status code 400 from server: Bad Request
```
I maintain the Kotlin/Native package for a Linux distribution, and this is preventing me from updating the package from version `1.3.50` (which does work, with no HTTP errors). I can provide more information if needed.

**Comment by artdfel** [comment]
Thanks for the report! Please try with 1.3.70 EAP2 when it will be released.

**Comment by serebit** [comment]
@artfdel Attempted with tag `v1.3.70-eap2`, and while it did reach much further into the build, it did still fail. This time, it failed at `:backend.native:tests:update_tests`, with the following trace:
```
> Could not resolve all files for configuration ':backend.native:tests:update_tests'.
   > Could not resolve org:Kotlin_KotlinRelease_1370_Compiler:1.3.70-eap-177.
     Required by:
         project :backend.native:tests
      > Could not resolve org:Kotlin_KotlinRelease_1370_Compiler:1.3.70-eap-177.
         > Could not get resource 'https://buildserver.labs.intellij.net/guestAuth/repository/download/Kotlin_KotlinRelease_1370_Compiler/1.3.70-eap-177/teamcity-ivy.xml'.
            > Could not GET 'https://buildserver.labs.intellij.net/guestAuth/repository/download/Kotlin_KotlinRelease_1370_Compiler/1.3.70-eap-177/teamcity-ivy.xml'. Received status code 400 from server: Bad Request

**Comment by artdfel** [comment]
If there is no need to perform these tests, I think you can try to workaround it like described [here](https://github.com/JetBrains/kotlin-native/issues/2677). Also, just out of curiosity, what's the reason behind building release and EAP versions of the compiler? AFAIK, built artifacts can be found in the Kotlin repository.

**Comment by serebit** [comment]
`v1.3.70-eap2` fails to compile with that flag, but it's with an actual compile error, so it's fine. Thanks for the fix!

To answer your question, all the packages in this linux distribution that *can* be built from source (i.e. aren't proprietary) *are* built from source. If this rule weren't in place, we'd be using the prebuilt artifacts. If you're asking why not just use Gradle, I do for my own projects; but we like to integrate as much of the build process into our package system as possible, and Kotlin/Native is a nice thing to be able to use from the command line as well. Does that make sense?

**Comment by serebit** [comment]
It would appear that more tags have either this problem or a general compile error when attempting to build locally. These include:
- `1.3.60` (HTTP)
- `1.3.70-eap1` (HTTP)
- `1.3.70-eap2` (HTTP in backend tests, compile error elsewhere)
- `1.3.70-eap3` (Compile)
- `1.3.70` (Compile)

As someone who's attempting to maintain a locally built copy of this software, this is extremely frustrating. I'm glad the HTTP errors are no longer showing up, but if a release is tagged as a final release for a version, I expect it to be able to compile. While I understand that most won't be compiling their own versions of Kotlin/Native, what if someone wishes to use the experimental targets and has to build it locally to do so? I know this isn't a high priority at the moment, but I think it should be addressed as soon as possible.

**Comment by serebit** [comment]
Add `1.3.71` to that list.

**Comment by serebit** [comment]
Created new issue at #4016, as it's a separate problem.
