### ISSUE TITLE
Cannot detach stdlib HashMap after iteration

### ISSUE THREAD

**Issue by Dominaezzz** [JetBrains/kotlin-native#3801]
Kotlin 1.3.61
OS: Arch Linux
Target: LinuxX64

```
val graph = DetachedObjectGraph {
    val map = mutableMapOf<String, String>()
    for (entry in map.entries) {
        // Do nothing.
    }
    map
} // kotlin.IllegalStateException: Illegal transfer state
println(graph.attach())
```

This happens if `entries`, `keys` or `values` is explicitly iterated through. It doesn't happen when the property is just called.

**Comment by olonho** [comment]
Yes, this is unfortunate result of cyclic garbage produced by iterators.
Smth like
```
import kotlin.native.concurrent.*

fun main()  {
 val graph = DetachedObjectGraph {
    fun makeMap(): Map<String, String> {
     val map = mutableMapOf<String, String>()
     for (entry in map.entries) {
         // Do nothing.
     }
     return map
    }
    val map = makeMap()
    kotlin.native.internal.GC.collect()
    map
 } 
 println(graph.attach())
}
```
does the job.

**Comment by Dominaezzz** [comment]
Oh okay. Is this something that needs to be "fixed" or should this be expected from iterators?

**Comment by olonho** [comment]
Generally, for cases where complex cyclic garbage is created - it's better collect it before detaching.

**Comment by Dominaezzz** [comment]
Ah, in that case, I guess this issue can be closed. I strongly suggest it should be mentioned `CONCURRENCY.md`.

**Comment by olonho** [comment]
Updated docs with 1e74b8effa828f61b5c9b64a146be00cd2bbf145
