### ISSUE TITLE
Same filename in multiple modules seems to drop all one but one of them, resulting in "unresolved reference" errors

### ISSUE THREAD

**Issue by digitalheir** [JetBrains/kotlin-native#3808]
My multi-platform project was not compiling, because Gradle said it could not resolve my function. But I could jump to its definition in Android Studio. It took me a minute to realise that I depended on global functions defined in the same package in files with the same name across multiple modules.

i.e.

┌ `module1` with `myFunctions.kt` and `fn1`
├ `module2` with `myFunctions.kt` and `fn2`
└ `app` which depends on `module1` and `module2` can't see both `fn1` and `fn2`

See this example repository for a variation of this problem:

https://github.com/digitalheir/kotlinReproduceUnresolvedReferenceBug

```Type inference failed: fun <D : Comparable<D>, T : D> sortMe(items: Array<T>): Collection<Wrapper<D>>
cannot be applied to
(kotlin.collections.ArrayList<SortableThing> /* = java.util.ArrayList<SortableThing> */)
```

Maybe the Kotlin compiler / IDE should disallow this practice of having the same package+filename in multiple modules with a more comprehensive error message, or merge the files so that it just works.

**Comment by artdfel** [comment]
Hello! Sorry if I'm missing something, but this problem seems to be related to Kotlin at all rather than Kotlin/Native. So, I would recommend opening an issue in the [YouTrack](https://youtrack.jetbrains.com/issues/KT), this tracker should be used for K/N-specific issues preferably.

**Comment by digitalheir** [comment]
@artdfel Thank you. I have replicated this issue at https://youtrack.jetbrains.com/issue/KT-36288
