### ISSUE TITLE
EXC_BAD_ACCESS in Kotlin_Array_get

### ISSUE THREAD

**Issue by shadowsheep1** [JetBrains/kotlin-native#3831]
Hi guys!

I got this `Thread 1: EXC_BAD_ACCESS (code=1, address=0x8)`

![image](https://user-images.githubusercontent.com/16268789/73929562-4e78e080-48d5-11ea-84e8-291774e0c5d1.png)

when I do something like that:

```
expect val expectGlobalVal: MyClass

val myClass2 = MyClass2(myClass = expectGlobalVal) // <- Thread 1: EXC_BAD_ACCESS (code=1, address=0x8)
```

**Android**

```
actual val expectGlobalVal: MyClass by lazy {
    MyClass(Platform.name)
}
```

**iOS**

```
actual val expectGlobalVal: MyClass  by lazy {
    MyClass(Platform.name)
}

```

I read it should be a wrong order initialization problem. Is that right? My framework breaks as soon as I try to use it.

Sample project to reproduce it

https://github.com/shadowsheep1/kotlin-mpp-playground/tree/EXC_BAD_ACCESS

Is that something I must not do in Kotlin Native?

**Comment by artdfel** [comment]
Hello @shadowsheep1! Thank you for the report, we managed to reproduce the error and now searching for its cause. Please wait for updates.

**Comment by artdfel** [comment]
Minimized repro:
####  `common.kt`
```
expect val commonGlobalVal: Int

val ref = commonGlobalVal
```
#### `native.kt`
```
actual val commonGlobalVal: Int  by lazy {
    42
}

fun main(){
    println(commonGlobalVal)
    println(ref)
}
```
Compile by `konanc -g -o fail.kexe -Xmulti-platform -no-endorsed-libs native.kt common.kt -Xcommon-sources=common.kt`.

**Comment by homuroll** [comment]
Create a YT issue: https://youtrack.jetbrains.com/issue/KT-43604. The cause is undefied initialization order of top-level properties.
