### ISSUE TITLE
Could not find or load main class org.jetbrains.kotlin.cli.utilities.MainKt

### ISSUE THREAD

**Issue by cup** [JetBrains/kotlin-native#3838]
Using Kotlin from here:

https://github.com/JetBrains/kotlin/releases/latest

I get this:

~~~
$ PATH=jdk-13.0.2/bin:"$PATH" \
> kotlin-native-windows-1.3.61/bin/kotlinc
Error: Could not find or load main class
   org.jetbrains.kotlin.cli.utilities.MainKt
Caused by: java.lang.ClassNotFoundException:
   org.jetbrains.kotlin.cli.utilities.MainKt
~~~

Repost as the previous issue was closed in error.

**Comment by cup** [comment]
https://github.com/JetBrains/kotlin-native/issues/3687

**Comment by artdfel** [comment]
Hello! Can you extend the issue with detailed instructions? I've seen that you tried other JDK already, but with no luck. Your system configuration info can help too.

**Comment by cup** [comment]
Im not sure what other information you need...

**Comment by artdfel** [comment]
What is your JDK vendor? Have you seen [this](https://github.com/JetBrains/kotlin-native/blob/master/RELEASE_NOTES.md#microsoft-windows-support) paragraph, are you meeting these requirements?

**Comment by cup** [comment]
> What is your JDK vendor?

Im just getting it from here:

https://jdk.java.net

I can get it somewhere else if need be

> Have you seen this paragraph, are you meeting these requirements?

Yeah, I have 64-bit Windows

**Comment by msink** [comment]
On Windows 10 64 bit:
```
D:\kotlin-native-windows-1.3.61\bin>set PATH="C:\Program Files\Java\jdk-11.0.5\bin\java.exe";%PATH% && kotlinc
error: you have not specified any compilation arguments. No output has been produced.
```

**Comment by cup** [comment]
I dont know where youre getting that Java, but again Im using this:

~~~
$ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
~~~

https://jdk.java.net

**Comment by msink** [comment]
I mean you surely run not in Windows command prompt.

**Comment by cup** [comment]
Ah, so it seems Cygwin is not currently supported. If I run with Command Prompt,
it works:

~~~
C:\> path C:\cygwin64\bin
C:\> path jdk-11\bin;%PATH%
C:\> kotlin-native-windows-1.3.61\bin\kotlinc
error: you have not specified any compilation arguments. No output has been 
produced.
~~~

but if I run the same commands with Cygwin, it fails:

~~~
$ PATH=jdk-11/bin:$PATH
$ d2u kotlin-native-windows-1.3.61/bin/kotlinc
$ d2u kotlin-native-windows-1.3.61/bin/run_konan
$ kotlin-native-windows-1.3.61/bin/kotlinc
Error: Could not find or load main class
   org.jetbrains.kotlin.cli.utilities.MainKt
Caused by: java.lang.ClassNotFoundException:
   org.jetbrains.kotlin.cli.utilities.MainKt
~~~

**Comment by msink** [comment]
Didn't use cygwin for years, in MSYS2 and Git it works.

**Comment by cup** [comment]
Cygwin is still and active project, last release Dec 2019. So it should be supported.

**Comment by msink** [comment]
You anyway will install MSYS2 to do anything not trivial, because Kotlin/Native sysroot is MSYS2 based.

**Comment by cup** [comment]
I am not installing MSYS2. I will try to get Kotlin to work with Cygwin, or wait until a fix is released.

**Comment by msink** [comment]
It's impossible - cygwin ABI is very different from MinGW, it will be entire new port, and I doubt in much interest in so big effort.

**Comment by cup** [comment]
@msink I dont think you understand.

I am using Cygwin only for the shell. Cygwin offer the package:

~~~
mingw64-x86_64-gcc-core
~~~

which produced Windows native binaries, just like MSYS2. This package has been
available for many years. It includes the compiler:

~~~
x86_64-w64-mingw32-gcc.exe
~~~

**Comment by msink** [comment]
Well maybe.
But I personally prefer not to deal with subtle differences between сygwin and msys2.

**Comment by cup** [comment]
It looks to work with Cygwin if you use the Batch file instead of the Shell 
script:

~~~
$ PATH=jdk-11/bin:$PATH kotlin-native-windows-1.3.61/bin/kotlinc.bat
error: you have not specified any compilation arguments. No output has been 
produced.
~~~

that should probably be documented somewhere. Thanks for the replies.
