### ISSUE TITLE
Enum class cases somehow converted to lower case in ObjC

### ISSUE THREAD

**Issue by daxios-learn** [JetBrains/kotlin-native#3846]
I have an enum in Kotlin
```kotlin
enum class StbFeatures(val rawValue: Int) {
    messageCenter(1),
    favoriteLocation(2),
    trainingCenter(3)
}
```

All the cases are exported to ObjC framework in lower case:
```Obj-C
messagecenter
favoritelocation
trainingcenter
```

Is there anyway to preserve the case name ?

**Comment by artdfel** [comment]
Thank you for the report, @daxios-learn ! Seems like currently K/N supports the correct export only for the UPPERCASE_UNDERSCORED names of enum constants, which partially responds to the coding [convention]( https://kotlinlang.org/docs/reference/coding-conventions.html#property-names):

> For enum constants, it's OK to use either uppercase underscore-separated names (enum class `Color { RED, GREEN }`) or regular camel-case names starting with an uppercase first letter, depending on the usage.

So, if you apply this convention, everything should work correctly. Or, if you really want to save lowercase here, just separate words with underscores. This code:
```
enum class StbFeatures(val rawValue: Int) {
    message_Center(1), //or MESSAGE_CENTER(1)
    favorite_Location(2),
    training_Center(3)
}
```
should export names as 
```
@property (class, readonly) ... *messageCenter __attribute__((swift_name("messageCenter")));
@property (class, readonly) ... *favoriteLocation __attribute__((swift_name("favoriteLocation")));
@property (class, readonly) ... *trainingCenter __attribute__((swift_name("trainingCenter")));
```
About the regular camel-case names, this part of convention is not supported yet.

**Comment by daxios-learn** [comment]
Thanks @artdfel for the information.

Using UPPERCASE_UNDERSCORED works nicely for iOS, and also it fits Java convention. 

Thank you !

**Comment by necrogt4** [comment]
I've run into an issue where I'm using uppercase/underscored enums originally from a Kotlin/Android project now being shared via Kotlin/Native to an iOS project and the names are being implicitly converted to camel case.

How does one tell the compiler to use "UPPERCASE_UNDERSCORED" for iOS?

**Comment by artdfel** [comment]
Hello, @necrogt4! Do you mean you would like to have the same enums appearance in the final framework headers? AFAIK, this does not correspond well to the Objective-C coding conventions(according to either [Apple](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html) or [Google](http://google.github.io/styleguide/objcguide.html) recommendations).

**Comment by necrogt4** [comment]
Hey Artyom,

Yes, I would like to have the same enum appearance in the final framework
headers. Their names are used as identifiers in a third party analytics
system and need to be identical across platforms.

I know there are other ways to do this but if it's possible to have the
enum names kept the same as their Kotlin source that would be ideal.

Is it possible with theKotlin/Native -> ObjC/Swift compiler?

**Comment by PhilipDukhov** [comment]
Maybe it's possible to add a possibility to choose preferred style? 

I come to kotlin from iOS and using uppercase underscore-separated seems pretty distracting for me, and for now I choose to use camel-case in kotlin and live on with lover-cased names on iOS as lesser evil for me.

**Comment by SvyatoslavScherbina** [comment]
It should be possible. That's why this YouTrack issue is open: https://youtrack.jetbrains.com/issue/KT-40796
