### ISSUE TITLE
`pthread_threadid_np` not available in `platform.posix` on macOS

### ISSUE THREAD

**Issue by nlbuescher** [JetBrains/kotlin-native#3854]
This seems to be due to the [defines specified in the `posix.def` file](https://github.com/JetBrains/kotlin-native/blob/8f7ebe7f511d5700cf559c854f9202bf55240e11/platformLibs/src/platform/osx/posix.def#L16).

The compilerArgs defined the `_XOPEN_SOURCE` macro, which excludes most of the `_np` functions defined in `pthread.h` since those functions are wrapped by:

```c
#if (!defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE)) || defined(_DARWIN_C_SOURCE) || defined(__cplusplus)
```

One solution for this particular problem would be to define `_DARWIN_C_SOURCE`, but there might be side-effects to that.

**Comment by olonho** [comment]
Fixed with e8a6aeb48e6dadb24afc138d809abc12ef275d0b
