### ISSUE TITLE
Bug: Json boolean is converted to 0/1 in iOS

### ISSUE THREAD

**Issue by daxios-learn** [JetBrains/kotlin-native#3857]
```kotlin
import platform.Foundation.*
actual fun convertToJson(map: Map<String, Any>): String {
    val data = NSJSONSerialization.dataWithJSONObject(obj = map, options = 0, error = null)
        ?: throw Exception("Cannot convert data to JSON. $map")
    return NSString.create(data = data, encoding = NSUTF8StringEncoding) as String
}
```

If we use this to convert a map to Json string, any boolean will be converted to 0 or 1, which is not expected. It should be `true` or `false`.

I'm using `id 'org.jetbrains.kotlin.multiplatform' version '1.3.50'`

**Comment by artdfel** [comment]
Hello! AFAIK, this is correct behavior from Kotlin/Native point of view. Kotlin's `Boolean` is translated to Objective-C as a `<FrameworkName>Boolean` subclass of `<FrameworkName>Number` subclass of an `NSNumber`. So, the value here would be 1/0, and so it is being serialized as 1/0. Consider looking at [this SO discussion](https://stackoverflow.com/questions/13615451/how-do-i-get-nsjsonserialization-to-output-a-boolean-as-true-or-false). The problem there is the same, and it originates from `NSJSONSerialization` implementation details.

**Comment by daxios-learn** [comment]
Oh i see. That's very helpful info. Thanks @artdfel
