### ISSUE TITLE
Compiler plugin

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3872]
I want to use "Google Jetpack Compose" Kotlin compiler plugin
(https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/compose/compose-compiler-hosted/) in Kotlin/Native backend.
Is it possible, and how difficult?
Any starting points to learn?

For now I see that, from high level point of vew, it is very similar to coroutines plugin - rewrites code and adds additional argument to all functions annotated as `@Composable`

**Comment by olonho** [comment]
It could be possible, as IR is very similar between JVM and Native backends on that level, would be interesting to see your progress here.

**Comment by msink** [comment]
Well, first question - what is recommended way to apply compiler plugin?
In Google repository I see:

https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/compose/compose-runtime/build.gradle#31
```
dependencies {
  kotlinPlugin project(path: ":compose:compose-compiler")
}
```

https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/buildSrc/src/main/kotlin/androidx/build/AndroidXUiPlugin.kt#60
```
  is KotlinBasePluginWrapper -> {
    val conf = project.configurations.create("kotlinPlugin")
    project.tasks.withType(KotlinCompile::class.java).configureEach { compile ->
      compile.dependsOn(conf)
      compile.doFirst {
        if (!conf.isEmpty) {
          compile.kotlinOptions.freeCompilerArgs += "-Xplugin=${conf.files.first()}"
        }
      }
    }
  }
```

**Comment by SvyatoslavScherbina** [comment]
`-Xplugin=` compiler flag is the recommended way to apply a compiler plugin, at least from compiler point of view.
