### ISSUE TITLE
Type mismatch: inferred type is ULong but NSUInteger /* = UInt */ was expected

### ISSUE THREAD

**Issue by VincentChen1212** [JetBrains/kotlin-native#3883]
Hi

In my iosMain
```
val delegate = object : NSObject(), NSURLSessionDelegateProtocol {

        override fun URLSession(session: NSURLSession,
                                didReceiveChallenge: NSURLAuthenticationChallenge,
                                completionHandler: (NSURLSessionAuthChallengeDisposition, NSURLCredential?) -> Unit) {
            val serverTrust = didReceiveChallenge.protectionSpace.serverTrust
            var result: SecTrustResultType = 0u

            val serverCertificate = SecTrustGetCertificateAtIndex(serverTrust, 0)
            val serverCertificateData = SecCertificateCopyData(serverCertificate)
            val data = CFDataGetBytePtr(serverCertificateData)
            val size = CFDataGetLength(serverCertificateData)
            val cert1 = NSData.dataWithBytes(data, size.toULong())
        }
    }
```

NSData.dataWithBytes
```
@kotlinx.cinterop.ObjCMethod public external fun platform.Foundation.NSDataMeta.dataWithBytes(bytes: kotlinx.cinterop.COpaquePointer? /* = kotlinx.cinterop.CPointer<out kotlinx.cinterop.CPointed>? */, length: platform.darwin.NSUInteger /* = kotlin.ULong */): platform.Foundation.NSData { /* compiled code */ }
```

it's fine.

but when I compile

I got error
```
Type mismatch: inferred type is ULong but NSUInteger /* = UInt */ was expected
```

Is it a bug ???

Thanks.

**Comment by artdfel** [comment]
Hello, @VincentChen1212! `NSUInteger` is type aliased differently for x32 and x64 targets, so it might be the problem here. This code should be correct for ios_arm64 and ios_x64, but erroneous for ios_x32. What platform are you targeting here?

**Comment by VincentChen1212** [comment]
@artdfel 
Thanks for your helping.

Yes, My platform include - Arm64/Arm32/X64，and
```
        val iOSArm64Main by getting
        val iOSArm32Main by getting
        val iOSX64Main by getting

        iOSArm64Main.dependencies {
            implementation("io.ktor:ktor-client-ios:latest.release")
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-native:latest.release")
        }

        configure(listOf(iOSArm32Main, iOSX64Main)) {
            dependsOn(iOSArm64Main)
        }
```

so, I only write code in Arm64 Platform

Are there any solution to fix it ?

Thanks.

**Comment by artdfel** [comment]
First of all, I would say it is a bit optimistic to use platform-specific code as a source for a different bitness target. I found an example of dealing with such an issue, there is a [link](https://kotlinlang.slack.com/archives/C3SGXARS6/p1579667924123100?thread_ts=1579574116.085700&cid=C3SGXARS6) to the kotlinlang Slack. Rephrasing this answer, just for the record:
One can avoid such issues by extracting all common logic to a separate common-iOS source set, and provide expect functions, that consume platform-dependently typed arguments with two wrappers - one consuming the `UInt` value, and one - `ULong`. Depend on this common set with your platform ones, and actualize wrappers like this:
`commoniOS.kt`
```
import kotlinx.cinterop.*
import platform.Foundation.*
import platform.darwin.*
//those imports should be presented to resolve correctly in the compile-time, even if the IDE shows it as unresolved

expect private fun NSData.Companion.myDataWithBytes(data: CPointer<UByteVarOf<UInt8>>?, uLong: ULong): Any
expect private fun NSData.Companion.myDataWithBytes(data: CPointer<UByteVarOf<UInt8>>?, uInt: UInt): Any

object delegate : NSObject(), NSURLSessionDelegateProtocol {

    override fun URLSession(session: NSURLSession,
                            didReceiveChallenge: NSURLAuthenticationChallenge,
                            completionHandler: (NSURLSessionAuthChallengeDisposition, NSURLCredential?) -> Unit) {
        val serverTrust = didReceiveChallenge.protectionSpace.serverTrust
        var result: SecTrustResultType = 0u

        val serverCertificate = SecTrustGetCertificateAtIndex(serverTrust, 0)
        val serverCertificateData = SecCertificateCopyData(serverCertificate)
        val data = CFDataGetBytePtr(serverCertificateData)
        val size = CFDataGetLength(serverCertificateData)
        val cert1 = NSData.myDataWithBytes(data, size)
    }
}
```
`actualArm64.kt`
```
actual private fun NSData.Companion.myDataWithBytes(data: CPointer<UByteVarOf<UInt8>>?, uLong: ULong): Any {
    return dataWithBytes(data, uLong)
}
actual private fun NSData.Companion.myDataWithBytes(data: CPointer<UByteVarOf<UInt8>>?, uInt: UInt): Any {
    return dataWithBytes(data, uInt.toULong())
}
```
`actualArm32.kt`
```
actual private fun NSData.Companion.myDataWithBytes(data: CPointer<UByteVarOf<UInt8>>?, uLong: ULong): Any {
    return dataWithBytes(data, uLong.toUInt())
}
actual private fun NSData.Companion.myDataWithBytes(data: CPointer<UByteVarOf<UInt8>>?, uInt: UInt): Any {
    return dataWithBytes(data, uInt)
}
```
This particular example is quite dirty, but I sketched that to prove the idea. Adding `kotlin.mpp.enableGranularSourceSetsMetadata=true` to your `gradle.properties` can make things a bit prettier in IDE, but don't rely on this too much - the is a very experimental feature for now.

**Comment by VincentChen1212** [comment]
@artdfel 
Thanks for your helping

Now, I get "Expected declaration cannot be private"
I can't find solution, so I need to actual every platforms (android/jvm/androidNative...)

Are there any good solutions to fix this?

Thanks

**Comment by artdfel** [comment]
Yes, using the `private` visibility modifier is incorrect here, consider changing it on the `internal` please. I'll fix it in the previous post.
The problem with conflicting overloads was expectable here, so please consider changing your project structure to avoid dependencies between leaf nodes(source sets targeting an exact platform) of your multiplatform project. As I said, it seems reasonable here to create an intermediate source set, being dependant on your commonMain source set and dependency for all your iOS source sets.

**Comment by VincentChen1212** [comment]
@artdfel  
Thanks for your helping
Finally. I Fix this question, although solution isn't the same above, but very near.

Thanks.
