### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_IosfwFrameworkMessage

### ISSUE THREAD

**Issue by algidrus** [JetBrains/kotlin-native#3899]
Hello
I've created a test sample to show an issue with Undefined symbol occurs on compile stage by Xcode a project with Framework (iosArm64) built by Kotlin/Native.
It occurs only on real device target (for me it is iPhone 8 Plus).
If I use  emulator (iosX64) framework links fine and Xcode application works.

============  Kotlin/native source ============
package test

import kotlin.text.*
import kotlin.native.concurrent.*

class FrameworkMessage {
    fun getFrameworkMessage(): String = "This is a framework message"
}

fun findSum(br: ByteArray): Double {
    var sum: Double = 0.0
    for (i in 0..br.lastIndex) {
        sum+=br[i].toDouble()
    }
    return sum
}

fun findSum(br: Array<UByte>): Double {
    var sum: Double = 0.0
    for (i in 0..br.lastIndex) {
        sum+=br[i].toDouble()
    }
    return sum
}

fun findSum(br: Array<UInt>): Double {
    var sum: Double = 0.0
    for (i in 0..br.lastIndex) {
        sum+=br[i].toDouble()
    }
    return sum
}

@kotlin.ExperimentalStdlibApi
fun main(args: Array<String>)
{
    var sum = 0.0
    val arr_b = byteArrayOf(10.toByte(),
                          20.toByte(),
                          30.toByte(),
                          40.toByte(),
                          50.toByte(),
                          60.toByte(),
                          70.toByte(),
                          80.toByte(),
                          90.toByte())

    sum = findSum(arr_b)
    println("Sum = $sum")

    val arr_ub = Array<UByte>(9) { i -> ((i+1)*10).toUByte() }
    sum = findSum(arr_ub)
    println("Sum = $sum")

    val arr_ui = Array<UInt>(9) { i -> ((i+1)*10).toUInt() }
    sum = findSum(arr_ui)
    println("Sum = $sum")
}

============= build.gradle.kts part ===============
    val iosFrameworkName = "iosfw"
    val libName = "testlib"

        iosArm64().apply {
            binaries {
                framework {
                    baseName = iosFrameworkName
                    isStatic = true
                }              
                staticLib {
                    baseName = libName
                }
            }
        }

        iosX64().apply {
            binaries {
                framework {
                    baseName = iosFrameworkName
                    isStatic = true
                }              
                staticLib {
                    baseName = libName
                }
            }
        }

============= Xcode part of sample ==============
import SwiftUI
import iosfw

struct ContentView: View {
 
    var body: some View {
        let fm: FrameworkMessage = FrameworkMessage()
        return Text(fm.getFrameworkMessage())
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

**Comment by artdfel** [comment]
Hello, @algidrus! Unfortunately, I was unable to reproduce this issue locally. How do you add the framework to the Xcode project? Seems like the device one is just missing here.

**Comment by algidrus** [comment]
Hi! 
I've added a path to the framework in a section "Search Paths"->"Framework Search Paths".  Then I've added the framework to the "Framework, Libraries, and Embedded Content". 
Clean build folder and recompile project by menu "Product"->"Clean build folder", "Product"->"Build"
This instruction works fine for iosX64 (emulator), but the same actions with a iosArm64 framework fails.

**Comment by artdfel** [comment]
Ok, and what about the framework path, are you sure that it's the same for both of your targets? How does the Gradle script define it?

**Comment by algidrus** [comment]
The iosArm64 framework has another path in the same up directory tree that the iosX64 framework (e.g. ../build/iosX64/frameworkname  and ../build/iosArm64/frameworkname). To compile iOS project I manually change the last name in path settings from iosX64 to iosArm64 and anew remove/add iosArm64 framework to the "Framework, Libraries, and Embedded Content". Clean and recompile.

**Comment by artdfel** [comment]
Okay, so the wrong framework should not be the cause here. Maybe the problem is that the source set is not connected to the simulator target? Is this class presented correctly in both frameworks headers?
It's hard to say anything specific for now. It would be nice if some kind of reproducer can be shared. 
Do you have the Kotlinlang Slack [invitation](http://slack.kotlinlang.org/?_ga=2.194654574.23958370.1583131289-1194240550.1578557352)? Such practical issues are easier to discuss in a chat rather than the GH issue.

**Comment by algidrus** [comment]
You are right, framework works fine now. I've created new iOS application instead of previous, and it new one works. It seems to be was something wrong with some settings in the old iOS app. Sorry for wasted you time on this issue.
