### ISSUE TITLE
support usage of newest iOS sdk features with targeting on old ios sdk

### ISSUE THREAD

**Issue by Alex009** [JetBrains/kotlin-native#3912]
My iOS project have target iOS sdk - 12.0 and i want add support of new iOS 13 feature, for iOS 13 devices only.
in iOS world i do:
```
if #available(iOS 13.0, *) {
    // 13.0+ code
} else {
    // pre 13.0 code
}
```
and it works. Next i try it in kotlin:
```
if (UIDevice.currentDevice.systemVersion.compareTo("13.0") < 0) {
    this.barTintColor = backgroundColor
    this.titleTextAttributes = textAttributes
    this.tintColor = tintColor
} else {
    val appearance = UINavigationBarAppearance().apply {
        configureWithDefaultBackground()
        this.backgroundColor = backgroundColor
        textAttributes?.let { this.titleTextAttributes = it }
    }
    this.scrollEdgeAppearance = appearance
    this.standardAppearance = appearance
    this.tintColor = tintColor
}
```
and it compiled, but on application startup it crash with error:
```
dyld: Symbol not found: _OBJC_CLASS_$_UINavigationBarAppearance
  Referenced from: /Users/alekseymikhailovwork/Library/Developer/CoreSimulator/Devices/61F79B47-464F-4B05-B486-9D81F093EBB3/data/Containers/Bundle/Application/2C6C64DC-1613-4A99-999A-EF18C9881635/moko-widgets.app/Frameworks/MultiPlatformLibrary.framework/MultiPlatformLibrary
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
 in /Users/alekseymikhailovwork/Library/Developer/CoreSimulator/Devices/61F79B47-464F-4B05-B486-9D81F093EBB3/data/Containers/Bundle/Application/2C6C64DC-1613-4A99-999A-EF18C9881635/moko-widgets.app/Frameworks/MultiPlatformLibrary.framework/MultiPlatformLibrary
```

MultiPlatformLibrary.framework was strongly linked with ios13 sdk and when i run it on ios 12 sdk it can not find classes, what was added only in ios 13.

i think we should set target ios sdk in gradle, in iOS configuration. and generated framework should not require existance of classes what was added in newer versions of iOS.

**Comment by idstein** [comment]
I think this is not supported. @SvyatoslavScherbina is it planned to support weak import attributes in Kotlin/Native?

Compilation will based on min / targed SDK version weak link any function that is imported, but not available on min SDK.
https://opensource.apple.com/source/xnu/xnu-2050.18.24/EXTERNAL_HEADERS/AvailabilityMacros.h.auto.html

**Comment by SvyatoslavScherbina** [comment]
It is planned to fix at least this particular case (`UINavigationBarAppearance`). I'm not sure that it actually makes use of weak import attributes though.

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-37180
