### ISSUE TITLE
[BUG] HashMap.findKey blocks a process 

### ISSUE THREAD

**Issue by IgorKey** [JetBrains/kotlin-native#3918]
Hi! I have some code like this:
` if (accepts.contains(fd.convert()) || connects.contains(fd.convert()))` where accepts and connects are **hashSets** created by mutableSet<Int>
Sometimes (one of ten attempts), this block of code freezes the process... 

stacktrace:

`2120 Thread_5372691
    + 2120 kfun:kotlin.collections.HashMap.findKey#internal  (in libdrill_agent.dylib) + 356  [0x10928c234]  HashMap.kt:246
    +   2120 kfun:kotlin.collections.HashMap.hash#internal  (in libdrill_agent.dylib) + 398  [0x10928b43e]  HashMap.kt:193
    +     2120 ???  (in <unknown binary>)  [0x70000086a568]
    +       2120 _sigtramp  (in libsystem_platform.dylib) + 29  [0x7fff66e5f42d]
    +         2120 crash_handler(int, __siginfo*, void*)  (in libjvm.dylib) + 106  [0x1087b7211]
    +           2120 VMError::report_and_die()  (in libjvm.dylib) + 429  [0x1087b6749]
    +             2120 fdStream::write(char const*, unsigned long)  (in libjvm.dylib) + 41  [0x10869416b]
    +               2120 _knbridge463  (in libdrill_agent.dylib) + 73  [0x10947eab9]  DrillIo.kt:53`

Can't provide an introducible app.

**Comment by SvyatoslavScherbina** [comment]
> Can't provide an introducible app.

This issue doesn't make much sense without a reproducer.

> HashMap.findKey blocks a process

Are you sure it blocks the process? Isn't it an infinite loop?

```
2120 _sigtramp  (in libsystem_platform.dylib) + 29  [0x7fff66e5f42d]
  2120 crash_handler(int, __siginfo*, void*)  (in libjvm.dylib) + 106  [0x1087b7211]
```

This probably means that you use K/N from signal handler. If so, please don't do this: signal handlers are known to allow using only limited subset of code (e.g. reentrant functions).

**Comment by IgorKey** [comment]
Thx. I’ll try to find a stable reproducer

**Comment by SvyatoslavScherbina** [comment]
Closing as incomplete. Feel free to reopen with a reproducer.
