### ISSUE TITLE
Kotlin native mpp project compileKotlinJvm task takes extremely long time (10 minutes)

### ISSUE THREAD

**Issue by mikezliu** [JetBrains/kotlin-native#3933]
Every time I make a change in my Kotlin mpp common project and recompile, it takes about 10 minutes. If I make a change in the Android project and recompile, it takes only a few seconds. The Android project is 90% kotlin, 10% java code.

Kotlin mpp project makes heavy use of lambdas, enums, etc (not sure if this makes a difference). I ran a profiled build with offline mode, and almost all the build time is due to the kotlin mpp common project's compileKotlinJvm task.

What steps can I take to further debug this issue and speed it up? I'm using a top of the line machine.

My computer specs:
Macbook Pro 2019, 2.4 GHz 8-core i9, 64GB Ram, all specs are maxed

IDE max heap size: 4 GB
Gradle daemon max heap: 8 GB
Kotlin daemon max heap: 8 GB

Gradle settings:

`
org.gradle.jvmargs=-Xmx8192m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.caching.debug=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.parallel.threads=4
org.gradle.workers.max=8

android.useAndroidX=true
android.enableJetifier=true
android.jetifier.blacklist=parceler-1.1.11.jar

kotlin.incremental=true
kapt.incremental.apt=true
kapt.use.worker.api=true
kapt.include.compile.classpath=false
android.databinding.incremental=true
`

Kotlin mpp project gradle file:

`
    sourceSets {
        commonMain.dependencies {
            api kotlin('stdlib-common')

            // Rx
            api "com.badoo.reaktive:reaktive:$reaktiveVersion"
            api "com.badoo.reaktive:reaktive-annotations:$reaktiveVersion"
            api "com.badoo.reaktive:coroutines-interop:$reaktiveVersion"

            api "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$kotlinCoroutineVersion"
            api "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$kotlinSerializationVersion"
            api "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$kotlinSerializationVersion"

            api "com.soywiz.korlibs.klock:klock:1.8.3"

            api "com.squareup.sqldelight:sqlite-driver:$sqldelightVersion"

            // Bug: Ktor has deadlocks
            // https://github.com/ktorio/ktor/issues/770
            // https://github.com/ktorio/ktor/issues/679
            // https://github.com/ktorio/ktor/issues/821
            api "io.ktor:ktor-client-core:$ktorVersion"
        }

        jvmMain.dependencies {
            api kotlin('stdlib-jdk8')

            api "com.squareup.sqldelight:coroutines-extensions:$sqldelightVersion"
            api "com.squareup.sqldelight:rxjava2-extensions:$sqldelightVersion"

            // Rx
            api "com.badoo.reaktive:rxjava2-interop:$reaktiveVersion"
            api "com.squareup.retrofit2:adapter-rxjava2:$retrofitVersion"
            api "io.reactivex.rxjava2:rxjava:2.2.9"

            // Networking
            api 'com.google.http-client:google-http-client-gson:1.30.1'
            api "com.squareup.retrofit2:retrofit:$retrofitVersion"
            api "com.squareup.retrofit2:converter-gson:$retrofitVersion"
            api "com.squareup.retrofit2:converter-scalars:$retrofitVersion"
            api "com.squareup.retrofit2:converter-simplexml:$retrofitVersion"
            api 'com.squareup.okio:okio:2.2.2'
            // Okhttp 3.13+ requires API level 21
            // io.ktor:ktor-client-okhttp only works on API level 21
            api "io.ktor:ktor-client-android:$ktorVersion"
            api "com.squareup.okhttp3:okhttp:3.12.3"
        }
`

**Comment by artdfel** [comment]
Hello! As the JVM target is not directly connected to the Kotlin/Native, I would recommend you to open a YouTrack issue [here](https://kotl.in/issue). Also, it would be nice to illustrate it with some example project, that could be used to measure progress.
