### ISSUE TITLE
[DOCS] outputKinds still referred to in docs

### ISSUE THREAD

**Issue by penn5** [JetBrains/kotlin-native#3958]
It was removed a while ago and is still confusingly referred to in the docs.

**Comment by artdfel** [comment]
Hello @penn5! Are you referring to the GRADLE_PLUGIN.md here? There is a note at the beginning about this option being presented only in the old `kotlin-platform-native` plugin, being deprecated(and finally [removed](https://github.com/JetBrains/kotlin-native/commit/2720c24821da0077db94ca61d02c1d171d6e866b) in 1.3.70). If you found this property somewhere else, please link it here - this should not be used in any other docs.

**Comment by penn5** [comment]
https://github.com/JetBrains/kotlin-native/blob/aafe34db13a902fa93609be593860e0d22c7b9e7/GRADLE_PLUGIN.md#dsl-example is the bit that caught me out. Perhaps that specific example should be updated

**Comment by artdfel** [comment]
This one is correct, as this paragraph lies inside of the _**`kotlin-platform-native` reference**_ section. Anyway, thanks for the notice, this part of the documentation will be rewritten soon.
