### ISSUE TITLE
Regex NamedGroups not working

### ISSUE THREAD

**Issue by ProbstDJakob** [JetBrains/kotlin-native#3968]
I wrote a RegularExpression in KotlinJvm and it worked, but after I ported my code over to KotlinNative (Multiplatform) and executed it, it failed with the error message:

```
Unknown look behind near index: 10
(?<=[\[,])(?:(?<lowerCase>(?<fromLowerCase>[a-z])-(?<toLowerCase>[a-z]))|(?<upperCase>(?<fromUpperCase>[A-Z])-(?<toUpperCase>[A-Z]))|(?<decimal>(?<fromDecimal>\d+)-(?<toDecimal>\d+))|(?<singleString>[a-zA-Z0-9]+))(?=[,\]])
          ^
```

But the same Code still executes fine in the JVM. I tested why this happens, with the follwoing expressions:

```
Regex("(?:test)")
Regex("(test)")
Regex("(?<namedGroup>test)")
```

And it seams, that the problem is not the NonCapturing Group, but rather the NamedGroupe. But I'm no quite sure if this is a failure of mine, a not fully implemented feature, or a bug.

**Comment by artdfel** [comment]
Hello, @ProbstDJakob! Thank you for the report, this code seems to be correct, and you've done everything right.🙂 This feature is missing from the Kotlin/Native, and it is incorrect from the Multiplatform point of view. Unfortunately, I cannot give you any fix arrival estimates on my own, as it has to be discussed on the implementation and priority.

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-41890
