### ISSUE TITLE
Reverse C++ interop: Proposal or alternatives?

### ISSUE THREAD

**Issue by sigmasoldi3r** [JetBrains/kotlin-native#3975]
I'm generating a shared library for use in a C++ programs, so it would be nice to have the option to wrap the structs into classes automatically.

Now what I'm doing is something like this (Really simple example):
```cpp
class Core
{
public:
  Core(mylib_core_ExportedSymbols* lib): lib(lib) {
    ref = lib->kotlin.root.Core.Core();
  }
  virtual ~Core() {
    lib->DisposeStablePointer(this->ref.pinned);
  }
private:
  mylib_core_kref_Core ref;
  mylib_core_ExportedSymbols* lib;
};
```

To wrap an exported kotlin class (Ie: `Core`), to avoid using long and tedious C struct plus static function combination.

So the question here is... It could be a future feature? Or there is any tool that generates automatically?

**Comment by artdfel** [comment]
Hi! This seems to be an interesting feature proposal, there are no such tools, or we are not informed of them. Contributions are always welcome. 🙂  The only thing I should ask - why this scheme does not include a class destructor calling `DisposeStablePointer` on this ref?

**Comment by sigmasoldi3r** [comment]
@artdfel Thanks for your reply! Well about the DisposeStablePointer, I didn't include it because of my ignorance, sorry 😅 I'm quite new using native interop that way, I've updated the example to make it more accurate! (Thanks for pointing it out!! 😄 )

**Comment by SvyatoslavScherbina** [comment]
Closing as answered.
