### ISSUE TITLE
Support non-NativeActivity Android executables

### ISSUE THREAD

**Issue by penn5** [JetBrains/kotlin-native#3985]
See #3957 - TL;DR I'd like a way to make executables like on the linux* targets, only with the Android toolchain

**Comment by penn5** [comment]
Ping? My project is still blocked on this. I've demoted it to side project, but it would still be really good to be able to finish it. Thanks!

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48078, closing.
