### ISSUE TITLE
iOS interop works incorrectly for classes that implement Map

### ISSUE THREAD

**Issue by sandwwraith** [JetBrains/kotlin-native#3991]
Look at these classes from [kotlinx.serialization](https://github.com/kotlin/kotlinx.serialization/blob/e6db6ab41c1ec2dfa1958e19c32c962573876806/runtime/commonMain/src/kotlinx/serialization/json/JsonElement.kt#L23):

```kotlin
public sealed class JsonElement {
    /**
     * Convenience method to get current element as [JsonObject]
     * @throws JsonException if current element is not a [JsonObject]
     */
    public open val jsonObject: JsonObject // implementation omitted
}

public data class JsonObject(val content: Map<String, JsonElement>) : JsonElement(), Map<String, JsonElement> by content {

   /**
     * Returns [JsonPrimitive] associated with given [key]
     *
     * @throws NoSuchElementException if element is not present
     * @throws JsonException if element is present, but has invalid type
     */
    public fun getPrimitive(key: String): JsonPrimitive // implementation omitted

    public override fun toString(): String {
        return content.entries.joinToString(
            separator = ",",
            prefix = "{",
            postfix = "}",
            transform = {(k, v) -> """"$k":$v"""}
        )
    }
}
```

Let's try to make a common code with the following functions:

```kotlin
class Proxy {
val json = Json(JsonConfiguration.Default)

fun retrieveJsonObject(): JsonObject = json.parseJson("{\"status_code\":1}").jsonObject
fun retrieveJsonElement(): JsonElement = json.parseJson("{\"status_code\":1}")
fun asString(element: JsonElement) = element.toString()
}
```

and call it from Swift:

```swift
let json1 = Proxy().retrieveJsonObject()
let json2 = Proxy().retrieveJsonElement()
let json3 = Proxy().json.parseJson(string: "{\"status_code\":1}")
let typeName = String(describing: type(of: json2))
let json5 = Proxy().asString(element: json2)

print("json1.description: " + json1.description)
print("json2.description: " + json2.description)
print("json3.description: " + json3.description)
print("json2.typeName: " + typeName)
print("json5: " + json5)
```

What we see as a result:

```
json1.description: ["status_code": 1]
json2.description: {
    "status_code" = 1;
}
json3.description: {
    "status_code" = 1;
}
json2.typeName: AppKMapAsNSDictionary
json5: {"status_code":1}
```

That result is incorrect (except for json5) for several reasons:

1. It all should be `{"status_code":1}` because that's what written in `JsonObject.toString` method.
2. `retreiveJsonObject` returns object of `[String : Kotlinx_serialization_runtimeJsonElement]` type. This prohibits us from calling actual JsonObject's functions, like `getPrimitive`. But at least, its `description` matches one for NSDictionary.
3. `retreiveJsonElement` and `parseJson` return strange `AppKMapAsNSDictionary` type (although json2 and json3 variables have type `Kotlinx_serialization_runtimeJsonElement`!)
Their description is very strange (same to `AnyObject` one?).
4. Moreover, they lead to runtime crash: if one tries to write `print("json2.jsonObject" + json2.jsonObject.description)`, this code **compiles** as Swift sees `jsonObject` function. In runtime, this line crashes with 

```
2020-03-17 18:34:53.717583+0300 iosApp[25620:5335875] -[AppKMapAsNSDictionary jsonObject]: unrecognized selector sent to instance 0x6000009553e0
2020-03-17 18:34:53.726283+0300 iosApp[25620:5335875] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppKMapAsNSDictionary jsonObject]: unrecognized selector sent to instance 0x6000009553e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23bcb154 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23baef6c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23bb10f8 _CF_forwarding_prep_0 + 120
	5   iosApp                              0x0000000101f29b3e $s6iosApp14ViewControllerC11viewDidLoadyyF + 4318
	6   iosApp                              0x0000000101f29f3b $s6iosApp14ViewControllerC11viewDidLoadyyFTo + 43
	7   UIKitCore                           0x00007fff46f03d96 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 83
	8   UIKitCore                           0x00007fff46f08cef -[UIViewController loadViewIfRequired] + 1084
```

I'd say that expected behaviour would be to retain actual types, and to save 'JsonObject implements Map' relationship if possible.

I assume same problem also applicable to Lists and other interop-ed collections, but I haven't checked.

**Comment by SvyatoslavScherbina** [comment]
> I'd say that expected behaviour would be to retain actual types, and to save 'JsonObject implements Map' relationship if possible.

This is not how interop is designed. Please avoid using public types extending standard collection interfaces.

**Comment by sandwwraith** [comment]
At least this problem deserves better UX (user should get a warning that such type can't be properly interoped and may crush in runtime). 

Any chances this part of design can be revisited and improved?

**Comment by SvyatoslavScherbina** [comment]
> At least this problem deserves better UX (user should get a warning that such type can't be properly interoped and may crush in runtime).

Indeed.

> Any chances this part of design can be revisited and improved?

We don't have any particular plans.

**Comment by SvyatoslavScherbina** [comment]
See also: https://youtrack.jetbrains.com/issue/KT-32500

**Comment by SvyatoslavScherbina** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-48079, closing.
