### ISSUE TITLE
Header warnings when overriding open member

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#3992]
```kotlin
abstract class C(open val a: A)

class D(override val a: B): C(a)

abstract class A

class B: A()
```

This gets you a header where class C and D are defined before the compiler knows the relationship (subclass, which can't be expressed with `@class` forward declarations) between B and A, so Obj-C warns that D's `a` is incompatible with C's `a`. The only way to suppress the warning seems to be to manually wrap the header in pragmas (our build tooling now rewrites the header to add this pragma 😄):
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wincompatible-property-type"
// rest of header here
#pragma clang diagnostic pop
```

Tested this with Kotlin 1.3.61 and 1.3.70: `konanc -p framework test.kt -o test`

**Comment by SvyatoslavScherbina** [comment]
Thanks!
Accidentally got fixed with #4114.
#4167 adds this particular test.
