### ISSUE TITLE
IntelliJ incomplete autocomplete

### ISSUE THREAD

**Issue by julKali** [JetBrains/kotlin-native#3994]
IntelliJ has a very limited set of autocomplete entries in K/N.

For demonstration, I created a Kotlin/JVM and a K/N project. I didn't change any config/setting except the name. Everything else is default and set by the Kotlin IntelliJ plugin.
Here are some screenshots that display the issue:

JVM:
![image](https://user-images.githubusercontent.com/17690423/76941455-5d06de80-68fc-11ea-9eaa-7e84818dce07.png)

Native:
![image](https://user-images.githubusercontent.com/17690423/76941503-727c0880-68fc-11ea-844b-831b25089ba5.png)

JVM:
![image](https://user-images.githubusercontent.com/17690423/76941521-7f98f780-68fc-11ea-9b7a-912a3bce3b2b.png)

Native:
![image](https://user-images.githubusercontent.com/17690423/76941550-8aec2300-68fc-11ea-9ac7-54301e21040f.png)

JVM:
![image](https://user-images.githubusercontent.com/17690423/76941591-9ccdc600-68fc-11ea-937a-b7fc5a3049b5.png)

Native:
![image](https://user-images.githubusercontent.com/17690423/76941615-a6efc480-68fc-11ea-923d-589cfd834e22.png)

As you can see, JVM suggest the map function when I start typing, while K/N does not. However, as you can see in the last pair of screenshots, both version support the map function.
I noticed that for the K/N project, IntelliJ tells me "Kotlin not configured":
![image](https://user-images.githubusercontent.com/17690423/76942163-925ffc00-68fd-11ea-9f47-54d616eec192.png)
However, clicking on "Configure" only provides options for JVM and JS. Also, I think that one could expect the Kotlin IntelliJ plugin to handle configuration so that new projects work out of the box.

I would love to see this fixed soon, as it hinders development drastically!

Gradle file for K/N (automatically generated):
```groovy
plugins {
    id 'org.jetbrains.kotlin.multiplatform' version '1.3.70'
}
repositories {
    mavenCentral()
}
kotlin {
    // For ARM, should be changed to iosArm32 or iosArm64
    // For Linux, should be changed to e.g. linuxX64
    // For MacOS, should be changed to e.g. macosX64
    // For Windows, should be changed to e.g. mingwX64
    mingwX64("mingw") {
        binaries {
            executable {
                // Change to specify fully qualified name of your application's entry point:
               entryPoint = 'sample.main'
                // Specify command-line arguments, if necessary:
                runTask?.args('')
            }
        }
    }
    sourceSets {
        // Note: To enable common source sets please comment out 'kotlin.import.noCommonSourceSets' property
        // in gradle.properties file and re-import your project in IDE.
        mingwMain {
        }
        mingwTest {
        }
    }
}

// Use the following Gradle tasks to run your application:
// :runReleaseExecutableMingw - without debug symbols
// :runDebugExecutableMingw - with debug symbols
```

**Comment by artdfel** [comment]
Hello, @julKali! Thank you for the report. I've found a similar issue in the YouTrack, check it [here](https://youtrack.jetbrains.com/issue/KT-37121). Its a bit more generalized but I'm sure that your problem has the same cause. The team working on it is already notified on your case, so you can just subscribe to that ticket and wait for updates.

**Comment by SvyatoslavScherbina** [comment]
Closing as duplicate.
