### ISSUE TITLE
Make Documentation accessible from Swift / ObjC when using a Kotlin/Native Framework

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/kotlin-native#4000]
Currently there is no documentation when I compile a Fat Framework for iOS, even when I put documentation in the common code. I'm not entirely sure where it should go, perhaps in the ObjC headers?

**Comment by benasher44** [comment]
Obj-C headers would be the right place

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-38600
