### ISSUE TITLE
Categories?

### ISSUE THREAD

**Issue by andymans** [JetBrains/kotlin-native#4001]
Hi Guys

Would it make sense to have your "native" samples/guides etc grouped by: 

"what platform/os is this app native to?" 

Right now I need to build a mac desktop app - and it looks as though I need to open up around 60 projects to see if any of them actually relate to what I'm working on?

Just a thought...

**Comment by SvyatoslavScherbina** [comment]
Thank you for the suggestion. We have plans to reorganize our samples, and we consider adding groups as a part of this rework.
