### ISSUE TITLE
Modular Framework Dependencies

### ISSUE THREAD

**Issue by kuuuurt** [JetBrains/kotlin-native#4013]
Hi!

We've been trying a multi-module approach for our frameworks with the 1.3.70 release.

Our current setup has feature modules which are dependent on a core module

`Feature 1 ---> Core <--- Feature 2`

Sample Feature dependency configuration:
```kotlin
sourceSets["commonMain"].dependencies {
    implementation(project(":shared:core"))
}
```

We're able to create the frameworks each feature however it's consuming core and packaging it inside the framework.

In swift, we want to use our class but each framework is making a copy of the classes inside core

```swift 
import Feature1
import Core

class MyClass {
   let myVar: MyKotlinClass // <-- From Core
   let myVar2: CoreMyKotlinClass // <-- From Feature 1
}
```

Is there a way to prevent this so we can just have the type from the Core module instead? 

Thanks in advance!

**Comment by SvyatoslavScherbina** [comment]
Hi.

> Is there a way to prevent this so we can just have the type from the Core module instead?

No. 1.3.70 includes support for multiple **independent** frameworks.

Please refer to the discussion in https://github.com/JetBrains/kotlin-native/issues/2423 for more details.

**Comment by kuuuurt** [comment]
Got it. Thanks! Closing this as a duplicate.
