### ISSUE TITLE
How can I access Kotlin/Native object in Objective-C/Swift code with multi-thread?

### ISSUE THREAD

**Issue by qiaoyuang** [JetBrains/kotlin-native#4022]
Hey, I encountered a problem. In my iOS project, I need access an Kotlin/Native object in worker thread. But Objective-C code can't use the DetachedObjectGraph. So, how can I do it? Thank you very much.

**Comment by artdfel** [comment]
Hello, @qiaoyuang! One can try to wrap the DetachedObjecttGraph class in your code, so the wrapper would be accessible from Objective-C. Also, can you describe your case a bit wider? Is freezing unacceptable here because of the need to mutate object by a different thread?

**Comment by qiaoyuang** [comment]
Hi, @artdfel , I try to wrap the DetachedObjecttGraph in Kotlin/Native, but the wrapper is also a Kotlin/Native class. So when I try to access wrapper in another thread, the application would crash. In my case, My iOS developer colleague want to create a singleton(Kotlin/Native class) in Objective-C code, and he want to access the singleton on multi-thread and change its status. So, this situation bothers us.

**Comment by artdfel** [comment]
Ah, I see. Maybe for your case, it would be helpful to use [`AtomicReference` property](https://github.com/JetBrains/kotlin-native/blob/61702a64c05951325500aee2fc67f0e4315aead6/FAQ.md#q-how-do-i-make-a-singleton-object-mutable) to represent the state of your singleton?

**Comment by qiaoyuang** [comment]
Yeah, I will try it, thank you~ @artdfel
