### ISSUE TITLE
objc_runtime_name breaks Swift 5.2 / Xcode 11.4

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#4025]
I filed a Swift issue, which ended up being marked as a dup of https://bugs.swift.org/browse/SR-12169. The central problem is objc_runtime_name: https://twitter.com/jckarter/status/1242883858950803456?s=20.

If possible, K/N should avoid outputting objc_runtime_name. I'm not sure how much work this is for the K/N team, but it appears using that attribute puts most K/N frameworks at risk for not working in Swift apps built with Xcode 11.4. There is no timeline for an updated Xcode that contains the fix merged to Swift to fix it (fix PR linked in the Swift issue).

**Comment by benasher44** [comment]
Match KT issue here: https://youtrack.jetbrains.com/issue/KT-36425.

Looks like we still output it here: https://github.com/JetBrains/kotlin-native/blob/v1.3.70-fixes/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExportHeaderGenerator.kt#L1174. But maybe this is no longer called?

**Comment by SvyatoslavScherbina** [comment]
Hi. Thank you for your concern!

> But maybe this is no longer called?

Exactly.

**Comment by benasher44** [comment]
Thanks!
