### ISSUE TITLE
Crash copying Obj-C/Kotlin number

### ISSUE THREAD

**Issue by benasher44** [JetBrains/kotlin-native#4051]
If you try to call copy on a number in this way, you get an exception. This should work, since Kotlin's number class inherits from `NSValue`, which implements `NSCopying`.

Repro:

test.kt
```kotlin
data class A(val m: Map<String, Any>) {
    constructor(): this(mapOf("test" to 1))
}
```

main.swift
```swift
import test

let a = A()
let copiedNum = (a.m["test"] as? NSObject)?.copy()
print(String(describing: copiedNum))
```

steps to run this together:
1. Put these files in the same directory
2. Build the test framework using: `konanc -p framework test.kt -target ios_x64 -o test`
3. Build swift using: `xcrun --sdk iphonesimulator swiftc -target x86_64-apple-ios12.0-simulator -F${PWD} -framework test -Xlinker -rpath -Xlinker $PWD main.swift`
4. Run the swift using: `xcrun simctl spawn -s 'iPhone 8' ${PWD}/main`

Crash:
```
2020-04-01 14:40:32.736 main[5659:8798622] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -getValue: only defined for abstract class.  Define -[KotlinInt getValue:]!'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107a0527e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00000001061bbb20 objc_exception_throw + 48
	2   Foundation                          0x000000010752b5e3 _NSRequestConcreteObject + 0
	3   Foundation                          0x000000010739f9ae -[NSNumber copyWithZone:] + 129
	4   main                                0x000000010610f63c main + 588
	5   libdyld.dylib                       0x0000000106f30c25 start + 1
	6   ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Tested with Kotlin 1.3.61 and 1.3.71 + Xcode 11.3.

**Comment by benasher44** [comment]
Any help with a workaround would be appreciated!

**Comment by SvyatoslavScherbina** [comment]
Thank you for the report!
This is known issue (see [KT-36204](https://youtrack.jetbrains.com/issue/KT-36204)), and it is already fixed in master (https://github.com/JetBrains/kotlin-native/pull/3964).
As a workaround, please try to implement `getValue:` methods manually (like in the PR), using Swift extensions or Objective-C categories.

**Comment by benasher44** [comment]
Ah cool thanks!

**Comment by benasher44** [comment]
Posted workaround in the KT issue
