### ISSUE TITLE
DSYM for Release Fat-Framework?

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/kotlin-native#4059]
I’m trying to release a library to my iOS team. The Debug version of the fat framework creates a DSYM folder, which is essential from my understanding to get desymbolicated stack traces. However, it’s also my understanding that the release version does certain optimizations in code. I want the optimized code, but I also want desymbolicated stack-traces in production. Is this possible?

```
tasks.create("buildReleaseFatFramework", org.jetbrains.kotlin.gradle.tasks.FatFrameworkTask::class) {
    baseName = iosFrameworkName

    destinationDir = File("$buildDir/fat-framework/release")

    from(
        iosX64.binaries.getFramework("RELEASE"),
        iosArm64.binaries.getFramework("RELEASE")
    )
}

tasks.create("buildDebugFatFramework", org.jetbrains.kotlin.gradle.tasks.FatFrameworkTask::class) {
    baseName = iosFrameworkName

    destinationDir = File("$buildDir/fat-framework/debug")

    from(
        iosX64.binaries.getFramework("DEBUG"),
        iosArm64.binaries.getFramework("DEBUG")
    )
}
```

**Comment by artdfel** [comment]
Hello, @ScottPierce! I think [this](https://kotlinlang.org/docs/reference/native/ios_symbolication.html) page would be helpful here. The `-Xg0` experimental flag should do the trick.

**Comment by ScottPierce** [comment]
@artdfel That seems to have worked. Thanks for pointing me in the right direction.

Why isn't this enabled by default?

**Comment by ScottPierce** [comment]
Actually - I must have made a mistake. I'm no longer seeing the dsyms with that compiler arg.

**Comment by ScottPierce** [comment]
Actually - I see - it works when compiling a dynamic framework, but if the framework is set to static, then it doesn't work. Is this a bug or intentional?

**Comment by SvyatoslavScherbina** [comment]
When your framework is static, the tool (typically Xcode) producing final binary with this static framework included is responsible for generating `.dSYM`.
`-Xg0` is required in this case too.

**Comment by ScottPierce** [comment]
Would the final binary be able to do that? How would it have the
information?

**Comment by SvyatoslavScherbina** [comment]
If you compile your static framework with `-Xg0`, then debug information will be embedded into the framework. Xcode then will use this information when producing `.dSYM`.

**Comment by ScottPierce** [comment]
@SvyatoslavScherbina So if I compile a static fat framework with this setting, and then include that framework in an iOS app, I should still get desymbolicated stack traces in production?

**Comment by SvyatoslavScherbina** [comment]
Yes.

**Comment by ScottPierce** [comment]
@SvyatoslavScherbina I tried it out, and I'm seeing that class names, but I'm not getting actual line numbers.

```
kfun:com.rallyhealth.abtest.InternalRallyAbTest.$init$lambda-2COROUTINE$10.invokeSuspend#internal + 331
        at 1   RallyCoaching                       0x0000000108273f07 kfun:com.rallyhealth.abtest.InternalRallyAbTest.$init$lambda-2COROUTINE$10.invoke#internal + 119
        at 2   RallyCoaching                       0x000000010814c8bd kfun:kotlinx.coroutines.flow.SafeFlow.$collectCOROUTINE$115.invokeSuspend#internal + 653
        at 3   RallyCoaching                       0x000000010814cc58 kfun:kotlinx.coroutines.flow.SafeFlow.collect#internal + 328
        at 4   RallyCoaching                       0x0000000108150fdd kfun:kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(kotlinx.coroutines.flow.FlowCollector<T>) + 141
        at 5   RallyCoaching                       0x0000000108151507 kfun:kotlinx.coroutines.flow.internal.ChannelFlowOperator.$collectCOROUTINE$120.invokeSuspend(kotlin.Result<kotlin.Any?>)kotlin.Any? + 807
        at 6   RallyCoaching                       0x00000001081522e8 kfun:kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(kotlinx.coroutines.flow.FlowCollector<T>) + 328
        at 7   RallyCoaching                       0x0000000108274412 kfun:com.rallyhealth.abtest.RallyAbTestIos.$init$lambda-0COROUTINE$12.invokeSuspend#internal + 738
        at 8   RallyCoaching                       0x00000001080b7b93 kfun:kotlin.coroutines.native.internal.BaseContinuationImpl.resumeWith(kotlin.Result<kotlin.Any?>) + 211
        at 9   RallyCoaching                       0x0000000108155b05 kfun:kotlinx.coroutines.DispatchedTask.run() + 677
        at 10  RallyCoaching                       0x000000010811f738 kfun:kotlinx.coroutines.EventLoopImplBase.processNextEvent()kotlin.Long + 3384
        at 11  RallyCoaching                       0x0000000108164352 kfun:kotlinx.coroutines.WorkerCoroutineDispatcherImpl.$start$lambda-0$FUNCTION_REFERENCE$139.$<bridge-UNN>invoke()#internal + 738
        at 12  RallyCoaching                       0x00000001082bd553 _ZN6Worker19processQueueElementEb + 979
        at 13  RallyCoaching                       0x00000001082be5bd _ZN12_GLOBAL__N_113workerRoutineEPv + 45
        at 14  libsystem_pthread.dylib             0x00007fff51c04109 _pthread_start + 148
        at 15  libsystem_pthread.dylib             0x00007fff51bffb8b thread_start + 15
```

That's disappointing. When I swapped it back to a dynamic framework to compare the stack trace, I'm now getting a crash in the ObjC Bridge.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RATExperiment initWithName:group:]: unrecognized selector sent to instance 0x600001180760'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	5   RallyCoaching                       0x000000010a64ed99 $sSo13RATExperimentC4name5groupABSS_SStcfcTO + 73
	6   RallyCoaching                       0x000000010a64ed02 $sSo13RATExperimentC4name5groupABSS_SStcfC + 66
	7   RallyCoaching                       0x000000010a64e435 $s13RallyCoaching12LoginReactorCACycfc + 1221
	8   RallyCoaching                       0x000000010a64df64 $s13RallyCoaching12LoginReactorCACycfC + 36
	9   RallyCoaching                       0x000000010a295980 $s13RallyCoaching25LoginNavigationControllerC023instanceWithInitialViewE0ACyFZ + 176
	10  RallyCoaching                       0x000000010aa26b6a $s13RallyCoaching15AppStateMachineC24getInitialViewControllerAA09ContainerhI0CyF + 458
	11  RallyCoaching                       0x000000010aaae252 $s13RallyCoaching11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtF + 1778
	12  RallyCoaching                       0x000000010aaae993 $s13RallyCoaching11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtFTo + 211
	13  UIKitCore                           0x00007fff47846788 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 232
	14  UIKitCore                           0x00007fff47848197 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3980
	15  UIKitCore                           0x00007fff4784dce6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1281
	16  UIKitCore                           0x00007fff46f843c9 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
	17  UIKitCore                           0x00007fff47471be1 _UIScenePerformActionsWithLifecycleActionMask + 83
	18  UIKitCore                           0x00007fff46f84edb __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	19  UIKitCore                           0x00007fff46f848ea -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 296
	20  UIKitCore                           0x00007fff46f84d08 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 818
	21  UIKitCore                           0x00007fff46f8459d -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	22  UIKitCore                           0x00007fff46f88bcb __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2 + 178
	23  UIKitCore                           0x00007fff4739769b +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 865
	24  UIKitCore                           0x00007fff4749051f _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	25  UIKitCore                           0x00007fff46f888e6 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 153
	26  UIKitCore                           0x00007fff47490422 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 84
	27  UIKitCore                           0x00007fff46f88754 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 381
	28  UIKitCore                           0x00007fff46ddf123 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 657
	29  UIKitCore                           0x00007fff46dddca8 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
	30  UIKitCore                           0x00007fff46ddee4d -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 210
	31  UIKitCore                           0x00007fff4784c343 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 535
	32  UIKitCore                           0x00007fff473b920d -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	33  FrontBoardServices                  0x00007fff36555225 -[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 442
	34  FrontBoardServices                  0x00007fff3657b598 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
	35  FrontBoardServices                  0x00007fff3655fd05 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
	36  FrontBoardServices                  0x00007fff3657b229 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
	37  libdispatch.dylib                   0x0000000113511d48 _dispatch_client_callout + 8
	38  libdispatch.dylib                   0x0000000113514cb9 _dispatch_block_invoke_direct + 300
	39  FrontBoardServices                  0x00007fff365a143e __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	40  FrontBoardServices                  0x00007fff365a112c -[FBSSerialQueue _queue_performNextIfPossible] + 441
	41  FrontBoardServices                  0x00007fff365a163b -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	42  CoreFoundation                      0x00007fff23bb2221 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	43  CoreFoundation                      0x00007fff23bb214c __CFRunLoopDoSource0 + 76
	44  CoreFoundation                      0x00007fff23bb1924 __CFRunLoopDoSources0 + 180
	45  CoreFoundation                      0x00007fff23bac62f __CFRunLoopRun + 1263
	46  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	47  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	48  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	49  RallyCoaching                       0x000000010aab2b0b main + 75
	50  libdyld.dylib                       0x00007fff51a1dc25 start + 1
```

**Comment by SvyatoslavScherbina** [comment]
> I tried it out, and I'm seeing that class names, but I'm not getting actual line numbers.

Do you expect that `.dSYM` makes your program print stack traces with line numbers?
That's not how `.dSYM` for release binaries work. Instead they allow to symbolicate crash logs. Please refer to the documentation: https://kotlinlang.org/docs/reference/native/ios_symbolication.html

Normally release binaries are used for publishing the application, and you can't get output from published application installed on user's device.
Debug binaries print stack traces with line numbers by default.
What is your case? Why do you use release binaries for development?

> That's disappointing. When I swapped it back to a dynamic framework to compare the stack trace, I'm now getting a crash in the ObjC Bridge.

What do you mean by "ObjC Bridge" here? What is `RATExperiment`?
Is `RATExperiment.init(name: Swift.String, group: Swift.String)` implemented in Swift? If so, then how exactly is it implemented?

**Comment by ScottPierce** [comment]
>Do you expect that .dSYM makes your program print stack traces with line numbers?

Yes

>Instead it allows to symbolicate crash reports.

From working on Android, I expect crash reports to have line numbers. Otherwise, I'm playing a guessing game of what actually caused the crash. My iOS devs tell me they are used to getting line numbers with crashes also.

>Normally release binaries are used for publishing the application, and you can't get output from published application installed on user's device.

I'm told that the iOS App Store removes the dsym from the actual app distribution, meaning that the app download size isn't impacted by them.

**When I look at my iOS teams production crash logs for their app written in Swift, I'm able to see line numbers in Firestore Crashlyics for their Swift files that they wrote.**

> What is your case? Why do you use release binaries for development?

I've created a cross-platform library to be shared across android and iOS. I'm compiling the library for iOS to a Fat Framework, and releasing it to them as a carthage precompiled dependency (basically a framework zip that carthage knows how to download, containing the .framework, and the dsym). I can't change the framework for production or development. I can only choose to give them a release or debug build, so I've been choosing release.

> What do you mean by "ObjC Bridge" here? 

I was seeing the IDE pause the app, and it was showing me a file that looked like it was the ObjC Bridge between Kotlin and ObjC. I can't repro this anymore.

>What is RATExperiment?

```
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("Experiment")))
@interface RATExperiment : RATBase
- (instancetype)initWithName:(NSString *)name group:(NSString *)group __attribute__((swift_name("init(name:group:)"))) __attribute__((objc_designated_initializer));
- (NSString *)component1 __attribute__((swift_name("component1()")));
- (NSString *)component2 __attribute__((swift_name("component2()")));
- (RATExperiment *)doCopyName:(NSString *)name group:(NSString *)group __attribute__((swift_name("doCopy(name:group:)")));
- (BOOL)isEqual:(id _Nullable)other __attribute__((swift_name("isEqual(_:)")));
- (NSUInteger)hash __attribute__((swift_name("hash()")));
- (NSString *)description __attribute__((swift_name("description()")));
@property (readonly) NSString *group __attribute__((swift_name("group")));
@property (readonly) NSString *name __attribute__((swift_name("name")));
@end;
```

Here's how we're using it. We're creating it inside of a Swift `List`
``` Swift
Experiment(name: "Test", group: "Blah")
```

Here is the context that it's implemented:
```Swift
            RallyAbTestIos().doInit(
               appName: "test",
               userIdentifier: "testUser",
               experiments: [Experiment(name: "Test", group: "Blah")],
               mode: .Development(config: ["Test": ["Blah", "Grah"]])
            ) { result in
                
            }
```

The app this framework is added too is compiling fine. I don't get this error when I had compiled a static release framework, only when I take the exact same code and change it to a dynamic release framework.

**Comment by SvyatoslavScherbina** [comment]
> When I look at my iOS teams production crash logs for their app written in Swift, I'm able to see line numbers in Firestore Crashlyics for their Swift files that they wrote.

Yes. And that's how it works on iOS. And that's what Kotlin provides on iOS too, when release `.dSYM`s are enabled.

And this is clearly not the same as

> > Do you expect that .dSYM makes your program print stack traces with line numbers?

> Yes

**Print != show in crash reports**.


Concerning dynamic framework crash:
>  I can't repro this anymore.
> I don't get this error when I had compiled a static release framework, only when I take the exact same code and change it to a dynamic release framework.

These two statements don't seem any consistent. Are you still experiencing the crash with `RATExperiment`? If yes, then why do you claim that you can't repro this anymore? If no, then why do you write "only when I **take** the exact same code and change it to a dynamic release framework" like you still experience the crash?

**Comment by ScottPierce** [comment]
Forget what I said about the ObjC Bridge.

>Yes. And that's how it works on iOS. And that's what Kotlin provides on iOS too, when release .dSYMs are enabled.

So when providing `-Xg0` to a static release framework, I'll get line numbers in Firebase Crashlytics the same as iOS is what you are saying? If that works then it's perfect.

>Are you still experiencing the crash with RATExperiment?

I am.

>If yes, then why do you claim that you can't repro this anymore?

I was talking about the ObjC Bridge. Let's forget I mentioned the ObjC Bridge. I can still reproduce the crash.

I've been playing with this for the past few hours. It doesn't matter whether or not the framework is debug or release, if it's static, it works as expected. If It's dynamic, it fails with the crash I gave you.

**Comment by SvyatoslavScherbina** [comment]
> So when providing -Xg0 to a static release framework, I'll get line numbers in Firebase Crashlytics the same as iOS is what you are saying? If that works then it's perfect.

Providing `-Xg0` enables symbolication for Kotlin frames in stack traces.

Then you'll likely need unhandled Kotlin exceptions to be reported properly, since they aren't Objective-C exceptions.
In Xcode crash reports you get unhandled Kotlin exceptions by default. For Firebase Crashlytics you would probably have to implement reporting Kotlin exceptions. [setUnhandledExceptionHook](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native/set-unhandled-exception-hook.html) can help you to detect them. You may also find [CrashKiOS](https://github.com/touchlab/CrashKiOS) project useful.

> I've been playing with this for the past few hours. It doesn't matter whether or not the framework is debug or release, if it's static, it works as expected. If It's dynamic, it fails with the crash I gave you.

I see. Could you please share a reproducer?

**Comment by SvyatoslavScherbina** [comment]
JFTR: `-Xg0` is no longer required since 1.4.0.
Got no response, closing.

**Comment by fenglh** [comment]
Mark
