### ISSUE TITLE
licenses/LICENSE.txt file duplicates LICENSE

### ISSUE THREAD

**Issue by tonsky** [JetBrains/kotlin-native#4065]
```
   Copyright {yyyy} {name of copyright owner}
```

**Comment by JakeWharton** [comment]
It's supposed to. That's the section _how_ you apply it.

**Comment by tonsky** [comment]
Oh I see. So it’s a template of a license? Should it be replaced by the actual license? Like “How to apply” section suggests?

**Comment by JakeWharton** [comment]
The source files contained in the repository have comment headers with the year and owner replaced by their actual values.

**Comment by tonsky** [comment]
Ok so there’s LICENSE and there’s licenses/LICENSE.txt. There should be only one file, maybe? And that one file should NOT contain words like

```
   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.
```

Because they mean that you are not licensing anything, but just giving an example to someone else to license their work.

**Comment by JakeWharton** [comment]
Those words are part of the license file so they're fine as-is. The one in `licenses/` is wrong, though.

If you have questions about the Apache 2 license and how it's actually applied you should speak to a lawyer.

**Comment by tonsky** [comment]
I see. The only issue is duplicate files then.

**Comment by SvyatoslavScherbina** [comment]
@tonsky Thank you for noticing "Copyright {yyyy} {name of copyright owner}"!

> The one in licenses/ is wrong, though.

@JakeWharton Are you sure? See [license/LICENSE.txt in kotlin repo](https://github.com/JetBrains/kotlin/blob/master/license/LICENSE.txt#L190).

> I see. The only issue is duplicate files then.

`licenses/LICENSE.txt` is "main" license file.
`LICENSE` is required for GitHub to render license at repository header.

**Comment by JakeWharton** [comment]
Yep that one is also wrong.

I would suggest consulting with your lawyers about it as you're effectively changing the license contents.

You can also look around at other Apache 2 projects, such as ones inside the Apache Foundation itself. Here's Apache Ant: https://gitbox.apache.org/repos/asf?p=ant.git;a=blob;f=LICENSE;h=5cfe309ec958431fd47e1b4ec015f954c840bd29;hb=HEAD#l190

**Comment by SvyatoslavScherbina** [comment]
Thank you for the advice!
We've decided [to make license files uniform](https://github.com/JetBrains/kotlin-native/pull/4076) with kotlin repository for now, and make consistent decision later.

**Comment by SvyatoslavScherbina** [comment]
Closing this issue since duplication is intentional.
