### ISSUE TITLE
Consider mechanism for running tests on different/multiple threads

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/kotlin-native#4075]
With bugs like #3876, it would be nice if there was a way to denote tests that should be run on both the main thread and a background thread. Perhaps an annotation for the class and/or method which ran the test functions twice to make sure code is adhering to the constraints of the memory model.

This annotation should probably be a part of `kotlin.test` as an `@OptionalExpectation` so that it can be used in common test code.

Right now I'm doing this myself with an expect/actual function that I wrap each test body in, but I would prefer for something at the class-level so that I do not forget a test.

**Comment by SvyatoslavScherbina** [comment]
Have you seen [`-trw` compiler flag](https://kotlinlang.org/docs/reference/compiler-reference.html#-generate-worker-test-runner--trw)?

**Comment by JakeWharton** [comment]
I have not! I'm way up in Gradle land so never thought to look at these flags directly. I may file a separate feature request for the Gradle plugin to somehow expose this where it can run both variants.

My understanding is that I need to compile the tests twice to produce two test executables and that the entire suite will be included in each. Are you doing this with the stdlib tests? I'm curious if it ever comes up that you have things which simply don't work from main or worker threads and would be without a way to exclude them.

**Comment by SvyatoslavScherbina** [comment]
> My understanding is that I need to compile the tests twice to produce two test executables and that the entire suite will be included in each.

Yes, but this flag just switches test launcher from default to `worker`: https://github.com/JetBrains/kotlin-native/blob/721a84ea441a9f3bb0f9011d686493beba503143/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt#L29
You can actually implement your own launcher, and specify it with `-entry` compiler flag. Running all the tests twice in single process appears to work.

> Are you doing this with the stdlib tests?

I don't think so. Thank you for the idea!

**Comment by SvyatoslavScherbina** [comment]
https://github.com/JetBrains/kotlin-native/pull/4592 enables running stdlib tests in worker.
For other libraries, using `-trw` compiler flag should do the trick.
We don't have plans to automate or simplify this further, focusing instead on the development of new GC and memory model, that would eliminate the need for the requested machinery.
