### ISSUE TITLE
Windows line endings cause errors in MSYS

### ISSUE THREAD

**Issue by aknauf** [JetBrains/kotlin-native#4078]
This looks like a regression of #1659, which occurs in kotlin-native-windows-1.3.61 and 1.3.71. The shell scripts in the bin directory contain windows (CRLF ) line ending rendering them invalid as shell scripts. 

This prevents their use under either cygwin or msys.

**Comment by PavelPunegov** [comment]
According to the [migration process](https://github.com/JetBrains/kotlin-native/issues/4079) issue is moved to YouTrack: https://youtrack.jetbrains.com/issue/KT-42893
