### ISSUE TITLE
How to interact with kotlin collections from C/C++ code?

### ISSUE THREAD

**Issue by DTHeaven** [JetBrains/kotlin-native#4130]
There's no method exported in .h file, is there is a way to use kotlin collections from c/c++ code?

**Comment by artdfel** [comment]
Hello! First of all, I got to remind you about Kotlin/Native issue tracker migration(see #4079). Bugs should be reported to the YouTrack, while questions are preferable to be asked on the #kotlin-native [slack](https://github.com/JetBrains/kotlin-native/issues/kotlinlang.slack.com) channel.
To use any API of Kotlin's stdlib collections, one should explicitly expose them to the library API. This makes compiled headers less verbose, but more expressive - just think about the number of unneeded methods one would get without this feature. Just write a unique-named function getting the collection instance and call the needed method inside of it. This function should be accessible from C.

**Comment by DTHeaven** [comment]
OK, thanks for your replay.

So if I want to use list.add/remove method, I would write like this:
`fun newArrayListInstance(): ArrayList {
    return ArrayList()
}

fun addToList(list: ArrayList, element: Any) {
    list.add(element)
}
`
Then I need list.get method, I would write another function wrapper.
It's inconvenient, could you support an easy way to get necessary methods access?

**Comment by artdfel** [comment]
The whole idea here was to minimize the amount of API getting into the header. Can you clarify, why getting many Kotlin's methods exposed is so important for you here? Are the C/C++ data structures unapplicable here?

**Comment by vvlevchenko** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-45961 Users want to interact with objects of libraries (e.g. stdlib) types used in C/C++ exported kotlin code](https://youtrack.jetbrains.com/issue/KT-45961)
