### ISSUE TITLE
Code of cmake project, compile error error: invalid use of incomplete type 'std::filesystem::__cxx11::filesystem_error'

### ISSUE THREAD

**Issue by henjue** [JetBrains/kotlin-native#4133]
I have a cmake project. I want to merge it into kotlin native, but the compilation reports an error! I look up the information on the Internet. It seems that there is a problem with the version of clang. How can I change the version of clang
```
C:\Users\henjue\.konan\dependencies\msys2-mingw-w64-i686-clang-llvm-lld-compiler_rt-8.0.1\include\c++\9.2.0\bits/fs_path.h:636:31: error: invalid use of incomplete type 'std::filesystem::__cxx11::filesystem_error'
```

**Comment by artdfel** [comment]
Hello, @henjue! First of all, I got to remind you about Kotlin/Native issue tracker migration(see #4079). Bugs should be reported to the YouTrack, while questions are preferable to be asked on the #kotlin-native slack channel.
Please extend your issue with an exact explanation of steps to reproduce it. If possible, attaching the project would also help a lot.
