### ISSUE TITLE
Platform iOS package is missing

### ISSUE THREAD

**Issue by ImanX** [JetBrains/kotlin-native#4176]
I use Kotlin 1.3.61 on Android Studio 3.6.3 and IDE miss Platform libraries in Kotlin Multiplatform in iOS layer
What's wrong?

YouTrack: https://youtrack.jetbrains.com/issue/KT-38976
More details: https://github.com/JetBrains/kotlin-native/issues/4079

**Comment by SvyatoslavScherbina** [comment]
Please create only YouTrack issues. Closing this issue as duplicate.

**Comment by ImanX** [comment]
I updated kotlin version to 1.3.72 and issue fixed.
