### ISSUE TITLE
Please read the text below

### ISSUE THREAD

**Issue by GpnagpurAkshat** [JetBrains/kotlin-native#4338]
Please read the text below.

# Are you reporting a bug or requesting a feature?

Please don't submit GitHub issue, create YouTrack issue instead: https://kotl.in/issue

# Are you asking a question?

Please use StackOverflow with `kotlin-native` tag: https://stackoverflow.com/questions/ask?tags=kotlin-native

Also feel free to ask or discuss anything on `#kotlin-native` and `#multiplatform` channels in Slack workspace for Kotlin community -- https://slack.kotl.in.

# Not sure?

Then you are probably asking a question, see above.

Please avoid creating new GitHub issues in any case. More details: https://github.com/JetBrains/kotlin-native/issues/4079

**Comment by artdfel** [comment]
Hello, @GpnagpurAkshat! I'm closing this issue as it was, probably, created accidentally. If there is something you wanted to ask or share, please use YouTrack, StackOverflow, or Slack.
