### ISSUE TITLE
Xcode 11.6 still using older versions of kotlin native

### ISSUE THREAD

**Issue by mathemandy** [JetBrains/kotlin-native#4339]
![IMG-20200822-WA0016](https://user-images.githubusercontent.com/6526607/90966645-b63af580-e4cc-11ea-8f00-d231c591b913.jpg)

I am building a KMP app and building from xcode still says kotlin Multiplatform is an experimental feature. 

Its refusing to adjust to the new compiler.

Please how do i resolve this issue. 

It works fine on android studio with kotlin gradle plugin on 1.4.0 and build.gradle on v6.6

**Comment by artdfel** [comment]
Hello, @mathemandy! First of all, I have to remind you about Kotlin/Native issue tracker migration(see details here #4079). About this particular issue - can you clarify, what does the project gradle script look like? Usually, the Xcode project contains a custom script phase, calling `./gradlew`. It should utilize the same Kotlin version as the build from the CLI of Android Studio.

**Comment by mathemandy** [comment]
Thanks for the assistance. I'll use the issue tracker next time. 

`
 /bin/sh -c /Users/androiddeveloper/Library/Developer/Xcode/DerivedData/uduxIOS-agxepfzgqhwritfjkwoqrmjbqemc/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/SharedCode.build/Script-1766B4386E9A9ECAB9A5E5DC74379E50.sh

                REPO_ROOT="$PODS_TARGET_SRCROOT"
                "$REPO_ROOT/../live/gradlew" -p "$REPO_ROOT" :SharedCode:syncFramework                     -Pkotlin.native.cocoapods.target=$KOTLIN_TARGET                     -Pkotlin.native.cocoapods.configuration=$CONFIGURATION                     -Pkotlin.native.cocoapods.cflags="$OTHER_CFLAGS"                     -Pkotlin.native.cocoapods.paths.headers="$HEADER_SEARCH_PATHS"                     -Pkotlin.native.cocoapods.paths.frameworks="$FRAMEWORK_SEARCH_PATHS"
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :SharedCode
Kotlin Multiplatform Projects are an Alpha feature.

> Task :SharedCode:generateDefFirebaseAuth UP-TO-DATE

> Task :SharedCode:cinteropFirebaseAuthIos FAILED
Exception in thread "main" java.lang.Error: /var/folders/c0/n7gzryts5yj_rp9jw65w22pw0000gq/T/tmp1667905949200127761.m:1:9: fatal error: module 'FirebaseAuth' not found
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:67)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:13)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:499)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:264)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:72)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:19)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:37)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':SharedCode:cinteropFirebaseAuthIos'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
`

**This task fails in task :SharedCode:cinteropFirebaseAuthIos from Xcode** 

`12:18:04: Executing task ':SharedCode:cinteropFirebaseAuthIos'...

Executing tasks: [:SharedCode:cinteropFirebaseAuthIos] in project /Users/androiddeveloper/Documents/udux_android/live

> Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
> Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
> Task :buildSrc:compilePluginsBlocks UP-TO-DATE
> Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
> Task :buildSrc:configurePrecompiledScriptDependenciesResolver
> Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
Configuration on demand is an incubating feature.

> Configure project :SharedCode
Kotlin Multiplatform Projects are an Alpha feature.

> Task :SharedCode:generateDefFirebaseAuth UP-TO-DATE
> Task :SharedCode:generateDummyFramework

> Task :SharedCode:podspec
Generated a podspec file at: /Users/androiddeveloper/Documents/udux_android/SharedCode/SharedCode.podspec.
To include it in your Xcode project, check that the following dependency snippet exists in your Podfile:

pod 'SharedCode', :path => '/Users/androiddeveloper/Documents/udux_android/SharedCode'


> Task :SharedCode:podGenIos
> Task :SharedCode:podSetupBuildIos
> Task :SharedCode:podBuildDependenciesIos
> Task :SharedCode:cinteropFirebaseAuthIos

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 29s
7 actionable tasks: 6 executed, 1 up-to-date
12:18:34: Task execution finished ':SharedCode:cinteropFirebaseAuthIos'.`


The task runs successfully  when built from Android Studio or Intellij

**Comment by mathemandy** [comment]
@artdfel  
I have attached two logs showing failure on build on xcode and success on. 
The build script is autogenerated from the podspec in android Studio. 

Any help would be appreciated.

**Comment by mathemandy** [comment]
`
Showing All Messages
The Kotlin/Native distribution used in this build does not provide the standard library. Make sure that the 'kotlin.native.home' property points to a valid Kotlin/Native distribution.
`

i get this error when i try to build  `/samples/cocoapods` and yes, i followed everything on the readMe.

**Comment by mathemandy** [comment]
> `Showing All Messages The Kotlin/Native distribution used in this build does not provide the standard library. Make sure that the 'kotlin.native.home' property points to a valid Kotlin/Native distribution.`
> 
> i get this error when i try to build `/samples/cocoapods` and yes, i followed everything on the readMe.

i just changed this in the gradle.properties files to 
org.jetbrains.kotlin.native.home=/home/user/kotlin-native-0.8

to my location of kotlin-native.

Ill update if i get around this

**Comment by mathemandy** [comment]
@artdfel  i was able to build my library in the sample code, so whats left is my own  Ios Project. Still cant find FirebaseAuth on xcode in my project. 

ill probably have to create a new ios project and start anew

**Comment by mathemandy** [comment]
> @artdfel i was able to build my library in the sample code, so whats left is my own Ios Project. Still cant find FirebaseAuth on xcode in my project.
> 
> ill probably _have to create a new ios project and start anew_

I found the issue. 
In my PodFile, i commented out the line `use_frameworks!`, i must have  done that for another dependency. 

Thanks for the assistance.  its all sorted now. I can access the dependency correctly on  IOS(Xcode) and Android Studio/Intellij
