### ISSUE TITLE
This doesn't work with Java 9, does it?

### ISSUE THREAD

**Issue by timmyjose** [JetBrains/kotlin-native#447]
./gradlew dependencies:update fails with unresolved dependencies - https://pastebin.com/TCatwYQy

Stack Trace:

https://pastebin.com/ngsG9zdw

Java version: $ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+140)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+140, mixed mode)

**Comment by timmyjose** [comment]
Just an update - tried it with Java 8, and it works fine. For folks on macOS, in case you have the default Java version set to 9, you can do the following (in case you also have other Java installations):

$ export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
$ ./gradlew dependencies:update

And then the commands work fine. Note: You can choose -v 1.7 etc., to set the specific Java version. I couldn't find any version support information in the FAQ or the README, but I presume Java 1.7 and 1.8 should be well supported.

On Windows, the procedure is pretty much the same - set the JAVA_HOME environment variable to a non-9 version, and it should work fine.

**Comment by olonho** [comment]
Yes, Java 9 is not currently supported. Once it will be released, we will support it.

**Comment by timmyjose** [comment]
Thanks for confirming that! You can close this issue then, I suppose.
