### ISSUE TITLE
Compilation failed: llvm.llvm (initialization failure) NoClassDefFoundError: llvm.llvm

### ISSUE THREAD

**Issue by alapierre** [JetBrains/kotlin-native#4501]
First time compilation of new Kotlin Native Gradle project

```
Task :linkDebugExecutableNative FAILED
e: Compilation failed: llvm.llvm (initialization failure)

 * Source files: 
 * Compiler version info: Konan: 1.4.10 / Kotlin: 1.4.10
 * Output kind: PROGRAM

e: java.lang.NoClassDefFoundError: llvm.llvm (initialization failure)
e: Compilation failed: llvm.llvm (initialization failure)

	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:136)
e: java.lang.NoClassDefFoundError: llvm.llvm (initialization failure)
```

```
Caused by: java.lang.UnsatisfiedLinkError: Can't load /home/adrian/.konan/kotlin-native-prebuilt-linux-1.4.10/konan/nativelib/tmp4749578871872200773.tmp/libllvmstubs.so
```
libllvmstubs.so is in `/home/adrian/.konan/kotlin-native-prebuilt-linux-1.4.10/konan/nativelib/libllvmstubs.so`

Even if I create folder `tmp4749578871872200773.tmp` and copy *.so - it not works - `Can't load /home/*********/.konan/kotlin-native-prebuilt-linux-1.4.10/konan/nativelib/tmp4749578871872200773.tmp/libllvmstubs.so`

```
ls -l /home/adrian/.konan/kotlin-native-prebuilt-linux-1.4.10/konan/nativelib/

-rwxr-xr-x 1 adrian adrian    56685 lis  6 08:15 libcallbacks.so
-rwxr-xr-x 1 adrian adrian   431112 lis  6 08:15 libclangstubs.so
-rwxr-xr-x 1 adrian adrian 41643554 lis  6 08:15 libllvmstubs.so
-rwxr-xr-x 1 adrian adrian     6637 lis  6 08:15 liborgjetbrainskotlinbackendkonanfilesstubs.so
-rwxr-xr-x 1 adrian adrian    24732 lis  6 08:15 liborgjetbrainskotlinbackendkonanhashstubs.so
drwxrwxr-x 2 adrian adrian     4096 lis  6 08:22 tmp4749578871872200773.tmp
```

```
ls -l /home/adrian/.konan/kotlin-native-prebuilt-linux-1.4.10/konan/nativelib/tmp4749578871872200773.tmp
razem 41184
-rwxr-xr-x 1 adrian adrian    56685 lis  6 08:15 libcallbacks.so
-rwxr-xr-x 1 adrian adrian   431112 lis  6 08:15 libclangstubs.so
-rwxr-xr-x 1 adrian adrian 41643554 lis  6 08:23 libllvmstubs.so
-rwxr-xr-x 1 adrian adrian     6637 lis  6 08:15 liborgjetbrainskotlinbackendkonanfilesstubs.so
-rwxr-xr-x 1 adrian adrian    24732 lis  6 08:15 liborgjetbrainskotlinbackendkonanhashstubs.so

```

Project created with IntelliJ as a Kotlin Native Project (Gradle Kotlin)

**Comment by artdfel** [comment]
Hello, @alapierre! I got two questions to start with:
 1) Is this the first time you created a Kotlin/Native project?
 2) What is your system environment?

Also, I would recommend deleting `/home/adrian/.konan/kotlin-native-prebuilt-linux-1.4.10` directory and letting the Gradle to re-download it. This is a simple move, but it can help if the downloading was incorrect.

**Comment by alapierre** [comment]
hello, 

I'm using Linux Mint 18. It was first Kotlin Native project in Intelli 2020 - last year I tried Kotlin Native kotlin-native-linux-1.0.3 and it works fine. 

I tried to delete kotlin-native-prebuilt-linux-1.4.10 several times before I sent issue.

**Comment by SvyatoslavScherbina** [comment]
What does `ldd /home/adrian/.konan/kotlin-native-prebuilt-linux-1.4.10/konan/nativelib/libllvmstubs.so` show?

> 	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:136)

So I guess you are using J9 as your JVM. Please try using Oracle JDK or OpenJDK instead.

**Comment by alapierre** [comment]
``
ldd /home/adrian/.konan/kotlin-native-prebuilt-linux-1.4.10/konan/nativelib/libllvmstubs.so
	linux-vdso.so.1 (0x00007fffa47f0000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4728eba000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4728cb6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4728a97000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f472887a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f47284dc000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4728153000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4727f3b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4727b4a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f472b678000)
``

**Comment by alapierre** [comment]
with OpenJDK 8.x it works fine.
