### ISSUE TITLE
Provide Support For ARM Microcontrollers

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#458]
LLVM has support for [targeting ARM Microcontrollers](https://groups.google.com/forum/#!topic/llvm-dev/baI0yOphEPI) like the Cortex M3 and M4 for example. Kotlin Native should have the ARM microcontrollers as the next target. Many of the ARM microcontroller boards provide standard C libraries to cover low level HW access.

One ARM microcontroller board that would be a good candidate to get Kotlin Native working on is the [STM 32 F4 Discovery](http://www.st.com/en/evaluation-tools/stm32f4discovery.html). Some companies like [Samsung](http://llvm.org/devmtg/2016-03/Presentations/eurollvm-2016-arm-code-size.pdf) have successfully used LLVM to target ARM microcontrollers.

**Comment by olonho** [comment]
The support for embedded targets is being considered, and community contributions are welcome.

**Comment by napperley** [comment]
What is the standard procedure for adding a new platform (eg **cortex-m3**) to Kotlin Native?

**Comment by napperley** [comment]
Does the Kotlin Native LLVM backend have [ARM Thumb support](http://stackoverflow.com/a/21272095) compiled **into** it?

**Comment by olonho** [comment]
See https://github.com/JetBrains/kotlin-native/pull/365/files as an example of adding new backend. Also you need to create appropriate sysroot and stub/implement some platform functionality, such as locale support (will be fixed soon).

**Comment by olonho** [comment]
`llc --version` from sysroot lists all supported targets, and Thumb is amongst them.

**Comment by napperley** [comment]
@olonho - Thank you for the update on the Thumb support. How much of an issue is locale support? Huge concerns regarding the size of the Kotlin standard library since code size really matters on the ARM microcontroller side (every **bit** counts). Where is the Kotlin standard library currently located?

Is it normal for LLVM to generate ARM executables that are bigger than the Linux x86-64 ones?

**Comment by olonho** [comment]
If you're OK with not being able to parform case conversions and charater type detection - simple ASCII-only stubs could be used.

Standard library is linked into final binary only partially (due to LTO optimizations). stdlib is in https://github.com/JetBrains/kotlin-native/tree/master/runtime/src.

Generally, Thumb2 code compiled with optimizations (`-opt` `konanc` flag) is expected to be a bit smaller than optimized x86.

**Comment by napperley** [comment]
Character/string handling won't be a big issue at this stage. More important to have basic C interop that is good enough to do a basic **Blinky** project (requires basic hardware access) to see if it works. Have *a* [STM32 Nucleo board](http://www.st.com/en/evaluation-tools/stm32-mcu-nucleo.html?querycriteria=productId=LN1847) in mind for the project.

Good to know that Thumb code will be smaller.

> Generally, Thumb2 code compiled with optimizations (-opt konanc flag) is expected to be a bit smaller than optimized x86.

**Comment by olonho** [comment]
I removed system locale dependencies, so now it shall not be a problem anymore.

**Comment by napperley** [comment]
Have temporarily procured a [STM32F411](http://www.st.com/en/microcontrollers/stm32f411.html?querycriteria=productId=LN1877) (development board) for the **Blinky** project. Below is the basic hardware info for the board:

- ARM Cortex M4 (100 MHz)
- 512 KB Flash
- 128 KB SRAM
- USARTs (3x)
- SPI (5x)
- SDIO (1x)
- I2C (3x)
- USB 2.0 OTG (1x)
- ADC (12 bit)
- Timers (11x - 16 and 32 bit)

**Comment by napperley** [comment]
Using the following [Target Triple](https://clang.llvm.org/docs/CrossCompilation.html#target-triple):

- arch = **thumb**
- sub = **v7m**
- abi = **eabi**

Translates to the following string: **thumbv7m-eabi**. Note that there is no vendor and OS specified. Microcontrollers don't need an OS.

Using the following [hardware flag](https://clang.llvm.org/docs/CrossCompilation.html#cpu-fpu-abi):
    **-mcpu=cortex-m4**

Attempting to figure out how to create **sysroot** since it can be very tricky with the ARM microcontroller CPUs as there are many manufacturers that implement them in different ways.

**Comment by olonho** [comment]
For sysroot you likely need to start with some existing toolchain to produce binaries for your board. Once you wil create proper tarball I can make it available for download.

**Comment by napperley** [comment]
Is **libffi** required for the ARM Cortex M4 port? Does Kotlin Native use **libffi** for the C interop?

**Comment by olonho** [comment]
Yes, it is required for some corner cases, such as varargs processing. Basic port not needing C varargs could try to survive #ifdef'ing FFI code.

**Comment by napperley** [comment]
Where would the #ifdef'ing FFI code be implemented?

**Comment by napperley** [comment]
Currently [libffi](https://sourceware.org/ml/libffi-discuss/2015/msg00087.html) don't support the Cortex M CPUs, but do support the Cortex A ones. Downright [confusing](https://community.arm.com/processors/f/discussions/2900/thumb-or-thumb-2) to determine which instruction set each ARM CPU uses.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/blob/master/runtime/src/main/cpp/Interop.cpp#L20

**Comment by olonho** [comment]
Also for purposes of what we need from libffi supporting Thumb2 ISA shalln't be too hard, looking at what kind of ASM it needs https://github.com/libffi/libffi/blob/master/src/arm/sysv.S#L153. Problematic instructions are multiple loads with disjoint register sets, maybe those could be split into multiple instructions, and 3 argument arithmetic, which likely could be achieved by two argument arithmetic and move.

**Comment by napperley** [comment]
All Cortex M CPUs support Thumb1, not Thumb2.

**Comment by napperley** [comment]
Cortex A CPUs support **Thumb2**, which is what the Raspberry Pi (RPi) and [Beaglebone Black](https://beagleboard.org/black) (BBB - RPi's biggest competitor) use for example. Very common for the Single Board Computers (SBCs) to use a Cortex A CPU.

**Comment by napperley** [comment]
Might be best to try with an ARM Cortex M7 (has **Thumb2** support) development board. Don't know anyone who has one. Would be good if a major ARM manufacturer could send one to JetBrains for the Kotlin Native port.

**Comment by jabrena** [comment]
I think that the compilation for ARM 7, could be necessary to be adopted for educational robots like Lego Mindstorms.
https://en.wikipedia.org/wiki/Lego_Mindstorms_EV3
http://ev3dev-lang-java.github.io/#/
http://www.oracle.com/technetwork/java/embedded/downloads/javase/javaseemeddedev3-1982511.html

**Comment by napperley** [comment]
First version of the Raspberry Pi's SoC is ARM 7 based and Kotlin Native
was recently back ported to it. Juan - Are you talking about the old
application based ARM CPUs?

**Comment by jabrena** [comment]
Hi @napperley,

This kind of boards:
https://en.wikipedia.org/wiki/ARM9#ARM9E

Next week, I will test the native features with Raspi 3 + BrickPi:
https://www.dexterindustries.com/brickpi/

But I think that EV3 community is greater. If Kotlin could have support for that boards, it could be pretty interesting for the whole ecosystem.

Cheers

Juan Antonio

**Comment by olonho** [comment]
With recent changes for WASM, unifying memory management and making explicit porting layer here https://github.com/JetBrains/kotlin-native/blob/master/runtime/src/main/cpp/Porting.cpp porting Kotlin/Native to embedded targets shall be relatively easy.

**Comment by aydin192** [comment]
Hi everyone,

I am curious if anyone has started adding _Thumb_ (either _Thumb-1_ or _Thumb-2_) support? Is there any repository?

Regards,
Aydin

**Comment by olonho** [comment]
STM32 support is merged, it includes Thumb support in https://github.com/JetBrains/kotlin-native/pull/1305

**Comment by mgiaco** [comment]
@olonho that sounds really great. Is there any information available how to start with a sample project?
