### ISSUE TITLE
Provide Support For Beaglebone Black Platform

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#473]
Kotlin Native already has support for the Raspberry Pi (RPi). Would make sense to add support for the [Beaglebone Black](https://beagleboard.org/black) (BBB) considering that the RPi uses very similar software (toolchain, OS, standard libraries etc), and has a similar ARM CPU (Cortex A).

**Comment by napperley** [comment]
Made some changes in a fork and ran the following command in the terminal: 
    **./gradlew dependencies:update**

Ended up with the following error:

```
A problem occurred evaluating project ':runtime'.
> Cannot get property 'beaglebone_blackLibffiDir' on extra properties extension as it does not exist
```

What is meant by **extra properties extension**?

**Comment by ilmat192** [comment]
Our build script adds properties with paths for all dependencies in the root Gradle project. E.g. we have `llvmDir`, `gccToolchain` etc. We do it [here](https://github.com/napperley/kotlin-native/blob/master/dependencies/build.gradle#L157) using name of dependency downloading task as a base name. In other build scripts we use these properties forming their name on basis of target platform (e.g. [here](https://github.com/napperley/kotlin-native/blob/master/runtime/build.gradle#L30)). I believe the name of Beaglebone Black target platform in the `targetList` (a key in the `targetArgs` map) differs from the name of dependencies downloading task for it, so you have such error.

Also I think you need to add some path for dependencies downloading. We download it from our server [here](https://github.com/napperley/kotlin-native/blob/master/dependencies/build.gradle#L106) using path provided by the `getBaseUrl()` method but we have no Beaglebone stuff there. You can extend the `HelperNativeDep` class and override `getBaseUrl()` to provide your own path.

**Comment by napperley** [comment]
@ilmat192 - Thank you for the helpful explanation of how the dependency management works in the build process. Fixed the key in **targetArgs** to **beagleboneBlack** and reran the build. A ClassNotFoundException (**com.sun.tools.javac.util.Context**) appeared during the last stage of the build.

[Kotlin Native Build Errors.txt](https://github.com/JetBrains/kotlin-native/files/916345/Kotlin.Native.Build.Errors.txt)

**Comment by napperley** [comment]
Just realized that Linux Mint 18 only has the **openjdk8-jre** package installed by default. Resolved the issue by installing the **openjdk8-jdk** package and rerunning the build. This time Gradle can't download the dependencies related to the Beaglebone Black.

Is there a mechanism to supply a local directory path as a build dependency? Very unfortunate that Gradle cannot handle symlinks as I wanted to use symlinks to point to the **libffi-3.2.1-2-raspberrypi** and **target-sysroot-1-raspberrypi** directories.

**Comment by napperley** [comment]
Starting to make progress on the build resolving the local Kotlin Native dependencies. Encountering difficulties with symbolic links not being followed:

```
:dependencies:beagleboneBlackLibffi UP-TO-DATE
:dependencies:beagleboneBlackSysroot

FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of '/home/napperley/repos/kotlin_native/dist/dependencies/target-sysroot-1-beaglebone-black/usr/lib64/libcidn.so'. Couldn't follow symbolic link.
```

**Comment by ilmat192** [comment]
It looks strange. I've made a similar experiment (made symlink `$HOME/kotlin_native_dependencies`, copied tar.gz with libraries into it and ran `dependencies:update`) and have't got the problem. Could you please provide more details about the problem (e.g. what directory in the path is the symlink)?

Also you may try to remove `dist/dependencies` and run the update again. Or run with Gradle's up-to-date checks disabled: `./gradlew dependencies:update --rerun-tasks`.

The dependency downloader uses a URL to locate dependencies so probably you will need to add `file://` string before the path in the `getBaseUrl()` method.

If you want to modify the dependency downloading system itself, you can do it in `tools/helpers` subproject.

**Comment by napperley** [comment]
Resolved the symlinks issue (emptied **dist/dependencies**, prepended **file://** and reran the build) but end up with a bizarre extract archive error instead.

[Kotlin Native Build Errors.txt](https://github.com/JetBrains/kotlin-native/files/918522/Kotlin.Native.Build.Errors.txt)

Wonder if emptying the cache will do the trick. Absolutely certain that the archive files can be extracted just fine. Manually extracted the archives just to be sure.

**Comment by napperley** [comment]
Running **./gradlew dependencies:update --rerun-tasks** results in the same issue appearing.

**Comment by napperley** [comment]
@ilmat192 - Managed to temporarily fix the issue via a messy hack job. Manually extracted the **lib** directory from the archive and moved it to **dist/dependencies/target-sysroot-1-beaglebone-black**. For future reference this is the environment under which the odd error occurred:

- Linux Mint 18.1 (Main edition) 64 bit
- Linux Kernel: 4.4.0-21-generic
- Gradle 3.1 (revision: 13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97)
- OpenJDK JDK: 1.8.0_121
- OpenJDK JRE: build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13
- OpenJDK Server VM: build 25.121-b13, mixed mode
- GZip 1.6
- Tar 1.28

**Comment by napperley** [comment]
Currently at the **cross_dist** build step. The build is failing during the **:common:beagleboneBlackHash** Gradle task with the following errors:

[Kotlin Native Build Errors.txt](https://github.com/JetBrains/kotlin-native/files/918830/Kotlin.Native.Build.Errors.txt)

Gradle is throwing up **IllegalStateException: Unknown target: beagleboneBlack**. Below are the targets that the new **konanc** program supports:

```
dist/bin/konanc -list_targets
linux:                        (default) 
raspberrypi:                            
beaglebone_black:    
```

Where is the unknown **beagleboneBlack** target coming from?

**Comment by ilmat192** [comment]
@napperley Strange issue with unpacking. I'll look at it when I have a chance. Could you please send me your sysroot and libffi archives for BBB somehow?

> Gradle is throwing up IllegalStateException: Unknown target: beagleboneBlack.

It's stdlib compilation (**:backend.native:beagleboneBlackStdlib** task). We compile the stdlib for each target listed in the `targetList` (see the code [here](https://github.com/napperley/kotlin-native/blob/beaglebone_black/backend.native/build.gradle#L208)) passing the target name as a `-target` parameter to the compiler. So you have `beagleboneBlack` in the `targetList` and in the compiler argument but `beaglebone_black` in the compiler itself.

**Comment by olonho** [comment]
If Beaglebone Black is so similar, could you try building for RaspberryPi and try resulting executable on Beaglebone? Then additional changes are not required.

**Comment by napperley** [comment]
Already have a pre-built Tetris executable for the RPi which is ready to be tried out on the BBB. Will use a BBB (rev B) running Debian Jessie (v8.7) and LXQT for the desktop (using [this](https://debian.beagleboard.org/images/bone-debian-8.7-lxqt-4gb-armhf-2017-03-19-4gb.img.xz) official image file).

Success! :)  The executable runs properly on the BBB after the **libsdl2** package is installed, and the **tetris_all.bmp** file is copied over to where the executable is located.

**Comment by olonho** [comment]
Then I assume this bug could be closed.

**Comment by napperley** [comment]
@olonho - Yes. I'm assuming the issue can be reopened if there are some major problems encountered?

**Comment by napperley** [comment]
Are target platform aliases being considered?

**Comment by olonho** [comment]
Yes, good idea to have an alias. Maybe @alexander-gorshenev may implement that.
