### ISSUE TITLE
Command Line Tools For Kotlin Native Development

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#475]
What CLI tools are currently available for doing software development with Kotlin Native? Are there any plans to provide additional CLI tools (eg debugger)?

**Comment by vvlevchenko** [comment]
we suppose to use lldb (gdb) for debugging and other native tools used in development in unmanaged environments.

**Comment by olonho** [comment]
As we produce native code and compile to normal system binaries, all tools (debuggers, profilers and so on) will likely work with produced binaries.
