### ISSUE TITLE
Not compatible with latest compiler

### ISSUE THREAD

**Issue by wenerme** [JetBrains/kotlin-native#479]
Due to this commit https://github.com/JetBrains/kotlin/commit/cb4d2994a3b3c6d86e5bf3a39db68c0e0686d1f6 

https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/ir/util/IrUtils.kt#L87 will report compile error.

    Type mismatch: inferred type is CompilerMessageLocation? but CompilerMessageLocation was expected

**Comment by wenerme** [comment]
There is [no snapshot build](https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/kotlin/kotlin-compiler/1.1-SNAPSHOT/) before 20170411, so, can not compile kotlin-native anymore.

**Comment by vvlevchenko** [comment]
we've refreshed compiler dependencies on EAP branch [b7dde2b0769d29a5503a7c1776769e286f1ac13d](https://github.com/JetBrains/kotlin-native/commit/b7dde2b0769d29a5503a7c1776769e286f1ac13d) you can build snapshot by yourself or wait a while we're preparing binaries
