### ISSUE TITLE
Convert offset to void *pointer

### ISSUE THREAD

**Issue by perses-games** [JetBrains/kotlin-native#493]
Some api's expect offsets as a void *pointer parameter. It would be nice if there was an easy way to convert an offset (Long)  to a pointer (or maybe there is but I haven't found it yet).

For example, the opengl api has the following function [glVertexAttribPointer](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml)

```c
void glVertexAttribPointer(	
        GLuint index,
 	GLint size,
 	GLenum type,
 	GLboolean normalized,
 	GLsizei stride,
 	const GLvoid * pointer);
```
The last parameter is an offset into the current array buffer. So it doesn't actually point to something in memory.

After some searching I got it working, at the moment I call it like this:

```kotlin
glVertexAttribPointer(
                  info.location,
                  info.numElements,
                  GL_FLOAT,
                  0.toByte(),
                  verticesBlockSize * 4,
                  interpretCPointer<EmptyClass>(nativeNullPtr.plus(info.offset * 4L)))
```

EmptyClass is defined as follows:

```
class EmptyClass(override val rawPtr: NativePtr) : CPointed
```

It has to be empty so kotlin doesn't actually try to interpret it (I assume that an illegal memory access caused the crashes I experienced).

So it would be nice if there was an easier way to do this.

**Comment by SvyatoslavScherbina** [comment]
Actually it is not necessary to declare any class. You can use the `CPointed` type instead:
```
interpretCPointer<CPointed>(nativeNullPtr.plus(info.offset * 4L))
```

Also the type inference allows to omit the type argument here:

```
interpretCPointer(nativeNullPtr.plus(info.offset * 4L))
```

Of course this is the temporary solution, and we will provide the better way to convert between pointers and integers.

> It has to be empty so kotlin doesn't actually try to interpret it (I assume that an illegal memory access caused the crashes I experienced).

Calling `interpretCPointer` actually shouldn't provoke any memory accesses. Do you experience illegal memory accesses when using a non-empty class instead?

**Comment by perses-games** [comment]
Ok thx, that works for me. 

If there are no memory reads then the crash was probably something else (video driver didn't like the passed value I guess).

**Comment by SvyatoslavScherbina** [comment]
Converting between pointers and integers seems to be very popular operation, so we have already implemented the better way to achieve that. Please see `.toCPointer<T>()` at the end of this section: https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#pointer-types

**Comment by perses-games** [comment]
Thx, works great!

**Comment by SvyatoslavScherbina** [comment]
Thank you for the feedback! Feel free to report more discovered issues.
