### ISSUE TITLE
staticCFunction alternative for non-static code

### ISSUE THREAD

**Issue by AdrianVovk** [JetBrains/kotlin-native#518]
It is really difficult to write code around the limitations of `staticCFunction`. Is there any possible way to get around them with the compiler?

**Comment by AdrianVovk** [comment]
Here is a perfect example:
```
inline fun onClick(noinline listener: () -> Unit) : Unit = 
    g_signal_connect(internal, "clicked", staticCFunction(listener))
```

Outputs:
`error: kotlinx.cinterop.staticCFunction must take an unbound, non-capturing function or lambda`

**Comment by olonho** [comment]
One may implement custom solution around user data, like is being done here https://github.com/JetBrains/kotlin-native/blob/master/samples/libcurl/src/org/konan/libcurl/CUrl.kt#L39

More generic solution is feasible, but raises ugly issues with callback lifetimes (as if we create a true closure, closure object need to be freed at some moment + requires codegeneration at runtime, as single C function pointer has to combine both data and code pointer, thus have to be unique executable segment pointer per closure). 

We may consider implementing this feature in the future.

**Comment by AdrianVovk** [comment]
I worked around the limitations using the example you linked (`StableObjPtr`) and got it to work. Of course it would be nice to do by default. Close this issue if you see it necessary (or keep it open to track progress on the implementation)
