### ISSUE TITLE
Typealias resolution for parameters

### ISSUE THREAD

**Issue by AdrianVovk** [JetBrains/kotlin-native#524]
I have a function:
```kotlin
fun someFunction(ptr: COpaquePointer?) {...}
```
And I have a variable:
```kotlin
//typealias gpointer = CPointer<out CPointed>
//typealias COpaquePointer = CPointer<out CPointed>
var data: gpointer?
```
I cannot call `someFunction(data)`, because it throws something along the lines of:
```
Expecting COpaquePointer? /*CPointer<out CPointed>?*/ but found gpointer? /*CPointer<out CPointed>?*/
```

That is the premise of the issue. Once I have access to a computer I'll give you real code and the real output

**Comment by olonho** [comment]
Do you have any further info on this issue?

**Comment by AdrianVovk** [comment]
Not yet. I've been busy replacing a screen on a device this weekend. I'll update this more when I have time. @olonho

**Comment by AdrianVovk** [comment]
**Turns out that this is a non-issue**

This was the "issue": 
```
src/sdk/UI.kt:28:48: error: type mismatch: inferred type is gpointer? /* = CPointer<out CPointed>? */ but COpaquePointer /* = CPointer<out CPointed> */ was expected
```

When I looked again, I realized that I have `CPointer?` and `CPointer`.

I'd like to apologize and am closing the issue
