### ISSUE TITLE
Tizen support

### ISSUE THREAD

**Issue by gyorgygabor** [JetBrains/kotlin-native#551]
Hi,

Can we develop with Kotlin Native to Tizen platform?

Best regards,
Gabor

**Comment by olonho** [comment]
What kind of OS/CPU combo is used on your target Tizen? According to https://en.wikipedia.org/wiki/Tizen
it is Linux for x86 and ARM, and as such, you may try to compile for 'linux' (x86-64) and 'raspberrypi' (arm-32) targets.

**Comment by ilmat192** [comment]
Gradle plugin allows passing additional linker options to the K/N compiler. Also, if you need to pass some custom flags to the K/N compiler itself or to the cinterop tool, you can use the `extraOpts` parameter:
```
konanArtifacts {
    library('foo') {
        // Arguments to be passed to a linker.
        linkerOpts '-Lpath/to/libs', '-lmylibrary'

        // Pass additional command line options to the K/N compiler.
        extraOpts '--time', '--verbose', 'linker'
    }
}
```

**Comment by Thomas-Vos** [comment]
I am interested in Tizen OS support. I created an issue on YouTrack here: https://youtrack.jetbrains.com/issue/KT-43808

I have Kotlin/Native working on physical Tizen OS watches (see linked issue for details), but cannot get it working on emulator because of missing targets. Did anyone here get Kotlin working on the Tizen OS emulator?

**Comment by Shusek** [comment]
I managed to do it but but unfortunately only as "fun project" and it is not usable for production application. If I remember correctly I forked whole kotlin-native and change math precision and hardcode buildChain to use tizen buildChain instead linux-arm default. Most libraries on tizen is written in C language instead C++ so the porting worked well.
