### ISSUE TITLE
Feature request: Kotlin declaration file for header/lib

### ISSUE THREAD

**Issue by wenerme** [JetBrains/kotlin-native#554]
Like TypeScript [declaration-files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) for js lib, with these declaration, typescript is easy to work with vanilla js.

TypeScript with JavaScript like KN with vanilla C, KN will stub for headers, why not standardize these stubs, like

```xml
<dependency>
    <groupId>org.jetbrains.kotlin.stubs</groupId>
    <artifactId>glibc</artifactId>
    <version>2.25.0</version>
</dependency>
```

for glibc v2.25, if someone need glibc, just include this, then done, everything just works.In this dependency, just some declarations, like interface or method declarations. With theses, DRY is achieved, maybe with better doc, we can work with kn way more easier and share what we have done.

If kn can do this, then maybe a doxgen doc to kn declarations will build up, boom, a lot of very good qualified libs just works in kn.So, why should I use c/c++ if I can use typed and featured kotlin-native.

**Comment by olonho** [comment]
Chen, could you please elaborate, what is exact scope of your proposal. We're working on library format, which will allow easy linking with pure Kotlin/Native and mixed Kotlin/Native + compiled code (either included, or externally installed). 

Auto-translation of documents in bindings is being considered, but not yet implemented (and we're welcome contributions here).

**Comment by wenerme** [comment]
Is there any info about the library format you saied ?

As declaration file, I mean a bridge between C Header and Kotlin which can be shared and hosted on repos.

**Comment by olonho** [comment]
We will provide more information on Kotlin libraries, once they are ready. Part of libarary functionality will be linking with external libraries.

**Comment by linux-china** [comment]
Nice idea :)
