### ISSUE TITLE
Question,the idea will use kotlin-native build  IntelliJ-platform?

### ISSUE THREAD

**Issue by NateLing** [JetBrains/kotlin-native#570]
hi all:

i hava a question.if kotlin-native released. IntelliJ-platform will use kotlin-native to rebuild?

**Comment by wenerme** [comment]
IMO, maybe, after many years. 

kn's runtime is not complete yet, even it's complete, idea written in java, kn's runtime != java's runtime, convert whole idea's source code to pure kotlin is nearly impossible(so many jars, so many things have to maintain). Maybe some module can write in kn, but not the whole project.

**Comment by olonho** [comment]
Not sure if this question is related to Kotlin/Native itself. From common sense, IDEA is bound to Java APIs as much, as to Java as language itself, so this is not a question of pure recompilation, but major rewrite.
