### ISSUE TITLE
Gradle Plugin recompiles libraries

### ISSUE THREAD

**Issue by AdrianVovk** [JetBrains/kotlin-native#573]
The Gradle plugin will recompile libraries when it is unnecessary.

For example, I have it build GTK. Whenever I do `gradle build` it recompiles the stubs for GTK. Each time

**Comment by AdrianVovk** [comment]
Nevermind. It started working all of the sudden. I don't know what happened but it is fine now. After a few recompiles of GTK it says `UP-TO-DATE`

**Comment by ilmat192** [comment]
Yes, it's a known issue and it's fixed by this pull request: https://github.com/JetBrains/kotlin-native/pull/571

**Comment by ilmat192** [comment]
The fix have been merged into master.

**Comment by AdrianVovk** [comment]
Thank you!

**Comment by AdrianVovk** [comment]
This issue is back

**Comment by ilmat192** [comment]
Do you observe the problem in some of our samples or in your project?

**Comment by AdrianVovk** [comment]
My project @iomat192

**Comment by ilmat192** [comment]
Could you please provide the `build.gradle` script you use?

**Comment by AdrianVovk** [comment]
Closing again. It turns out I'm forgetting to use the latest gradle plugin with `--include-build`. I'm using an old plugin and a new compiler, which causes issues
