### ISSUE TITLE
Question: GC or MM?

### ISSUE THREAD

**Issue by Cortlandd** [JetBrains/kotlin-native#587]
Will Kotlin native be garbage collected or managed manually like C, Rust, etc?

**Comment by wenerme** [comment]
Check this https://github.com/JetBrains/kotlin-native/issues/556#issuecomment-299765979

**Comment by olonho** [comment]
Kotlin/Native uses automated memory management, currntly based on automated reference counting with cycle collector. See here for details: https://github.com/JetBrains/kotlin-native/blob/master/runtime/src/main/cpp/Memory.cpp

**Comment by olonho** [comment]
Also not sure if opening an issue is a good way to ask question, I suggest using public Slack server or other ways mentioned at https://kotlinlang.org/community/

**Comment by omochi** [comment]
I got my answer here via google too.
