### ISSUE TITLE
iOS Installation instructions

### ISSUE THREAD

**Issue by jeffmcclure** [JetBrains/kotlin-native#613]
I'm trying to install the sample tetris on my iPhone but I am stuck.  the instructions state "take Info.plist, then use XCode and your own private signing identity"

I'd appreciate any further guidance on how this is done.  Do I create a new xcode project?  Is this done via the command line?

**Comment by olonho** [comment]
Jeff, packing iOS applications is not in the scope of Kotlin/Native. Generally, what you need to do is pretty well described on the net, for example http://codewithchris.com/deploy-your-app-on-an-iphone/ https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/LaunchingYourApponDevices/LaunchingYourApponDevices.html

Easy way is start with empty project for iOS, compile it and replace a binary with binary produced by Kotlin/Native compiler.

Also JetBrains is working on a commercial IDE, which will make packing and deployment easier.
