### ISSUE TITLE
[Windows] Process name is wrong ?

### ISSUE THREAD

**Issue by Scellow** [JetBrains/kotlin-native#626]
Hello

Is there a way to change the process name?

In task manager here is what i get:

![taskmgr_2017-06-01_15-48-36](https://cloud.githubusercontent.com/assets/27389256/26682806/10e13f12-46e2-11e7-8b73-f94f7fb4c78a.png)

**Comment by olonho** [comment]
Probably, this is an artefact of using mingw pthread libraries in our process. See ftp://sourceware.org/pub/pthreads-win32/sources/pthreads-w32-2-9-1-release/version.rc
If you're aware how to change it - please let us know.

**Comment by Scellow** [comment]
I'll try to investigate

**Comment by Scellow** [comment]
http://man7.org/linux/man-pages/man3/pthread_setname_np.3.html

>   By default, all the threads created using pthread_create() inherit
       the program name.

That's what the doc says, so it is the way the thread is created that cause the name to be choosen like that

**Comment by olonho** [comment]
We likely need to override program name, not the names of individual threads.

**Comment by msink** [comment]
I tried this:

```rc
VS_VERSION_INFO    VERSIONINFO
FILEVERSION        1,0,0,0
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904e4"
    BEGIN
      VALUE "FileDescription", "Kotlin/Native Tersis sample"
      VALUE "FileVersion", "1.0.0.0"
      VALUE "ProductName", "Kotlin/Native Tersis sample"
      VALUE "ProductVersion", "1.0.0.0"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x409, 65001
  END
END
```
Compile - `windres -i Tetris.rc -o Tetris.rc.o`
And added `Tetris.rc.o` to `konanc -linkerOpts`.

But it still stays "POSIX WinThreads" - my resource linked AFTER default one, and ignored in Windows.

**Comment by olonho** [comment]
Shall be fixed with https://github.com/JetBrains/kotlin-native/pull/633.
