### ISSUE TITLE
Gradle Plugin Tasks Restructuring

### ISSUE THREAD

**Issue by AdrianVovk** [JetBrains/kotlin-native#630]
I'm writing a Gradle plugin that generates a source and then runs Kotlin/Native.

I'm using `build.dependsOn("genMetadata")`, but the problem is that `compileKonanSample` runs before `genMetadata`. I cannot use `compileKonanSample.dependsOn(...)` because this is in a plugin, and the name might be different.

I propose that a solution might be that instead of having this structure:
```
build
   dependsOn: compileKonanSample
   dependsOn: compileKonanFoo
```

This would be more logical:
```
build
   dependsOn: compileKonan
      dependsOn: compileKonanSample
      dependsOn: compileKonanFoo
```
This would fix the problem because I could then just use `compileKonan.dependsOn("genMetadata")`, which is a safe call because `compileKonan` doesn't change.

If I have time, I might try implementing this in a PR

**Comment by ilmat192** [comment]
It's a good proposal. Thank you!

> If I have time, I might try implementing this in a PR

It would be great.

**Comment by ilmat192** [comment]
Such task structure is add in https://github.com/JetBrains/kotlin-native/pull/675/commits/c2312ab615e37fdb5fc485663231924ecbb03a14
