### ISSUE TITLE
Please includes dates in CHANGELOG.md headings

### ISSUE THREAD

**Issue by uvtc** [JetBrains/kotlin-native#656]
Currently there's no easy way to tell when a given release was made.

Can you please add dates to the headings, as in:

    # v0.2, 2017-xx-xx
    ...
    # v0.1, 2017-xx-xx

**Comment by Scellow** [comment]
You have the dates here: https://github.com/JetBrains/kotlin-native/releases

**Comment by uvtc** [comment]
Ah. I'm glad that's there. My original complaint was poorly worded. I should've written that there's no easy way to tell the dates by looking at the changelog. When reading the changelog, it's nice to see dates right next those lists of changes. Currently, if I want to see both, I need to bounce back and forth between two browser tabs. This will become more of a hassle as the changelog file grows.

Having the dates in the changelog also helps the reader more easily understand how much time various features took to develop.

Also, if the project were ever moved off of github, those dates on the releases page might not make it to the new location, but dates in the changelog are eternal.

**Comment by olonho** [comment]
Looks like a good idea, added.
