### ISSUE TITLE
WebAssembly Support

### ISSUE THREAD

**Issue by DQvsRA** [JetBrains/kotlin-native#657]
Is it possible to compile to wasm?

**Comment by olonho** [comment]
In theory - yes, see https://gist.github.com/yurydelendik/4eeff8248aeb14ce763e as an example. One may just create bitcode files of Kotlin files and Kotlin/Native runtime, and convert those to WebAssembly. However, runtime depends on some POSIX APIs, such as malloc()/free() and write() so one need to implement those somehow.

**Comment by cbeust** [comment]
The main obstacle to this is that WebAssembly currently doesn't have a GC. There is [a project trying to fix that](https://github.com/WebAssembly/gc) but unfortunately, the last commit was two months ago :-(

There is also the issue that WebAssembly doesn't have access to the DOM, but [there's also a project for that](https://github.com/mbasso/asm-dom).

**Comment by napperley** [comment]
Cedric - Kotlin Native already has WASM support (currently experimental). See the [HTML 5 Canvas sample](https://github.com/JetBrains/kotlin-native/tree/master/samples/html5Canvas) One of the big issues faced with WASM support in Kotlin Native is interop with JS/web APIs.

**Comment by cbeust** [comment]
@napperley I know and I fail to see how what you say invalidates my two points.

**Comment by napperley** [comment]
The point being made is that Kotlin Native doesn't need a GC to work with WASM, hence there is no reliance on the WASM group to provide a GC system (would be waiting a while). As mentioned previously lack of JS/web API interop will greatly hinder Kotlin Native's WASM support. There is a valuable opportunity for Kotlin to have a JS/web interop system for WASM before any other language (**"first mover"** advantage).

**Comment by olonho** [comment]
Supported since v0.4, closing.
