### ISSUE TITLE
llc: xxxx.bc: error: Invalid value

### ISSUE THREAD

**Issue by aydin192** [JetBrains/kotlin-native#693]
Hi,

Trying to pass the generated _bitcode_ file to `llc`, I keep getting "Invalid Value" error. Am I missing something?
I am using LLVM version 3.4 and latest Kotlin/Native version.

Regards,
Aydin

**Comment by vvlevchenko** [comment]
Hello Aydin,
Perhaps your llvm is too old, we use version 3.9.

**Comment by olonho** [comment]
You could try to generate .o files with llc and link thos into your final executable.

**Comment by aydin192** [comment]
@vvlevchenko You are right. The problem was my LLVM version.

**Comment by ChangXiaoning** [comment]
@vvlevchenko Hi, I have a same problem when using "llc", but my LLVM version is RELEASE 500. I don't what's wrong.
