### ISSUE TITLE
Freestanding environment

### ISSUE THREAD

**Issue by ghost** [JetBrains/kotlin-native#694]
I love Kotlin Native so far. 

I would very much like to write a sample OS kernel project in it, but this requires the equivalent of --freestanding. It also means being able to shut off automatic mem mgmt.

Any plans for this?

**Comment by olonho** [comment]
Well, it's up to target platform how to link the final binary, so you could produce any image you like,
 including a self-contained ELF or similar (see https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/LinkStage.kt).

 Regarding memory management - nothing prevents you from using automated MM in kernel environment as well, it's just a reference counter, most kernels do that themselves for some types of data. What you would need to implement for such a port is:
   * custom malloc/free (better based on some buddy algorithm)
   * custom address -> symbol mapper, if symbolic backtraces expected
   * console output with print

IIRC, there's an effort in similar direction, see https://github.com/semoro/KOS

**Comment by notsonotso** [comment]
> Regarding memory management - nothing prevents you from using automated MM in kernel environment as well,

Cleary not for memory mapped I/O...

**Comment by olonho** [comment]
Probably such components better be written in C.

**Comment by olonho** [comment]
As K/N is being primarily an application development language, there's no plans to support such a feature.
