### ISSUE TITLE
GTK sample uses C API directly, use GIR files to create Kotlin binding instead

### ISSUE THREAD

**Issue by russel** [JetBrains/kotlin-native#701]
It appears that the GTK example is just using the C API directly . This is very not Kotlin. RAII is very difficult in C and it all gets very awkward for people not having C tunnel vision. gtkmm is a binding to GTK for C++, GtkD is a binding for D. both of these provide an adaptor layer which is very lightweight to allow people to construct GTK application but using idiomatic code. D uses the GIR files of GTK (and GStreamer) to create a very idiomatic D way of using GTK.

I propose that a Kotlin binding is created to GTK and GStreamer by using the GIR files just as GtkD does.

**Comment by r4zzz4k** [comment]
I saw at least [one](https://victor.kropp.name/blog/kotlin-native-0.2-and-gtk/) article on this topic where author mentioned his will to work on such bindings (the repo is empty for the time being though). I think it's more reasonable to leave development of such bindings to the community -- the only thing I personally expect from kotlin-native team is centralized repository for `klib`s, and I believe they've mentioned there would be one in the future.
But yes, I agree that it may be more logical to provide an example which doesn't use C API directly but contains small binding incorporated (similar to one the linked article provides) just to show more idiomatic Kotlin usage.

**Comment by msink** [comment]
https://github.com/afcowie/java-gnome - java bindings, should be easy (relatively) convert to Kotlin...

**Comment by r4zzz4k** [comment]
Not sure if it would be that straightforward to port them, because Java bindings rely on JNI, and kotlin-native bindings would use it's own C interop, but great pointer, thanks!

**Comment by olonho** [comment]
Take a look at https://victor.kropp.name/blog/kotlin-native-0.2-and-gtk/. Note, that generally all samples shows how to interact with native library directly, not to provide sweet Kotlin-style bindings around those. Our plan is that interesting people could develop nicer bindings in pure Kotlin, using straight interop bindings as a mechanism to call the library. That's what Victor started for GTK.

**Comment by russel** [comment]
OK, I've no problem with this, but could a note be added that the intention of this example is to show direct C working, not to be the way it should be in Kotlin Native. i.e. turn the comments above into a note in a file in the directory.

**Comment by russel** [comment]
BTW the point about using application (GTK+3) rather than the main loop directly (GTK+2) still stands even in C code.
