### ISSUE TITLE
Must rely on Java?

### ISSUE THREAD

**Issue by sgf** [JetBrains/kotlin-native#705]
when i do cmds on windows,its show some thing like need java or JavaHome....

dose kotlin native must rely on Java?
If Java indispensable, so do you have any plans to cancel its reliance on Java?

**Comment by olonho** [comment]
JDK is being used during compilation, resulting binaries do not depend on it.

**Comment by sgf** [comment]
@olonho thank u.
Is it possible to disengage from the JDK in the future ?

**Comment by olonho** [comment]
Maybe in relatively distant future, but so far we see no real reasons to invest into that.

**Comment by sgf** [comment]
ok,thank u reply.
