### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by gil-levy** [JetBrains/kotlin-native#714]
hi,

1.I can't see any variables when debugging, i've tried building using the gradle plugin or using kotlinc -g.
2.where do you stand in regards to idea/clion debug integration?

Thanks,
Gil

**Comment by olonho** [comment]
Did you checked https://github.com/JetBrains/kotlin-native/blob/master/DEBUGGING.md, especially Known Issues section? IDE debugger integration is worked on.

**Comment by gil-levy** [comment]
hi,

Thanks for answering, yes I've read that and i'm able to debug as in that readme, the problem is when i try to view local variables.... no matter wich way i try (lldb, gdb or any other way) i can't view the local variables or their values.

**Comment by vvlevchenko** [comment]
> the problem is when i try to view local variables
That is exactly why @olonho referenced to DEBUGGING.md.  Your case is mentioned as "inspection isn't implemented".

**Comment by gil-levy** [comment]
Thanks

**Comment by olonho** [comment]
Now some basic inspections of variables works.
