### ISSUE TITLE
Build seems to not consider changes

### ISSUE THREAD

**Issue by ftomassetti** [JetBrains/kotlin-native#722]
Hi, I am building a project with the kotlin-native gradle plugin. When I change the source and run `./gradlew build` everything seems up to date and the application is not recompiled. I have to run `./gradlew clean build` to actually update it. I am running version 0.3 on Mac.

**Comment by olonho** [comment]
Please test with https://github.com/JetBrains/kotlin-native/pull/730

**Comment by ilmat192** [comment]
#730 has been merged into master.
