### ISSUE TITLE
Where to find all targets?

### ISSUE THREAD

**Issue by ftomassetti** [JetBrains/kotlin-native#725]
When running ` konanc -list_targets` on mac I get just 5 targets:

- android_arm32:
- android_arm64:
- iphone:
- iphone_sim:
- macbook:                      (default)

Where I can find the complete list? I need it for an article

**Comment by Scellow** [comment]
I found the list here:

https://github.com/JetBrains/kotlin-native/blob/master/shared/src/main/kotlin/org/jetbrains/kotlin/konan/target/KonanTarget.kt

Ans looks like they are also working on web assembly! https://github.com/JetBrains/kotlin-native/pull/721

**Comment by ftomassetti** [comment]
Thank you @Scellow and looking forward to WebAssembly support!

**Comment by vvlevchenko** [comment]
All possible targets are mentioned in [kotlin-native/RELEASE_NOTES.md](https://github.com/JetBrains/kotlin-native/blob/master/RELEASE_NOTES.md)

**Comment by ftomassetti** [comment]
Well, the targets are listed but not the name of the option. For example, it says that Windows is a valid target, but it does not say that the option is actually `mingw`.
