### ISSUE TITLE
Readme, Gradle required?

### ISSUE THREAD

**Issue by uvtc** [JetBrains/kotlin-native#732]
Is it required to install Gradle before attempting to run the included gradlew command?

It would be helpful to users if you added a note to the README about whether or not they must have Gradle already installed (it appears that the easiest way to install gradle is to first install sdkman, and then use that install gradle).

Note: users unfamiliar with Java may not know what Gradle is, or sdkman, and not even realize that `gradlew` is something that comes with Kotlin/Native (I assumed it was an app I was supposed to install after installing Gradle).

**Comment by olonho** [comment]
Java has to be installed, and it is mentioned in documentation: https://github.com/JetBrains/kotlin-native/blob/master/RELEASE_NOTES.md. Gradle is not listed there, and so it is not required to be installed.

**Comment by AdrianVovk** [comment]
@uvtc I'm assuming you already looked up what gradlew is, but I'll clarify anyways.

Gradlew actually stands for Gradle Wrapper. The Gradle Wrapper is a script that runs a version of Gradle that comes with the project (see the `gradle/` folder). It's very useful for projects to include it so people don't have to install anything (other than Java), and to maintain a specific Gradle version (for example, if you have a project that only compiles on grade version 3.5, anyone who tries to compile it doesn't have to mess with Gradle versions and such)
