### ISSUE TITLE
Feature Request: Basic IO utilities

### ISSUE THREAD

**Issue by RUSshy** [JetBrains/kotlin-native#743]
Hello

What about some IO classes like in Java (DataInput, DataOutput, File) built in the std lib?  

Also would be cool to see built in networking capabilities (tcp client/server), i tried with C, but it is really hard to wrap into the "kotlin way" it is too dirty
thanks

**Comment by alexandrenavarro** [comment]
See my issue https://github.com/JetBrains/kotlin-native/issues/843, it is linked.

**Comment by olonho** [comment]
We're working on somewhat related platform library functionality, which provides uniform IO across POSIX-like platforms.

**Comment by sureshg** [comment]
@olonho Any plans to provide a similar interface for windows or will it completely different altogether?

**Comment by msink** [comment]
MinGW is mostly POSIX compatible - no mmap(), fork() and similar, but basic io works.
So should be possible on windows too.

**Comment by olonho** [comment]
Yes, we are considering creating platform library for POSIX-like APIs available on Windows.  Stay tuned.

**Comment by msink** [comment]
Works now in master branch!

- build platform libraries:
```gradlew distPlatformLibs```

- use it like this:
````
import platform.posix.*

fun main(args: Array<String>) {
    val fileName = "test.txt"
    val file = fopen(fileName, "wt")
    if (file == null) throw Error("Cannot write file '$fileName'")
    try {
        fputs("Hello! Привет!", file)
    } finally {
        fclose(file)
    }
}

**Comment by RUSshy** [comment]
Thanks a lot!

**Comment by RUSshy** [comment]
Do you plant to make it more "managed" ?

**Comment by joelhandwell** [comment]
@msink how about Windows Subsystem for Linux in addition to MinGW ?

**Comment by msink** [comment]
@joelhandwell After #1073 finished it should do just what you want - compile linux executable on windows host.
Windows Subsystem for Linux should run it.

**Comment by olonho** [comment]
This will be covered by Kotlin libraries, such as kotlinx.io.
