### ISSUE TITLE
cinterop and #define

### ISSUE THREAD

**Issue by aydin192** [JetBrains/kotlin-native#751]
Hi,

It seems that the `cinterop` tool does not generate stubs/code for the `#define` statements. Is that right?
If it is, is there any plan for supporting this feature or there is a reason against it?

Regards,
Aydin

**Comment by olonho** [comment]
Could you please be more concrete what kind of defines you would like to have code generated for?

**Comment by aydin192** [comment]
I am using a C SDK which supports different platforms; To make the code using it more portable, the SDK designers have created a "wrapper" header file (.h file) for each platform which converts the underlining platform specific constants to a more general "constant" using "#define." For example if they have a constant named `PLAT_X1_CONSTANT_1` for X1 platform, in the corresponding "wrapper" header file for this platform there is a line like:

`#define CONSTANT_1 PLAT_X1_CONSTANT_1`

There would be a line like following line in the "wrapper" header file in another platform say X2:

`#define CONSTANT_1 PLAT_X2_CONSTANT_1`

The point is the developer using this SDK only add one of the "wrapper" header files in their compile/link chain so no conflicts would happen, but they can easily switch to the other platform without changing any code.

**Comment by olonho** [comment]
For this scenario, you shall select for which platform you generate wrappers and add appropriate defines to .def file, i.e. 

platform1.def:
  compilerOpts = -DPLATFORM1
platform2.def:
  compilerOpts = -DPLATFORM2
And then run cinterop tool using def file matching your needs.

**Comment by aydin192** [comment]
@olonho I don't understand how this could solve my issue? My issue is that the _cinterop_ does not generate anything for `#define` commands and I don't think you solution would help me with that.

**Comment by olonho** [comment]
Could you please post simplified header and what would you like to see in Kotlin bindings?

**Comment by aydin192** [comment]
I have a _board.h_ file which contains lines like these:
```
#define Board_GPIO_LED_ON            CC3220S_LAUNCHXL_GPIO_LED_ON
#define Board_GPIO_LED_OFF           CC3220S_LAUNCHXL_GPIO_LED_OFF
#define Board_GPIO_LED0              CC3220S_LAUNCHXL_GPIO_LED_D7
```
CC3220S_LAUNCHXL is a development board from TI; CC3220S_LAUNCHXL_XXXX values are defined in some other file say _CC3220S_LAUNCHXL.h_ and the _board.h_ wraps them. There are other _board.h_ files for different boards like CC3220_SF__LAUNCHXL.

I want to be able to access Board_GPIO_LED_ON in Kotlin in some way for example `board.Board_GPIO_LED_ON`. Right now I have to use CC3220S_LAUNCHXL_GPIO_LED_ON directly from some other header file.

**Comment by napperley** [comment]
@aydin192 - What CPU is the **CC3220S_LAUNCHXL** development board using? Appears as though the board doesn't use an ARM CPU but some proprietary one. Currently **if** Kotlin Native can be ported to Uc's then the support will be limited to ARM ones. Could be expanded in the future to say MIPS for example although there would be a number of variable factors to consider (one being the hardware has sufficient resources to properly run Kotlin Native programs performance wise).

**Comment by napperley** [comment]
@aydin192 - Note that each major embedded manufacturer has their own way of doing APIs/SDKs. There is **NO** global standard for API design in embedded development. **If** Kotlin Native is successfully ported to a Uc then it would most likely be one developed by STM, NOT TI for testing reasons (much greater availability, especially with the STM discovery boards which are **"cheap, cheap!"**).

**Comment by aydin192** [comment]
@napperley I brought up the **CC3220S_LAUNCHXL** name as an example for the feature I am requesting which is adding support for `#define` syntax; It has nothing to do with the type of the Uc, its manufacturer or its price. :)

BTW, I think supporting _AVR_ Ucs is almost as important as supporting _AMRs_ since there are lots of "cheap" boards based on them and most of the _Arduino_ boards are using them.

**Comment by SvyatoslavScherbina** [comment]
@aydin192 
> It seems that the `cinterop` tool does not generate stubs/code for the #define statements. Is that right?

`cinterop` tool actually imports macros expanding to constants:
https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#macros
See also e.g. [sample/socket](https://github.com/JetBrains/kotlin-native/blob/master/samples/socket/src/main/kotlin/EchoServer.kt#L34). POSIX constants are mostly defined with `#define`, and are imported automatically there.

How `CC3220S_LAUNCHXL_GPIO_LED_ON` is defined? What it gets finally expanded to?
Which compiler do you apply to C code when using the SDK?
Are the headers and the compiler publicly available?

**Comment by aydin192** [comment]
@SvyatoslavScherbina

The `CC3220S_LAUNCHXL_GPIO_LED_ON` is defined like this:
```
#defione CC3220S_LAUNCHXL_GPIO_LED_ON (1)
```
I am currently using _gcc_ but I am pretty sure it works with _clang_ too.
You should be able to download the _CC3220_'s SDK from [here](http://www.ti.com/tool/simplelink-cc3220-sdk) and search for `CC3220S_LAUNCHXL_GPIO_LED_ON` in the source files.

**Comment by SvyatoslavScherbina** [comment]
Such macros are supported.
Do I understand correctly that the line
```
#define Board_GPIO_LED_ON            CC3220S_LAUNCHXL_GPIO_LED_ON
```
is guarded by something like `#ifdef`?

Are you sure that you have added the proper `-D` option to def file to get this line included?

**Comment by aydin192** [comment]
These are the lines leading to the `Board_GPIO_LED_ON` definition:
```
#ifndef __BOARD_H
#define __BOARD_H

#ifdef __cplusplus
extern "C" {
#endif

#include <ti/drivers/ADC.h>
#include <ti/drivers/GPIO.h>
#include <ti/drivers/I2C.h>
#include <ti/drivers/I2S.h>
#include <ti/drivers/PWM.h>
#include <ti/drivers/SDSPI.h>
#include <ti/drivers/SD.h>
#include <ti/drivers/SDFatFS.h>
#include <ti/drivers/SPI.h>
#include <ti/drivers/UART.h>
#include <ti/drivers/Watchdog.h>

#include "CC3220S_LAUNCHXL.h"

#define Board_initGeneral            CC3220S_LAUNCHXL_initGeneral

/* These #defines allow us to reuse TI-RTOS across other device families */

#define Board_ADC0                   CC3220S_LAUNCHXL_ADC0
#define Board_ADC1                   CC3220S_LAUNCHXL_ADC1

#define Board_CAPTURE0               CC3220S_LAUNCHXL_CAPTURE0
#define Board_CAPTURE1               CC3220S_LAUNCHXL_CAPTURE1

#define Board_CRYPTO0                CC3220S_LAUNCHXL_CRYPTO0

#define Board_GPIO_LED_ON            CC3220S_LAUNCHXL_GPIO_LED_ON
```
It does not seem that I need the `-D` option, does it?

**Comment by SvyatoslavScherbina** [comment]
Yes, you are right, the option doesn't seem to be required.
Do your Kotlin bindings contain any declarations from `CC3220S_LAUNCHXL.h` or `Board.h`?

**Comment by aydin192** [comment]
I think the issue is resolved in the new version of _Kotlin-Native_; I can see that "now" the `board.kt` file contains definition for the `BOARD_GPIO_LED_ON` as following:
```
val Board_GPIO_LED_ON: Int = 1
```
Sorry for taking your time; When I first generated the `board.kt` file, I was using **0.2** version but now with **0.3** it seems the issue is fixed.

**Comment by SvyatoslavScherbina** [comment]
I'm glad to see that the problem is solved.
