### ISSUE TITLE
Best Way to Define Static Methods?

### ISSUE THREAD

**Issue by aydin192** [JetBrains/kotlin-native#758]
Hi,

I was wondering if package-level static methods and companion-based "static-like" methods will get compiled to a more or less same "bitcode" or they get compiled into completely different "bitcode"?

In other words: How can I have something like following without introducing unnecessary complexity to the generated "bitcode", eventually the native code and loose performance as the result:

`MyClass.Method1()`

Please not that my final target is a MCU so creating and working with unnecessary objects (instances of classes) is not preferable.

Regards,
Aydin

**Comment by olonho** [comment]
I think you shall use top level functions for that purpose. Companion object have different contract, they have to be inited before usage, so if inited check has some cost.

**Comment by aydin192** [comment]
Thanks a lot for the help.
