### ISSUE TITLE
Konan --help is not supported

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-native#760]
I run `konan --help` or just `konan` as I want to see the list of supported commandline arguments
Current build shows nothing but errors. 

Also `/?` is nice to have on Windows

**Comment by alexander-gorshenev** [comment]
That's `-help`, not `--help`.

**Comment by jonnyzzz** [comment]
Thanks. I found that later too. Having an alias can be nice

**Comment by msink** [comment]
But I personally agree that `konanc --help` and just `konanc` should do the same as `konanc -help`.

**Comment by olonho** [comment]
This style of command line arguments is not supported at the moment.
