### ISSUE TITLE
Show tools commands `konan` calls

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-native#761]
It's nice to see the actual call to `ld`, to make it easier to understand what is going wrong and why a particular build is failing

**Comment by msink** [comment]
AFAIK it don't call ld directly, but calls 'clang' or 'clang++'.
You can pass anything you want to it using `-linkerOpts`
For example `-linkerOpts --verbose`

**Comment by alexander-gorshenev** [comment]
`--verbose object_files` and `--verbose linker` would do the trick. The compiler runs different sets of utilities depending on the platform. On Mac and Linux it calls `ld`.

**Comment by olonho** [comment]
Will close it, reopen if you need more.
