### ISSUE TITLE
Konan tasks in Gradle are not shown

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-native#771]
I have a project with 'apply plugin: 'konan'. Call `./gradle <proejct>:tasks` and there are no konan tasks shown. Calling `./gradle <project>:tasks --all` makes Gradle show the task. 

Setting group property for all plugin-created task classes should solve the issue.
See org.gradle.api.Task#setGroup

**Comment by ilmat192** [comment]
Fixed.
