### ISSUE TITLE
Gradle. Source-Sets are not supported

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-native#774]
In Java we have 'SourceSets` field in Gradle. This is a way to add/change/configure source sets. 
Shall we have similar approach in Konan?

**Comment by ilmat192** [comment]
I think we can rework the plugin using Gradle native software model. It would provide us with source sets too. But we have no ETA yet.

**Comment by ilmat192** [comment]
The plugin reworking will be tracked in #778.
