### ISSUE TITLE
Gradle. `compileKonan` is default task, not real

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-native#776]
I want to include default compiler settings in Gradle or have a pre-task executed before the compiler. 

Both things are only possible to be done for every konanArtifact. 

I'm missing a base configuration to reuse between all possible artifacts. Similarly, I'm missing a common task in Gradle, from which all compileKonan tasks depends.

**Comment by jonnyzzz** [comment]
There is workaround like
```
project.afterEvaluate {
  tasks.withType(org.jetbrains.kotlin.gradle.plugin.KonanCompileTask) {
    dependsOn generateStaticParameters
  }
}
``` 
But it adds an extra level of mess to the build, unfortunately

**Comment by olonho** [comment]
Anything left here?

**Comment by ilmat192** [comment]
We have such a task, called `checkKonanCompiler`. But this task does some internal work for plugin (check if the compiler is available on the local machine and download it if it doesn't) so it's better to add some empty task named, for example, `konanPrecompile` that will depend on `checkKonanCompiler` and will be a dependency for all compilation tasks.
