### ISSUE TITLE
Gradle-plugin: Rework gradle plugin using Gradle native software model

### ISSUE THREAD

**Issue by ilmat192** [JetBrains/kotlin-native#778]
We need to integrate Kotlin/Native Gradle plugin with existing Gradle mechanisms for building native software.

**Comment by msink** [comment]
I'm not sure it's good idea.
Native software usually built one-file-at-a-time, like this:
```
$(OUT)/%.o: %.c
	$(CC) -c $< -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o $@

$(OUT)/$(PROJ): $(OBJS) Makefile
	$(LD) $(OBJS) $(STAGEDIR)/usr/lib/libneo_utl.a -o $@
```
Kotlin compilation in this mode will be VERY slow. And it is slow already...

**Comment by ilmat192** [comment]
Moved to YouTrack: https://youtrack.jetbrains.com/issue/KT-19893.
