### ISSUE TITLE
can't support xp?

### ISSUE THREAD

**Issue by lineCode** [JetBrains/kotlin-native#787]
i compiled the win32 example, but it can't run on windows xp

**Comment by msink** [comment]
64 bit?

**Comment by lineCode** [comment]
no! 32 bit

**Comment by msink** [comment]
For now only 64 bit windows supported,  host and target
https://github.com/JetBrains/kotlin-native/blob/master/RELEASE_NOTES.md#supported-platforms

**Comment by lineCode** [comment]
I see. Thank you！

**Comment by napperley** [comment]
XP does have a 64 bit version.
