### ISSUE TITLE
Use java dependencies

### ISSUE THREAD

**Issue by ojacquemart** [JetBrains/kotlin-native#805]
Hello,

Is it possible to use a java dependency in a kotlin-native module? i.e firebase?

I have tried to add the dependency in the build.gradle but the compilation fails.
I can't see any info the various help files 

Great project, btw 👍

**Comment by napperley** [comment]
Kotlin Native doesn't support Java interoperability. Does Firebase provide
C APIs?

**Comment by ojacquemart** [comment]
Thanks for your answer :)

Firebase provides a C++ skd but not a C one.
Could it be usable?

**Comment by olonho** [comment]
Currently, C++ bindings aren't implemented, however, depending on API style, creating C wrapper may be pretty straightforward, see how some missing parts of LLVM API is implemented here: https://github.com/JetBrains/kotlin-native/tree/master/libclangext/src/main/cpp

**Comment by ojacquemart** [comment]
Ok, I will take a look by curiosity but I am not really comfortable with c/cpp. 
I will wait for a support of java interoperability ;)

**Comment by prithivraj** [comment]
Is there a plan to support this in future?

**Comment by StefMa** [comment]
Nope. It isn't.
You can use native libraries or use multiplatform...
