### ISSUE TITLE
OutOfMemory when compile objc sample

### ISSUE THREAD

**Issue by prsolucoes** [JetBrains/kotlin-native#825]
Hi, i get out of memorty when try compile objc sample:

KtFile: objc.kt
exception: java.lang.OutOfMemoryError: Java heap space

What it do in this sample (samples/objc)? It read full headers and generate the bridge on this moment? What is the steps and how i can solve this out of memory problem?

Thanks.

**Comment by olonho** [comment]
ObjectiveC sample not yet officially supported.
