### ISSUE TITLE
Will GUI programming be supported in the future?

### ISSUE THREAD

**Issue by oahzuw** [JetBrains/kotlin-native#826]
Will GUI programming be supported in the future？A set of code, you can in windows, linux, macos, compile and run

**Comment by AdrianVovk** [comment]
do you mean a universal library?

you can program GUIs using the system's respective libraries

**Comment by olonho** [comment]
Yes, GUI programming is already supported, see https://github.com/JetBrains/kotlin-native/tree/master/samples/win32 and https://github.com/JetBrains/kotlin-native/tree/master/samples/gtk

**Comment by LoganDark** [comment]
@olonho of course macOS is left out, you have to go through objective-C manually...
