### ISSUE TITLE
Huge Binary after Linking Unused program.kt.bc

### ISSUE THREAD

**Issue by khatamnejad** [JetBrains/kotlin-native#841]
I am trying to compile Kotlin for my _CC3220_ micro-controller. I managed to add the _armv7e_m_ target to the Kotlin compiler and generate `runime.bc` and `program.kt.bc` for this target. However I faced an issue related to the size of the final binary: Even if I don't put any references to `runime.bc` and `program.kt.bc` in my Kotlin code (i.e. I can generate the final binary without linking these files), when I link the object file generated from these files, the size of the binary becomes very large and `program.kt.bc` is responsible for it. Following shows the sizes of the final binary with different settings:

- **Without `runime.bc` and `program.kt.bc`**: 67KB
- **With only `runime.bc`**: 68KB
- **With both `runime.bc` and `program.kt.bc`**: 246KB

I was expecting zero or very small amount of size change since none of these files are used in the code.

Is this an expected behavior? Is there any way I can fixed this?

**Comment by olonho** [comment]
Bitcode file size is pretty much irrelevant, what is important is size of machine code generated out of it (as optimizations happens here).
Generate .o binary using llc+ld for your target and this will be more suitable metrics.

**Comment by aydin192** [comment]
@olonho The sizes I mentioned above is the size of the final binary which is in machine code. I just used `.bc` extension to show the relating file; As the matter of fact I cannot link then _bitcode_ files and have to convert them to object files - as I mentioned in my previous post - in order to do that.

**Comment by olonho** [comment]
Could you share the binaries to see where footprint comes from? Did you use -opt flag?

**Comment by aydin192** [comment]
Yes, I use `-O3` optimization flags in the link time.

The [`without_runtime_program.out.zip`](https://github.com/JetBrains/kotlin-native/files/1293603/without_runtime_program.out.zip) contains the output file generated without linking the `runtime.bc.obj` and `program.kt.bc.obj`; The [`with_runtime_program.out.zip`](https://github.com/JetBrains/kotlin-native/files/1293606/with_runtime_program.out.zip) is the same file generated with linking the mentioned files. Please note that the source code is not changed for generating these file which means there is **no** dependencies on `runtime.bc.obj` and `program.kt.bc.obj` files.

**Comment by olonho** [comment]
Did you use konanc -opt flag?

**Comment by aydin192** [comment]
Yes, I have used `-opt` flag.

**Comment by aydin192** [comment]
@olonho Any updates?

**Comment by olonho** [comment]
Sorry, not yet, we're investigating.

**Comment by napperley** [comment]
Presumably the *out* file is an ELF. What happens to the file size when the
*-03* flag is removed? Are you sure the file doesn't contain any debug info?

**Comment by napperley** [comment]
Some optimisation flags can cause the resulting output file to be bigger
rather than smaller in size.

**Comment by alexander-gorshenev** [comment]
@aydin192  Could you please check how passing `-S` to the linker affects your arm binary size?

**Comment by alexander-gorshenev** [comment]
If you are on linux, you can control what's in the final binary using something like
`$ size -A -d program.kexe | sort -n -k 2`.

**Comment by aydin192** [comment]
@napperley it seems `-O3` parameter does not have any effect on the size of the `.out` file.

**Comment by aydin192** [comment]
@alexander-gorshenev I am a bit confused about your passing `-S` to linker suggestion: This option tells `gcc` to only compile the code and not to do any linking which is not what we want in **link** stage.

**Comment by alexander-gorshenev** [comment]
That's another `-S`, not a C compiler flag, but the linker flag.

from `man ld`:
```
       -S
       --strip-debug
           Omit debugger symbol information (but not all symbols) from the
           output file.
```

If you have copied over the `raspberrypi` config in `konan.properties` for your platform, 
that flag was missing from raspberry config, while used on all other platforms. 
See #871 for details.

**Comment by aydin192** [comment]
Oh, I see! The thing is that I don't use `konan` for linking and instead I am using `gcc` as the linker since I have bunch of `c` codes and libraries.

**Comment by aydin192** [comment]
I added `-Wl,-S` to the link stage and generated the final binary and .out files. It seems this option removes some unnecessary code, however still linking **object file** generated from `program.kt.bc` - while it is not used and referenced anywhere - causes a huge jump in the size of the final binary and `.out` files.

Here are the new sizes for final binary (can be compared to the sizes in my first comment):
- **Without `runime.bc` and `program.kt.bc`:** 25KB
- **With only `runime.bc`:** 27KB
- **With both `runime.bc` and `program.kt.bc`:** 206KB

And here are the sizes for the corresponding `.out` file:
- **Without `runime.bc` and `program.kt.bc`:** 58KB
- **With only `runime.bc`:** 69KB
- **With both `runime.bc` and `program.kt.bc`:** 358KB

I think the added size shows that something is not well optimized, well designed or well implemented.

**Comment by msink** [comment]
AFAIK for removing unnecessary code you have to use LTO (link time optomization)  - and LTO works only when you link bitcode files directly, not object files converted from bitcode.

**Comment by alexander-gorshenev** [comment]
Can you show the exact log of bc to out transformation. What commands with what flags you are using? It is really hard to debug issues remotely having only these two tables and explanations.

**Comment by aydin192** [comment]
Okay. Here they are: [**runtime.bc.zip**](https://github.com/JetBrains/kotlin-native/files/1325462/runtime.bc.zip) and [**program.kt.bc.zip**](https://github.com/JetBrains/kotlin-native/files/1325463/program.kt.bc.zip) are the _bitcode_ files I have generated for _armv7e-m_ targets. I run following command for each of these file to generate an object file for them:
```
llc -filetype=obj -mtriple=arm-none-eabi -mcpu=cortex-m4 -mattr=armv7e-m -march=thumb -float-abi=soft -function-sections -data-sections -emulated-tls -O=3 input.bc -o output.obj
```
[**ktdist-runtime.obj.zip**](https://github.com/JetBrains/kotlin-native/files/1325464/ktdist-runtime.obj.zip) is the object file generated for **runtime.bc** and [**ktdist-program.obj.zip**](https://github.com/JetBrains/kotlin-native/files/1325466/ktdist-program.obj.zip) is the object file generated for **program.kt.bc**.

Please not that since my target is an _ARM_ micro-controller, I am using `arm-none-eabi-gcc` which is the _ARM_ version of `gcc` that can be downloaded from [_ARM_ website](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads).

**Comment by msink** [comment]
Where is `main`?
```
$ arm-none-eabi-ld -r --gc-sections --entry main ktdist-program.obj ktdist-runtime.obj -o ktdist-small.o
arm-none-eabi-ld: warning: cannot find entry symbol main; not setting start address
```

**Comment by olonho** [comment]
Is it any better now? We added DCE in codegen.

**Comment by msink** [comment]
Now, for simple "blink LED" program:

|       | FLASH | SRAM |
| --- | ------: | ---: |
| C | 11.808 | 4.668 |
| Kotlin | 175.704  | 15.892  |

A little better, but still bad.
Is DCE really enabled?

**Comment by msink** [comment]
A lot of functions from Runtime are not referenced, and not eliminated:
```
kfun_kotlin.String.toString__kotlin.String
kfun_kotlin.String._get_length___ValueType
kfun_kotlin.Any.toString__kotlin.String
kfun_kotlin.text.StringBuilder.toString__kotlin.String
kfun_kotlin.text.StringBuilder._get_length___ValueType
...
```

**Comment by chris-hatton** [comment]
@msink Do you know if any toolchain updates in the year since your last post have improved the 'blink LED' compile size?

**Comment by SvyatoslavScherbina** [comment]
Closing this abandoned discussion.
Feel free to submit a new bug report or feature request if you have any.
