### ISSUE TITLE
Add a native sample with a so lib generated with jaotc

### ISSUE THREAD

**Issue by alexandrenavarro** [JetBrains/kotlin-native#843]
Add a native sample with a so lib generated with jaotc

In jdk 9, it is possible to generate .so from class or a module or a jar  (see http://openjdk.java.net/jeps/295).

It should be great to have a kotlin sample with exactly the same code a kotlin jvm with a use of libjava.base.so generated by jaotc --output libjava.base.so --module java.base  for instance.

I supposed it is possible to do it but I don't know how to do it notably because of lack of .h

Thanks in advance,

**Comment by r4zzz4k** [comment]
Wow, cool to see that they decided to allow end-users to use AOT compiler. I remember talks that only java.base would be compiled, but this JEP definitely shows much wider scope.

Unfortunately I don't see anything regarding accessing classes during runtime though. It says that compiler merely provides *.so which is loaded by JVM, so I assume that interaction with the code could be done only via libjvm just like in general case with *.class files loaded in the same way. So Java 9 brings nothing useful here. Am I missing something?

Example with libjvm could be useful though; I'm currently using node-java package to load and run Java classes from Node.js environment at work, so if I have time, I might look into that.

And yes, having anything better than JNI would be convenient. What's the status of Panama right now?

**Comment by olonho** [comment]
Not sure what you're trying to do. Kotlin/Native is not bound to Java in runtime, only compiler uses Kotlin/JVM, so creating dynamic libs is orthogonal to anything Java 9 provides.

**Comment by alexandrenavarro** [comment]
In jdk 9, it is now possible to generate native binary with jlink / jaotc. It may be cool to generate native kotlin with possibility to use some java lib as the same way notably for non high performance device like raspberry / nas.

**Comment by olonho** [comment]
Kotlin/Native and AOTed JVM code have different object layout and memory management schemes. It may be possible to interoperate between them on level of primitive types and functions calls, but objects cannot be transparently passed. You may try to AOT Kotlin/JVM code for that.

**Comment by alexandrenavarro** [comment]
Ok, thanks, I thought it can be possible to interoperate easier with objects. Thanks for your answer, maybe it will be easier to do that when panama jep on JVM will be available and I may try AOT with Kotlin/JVM code.
