### ISSUE TITLE
Unable to run `dist` task

### ISSUE THREAD

**Issue by IgorGanapolsky** [JetBrains/kotlin-native#881]
Hello,
I am following your README on my Macbook.  I ran `./gradlew dist`, and got this error:
> Users/igorganapolsky/workspace/git/jetbrains/kotlin-native/runtime/src/main/kotlin/konan/internal/NumberConverter.kt:39:24: warning: this operation has led to an overflow
        val signMask = 0x7FFFFFFFFFFFFFFFL + 1 // The mask to get the sign of.
                       ^
/Users/igorganapolsky/workspace/git/jetbrains/kotlin-native/runtime/src/main/kotlin/konan/internal/NumberConverter.kt:91:24: warning: this operation has led to an overflow
        val signMask = 0x7FFFFFFF + 1 // The mask to get the sign of the number.
                       ^
:backend.native:macbookStart
KtFile: start.kt
:macbookCrossDistRuntime
:distRuntime UP-TO-DATE
:dist

Any ideas?

**Comment by vvlevchenko** [comment]
These are warnings, but not errors. In your  /Users/igorganapolsky/workspace/git/jetbrains/kotlin-native/dist folder you might find ready to use distribution of kotlin native compiler. Have you got any issues with it?

**Comment by olonho** [comment]
dist is short for 'distribution', and this task is not runnable.

**Comment by IgorGanapolsky** [comment]
@olonho Please see screenshot from the README:
<img width="1424" alt="screen shot 2017-09-26 at 9 13 23 am" src="https://user-images.githubusercontent.com/201209/30862192-330c9d60-a29b-11e7-8a5c-9601c633a928.png">

It says to build the compiler and standard library

**Comment by IgorGanapolsky** [comment]
@vvlevchenko Thanks for pointing out that it is only a warning.  My terminal was showing a red error, so it looked like an error.  To what you said about **dist** folder, mine contains:
`target-sysroot-1-darwin-macos`.  So that came pre-packaged with this distro?

**Comment by vvlevchenko** [comment]
yes, 'dist' target creates ready to use bundle, containing 
- `dist/bin/konanc` to compile your kotlin programs into executables or libraries
- `dist/bin/cinterop` to create interop library for your c-library
- `dist/bin/klib` tool to manage and diagnose kotlin native libraries

Other artefacts shouldn't be really interesting for end users.
