### ISSUE TITLE
html5Canvas Sample Fails To Compile On Linux

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#883]
When trying to build the **html5Canvas** sample on Linux it fails with the following error message:

```exception: java.lang.IllegalStateException: Target WASM32 is not available on the LINUX host```

Very strange considering that the **build.sh** file mentions Linux as a [valid build target](https://github.com/JetBrains/kotlin-native/blob/197f77f8e3976c9721df1982eede9398fc9fb0e5/samples/html5Canvas/build.sh#L9).

**Comment by alexander-gorshenev** [comment]
We just haven't published the sysroot and toolchain bits for wasm32 on Linux yet.

**Comment by olonho** [comment]
WASM32 is not supported target at the moment, so bug reports like that are not intended to be fixed.
