### ISSUE TITLE
Generate C Header Files

### ISSUE THREAD

**Issue by aydin192** [JetBrains/kotlin-native#898]
Hi,

Is there any way to generate C (or Objective-C) header files from Kotlin code?

**Detail:** Suppose I have bunch of Kotlin functions which all are annotated with `@ExportForCppRuntime`. To use these functions in a C, I have to declare them in the C side. How can I make creating declaration of the functions in the C side - and possibly generating a header file out of them - automatic?

Regards,
Aydin

**Comment by olonho** [comment]
Generally, we need to design backward interop (C->Kotlin) first, `@ExportForCppRuntime` annotation is implementation mechanism in Kotlin/Native runtime and is not intended to be the supported interop mechanism for general usage.

**Comment by aydin192** [comment]
So, based on your answer I conclude that there is no way for generating header files right now.
Now, is this something I can start working on and contribute? If yes, do you have any designs for this or guidelines on what the best approach is for adding this feature?

**Comment by olonho** [comment]
Yes, nothing at the moment, unless you're willing to write compiler's pass doing something along those lines. One may take a look on https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/lower/TestProcessor.kt as an example of somewhat related lowering.

**Comment by aydin192** [comment]
Thanks for the answer. I am working on it to see how it goes and if I can do something.

**Comment by aydin192** [comment]
@olonho Is there any class/util for converting Kotlin types to C types? I found [Mappings.kt](https://github.com/JetBrains/kotlin-native/blob/master/Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/Mappings.kt) in [Interop](https://github.com/JetBrains/kotlin-native/tree/master/Interop) folder but it does the conversion in reverse.

**Comment by aydin192** [comment]
Ping!

**Comment by olonho** [comment]
Probably you can read the same tables backward. I am not aware about such explicit table.

**Comment by olonho** [comment]
`-produce dynamic` does exactly that.
