### ISSUE TITLE
x86 32-bit targets

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#939]
Support for 32-bit x86 targets - Windows and Linux - is the only missing part for native desktop applications,  almost everythig else is in place already.

**Comment by olonho** [comment]
Why do you need 32-bit WIndows targets? Are there so many of them as targets for new development?

**Comment by msink** [comment]
WinXP is still in use, and will be long time. See #787 
Even WinCE is in use on embedded devices like GPS trackers.

**Comment by olonho** [comment]
Adding an additional platform imposes some overhead on us, but we're ready to consider external contribution of Windows/x86_32 support.  x86 Android and especially mobile Windows platforms are not something with significant market share, so we're not currently planning to support those.

**Comment by msink** [comment]
OK, thanks. But let's leave this issue open :)

**Comment by atsushieno** [comment]
Well, Android x86 target is real on emulators especially with HAXM enabled. It is something significant.

**Comment by akbcode** [comment]
Windows x86 is still an important target. Many cheap Windows tablets and convertibles sold in emerging markets have only 1GB or 2GB RAM. These devices ship with 32-bit version of Windows.

**Comment by vegansk** [comment]
My use case is that I'm searching for the language that allows me to create libraries from the same sources for the frontend (typescript), backend (scala), and for the legacy application (c++) for windows x86_32.

**Comment by damianw** [comment]
32-bit support is also necessary to support WatchOS - both x86 for the simulator and 32-bit ARM for the actual Apple Watch. I have an iOS project that I would like to integrate a kotlin-native framework into, but currently cannot because the core infrastructure, which would use the framework, is used by the project's WatchOS app.

**Comment by zaxebo1** [comment]
32 bit support is important even for "MS Windows Vista 32 bit Desktops" and "MS Windows 7 32 bit Desktops"

**Comment by zaxebo1** [comment]
@vegansk you can see haxe language https://en.wikipedia.org/wiki/Haxe#Compiler

**Comment by Dico200** [comment]
I've been doing some work with a compiled program on 32-bit x86, would love to start doing it in Kotlin.

**Comment by ferbeb** [comment]
I really liked the idea to replace native code with Kotlin Native, but not supporting Windows x86 makes it useless to me. What does this have to do with legacy 32bit operating systems? I'm looking to write a dynamic library plugin for an existing x86 application on Windows 10 x64 , obviously x64 .dll won't work.

**Comment by olonho** [comment]
Windows 32-bit is supported now. If 32-bit Linux is important with clear motivation for someone - please open a new issue.

**Comment by damianw** [comment]
@olonho Is 32-bit WatchOS already on the radar? Or should that be filed as a separate issue as well?

**Comment by olonho** [comment]
32-bit watchOS and Android will be available in 1.3.60.

**Comment by dmitrish** [comment]
@olonho  32 bit linux - yes please - for Tizen
