### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by aydin192** [JetBrains/kotlin-native#942]
Hi,

I am trying to make some changes to the source code of Kotlin-Native's compiler; The IDE I am currently use if VSCode; However it just provides me some very basic intellisense which is not enough at all. I am trying to work with instances of classes/interfaces like AnalyzerWithCompilerReport or ModuleDescriptor and finding methods and properties of these classes/interfaces is not very trivial.

I was wondering if there is a solution for this problem I don't know of. For example using another IDE with provide intellisense for Kotlin-Native code or something. What is the best setup for working on Kotlin-Native's compiler's source code?

Regards,
Aydin

**Comment by olonho** [comment]
I would suggest opening K/N compiler’s Gradle project with IntelliJ IDEA, if you do not have Ultimate, Community Edition would do as well.

**Comment by hhariri** [comment]
@aydin192 if you don't mind me asking, as I'm genuinely interested - had you heard of IntelliJ IDEA and that it provides Kotlin support, prior to @olonho response? I'm asking because I'm wondering if we're not getting the message out properly. 

Thanks.

**Comment by aydin192** [comment]
@hhariri Thanks for asking.  I think there are two issues here:

**1. An IDE for working with Kotlin-Native's compiler's source code:** This is my original question and didn't see any answer for it in the documentations; however I think there is no need for that as the answer is kinda obvious and I should have figured out that I should be able to develop the compiler part of the Kotlin-Native with Intellij IDEA as it is not in Kotlin-Native (I hope I am right!). Although it was worth questioning since I didn't know I have a free option - i.e. the community version of Intellij IDEA - for it too.

**2. An IDE for developing Kotlin-Native code:** I know about Intellij IDEA and its Kotlin support (Although I didn't know that the community version also supports Kotlin), however I still don't know if it supports Kotlin-Native; Maybe I am overthinking it but since the internals of JVM-Based Kotlin and Kotlin-Native are different, my feeling is that Intellij IDEA only supports JVM-based Kotlin and not the its native version.

I think either there is not message for the second issue or it has not delivered properly.

Regards,
Aydin
