### ISSUE TITLE
Calling Kotlin Function with String Parameter from C

### ISSUE THREAD

**Issue by aydin192** [JetBrains/kotlin-native#978]
Hi,

I have a Kotlin function like the following:
```
@ExportForCppRuntime
fun doThePrint(toPrint: String) {
    println(toPrint)
}
```
I want to call this function from C but I have no idea how to do that. For example I know that I cannot simply define an external function like this:
```
extern void doThePrint(char *);
```
in C and call it.

Is there a sample for this kind of function calls which involves strings or any other "pointer-based" data types?

Regards,
Aydin

**Comment by olonho** [comment]
There's no supported reverse interop: C -> Kotlin yet. Take a look at https://github.com/JetBrains/kotlin-native/blob/master/runtime/src/launcher/cpp/launcher.cpp#L47 but we're not intended to make this a stable API.

**Comment by aydin192** [comment]
Thanks @olonho.

As you know I am trying to achieve #898. Is it possible to give me a hint - ideally a code sample or sudo-code - on how I could call a Kotlin function which has a data class as a parameter from C? I am not looking for a general solution I just want to know what the approach is.

Thanks.

**Comment by olonho** [comment]
Don't think there's example of such a code for data class, however, as String is an object, code like 
in the link above shall work as well.

**Comment by cretz** [comment]
I too have this use case for JNI. I need to pass in a `JavaVM*` pointer to a Kotlin function and I see no way to do this with the current setup of generating the kt file from jni.h. Not with NativePtr, CPointer, CValuesRef, nothing.

An example of passing a C struct pointer to a Kotlin method would be ideal. https://blog.jetbrains.com/kotlin/2017/12/kotlinnative-v0-5-released-calling-kotlin-from-swift-and-c-llvm-5-and-more/ talks about calling Kotlin from C, but omits the obvious use case (the Python extension example only passes in non-primitives that originate from Kotlin). Is this the best issue to track this request or should a new one be created?

**Comment by cretz** [comment]
An update: I just [passed `Long`s](https://github.com/cretz/kotlin-native-sample-agent/blob/9e86054c20491e0f6e82e658a9a2a2db9f0d59bf/src/main/cpp/kotlin_bridge.cpp#L7) into [my function](https://github.com/cretz/kotlin-native-sample-agent/blob/9e86054c20491e0f6e82e658a9a2a2db9f0d59bf/src/main/kotlin/sampleagent/SampleAgent.kt#L13) and worked from there.

**Comment by olonho** [comment]
`-produce dynamic` allows automatic conversion of `String` as `const char*`.

**Comment by olonho** [comment]
Shall be working, please reopen if still relevant.

**Comment by norman784** [comment]
Whats the state of this? I'm currently facing an issue, cannot see the error message from a c library. This is the code generated by the compiler from the c library:

```
fun glfwSetErrorCallback(cbfun: GLFWerrorfun?): GLFWerrorfun? {
    return interpretCPointer<CFunction<(Int, CPointer<ByteVar>?) -> Unit>>(kniBridge4(cbfun.rawValue))
}
```

this is the c definition of the callback

```
typedef void(* GLFWerrorfun) (int, const char *)
```

Regards
