### ISSUE TITLE
"macbook" target question

### ISSUE THREAD

**Issue by Arcnor** [JetBrains/kotlin-native#987]
I'm not sure if this is the right place for questions but: Why is the OSX target called "macbook"? That sounds wrong, as a "MacBook" is the name of a single Apple product (a laptop that runs macOS) as opposed to the operating system itself (which should be "osx" with the old definition or "macos" with the new one).

So if this was a mistake, can it be changed to "macos" before it's too late?

**Comment by olonho** [comment]
We will consider adding other target aliases.
